-- =============================================================================
-- Studuel — Migration 230 : EMC Tle — LE PROGRAMME « LA DÉMOCRATIE »
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 230 --modules emc-tle
--
-- CONSTAT MESURÉ (sonde en lecture seule sur la base, 05/08/2026) :
-- l'EMC de Terminale n'avait que les 3 chapitres du socle lycée, écrits pour
-- la 2de, la 1re et la Tle à la fois. Le programme propre à la Terminale — « La
-- démocratie », ses deux axes et ses douze fiches — n'existait nulle part : ni
-- l'histoire de la démocratie, ni les modes de scrutin, ni la laïcité, ni
-- l'exemplarité des élus, ni les nouvelles formes de participation.
-- Cette migration AJOUTE 12 fiches derrière les 3 existantes, qui restent en
-- place : elles valent pour les trois niveaux du lycée, pas seulement pour la
-- Terminale.
--
-- Cette migration apporte : 12 chapitres, 12 leçons,
-- 12 quiz et 96 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position)
SELECT v.id, s.id, v.level, v.title, v.position
  FROM (VALUES
    ('99b79047-e0f8-53b6-83fd-381be01e0b49'::uuid, 'emc', 'Tle', 'Histoire de la démocratie', 4),
    ('1931e51c-4c88-52ef-9010-23dbb5ab8c18'::uuid, 'emc', 'Tle', 'La démocratie et le peuple souverain', 5),
    ('7d109bc2-6e82-532e-9de3-c30f86ea3f10'::uuid, 'emc', 'Tle', 'Les élections, outils de la démocratie', 6),
    ('641f8e0c-90af-5906-ac50-cf422583d8f6'::uuid, 'emc', 'Tle', 'Laïcité et démocratie', 7),
    ('f0fceaa8-f97d-54e9-bae4-ddbc1d986fef'::uuid, 'emc', 'Tle', 'Contestation de la démocratie et transformations des régimes politiques', 8),
    ('6c15ed54-8224-5b00-aa3a-6633c033438f'::uuid, 'emc', 'Tle', 'La protection des démocraties : les enjeux de sécurité', 9),
    ('0bc662bf-07ba-53e4-adfd-80b941138600'::uuid, 'emc', 'Tle', 'La construction européenne et la démocratie', 10),
    ('f5603d8e-b51e-575d-972d-d394d398e3e3'::uuid, 'emc', 'Tle', 'Faire vivre le débat dans une démocratie', 11),
    ('c91ea828-7673-5b40-98ad-8ed2976eb1f6'::uuid, 'emc', 'Tle', 'Le modèle démocratique en question : exemplarité et transparence', 12),
    ('74108697-0023-55b8-9f75-0a0b446af663'::uuid, 'emc', 'Tle', 'S’engager dans la démocratie au XXIe siècle', 13),
    ('34cd15f2-3c74-5a00-8766-4e7e008e7141'::uuid, 'emc', 'Tle', 'Nouvelles aspirations démocratiques', 14),
    ('ef694fa8-7d90-5ff2-ae9c-3e4fffb85c71'::uuid, 'emc', 'Tle', 'Conscience démocratique et relations internationales', 15)
  ) AS v(id, slug, level, title, position)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('030c34ca-eace-588c-8acc-a65b2d10d987', '99b79047-e0f8-53b6-83fd-381be01e0b49', 'D’Athènes au suffrage universel', E'La démocratie n’est ni une invention récente ni une évidence : c’est un régime **rare**, longtemps minoritaire, et toujours **réversible**.\n\n## Athènes, Ve siècle avant J.-C.\nLa démocratie athénienne est **directe** : les citoyens votent eux-mêmes les lois à l’**ecclésia**, et la plupart des magistrats sont **tirés au sort**.\n\n| Groupe | Effectif approximatif | Droits politiques |\n| Citoyens | environ **40 000** | Tous |\n| Femmes, **métèques**, **esclaves** | le reste des ~300 000 habitants | Aucun |\n\n> Deux enseignements durables. D’abord, la démocratie suppose un peuple **défini** — la première question est toujours « qui en fait partie ? ». Ensuite, le **tirage au sort** est aussi démocratique que l’élection : l’élection, disait Aristote, est plutôt **aristocratique**, puisqu’elle désigne les meilleurs.\n\n## Les jalons\n| Date | L’étape | Ce qu’elle apporte |\n| **1215** | *Magna Carta* | Limite le pouvoir du roi d’Angleterre |\n| **1688-1689** | Glorieuse Révolution, *Bill of Rights* | Installe la monarchie parlementaire |\n| **1776** | Déclaration d’indépendance américaine | Le droit de se donner un gouvernement |\n| **1787** | Constitution des États-Unis | La séparation des pouvoirs écrite |\n| **1789** | Révolution française, **DDHC** | Les droits comme fondement du régime |\n\n## L’élargissement du corps électoral\nLe suffrage reste longtemps **censitaire** — réservé aux plus imposés.\n\n| Date | L’extension en France |\n| **1848** | Suffrage universel **masculin** |\n| **1944** | Droit de vote des **femmes** (premier vote en 1945) |\n| **1974** | Majorité abaissée à **18 ans** |\n\n## Les vagues de démocratisation\nLe politiste **Samuel Huntington** décrit trois vagues.\n\n| Vague | Période | Exemples |\n| Première | XIXe et début du XXe siècle | Europe occidentale, Amérique du Nord |\n| Deuxième | Après 1945 | Reconstruction, décolonisation |\n| Troisième | À partir de 1974 | Portugal, Espagne, Grèce, Amérique latine, Europe de l’Est après 1989 |\n\nChaque vague a été suivie d’un **reflux** — d’où l’attention portée aujourd’hui aux reculs démocratiques.', 1),
  ('e2a5ec32-a8d1-5ab5-8113-fce2e84c3679', '1931e51c-4c88-52ef-9010-23dbb5ab8c18', 'Qui décide, et au nom de qui', E'« Gouvernement du peuple, par le peuple et pour le peuple » : la formule de Lincoln, reprise à l’**article 2 de la Constitution de 1958**, cache une question difficile — comment un peuple entier peut-il gouverner ?\n\n## Deux conceptions de la souveraineté\n| | Souveraineté **populaire** | Souveraineté **nationale** |\n| Le théoricien | **Rousseau** | **Sieyès** |\n| À qui elle appartient | Au peuple, somme des citoyens | À la Nation, entité abstraite |\n| Chacun en détient | Une part | Rien : elle est indivisible |\n| Le mandat | **Impératif** : l’élu obéit à ses électeurs | **Représentatif** : l’élu décide librement |\n| La forme logique | Démocratie directe | Démocratie représentative |\n\nLa Constitution française **combine** les deux : « La souveraineté nationale appartient au peuple qui l’exerce par ses représentants et par la voie du référendum. »\n\n## Trois formes de démocratie\n| Forme | Qui décide | Exemples |\n| **Directe** | Le peuple lui-même | Référendum, votations suisses |\n| **Représentative** | Ceux qu’il élit | Le régime français ordinaire |\n| **Participative** | Le peuple est associé sans trancher | Concertations, conventions citoyennes, budgets participatifs |\n\n## Les garanties du régime\n| Garantie | Ce qu’elle empêche |\n| **Séparation des pouvoirs** (Montesquieu) | Qu’un organe décide et juge à la fois |\n| **État de droit** | Que les gouvernants s’exemptent de la loi |\n| Hiérarchie des normes contrôlée | Qu’une loi viole la Constitution — **QPC** depuis 2010 |\n| **Droits fondamentaux** | Que la majorité décide de tout |\n\n> Point de vigilance pour une copie : la démocratie n’est **pas seulement** la règle de la majorité. Une majorité qui supprimerait les droits d’une minorité détruirait la démocratie tout en respectant la règle du nombre.', 1),
  ('f14baef7-8aba-584e-8db0-35d0efa8d25f', '7d109bc2-6e82-532e-9de3-c30f86ea3f10', 'Le vote, et ce qu’il produit', E'L’élection est l’acte démocratique le plus visible. Mais le **mode de scrutin** choisi façonne le résultat autant que les votes eux-mêmes.\n\n## Les principes du vote\n| Principe | Ce qu’il signifie | En France |\n| **Universel** | Tous les citoyens majeurs votent | Depuis 1944 pour les femmes |\n| **Égal** | Une personne, une voix | Oui |\n| **Secret** | L’isoloir est obligatoire | Oui |\n| **Libre** | Voter n’est pas obligatoire | Oui — à la différence de la Belgique ou de l’Australie |\n| **Direct ou indirect** | Les électeurs désignent l’élu, ou des grands électeurs | Indirect pour le **Sénat** |\n\n## Les modes de scrutin, et leurs effets\n| Mode | Ce qu’il produit | Ce qu’il coûte |\n| **Majoritaire à deux tours** | Des majorités nettes, un lien fort avec la circonscription | Il **sous-représente** les courants minoritaires |\n| **Proportionnel** | Une image fidèle de l’opinion | Des assemblées fragmentées, des coalitions instables |\n| **Mixte** | Une prime majoritaire ajoutée à la proportionnelle | Un compromis, jamais parfait |\n\n> Il n’existe **aucun** mode de scrutin neutre. Choisir entre représentativité et gouvernabilité est un **choix politique**, pas une question technique — et c’est pourquoi la réforme du mode de scrutin est un débat permanent.\n\n## L’abstention, principal enjeu contemporain\n| Phénomène | Ce qu’il produit |\n| Abstention | Plus de la moitié des inscrits aux dernières législatives, davantage chez les jeunes et les catégories populaires |\n| **Mal-inscription** | On est inscrit ailleurs que là où l’on vit |\n| Non-inscription | On n’est pas sur les listes du tout |\n\nUn élu peut ainsi être désigné par une **fraction réduite** du corps électoral — ce qui alimente la contestation de sa **légitimité**, distincte de sa légalité.\n\n## Le contrôle\n| Dispositif | Ce qu’il encadre |\n| Plafonnement des dépenses | Le coût des campagnes |\n| **CNCCFP** | Le contrôle des comptes de campagne |\n| **Arcom** | L’égalité du temps de parole |\n| Financement public des partis | Leur indépendance vis-à-vis des donateurs |\n| Le juge de l’élection | Il peut annuler un scrutin irrégulier |', 1),
  ('60366097-aec5-5a61-bbc6-13396adb5cda', '641f8e0c-90af-5906-ac50-cf422583d8f6', 'Ce que la laïcité oblige, et ce qu’elle n’interdit pas', E'La laïcité est l’un des principes les plus mal compris du droit français. Elle ne dit rien des croyances : elle organise le rapport entre l’**État** et les **cultes**.\n\n## La loi de 1905\nLa loi du **9 décembre 1905** tient dans deux articles fondateurs.\n\n| Article | Ce qu’il pose |\n| Article 1er | « La République **assure la liberté de conscience**. Elle **garantit le libre exercice des cultes**. » |\n| Article 2 | « La République **ne reconnaît, ne salarie ni ne subventionne** aucun culte. » |\n\nAutrement dit : **liberté** de croire ou de ne pas croire, et **neutralité** de l’État.\n\n## À qui s’applique la neutralité\n| Concerné | La règle |\n| Les **agents publics** dans l’exercice de leurs fonctions | Ils ne peuvent manifester leur religion |\n| Les bâtiments et services publics | Ils n’affichent aucun culte |\n| Les **usagers** dans l’espace public | **Ils sont libres** : un particulier peut porter un signe religieux dans la rue |\n\n| L’exception légale | Le texte |\n| Signes religieux ostensibles à l’école publique | **Loi de 2004** |\n| Dissimulation du visage dans l’espace public | **Loi de 2010** — motifs d’ordre public et de sécurité |\n| Neutralité étendue aux missions de service public | **Loi du 24 août 2021** |\n\n## Deux confusions à éviter\n| La confusion | La correction |\n| Laïcité = athéisme | L’État n’est **pas contre** les religions : il est **neutre** entre elles |\n| Critiquer une religion = délit | Le **blasphème n’existe pas** en droit français |\n\n> La ligne de partage est précise : les **idées** sont critiquables, y compris durement ; les **personnes** sont protégées. L’injure et l’incitation à la haine visant des personnes en raison de leur religion sont punies — pas la critique d’un dogme.\n\n## Un cas particulier assumé\nL’**Alsace-Moselle**, annexée à l’Empire allemand en 1905, n’a jamais reçu la loi de séparation : elle conserve le régime concordataire, où des cultes sont salariés par l’État.', 1),
  ('8691dd0d-327e-5aaf-bb73-f5afbca72f9d', 'f0fceaa8-f97d-54e9-bae4-ddbc1d986fef', 'Quand la démocratie recule', E'Depuis une quinzaine d’années, les grands indices — **V-Dem**, **Freedom House**, *Democracy Index* — constatent la même chose : le nombre de démocraties **recule**, et la population vivant sous régime autoritaire progresse.\n\n## Les régimes non démocratiques\n| | **Autoritaire** | **Totalitaire** |\n| Ce que le pouvoir contrôle | L’État et la vie politique | La **société entière** |\n| L’opposition | Entravée | Supprimée |\n| La société civile | Garde des espaces d’autonomie | N’en garde aucun |\n| Les moyens | Répression ciblée | Idéologie officielle, parti unique, terreur organisée |\n\n## La forme nouvelle : la démocratie illibérale\nLe régime conserve les **apparences** — élections tenues, Parlement en place — mais vide les contre-pouvoirs de leur substance.\n\n| L’apparence conservée | La substance vidée |\n| Des élections ont lieu | Découpage électoral sur mesure, médias rachetés |\n| Une justice existe | Elle est mise sous tutelle |\n| La presse n’est pas interdite | Elle est étouffée économiquement |\n| Les associations sont légales | Elles sont harcelées administrativement |\n\nLa **Hongrie** en est l’exemple le plus discuté en Europe ; la **Turquie** un autre cas fréquemment cité.\n\n> Le point décisif : on ne renverse plus une démocratie par un **coup d’État militaire**, on la **vide de l’intérieur** en respectant les formes. C’est ce qui rend le recul difficile à dater — et difficile à contester, puisque chaque étape est légale.\n\n## Ce qui alimente la contestation\n| Facteur | Comment il agit |\n| La **défiance** | Envers les élus et les institutions |\n| Le sentiment d’inutilité du vote | Abstention, votes protestataires |\n| Les **inégalités** | Déclassement, sentiment d’abandon |\n| La **désinformation** | Fragmentation de l’espace informationnel |\n| Un modèle alternatif revendiqué | La Chine met en avant l’efficacité contre le pluralisme |\n\n## Ce qui résiste\nDes institutions indépendantes, une presse pluraliste, des contre-pouvoirs locaux, une société civile organisée — et l’**alternance** effective. La résilience démocratique se mesure moins aux textes qu’à l’existence **réelle** de ces contre-pouvoirs.', 1),
  ('fc67cbaf-46c3-5b28-bf77-78e73c0bb4be', '6c15ed54-8224-5b00-aa3a-6633c033438f', 'Protéger sans détruire ce qu’on protège', E'Une démocratie doit assurer la sécurité de ses citoyens **sans sacrifier les libertés qui la définissent**. Tout le sujet tient dans cet équilibre.\n\n## Les menaces\n| Menace | Ce qu’elle vise |\n| Le **terrorisme** | *Charlie Hebdo* et l’Hyper Cacher (janvier 2015), le 13 novembre 2015, Nice (juillet 2016) |\n| Les **cyberattaques** | Hôpitaux, collectivités, entreprises |\n| Les **ingérences étrangères** | Manipulation de l’information, financement occulte, influence électorale |\n| La criminalité organisée | Trafics, blanchiment |\n\n## Les réponses françaises\n| Dispositif | Date | Ce qu’il permet | Qui décide |\n| **État d’urgence** | Novembre 2015, prolongé jusqu’en 2017 | Perquisitions administratives, assignations à résidence | L’**administration**, pas un juge |\n| **Loi SILT** | 2017 | Fait passer ces mesures dans le droit commun | Sous contrôle du juge administratif |\n| **Loi renseignement** | 2015 | Encadre — et élargit — les techniques de surveillance | Contrôle par la **CNCTR** |\n\n## Les garde-fous\n| Garde-fou | Son rôle |\n| Le **juge** administratif ou judiciaire | Contrôler la proportionnalité des mesures |\n| Le **Conseil constitutionnel** | Il a censuré plusieurs dispositions jugées excessives |\n| La **CNIL** | Protéger les données personnelles |\n| La **CEDH** | Un recours externe, à Strasbourg |\n| Le **Parlement** | Limiter dans le temps les régimes d’exception |\n\n## Le raisonnement attendu au bac\nUne mesure de sécurité s’apprécie à **trois critères**, et il faut les poser tous les trois :\n\n1. Est-elle **nécessaire** — répond-elle à une menace établie ?\n2. Est-elle **proportionnée** — n’existe-t-il pas de moyen moins attentatoire ?\n3. Est-elle **contrôlée** — un juge peut-il la censurer ?\n\n> Une mesure d’exception qui devient **permanente** et qui **échappe au contrôle** ne protège plus la démocratie : elle en change la nature.', 1),
  ('523b1afb-6ff6-5a45-ba89-a7fcef3b1f7d', '0bc662bf-07ba-53e4-adfd-80b941138600', 'L’Europe, contrainte et garantie démocratique', E'L’Union européenne n’est pas seulement un marché : c’est une **communauté de valeurs** qui conditionne l’adhésion et, de plus en plus, le versement des fonds.\n\n## L’exigence démocratique\nLes **critères de Copenhague (1993)** subordonnent l’adhésion à des « institutions stables garantissant la démocratie, l’État de droit, les droits de l’homme et la protection des minorités ».\n\n| Pays | Ce que l’adhésion a ancré |\n| Espagne, Portugal, Grèce | La sortie de dictature, dans les années 1980 |\n| Europe centrale et orientale | La transition post-communiste, après 1989 |\n\n| Instrument | Ce qu’il permet | Sa limite |\n| **Article 2 du TUE** | Énonce les valeurs communes | Déclaratif |\n| **Article 7** | Sanctionner un État qui s’en écarte, jusqu’à suspendre son droit de vote | L’**unanimité** requise le rend presque inapplicable |\n| **Conditionnalité budgétaire** (2020) | Suspendre les fonds en cas d’atteinte à l’État de droit | Elle, elle a été utilisée |\n\n## Les institutions et la question démocratique\n| Institution | Sa légitimité | Ce qu’on lui reproche |\n| **Parlement européen** | Élu au suffrage universel direct **depuis 1979** | Une participation faible aux européennes |\n| **Conseil** | Réunit des gouvernements élus | La responsabilité est diluée |\n| **Commission** | Investie par le Parlement | **Non élue**, et détient l’initiative législative |\n| **CJUE** | Fait respecter le droit de l’Union | Accusée de gouverner par la jurisprudence |\n\nLa **Charte des droits fondamentaux** a valeur contraignante depuis **2009**.\n\n## La participation citoyenne\n| Dispositif | Ce qu’il permet |\n| **Initiative citoyenne européenne** | Un million de citoyens d’au moins sept États demandent à la Commission de légiférer |\n| **Conférence sur l’avenir de l’Europe** (2021-2022) | Des panels de citoyens tirés au sort |\n\n## Le débat, honnêtement posé\n> Ceux qui parlent de **déficit démocratique** pointent une machine lointaine et technique, où la responsabilité se dilue. Ceux qui le contestent rappellent que chaque décision est prise soit par des députés élus, soit par des gouvernements responsables devant leurs Parlements. Les deux arguments sont recevables : c’est la **lisibilité** du système, plus que sa légitimité formelle, qui fait problème.', 1),
  ('420289ad-10d5-5d06-a933-8037d57aab39', 'f5603d8e-b51e-575d-972d-d394d398e3e3', 'Argumenter, écouter, se contredire', E'Une démocratie ne tient pas seulement par ses institutions : elle tient par la **qualité de son débat**. Or celle-ci n’a rien de spontané.\n\n## Débat n’est pas dispute\n| | Débattre | Se disputer |\n| Ce qu’on avance | Des raisons et des faits vérifiables | Des affirmations |\n| Ce qu’on fait de l’objection | On l’écoute, on la prend au sérieux | On l’ignore ou on la ridiculise |\n| Ce qu’on attaque | L’**idée** | La **personne** |\n| Ce qu’on cherche | Ce qui est vrai | À avoir raison |\n\n> Dans un débat démocratique, le **désaccord argumenté est productif** : il oblige chacun à préciser sa position. C’est le désaccord non argumenté qui stérilise.\n\n## L’espace public\nLe philosophe **Habermas** appelle *espace public* le lieu où les citoyens discutent des affaires communes : autrefois la presse, les cafés, les partis ; aujourd’hui, principalement, les médias et les **réseaux sociaux**.\n\n| La difficulté | Ce qu’elle produit |\n| La **concentration** des médias | Une question de pluralisme |\n| Les **algorithmes** de recommandation | Bulles de filtre, chambres d’écho : on voit ce qui confirme et ce qui indigne |\n| La **désinformation** | Elle circule plus vite que sa correction |\n| L’anonymat et le harcèlement | Ils font taire |\n\n## Les réponses\n| Réponse | Ce qu’elle vise |\n| **Éducation aux médias et à l’information** | Former le lecteur, inscrite dans les programmes |\n| Règles de pluralisme (Arcom) | Garantir les temps de parole |\n| *Fact-checking*, règlement européen sur les services numériques | Responsabiliser les plateformes |\n| Débat organisé | CNDP, enquêtes publiques, **conventions citoyennes** — 150 citoyens tirés au sort pour celle sur le climat |\n\n## Ce qu’on attend de toi\n1. **Construire** un argument : thèse, raison, exemple.\n2. **Repérer un sophisme** : attaque personnelle, faux dilemme, généralisation abusive.\n3. **Vérifier** une source.\n4. **Exposer honnêtement** la position adverse **avant** de la discuter.', 1),
  ('3dc78f98-93ce-57b9-99de-71322b02d948', 'c91ea828-7673-5b40-98ad-8ed2976eb1f6', 'Ce qu’on exige désormais des élus', E'La défiance envers les responsables politiques est devenue un fait durable des démocraties. La réponse construite depuis dix ans tient en deux mots : **transparence** et **exemplarité**.\n\n## Le tournant de 2013\nL’affaire Cahuzac — un ministre du Budget mentant sur un compte à l’étranger — provoque une réforme d’ampleur.\n\n| L’institution créée | Ce qu’elle contrôle |\n| La **HATVP** | Les **déclarations de patrimoine** et les **déclarations d’intérêts** de milliers de responsables publics, publiées pour certains |\n\n## Les lois de 2017\n| La mesure | Ce qu’elle interdit ou impose |\n| Emplois familiaux | Interdits aux parlementaires |\n| Réserve parlementaire | Supprimée |\n| Frais de mandat | Encadrés et justifiés |\n| Casier judiciaire | Doit être compatible avec l’exercice d’un mandat |\n| **Non-cumul** | Entre un mandat parlementaire et un exécutif local |\n\n## Encadrer l’influence\n| Notion | Sa définition | L’obligation |\n| **Représentant d’intérêts** | Un lobbyiste | S’inscrire au répertoire public de la HATVP et déclarer ses actions |\n| **Conflit d’intérêts** | Une situation où un intérêt privé peut influencer une fonction publique | Le déclarer, et se **déporter** |\n\n## Protéger ceux qui alertent\n| Texte | Ce qu’il apporte |\n| **Loi Sapin II** (2016) | Premier statut du **lanceur d’alerte** |\n| **Loi de 2022** | Transpose la directive européenne de 2019 : protection contre les représailles, procédure de signalement clarifiée |\n\n## Contrôler l’argent public\nLa **Cour des comptes** contrôle l’emploi des fonds publics et publie ses rapports ; les données publiques sont diffusées en **open data** ; les marchés publics sont encadrés.\n\n> À nuancer, comme toujours : la transparence **n’est pas la vertu**. Elle rend le contrôle possible, elle ne le garantit pas — et poussée à l’extrême, elle peut se retourner en défiance permanente, ou en surveillance de la vie privée des élus.', 1),
  ('e2b4310e-5785-5568-b9eb-09fe79d67959', '74108697-0023-55b8-9f75-0a0b446af663', 'Voter n’est pas la seule façon d’agir', E'L’engagement ne disparaît pas : il **change de forme**. Le militantisme de long terme recule, l’engagement ponctuel, concret et choisi progresse.\n\n## Les formes classiques\n| Forme | Son état en France |\n| Le **vote** | Premier acte civique, mais en recul |\n| Les **partis politiques** | Effectifs fortement diminués |\n| Les **syndicats** | Taux de syndicalisation autour de **10 %**, l’un des plus faibles d’Europe — alors que la couverture des accords collectifs y est l’une des plus élevées |\n| Les **associations** | Plus d’**un million**, environ **20 millions de bénévoles** : la première forme d’engagement du pays |\n\n## Les formes nouvelles\n| Forme | Ce qu’elle est |\n| Pétitions en ligne, campagnes sur les réseaux | Une mobilisation rapide, sans organisation |\n| **Consommation engagée** | Boycott, achat responsable |\n| **Désobéissance civile** | Violation **publique, assumée et non violente** d’une règle jugée injuste, en acceptant la sanction — Thoreau, Gandhi, King |\n| **Service civique** (depuis 2010) | Ouvert aux 16-25 ans, plusieurs centaines de milliers de missions |\n| Engagement local | Conseils de quartier, conseils municipaux de jeunes, budgets participatifs |\n\n## Les limites à connaître\n| Le risque | Ce qui le distingue d’un vrai engagement |\n| Le « **slacktivisme** » | Un clic qui donne le sentiment d’agir, sans coût ni effet |\n| À l’inverse | Une pétition massive peut porter un sujet jusqu’au Parlement |\n\n> Ce qui sépare les deux : la **continuité** de l’action et son **ancrage** dans une organisation. Un geste isolé n’est pas un engagement, même s’il est sincère.\n\n## Ce que le programme te demande\nIdentifier une cause, choisir une forme d’action **proportionnée et légale**, en mesurer les effets — et savoir distinguer l’**engagement**, qui vise l’intérêt général, de la simple expression d’une opinion.', 1),
  ('7609367e-c6eb-5242-ba38-c0de48eeaff4', '34cd15f2-3c74-5a00-8766-4e7e008e7141', 'Délibérer, tirer au sort, associer', E'À côté du vote, de nouvelles pratiques cherchent à associer les citoyens **entre** deux élections. Elles ne remplacent pas la démocratie représentative : elles la complètent — et la mettent sous tension.\n\n## La démocratie délibérative\nSon pari : une décision est meilleure et plus légitime si elle est précédée d’une **délibération informée**.\n\n| Dispositif | Date | Ce qu’il a produit |\n| Convention citoyenne pour le **climat** | 2019-2020 | 149 propositions, reprises très partiellement |\n| Convention sur la **fin de vie** | 2022-2023 | Un avis favorable à une aide active à mourir |\n| Panels européens | Depuis 2021 | Des recommandations à la Commission |\n\nLe **tirage au sort** revient ainsi dans le débat.\n\n| Ce qu’il apporte | Ce qui lui manque |\n| Une diversité sociale que l’élection ne produit pas | Un **mandat** : personne n’a voté pour ces citoyens |\n\nD’où la question, toujours ouverte : **que fait-on des propositions ?**\n\n## La démocratie participative locale\n| Dispositif | Ce qu’il permet |\n| **Budgets participatifs** | Les habitants affectent une part du budget municipal |\n| Conseils de quartier, jurys citoyens | Un avis organisé sur les projets |\n| **Enquêtes publiques** et **CNDP** | Un débat obligatoire avant les grands aménagements |\n\n## Les demandes plus radicales\nLe **référendum d’initiative citoyenne (RIC)** est réclamé notamment depuis le mouvement des Gilets jaunes. Le droit français ne connaît que le **référendum d’initiative partagée** (2008).\n\n| Seuil du RIP | Valeur |\n| Parlementaires signataires | Un **cinquième** |\n| Électeurs signataires | Un **dixième**, soit environ **4,8 millions** |\n| Fois où la procédure est allée à son terme | **Aucune** |\n\n## Les nouveaux objets du débat\n| Objet | Ce qui l’encadre |\n| **Démocratie environnementale** | La **Charte de l’environnement**, adossée à la Constitution en **2005** : droit à l’information et à la participation |\n| Droits des **générations futures** | Invoqués dans les contentieux climatiques |\n| **Transparence des algorithmes** | Ceux utilisés par l’administration |\n| *Civic tech* | Consulter par le numérique — au risque de consultations sans suite |\n\n> La question qui traverse tout le chapitre : associer davantage les citoyens **renforce** la démocratie si les décisions en tiennent compte. Sinon, chaque consultation sans effet **aggrave** la défiance qu’elle prétendait réduire.', 1),
  ('3bb5de61-33af-5a2a-a235-f55029c36f46', 'ef694fa8-7d90-5ff2-ae9c-3e4fffb85c71', 'Des droits universels, un monde d’États souverains', E'Depuis 1945, un ordre juridique international proclame des droits **universels**. Il se heurte en permanence à un principe aussi fort : la **souveraineté** des États.\n\n## Les textes fondateurs\n| Texte | Date | Force contraignante |\n| **Déclaration universelle des droits de l’homme** | 1948 | **Aucune** — mais une référence morale et juridique universelle |\n| **Convention européenne des droits de l’homme** | 1950 | **Oui** : la CEDH peut condamner un État sur requête d’un simple individu |\n| Pactes internationaux | 1966 | Oui, avec un contrôle faible |\n| Convention des droits de l’enfant | 1989 | Oui |\n\n## La justice pénale internationale\nLa **Cour pénale internationale** — statut de Rome, **1998**, en vigueur **2002** — juge des **individus**, et non des États.\n\n| Ce qu’elle juge | Ses limites |\n| Génocide | Les États-Unis, la Chine, la Russie et l’Inde n’ont pas ratifié |\n| Crimes contre l’humanité | Elle dépend des États pour arrêter les personnes recherchées |\n| Crimes de guerre, crime d’agression | Ses procédures sont longues |\n\n## Intervenir ou non\n| Notion | Ce qu’elle pose | Ce qui la bloque |\n| **Droit d’ingérence** | Une communauté internationale peut intervenir | Il n’a jamais eu de base juridique claire |\n| **Responsabilité de protéger** (ONU, 2005) | Un État qui massacre sa population perd la protection de sa souveraineté | Son application dépend du **Conseil de sécurité**, où cinq membres ont le **veto** |\n\nC’est ce veto qui a bloqué l’action sur la Syrie comme sur d’autres crises.\n\n## Les acteurs non étatiques\nLes **ONG** — Amnesty International, Human Rights Watch, Médecins sans frontières, Reporters sans frontières — documentent, alertent, plaident.\n\n> Leur pouvoir est celui de la **preuve** et de l’**opinion**. Elles n’ont aucune force contraignante, mais leurs rapports pèsent sur les décisions et les réputations : c’est une puissance sans moyens de coercition.\n\n## Le débat honnête\n| L’argument | Ce qu’il rappelle |\n| Les réussites | L’élargissement européen a ancré des démocraties |\n| Les échecs | Là où elle a été **imposée par la force**, la démocratie n’a pas pris |\n| Le reproche | Le « **deux poids, deux mesures** » adressé aux puissances occidentales |\n\nCe que le programme attend : comprendre que la conscience démocratique **ne s’arrête pas aux frontières**, tout en mesurant ce qui limite son application — souveraineté, veto, rapports de force.', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('366b29bc-3e55-5737-b8e6-5efb48978a1b'::uuid, 'Quiz — D’Athènes au suffrage universel', 'EMC', 'Tle', 'Histoire de la démocratie', '030c34ca-eace-588c-8acc-a65b2d10d987'::uuid),
    ('47d321eb-be02-5d0e-a478-b85a96ad7891'::uuid, 'Quiz — Qui décide, et au nom de qui', 'EMC', 'Tle', 'La démocratie et le peuple souverain', 'e2a5ec32-a8d1-5ab5-8113-fce2e84c3679'::uuid),
    ('4a1655d9-9854-5b40-b0e4-0b328714fa00'::uuid, 'Quiz — Le vote, et ce qu’il produit', 'EMC', 'Tle', 'Les élections, outils de la démocratie', 'f14baef7-8aba-584e-8db0-35d0efa8d25f'::uuid),
    ('01fa116c-aafb-5de6-85f3-3b048b920095'::uuid, 'Quiz — Ce que la laïcité oblige, et ce qu’elle n’interdit pas', 'EMC', 'Tle', 'Laïcité et démocratie', '60366097-aec5-5a61-bbc6-13396adb5cda'::uuid),
    ('7ba5f44a-33d1-5239-9a2b-1f0c2071fd87'::uuid, 'Quiz — Quand la démocratie recule', 'EMC', 'Tle', 'Contestation de la démocratie et transformations des régimes politiques', '8691dd0d-327e-5aaf-bb73-f5afbca72f9d'::uuid),
    ('63242696-e242-5d50-aa38-ddf83d2d6406'::uuid, 'Quiz — Protéger sans détruire ce qu’on protège', 'EMC', 'Tle', 'La protection des démocraties : les enjeux de sécurité', 'fc67cbaf-46c3-5b28-bf77-78e73c0bb4be'::uuid),
    ('ab62d378-6e83-5da1-841c-7bb0adfee22b'::uuid, 'Quiz — L’Europe, contrainte et garantie démocratique', 'EMC', 'Tle', 'La construction européenne et la démocratie', '523b1afb-6ff6-5a45-ba89-a7fcef3b1f7d'::uuid),
    ('a8828cf1-043c-5e6e-923f-31acc0842688'::uuid, 'Quiz — Argumenter, écouter, se contredire', 'EMC', 'Tle', 'Faire vivre le débat dans une démocratie', '420289ad-10d5-5d06-a933-8037d57aab39'::uuid),
    ('5661509d-9cdb-5b6c-a454-1f66ae120c85'::uuid, 'Quiz — Ce qu’on exige désormais des élus', 'EMC', 'Tle', 'Le modèle démocratique en question : exemplarité et transparence', '3dc78f98-93ce-57b9-99de-71322b02d948'::uuid),
    ('85740ba6-faa2-5ec0-913a-f73b774871e5'::uuid, 'Quiz — Voter n’est pas la seule façon d’agir', 'EMC', 'Tle', 'S’engager dans la démocratie au XXIe siècle', 'e2b4310e-5785-5568-b9eb-09fe79d67959'::uuid),
    ('f43e1a78-519c-54ef-8387-2ac618634468'::uuid, 'Quiz — Délibérer, tirer au sort, associer', 'EMC', 'Tle', 'Nouvelles aspirations démocratiques', '7609367e-c6eb-5242-ba38-c0de48eeaff4'::uuid),
    ('4679ad72-acaa-5706-a891-a506c6b909be'::uuid, 'Quiz — Des droits universels, un monde d’États souverains', 'EMC', 'Tle', 'Conscience démocratique et relations internationales', '3bb5de61-33af-5a2a-a235-f55029c36f46'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('241d8d63-475b-5c6d-b637-4749d7dc82cf'::uuid, '366b29bc-3e55-5737-b8e6-5efb48978a1b'::uuid, 'Comment étaient désignés la plupart des magistrats à Athènes ?', 'mcq', '["Par tirage au sort","Par élection au suffrage universel","Par hérédité","Par cooptation des riches"]'::jsonb, 0, 'Aristote jugeait l’élection plutôt aristocratique, et le tirage au sort démocratique.', 1),
    ('747c362c-86cc-5972-8775-23c7ce735b98'::uuid, '366b29bc-3e55-5737-b8e6-5efb48978a1b'::uuid, 'Qui était exclu de la citoyenneté à Athènes ?', 'mcq', '["Les femmes, les métèques et les esclaves","Seulement les esclaves","Seulement les étrangers","Les artisans et les paysans"]'::jsonb, 0, 'Environ 40 000 citoyens pour peut-être 300 000 habitants.', 2),
    ('89249b08-4dbb-5f61-be48-e1c71bd5686f'::uuid, '366b29bc-3e55-5737-b8e6-5efb48978a1b'::uuid, 'Quand les femmes obtiennent-elles le droit de vote en France ?', 'mcq', '["En 1944","En 1848","En 1918","En 1965"]'::jsonb, 0, 'Ordonnance de 1944, premier vote effectif en 1945.', 3),
    ('a0185759-e4fa-5cad-b0f0-8ae2459d9760'::uuid, '366b29bc-3e55-5737-b8e6-5efb48978a1b'::uuid, 'Le suffrage universel masculin est instauré en France en…', 'mcq', '["1848","1789","1875","1830"]'::jsonb, 0, 'Il met fin au suffrage censitaire, réservé aux plus imposés.', 4),
    ('6a00dda2-8ec0-54be-b6e7-73162c04d7f0'::uuid, '366b29bc-3e55-5737-b8e6-5efb48978a1b'::uuid, 'Qu’est-ce qu’un suffrage censitaire ?', 'mcq', '["Un droit de vote réservé à ceux qui paient un certain impôt","Un vote par recensement de la population","Un vote obligatoire","Un scrutin indirect"]'::jsonb, 0, 'Il a longtemps réduit le corps électoral à une minorité de propriétaires.', 5),
    ('ddb42121-c1e5-553d-917d-46e3022ef980'::uuid, '366b29bc-3e55-5737-b8e6-5efb48978a1b'::uuid, 'La démocratie athénienne était une démocratie représentative.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle était directe : les citoyens votaient eux-mêmes les lois à l’ecclésia.', 6),
    ('de077dd0-c2af-56d3-9b75-7b912973e551'::uuid, '366b29bc-3e55-5737-b8e6-5efb48978a1b'::uuid, 'Quel texte anglais de 1215 limite le pouvoir du roi ?', 'mcq', '["La Magna Carta","Le Bill of Rights","L’Habeas Corpus","L’Acte d’Union"]'::jsonb, 0, 'Un jalon précoce de la limitation du pouvoir par le droit.', 7),
    ('f87e3691-c443-59bf-befd-fa2866d49819'::uuid, '366b29bc-3e55-5737-b8e6-5efb48978a1b'::uuid, 'Chaque vague de démocratisation a été suivie d’un reflux.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est ce qui rend l’observation des reculs démocratiques actuels si importante.', 8),
    ('577a3ca4-9c48-57b9-bd5c-0f24dda02977'::uuid, '47d321eb-be02-5d0e-a478-b85a96ad7891'::uuid, 'Selon Rousseau, à qui appartient la souveraineté ?', 'mcq', '["Au peuple, somme des citoyens","À la Nation, entité abstraite","Aux représentants élus","Au chef de l’État"]'::jsonb, 0, 'De là découlent le mandat impératif et la préférence pour la démocratie directe.', 1),
    ('d91399f0-a709-5fdd-b58e-e50e5849b407'::uuid, '47d321eb-be02-5d0e-a478-b85a96ad7891'::uuid, 'Que défend Sieyès avec la souveraineté nationale ?', 'mcq', '["La Nation ne s’exprime que par des représentants","Le peuple doit voter chaque loi","Le roi conserve la souveraineté","Les régions sont souveraines"]'::jsonb, 0, 'Le représentant reçoit un mandat représentatif, sans ordre de ses électeurs.', 2),
    ('0c08f23c-31b2-55fd-9daf-5514c287fd4e'::uuid, '47d321eb-be02-5d0e-a478-b85a96ad7891'::uuid, 'Quel principe, énoncé par Montesquieu, limite le pouvoir par le pouvoir ?', 'mcq', '["La séparation des pouvoirs","La souveraineté populaire","Le suffrage universel","Le contrôle de constitutionnalité"]'::jsonb, 0, 'Exécutif, législatif et judiciaire se limitent mutuellement.', 3),
    ('166aafd7-7aa8-5c06-ae86-f16c4c030659'::uuid, '47d321eb-be02-5d0e-a478-b85a96ad7891'::uuid, 'Que permet la QPC depuis 2010 ?', 'mcq', '["Contester devant le juge une loi déjà en vigueur","Organiser un référendum d’initiative citoyenne","Destituer un élu","Saisir la Cour européenne directement"]'::jsonb, 0, 'La question prioritaire de constitutionnalité ouvre le contrôle aux justiciables.', 4),
    ('9510a6d4-2c60-5cbd-8865-4a6bdfeb48e8'::uuid, '47d321eb-be02-5d0e-a478-b85a96ad7891'::uuid, 'La démocratie se réduit à la règle de la majorité.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Des droits fondamentaux limitent ce qu’une majorité peut décider.', 5),
    ('b0ab830f-3a67-5144-8d4b-5656719a3c80'::uuid, '47d321eb-be02-5d0e-a478-b85a96ad7891'::uuid, 'Qu’est-ce que la démocratie participative ?', 'mcq', '["Associer les citoyens aux décisions sans qu’ils tranchent seuls","Faire voter le peuple sur chaque loi","Élire tous les fonctionnaires","Tirer au sort les députés"]'::jsonb, 0, 'Concertations, conventions citoyennes et budgets participatifs en relèvent.', 6),
    ('e23e7966-49b4-5118-bc69-f469c479c1ce'::uuid, '47d321eb-be02-5d0e-a478-b85a96ad7891'::uuid, 'Que signifie l’État de droit ?', 'mcq', '["Les gouvernants eux-mêmes sont soumis au droit","L’État peut tout décider","Le droit est fixé par la majorité","La justice dépend du gouvernement"]'::jsonb, 0, 'C’est ce qui distingue un pouvoir légitime d’un pouvoir arbitraire.', 7),
    ('5a5cdb52-8399-513f-918b-414f3b32bff1'::uuid, '47d321eb-be02-5d0e-a478-b85a96ad7891'::uuid, 'La Constitution française combine souveraineté nationale et souveraineté populaire.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Le peuple l’exerce « par ses représentants et par la voie du référendum ».', 8),
    ('94a13aad-d1f0-5b90-b5b5-d3a7321a08f0'::uuid, '4a1655d9-9854-5b40-b0e4-0b328714fa00'::uuid, 'Quel mode de scrutin dégage le plus facilement une majorité stable ?', 'mcq', '["Le scrutin majoritaire","La proportionnelle intégrale","Le vote préférentiel","Le tirage au sort"]'::jsonb, 0, 'Au prix d’une sous-représentation des courants minoritaires.', 1),
    ('651742cc-4f82-52f3-8937-59269df37def'::uuid, '4a1655d9-9854-5b40-b0e4-0b328714fa00'::uuid, 'Comment sont élus les sénateurs français ?', 'mcq', '["Au suffrage universel indirect","Au suffrage universel direct","Par tirage au sort","Par nomination présidentielle"]'::jsonb, 0, 'Par un collège de grands électeurs, essentiellement des élus locaux.', 2),
    ('bf8c6b20-3988-5b32-8025-4d21ba85f6cb'::uuid, '4a1655d9-9854-5b40-b0e4-0b328714fa00'::uuid, 'Le vote est-il obligatoire en France ?', 'mcq', '["Non, il est libre","Oui, sous peine d’amende","Oui, pour la présidentielle seulement","Oui, depuis 2017"]'::jsonb, 0, 'Il l’est en Belgique et en Australie, pas en France.', 3),
    ('f17f92af-f455-5768-a88a-e6ffb10c9888'::uuid, '4a1655d9-9854-5b40-b0e4-0b328714fa00'::uuid, 'Quel organisme contrôle les comptes de campagne ?', 'mcq', '["La CNCCFP","L’Arcom","La CNIL","La HATVP"]'::jsonb, 0, 'L’Arcom veille, elle, à l’équité du temps de parole.', 4),
    ('e5e395c1-63b2-503b-81dc-8225eb6c24b6'::uuid, '4a1655d9-9854-5b40-b0e4-0b328714fa00'::uuid, 'La proportionnelle reflète mieux l’opinion mais peut fragmenter l’assemblée.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'D’où les systèmes mixtes, qui ajoutent une prime majoritaire.', 5),
    ('fa45a7d1-104c-50bf-89bc-744a734dcf0f'::uuid, '4a1655d9-9854-5b40-b0e4-0b328714fa00'::uuid, 'Qu’appelle-t-on la mal-inscription ?', 'mcq', '["Être inscrit sur les listes d’une commune où l’on ne vit plus","Voter deux fois","Ne pas être inscrit du tout","Se tromper de bulletin"]'::jsonb, 0, 'Elle gonfle mécaniquement l’abstention mesurée.', 6),
    ('782baa2e-8d0c-5aa4-a825-c8d381fe7f2d'::uuid, '4a1655d9-9854-5b40-b0e4-0b328714fa00'::uuid, 'Il existe un mode de scrutin politiquement neutre.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Chaque mode arbitre entre représentativité et gouvernabilité : c’est un choix politique.', 7),
    ('a9189915-6ab7-504e-a3b1-5bf2c94efdfb'::uuid, '4a1655d9-9854-5b40-b0e4-0b328714fa00'::uuid, 'Quelle réforme de 2000 a rapproché législatives et présidentielle ?', 'mcq', '["Le passage au quinquennat","Le non-cumul des mandats","La parité","La réforme du Sénat"]'::jsonb, 0, 'Avec l’inversion du calendrier, les législatives suivent la présidentielle.', 8),
    ('7d01209d-e087-512d-a9f1-7745265cdea3'::uuid, '01fa116c-aafb-5de6-85f3-3b048b920095'::uuid, 'Que garantissent les deux premiers articles de la loi de 1905 ?', 'mcq', '["La liberté de conscience et le libre exercice des cultes","L’interdiction des religions dans l’espace public","Le financement des cultes par l’État","La suppression des jours fériés religieux"]'::jsonb, 0, 'Et, dans le même mouvement, la neutralité de l’État qui ne salarie aucun culte.', 1),
    ('0210ab44-0290-5135-a23f-56b0092bc705'::uuid, '01fa116c-aafb-5de6-85f3-3b048b920095'::uuid, 'À qui s’applique l’obligation de neutralité religieuse ?', 'mcq', '["Aux agents publics dans leurs fonctions","À tous les citoyens dans la rue","Aux seuls enseignants","Aux entreprises privées"]'::jsonb, 0, 'Un usager du service public, lui, n’y est pas soumis.', 2),
    ('fd120dfc-64f9-549a-b5c7-55ac7774c02a'::uuid, '01fa116c-aafb-5de6-85f3-3b048b920095'::uuid, 'Que prévoit la loi de 2004 ?', 'mcq', '["L’interdiction des signes religieux ostensibles dans les écoles publiques","L’interdiction du voile dans la rue","La fin du concordat en Alsace-Moselle","La neutralité des entreprises"]'::jsonb, 0, 'Elle vise les élèves des écoles, collèges et lycées publics.', 3),
    ('356fe135-959a-5c99-91d1-b49f28ed0d8f'::uuid, '01fa116c-aafb-5de6-85f3-3b048b920095'::uuid, 'Le blasphème est-il un délit en droit français ?', 'mcq', '["Non","Oui, depuis 1905","Oui, depuis 2021","Oui, pour certaines religions"]'::jsonb, 0, 'La critique des idées religieuses est libre ; l’injure envers des personnes ne l’est pas.', 4),
    ('6a10c740-d4a4-52a5-a4ac-2268fed07b40'::uuid, '01fa116c-aafb-5de6-85f3-3b048b920095'::uuid, 'Laïcité et athéisme d’État sont deux choses différentes.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'L’État n’est pas contre les religions : il est neutre entre elles.', 5),
    ('53e2b60e-ecee-5680-80cf-1f1faeaf96c2'::uuid, '01fa116c-aafb-5de6-85f3-3b048b920095'::uuid, 'Quel territoire français conserve un régime concordataire ?', 'mcq', '["L’Alsace-Moselle","La Corse","La Guyane","Mayotte"]'::jsonb, 0, 'Annexée en 1905, elle n’a pas connu l’application de la loi de séparation.', 6),
    ('4c85c0fa-1345-5c4d-94b7-937adca40d46'::uuid, '01fa116c-aafb-5de6-85f3-3b048b920095'::uuid, 'Qu’a renforcé la loi du 24 août 2021 ?', 'mcq', '["La neutralité dans les missions de service public et le contrôle des associations","L’interdiction des signes religieux dans la rue","Le financement des cultes","La suppression de l’instruction en famille"]'::jsonb, 0, 'Elle encadre aussi plus strictement l’instruction en famille.', 7),
    ('cb0915bb-e803-5037-b445-91321de17f87'::uuid, '01fa116c-aafb-5de6-85f3-3b048b920095'::uuid, 'Un particulier peut porter un signe religieux dans la rue.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'La neutralité s’impose à l’État et à ses agents, pas aux usagers dans l’espace public.', 8),
    ('ac726746-1365-5ba7-a129-d99efec8be20'::uuid, '7ba5f44a-33d1-5239-9a2b-1f0c2071fd87'::uuid, 'Qu’est-ce qu’une démocratie illibérale ?', 'mcq', '["Un régime qui garde les formes électorales mais vide les contre-pouvoirs","Une démocratie sans élections","Une monarchie constitutionnelle","Un régime militaire"]'::jsonb, 0, 'Justice sous tutelle, médias contrôlés, société civile harcelée.', 1),
    ('ecc2125f-cfb2-541a-98b0-b0a12a122575'::uuid, '7ba5f44a-33d1-5239-9a2b-1f0c2071fd87'::uuid, 'Qu’est-ce qui distingue un régime totalitaire d’un régime autoritaire ?', 'mcq', '["Il prétend contrôler la société entière avec une idéologie officielle","Il organise des élections","Il tolère une opposition","Il respecte la justice"]'::jsonb, 0, 'Parti unique, idéologie obligatoire, terreur organisée.', 2),
    ('8d05872e-0abb-5006-bd14-212c4a30f8ab'::uuid, '7ba5f44a-33d1-5239-9a2b-1f0c2071fd87'::uuid, 'Les indices internationaux constatent une progression continue des démocraties.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'V-Dem et Freedom House mesurent au contraire un recul depuis une quinzaine d’années.', 3),
    ('47050472-10f8-5264-801a-2b434b4a1600'::uuid, '7ba5f44a-33d1-5239-9a2b-1f0c2071fd87'::uuid, 'Comment une démocratie est-elle aujourd’hui le plus souvent affaiblie ?', 'mcq', '["De l’intérieur, en respectant les formes","Par un coup d’État militaire","Par une invasion étrangère","Par un référendum de dissolution"]'::jsonb, 0, 'Ce qui rend le recul difficile à dater et à contester juridiquement.', 4),
    ('96c1f420-c7ee-5d60-9d99-bc9824d67b68'::uuid, '7ba5f44a-33d1-5239-9a2b-1f0c2071fd87'::uuid, 'Quel pays européen est le plus souvent cité comme démocratie illibérale ?', 'mcq', '["La Hongrie","Le Portugal","L’Irlande","La Suède"]'::jsonb, 0, 'La Turquie est un autre cas fréquemment analysé.', 5),
    ('d626b147-ab0d-5690-a23f-476cd819b425'::uuid, '7ba5f44a-33d1-5239-9a2b-1f0c2071fd87'::uuid, 'Quel facteur alimente la contestation des démocraties ?', 'mcq', '["La défiance envers les élus et le sentiment que le vote ne change rien","La hausse de la participation électorale","Le renforcement des contre-pouvoirs","La stabilité des majorités"]'::jsonb, 0, 'S’y ajoutent les inégalités et la désinformation.', 6),
    ('79b7633f-6a77-587a-8997-fd2f2f34c475'::uuid, '7ba5f44a-33d1-5239-9a2b-1f0c2071fd87'::uuid, 'Qu’est-ce qui mesure le mieux la résilience d’une démocratie ?', 'mcq', '["L’existence réelle de contre-pouvoirs indépendants","La longueur de sa Constitution","Le nombre de partis","La fréquence des référendums"]'::jsonb, 0, 'Les textes ne suffisent pas : ce sont les contre-pouvoirs effectifs qui tiennent.', 7),
    ('d3d6d2b8-7d8a-5edb-976f-d092ef4a4a40'::uuid, '7ba5f44a-33d1-5239-9a2b-1f0c2071fd87'::uuid, 'La Chine met en avant un modèle fondé sur l’efficacité plutôt que sur le pluralisme.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est l’un des ressorts de la contestation du modèle démocratique à l’échelle mondiale.', 8),
    ('32fa4924-98ba-5729-ae90-a185f496ccb7'::uuid, '63242696-e242-5d50-aa38-ddf83d2d6406'::uuid, 'Quand l’état d’urgence a-t-il été déclaré en France après les attentats ?', 'mcq', '["En novembre 2015","En janvier 2015","En juillet 2016","En 2017"]'::jsonb, 0, 'Il a été prolongé jusqu’à son remplacement partiel par la loi SILT en 2017.', 1),
    ('0b911626-04e6-5106-8c69-7f948755afaf'::uuid, '63242696-e242-5d50-aa38-ddf83d2d6406'::uuid, 'Que permet une perquisition administrative sous état d’urgence ?', 'mcq', '["Une perquisition décidée sans autorisation d’un juge","Une perquisition ordonnée par un juge d’instruction","Une fouille des seuls lieux publics","Une garde à vue prolongée"]'::jsonb, 0, 'C’est précisément ce qui la distingue du droit commun — et ce qui la rend contestée.', 2),
    ('61e6eaa2-4b69-5704-a93c-54ca9694b6c4'::uuid, '63242696-e242-5d50-aa38-ddf83d2d6406'::uuid, 'Quelle loi de 2017 fait passer des mesures d’exception dans le droit commun ?', 'mcq', '["La loi SILT","La loi renseignement","La loi Informatique et libertés","La loi de 1905"]'::jsonb, 0, 'Sous contrôle du juge administratif.', 3),
    ('8f6d33ca-2c82-5125-8fc8-64e5bd4f8f50'::uuid, '63242696-e242-5d50-aa38-ddf83d2d6406'::uuid, 'Quelle autorité protège les données personnelles en France ?', 'mcq', '["La CNIL","La HATVP","L’Arcom","La CNCCFP"]'::jsonb, 0, 'Elle contrôle notamment les fichiers et les dispositifs de surveillance.', 4),
    ('d2d0802f-ba64-5d78-a8e2-000296379f97'::uuid, '63242696-e242-5d50-aa38-ddf83d2d6406'::uuid, 'Le Conseil constitutionnel a censuré certaines mesures antiterroristes jugées excessives.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est l’un des garde-fous du contrôle de proportionnalité.', 5),
    ('0c020f91-7b69-5fb9-88d7-37efd797fb53'::uuid, '63242696-e242-5d50-aa38-ddf83d2d6406'::uuid, 'Quels critères permettent d’apprécier une mesure de sécurité ?', 'mcq', '["Nécessité, proportionnalité, contrôle par un juge","Rapidité, coût, efficacité","Popularité, urgence, durée","Légalité seule"]'::jsonb, 0, 'C’est la grille attendue dans une copie d’EMC.', 6),
    ('81cadf67-dd05-5d83-a940-7ab74fa88b1a'::uuid, '63242696-e242-5d50-aa38-ddf83d2d6406'::uuid, 'Qu’appelle-t-on ingérence étrangère ?', 'mcq', '["Une opération d’influence ou de manipulation venue d’un autre État","Une immigration non contrôlée","Un investissement étranger","Une aide au développement"]'::jsonb, 0, 'Manipulation de l’information et financements occultes en sont les formes courantes.', 7),
    ('a1f840e9-9914-57a5-87d6-24561f0b1fdf'::uuid, '63242696-e242-5d50-aa38-ddf83d2d6406'::uuid, 'Un régime d’exception peut devenir permanent sans changer la nature du régime politique.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Une exception permanente et sans contrôle transforme le régime lui-même.', 8),
    ('c9a1bcb1-029e-5ed6-8c32-38be81b53b3b'::uuid, 'ab62d378-6e83-5da1-841c-7bb0adfee22b'::uuid, 'Que fixent les critères de Copenhague de 1993 ?', 'mcq', '["Les conditions démocratiques d’adhésion à l’Union","Les règles budgétaires de la zone euro","Les quotas migratoires","Le fonctionnement de la BCE"]'::jsonb, 0, 'Institutions stables, État de droit, droits de l’homme, protection des minorités.', 1),
    ('1b68c89f-75ef-5859-b1ee-26bb605d013b'::uuid, 'ab62d378-6e83-5da1-841c-7bb0adfee22b'::uuid, 'Depuis quand le Parlement européen est-il élu au suffrage universel direct ?', 'mcq', '["1979","1957","1992","2009"]'::jsonb, 0, 'Ses pouvoirs se sont ensuite considérablement étendus.', 2),
    ('6b8b63b2-18db-5965-98c7-6bf5048d84c9'::uuid, 'ab62d378-6e83-5da1-841c-7bb0adfee22b'::uuid, 'Que permet l’article 7 du traité sur l’Union européenne ?', 'mcq', '["Sanctionner un État qui s’écarte des valeurs communes","Sortir de l’Union","Créer une armée commune","Suspendre l’euro"]'::jsonb, 0, 'L’unanimité requise le rend très difficile à appliquer — d’où la conditionnalité budgétaire.', 3),
    ('b7e8b5af-481d-5c6f-b1b2-87fe028a977d'::uuid, 'ab62d378-6e83-5da1-841c-7bb0adfee22b'::uuid, 'Quelle institution européenne détient l’initiative législative ?', 'mcq', '["La Commission","Le Parlement","Le Conseil","La CJUE"]'::jsonb, 0, 'C’est l’un des arguments avancés pour parler de déficit démocratique.', 4),
    ('0071760a-2845-545b-a5df-686b23122906'::uuid, 'ab62d378-6e83-5da1-841c-7bb0adfee22b'::uuid, 'Que permet l’initiative citoyenne européenne ?', 'mcq', '["Demander à la Commission de légiférer avec un million de signatures","Organiser un référendum européen","Destituer un commissaire","Élire le président de la Commission"]'::jsonb, 0, 'Les signatures doivent venir d’au moins sept États membres.', 5),
    ('e574a14f-207f-5d35-b8c3-d856ec05bdda'::uuid, 'ab62d378-6e83-5da1-841c-7bb0adfee22b'::uuid, 'L’adhésion à l’Union a servi d’ancrage démocratique après des dictatures.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Espagne, Portugal, Grèce, puis les pays d’Europe centrale après 1989.', 6),
    ('12bb6259-34c9-554a-9145-49e1476a4225'::uuid, 'ab62d378-6e83-5da1-841c-7bb0adfee22b'::uuid, 'Depuis quand la Charte des droits fondamentaux a-t-elle valeur contraignante ?', 'mcq', '["2009","2000","1993","2016"]'::jsonb, 0, 'Avec l’entrée en vigueur du traité de Lisbonne.', 7),
    ('49c0705c-640a-5432-a882-c23425be933a'::uuid, 'ab62d378-6e83-5da1-841c-7bb0adfee22b'::uuid, 'Aucune décision européenne n’est prise par des responsables issus d’élections.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elles le sont par des députés élus ou par des gouvernements responsables devant leurs Parlements.', 8),
    ('574b5f9c-9911-521a-aad7-63daed395e8b'::uuid, 'a8828cf1-043c-5e6e-923f-31acc0842688'::uuid, 'Qu’est-ce qu’argumenter ?', 'mcq', '["Appuyer une position sur des raisons et des faits vérifiables","Répéter son opinion avec conviction","Convaincre par tous les moyens","Éviter le désaccord"]'::jsonb, 0, 'Sans raisons vérifiables, il n’y a pas de débat mais une confrontation d’affirmations.', 1),
    ('bad13781-2319-5e9c-a258-fae80bb57ba0'::uuid, 'a8828cf1-043c-5e6e-923f-31acc0842688'::uuid, 'Quel philosophe a théorisé la notion d’espace public ?', 'mcq', '["Habermas","Montesquieu","Rousseau","Tocqueville"]'::jsonb, 0, 'Le lieu où les citoyens discutent publiquement des affaires communes.', 2),
    ('efc9b0a9-b68b-5a6a-9a03-0f863cd9c4f2'::uuid, 'a8828cf1-043c-5e6e-923f-31acc0842688'::uuid, 'Qu’est-ce qu’une bulle de filtre ?', 'mcq', '["Une exposition sélective à des contenus qui confirment nos opinions","Un filtre anti-spam","Une censure d’État","Un dispositif de fact-checking"]'::jsonb, 0, 'Les algorithmes privilégient ce qui confirme et ce qui indigne.', 3),
    ('50731537-0fef-5756-aa32-77c07592af54'::uuid, 'a8828cf1-043c-5e6e-923f-31acc0842688'::uuid, 'Combien de citoyens tirés au sort composaient la Convention citoyenne pour le climat ?', 'mcq', '["150","50","500","1 000"]'::jsonb, 0, 'Une expérimentation majeure de délibération citoyenne en France.', 4),
    ('41740847-2ee6-527e-b552-bc4b62c1f896'::uuid, 'a8828cf1-043c-5e6e-923f-31acc0842688'::uuid, 'Un désaccord argumenté est utile à la démocratie.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est le désaccord non argumenté, ou l’absence de débat, qui l’abîme.', 5),
    ('60af97ae-ac76-5588-a9be-5b6c4db7c492'::uuid, 'a8828cf1-043c-5e6e-923f-31acc0842688'::uuid, 'Qu’est-ce qu’un sophisme ?', 'mcq', '["Un raisonnement trompeur qui a l’apparence de la logique","Une opinion minoritaire","Une information fausse","Un argument d’autorité valide"]'::jsonb, 0, 'Attaque personnelle, faux dilemme et généralisation abusive en sont des formes courantes.', 6),
    ('a346bab2-95f4-52de-a4c6-c84c1b4874ea'::uuid, 'a8828cf1-043c-5e6e-923f-31acc0842688'::uuid, 'La désinformation circule généralement plus vite que sa correction.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est l’une des difficultés structurelles de l’espace informationnel actuel.', 7),
    ('25d3ac73-50bd-55db-baaf-921ba2bf85dd'::uuid, 'a8828cf1-043c-5e6e-923f-31acc0842688'::uuid, 'Que vise l’éducation aux médias et à l’information ?', 'mcq', '["Apprendre à vérifier et à hiérarchiser l’information","Interdire les réseaux sociaux aux mineurs","Former des journalistes","Contrôler les contenus en ligne"]'::jsonb, 0, 'Elle est inscrite dans les programmes scolaires.', 8),
    ('83740ec1-1aec-575a-9121-f1acd0eec3a4'::uuid, '5661509d-9cdb-5b6c-a454-1f66ae120c85'::uuid, 'Quelle autorité contrôle les déclarations de patrimoine des responsables publics ?', 'mcq', '["La HATVP","La CNIL","La Cour des comptes","Le Conseil constitutionnel"]'::jsonb, 0, 'Créée en 2013 après l’affaire Cahuzac.', 1),
    ('4e7e6421-3917-54cb-83cf-dd8d9139655b'::uuid, '5661509d-9cdb-5b6c-a454-1f66ae120c85'::uuid, 'Qu’interdisent les lois de 2017 pour la confiance dans la vie politique ?', 'mcq', '["Les emplois familiaux des parlementaires","Le financement public des partis","Le lobbying","Le cumul de deux mandats locaux"]'::jsonb, 0, 'Elles suppriment aussi la réserve parlementaire et encadrent les frais de mandat.', 2),
    ('074d31fe-462f-5252-a1be-e36756f8617f'::uuid, '5661509d-9cdb-5b6c-a454-1f66ae120c85'::uuid, 'Qu’est-ce qu’un conflit d’intérêts ?', 'mcq', '["Une situation où un intérêt privé peut influencer une fonction publique","Un désaccord entre deux ministères","Une grève dans le service public","Un litige commercial"]'::jsonb, 0, 'Il doit être déclaré, et la personne concernée doit se déporter.', 3),
    ('062e3ab4-cc58-5db8-a5ff-51ad8deef452'::uuid, '5661509d-9cdb-5b6c-a454-1f66ae120c85'::uuid, 'Quelle loi de 2016 protège les lanceurs d’alerte ?', 'mcq', '["La loi Sapin II","La loi SILT","La loi Informatique et libertés","La loi de 1905"]'::jsonb, 0, 'Renforcée en 2022 par la transposition d’une directive européenne.', 4),
    ('497d70a4-7911-57e9-9c3f-cd01cedf92c1'::uuid, '5661509d-9cdb-5b6c-a454-1f66ae120c85'::uuid, 'Les lobbyistes doivent s’inscrire sur un répertoire public.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Tenu par la HATVP, il oblige à déclarer les actions d’influence menées.', 5),
    ('e3156f07-25de-54e2-8988-e699b7169a5d'::uuid, '5661509d-9cdb-5b6c-a454-1f66ae120c85'::uuid, 'Quelle institution contrôle l’emploi des fonds publics ?', 'mcq', '["La Cour des comptes","La HATVP","Le Conseil d’État","L’Arcom"]'::jsonb, 0, 'Ses rapports publics alimentent le débat démocratique.', 6),
    ('1a82da53-fc11-5bfb-933d-0edab389ff97'::uuid, '5661509d-9cdb-5b6c-a454-1f66ae120c85'::uuid, 'Le non-cumul entre mandat parlementaire et exécutif local s’applique depuis…', 'mcq', '["2017","2013","2008","2022"]'::jsonb, 0, 'Une transformation importante du métier de parlementaire.', 7),
    ('479389b3-1db3-50f9-aa90-129f6dadacef'::uuid, '5661509d-9cdb-5b6c-a454-1f66ae120c85'::uuid, 'La transparence garantit à elle seule la probité des élus.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle rend le contrôle possible ; elle ne remplace ni la déontologie ni la sanction.', 8),
    ('5447f3df-1f88-5e84-b2ef-2c3a9c178af1'::uuid, '85740ba6-faa2-5ec0-913a-f73b774871e5'::uuid, 'Quelle est aujourd’hui la première forme d’engagement en France ?', 'mcq', '["Le bénévolat associatif","L’adhésion à un parti","La syndicalisation","La pétition en ligne"]'::jsonb, 0, 'Plus d’un million d’associations et de l’ordre de 20 millions de bénévoles.', 1),
    ('21471099-a5a3-5135-b3fc-3c6bde85040e'::uuid, '85740ba6-faa2-5ec0-913a-f73b774871e5'::uuid, 'Quel est l’ordre de grandeur du taux de syndicalisation en France ?', 'mcq', '["Environ 10 %","Environ 40 %","Environ 25 %","Environ 60 %"]'::jsonb, 0, 'L’un des plus faibles d’Europe, alors que la couverture des accords y est très large.', 2),
    ('f07ef073-1d3e-50ce-9c61-afc08946c52a'::uuid, '85740ba6-faa2-5ec0-913a-f73b774871e5'::uuid, 'Qu’est-ce que la désobéissance civile ?', 'mcq', '["Violer publiquement et sans violence une règle jugée injuste, en acceptant la sanction","Refuser de payer ses impôts en secret","Manifester sans autorisation","Voter blanc"]'::jsonb, 0, 'Thoreau, Gandhi et Martin Luther King en sont les références classiques.', 3),
    ('4ada4ff7-ed7a-5a4b-a1a7-d3d1b2291094'::uuid, '85740ba6-faa2-5ec0-913a-f73b774871e5'::uuid, 'Depuis quelle année existe le service civique ?', 'mcq', '["2010","1997","2000","2016"]'::jsonb, 0, 'Ouvert aux 16-25 ans, pour des missions d’intérêt général.', 4),
    ('97373bdb-e100-53a5-884a-7c3577935d7f'::uuid, '85740ba6-faa2-5ec0-913a-f73b774871e5'::uuid, 'Qu’appelle-t-on le « slacktivisme » ?', 'mcq', '["Un engagement en ligne sans effort ni effet réel","Un militantisme syndical radical","Un boycott organisé","Une grève illimitée"]'::jsonb, 0, 'Ce qui fait la différence : la continuité de l’action et son ancrage collectif.', 5),
    ('5244d2a8-f632-538b-82a9-576528a8c08b'::uuid, '85740ba6-faa2-5ec0-913a-f73b774871e5'::uuid, 'Les effectifs des partis politiques ont fortement diminué en France.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'L’engagement se reporte vers des formes plus ponctuelles et choisies.', 6),
    ('9ea5520b-93d9-5af8-84d6-69f70e037477'::uuid, '85740ba6-faa2-5ec0-913a-f73b774871e5'::uuid, 'Qu’est-ce qu’un budget participatif ?', 'mcq', '["Une part du budget local dont l’affectation est décidée par les habitants","Le budget de l’État voté par référendum","Une cagnotte associative","Le financement participatif d’une entreprise"]'::jsonb, 0, 'Une forme concrète de démocratie participative locale.', 7),
    ('1cffdeb4-0ec5-524d-8da8-568ddc0314d8'::uuid, '85740ba6-faa2-5ec0-913a-f73b774871e5'::uuid, 'Une pétition en ligne ne peut avoir aucun effet institutionnel.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Une pétition massive peut porter un sujet jusqu’au Parlement.', 8),
    ('6f218153-bcc8-5da4-b056-e7bf79f6684f'::uuid, 'f43e1a78-519c-54ef-8387-2ac618634468'::uuid, 'Sur quel pari repose la démocratie délibérative ?', 'mcq', '["Une décision précédée d’une délibération informée est plus légitime","La majorité a toujours raison","Les experts doivent décider seuls","Le vote suffit à légitimer"]'::jsonb, 0, 'D’où les panels de citoyens tirés au sort et formés avant de délibérer.', 1),
    ('784a35cd-158d-5750-8185-26641cad54ef'::uuid, 'f43e1a78-519c-54ef-8387-2ac618634468'::uuid, 'Quel est l’avantage du tirage au sort par rapport à l’élection ?', 'mcq', '["Il assure une diversité sociale que l’élection ne produit pas","Il donne un mandat plus fort","Il coûte moins cher","Il évite tout débat"]'::jsonb, 0, 'En revanche, il ne confère pas de mandat : le sort des propositions reste la difficulté.', 2),
    ('647fdc4e-3f02-58fa-b77e-037d076bc085'::uuid, 'f43e1a78-519c-54ef-8387-2ac618634468'::uuid, 'Quel référendum existe en droit français depuis 2008 ?', 'mcq', '["Le référendum d’initiative partagée","Le référendum d’initiative citoyenne","Le référendum révocatoire","Le référendum local obligatoire"]'::jsonb, 0, 'Ses seuils, très élevés, n’ont jamais été franchis jusqu’au bout.', 3),
    ('293609df-caff-5105-b5d3-ae4660f14a56'::uuid, 'f43e1a78-519c-54ef-8387-2ac618634468'::uuid, 'Que garantit la Charte de l’environnement adossée à la Constitution en 2005 ?', 'mcq', '["Un droit à l’information et à la participation du public","L’interdiction des énergies fossiles","Un droit de veto écologique","La neutralité carbone"]'::jsonb, 0, 'Elle fonde la démocratie environnementale en droit français.', 4),
    ('f6a9f270-35e5-55ad-b534-84071a67321f'::uuid, 'f43e1a78-519c-54ef-8387-2ac618634468'::uuid, 'Un budget participatif laisse les habitants décider d’une part du budget local.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est la forme la plus répandue de démocratie participative locale.', 5),
    ('2771531c-b813-549d-8ab5-9ba894aaa1bd'::uuid, 'f43e1a78-519c-54ef-8387-2ac618634468'::uuid, 'Quelle convention citoyenne a réuni 150 personnes tirées au sort en 2019-2020 ?', 'mcq', '["La Convention citoyenne pour le climat","La Convention sur la fin de vie","Le Grand Débat national","La Conférence sur l’avenir de l’Europe"]'::jsonb, 0, 'Ses propositions ont été partiellement reprises, ce qui a nourri le débat sur les suites données.', 6),
    ('55806e43-4c12-5e83-ab38-4f186a2056b2'::uuid, 'f43e1a78-519c-54ef-8387-2ac618634468'::uuid, 'Une consultation citoyenne sans suite renforce la confiance envers les institutions.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle produit l’inverse : la déception aggrave la défiance qu’elle prétendait réduire.', 7),
    ('7ad82949-d2f9-5f9f-8d96-26156f80752e'::uuid, 'f43e1a78-519c-54ef-8387-2ac618634468'::uuid, 'Que désigne la civic tech ?', 'mcq', '["Les outils numériques de consultation et de participation citoyenne","La surveillance algorithmique","Le vote électronique obligatoire","Les réseaux sociaux politiques"]'::jsonb, 0, 'Elle facilite la consultation, sans régler la question du suivi des avis recueillis.', 8),
    ('f54686e4-4938-5775-af07-b25f25172fcb'::uuid, '4679ad72-acaa-5706-a891-a506c6b909be'::uuid, 'En quelle année la Déclaration universelle des droits de l’homme est-elle adoptée ?', 'mcq', '["1948","1945","1950","1966"]'::jsonb, 0, 'Par l’Assemblée générale de l’ONU : une référence sans force contraignante.', 1),
    ('e94a1220-b74d-525f-ad3c-0166e606a7b1'::uuid, '4679ad72-acaa-5706-a891-a506c6b909be'::uuid, 'Quelle cour peut condamner un État sur requête d’un individu ?', 'mcq', '["La Cour européenne des droits de l’homme","La Cour pénale internationale","La Cour internationale de justice","La CJUE"]'::jsonb, 0, 'Elle applique la Convention européenne des droits de l’homme de 1950.', 2),
    ('9f22d2d7-a446-53b0-8356-3386474363bb'::uuid, '4679ad72-acaa-5706-a891-a506c6b909be'::uuid, 'Que juge la Cour pénale internationale ?', 'mcq', '["Des individus, pour les crimes les plus graves","Des États, pour violation de traités","Des entreprises","Des organisations internationales"]'::jsonb, 0, 'Génocide, crimes contre l’humanité, crimes de guerre, crime d’agression.', 3),
    ('285e56df-b434-5e84-925d-8b156e0a2178'::uuid, '4679ad72-acaa-5706-a891-a506c6b909be'::uuid, 'Toutes les grandes puissances ont ratifié le statut de Rome.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'États-Unis, Chine, Russie et Inde ne l’ont pas ratifié — une limite majeure.', 4),
    ('d7f15807-edd6-5d77-95c3-0f4b06b37143'::uuid, '4679ad72-acaa-5706-a891-a506c6b909be'::uuid, 'Qu’est-ce que la responsabilité de protéger, adoptée en 2005 ?', 'mcq', '["Le principe autorisant la communauté internationale à agir quand un État massacre sa population","L’obligation d’accueillir des réfugiés","La protection des ambassades","Le devoir d’aide au développement"]'::jsonb, 0, 'Son application dépend du Conseil de sécurité, donc du droit de veto.', 5),
    ('fa3173c9-49a1-5355-ae6e-340c7e656ed6'::uuid, '4679ad72-acaa-5706-a891-a506c6b909be'::uuid, 'Quel mécanisme bloque souvent l’action du Conseil de sécurité ?', 'mcq', '["Le droit de veto des cinq membres permanents","Le vote à la majorité qualifiée","L’absence de budget","Le retrait des ONG"]'::jsonb, 0, 'Il a notamment paralysé l’action sur la Syrie.', 6),
    ('66d27154-22cf-514f-b683-e0bdaa9d19e2'::uuid, '4679ad72-acaa-5706-a891-a506c6b909be'::uuid, 'Quel est le principal pouvoir des ONG de défense des droits humains ?', 'mcq', '["Documenter et alerter l’opinion","Sanctionner les États","Arrêter les responsables","Voter à l’ONU"]'::jsonb, 0, 'Leurs rapports pèsent par la preuve et la réputation, non par la contrainte.', 7),
    ('25db9065-37e4-5ff3-a390-8de9f35c3c4b'::uuid, '4679ad72-acaa-5706-a891-a506c6b909be'::uuid, 'La promotion de la démocratie par la force a produit des résultats contrastés.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Ancrage réussi par l’élargissement européen, échecs coûteux là où elle a été imposée militairement.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('emc');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('emc')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 230 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 230 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
