-- =============================================================================
-- Studuel — Migration 336 : TECHNOLOGIE 6e — LE PROGRAMME DU CYCLE 3 (10 fiches)
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 336 --modules technologie-6e
--
-- CONSTAT : la technologie de 6e n'avait que DEUX chapitres et 20 questions — après
-- la physique-chimie (traitée par la 326), la matière la plus pauvre du collège.
-- Un élève qui révisait le besoin, la fonction d'usage, les matériaux, le croquis,
-- la chaîne d'information ou la programmation d'un objet ne trouvait presque RIEN.
-- Cette migration installe 10 fiches sous les 4 chapitres du programme et retire
-- les 2 chapitres génériques.
-- ÉCRITE, PAS IMPORTÉE DE LA 3e, contrairement à la 5e (334) et à la 4e (335) : le
-- BO écrit la technologie pour le CYCLE 4, dont la 6e ne fait pas partie. Elle
-- relève du CYCLE 3, où la technologie s'enseigne dans « sciences et technologie ».
-- LA FRONTIÈRE AVEC LA PHYSIQUE-CHIMIE DE 6e EST TENUE : la 326 traite le SIGNAL
-- (lumière, son), ce module traite l'OBJET qui le produit et le transporte.
--
-- Cette migration apporte : 10 chapitres, 10 leçons,
-- 10 quiz et 80 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 0. Ménage ----------------------------------------------------------------
-- [technologie] La colonne chapters.theme (migration 234) porte le chapitre du programme, et
-- [technologie] l'INSERT l'écrit pour les 10 fiches. Elle est REPRISE ici en ADD COLUMN IF NOT
-- [technologie] EXISTS parce qu'on ne peut pas garantir que la 234 soit passée en production —
-- [technologie] sans cette reprise, la migration échouerait sur "column chapters.theme does not
-- [technologie] exist", les 2 anciens chapitres déjà supprimés et les 10 neufs pas encore posés.
-- [technologie] Le GRANT n'est pas décoratif : la migration 182 a révoqué le SELECT de table sur
-- [technologie] chapters et ne l'a rendu que colonne par colonne.
ALTER TABLE public.chapters ADD COLUMN IF NOT EXISTS theme TEXT;
GRANT SELECT (theme) ON public.chapters TO anon;
GRANT SELECT (theme) ON public.chapters TO authenticated;

-- [technologie] Les 2 chapitres hérités partent, au niveau 6e SEULEMENT.
-- [technologie] 
-- [technologie] LE REPÈRE EST theme IS NULL, PAS LE TITRE : les 10 fiches neuves portent leur
-- [technologie] chapitre de programme dès l'INSERT, les 2 anciennes n'en ont aucun. Le ménage
-- [technologie] tourne AVANT les insertions et ne peut donc jamais mordre sur les neuves.
-- [technologie] Le filtre level = '6e' est indispensable : la technologie existe sur quatre
-- [technologie] niveaux, et la 3e est la SOURCE des imports de 5e et 4e.
-- [technologie] L'ordre compte : la file "À revoir" d'abord (review_items.item_id n'a PAS de clé
-- [technologie] étrangère), puis les quiz (quizzes.lesson_id est ON DELETE SET NULL), puis les
-- [technologie] chapitres, dont les leçons partent en cascade.
DELETE FROM public.review_items ri
 USING public.quiz_questions qq, public.quizzes qz, public.lessons l,
       public.chapters c, public.subjects s
 WHERE ri.item_kind = 'question'
   AND ri.item_id = qq.id
   AND qq.quiz_id = qz.id
   AND qz.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'technologie'
   AND c.level = '6e'
   AND c.theme IS NULL;

DELETE FROM public.quizzes q
 USING public.lessons l, public.chapters c, public.subjects s
 WHERE q.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'technologie'
   AND c.level = '6e'
   AND c.theme IS NULL;

DELETE FROM public.chapters c
 USING public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'technologie'
   AND c.level = '6e'
   AND c.theme IS NULL;

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position, theme)
SELECT v.id, s.id, v.level, v.title, v.position, v.theme
  FROM (VALUES
    ('beb5b557-794c-5051-802f-05a3546b457e'::uuid, 'technologie', '6e', 'Le besoin et la fonction d’usage', 1, 'L’objet technique et son besoin'),
    ('2d642a5c-891b-52bb-bcd8-ceca9ae91d98'::uuid, 'technologie', '6e', 'Les fonctions techniques et les solutions', 2, 'L’objet technique et son besoin'),
    ('03bdc09b-46eb-5ca6-a7a3-6b8af8a1d49c'::uuid, 'technologie', '6e', 'L’évolution des objets techniques', 3, 'L’objet technique et son besoin'),
    ('14f83a33-63c3-5829-b7bb-89bffb4ae51f'::uuid, 'technologie', '6e', 'Les familles de matériaux', 4, 'Les matériaux'),
    ('6fb7180b-9054-5ddb-9a94-721619109053'::uuid, 'technologie', '6e', 'L’impact environnemental des objets', 5, 'Les matériaux'),
    ('aa23b9a5-3ea4-5f87-9ea0-bed7365ca6f2'::uuid, 'technologie', '6e', 'Croquis, schémas et plans', 6, 'Représenter et fabriquer'),
    ('b83df816-835e-5261-8888-e3668a808edc'::uuid, 'technologie', '6e', 'Fabriquer un objet', 7, 'Représenter et fabriquer'),
    ('a4015043-2efc-542d-99ab-508226b73e2c'::uuid, 'technologie', '6e', 'La chaîne d’information et la chaîne d’énergie', 8, 'Objets programmables et information'),
    ('88c473ff-8210-5cb9-96f7-77dd8c1bfb61'::uuid, 'technologie', '6e', 'Programmer un objet technique', 9, 'Objets programmables et information'),
    ('b9efad07-39af-5d74-9261-8dbbd463217b'::uuid, 'technologie', '6e', 'L’information et sa circulation', 10, 'Objets programmables et information')
  ) AS v(id, slug, level, title, position, theme)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 1 bis. Axes du programme -------------------------------------------------
-- `chapters.theme` (migration 234) : l’intitulé du programme officiel qui
-- coiffe le chapitre. La page matière s’en sert pour grouper au lieu
-- d’aligner 28 lignes à plat. UPDATE et non INSERT : le chapitre peut déjà
-- exister (l’INSERT précédent l’aurait alors ignoré).
UPDATE public.chapters c SET theme = v.theme
  FROM (VALUES
    ('beb5b557-794c-5051-802f-05a3546b457e'::uuid, 'L’objet technique et son besoin'),
    ('2d642a5c-891b-52bb-bcd8-ceca9ae91d98'::uuid, 'L’objet technique et son besoin'),
    ('03bdc09b-46eb-5ca6-a7a3-6b8af8a1d49c'::uuid, 'L’objet technique et son besoin'),
    ('14f83a33-63c3-5829-b7bb-89bffb4ae51f'::uuid, 'Les matériaux'),
    ('6fb7180b-9054-5ddb-9a94-721619109053'::uuid, 'Les matériaux'),
    ('aa23b9a5-3ea4-5f87-9ea0-bed7365ca6f2'::uuid, 'Représenter et fabriquer'),
    ('b83df816-835e-5261-8888-e3668a808edc'::uuid, 'Représenter et fabriquer'),
    ('a4015043-2efc-542d-99ab-508226b73e2c'::uuid, 'Objets programmables et information'),
    ('88c473ff-8210-5cb9-96f7-77dd8c1bfb61'::uuid, 'Objets programmables et information'),
    ('b9efad07-39af-5d74-9261-8dbbd463217b'::uuid, 'Objets programmables et information')
  ) AS v(id, theme)
 WHERE c.id = v.id AND c.theme IS DISTINCT FROM v.theme;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('c9d13c45-5924-5c72-a553-30f97f3b2518', 'beb5b557-794c-5051-802f-05a3546b457e', 'Pourquoi cet objet existe', E'Un objet technique est fabriqué par l’humain pour répondre à un besoin. Un caillou n’en est pas un ; un marteau, si.\n\n## Le besoin d’abord\n!> On n’a **pas** inventé le vélo puis trouvé à quoi il servait. Le besoin — se déplacer — existait avant l’objet. **Le besoin précède toujours l’objet.**\n\n## La fonction d’usage\n= La fonction d’usage répond à : À QUOI ÇA SERT ?\n\nElle s’écrit avec un **verbe à l’infinitif** suivi d’un complément.\n\n| L’objet | Sa fonction d’usage |\n| Un parapluie | **Protéger de la pluie** |\n| Une lampe | **Éclairer un espace** |\n| Un vélo | **Se déplacer** |\n\n## La fonction d’estime\nC’est ce qui fait **préférer** un objet à un autre alors qu’ils rendent le même service : la couleur, la forme, la marque, le prix.\n\n> La fonction d’usage explique pourquoi l’objet **existe**. La fonction d’estime explique pourquoi on achète **celui-là**.\n\n## Le cahier des charges\nLa liste des **contraintes** que l’objet devra respecter.\n\n| La contrainte | Exemple |\n| Dimensions, poids | |\n| Prix | |\n| Sécurité | |\n| Matériaux, durée de vie | |\n| Impact sur l’environnement | |\n\n!> Le cahier des charges dit **ce que l’objet doit faire**, jamais **comment** le faire. C’est un contrat, pas une notice.\n\n## L’utilisateur\n~ Une cuillère pour un adulte → pour un bébé → pour une personne qui n’a qu’une main valide\n\nUn même besoin appelle des objets différents selon **qui** s’en sert.\n\n> Concevoir, c’est d’abord regarder l’utilisateur.', 1),
  ('2ffb2547-6a8d-50aa-97ae-d21c08a1fe40', '2d642a5c-891b-52bb-bcd8-ceca9ae91d98', 'Comment l’objet fait ce qu’il fait', E'La fonction d’usage dit à quoi l’objet sert. Les fonctions techniques disent comment il y parvient.\n\n## De l’usage à la technique\nUn vélo sert à **se déplacer**. Pour cela, il doit :\n\n| La fonction technique | Les organes qui l’assurent |\n| **Transmettre** le mouvement | Pédalier, chaîne, roue |\n| **Diriger** | Guidon, fourche |\n| **Freiner** | Leviers, patins |\n| **Soutenir** l’utilisateur | Cadre, selle |\n\n## Les solutions techniques\nPour chaque fonction technique, plusieurs **solutions** sont possibles.\n\n| La fonction | Les solutions possibles |\n| **Freiner** | Patins sur la jante · frein à disque · rétropédalage |\n| **Transmettre** | Chaîne · courroie · cardan |\n\nLe concepteur choisit selon le **cahier des charges** : coût, poids, entretien, sécurité.\n\n!> Une fonction technique est un **problème** à résoudre ; une solution technique est **une** réponse parmi d’autres. Il n’y a jamais une seule bonne solution.\n\n## Le diagramme\n~ La fonction d’usage → les fonctions techniques → les solutions retenues\n\nOn le représente en arbre, de haut en bas.\n\n## Les composants\nChaque solution se réalise par des **composants** : un ressort, un engrenage, une vis, un moteur, un interrupteur. Un même composant peut servir plusieurs fonctions.\n\n## Faire des choix\n| Le critère de comparaison | |\n| Prix | Masse |\n| Résistance | Facilité de **réparation** |\n| Impact environnemental | |\n\n> Un tableau de comparaison rend le choix **explicite** au lieu de le laisser à l’intuition.', 1),
  ('c7f3497b-c95f-5db7-8de9-592ebf7ce96c', '03bdc09b-46eb-5ca6-a7a3-6b8af8a1d49c', 'Pourquoi les objets changent', E'Un objet technique n’apparaît pas d’un coup : il évolue. Et ce qui évolue, ce n’est presque jamais sa fonction d’usage.\n\n## Ce qui pousse l’évolution\n| Le moteur | Ce qu’il apporte |\n| Les **progrès techniques** | Nouveaux matériaux, nouvelles énergies, électronique |\n| Les **besoins** qui changent | Aller plus vite, plus loin, plus confortablement |\n| La **société** | Lois de sécurité, normes, préoccupations environnementales |\n| L’**économie** | Produire moins cher, en plus grande quantité |\n\n## Un exemple : l’éclairage\n~ Feu → bougie → lampe à huile → bec de gaz → lampe à incandescence → fluocompacte → LED\n\nÀ chaque étape : **plus de lumière**, **moins d’énergie**, **moins de danger**.\n\n= La LED consomme environ dix fois moins que l’ampoule à filament, pour le même éclairage\n\n## Ce qui reste, ce qui change\n| Ce qui reste | Ce qui change |\n| La **fonction d’usage** — éclairer, se déplacer, conserver | Les **solutions techniques** |\n\n> On n’a jamais cessé d’avoir besoin de lumière. On a cessé d’utiliser le feu pour l’obtenir.\n\n## Familles et lignées\n| Le mot | Ce qu’il regroupe |\n| Une **famille** | Les objets qui remplissent la **même fonction d’usage** à une même époque |\n| Une **lignée** | Un objet suivi **à travers le temps** |\n\n## Le progrès n’est pas automatique\n!> Un objet plus récent **n’est pas meilleur sur tous les critères** : il peut être plus difficile à réparer, plus coûteux à produire, ou dépendant de matériaux rares.\n\nC’est pour cela que l’**analyse du cycle de vie** — extraction, fabrication, usage, fin de vie — est devenue un critère de conception.', 1),
  ('1a3fcc4a-f765-56c5-983d-bff3067c2701', '14f83a33-63c3-5829-b7bb-89bffb4ae51f', 'De quoi les objets sont faits', E'On ne choisit pas un matériau parce qu’il est « meilleur ». On le choisit parce que ses propriétés correspondent aux contraintes.\n\n## Les grandes familles\n| La famille | Ses qualités | Sa limite |\n| Les **métaux** — fer, acier, aluminium, cuivre | Résistants, conducteurs, **recyclables à l’infini** | Souvent lourds |\n| Les **plastiques** | Légers, faciles à mouler, isolants, peu chers | Issus du **pétrole**, longs à se dégrader |\n| Les **céramiques et verres** | Durs, résistants à la chaleur | **Fragiles** : ils cassent net |\n| Les **matériaux organiques** — bois, papier, cuir | **Renouvelables** | |\n| Les **composites** — béton armé, fibre de carbone, contreplaqué | Ils cumulent les qualités de plusieurs matériaux | Difficiles à recycler |\n\n## Les propriétés qu’on mesure\n| La propriété | Ce qu’elle dit |\n| La **dureté** | Il résiste à la rayure |\n| L’**élasticité** | Il reprend sa forme |\n| La **résistance** | Il supporte un effort sans casser |\n| La **masse volumique** | Léger ou lourd à volume égal |\n| La **conductivité** | Électrique et thermique |\n| La résistance à la **corrosion** | À l’eau, à la chaleur |\n\n## Le choix, en pratique\n~ Une casserole : métal pour le corps (il CONDUIT la chaleur) → plastique pour le manche (il ISOLE)\n\n> Deux matériaux dans un même objet, chacun pour une raison précise et opposée.\n\n## L’origine et le coût\n!> L’**aluminium** est très recyclable, mais sa production **initiale** consomme énormément d’électricité. Un matériau recyclable n’est pas pour autant un matériau bon marché à produire.\n\n## Le recyclage\n| Le matériau | Son recyclage |\n| Le **verre**, les **métaux** | Presque **indéfiniment** |\n| Le **plastique** | Il se **dégrade à chaque cycle** et finit par sortir de la boucle |', 1),
  ('0f746055-5a56-57de-871e-82745b273483', '6fb7180b-9054-5ddb-9a94-721619109053', 'Ce que coûte un objet, au-delà de son prix', E'Avant de vouloir réduire un impact, il faut savoir où il se trouve. Sinon on optimise ce qui ne pèse rien.\n\n## Le cycle de vie\n~ Extraction → fabrication → transport → utilisation → fin de vie\n\n| L’étape | Son coût |\n| L’**extraction** | Des matières premières |\n| La **fabrication** | Énergie, eau, rejets |\n| Le **transport** | Souvent des milliers de kilomètres |\n| L’**utilisation** | L’énergie consommée pendant des années |\n| La **fin de vie** | Réemploi, recyclage, incinération ou décharge |\n\n## Où se joue l’impact\n| L’objet | L’étape qui domine | Le geste utile |\n| Un **smartphone** | La **fabrication** | Le garder **deux ans de plus** |\n| Un **réfrigérateur** | L’**usage**, sur quinze ans | Choisir un bon rendement |\n\n!> L’impact n’est pas toujours là où on le croit. Recharger « proprement » un smartphone pèse bien moins que retarder son remplacement.\n\n## Les leviers, dans l’ordre d’efficacité\n1. **Ne pas produire** l’objet : s’en passer, le partager, le louer ;\n2. **allonger sa durée de vie** : entretenir, réparer, revendre ;\n3. **réemployer** : une seconde vie sans transformation ;\n4. **recycler** : refaire de la matière — utile, mais coûteux en énergie ;\n5. **valoriser** : incinérer en récupérant la chaleur, en dernier recours.\n\n> L’ordre compte autant que la liste : recycler est le **quatrième** levier, pas le premier.\n\n## L’obsolescence\nUn objet peut cesser d’être utilisé **alors qu’il fonctionne** : pièces indisponibles, logiciel qui ne se met plus à jour, mode.\n\n@ 2021 — L’indice de réparabilité devient obligatoire en France\n\n## L’écoconception\n| Le principe | Ce qu’il donne |\n| Moins de **matière** | |\n| Des matériaux **recyclables** | |\n| Un assemblage **démontable** | Vis plutôt que colle |\n| Des **pièces détachées** disponibles | |', 1),
  ('916bd092-12b0-52db-92bb-318b3e511102', 'aa23b9a5-3ea4-5f87-9ea0-bed7365ca6f2', 'Dessiner pour se faire comprendre', E'Un objet ne se fabrique pas à partir d’une description orale. Il lui faut un dessin que tout le monde lise de la même façon.\n\n## Les trois niveaux\n| Le dessin | Ce qu’il montre | Sa précision |\n| Le **croquis** | Une **idée** | À main levée, sans échelle exacte |\n| Le **schéma** | Le **fonctionnement** ou les liaisons | Simplifié, avec des **symboles normalisés** |\n| Le **plan** (dessin technique) | Comment **fabriquer** | À l’**échelle**, coté |\n\n!> Le **schéma ne ressemble pas à l’objet**. Il montre comment ça marche, pas à quoi ça ressemble.\n\n> Le croquis dit « voilà l’idée », le schéma dit « voilà comment ça marche », le plan dit « voilà comment le faire ».\n\n## L’échelle\n| L’échelle | Ce qu’elle signifie |\n| **1:1** | Taille réelle |\n| **1:10** | Le dessin est **10 fois plus petit** |\n| **10:1** | Le dessin est **10 fois plus grand** — pour une petite pièce |\n\n## Les vues\n~ Vue de face → vue de dessus → vue de gauche\n\nEnsemble, ces trois vues planes décrivent l’objet **sans ambiguïté**.\n\n!> La **perspective** donne une idée du volume, mais **ne permet pas de mesurer**. Ce n’est pas un dessin de fabrication.\n\n## Les cotes\nLes **cotes** indiquent les dimensions **réelles**, en **millimètres**, quelle que soit l’échelle du dessin.\n\n> On ne mesure jamais sur le papier : on **lit la cote**.\n\n## Les outils numériques\nLa **conception assistée par ordinateur** (CAO) permet de dessiner en 3D, de tester avant de fabriquer, et d’envoyer le fichier directement à une imprimante 3D ou à une découpeuse.', 1),
  ('3c1a95a4-7eae-5f2b-a1b3-b0d6a2f6c0b5', 'b83df816-835e-5261-8888-e3668a808edc', 'Du plan à l’objet réel', E'La gamme de fabrication est la suite ordonnée des opérations. Sans elle, chacun s’y prend autrement et les pièces ne s’assemblent pas.\n\n## Les grandes opérations\n~ Mesurer et tracer → découper → percer, usiner, poncer → assembler → contrôler → finir\n\n| L’opération | Les outils |\n| **Mesurer et tracer** | Reporter les cotes du plan sur la matière |\n| **Découper** | Scie, cisaille, découpeuse laser |\n| **Contrôler** | Vérifier que la pièce est conforme au plan |\n| **Finir** | Peinture, vernis, protection |\n\n## Les assemblages\n| Le type | Ses moyens | Sa conséquence |\n| **Démontable** | Vis, boulons, clips | On peut **réparer** et recycler |\n| **Permanent** | Colle, soudure, rivet | Plus solide, mais **difficile à réparer** |\n\n!> Choisir la colle plutôt que la vis, c’est décider **à la conception** que l’objet ne sera jamais réparé. Ce n’est pas un détail technique : c’est un choix de durée de vie.\n\n## Le contrôle qualité\n| On vérifie | Avec quoi |\n| Les **dimensions** | Pied à coulisse, gabarit |\n| L’**aspect** | À l’œil |\n| Le **fonctionnement** | En essai |\n\n= La tolérance : l’écart acceptable autour de la cote\n\nUne pièce hors tolérance est **refusée**.\n\n## La sécurité\n!> Lunettes, gants, cheveux attachés, machine **arrêtée avant tout réglage**, un seul opérateur à la fois. Les consignes ne sont pas des formalités : les machines de l’atelier coupent, percent et chauffent.\n\n## Prototype et série\n| L’étape | Son rôle |\n| Le **prototype** | Le premier exemplaire : il sert à **tester et corriger** |\n| La **série** | Des outillages rendent chaque pièce **identique** |', 1),
  ('d4e982cd-0bf3-5eb6-987a-3ede655d4ca8', 'a4015043-2efc-542d-99ab-508226b73e2c', 'Les deux circuits de tout objet technique', E'Le capteur est l’oreille, le microcontrôleur le cerveau, l’actionneur le muscle. Ces trois mots suffisent à lire n’importe quel objet.\n\n## Deux chaînes en parallèle\n| La chaîne | Ce qu’elle fait |\n| D’**information** | Elle **acquiert**, **traite** et **communique** |\n| D’**énergie** | Elle **alimente**, **distribue**, **convertit** et **transmet** |\n\n## La chaîne d’information\n| L’étape | Le composant | Son rôle |\n| **Acquérir** | Le **capteur** | Il transforme une grandeur physique en signal : température, lumière, présence, bouton-poussoir |\n| **Traiter** | La **carte programmable** (microcontrôleur) | Elle décide, selon le programme |\n| **Communiquer** | Écran, LED, haut-parleur | Le résultat part vers la chaîne d’énergie ou vers l’utilisateur |\n\n## La chaîne d’énergie\n| L’étape | Le composant | Son rôle |\n| **Alimenter** | Pile, secteur, batterie, panneau solaire | Fournir l’énergie |\n| **Distribuer** | Interrupteur, relais | Laisser passer ou non |\n| **Convertir** | L’**actionneur** | Moteur (mouvement), lampe (lumière), résistance (chaleur), buzzer (son) |\n| **Transmettre** | Engrenages, courroies, roues | Porter l’action jusqu’au bout |\n\n## Un exemple complet\n~ Capteur de présence → carte programmable → relais → lampe\n\nInformation à gauche, énergie à droite, et le programme au milieu qui décide.\n\n## Pourquoi les séparer\n!> Les pannes ne se cherchent pas au même endroit. Si la lampe ne s’allume pas : soit le **capteur** n’a rien vu (information), soit l’**alimentation** est coupée (énergie).\n\n> Distinguer les deux chaînes, c’est diviser le problème en deux.', 1),
  ('a188e6c2-bd8a-552e-87df-0d71f9e0c3a7', '88c473ff-8210-5cb9-96f7-77dd8c1bfb61', 'Donner des instructions à une carte', E'Une machine n’interprète pas : elle exécute exactement ce qui est écrit.\n\n## Le programme\nUne suite d’**instructions** que la carte exécute **dans l’ordre**. Il s’écrit par blocs (Scratch, mBlock) ou en texte (Python), puis se **téléverse** dans la carte.\n\n## Les briques de base\n| La brique | Ce qu’elle fait |\n| L’**instruction** | Une action simple : allumer, attendre, lire un capteur |\n| La **boucle** | Répéter sans réécrire : *répéter 10 fois*, *répéter indéfiniment* |\n| La **condition** | *si … alors … sinon …* — c’est elle qui rend l’objet capable de **réagir** |\n| La **variable** | Une case mémoire nommée : un compteur, une mesure |\n\n## Un exemple lisible\n= répéter indéfiniment : si le capteur de présence est activé, alors allumer la lampe et attendre 30 s ; sinon éteindre\n\n> Trois lignes, et l’objet devient automatique.\n\n## L’organigramme\n| Le symbole | Ce qu’il représente |\n| Le **rectangle** | Une action |\n| Le **losange** | Une décision |\n| La **flèche** | L’ordre d’exécution |\n\n> Le **logigramme** se lit sans connaître le langage : c’est ce qui permet d’en discuter à plusieurs, avant d’écrire une ligne.\n\n## Tester et déboguer\n~ Tester → isoler l’instruction fautive → corriger → retester\n\n!> Un **bug** n’est pas un échec : c’est une étape normale. Quand le résultat surprend, c’est presque toujours le **programme qui a raison** et l’**intention** qui était floue.\n\n## Les objets connectés\nUne carte peut envoyer ses mesures sur un réseau : c’est l’**objet connecté**.\n\n!> Cela pose des questions de **sécurité** et de **données personnelles** : qui reçoit ces mesures, et pour en faire quoi ?', 1),
  ('dd7792b6-23f8-5067-8cfa-1dc418af5947', 'b9efad07-39af-5d74-9261-8dbbd463217b', 'Comment les objets se parlent', E'Le « nuage » n’a rien d’immatériel : c’est un bâtiment climatisé plein de machines, quelque part sur la planète.\n\n## L’information numérique\n= Le binaire : deux états seulement, 0 et 1\n\n~ Textes, images, sons, mesures → convertis en 0 et 1 → transmis → reconvertis à l’arrivée\n\n## Les unités\n| L’unité | Sa valeur |\n| Le **bit** | L’unité de base |\n| L’**octet** | **8 bits** |\n| **ko**, **Mo**, **Go**, **To** | Les multiples |\n\nUne photo de téléphone pèse quelques **Mo**, un film quelques **Go**.\n\n## Les supports de transmission\n| Le support | Sous quelle forme |\n| Le **câble électrique** | Un **courant** |\n| Les **ondes** — wifi, Bluetooth, téléphonie | Sans fil, dans l’air |\n| La **fibre optique** | De la **lumière**, dans un fil de verre |\n\n> La fibre est le support le plus rapide, et celui qui porte le plus de données.\n\n## Le réseau\nUn **réseau** relie des machines pour qu’elles échangent. **Internet** est le réseau des réseaux.\n\n~ Les données sont découpées en PAQUETS → chaque paquet emprunte son propre chemin → ils sont réassemblés à l’arrivée\n\nChaque machine y possède une **adresse IP**.\n\n## Le stockage\nDisque dur, mémoire flash, carte SD, ou **serveur distant** — le « cloud ».\n\n!> Le « cloud », c’est l’**ordinateur de quelqu’un d’autre**, dans un centre de données bien réel, qui consomme de l’électricité.\n\n## Sécurité et responsabilité\n~ Un mot de passe solide → des mises à jour → de la prudence sur ce qu’on publie\n\n!> Une donnée transmise peut être **copiée**, **conservée** et **rediffusée** sans qu’on le sache. Ce qu’on met en ligne **échappe vite à son auteur**.', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('458fecce-5f40-5ba9-a3f4-87e853f9235f'::uuid, 'Quiz — Pourquoi cet objet existe', 'Technologie', '6e', 'Le besoin et la fonction d’usage', 'c9d13c45-5924-5c72-a553-30f97f3b2518'::uuid),
    ('d470fa5a-3d93-5fb3-bc87-6d4a5c411952'::uuid, 'Quiz — Comment l’objet fait ce qu’il fait', 'Technologie', '6e', 'Les fonctions techniques et les solutions', '2ffb2547-6a8d-50aa-97ae-d21c08a1fe40'::uuid),
    ('525b9ec3-189a-53e6-9388-35c91cb9b7b9'::uuid, 'Quiz — Pourquoi les objets changent', 'Technologie', '6e', 'L’évolution des objets techniques', 'c7f3497b-c95f-5db7-8de9-592ebf7ce96c'::uuid),
    ('9e691322-0af0-554a-b855-4349173fee9f'::uuid, 'Quiz — De quoi les objets sont faits', 'Technologie', '6e', 'Les familles de matériaux', '1a3fcc4a-f765-56c5-983d-bff3067c2701'::uuid),
    ('885cd9d1-5efb-536a-9b9b-97259bb080a0'::uuid, 'Quiz — Ce que coûte un objet, au-delà de son prix', 'Technologie', '6e', 'L’impact environnemental des objets', '0f746055-5a56-57de-871e-82745b273483'::uuid),
    ('911b57de-8e67-5047-a151-80255d6dd5ca'::uuid, 'Quiz — Dessiner pour se faire comprendre', 'Technologie', '6e', 'Croquis, schémas et plans', '916bd092-12b0-52db-92bb-318b3e511102'::uuid),
    ('831a9615-cb1d-5ec9-ab20-d371831d4019'::uuid, 'Quiz — Du plan à l’objet réel', 'Technologie', '6e', 'Fabriquer un objet', '3c1a95a4-7eae-5f2b-a1b3-b0d6a2f6c0b5'::uuid),
    ('5adcc223-ede5-5f74-bf9a-45fa548a4362'::uuid, 'Quiz — Les deux circuits de tout objet technique', 'Technologie', '6e', 'La chaîne d’information et la chaîne d’énergie', 'd4e982cd-0bf3-5eb6-987a-3ede655d4ca8'::uuid),
    ('55d37aeb-f866-5c3c-9b55-0548d8855ef5'::uuid, 'Quiz — Donner des instructions à une carte', 'Technologie', '6e', 'Programmer un objet technique', 'a188e6c2-bd8a-552e-87df-0d71f9e0c3a7'::uuid),
    ('3e987436-78a6-55af-9a2a-24a89581ed30'::uuid, 'Quiz — Comment les objets se parlent', 'Technologie', '6e', 'L’information et sa circulation', 'dd7792b6-23f8-5067-8cfa-1dc418af5947'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('0232ab35-1b07-5ce4-a92e-0019daaa8463'::uuid, '458fecce-5f40-5ba9-a3f4-87e853f9235f'::uuid, 'Qu’est-ce qu’un objet technique ?', 'mcq', '["Un objet fabriqué par l’humain pour répondre à un besoin","Tout objet naturel","Un objet électrique","Un objet en métal"]'::jsonb, 0, 'Un caillou n’en est pas un, un marteau si.', 1),
    ('87866b93-3272-5503-94fe-265a1191e59c'::uuid, '458fecce-5f40-5ba9-a3f4-87e853f9235f'::uuid, 'À quelle question répond la fonction d’usage ?', 'mcq', '["À quoi ça sert ?","Comment c’est fait ?","Combien ça coûte ?","Qui l’a inventé ?"]'::jsonb, 0, 'Elle s’exprime par un verbe à l’infinitif.', 2),
    ('ca4e2848-f9f8-5e44-bce7-b10d5bad9b51'::uuid, '458fecce-5f40-5ba9-a3f4-87e853f9235f'::uuid, 'Quelle est la fonction d’usage d’un parapluie ?', 'mcq', '["Protéger de la pluie","Être élégant","Coûter peu cher","Se ranger facilement"]'::jsonb, 0, 'Un verbe à l’infinitif + un complément.', 3),
    ('3ae8d6a4-ef33-5ec5-8163-029fdfa1e17b'::uuid, '458fecce-5f40-5ba9-a3f4-87e853f9235f'::uuid, 'Qu’est-ce que la fonction d’estime ?', 'mcq', '["Ce qui fait préférer un objet à un autre rendant le même service","Ce à quoi l’objet sert","Le prix de l’objet","La matière de l’objet"]'::jsonb, 0, 'Couleur, forme, marque.', 4),
    ('74dd810c-83af-54a5-ae5a-636726ded217'::uuid, '458fecce-5f40-5ba9-a3f4-87e853f9235f'::uuid, 'Qu’est-ce qu’un cahier des charges ?', 'mcq', '["La liste des contraintes que l’objet devra respecter","Le mode d’emploi","La facture","Le plan de fabrication"]'::jsonb, 0, 'Il dit ce que l’objet doit faire, pas comment.', 5),
    ('a0b0274f-96da-58cc-b3e0-54f4e8204ac8'::uuid, '458fecce-5f40-5ba9-a3f4-87e853f9235f'::uuid, 'Qu’est-ce qui précède toujours l’objet technique ?', 'mcq', '["Le besoin","Le matériau","Le prix","La marque"]'::jsonb, 0, 'On a inventé le vélo parce qu’on voulait se déplacer.', 6),
    ('0078057b-0356-5793-993b-b21aa1e81c08'::uuid, '458fecce-5f40-5ba9-a3f4-87e853f9235f'::uuid, 'Pourquoi un même besoin peut-il donner des objets différents ?', 'mcq', '["Parce que les utilisateurs sont différents","Parce que les matériaux manquent","Par hasard","Pour augmenter les prix"]'::jsonb, 0, 'Concevoir, c’est d’abord regarder l’utilisateur.', 7),
    ('25ff3172-d567-5c64-92ad-e37fe738a7da'::uuid, '458fecce-5f40-5ba9-a3f4-87e853f9235f'::uuid, 'La fonction d’usage et la fonction d’estime sont la même chose.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'L’une dit à quoi ça sert, l’autre pourquoi on choisit celui-là.', 8),
    ('826ea485-de9f-57f9-99cd-c4caa8e1bd44'::uuid, 'd470fa5a-3d93-5fb3-bc87-6d4a5c411952'::uuid, 'Que dit une fonction technique ?', 'mcq', '["Comment l’objet parvient à rendre son service","À quoi l’objet sert","Combien il coûte","Qui l’utilise"]'::jsonb, 0, 'C’est la tâche d’une partie de l’objet.', 1),
    ('20e28941-b4ce-57e0-a492-3d45b191471a'::uuid, 'd470fa5a-3d93-5fb3-bc87-6d4a5c411952'::uuid, 'Quelle est une fonction technique du vélo ?', 'mcq', '["Transmettre le mouvement","Se déplacer","Être rouge","Coûter 300 euros"]'::jsonb, 0, '« Se déplacer » est la fonction d’usage.', 2),
    ('7a71ec36-af6a-5271-8ca6-bc4855f5805b'::uuid, 'd470fa5a-3d93-5fb3-bc87-6d4a5c411952'::uuid, 'Qu’est-ce qu’une solution technique ?', 'mcq', '["Une façon parmi d’autres de réaliser une fonction technique","Le but de l’objet","Le matériau utilisé","Le prix de vente"]'::jsonb, 0, 'Freiner peut se faire par patins ou par disque.', 3),
    ('76ecd211-e1c2-5e0b-a00e-4647a4668f18'::uuid, 'd470fa5a-3d93-5fb3-bc87-6d4a5c411952'::uuid, 'Sur quoi le concepteur s’appuie-t-il pour choisir une solution ?', 'mcq', '["Le cahier des charges","Son intuition seule","La mode","Le hasard"]'::jsonb, 0, 'Coût, poids, entretien, sécurité.', 4),
    ('319b9574-17e8-5c5e-a9a0-0db4bb6ade03'::uuid, 'd470fa5a-3d93-5fb3-bc87-6d4a5c411952'::uuid, 'Comment représente-t-on l’ensemble des fonctions ?', 'mcq', '["Par un diagramme en arbre","Par une liste alphabétique","Par un graphique circulaire","Par une photo"]'::jsonb, 0, 'Fonction d’usage en haut, fonctions techniques en dessous.', 5),
    ('dff4bf7a-d0a3-573a-afb5-3d40183963ba'::uuid, 'd470fa5a-3d93-5fb3-bc87-6d4a5c411952'::uuid, 'Qu’est-ce qu’un composant ?', 'mcq', '["L’élément concret qui réalise une solution technique","Le besoin de départ","Le cahier des charges","L’utilisateur"]'::jsonb, 0, 'Ressort, engrenage, vis, moteur.', 6),
    ('0d367762-7bb8-5a08-b01f-c0d7fb601207'::uuid, 'd470fa5a-3d93-5fb3-bc87-6d4a5c411952'::uuid, 'Comment comparer deux solutions techniques ?', 'mcq', '["En pesant des critères dans un tableau","En choisissant la moins chère toujours","En prenant la plus récente","Au hasard"]'::jsonb, 0, 'Cela rend le choix explicite.', 7),
    ('7f0aa52f-666c-5b74-bbbd-47f2c9bdaca1'::uuid, 'd470fa5a-3d93-5fb3-bc87-6d4a5c411952'::uuid, 'Une fonction technique n’admet qu’une seule solution possible.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est un problème, et il y a toujours plusieurs réponses.', 8),
    ('83b0e0fd-a6a4-5646-98a6-e5488d9c645c'::uuid, '525b9ec3-189a-53e6-9388-35c91cb9b7b9'::uuid, 'Qu’est-ce qui pousse un objet technique à évoluer ?', 'mcq', '["Progrès techniques, besoins, société et économie","Uniquement la mode","Uniquement le prix","Rien, ils ne changent pas"]'::jsonb, 0, 'Plusieurs causes agissent ensemble.', 1),
    ('4a99a990-f279-52f1-8f2e-99efa5166e32'::uuid, '525b9ec3-189a-53e6-9388-35c91cb9b7b9'::uuid, 'Qu’est-ce qui reste souvent identique au fil de l’évolution ?', 'mcq', '["La fonction d’usage","Les solutions techniques","Les matériaux","Le prix"]'::jsonb, 0, 'On a toujours eu besoin de lumière.', 2),
    ('7ff87387-189d-59e8-9d59-43f2816d0db1'::uuid, '525b9ec3-189a-53e6-9388-35c91cb9b7b9'::uuid, 'Quelle est la lignée de l’éclairage ?', 'mcq', '["Feu, bougie, lampe à huile, gaz, incandescence, LED","LED, bougie, feu","Gaz, feu, bougie","Incandescence, feu, LED"]'::jsonb, 0, 'Chaque étape apporte plus de lumière pour moins d’énergie.', 3),
    ('9b6739e7-62fa-58c7-8517-3f4a6960fb61'::uuid, '525b9ec3-189a-53e6-9388-35c91cb9b7b9'::uuid, 'Combien la LED consomme-t-elle par rapport à l’ampoule à filament ?', 'mcq', '["Environ dix fois moins","Autant","Deux fois plus","Cent fois moins"]'::jsonb, 0, 'Pour un éclairage équivalent.', 4),
    ('83e16e4f-20cf-564d-82bc-3bd5c3537e2a'::uuid, '525b9ec3-189a-53e6-9388-35c91cb9b7b9'::uuid, 'Qu’est-ce qu’une famille d’objets techniques ?', 'mcq', '["Des objets remplissant la même fonction d’usage à une même époque","Un objet suivi dans le temps","Des objets du même fabricant","Des objets de même couleur"]'::jsonb, 0, 'La lignée, elle, suit un objet à travers le temps.', 5),
    ('087a36ae-726a-5e04-9973-89e64e16d3cf'::uuid, '525b9ec3-189a-53e6-9388-35c91cb9b7b9'::uuid, 'Qu’est-ce que l’analyse du cycle de vie ?', 'mcq', '["L’étude de l’objet de l’extraction à la fin de vie","La durée de la garantie","Le temps de fabrication","La durée d’utilisation seule"]'::jsonb, 0, 'Elle est devenue un critère de conception.', 6),
    ('afdfc5c6-00d4-5880-80f5-a062bb29abf3'::uuid, '525b9ec3-189a-53e6-9388-35c91cb9b7b9'::uuid, 'Un objet plus récent est-il toujours meilleur ?', 'mcq', '["Non : il peut être plus difficile à réparer ou dépendre de matériaux rares","Oui, toujours","Oui, sauf pour le prix","Cela ne se mesure pas"]'::jsonb, 0, 'Le progrès n’est pas automatique sur tous les critères.', 7),
    ('4f90fde4-b955-5df7-8dfe-dfa8ff18c8d0'::uuid, '525b9ec3-189a-53e6-9388-35c91cb9b7b9'::uuid, 'La fonction d’usage change à chaque évolution technique.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Ce sont les solutions techniques qui changent.', 8),
    ('1de0bcb0-4c64-5960-a9ac-bf3cb44b8302'::uuid, '9e691322-0af0-554a-b855-4349173fee9f'::uuid, 'Quelle famille regroupe le fer, l’aluminium et le cuivre ?', 'mcq', '["Les métaux","Les plastiques","Les céramiques","Les composites"]'::jsonb, 0, 'Résistants et conducteurs.', 1),
    ('4e1c0d21-75dc-5338-8b94-a8dfda4b7453'::uuid, '9e691322-0af0-554a-b855-4349173fee9f'::uuid, 'Quelle est la principale origine des plastiques ?', 'mcq', '["Le pétrole","Le bois","Le sable","Le minerai de fer"]'::jsonb, 0, 'Ils sont longs à se dégrader.', 2),
    ('360af84d-6f4e-5774-9b4a-c731eaa353e0'::uuid, '9e691322-0af0-554a-b855-4349173fee9f'::uuid, 'Qu’est-ce qu’un matériau composite ?', 'mcq', '["Plusieurs matériaux associés pour cumuler leurs qualités","Un métal très pur","Un plastique recyclé","Un matériau naturel"]'::jsonb, 0, 'Béton armé, fibre de carbone, contreplaqué.', 3),
    ('55b2582d-f67f-5d07-bd29-1f9e13314309'::uuid, '9e691322-0af0-554a-b855-4349173fee9f'::uuid, 'Quelle propriété désigne la résistance à la rayure ?', 'mcq', '["La dureté","L’élasticité","La conductivité","La masse volumique"]'::jsonb, 0, 'L’élasticité, c’est reprendre sa forme.', 4),
    ('24e9602f-a0ea-5464-b79c-4fdc1d80947b'::uuid, '9e691322-0af0-554a-b855-4349173fee9f'::uuid, 'Pourquoi le manche d’une casserole est-il en plastique ?', 'mcq', '["Parce que le plastique est isolant thermique","Parce qu’il est plus dur","Parce qu’il coûte plus cher","Parce qu’il conduit la chaleur"]'::jsonb, 0, 'Chaque matériau est choisi pour une raison précise.', 5),
    ('0b6c2721-03d8-510e-90b6-c29432147191'::uuid, '9e691322-0af0-554a-b855-4349173fee9f'::uuid, 'Quels matériaux se recyclent presque indéfiniment ?', 'mcq', '["Le verre et les métaux","Les plastiques","Le bois","Les composites"]'::jsonb, 0, 'Le plastique se dégrade à chaque cycle.', 6),
    ('4be194c3-2296-5a92-8166-e342ab2f47ea'::uuid, '9e691322-0af0-554a-b855-4349173fee9f'::uuid, 'Quelle est la faiblesse des céramiques et des verres ?', 'mcq', '["Ils sont fragiles et cassent net","Ils fondent à basse température","Ils conduisent l’électricité","Ils rouillent"]'::jsonb, 0, 'Ils sont pourtant durs et résistants à la chaleur.', 7),
    ('b8393b24-f1b4-54d2-baea-55d366a680ce'::uuid, '9e691322-0af0-554a-b855-4349173fee9f'::uuid, 'On choisit un matériau parce qu’il est meilleur que les autres.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'On le choisit parce que ses propriétés répondent aux contraintes.', 8),
    ('2b000dad-7416-5b4c-99b0-92d08f338f51'::uuid, '885cd9d1-5efb-536a-9b9b-97259bb080a0'::uuid, 'Quelles sont les cinq étapes du cycle de vie d’un objet ?', 'mcq', '["Extraction, fabrication, transport, utilisation, fin de vie","Achat, usage, revente","Conception, vente, recyclage","Fabrication, vente, réparation"]'::jsonb, 0, 'Chacune a un coût environnemental.', 1),
    ('eea5c181-88c1-5c52-9062-d7cb8b0a02e2'::uuid, '885cd9d1-5efb-536a-9b9b-97259bb080a0'::uuid, 'Où se situe l’essentiel de l’impact d’un smartphone ?', 'mcq', '["Dans sa fabrication","Dans son utilisation","Dans son transport","Dans sa fin de vie"]'::jsonb, 0, 'Le garder plus longtemps est donc le meilleur levier.', 2),
    ('2f4cf112-28a6-5b30-8741-860887867af7'::uuid, '885cd9d1-5efb-536a-9b9b-97259bb080a0'::uuid, 'Où se situe l’essentiel de l’impact d’un réfrigérateur ?', 'mcq', '["Dans son utilisation, sur quinze ans","Dans sa fabrication","Dans son transport","Dans son emballage"]'::jsonb, 0, 'C’est l’inverse du smartphone.', 3),
    ('11669c1c-6ba8-566b-89fb-c31532068a79'::uuid, '885cd9d1-5efb-536a-9b9b-97259bb080a0'::uuid, 'Quel est le levier le plus efficace pour réduire l’impact ?', 'mcq', '["Ne pas produire l’objet : s’en passer, le partager, le louer","Le recycler","L’incinérer","Le transporter autrement"]'::jsonb, 0, 'Le recyclage vient loin après.', 4),
    ('d8cc13fb-2aca-50d3-b538-00879e935b70'::uuid, '885cd9d1-5efb-536a-9b9b-97259bb080a0'::uuid, 'Qu’est-ce que l’obsolescence ?', 'mcq', '["Un objet cesse d’être utilisé alors qu’il fonctionne","Un objet qui casse","Un objet recyclé","Un objet neuf"]'::jsonb, 0, 'Pièces indisponibles, logiciel non mis à jour, mode.', 5),
    ('baa510fd-982a-5a37-a275-2ce8dc70917b'::uuid, '885cd9d1-5efb-536a-9b9b-97259bb080a0'::uuid, 'Qu’est-ce que l’indice de réparabilité ?', 'mcq', '["Une note affichée qui informe sur la facilité de réparation","Le prix des pièces","La durée de la garantie","Le poids de l’objet"]'::jsonb, 0, 'Affiché en France depuis 2021.', 6),
    ('3c723641-a5cf-52ae-9dcd-41fa835b1693'::uuid, '885cd9d1-5efb-536a-9b9b-97259bb080a0'::uuid, 'Qu’est-ce que l’écoconception ?', 'mcq', '["Concevoir en pensant à tout le cycle de vie","Fabriquer avec du plastique recyclé seulement","Vendre moins cher","Produire localement uniquement"]'::jsonb, 0, 'Moins de matière, assemblage démontable, pièces disponibles.', 7),
    ('dbdf34b2-64b9-5949-9212-ea99b56cabba'::uuid, '885cd9d1-5efb-536a-9b9b-97259bb080a0'::uuid, 'Recycler un objet est le meilleur moyen de réduire son impact.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Allonger sa durée de vie et ne pas le produire sont plus efficaces.', 8),
    ('32db53e1-bee4-5b96-8592-03d342738283'::uuid, '911b57de-8e67-5047-a151-80255d6dd5ca'::uuid, 'Qu’est-ce qu’un croquis ?', 'mcq', '["Un dessin à main levée qui montre une idée","Un dessin précis et coté","Un dessin avec des symboles normalisés","Une photographie"]'::jsonb, 0, 'Pas d’échelle exacte.', 1),
    ('4155c25f-1faa-54a4-bcc5-c34fc535e3a5'::uuid, '911b57de-8e67-5047-a151-80255d6dd5ca'::uuid, 'Que montre un schéma ?', 'mcq', '["Le fonctionnement ou les liaisons, avec des symboles","L’apparence exacte de l’objet","Les dimensions réelles","La couleur de l’objet"]'::jsonb, 0, 'Il ne ressemble pas à l’objet.', 2),
    ('9e137e05-0668-5d90-a695-50d81e8d5297'::uuid, '911b57de-8e67-5047-a151-80255d6dd5ca'::uuid, 'À quoi sert un plan technique ?', 'mcq', '["À fabriquer l’objet : il est à l’échelle et coté","À montrer une idée","À décorer","À vendre l’objet"]'::jsonb, 0, 'C’est le dessin le plus précis.', 3),
    ('cd4a6126-2b69-5c9f-8217-6a8d78c57b5f'::uuid, '911b57de-8e67-5047-a151-80255d6dd5ca'::uuid, 'Que signifie l’échelle 1:10 ?', 'mcq', '["Le dessin est 10 fois plus petit que le réel","Le dessin est 10 fois plus grand","Le dessin est à taille réelle","L’objet mesure 10 cm"]'::jsonb, 0, '10:1 serait l’inverse.', 4),
    ('8b9fa705-ad02-5a06-9bbc-5eac4fe62b83'::uuid, '911b57de-8e67-5047-a151-80255d6dd5ca'::uuid, 'Quelles sont les vues classiques d’un dessin technique ?', 'mcq', '["De face, de dessus, de gauche","De face seulement","En perspective seulement","De dessous et de droite"]'::jsonb, 0, 'Ensemble, elles décrivent l’objet sans ambiguïté.', 5),
    ('e61317b5-1883-58ae-b5aa-81f08cfca21d'::uuid, '911b57de-8e67-5047-a151-80255d6dd5ca'::uuid, 'Dans quelle unité les cotes sont-elles indiquées ?', 'mcq', '["En millimètres","En centimètres","En mètres","Selon l’échelle"]'::jsonb, 0, 'On lit la cote, on ne mesure jamais sur le papier.', 6),
    ('c33e5356-228a-5ad7-9fda-dc766b4843ba'::uuid, '911b57de-8e67-5047-a151-80255d6dd5ca'::uuid, 'Que permet la CAO ?', 'mcq', '["Dessiner en 3D, tester avant de fabriquer et piloter une machine","Uniquement imprimer des plans","Calculer un prix","Choisir un matériau automatiquement"]'::jsonb, 0, 'Imprimante 3D, découpeuse.', 7),
    ('4417405e-c5b1-5f9a-8b79-4ebc48dc0000'::uuid, '911b57de-8e67-5047-a151-80255d6dd5ca'::uuid, 'On peut mesurer directement sur un plan pour connaître les dimensions réelles.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'On lit les cotes : le dessin est à l’échelle, pas à la taille réelle.', 8),
    ('ab3ecdda-69f0-57bc-a7e3-376d37ed0ace'::uuid, '831a9615-cb1d-5ec9-ab20-d371831d4019'::uuid, 'Qu’est-ce qu’une gamme de fabrication ?', 'mcq', '["La suite ordonnée des opérations pour fabriquer l’objet","La liste des matériaux","Le prix de revient","Le plan coté"]'::jsonb, 0, 'Elle indique aussi les outils et les contrôles.', 1),
    ('3421f0c3-c7e6-5c7e-a635-84bcc8f1ef15'::uuid, '831a9615-cb1d-5ec9-ab20-d371831d4019'::uuid, 'Quel assemblage permet de réparer l’objet ?', 'mcq', '["Un assemblage démontable, par vis ou clips","Un assemblage collé","Une soudure","Un rivet"]'::jsonb, 0, 'Il facilite aussi le recyclage.', 2),
    ('3d7e8bf0-0940-5373-b7e3-31b3e0bf0912'::uuid, '831a9615-cb1d-5ec9-ab20-d371831d4019'::uuid, 'Que décide-t-on en choisissant la colle plutôt que la vis ?', 'mcq', '["Que l’objet ne sera pratiquement pas réparable","Qu’il sera moins cher à l’usage","Qu’il durera plus longtemps","Rien de particulier"]'::jsonb, 0, 'C’est un choix de durée de vie.', 3),
    ('5d32f4eb-0946-59d9-94a2-7c5c9d298cca'::uuid, '831a9615-cb1d-5ec9-ab20-d371831d4019'::uuid, 'Qu’est-ce que la tolérance ?', 'mcq', '["L’écart acceptable autour de la cote","Le temps de fabrication","Le prix maximal","La dureté du matériau"]'::jsonb, 0, 'Une pièce hors tolérance est refusée.', 4),
    ('cdf4688b-233f-528e-9500-c6f11288e741'::uuid, '831a9615-cb1d-5ec9-ab20-d371831d4019'::uuid, 'Quel outil sert à contrôler précisément une dimension ?', 'mcq', '["Le pied à coulisse","La scie","La perceuse","Le pinceau"]'::jsonb, 0, 'Ou un gabarit.', 5),
    ('47f1f7d9-46c2-51da-9777-ba3ce5fda9d1'::uuid, '831a9615-cb1d-5ec9-ab20-d371831d4019'::uuid, 'À quoi sert un prototype ?', 'mcq', '["À tester et corriger avant la série","À vendre en premier","À décorer","À remplacer le plan"]'::jsonb, 0, 'La série vient ensuite.', 6),
    ('5c6c9794-cc92-5541-9644-71edf1a4d3ee'::uuid, '831a9615-cb1d-5ec9-ab20-d371831d4019'::uuid, 'Quelle règle de sécurité s’applique avant un réglage ?', 'mcq', '["Arrêter la machine","Travailler plus vite","Retirer ses gants","Appeler un camarade"]'::jsonb, 0, 'Les machines coupent, percent et chauffent.', 7),
    ('f7d44d7b-4c56-5e85-9969-7ec008d5c32b'::uuid, '831a9615-cb1d-5ec9-ab20-d371831d4019'::uuid, 'La gamme de fabrication est facultative si l’on connaît le plan.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Sans elle, chacun s’y prend autrement et les pièces ne s’assemblent pas.', 8),
    ('fe83db29-b78a-574a-813d-c22610b95695'::uuid, '5adcc223-ede5-5f74-bf9a-45fa548a4362'::uuid, 'Quelles sont les deux chaînes d’un objet technique ?', 'mcq', '["La chaîne d’information et la chaîne d’énergie","La chaîne de production et de vente","La chaîne de montage et de contrôle","La chaîne mécanique et électrique"]'::jsonb, 0, 'Elles travaillent ensemble.', 1),
    ('d060f4bd-cf4c-5b0d-8846-5c55f1cacd9d'::uuid, '5adcc223-ede5-5f74-bf9a-45fa548a4362'::uuid, 'Que fait un capteur ?', 'mcq', '["Il transforme une grandeur physique en signal","Il produit du mouvement","Il stocke l’énergie","Il éclaire"]'::jsonb, 0, 'Température, lumière, présence.', 2),
    ('5a38551c-bd75-5a2d-862a-7d2dd65e69d9'::uuid, '5adcc223-ede5-5f74-bf9a-45fa548a4362'::uuid, 'Que fait un actionneur ?', 'mcq', '["Il transforme l’énergie en action","Il mesure une grandeur","Il décide selon un programme","Il stocke l’information"]'::jsonb, 0, 'Moteur, lampe, résistance, buzzer.', 3),
    ('e1623c6b-db32-5683-b921-61eca5520188'::uuid, '5adcc223-ede5-5f74-bf9a-45fa548a4362'::uuid, 'Quelles sont les trois fonctions de la chaîne d’information ?', 'mcq', '["Acquérir, traiter, communiquer","Alimenter, distribuer, convertir","Mesurer, couper, chauffer","Percer, assembler, contrôler"]'::jsonb, 0, 'Capteur, microcontrôleur, sortie.', 4),
    ('4a724b91-5845-53bb-96b5-3ded1acbec3e'::uuid, '5adcc223-ede5-5f74-bf9a-45fa548a4362'::uuid, 'Quelles sont les fonctions de la chaîne d’énergie ?', 'mcq', '["Alimenter, distribuer, convertir, transmettre","Acquérir, traiter, communiquer","Tracer, découper, assembler","Voir, décider, agir"]'::jsonb, 0, 'De la pile jusqu’aux engrenages.', 5),
    ('9e418404-d6fe-53be-aa09-17c5b7d6c6e1'::uuid, '5adcc223-ede5-5f74-bf9a-45fa548a4362'::uuid, 'Quel élément décide selon le programme ?', 'mcq', '["La carte programmable","Le capteur","L’actionneur","La pile"]'::jsonb, 0, 'C’est le microcontrôleur.', 6),
    ('7b868e54-6b02-5b4d-84f2-e62969d274ce'::uuid, '5adcc223-ede5-5f74-bf9a-45fa548a4362'::uuid, 'Pourquoi distingue-t-on les deux chaînes ?', 'mcq', '["Pour localiser une panne : information ou énergie","Par tradition","Pour réduire le prix","Pour accélérer la fabrication"]'::jsonb, 0, 'Cela divise le problème en deux.', 7),
    ('763eb65b-c86a-5658-84bc-90ae065259fb'::uuid, '5adcc223-ede5-5f74-bf9a-45fa548a4362'::uuid, 'Un moteur est un capteur.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est un actionneur : il transforme l’énergie en mouvement.', 8),
    ('128e210b-0335-561e-9170-83d7e50e2e93'::uuid, '55d37aeb-f866-5c3c-9b55-0548d8855ef5'::uuid, 'Qu’est-ce qu’un programme ?', 'mcq', '["Une suite d’instructions exécutées dans l’ordre","Un schéma de câblage","Un plan coté","Une liste de matériaux"]'::jsonb, 0, 'Il est téléversé dans la carte.', 1),
    ('43764a94-eb6a-518d-9439-513887208004'::uuid, '55d37aeb-f866-5c3c-9b55-0548d8855ef5'::uuid, 'À quoi sert une boucle ?', 'mcq', '["À répéter des instructions sans les réécrire","À arrêter le programme","À poser une question","À stocker une valeur"]'::jsonb, 0, '« Répéter indéfiniment ».', 2),
    ('eee9b762-0170-5559-bd40-a39cfe14f553'::uuid, '55d37aeb-f866-5c3c-9b55-0548d8855ef5'::uuid, 'Quelle instruction rend un objet capable de réagir ?', 'mcq', '["La condition « si … alors … sinon »","La boucle","La variable","L’instruction simple"]'::jsonb, 0, 'Elle fait dépendre l’action d’un capteur.', 3),
    ('89f9d0f0-7db7-5ca5-b484-60b4b6e65dc6'::uuid, '55d37aeb-f866-5c3c-9b55-0548d8855ef5'::uuid, 'Qu’est-ce qu’une variable ?', 'mcq', '["Une case mémoire nommée qui retient une valeur","Une instruction de répétition","Un capteur","Un actionneur"]'::jsonb, 0, 'Un compteur, une mesure.', 4),
    ('ab951944-7376-581c-b618-b3efcf7f6c40'::uuid, '55d37aeb-f866-5c3c-9b55-0548d8855ef5'::uuid, 'Qu’est-ce qu’un logigramme ?', 'mcq', '["Un schéma des actions et des décisions du programme","Le plan de la carte","La liste des composants","Le code source"]'::jsonb, 0, 'Rectangles pour les actions, losanges pour les décisions.', 5),
    ('3406c40e-9b23-5cfb-89ff-34099fcaae90'::uuid, '55d37aeb-f866-5c3c-9b55-0548d8855ef5'::uuid, 'Que faire quand un programme ne fonctionne pas ?', 'mcq', '["Tester pas à pas et isoler l’instruction fautive","Tout réécrire","Changer de carte","Abandonner"]'::jsonb, 0, 'Un bug est une étape normale.', 6),
    ('bbe3f376-c358-58fb-8028-1c282270a8c7'::uuid, '55d37aeb-f866-5c3c-9b55-0548d8855ef5'::uuid, 'Quelle question pose un objet connecté ?', 'mcq', '["Qui reçoit les données, et pour en faire quoi","Combien il pèse","De quelle couleur il est","Où il est fabriqué"]'::jsonb, 0, 'Sécurité et données personnelles.', 7),
    ('8015a952-6d95-5e9c-ad3b-5b4e0263669c'::uuid, '55d37aeb-f866-5c3c-9b55-0548d8855ef5'::uuid, 'Une machine interprète l’intention du programmeur.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle exécute exactement ce qui est écrit.', 8),
    ('3c9f9803-5a27-5509-8ec7-11311b9cfc84'::uuid, '3e987436-78a6-55af-9a2a-24a89581ed30'::uuid, 'Quels sont les deux états du langage binaire ?', 'mcq', '["0 et 1","A et B","Oui et non","+ et −"]'::jsonb, 0, 'Toute information y est convertie.', 1),
    ('06bef1c1-90f4-53e2-91c3-bc3e0ca22098'::uuid, '3e987436-78a6-55af-9a2a-24a89581ed30'::uuid, 'Combien de bits vaut un octet ?', 'mcq', '["8","2","10","16"]'::jsonb, 0, 'Puis viennent ko, Mo, Go, To.', 2),
    ('f6224657-41c1-5dc1-90e0-59acdb8e847b'::uuid, '3e987436-78a6-55af-9a2a-24a89581ed30'::uuid, 'Quel support transporte l’information sous forme de lumière ?', 'mcq', '["La fibre optique","Le câble électrique","Les ondes wifi","Le Bluetooth"]'::jsonb, 0, 'C’est le plus rapide.', 3),
    ('609beca7-74ef-56d6-aff2-8694563ed0d8'::uuid, '3e987436-78a6-55af-9a2a-24a89581ed30'::uuid, 'Comment les données voyagent-elles sur internet ?', 'mcq', '["Découpées en paquets qui empruntent des chemins différents","En un seul bloc continu","Toujours par le même câble","Sans être découpées"]'::jsonb, 0, 'Elles sont réassemblées à l’arrivée.', 4),
    ('eb578af9-188c-55b9-bb87-ef4f6c5ef6a8'::uuid, '3e987436-78a6-55af-9a2a-24a89581ed30'::uuid, 'Qu’est-ce qu’une adresse IP ?', 'mcq', '["L’adresse d’une machine sur un réseau","Un mot de passe","Un type de câble","Une unité de mesure"]'::jsonb, 0, 'Chaque machine connectée en possède une.', 5),
    ('8bc465b6-e5c5-5ada-bc8c-8d789d0366e4'::uuid, '3e987436-78a6-55af-9a2a-24a89581ed30'::uuid, 'Qu’est-ce que le « cloud » ?', 'mcq', '["Des serveurs distants dans un centre de données réel","Une mémoire dans les nuages","Un type de câble","Un logiciel"]'::jsonb, 0, 'Un bâtiment climatisé qui consomme de l’électricité.', 6),
    ('46185176-b1c6-559b-84d0-b0eee65f9f0a'::uuid, '3e987436-78a6-55af-9a2a-24a89581ed30'::uuid, 'Que devient une photo avant d’être transmise ?', 'mcq', '["Elle est convertie en une suite de 0 et de 1","Elle est imprimée","Elle est compressée en papier","Rien, elle circule telle quelle"]'::jsonb, 0, 'Puis reconvertie à l’arrivée.', 7),
    ('da2a5bd5-9916-5b4d-88ce-0769bae8ac90'::uuid, '3e987436-78a6-55af-9a2a-24a89581ed30'::uuid, 'Une donnée publiée en ligne reste sous le contrôle de son auteur.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle peut être copiée, conservée et rediffusée à son insu.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('technologie');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('technologie')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 336 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 336 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
