-- =============================================================================
-- 513 — LE CAHIER D'EXERCICES DE 1RE (partie 1)
--
-- FICHIER GÉNÉRÉ par scripts/exercices-sql.ts depuis contenu/exercices/1re/ :
-- ne pas l'éditer à la main, corriger le JSON et régénérer :
--   node node_modules/jiti/lib/jiti-cli.mjs scripts/exercices-sql.ts --num 513 --niveau 1re --fichiers allemand.jumelles-2 --suffixe 1 > supabase/contenu/513_exercices_1re_1.sql
--
-- 21 exercices écrits et relus : pour chaque chapitre, trois exercices faits
-- comme une page de manuel (★ facile, ★★ moyen, ★★★ plus corsé), avec leurs
-- documents (cartes, graphiques, textes, schémas…) et leurs questions. Le
-- contenu public va dans `exercices`, les réponses et explications dans
-- `exercices_cles` (qu'aucun élève ne lit). Gemmes et XP selon les étoiles
-- (5/10/15 gemmes, 20/35/50 XP), réglables ensuite en base.
--
--   allemand.jumelles-2     21 exercices · 7 chapitres
--
-- L'identifiant d'un exercice est dérivé de (chapitre, position) : rejouer ce
-- fichier met les exercices à jour sans doublon, et garde les résultats des
-- élèves. Un exercice dont le chapitre n'existe pas en base est sauté.
--
-- PRÉREQUIS : 372 (le cahier). Idempotent. À exécuter à la main dans :
-- Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

DROP TABLE IF EXISTS pg_temp.exercices_seed;
CREATE TEMP TABLE exercices_seed AS
SELECT md5('exercice:' || v.chapter_id::text || ':' || v.position::text)::uuid AS id, v.*
FROM (VALUES
  ('e9d46a34-f937-5cdd-b468-66f1b302908f'::uuid, 1, 1, 5, 20, 3,
   $ex${"titre":"Qui est le plus grand ?","competence":"lire-tableau","situation":"Trois élèves de l’équipe de volley ont été mesurés par le professeur de sport. Il note leur âge et leur taille.","documents":[{"id":"equipe","type":"tableau","titre":"L’équipe de volley","colonnes":["Name","Alter","Größe (cm)"],"lignes":[["Lena",13,158],["Tim",15,172],["Mia",15,165]],"enteteLignes":true,"source":"Données inventées pour l’exercice"}],"questions":[{"enonce":"D’après le tableau, quelle phrase est juste ?","aide":"Compare les tailles de Tim et de Lena, et regarde le mot qui suit *größer*.","type":"choix","options":[{"id":"a","texte":"Tim ist größer als Lena"},{"id":"b","texte":"Mia ist so groß wie Tim"},{"id":"c","texte":"Tim ist größer wie Lena"},{"id":"d","texte":"Lena ist größer als Tim"}],"multiple":false},{"enonce":"Complète : « Lena est plus jeune que Tim. »","aide":"Une inégalité s’exprime avec comparatif + ...","type":"trous","segments":["Lena ist jünger ",0," Tim."],"banque":["so","mehr","als","wie"]},{"enonce":"Complète d’après les âges : « Mia est plus âgée que Lena. »","aide":"*alt* prend un Umlaut au comparatif.","type":"trous","segments":["Mia ist ",0," als Lena."],"banque":["alter","mehr alt","älteres","älter"]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"choix","ids":["a"]},"explication":"**Tim ist größer als Lena** : Tim mesure 172 cm, Lena 158 cm. Après un comparatif, on emploie *als*, jamais *wie*."},{"cle":{"type":"trous","trous":[["als"]]},"affichage":"als","explication":"**Lena ist jünger als Tim.** Supériorité ou infériorité : comparatif + **als**."},{"cle":{"type":"trous","trous":[["alter"]]},"affichage":"älter","explication":"**Mia ist älter als Lena** : Mia a 15 ans, Lena 13 ; *alt → älter*, avec Umlaut."}]$ex$::jsonb),
  ('e9d46a34-f937-5cdd-b468-66f1b302908f'::uuid, 2, 2, 10, 35, 4,
   $ex${"titre":"Deux smartphones à comparer","competence":"lire-tableau","situation":"Yasmin hésite entre deux smartphones. Elle compare leur prix, leur poids et la durée de leur batterie.","documents":[{"id":"phones","type":"tableau","titre":"Zwei Smartphones","colonnes":["","Modell A","Modell B"],"lignes":[["Preis (€)",300,450],["Gewicht (g)",160,140],["Akku (h)",20,30]],"enteteLignes":true,"source":"Données inventées pour l’exercice"}],"questions":[{"enonce":"De combien d’euros le modèle B est-il plus cher que le modèle A ?","aide":"Soustrais les deux prix.","type":"nombre","unite":"€"},{"enonce":"Complète : « Le modèle A est moins cher que le modèle B. »","aide":"Adjectif + -er, sans mot supplémentaire.","type":"trous","segments":["Modell A ist ",0," als Modell B."],"banque":["billiger","billigere","mehr billig","billig"]},{"enonce":"Quelle phrase est FAUSSE d’après le tableau ?","aide":"Cherche la phrase qui contredit un prix, un poids ou une durée du tableau.","type":"choix","options":[{"id":"a","texte":"Modell B ist so teuer wie Modell A"},{"id":"b","texte":"Modell A ist billiger als Modell B"},{"id":"c","texte":"Modell A ist nicht so leicht wie Modell B"},{"id":"d","texte":"Modell B ist leichter als Modell A"}],"multiple":false},{"enonce":"Remets en ordre : « Le modèle B est plus cher que le modèle A. » La phrase commence par Modell B.","aide":"Comparatif, puis *als* et le second terme.","type":"ordre","items":[{"id":"a","texte":"Modell A"},{"id":"b","texte":"ist"},{"id":"c","texte":"als"},{"id":"d","texte":"Modell B"},{"id":"e","texte":"teurer"}]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"nombre","valeur":150,"tolerance":0},"affichage":"150 €","explication":"**150 €** : 450 − 300 = 150. On écrit *Modell B ist teurer als Modell A*."},{"cle":{"type":"trous","trous":[["billiger"]]},"affichage":"billiger","explication":"**Modell A ist billiger als Modell B.** Le comparatif se forme avec **-er** : on n’emploie jamais *mehr* devant un adjectif."},{"cle":{"type":"choix","ids":["a"]},"explication":"**Modell B ist so teuer wie Modell A** est fausse : B coûte 450 €, A 300 €. Les trois autres correspondent au tableau."},{"cle":{"type":"ordre","ids":["d","b","e","c","a"]},"explication":"**Modell B ist teurer als Modell A.** Structure : sujet + *ist* + comparatif + **als** + second terme."}]$ex$::jsonb),
  ('e9d46a34-f937-5cdd-b468-66f1b302908f'::uuid, 3, 3, 15, 50, 5,
   $ex${"titre":"Mon allemand s’améliore","competence":"argumenter","situation":"Clara tient un petit carnet de ses révisions d’allemand. Elle a tracé son temps de travail par semaine et raconte ses progrès dans une lettre.","documents":[{"id":"lernzeit","type":"graphique","forme":"barres","titre":"Meine Lernzeit pro Tag","categories":["Woche 1","Woche 2","Woche 3","Woche 4"],"series":[{"nom":"Minuten","valeurs":[15,25,40,55],"teinte":"turquoise"}],"axeY":{"titre":"Lernzeit","unite":"Minuten","min":0,"max":60,"pas":10},"axeX":{"titre":"Woche"},"valeurs":false,"source":"Données inventées pour l’exercice"},{"id":"brief","type":"texte","genre":"lettre","titre":"Hallo Lena","blocs":["Ich lerne jede Woche länger Deutsch. Mein älterer Bruder Paul lernt mehr als ich, aber ich verstehe schon viel."],"source":"Lettre écrite pour l’exercice"}],"questions":[{"enonce":"Touche la semaine pendant laquelle Clara a travaillé le plus longtemps.","aide":"Cherche la barre la plus haute.","type":"zone","document":"lernzeit","multiple":false},{"enonce":"Combien de minutes de plus par jour Clara travaille-t-elle en semaine 4 qu’en semaine 1 ?","aide":"Lis les deux barres, puis soustrais.","type":"nombre","unite":"minutes"},{"enonce":"Touche le comparatif qui porte, en plus, une terminaison de déclinaison.","aide":"Il est devant un nom et se termine par -er.","type":"zone","document":"brief","multiple":false},{"enonce":"Quelle phrase compare correctement les semaines 4 et 2 ?","aide":"Après un comparatif, on emploie *als*, et *mehr* ne se place jamais devant un adjectif.","type":"choix","options":[{"id":"a","texte":"In Woche 4 lerne ich so länger als in Woche 2"},{"id":"b","texte":"In Woche 4 lerne ich mehr lang als in Woche 2"},{"id":"c","texte":"In Woche 4 lerne ich länger als in Woche 2"},{"id":"d","texte":"In Woche 4 lerne ich länger wie in Woche 2"}],"multiple":false},{"enonce":"Remets en ordre : « Plus Paul s’exerce en allemand, mieux il parle. » La phrase commence par Je mehr Deutsch.","aide":"Après *je…*, le verbe est à la fin de la proposition ; après *desto…*, le verbe est en deuxième position.","type":"ordre","items":[{"id":"a","texte":"desto besser"},{"id":"b","texte":"spricht er"},{"id":"c","texte":"Paul"},{"id":"d","texte":"übt,"},{"id":"e","texte":"Je mehr Deutsch"}]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["k3"]},"explication":"**Woche 4** : environ 55 minutes par jour, c’est la barre la plus haute."},{"cle":{"type":"nombre","valeur":40,"tolerance":0},"affichage":"40 minutes","explication":"**40 minutes** : 55 − 15 = 40. *In Woche 4 lerne ich länger als in Woche 1.*"},{"cle":{"type":"zone","ids":["m7"]},"explication":"**älterer** : *alt → älter* (comparatif), puis *-er* (terminaison du masculin nominatif après *mein*) : *mein älterer Bruder*."},{"cle":{"type":"choix","ids":["c"]},"explication":"**länger als** : adjectif + **-er**, puis *als*. *wie* sert à l’égalité (*so lang wie*), et *mehr* ne traduit pas « plus » devant un adjectif."},{"cle":{"type":"ordre","ids":["e","c","d","a","b"]},"explication":"**Je mehr Deutsch Paul übt, desto besser spricht er.** Dans la première partie le verbe est rejeté en fin de proposition ; après *desto + comparatif*, il vient aussitôt, devant le sujet."}]$ex$::jsonb),
  ('8479055b-1fb7-55b1-a35f-5009eb9f76bd'::uuid, 1, 1, 5, 20, 3,
   $ex${"titre":"Le désordre de Lena","competence":"comprendre-langue","situation":"Lena range sa chambre avant de partir. Un court texte raconte où se trouvent ses affaires et où elle les met.","documents":[{"id":"zimmer","type":"texte","genre":"recit","titre":"Lenas Zimmer","blocs":["Das Buch liegt auf dem Tisch. Eine Katze sitzt unter dem Stuhl. Lena legt ein Heft auf den Tisch. Dann geht sie in die Küche."],"source":"Texte écrit pour l’exercice"}],"questions":[{"enonce":"Touche les deux articles au datif : ils répondent à la question « wo ? ».","aide":"Le livre et la chatte ne bougent pas.","type":"zone","document":"zimmer","multiple":true},{"enonce":"Touche les deux articles à l’accusatif : ils répondent à la question « wohin ? ».","aide":"Lena met le cahier quelque part et se déplace.","type":"zone","document":"zimmer","multiple":true},{"enonce":"Complète : « Le téléphone est sur le lit. »","aide":"*liegt* indique un lieu, pas un déplacement.","type":"trous","segments":["Das Handy liegt auf ",0," Bett."],"banque":["dem","das","den","die"]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m4","m10"]},"explication":"**dem** (deux fois) : *auf dem Tisch*, *unter dem Stuhl* décrivent un lieu où l’on est : datif."},{"cle":{"type":"zone","ids":["m17","m23"]},"explication":"**den** et **die** : *auf den Tisch*, *in die Küche* disent où l’on va ou où l’on pose quelque chose : accusatif."},{"cle":{"type":"trous","trous":[["dem"]]},"affichage":"dem","explication":"**auf dem Bett** : *wo ?* donne le datif ; *Bett* est neutre, donc *dem*."}]$ex$::jsonb),
  ('8479055b-1fb7-55b1-a35f-5009eb9f76bd'::uuid, 2, 2, 10, 35, 5,
   $ex${"titre":"Le déménagement","competence":"manier-langue","situation":"Eva et Max emménagent dans un nouvel appartement. Chaque objet doit être posé au bon endroit : ils parlent tantôt d’un mouvement, tantôt d’un lieu.","documents":[{"id":"umzug","type":"dialogue","modele":"sms","titre":"Umzug","participants":[{"nom":"Eva","emoji":"👧","cote":"gauche"},{"nom":"Max","emoji":"👦","cote":"droite"}],"repliques":[{"qui":"Eva","texte":"Wohin stelle ich die Lampe?"},{"qui":"Max","texte":"Stell sie bitte auf den Schreibtisch. Die Pflanze steht schon neben dem Fenster."},{"qui":"Eva","texte":"Und der Teppich? Ich lege ihn vor das Sofa."},{"qui":"Max","texte":"Gut. Dann sitzt die Katze bald auf dem Teppich."}],"source":"Messages écrits pour l’exercice"}],"questions":[{"enonce":"Touche les deux articles au datif : ils répondent à « wo ? ».","aide":"Ils décrivent un état, pas un mouvement.","type":"zone","document":"umzug","multiple":true},{"enonce":"Range chaque verbe : action (accusatif) ou état (datif) ?","aide":"Les verbes en *-en* qui commencent par *st-*, *l-*, *s-* vont par paires : un pour l’action, un pour l’état.","type":"categories","categories":[{"id":"c0","texte":"Action → accusatif (wohin ?)"},{"id":"c1","texte":"État → datif (wo ?)"}],"items":[{"id":"i0","texte":"stehen"},{"id":"i1","texte":"legen"},{"id":"i2","texte":"stellen"},{"id":"i3","texte":"sitzen"},{"id":"i4","texte":"setzen"},{"id":"i5","texte":"liegen"}]},{"enonce":"Complète : « Je pose le livre sur la table. Le livre est sur la table. »","aide":"Premier trou : action (*legen*) ; deuxième trou : état (*liegen*).","type":"trous","segments":["Ich ",0," das Buch auf den Tisch. Das Buch ",1," auf dem Tisch."],"banque":["legt","lege","liege","liegt"]},{"enonce":"Associe chaque forme pleine à sa contraction.","aide":"*das* devient *-s*, *dem* devient *-m*.","type":"association","gauche":[{"id":"g0","texte":"in das"},{"id":"g1","texte":"in dem"},{"id":"g2","texte":"an dem"},{"id":"g3","texte":"auf das"}],"droite":[{"id":"d0","texte":"am"},{"id":"d1","texte":"im"},{"id":"d2","texte":"aufs"},{"id":"d3","texte":"ins"}]},{"enonce":"Remets en ordre : « J’assieds l’enfant sur la chaise. » La phrase commence par Ich.","aide":"*setzen* indique un mouvement : accusatif.","type":"ordre","items":[{"id":"a","texte":"das Kind"},{"id":"b","texte":"auf den Stuhl"},{"id":"c","texte":"Ich"},{"id":"d","texte":"setze"}]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m16","m34"]},"explication":"**dem** (deux fois) : *neben dem Fenster* (où la plante se trouve) et *auf dem Teppich* (où la chatte sera) sont des lieux : datif."},{"cle":{"type":"categories","items":{"i0":"c1","i1":"c0","i2":"c0","i3":"c1","i4":"c0","i5":"c1"}},"explication":"*stellen / legen / setzen* décrivent une **action** (on déplace quelque chose : accusatif) ; *stehen / liegen / sitzen* décrivent un **état** (datif)."},{"cle":{"type":"trous","trous":[["lege"],["liegt"]]},"affichage":"lege · liegt","explication":"**Ich lege** (action, accusatif : *auf den Tisch*) puis **liegt** (état, datif : *auf dem Tisch*)."},{"cle":{"type":"association","paires":{"g2":"d0","g1":"d1","g3":"d2","g0":"d3"}},"explication":"*in das → ins*, *in dem → im*, *an dem → am*, *auf das → aufs*."},{"cle":{"type":"ordre","ids":["c","d","a","b"]},"explication":"**Ich setze das Kind auf den Stuhl.** *setzen* (action) appelle *auf* + accusatif."}]$ex$::jsonb),
  ('8479055b-1fb7-55b1-a35f-5009eb9f76bd'::uuid, 3, 3, 15, 50, 5,
   $ex${"titre":"Emménager, étape par étape","competence":"raisonner","situation":"Anna décrit sa nouvelle chambre dans une lettre ; elle échange aussi des messages avec son père, qui déplace les meubles. Il faut dire à chaque fois s’il y a mouvement ou non.","documents":[{"id":"brief","type":"texte","genre":"lettre","titre":"Hallo Mia","blocs":["Heute ziehe ich um! Das Sofa steht jetzt im Wohnzimmer. Den Tisch stelle ich vor das Fenster. Neben dem Sofa liegt der Teppich. Über dem Tisch hängt die Lampe. Morgen hänge ich ein Bild an die Wand."],"source":"Lettre écrite pour l’exercice"},{"id":"papa","type":"dialogue","modele":"sms","titre":"Mit Papa","participants":[{"nom":"Papa","emoji":"👧","cote":"gauche"},{"nom":"Anna","emoji":"👦","cote":"droite"}],"repliques":[{"qui":"Papa","texte":"Wo soll ich den Schrank hinstellen?"},{"qui":"Anna","texte":"Stell ihn neben die Tür."},{"qui":"Papa","texte":"Er steht jetzt neben der Tür. Und die Kisten?"},{"qui":"Anna","texte":"Leg sie unter das Bett. Dann liegen sie sicher unter dem Bett."}],"source":"Messages écrits pour l’exercice"}],"questions":[{"enonce":"Touche les deux prépositions qui expriment un déplacement : elles sont suivies de l’accusatif.","aide":"Anna pose ou accroche quelque chose quelque part.","type":"zone","document":"brief","multiple":true},{"enonce":"Touche les trois prépositions qui expriment un lieu : elles sont suivies du datif.","aide":"Le sofa, le tapis et la lampe sont déjà en place.","type":"zone","document":"brief","multiple":true},{"enonce":"Range chaque phrase du dialogue : mouvement (wohin ?) ou lieu (wo ?).","aide":"Repère le verbe : *stellen* et *legen* disent un geste, *stehen* et *liegen* un état.","type":"categories","categories":[{"id":"c0","texte":"Mouvement → accusatif (wohin ?)"},{"id":"c1","texte":"Lieu → datif (wo ?)"}],"items":[{"id":"i0","texte":"Er steht jetzt neben der Tür."},{"id":"i1","texte":"Sie liegen unter dem Bett."},{"id":"i2","texte":"Leg sie unter das Bett."},{"id":"i3","texte":"Stell ihn neben die Tür."}]},{"enonce":"Complète : « Papa pose l’armoire à côté de la porte. Maintenant elle est à côté de la porte. »","aide":"Premier trou : action ; deuxième trou : état.","type":"trous","segments":["Papa ",0," den Schrank neben die Tür. Jetzt ",1," er neben der Tür."],"banque":["stehen","steht","stellt","stelle"]},{"enonce":"Remets en ordre : « Je mets les caisses sous le lit. » La phrase commence par Ich.","aide":"Il y a un mouvement : accusatif.","type":"ordre","items":[{"id":"a","texte":"Ich"},{"id":"b","texte":"die Kisten"},{"id":"c","texte":"lege"},{"id":"d","texte":"unter das Bett"}]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m14","m34"]},"explication":"**vor** (*stelle ich vor das Fenster*) et **an** (*hänge ich an die Wand*) expriment un mouvement : accusatif."},{"cle":{"type":"zone","ids":["m8","m17","m23"]},"explication":"**im** (= *in dem*), **Neben** et **Über** décrivent où sont les objets : datif."},{"cle":{"type":"categories","items":{"i0":"c1","i1":"c1","i2":"c0","i3":"c0"}},"explication":"*Stell ihn neben die Tür* et *Leg sie unter das Bett* : mouvement, accusatif (*die*, *das*). *steht neben der Tür* et *liegen unter dem Bett* : lieu, datif (*der*, *dem*)."},{"cle":{"type":"trous","trous":[["stellt"],["steht"]]},"affichage":"stellt · steht","explication":"**stellt** (action, avec accusatif : *neben die Tür*) puis **steht** (état, avec datif : *neben der Tür*)."},{"cle":{"type":"ordre","ids":["a","c","b","d"]},"explication":"**Ich lege die Kisten unter das Bett.** *legen* + *unter* + accusatif."}]$ex$::jsonb),
  ('8c3bf0b0-bf2d-5cbb-ac85-dd6466cb04f1'::uuid, 1, 1, 5, 20, 3,
   $ex${"titre":"Sur le parking de l’école","competence":"comprendre-langue","situation":"Le journal de l’école décrit les véhicules garés devant le lycée. Les propriétaires sont indiqués de deux manières différentes.","documents":[{"id":"park","type":"texte","genre":"article","titre":"Auf dem Parkplatz","blocs":["Auf dem Parkplatz stehen drei Fahrzeuge. Peters Auto ist blau, Annas Roller ist rot. Das Auto des Lehrers ist schwarz."],"source":"Article écrit pour l’exercice"}],"questions":[{"enonce":"Touche les deux génitifs saxons : le nom du possesseur est devant, avec un -s.","aide":"Ce sont des prénoms, sans article.","type":"zone","document":"park","multiple":true},{"enonce":"Touche l’article qui introduit un génitif ordinaire, placé derrière le nom.","aide":"Cet article est suivi d’un nom masculin avec -s.","type":"zone","document":"park","multiple":false},{"enonce":"Complète : « la maison du père et la chambre de la mère ».","aide":"Masculin et neutre : *des* ; féminin et pluriel : *der*.","type":"trous","segments":["Das Haus ",0," Vaters und das Zimmer ",1," Mutter."],"banque":["der","den","des","dem"]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m6","m10"]},"explication":"**Peters** et **Annas** : le génitif saxon se place devant le nom, avec **-s** et sans apostrophe ni article."},{"cle":{"type":"zone","ids":["m16"]},"explication":"**des** : *das Auto des Lehrers*. Le possesseur est derrière, avec l’article au génitif (*des*) et un **-s** au nom."},{"cle":{"type":"trous","trous":[["des"],["der"]]},"affichage":"des · der","explication":"**des Vaters** (masculin : *des* + nom en -s) et **der Mutter** (féminin : *der*, le nom ne change pas)."}]$ex$::jsonb),
  ('8c3bf0b0-bf2d-5cbb-ac85-dd6466cb04f1'::uuid, 2, 2, 10, 35, 5,
   $ex${"titre":"À qui est ce vélo ?","competence":"manier-langue","situation":"Lena veut savoir à qui appartiennent un téléphone et un vélo. Tom répond de trois manières différentes.","documents":[{"id":"wem","type":"dialogue","modele":"sms","titre":"Wessen Handy?","participants":[{"nom":"Lena","emoji":"👧","cote":"gauche"},{"nom":"Tom","emoji":"👦","cote":"droite"}],"repliques":[{"qui":"Lena","texte":"Wessen Handy liegt da?"},{"qui":"Tom","texte":"Das ist das Handy von meinem Bruder."},{"qui":"Lena","texte":"Und das Fahrrad vor der Tür?"},{"qui":"Tom","texte":"Das ist Annas Fahrrad. Es bleibt wegen des Regens hier."}],"source":"Messages écrits pour l’exercice"}],"questions":[{"enonce":"Touche la préposition de la tournure orale « de + datif » : le possesseur est derrière.","aide":"Elle introduit « mon frère ».","type":"zone","document":"wem","multiple":false},{"enonce":"Touche le génitif saxon : le possesseur est devant le nom, sans article.","aide":"C’est un prénom terminé par -s.","type":"zone","document":"wem","multiple":false},{"enonce":"Touche la préposition qui régit le génitif et veut dire « à cause de ».","aide":"Elle est suivie de *des Regens*.","type":"zone","document":"wem","multiple":false},{"enonce":"Range chaque tournure selon sa construction.","aide":"Regarde où se trouve le possesseur et s’il y a un *von*.","type":"categories","categories":[{"id":"c0","texte":"Génitif saxon"},{"id":"c1","texte":"Génitif ordinaire"},{"id":"c2","texte":"von + datif"}],"items":[{"id":"i0","texte":"Lenas Tasche"},{"id":"i1","texte":"das Auto von meinem Vater"},{"id":"i2","texte":"das Auto des Vaters"},{"id":"i3","texte":"die Tasche der Frau"},{"id":"i4","texte":"Peters Auto"},{"id":"i5","texte":"die Tasche von meiner Mutter"}]},{"enonce":"Complète : « Pendant l’été, nous allons à la mer. »","aide":"Le sens est « pendant » : une durée.","type":"trous","segments":[0," des Sommers fahren wir ans Meer."],"banque":["Wegen","Während","Statt","Trotz"]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m8"]},"explication":"**von** : *das Handy von meinem Bruder* est la tournure orale, avec un datif."},{"cle":{"type":"zone","ids":["m19"]},"explication":"**Annas** : *Annas Fahrrad*, sans article et sans apostrophe."},{"cle":{"type":"zone","ids":["m23"]},"explication":"**wegen** : *wegen des Regens*. Les prépositions *wegen*, *trotz*, *während*, *statt* régissent le génitif."},{"cle":{"type":"categories","items":{"i0":"c0","i1":"c2","i2":"c1","i3":"c1","i4":"c0","i5":"c2"}},"explication":"Le **génitif saxon** met le possesseur devant (*Lenas Tasche*), le **génitif ordinaire** derrière avec *des* ou *der*, et *von* + datif est la forme orale."},{"cle":{"type":"trous","trous":[["wahrend"]]},"affichage":"Während","explication":"**Während des Sommers** : *während* + génitif veut dire « pendant »."}]$ex$::jsonb),
  ('8c3bf0b0-bf2d-5cbb-ac85-dd6466cb04f1'::uuid, 3, 3, 15, 50, 5,
   $ex${"titre":"Le journal du quartier","competence":"analyser-texte","situation":"Le journal du quartier raconte les travaux de l’été. Son vocabulaire est celui de l’écrit soigné : il utilise des prépositions suivies du génitif.","documents":[{"id":"viertel","type":"texte","genre":"article","titre":"Bei uns im Viertel","blocs":["Während des Sommers war die Straße gesperrt. Trotz der Hitze arbeiteten die Männer jeden Tag. Statt des alten Marktes gibt es jetzt einen Parkplatz.","Der Bürgermeister war nicht da, wegen seiner Krankheit."],"source":"Article écrit pour l’exercice"},{"id":"tabgen","type":"tableau","titre":"L’article et le nom au génitif","colonnes":["Genre","Article","Le nom"],"lignes":[["Masculin","des","prend -(e)s"],["Neutre","des","?"],["Féminin","der","?"],["Pluriel","der","?"]],"source":"Tableau écrit pour l’exercice"}],"questions":[{"enonce":"Touche les quatre prépositions qui régissent le génitif.","aide":"Le sens est : pendant, malgré, au lieu de, à cause de.","type":"zone","document":"viertel","multiple":true},{"enonce":"Touche les deux noms féminins au génitif.","aide":"Leur article est *der*, ou le possessif *seiner*.","type":"zone","document":"viertel","multiple":true},{"enonce":"Complète d’après le tableau : « pendant l’année » (*das Jahr*).","aide":"Le nom neutre prend -(e)s au génitif, comme le masculin.","type":"trous","segments":["während des ",0],"banque":["Jahres","Jahre","Jahr","Jahren"]},{"enonce":"Associe chaque préposition à son sens.","aide":"Cherche la phrase du journal où chaque mot est utilisé.","type":"association","gauche":[{"id":"g0","texte":"wegen"},{"id":"g1","texte":"trotz"},{"id":"g2","texte":"während"},{"id":"g3","texte":"statt"}],"droite":[{"id":"d0","texte":"au lieu de"},{"id":"d1","texte":"à cause de"},{"id":"d2","texte":"malgré"},{"id":"d3","texte":"pendant"}]},{"enonce":"Remets en ordre : « À cause de la pluie, je reste à la maison. » La phrase commence par Wegen des Regens.","aide":"Le groupe prépositionnel est en première position : le verbe passe devant le sujet.","type":"ordre","items":[{"id":"a","texte":"Wegen des Regens"},{"id":"b","texte":"ich"},{"id":"c","texte":"bleibe"},{"id":"d","texte":"zu Hause"}]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m0","m7","m15","m29"]},"explication":"**Während**, **Trotz**, **Statt** et **wegen** régissent le génitif."},{"cle":{"type":"zone","ids":["m9","m31"]},"explication":"**Hitze** et **Krankheit** sont féminins : au génitif, le nom ne prend aucune marque (*der Hitze*, *seiner Krankheit*)."},{"cle":{"type":"trous","trous":[["jahres"]]},"affichage":"Jahres","explication":"**während des Jahres** : au génitif, le nom masculin ou neutre prend **-(e)s** ; le féminin et le pluriel ne changent pas."},{"cle":{"type":"association","paires":{"g3":"d0","g0":"d1","g1":"d2","g2":"d3"}},"explication":"*wegen* = à cause de, *trotz* = malgré, *während* = pendant, *statt* = au lieu de."},{"cle":{"type":"ordre","ids":["a","c","b","d"]},"explication":"**Wegen des Regens bleibe ich zu Hause.** Le groupe en tête occupe la première place ; le verbe reste en deuxième, avant *ich*."}]$ex$::jsonb),
  ('94371d4d-0c80-5235-a5b4-d9764ea8a9c0'::uuid, 1, 1, 5, 20, 3,
   $ex${"titre":"Le menu du Café zur Sonne","competence":"comprendre-langue","situation":"Jan lit l’ardoise du café en bas de chez lui. Chaque ligne a un adjectif devant un nom, avec ou sans déterminant.","documents":[{"id":"menu","type":"fiche","modele":"menu","entete":"Café zur Sonne","sousTitre":"Heute im Angebot","emoji":"☕","lignes":[{"texte":"Kalte Milch","valeur":"1,20 €","id":"z1"},{"texte":"Frisches Brot","valeur":"2,00 €","id":"z2"},{"texte":"Die heiße Suppe","valeur":"3,50 €","id":"z3"},{"texte":"Ein warmer Apfelkuchen","valeur":"2,80 €","id":"z4"}],"pied":"Menu écrit pour l’exercice","teinte":"ambre"}],"questions":[{"enonce":"Touche les deux lignes où l’adjectif est employé sans déterminant (déclinaison forte).","aide":"Cherche les lignes qui commencent directement par l’adjectif.","type":"zone","document":"menu","multiple":true},{"enonce":"Pourquoi « Die heiße Suppe » se termine-t-il en -e ?","aide":"Quel mot précède l’adjectif ?","type":"choix","options":[{"id":"a","texte":"Parce qu’il n’y a aucun déterminant"},{"id":"b","texte":"Parce que « die » porte déjà la marque du cas"},{"id":"c","texte":"Parce que heiß est un adjectif invariable"},{"id":"d","texte":"Parce que Suppe est un nom masculin"}],"multiple":false},{"enonce":"Complète : « Au petit-déjeuner, je mange du bon pain. »","aide":"Il n’y a pas de déterminant, et *Brot* est neutre.","type":"trous","segments":["Zum Frühstück esse ich ",0," Brot."],"banque":["gutes","guter","gute","guten"]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["z1","z2"]},"explication":"**Kalte Milch** et **Frisches Brot** : sans article, l’adjectif porte lui-même la marque du cas (*-e* pour le féminin, *-es* pour le neutre)."},{"cle":{"type":"choix","ids":["b"]},"explication":"Quand le déterminant (*die*) porte déjà la marque du cas, l’adjectif prend une terminaison faible : **-e** ici."},{"cle":{"type":"trous","trous":[["gutes"]]},"affichage":"gutes","explication":"**gutes** : sans déterminant, l’adjectif reprend la terminaison de l’article défini ; pour un neutre à l’accusatif, c’est **-es**."}]$ex$::jsonb),
  ('94371d4d-0c80-5235-a5b4-d9764ea8a9c0'::uuid, 2, 2, 10, 35, 4,
   $ex${"titre":"Les petites annonces de Lukas","competence":"manier-langue","situation":"Lukas vide sa chambre et publie une annonce. Il doit choisir la bonne terminaison pour chaque adjectif.","documents":[{"id":"kleinanz","type":"texte","genre":"article","titre":"Zu verkaufen","blocs":["Verkaufe meinen alten Computer, einen schnellen Drucker und gute Bücher. Dazu gibt es frische Eier vom Bauernhof."],"source":"Annonce écrite pour l’exercice"}],"questions":[{"enonce":"Touche les deux adjectifs employés sans déterminant (déclinaison forte).","aide":"Cherche les adjectifs qui précèdent directement un nom au pluriel.","type":"zone","document":"kleinanz","multiple":true},{"enonce":"Touche l’adjectif qui suit un possessif (« meinen »).","aide":"C’est un masculin à l’accusatif.","type":"zone","document":"kleinanz","multiple":false},{"enonce":"Range chaque groupe nominal selon sa déclinaison.","aide":"Regarde ce qui précède l’adjectif : article défini, article indéfini ou rien.","type":"categories","categories":[{"id":"c0","texte":"Faible (après der, die, das)"},{"id":"c1","texte":"Mixte (après ein, mein)"},{"id":"c2","texte":"Forte (sans déterminant)"}],"items":[{"id":"i0","texte":"alter Wein"},{"id":"i1","texte":"gute Freunde"},{"id":"i2","texte":"ein alter Mann"},{"id":"i3","texte":"mein neues Auto"},{"id":"i4","texte":"der alte Mann"},{"id":"i5","texte":"die neue Schule"}]},{"enonce":"Complète avec la bonne forme : « C’est une haute montagne et une voiture chère. »","aide":"*hoch* perd son c ; *teuer* perd son e devant une terminaison.","type":"trous","segments":["Das ist ein ",0," Berg und ein ",1," Auto."],"banque":["teures","hoher","hohes","teueres","hocher"]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m8","m13"]},"explication":"**gute** (*gute Bücher*) et **frische** (*frische Eier*) : pas de déterminant, donc l’adjectif porte la marque du cas (*-e* au pluriel)."},{"cle":{"type":"zone","ids":["m2"]},"explication":"**alten** : après le possessif *meinen*, qui marque déjà le cas, l’adjectif prend **-en**."},{"cle":{"type":"categories","items":{"i0":"c2","i1":"c2","i2":"c1","i3":"c1","i4":"c0","i5":"c0"}},"explication":"Après *der/die/das* : faible. Après *ein/mein* : mixte. Sans déterminant : forte (*alter Wein*, *gute Freunde*)."},{"cle":{"type":"trous","trous":[["hoher"],["teures"]]},"affichage":"hoher · teures","explication":"**ein hoher Berg** (*hoch* → *hoh-*, + *-er*) et **ein teures Auto** (*teuer* → *teur-*, + *-es*) : *ein* ne marque ni le masculin ni le neutre, l’adjectif le fait."}]$ex$::jsonb),
  ('94371d4d-0c80-5235-a5b4-d9764ea8a9c0'::uuid, 3, 3, 15, 50, 5,
   $ex${"titre":"Ma nouvelle chambre : lettre et grille","competence":"manier-langue","situation":"Mia emménage dans un nouveau logement. Elle décrit sa chambre à une amie, puis révise la déclinaison faible avec un tableau.","documents":[{"id":"zimmer","type":"texte","genre":"lettre","titre":"Hallo Mia","blocs":["Mein neues Zimmer ist toll! Ein großes Bett steht am Fenster. Neben dem alten Schrank hängt ein rosa Poster. Auf dem Tisch liegt ein dunkles Heft."],"source":"Lettre écrite pour l’exercice"},{"id":"tabdekl","type":"tableau","titre":"La déclinaison faible","colonnes":["Cas","Masculin","Féminin","Neutre","Pluriel"],"lignes":[["Nominatif","der alte Mann","die alte Frau","das alte Haus","die alten Kinder"],["Accusatif","den alten Mann","?","?","die alten Kinder"],["Datif","dem alten Mann","der alten Frau","?","?"]],"enteteLignes":true,"source":"Tableau écrit pour l’exercice"}],"questions":[{"enonce":"Touche l’adjectif qui ne prend jamais de terminaison.","aide":"C’est une couleur empruntée.","type":"zone","document":"zimmer","multiple":false},{"enonce":"Touche l’adjectif qui a perdu un e pour recevoir sa terminaison.","aide":"Compare avec *dunkel*.","type":"zone","document":"zimmer","multiple":false},{"enonce":"Pourquoi « ein großes Bett », mais « eine große Lampe » ?","aide":"Compare la terminaison de *ein* et celle de *eine*.","type":"choix","options":[{"id":"a","texte":"Après ein, l’adjectif prend toujours la forme -en"},{"id":"b","texte":"Bett est féminin, l’adjectif prend donc un -e"},{"id":"c","texte":"Ein ne marque pas le neutre, l’adjectif le fait"},{"id":"d","texte":"Groß est un attribut, donc il se décline ici"}],"multiple":false},{"enonce":"Complète les cases du tableau : accusatif féminin et accusatif neutre.","aide":"À l’accusatif, féminin et neutre ressemblent au nominatif.","type":"trous","segments":["die ",0," Frau · das ",1," Haus"],"banque":["altes","alter","alte","alten"]},{"enonce":"Complète les cases du datif : le neutre, puis le pluriel.","aide":"Au datif, l’adjectif faible prend la même terminaison partout.","type":"trous","segments":["dem ",0," Haus · den ",1," Kindern"],"banque":["alten","alter","altes","alte"]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m17"]},"explication":"**rosa** est invariable, comme *lila* : *ein rosa Poster*."},{"cle":{"type":"zone","ids":["m24"]},"explication":"**dunkles** : *dunkel* perd son *e* devant une terminaison (*ein dunkles Heft*)."},{"cle":{"type":"choix","ids":["c"]},"explication":"*ein* est sans marque au neutre : l’adjectif porte **-es**. *eine* marque déjà le féminin : l’adjectif se contente de **-e**."},{"cle":{"type":"trous","trous":[["alte"],["alte"]]},"affichage":"alte · alte","explication":"**die alte Frau**, **das alte Haus** : à l’accusatif, le féminin et le neutre gardent le **-e** du nominatif."},{"cle":{"type":"trous","trous":[["alten"],["alten"]]},"affichage":"alten · alten","explication":"**dem alten Haus**, **den alten Kindern** : au datif (et au génitif), la terminaison faible est toujours **-en**."}]$ex$::jsonb),
  ('9712f7b8-159d-5a85-b792-992b0ea096f4'::uuid, 1, 1, 5, 20, 3,
   $ex${"titre":"Un samedi chargé pour Lena","competence":"comprendre-langue","situation":"Mia veut voir Lena ce week-end. Lena lui répond par SMS et donne ses horaires : à toi de repérer comment elle dit le temps.","documents":[{"id":"sms","type":"dialogue","modele":"sms","titre":"Samstag","participants":[{"nom":"Mia","emoji":"👧","cote":"gauche"},{"nom":"Lena","emoji":"👦","cote":"droite"}],"repliques":[{"qui":"Mia","texte":"Hast du am Samstag Zeit?"},{"qui":"Lena","texte":"Nur am Nachmittag. Um zehn Uhr habe ich Training."},{"qui":"Mia","texte":"Und im Juli? Fährst du weg?"},{"qui":"Lena","texte":"Ja, im Juli fahre ich zu meiner Oma."}],"source":"Messages écrits pour l’exercice"}],"questions":[{"enonce":"Touche la préposition qui donne l’heure précise du Training.","aide":"C’est le petit mot placé juste devant « zehn Uhr ».","type":"zone","document":"sms","multiple":false},{"enonce":"Range ces compléments de temps selon la préposition qui leur convient.","aide":"Jours et moments de la journée : am. Mois et saisons : im. Heures précises : um.","type":"categories","categories":[{"id":"c0","texte":"am"},{"id":"c1","texte":"im"},{"id":"c2","texte":"um"}],"items":[{"id":"i0","texte":"Januar"},{"id":"i1","texte":"Mitternacht"},{"id":"i2","texte":"acht Uhr"},{"id":"i3","texte":"Sommer"},{"id":"i4","texte":"Montag"},{"id":"i5","texte":"Abend"}]},{"enonce":"Lena propose : « Je suis libre le samedi après-midi. » Complète.","aide":"Samstagnachmittag est un moment précis d’un jour.","type":"trous","segments":["Ich habe ",0," Samstagnachmittag Zeit."],"banque":["im","am","in","um"]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m8"]},"explication":"**um** s’emploie devant une heure précise : *um zehn Uhr*."},{"cle":{"type":"categories","items":{"i0":"c1","i1":"c2","i2":"c2","i3":"c1","i4":"c0","i5":"c0"}},"explication":"**am** : jours et moments de la journée ; **im** : mois et saisons ; **um** : heure précise."},{"cle":{"type":"trous","trous":[["am"]]},"affichage":"am","explication":"**Ich habe am Samstagnachmittag Zeit.** *am* s’emploie pour les jours et les parties de la journée."}]$ex$::jsonb),
  ('9712f7b8-159d-5a85-b792-992b0ea096f4'::uuid, 2, 2, 10, 35, 4,
   $ex${"titre":"Une lettre de Vienne","competence":"analyser-texte","situation":"Jonas passe quelques jours à Vienne et écrit à sa correspondante Paula. Son courrier est plein de repères de temps.","documents":[{"id":"lettre","type":"texte","genre":"lettre","titre":"Liebe Paula","blocs":["Liebe Paula, vor zwei Wochen habe ich meine Reise geplant, und jetzt bin ich in Wien! Ich bleibe von Montag bis Freitag. Morgens gehe ich ins Museum, abends esse ich mit Freunden. In einer Woche bin ich wieder zu Hause. Bis bald! Jonas"],"source":"Courrier écrit pour l’exercice"}],"questions":[{"enonce":"Touche les deux petits mots qui disent « du lundi au vendredi ».","aide":"Cherche une préposition de départ et une préposition d’arrivée autour des jours.","type":"zone","document":"lettre","multiple":true},{"enonce":"Touche les deux adverbes qui disent ce que Jonas fait d’habitude, le matin et le soir.","aide":"Ils se terminent par un -s et décrivent une habitude.","type":"zone","document":"lettre","multiple":true},{"enonce":"Que dit Jonas dans « In einer Woche bin ich wieder zu Hause » ?","aide":"Pense au futur : *in* + datif exprime un moment à venir.","type":"choix","options":[{"id":"a","texte":"Il rentre dans une semaine"},{"id":"b","texte":"Il rentre depuis une semaine"},{"id":"c","texte":"Il est rentré il y a une semaine"},{"id":"d","texte":"Il rentre pour une semaine"}],"multiple":false},{"enonce":"Associe chaque expression de temps à sa traduction.","aide":"Vor = passé, in = futur, seit = depuis, während = pendant.","type":"association","gauche":[{"id":"g0","texte":"vor zwei Wochen"},{"id":"g1","texte":"in zwei Wochen"},{"id":"g2","texte":"seit zwei Wochen"},{"id":"g3","texte":"während der Ferien"}],"droite":[{"id":"d0","texte":"dans deux semaines"},{"id":"d1","texte":"depuis deux semaines"},{"id":"d2","texte":"pendant les vacances"},{"id":"d3","texte":"il y a deux semaines"}]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m18","m20"]},"explication":"**von … bis** se traduit par « de … à » : *von Montag bis Freitag*."},{"cle":{"type":"zone","ids":["m22","m27"]},"explication":"**morgens** et **abends** (avec le -s) disent le matin et le soir « en général »."},{"cle":{"type":"choix","ids":["a"]},"explication":"**in einer Woche** = « dans une semaine » : on compte à partir de maintenant. Pour « il y a », on dirait *vor einer Woche*."},{"cle":{"type":"association","paires":{"g1":"d0","g2":"d1","g3":"d2","g0":"d3"}},"explication":"**vor** + datif : il y a ; **in** + datif : dans ; **seit** + datif : depuis ; **während** + génitif : pendant."}]$ex$::jsonb),
  ('9712f7b8-159d-5a85-b792-992b0ea096f4'::uuid, 3, 3, 15, 50, 6,
   $ex${"titre":"Échange scolaire à Hambourg","competence":"raisonner","situation":"Frau Brandt organise un échange entre Lyon et Hambourg. Elle affiche le programme, et pendant l’arrivée, une élève prévient son correspondant.","documents":[{"id":"affiche","type":"fiche","modele":"affiche","entete":"Schüleraustausch Lyon–Hamburg","sousTitre":"Programm","emoji":"🚆","lignes":[{"texte":"Ankunft","valeur":"am Montag, um 8 Uhr","id":"z1"},{"texte":"Dauer","valeur":"von Montag bis Freitag","id":"z2"},{"texte":"Sport","valeur":"jeden Nachmittag","id":"z3"},{"texte":"Pause","valeur":"während der Mittagszeit","id":"z4"},{"texte":"Abreise","valeur":"am Samstag","id":"z5"}],"pied":"Anmeldung bis morgen!","source":"Affiche écrite pour l’exercice"},{"id":"sms","type":"dialogue","modele":"sms","titre":"Am Bahnhof","participants":[{"nom":"Lisa","emoji":"👧","cote":"gauche"},{"nom":"Max","emoji":"👦","cote":"droite"}],"repliques":[{"qui":"Lisa","texte":"Wo seid ihr? Ich warte seit zehn Minuten am Bahnhof."},{"qui":"Max","texte":"Wir sind in fünf Minuten da."}],"source":"Messages écrits pour l’exercice"}],"questions":[{"enonce":"Touche la ligne dont le complément de temps est à l’accusatif, sans préposition.","aide":"Cherche une expression de temps qui commence par un déterminant et pas par une préposition.","type":"zone","document":"affiche","multiple":false},{"enonce":"Touche la ligne qui contient une préposition suivie du génitif.","aide":"Cette préposition veut dire « pendant ».","type":"zone","document":"affiche","multiple":false},{"enonce":"Frau Brandt écrit : « Lundi à huit heures, nous partons pour Hambourg. » Remets la phrase en ordre.","aide":"La phrase commence par le complément de temps : le verbe vient juste après, puis le sujet.","type":"ordre","items":[{"id":"a","texte":"Am Montag um acht Uhr"},{"id":"b","texte":"wir"},{"id":"c","texte":"nach Hamburg"},{"id":"d","texte":"fahren"}]},{"enonce":"Complète le programme : « L’échange dure du lundi au vendredi. »","aide":"Il faut une préposition de départ et une préposition d’arrivée.","type":"trous","segments":["Der Austausch dauert ",0," Montag ",1," Freitag."],"banque":["bis","von","ab","seit"]},{"enonce":"Touche la préposition qui dit que Lisa attend « depuis » dix minutes.","aide":"Cette préposition est suivie du datif et, en allemand, le verbe reste au présent.","type":"zone","document":"sms","multiple":false},{"enonce":"Que signifie « Wir sind in fünf Minuten da » ?","aide":"Pour parler de l’avenir, l’allemand dit *in* + datif.","type":"choix","options":[{"id":"a","texte":"Nous serons là dans cinq minutes"},{"id":"b","texte":"Nous sommes là depuis cinq minutes"},{"id":"c","texte":"Nous étions là il y a cinq minutes"},{"id":"d","texte":"Nous sommes là pendant cinq minutes"}],"multiple":false}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["z3"]},"explication":"**jeden Nachmittag** est un accusatif sans préposition : une habitude qui se répète."},{"cle":{"type":"zone","ids":["z4"]},"explication":"**während** est suivie du génitif : *während der Mittagszeit*."},{"cle":{"type":"ordre","ids":["a","d","b","c"]},"explication":"**Am Montag um acht Uhr fahren wir nach Hamburg.** Le complément de temps ouvre la phrase : le verbe reste en deuxième position et le sujet passe derrière lui."},{"cle":{"type":"trous","trous":[["von"],["bis"]]},"affichage":"von · bis","explication":"**Der Austausch dauert von Montag bis Freitag.** *von … bis* = « de … à »."},{"cle":{"type":"zone","ids":["m5"]},"explication":"**seit** = depuis ; avec elle, l’allemand garde le présent : *Ich warte seit zehn Minuten*."},{"cle":{"type":"choix","ids":["a"]},"explication":"**in fünf Minuten** = « dans cinq minutes ». Le présent suffit pour l’avenir quand un complément de temps le précise."}]$ex$::jsonb),
  ('8ac8fba3-6ef4-59d4-b1bf-8840c1cacf0c'::uuid, 1, 1, 5, 20, 3,
   $ex${"titre":"Une carte postale de Vienne","competence":"manier-langue","situation":"Mia est en voyage à Vienne et écrit à sa grand-mère. Elle décrit la ville, les gens et le temps.","documents":[{"id":"wien","type":"texte","genre":"lettre","titre":"Liebe Oma","blocs":["Wir sind jetzt in Wien. Die Stadt ist groß und die Leute sind freundlich. Das Wetter bleibt schön. Mein Bruder hat ein neues Fahrrad."],"source":"Carte postale écrite pour l’exercice"}],"questions":[{"enonce":"Touche les trois adjectifs attributs, ceux qui suivent « ist », « sind » ou « bleibt ».","aide":"Ils viennent après le verbe, pas devant un nom.","type":"zone","document":"wien","multiple":true},{"enonce":"Complète : « Les enfants sont fatigués. »","aide":"Après *sein*, l’adjectif ne change pas.","type":"trous","segments":["Die Kinder sind ",0,"."],"banque":["müder","müden","müdes","müde"]},{"enonce":"Pourquoi écrit-on « Die Stadt ist groß » et non « große » ?","aide":"Pense à la place de l’adjectif par rapport au verbe.","type":"choix","options":[{"id":"a","texte":"Groß est un attribut, donc il se décline"},{"id":"b","texte":"Après sein, l’adjectif attribut reste invariable"},{"id":"c","texte":"Stadt est féminin, il faut donc un -e"},{"id":"d","texte":"Après ist, l’adjectif prend toujours -en"}],"multiple":false}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m8","m13","m17"]},"explication":"**groß**, **freundlich** et **schön** sont attributs : ils suivent *sein* ou *bleiben*. *neues* est épithète, devant *Fahrrad*."},{"cle":{"type":"trous","trous":[["mude"]]},"affichage":"müde","explication":"**Die Kinder sind müde.** L’adjectif attribut reste à sa forme nue, même avec un sujet au pluriel."},{"cle":{"type":"choix","ids":["b"]},"explication":"**Après *sein*, *werden* et *bleiben*, l’adjectif attribut ne se décline jamais.** Le français accorde (« grande »), l’allemand non."}]$ex$::jsonb),
  ('8ac8fba3-6ef4-59d4-b1bf-8840c1cacf0c'::uuid, 2, 2, 10, 35, 4,
   $ex${"titre":"Une annonce : devant ou après ?","competence":"analyser-texte","situation":"Jonas a mis une annonce sur le tableau du lycée pour vendre des meubles. Observe où se trouvent les adjectifs.","documents":[{"id":"anz","type":"texte","genre":"article","titre":"Zu verkaufen","blocs":["Ein alter Tisch und ein neues Fahrrad. Der Tisch ist stabil, das Fahrrad ist schnell und die Stühle sind sehr bequem."],"source":"Petite annonce écrite pour l’exercice"}],"questions":[{"enonce":"Touche les deux adjectifs épithètes, ceux qui sont devant le nom.","aide":"Ils portent une terminaison, et un nom les suit tout de suite.","type":"zone","document":"anz","multiple":true},{"enonce":"Touche les trois adjectifs attributs, qui ne portent aucune terminaison.","aide":"Ils viennent après *ist* ou *sind*.","type":"zone","document":"anz","multiple":true},{"enonce":"Range chaque phrase : l’adjectif est-il attribut ou épithète ?","aide":"Cherche si l’adjectif vient après le verbe ou devant le nom.","type":"categories","categories":[{"id":"c0","texte":"Attribut (invariable)"},{"id":"c1","texte":"Épithète (décliné)"}],"items":[{"id":"i0","texte":"Die Kinder sind müde."},{"id":"i1","texte":"Das Auto ist teuer."},{"id":"i2","texte":"Ein teures Auto steht da."},{"id":"i3","texte":"Die müden Kinder schlafen."}]},{"enonce":"Remets en ordre : « Le chat est très petit. » La phrase commence par Die Katze.","aide":"Le verbe est en deuxième position ; l’attribut vient en dernier.","type":"ordre","items":[{"id":"a","texte":"klein"},{"id":"b","texte":"Die Katze"},{"id":"c","texte":"ist"},{"id":"d","texte":"sehr"}]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m1","m5"]},"explication":"**alter** (*ein alter Tisch*) et **neues** (*ein neues Fahrrad*) sont devant le nom : ils se déclinent."},{"cle":{"type":"zone","ids":["m10","m14","m20"]},"explication":"**stabil**, **schnell** et **bequem** suivent le verbe *sein* : ils restent invariables, même pour *die Stühle* au pluriel."},{"cle":{"type":"categories","items":{"i0":"c0","i1":"c0","i2":"c1","i3":"c1"}},"explication":"Après le verbe (*ist teuer*, *sind müde*), l’adjectif ne change pas. Devant le nom (*ein teures Auto*, *die müden Kinder*), il se décline."},{"cle":{"type":"ordre","ids":["b","c","d","a"]},"explication":"**Die Katze ist sehr klein.** L’adjectif attribut, sans terminaison, se place après le verbe."}]$ex$::jsonb),
  ('8ac8fba3-6ef4-59d4-b1bf-8840c1cacf0c'::uuid, 3, 3, 15, 50, 5,
   $ex${"titre":"Messages dans le train : attribut, adverbe, comparatif","competence":"manier-langue","situation":"Emma discute avec Paul, qui revient d’un voyage à Hambourg. Les mêmes mots changent de rôle : adjectif, adverbe ou comparatif.","documents":[{"id":"train","type":"dialogue","modele":"sms","titre":"Nach Hamburg","participants":[{"nom":"Emma","emoji":"👧","cote":"gauche"},{"nom":"Paul","emoji":"👦","cote":"droite"}],"repliques":[{"qui":"Emma","texte":"Wie war die Fahrt nach Hamburg?"},{"qui":"Paul","texte":"Der Zug fährt schnell, aber er ist teuer."},{"qui":"Emma","texte":"Und dein Bruder? Er singt jetzt im Chor."},{"qui":"Paul","texte":"Ja, er singt schön. Aber der Bus ist billiger."}],"source":"Messages écrits pour l’exercice"}],"questions":[{"enonce":"Touche les deux adverbes : ils décrivent un verbe, et non un nom.","aide":"En allemand, l’adverbe a la même forme que l’adjectif.","type":"zone","document":"train","multiple":true},{"enonce":"Touche l’adjectif attribut qui suit « ist » et garde sa forme nue.","aide":"Ne choisis pas le mot qui se termine par -er.","type":"zone","document":"train","multiple":false},{"enonce":"Dans « Der Bus ist billiger », que marque la terminaison -er ?","aide":"Emma et Paul comparent le train et le bus.","type":"choix","options":[{"id":"a","texte":"Le comparatif"},{"id":"b","texte":"Le masculin singulier"},{"id":"c","texte":"Le génitif"},{"id":"d","texte":"Le pluriel"}],"multiple":false},{"enonce":"Associe chaque phrase allemande à sa traduction.","aide":"*schön* est « bien » après un verbe d’action, « beau » après *sein* ou *bleiben*.","type":"association","gauche":[{"id":"g0","texte":"Er singt schön"},{"id":"g1","texte":"Das Lied ist schön"},{"id":"g2","texte":"Der Bus ist billiger"},{"id":"g3","texte":"Das Wetter bleibt schön"}],"droite":[{"id":"d0","texte":"La chanson est belle"},{"id":"d1","texte":"Il chante bien"},{"id":"d2","texte":"Le temps reste beau"},{"id":"d3","texte":"Le bus est moins cher"}]},{"enonce":"Remets en ordre : « Je trouve le film ennuyeux. » La phrase commence par Ich.","aide":"*finden* est en deuxième position ; l’attribut du COD vient à la fin.","type":"ordre","items":[{"id":"a","texte":"langweilig"},{"id":"b","texte":"den Film"},{"id":"c","texte":"finde"},{"id":"d","texte":"Ich"}]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m9","m25"]},"explication":"**schnell** (*fährt schnell*) et **schön** (*singt schön*) complètent un verbe : ce sont des adverbes, sans terminaison."},{"cle":{"type":"zone","ids":["m13"]},"explication":"**teuer** suit *ist* : c’est un attribut invariable. *billiger* est un comparatif : son -er est la marque du comparatif, pas un accord."},{"cle":{"type":"choix","ids":["a"]},"explication":"**Le comparatif** : *billiger* = « moins cher ». Ce n’est pas un accord avec *Bus*."},{"cle":{"type":"association","paires":{"g1":"d0","g0":"d1","g3":"d2","g2":"d3"}},"explication":"Le même mot *schön* sert d’adverbe (*singt schön* = « chante bien ») ou d’attribut (*ist schön* = « est belle »)."},{"cle":{"type":"ordre","ids":["d","c","b","a"]},"explication":"**Ich finde den Film langweilig.** Avec *finden*, l’adjectif qualifie le COD et reste invariable."}]$ex$::jsonb),
  ('ae0a3bfb-73a9-554f-95a1-d5ea673e88af'::uuid, 1, 1, 5, 20, 3,
   $ex${"titre":"Le quotidien de Nele","competence":"comprendre-langue","situation":"Nele se présente à sa correspondante française. Elle raconte où elle habite, comment elle va à l’école et d’où vient son amie.","documents":[{"id":"nele","type":"texte","genre":"recit","titre":"Mein Alltag","blocs":["Ich wohne bei meinen Eltern. Ich fahre mit dem Bus zur Schule. Meine Freundin kommt aus der Schweiz. Sie lernt seit einem Jahr Deutsch."],"source":"Texte écrit pour l’exercice"}],"questions":[{"enonce":"Touche les cinq prépositions qui sont toujours suivies du datif.","aide":"Pense à la formule aus · bei · mit · nach · seit · von · zu.","type":"zone","document":"nele","multiple":true},{"enonce":"Associe chaque préposition à son sens.","aide":"Retrouve chaque préposition dans le texte de Nele.","type":"association","gauche":[{"id":"g0","texte":"aus"},{"id":"g1","texte":"bei"},{"id":"g2","texte":"mit"},{"id":"g3","texte":"seit"}],"droite":[{"id":"d0","texte":"depuis"},{"id":"d1","texte":"en provenance de"},{"id":"d2","texte":"chez"},{"id":"d3","texte":"avec, en (transport)"}]},{"enonce":"Complète : « Il va en train et habite chez sa tante. »","aide":"Après ces prépositions, le datif : *der Zug* est masculin, *die Tante* féminin.","type":"trous","segments":["Er fährt mit ",0," Zug und wohnt bei ",1," Tante."],"banque":["dem","seiner","seine","den"]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m2","m7","m10","m15","m20"]},"explication":"**bei**, **mit**, **zur** (= *zu der*), **aus** et **seit** régissent toujours le datif."},{"cle":{"type":"association","paires":{"g3":"d0","g0":"d1","g1":"d2","g2":"d3"}},"explication":"*aus* = hors de, *bei* = chez, *mit* = avec (ou « en » avec un moyen de transport), *seit* = depuis."},{"cle":{"type":"trous","trous":[["dem"],["seiner"]]},"affichage":"dem · seiner","explication":"**mit dem Zug** (masculin datif : *dem*) et **bei seiner Tante** (féminin datif : *-er*)."}]$ex$::jsonb),
  ('ae0a3bfb-73a9-554f-95a1-d5ea673e88af'::uuid, 2, 2, 10, 35, 4,
   $ex${"titre":"Où est Mara ?","competence":"manier-langue","situation":"Lukas cherche Mara, qui enchaîne plusieurs rendez-vous. Dans leurs messages, plusieurs prépositions sont contractées avec l’article.","documents":[{"id":"mara","type":"dialogue","modele":"sms","titre":"Wo bist du?","participants":[{"nom":"Lukas","emoji":"👧","cote":"gauche"},{"nom":"Mara","emoji":"👦","cote":"droite"}],"repliques":[{"qui":"Lukas","texte":"Wo bist du?"},{"qui":"Mara","texte":"Ich bin beim Arzt. Danach gehe ich zur Apotheke und dann zum Bahnhof."},{"qui":"Lukas","texte":"Kommst du vom Arzt direkt zu mir?"},{"qui":"Mara","texte":"Nein, erst nach dem Essen."}],"source":"Messages écrits pour l’exercice"}],"questions":[{"enonce":"Touche les quatre prépositions contractées avec l’article.","aide":"Elles se terminent par -m ou -r et remplacent *bei dem*, *zu der*, *zu dem*, *von dem*.","type":"zone","document":"mara","multiple":true},{"enonce":"Associe chaque forme pleine à sa contraction.","aide":"Garde la même préposition et fusionne-la avec l’article.","type":"association","gauche":[{"id":"g0","texte":"zu der"},{"id":"g1","texte":"zu dem"},{"id":"g2","texte":"bei dem"},{"id":"g3","texte":"von dem"}],"droite":[{"id":"d0","texte":"zum"},{"id":"d1","texte":"beim"},{"id":"d2","texte":"zur"},{"id":"d3","texte":"vom"}]},{"enonce":"Complète : « Nous allons à la piscine. »","aide":"*Schwimmbad* est neutre.","type":"trous","segments":["Wir gehen ",0," Schwimmbad."],"banque":["zum","beim","vom","zur"]},{"enonce":"Remets en ordre : « Après le repas, je vais à la pharmacie. » La phrase commence par Nach dem Essen.","aide":"Le groupe de temps est en tête, donc le verbe passe avant le sujet.","type":"ordre","items":[{"id":"a","texte":"zur Apotheke"},{"id":"b","texte":"Nach dem Essen"},{"id":"c","texte":"gehe"},{"id":"d","texte":"ich"}]}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m5","m10","m14","m18"]},"explication":"**beim**, **zur**, **zum** et **vom** sont des contractions obligatoires dans l’usage courant."},{"cle":{"type":"association","paires":{"g1":"d0","g2":"d1","g0":"d2","g3":"d3"}},"explication":"*zu der → zur*, *zu dem → zum*, *bei dem → beim*, *von dem → vom*."},{"cle":{"type":"trous","trous":[["zum"]]},"affichage":"zum","explication":"**zum Schwimmbad** : *zu dem* se contracte en *zum* (masculin et neutre)."},{"cle":{"type":"ordre","ids":["b","c","d","a"]},"explication":"**Nach dem Essen gehe ich zur Apotheke.** *nach* + datif ; le verbe reste en deuxième position."}]$ex$::jsonb),
  ('ae0a3bfb-73a9-554f-95a1-d5ea673e88af'::uuid, 3, 3, 15, 50, 6,
   $ex${"titre":"Une carte postale de Vienne et de Suisse","competence":"argumenter","situation":"Jana prépare un voyage en Autriche puis en Suisse. Elle l’annonce à sa grand-mère et lui répond au sujet de son allemand.","documents":[{"id":"reise","type":"texte","genre":"lettre","titre":"Hallo Oma","blocs":["Morgen fahre ich mit dem Zug nach Wien. Am Samstag fliege ich in die Schweiz, zu meinem Onkel. Ich bleibe bei ihm bis Montag. Die Schokolade für dich ist aus der Schweiz."],"source":"Lettre écrite pour l’exercice"},{"id":"oma","type":"dialogue","modele":"sms","titre":"Oma fragt","participants":[{"nom":"Oma","emoji":"👧","cote":"gauche"},{"nom":"Jana","emoji":"👦","cote":"droite"}],"repliques":[{"qui":"Oma","texte":"Wie lange lernst du schon Deutsch?"},{"qui":"Jana","texte":"Ich lerne seit zwei Jahren Deutsch."}],"source":"Messages écrits pour l’exercice"}],"questions":[{"enonce":"Touche la préposition qui précède une ville sans article.","aide":"Wien est un nom de ville.","type":"zone","document":"reise","multiple":false},{"enonce":"Touche la préposition employée devant un pays avec article.","aide":"*die Schweiz* a un article.","type":"zone","document":"reise","multiple":false},{"enonce":"Touche la préposition qui précède une personne comme but du voyage.","aide":"Elle est suivie de *meinem Onkel*.","type":"zone","document":"reise","multiple":false},{"enonce":"Complète : « Je vais à Berlin, en Turquie et chez ma tante. »","aide":"Ville sans article, pays avec article, personne : trois prépositions différentes.","type":"trous","segments":["Ich fahre ",0," Berlin, ",1," die Türkei und ",2," meiner Tante."],"banque":["zu","aus","in","nach","bei"]},{"enonce":"Touche la préposition qui exprime « depuis » dans la réponse de Jana.","aide":"Elle est devant « zwei Jahren ».","type":"zone","document":"oma","multiple":false},{"enonce":"Comment dit-on « Je connais Marie depuis deux ans » ?","aide":"Comme dans la réponse de Jana, un fait qui dure encore s’exprime avec le même temps.","type":"choix","options":[{"id":"a","texte":"Ich werde Marie seit zwei Jahren kennen"},{"id":"b","texte":"Ich habe Marie seit zwei Jahren gekannt"},{"id":"c","texte":"Ich kenne Marie seit zwei Jahren"},{"id":"d","texte":"Ich kannte Marie seit zwei Jahren"}],"multiple":false}]}$ex$::jsonb,
   $ex$[{"cle":{"type":"zone","ids":["m6"]},"explication":"**nach** : *nach Wien*. Les villes et les pays sans article se disent avec *nach*."},{"cle":{"type":"zone","ids":["m12"]},"explication":"**in** : *in die Schweiz* (accusatif). Un pays avec article demande *in* + accusatif."},{"cle":{"type":"zone","ids":["m15"]},"explication":"**zu** : *zu meinem Onkel*. Pour aller chez quelqu’un, on emploie *zu* + datif."},{"cle":{"type":"trous","trous":[["nach"],["in"],["zu"]]},"affichage":"nach · in · zu","explication":"**nach Berlin** (ville sans article), **in die Türkei** (pays avec article, accusatif), **zu meiner Tante** (personne, datif)."},{"cle":{"type":"zone","ids":["m8"]},"explication":"**seit** : *seit zwei Jahren* = « depuis deux ans », avec un datif."},{"cle":{"type":"choix","ids":["c"]},"explication":"**Ich kenne Marie seit zwei Jahren** : avec *seit*, l’allemand emploie le **présent** pour une situation qui dure encore."}]$ex$::jsonb)
) AS v (chapter_id, position, etoiles, gemmes, xp, nb_questions, contenu, cles);

INSERT INTO public.exercices (id, chapter_id, position, etoiles, gemmes, xp, nb_questions, contenu)
SELECT s.id, s.chapter_id, s.position, s.etoiles, s.gemmes, s.xp, s.nb_questions, s.contenu
FROM exercices_seed s
JOIN public.chapters c ON c.id = s.chapter_id
ON CONFLICT (id) DO UPDATE
  SET etoiles      = EXCLUDED.etoiles,
      nb_questions = EXCLUDED.nb_questions,
      contenu      = EXCLUDED.contenu,
      updated_at   = now();

INSERT INTO public.exercices_cles (exercice_id, cles)
SELECT s.id, s.cles
FROM exercices_seed s
JOIN public.exercices e ON e.id = s.id
ON CONFLICT (exercice_id) DO UPDATE SET cles = EXCLUDED.cles;

-- Contrôle : combien d'exercices de ce fichier sont en base, et combien sautés.
DO $$
DECLARE
  v_attendus INTEGER;
  v_poses    INTEGER;
BEGIN
  SELECT count(*) INTO v_attendus FROM exercices_seed;
  SELECT count(*) INTO v_poses FROM public.exercices e JOIN exercices_seed s ON s.id = e.id;
  RAISE NOTICE 'Cahier 1re (1) : % exercices posés sur % (les autres n''ont pas leur chapitre en base).', v_poses, v_attendus;
  DROP TABLE IF EXISTS pg_temp.exercices_seed;
END $$;
