-- =============================================================================
-- Studuel — Migration 225 : LE PROGRAMME DE PHILOSOPHIE (Tle)
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 225 --slugs philosophie
--
-- CONSTAT MESURÉ (node _ASSOCIE/sonde-contenu.mjs, 05/08/2026) : la
-- philosophie Tle n'avait que 5 chapitres, taillés dans un découpage maison
-- (« La conscience et l'inconscient », « La vérité et la raison »…) qui ne
-- correspond à AUCUNE des notions au programme du baccalauréat. Un élève qui
-- révisait « le devoir », « la technique » ou « le temps » ne trouvait rien.
-- Cette migration installe les 17 notions officielles, la liberté étant
-- éclatée en trois chapitres (indépendance / libre arbitre / liberté
-- politique) — soit 19 chapitres.
--
-- Cette migration apporte : 19 chapitres, 19 leçons,
-- 19 quiz et 152 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 0. Ménage ----------------------------------------------------------------
-- [philosophie] La file « À revoir » d'abord : review_items.item_id n'a PAS de clé
-- [philosophie] étrangère (il pointe soit une question, soit une carte). Rien ne casse si on
-- [philosophie] l'oublie — le lecteur écarte déjà un contenu disparu — mais le compteur
-- [philosophie] « X à revoir » continuerait de compter des questions qui n'existent plus.
DELETE FROM public.review_items ri
 USING public.quiz_questions qq, public.quizzes qz, public.lessons l,
       public.chapters c, public.subjects s
 WHERE ri.item_kind = 'question'
   AND ri.item_id = qq.id
   AND qq.quiz_id = qz.id
   AND qz.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'philosophie'
   AND c.level = 'Tle'
   AND l.title IN ('L''essentiel du cours', 'Exercices types');

-- [philosophie] Les quiz ensuite : quizzes.lesson_id est ON DELETE SET NULL, donc
-- [philosophie] supprimer le chapitre laisserait derrière lui des quiz orphelins, rattachés à
-- [philosophie] aucune leçon mais toujours servis par le moteur de révision.
DELETE FROM public.quizzes q
 USING public.lessons l, public.chapters c, public.subjects s
 WHERE q.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'philosophie'
   AND c.level = 'Tle'
   AND l.title IN ('L''essentiel du cours', 'Exercices types');

-- [philosophie] Puis les chapitres : leçons, fiches de révision, supports, progression
-- [philosophie] et chapitres cochés partent en cascade (toutes les clés étrangères vers
-- [philosophie] chapters et lessons sont ON DELETE CASCADE).
DELETE FROM public.chapters c
 USING public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'philosophie'
   AND c.level = 'Tle'
   AND EXISTS (
     SELECT 1 FROM public.lessons l
      WHERE l.chapter_id = c.id
        AND l.title IN ('L''essentiel du cours', 'Exercices types')
   );

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position)
SELECT v.id, s.id, v.level, v.title, v.position
  FROM (VALUES
    ('8df57df5-b863-5c0d-9e7c-13b2f0214ddc'::uuid, 'philosophie', 'Tle', 'La conscience', 1),
    ('f712a205-ddcf-50d4-bebf-a32c2e2aa4e2'::uuid, 'philosophie', 'Tle', 'L’inconscient', 2),
    ('555a9a35-e78f-5612-8d80-3c1a441becb1'::uuid, 'philosophie', 'Tle', 'La nature', 3),
    ('1af1e7a9-efc1-52b8-adaa-c01f4b863ba9'::uuid, 'philosophie', 'Tle', 'Le bonheur', 4),
    ('15c7919c-6b47-5ac7-b80f-aae35ae12c84'::uuid, 'philosophie', 'Tle', 'Le travail', 5),
    ('a9c5fb62-742f-5f14-8097-2203333654b9'::uuid, 'philosophie', 'Tle', 'L’État', 6),
    ('2e894746-3958-5712-b2d1-3dc26f59c121'::uuid, 'philosophie', 'Tle', 'La justice et le droit', 7),
    ('f7d54ea5-7a57-5c35-8910-ef6e1fd05c7d'::uuid, 'philosophie', 'Tle', 'Le devoir', 8),
    ('8a83108a-1f1c-5b30-93cc-4e06e42a79e3'::uuid, 'philosophie', 'Tle', 'La raison', 9),
    ('e91004a8-9ad3-5a14-992e-add1a97a8730'::uuid, 'philosophie', 'Tle', 'La liberté de faire ce qui me plaît', 10),
    ('ec09b321-34f9-5e16-88ea-7d5fcebe79ab'::uuid, 'philosophie', 'Tle', 'Le libre arbitre', 11),
    ('00a8ab06-4e88-5e98-ac95-4c986eb57c10'::uuid, 'philosophie', 'Tle', 'La liberté politique', 12),
    ('8db367be-d98a-518c-8116-d39e8f5f129d'::uuid, 'philosophie', 'Tle', 'Le langage', 13),
    ('36834bd6-7806-517b-9ff1-2ce9ee56f042'::uuid, 'philosophie', 'Tle', 'La vérité', 14),
    ('e96db71d-2388-59bd-ab80-9b5d2e71f4be'::uuid, 'philosophie', 'Tle', 'La science', 15),
    ('8922c185-ca43-55a7-bc0c-6505750bd2b8'::uuid, 'philosophie', 'Tle', 'La technique', 16),
    ('3f486caa-bf4f-5818-aa58-17f56f064407'::uuid, 'philosophie', 'Tle', 'L’art', 17),
    ('fc07b499-c020-5144-a6e4-f41d140f9b20'::uuid, 'philosophie', 'Tle', 'La religion', 18),
    ('a90225b2-7929-556f-b864-1970231596e3'::uuid, 'philosophie', 'Tle', 'Le temps', 19)
  ) AS v(id, slug, level, title, position)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('5a495098-0f0b-54c2-a72b-98af1b556f14', '8df57df5-b863-5c0d-9e7c-13b2f0214ddc', 'Être présent à soi', E'« Conscience » vient du latin *cum scientia* : accompagné de savoir. Être conscient, ce n''est pas seulement percevoir, c''est savoir que l''on perçoit.\n\n## Trois degrés\nLa conscience **immédiate** est le rapport spontané au monde : je vois, je marche, j''ai froid. La conscience **réfléchie** est le retour de la pensée sur elle-même : je sais que je vois. La conscience **morale**, elle, ne dit pas ce qui est mais ce qui vaut : elle juge ce que je fais.\n\n## Le sujet pensant\nDescartes cherche une certitude que le doute ne puisse pas entamer. Il peut douter de ses sens, du monde, de son corps — mais s''il doute, il pense, et s''il pense, il est. « Je pense, donc je suis » (*Discours de la méthode*, 1637). Le doute n''est pas ici du scepticisme : il est **méthodique**, il sert à trouver un point fixe.\n\n## Les soupçons\nKant accorde que le « je pense » accompagne toutes mes représentations, mais il ajoute que je me connais seulement comme phénomène : la conscience ne me livre pas ce que je suis en moi-même. Freud fait de la conscience une petite partie du psychisme. Sartre, lui, retourne l''affaire : la conscience n''est pas une chose, elle est vide, elle n''est rien d''autre que le mouvement par lequel elle vise le monde et se choisit.\n\n## Une séparation d''avec soi\nÊtre conscient, c''est ne plus coïncider avec soi : je me juge, je me projette, je me regrette. Pascal y voit à la fois notre inquiétude et notre grandeur — l''homme est « un roseau, le plus faible de la nature, mais un roseau pensant », et « toute notre dignité consiste en la pensée ».', 1),
  ('beaa53ba-0979-5b47-bc99-03b70556b658', 'f712a205-ddcf-50d4-bebf-a32c2e2aa4e2', 'Ce qui agit en nous à notre insu', E'Peut-on parler d''une pensée qui échappe à la conscience ? L''idée paraît contradictoire — et c''est pourtant l''hypothèse que Freud transforme en méthode.\n\n## Ce que l''inconscient n''est pas\nIl ne désigne pas le **non-conscient** biologique (la digestion, le rythme cardiaque), ni l''inattention, ni l''oubli banal. L''inconscient **psychique** est fait de représentations qui ont un sens et qui agissent : des pensées, mais des pensées que le sujet ne peut pas reconnaître comme siennes.\n\n## Le refoulement et ses retours\nCertains désirs, incompatibles avec les exigences morales et sociales, sont **refoulés** : repoussés hors de la conscience par une censure. Ils ne disparaissent pas pour autant, ils reviennent déguisés — dans les **rêves**, les **lapsus**, les **actes manqués**, les **symptômes**. Rien n''est fortuit dans la vie psychique : c''est le **déterminisme psychique**.\n\n## Les deux topiques\nPremière topique : inconscient / préconscient / conscient. Seconde topique : le **Ça** (les pulsions, qui ne connaît que le plaisir), le **Moi** (qui compose avec le réel) et le **Surmoi** (les interdits intériorisés). D''où la formule : le Moi « n''est pas maître dans sa propre maison ».\n\n## L''objection de la mauvaise foi\nSartre refuse l''inconscient : pour censurer un désir, la censure devrait déjà le connaître — donc en être consciente. Ce que Freud appelle refoulement, il l''appelle **mauvaise foi** : une fuite de la conscience devant sa propre liberté, dont on reste responsable. C''est là tout l''enjeu : l''inconscient explique-t-il l''homme, ou l''excuse-t-il ?', 1),
  ('0bd1e271-9b33-568e-b2c6-9ec1aa206290', '555a9a35-e78f-5612-8d80-3c1a441becb1', 'Ce qui n’est pas l’œuvre de l’homme', E'Le mot « nature » sert à tout : la campagne, l''univers, l''essence d''une chose, ce qui est normal. Une dissertation commence toujours par y mettre de l''ordre.\n\n## Deux sens à distinguer\nLa **nature d''une chose** est ce qu''elle est essentiellement (« la nature du triangle »). **La nature** est l''ensemble de ce qui existe et se produit sans l''homme. Les Grecs opposent la *phusis*, ce qui pousse et se développe de soi-même, à la *technè*, ce qui est produit par l''art humain. Aristote y ajoute une idée forte : dans la nature, chaque être tend vers sa fin — « la nature ne fait rien en vain ».\n\n## Nature et culture\nEst **naturel** ce qui est universel et spontané ; est **culturel** ce qui varie d''une société à l''autre et relève de la norme. Lévi-Strauss note que la prohibition de l''inceste tient les deux à la fois : universelle comme la nature, règle comme la culture. C''est le seuil où l''humain commence.\n\n## Y a-t-il une nature humaine ?\nL''état de nature de Hobbes ou de Rousseau n''est pas un fait historique : c''est une **fiction méthodique** qui sert à comprendre ce que la société nous a fait. Chez Hobbes, l''homme sans État vit dans « la guerre de tous contre tous » ; chez Rousseau, il est paisible, ignorant, mû par l''amour de soi et la pitié. Sartre récuse la question : « l''existence précède l''essence », rien n''est donné d''avance à l''homme.\n\n## Maîtriser ou ménager\nDescartes veut nous rendre « comme maîtres et possesseurs de la nature » : la connaître pour l''utiliser. La crise écologique retourne le programme — Hans Jonas demande d''agir de telle sorte que les effets de nos actes soient compatibles avec la permanence d''une vie humaine sur terre. La nature devient alors moins une réserve qu''une responsabilité.', 1),
  ('4cf96624-f485-50df-886b-c186a4a2f0db', '1af1e7a9-efc1-52b8-adaa-c01f4b863ba9', 'Le souverain bien', E'Tout le monde veut être heureux : c''est ce que les philosophes appellent le **souverain bien**, la fin que l''on recherche pour elle-même et non pour autre chose. Le désaccord commence dès qu''on demande en quoi il consiste.\n\n## Un idéal flou\nKant y voit « un idéal, non de la raison, mais de l''imagination » : chacun le veut, personne ne peut dire précisément ce qu''il veut. Le bonheur n''est pas non plus le **plaisir**, qui est ponctuel et fugitif, ni la **joie**, qui est une émotion : il désigne un état durable de satisfaction complète.\n\n## Les recettes antiques\n**Épicure** distingue les désirs naturels et nécessaires (manger), naturels et non nécessaires (bien manger), ni naturels ni nécessaires (la gloire, la richesse). Réduire ses désirs suffit : le bonheur est l''*ataraxie*, l''absence de trouble. Les **stoïciens** (Épictète, Marc Aurèle) distinguent ce qui dépend de nous — nos jugements — et ce qui n''en dépend pas : vouloir changer le reste, c''est se condamner au malheur. **Aristote** répond autrement : le bonheur est l''activité de l''âme conforme à la vertu, dans une vie accomplie ; il y faut aussi des amis et un minimum de biens.\n\n## Les objections\nPascal soutient que nous ne cherchons pas le bonheur mais le **divertissement** : nous fuyons le repos, où nous rencontrerions notre condition. Schopenhauer décrit une oscillation entre la souffrance du manque et l''ennui de la satisfaction. Kant, lui, sépare morale et bonheur : la morale n''apprend pas à être heureux mais à se rendre **digne** de l''être.', 1),
  ('36575839-2814-5d45-ae36-c615b7fa0781', '15c7919c-6b47-5ac7-b80f-aae35ae12c84', 'Peine, œuvre et valeur', E'Le mot vient du latin *tripalium*, un instrument de torture — et la Genèse fait du travail une punition. Pourtant, c''est aussi par lui que l''homme se fait lui-même.\n\n## La nécessité et la peine\nTravailler, c''est transformer la nature pour subsister : une activité contrainte, pénible, qui prend du temps de vie. Les Grecs la réservaient aux esclaves, laissant aux citoyens libres le loisir (*skholè*) — d''où vient notre mot « école ».\n\n## Le travail qui humanise\nHegel renverse ce mépris. Dans la dialectique du **maître et de l''esclave**, c''est l''esclave qui, en travaillant la chose, forme le monde et se forme lui-même : il se reconnaît dans son œuvre, tandis que le maître, qui ne fait que consommer, ne produit rien. Marx ajoute la différence décisive : « ce qui distingue dès l''abord le plus mauvais architecte de l''abeille la plus experte, c''est qu''il a construit la cellule dans sa tête avant de la construire dans la ruche ».\n\n## L''aliénation\nMais le travail peut aussi défaire celui qui travaille. Marx appelle **aliénation** la situation où le travailleur ne se reconnaît plus dans son produit : il vend sa force de travail, l''objet lui échappe, la tâche est parcellisée. Adam Smith avait déjà décrit les gains de la division du travail ; Marx en montre le prix humain.\n\n## Œuvre, travail, action\nHannah Arendt distingue le **travail** (qui produit du consommable et recommence sans fin), l''**œuvre** (qui produit un monde durable) et l''**action** (la parole et l''initiative politiques). Sa question reste ouverte : une société qui ne valorise plus que le travail sait-elle encore ce qu''elle fait des deux autres ?', 1),
  ('f23f1250-39b4-577f-9dba-baf7c1ec69cd', 'a9c5fb62-742f-5f14-8097-2203333654b9', 'Pourquoi obéir à un pouvoir commun', E'L''État n''est pas la société : c''est l''institution qui détient le pouvoir politique sur un territoire, avec ses lois, son administration, sa police, ses tribunaux.\n\n## Le pari de Hobbes\nSans pouvoir commun, dit Hobbes, les hommes sont dans « la guerre de tous contre tous », et la vie y est « solitaire, misérable, dangereuse, animale et brève ». Chacun renonce alors à son droit sur tout au profit d''un souverain — le **Léviathan** — en échange de la sécurité. L''État naît d''un **contrat**, non de la nature.\n\n## Les autres contrats\nLocke n''accepte pas un pouvoir absolu : les individus ont des droits naturels (vie, liberté, propriété) que l''État doit **garantir**, et qu''il perd le droit de gouverner s''il les viole. Rousseau change encore la donne : le peuple ne se donne pas un maître, il devient souverain ; obéir à la **volonté générale** exprimée par la loi, c''est n''obéir qu''à soi-même.\n\n## Ce qui définit l''État moderne\nMax Weber le définit par le **monopole de la violence physique légitime** sur un territoire donné : l''État seul peut contraindre légalement, et cette contrainte est reconnue comme fondée. S''y ajoutent l''impersonnalité du droit et une administration réglée.\n\n## Les critiques\nPour Marx, l''État n''est pas neutre : il est l''instrument par lequel une classe maintient sa domination. La Boétie s''étonne d''autre chose — de la **servitude volontaire**, qui fait que des millions d''hommes obéissent à un seul sans y être forcés. Reste alors la question de fond : jusqu''où l''État doit-il aller, et où commence la tyrannie ?', 1),
  ('88e01c95-541e-59cb-862a-b7cc29e5967c', '2e894746-3958-5712-b2d1-3dc26f59c121', 'Le juste, le légal, le légitime', E'Le droit dit ce qui est **légal** ; la justice demande ce qui est **légitime**. Tant que les deux coïncident, la question dort ; c''est quand une loi paraît injuste qu''elle se réveille.\n\n## Droit positif et droit naturel\nLe **droit positif** est l''ensemble des règles effectivement en vigueur dans une société, à une époque. Le **droit naturel** désigne des principes valables indépendamment des lois écrites, auxquels on peut les mesurer. Antigone, chez Sophocle, oppose déjà « les lois non écrites des dieux » à l''édit de Créon : la scène pose le problème une fois pour toutes.\n\n## Les deux justices d''Aristote\nLa justice **distributive** répartit les biens et les honneurs selon le mérite : c''est une égalité **proportionnelle** (à chacun selon sa contribution). La justice **corrective** rétablit l''équilibre rompu par un tort, indépendamment des personnes : c''est une égalité **arithmétique**. Confondre les deux, c''est se tromper d''exigence.\n\n## La force et la justice\nPascal constate froidement : « ne pouvant faire que ce qui est juste fût fort, on a fait que ce qui est fort fût juste ». Rawls cherche une issue : imaginons des personnes choisissant les règles de leur société sous un **voile d''ignorance**, sans savoir la place qu''elles y occuperont. Elles n''accepteraient d''inégalités que si elles profitent aux plus défavorisés.\n\n## Punir\nPourquoi punir ? Par **rétribution** — la peine répare l''ordre rompu, elle est due au crime ; ou par **prévention** — elle dissuade et protège. Beccaria en tire une règle qui a fait le droit pénal moderne : ce n''est pas la sévérité de la peine qui dissuade, mais sa certitude.', 1),
  ('61be3b16-6148-5546-a407-615bd754c745', 'f7d54ea5-7a57-5c35-8910-ef6e1fd05c7d', 'Agir par devoir', E'Le devoir n''est pas la contrainte. La contrainte me force de l''extérieur ; l''obligation morale me lie de l''intérieur — je peux toujours y désobéir, et c''est pourquoi elle a un sens.\n\n## Par devoir, ou conformément au devoir\nKant introduit la distinction décisive. Le commerçant honnête par intérêt agit **conformément** au devoir ; celui qui l''est parce que c''est juste agit **par** devoir. Seule la seconde intention a une valeur morale : « il n''est rien dans le monde que l''on puisse concevoir sans restriction comme bon, à l''exception d''une bonne volonté ».\n\n## L''impératif catégorique\nUn impératif **hypothétique** dit : si tu veux X, fais Y. L''impératif **catégorique** commande sans condition. Kant en donne deux formulations à retenir : « agis uniquement d''après la maxime qui fait que tu peux vouloir en même temps qu''elle devienne une loi universelle » ; et « agis de façon à traiter l''humanité, en toi comme en autrui, toujours en même temps comme une fin, jamais simplement comme un moyen ».\n\n## Les objections\nBenjamin Constant objecte le cas du mensonge : faut-il dire la vérité à l''assassin qui cherche sa victime ? L''**utilitarisme** (Bentham, Mill) répond autrement — une action est bonne selon ses conséquences, par la plus grande somme de bonheur du plus grand nombre. Nietzsche, lui, soupçonne : la morale du devoir serait une invention des faibles, un **ressentiment** retourné en vertu.\n\n## Conviction et responsabilité\nMax Weber propose une sortie utile : l''**éthique de conviction** juge l''acte sur son principe, l''**éthique de responsabilité** sur ses effets prévisibles. Un homme d''action sérieux tient les deux, sans jamais les confondre.', 1),
  ('2c4e2f76-f1bd-5fda-bbec-01c6507fd790', '8a83108a-1f1c-5b30-93cc-4e06e42a79e3', 'Le pouvoir de rendre raison', E'La raison est double : c''est la **faculté** de penser et de juger, et c''est aussi la **cause** d''une chose — « la raison de ce phénomène ». Les deux sens tiennent ensemble : rendre raison, c''est expliquer.\n\n## Le principe de raison\nLeibniz le formule : « rien n''arrive sans qu''il y ait une raison suffisante ». C''est ce principe qui interdit de se satisfaire du hasard ou du merveilleux, et qui a fait sortir la pensée du mythe : au lieu de raconter comment le monde est né, on cherche par quoi il s''explique.\n\n## Rationalisme et empirisme\nDescartes soutient que la raison — « la chose du monde la mieux partagée » — peut atteindre le vrai par ses seules idées claires et distinctes. Hume répond que toute connaissance vient de l''**expérience**, et que notre idée de causalité n''est qu''une habitude : nous avons vu mille fois B suivre A, nous n''avons jamais vu de lien nécessaire. Kant tranche : « des pensées sans contenu sont vides, des intuitions sans concepts sont aveugles » — il faut les deux.\n\n## Les limites de la raison\nKant montre que la raison s''égare quand elle veut connaître ce qui excède toute expérience possible (Dieu, l''âme, le monde comme totalité) : elle produit alors des raisonnements également démontrables et contradictoires. Pascal ajoute : « le cœur a ses raisons que la raison ne connaît point » — non pour renoncer à penser, mais pour marquer un autre ordre.\n\n## Raison et histoire\nLes Lumières font de la raison une émancipation : « Sapere aude ! Aie le courage de te servir de ton propre entendement », écrit Kant. Le XXe siècle apporte la contre-épreuve : une rationalité purement **instrumentale**, qui calcule parfaitement les moyens sans jamais interroger les fins, peut servir le pire.', 1),
  ('ab5a70b2-64e8-54e4-8baf-88e509714119', 'e91004a8-9ad3-5a14-992e-add1a97a8730', 'Indépendance, caprice et licence', E'Le premier sens du mot est le plus spontané : être libre, ce serait n''être gêné par rien ni personne, faire ce qui me plaît. Ce sens ne résiste pas longtemps à l''examen — et c''est précisément ce qu''une dissertation doit montrer.\n\n## L''indépendance\nAu sens le plus simple, la liberté est l''absence d''obstacle : je suis libre quand rien ne m''empêche de faire ce que je veux. Hobbes en reste à cette définition, celle du mouvement sans entrave. Mais elle laisse une question entière : d''où viennent les désirs que je suis ?\n\n## Le caprice n''est pas la liberté\nSpinoza prend l''exemple de l''ivrogne « qui croit dire par un libre décret de son esprit ce qu''ensuite, à jeun, il voudrait avoir tu ». Les hommes « se croient libres parce qu''ils ont conscience de leurs actions et ignorants des causes qui les déterminent ». Suivre le premier désir venu, ce n''est pas être libre : c''est obéir à ce qui, en nous, a été mis par autre chose — la mode, l''habitude, la publicité, l''humeur.\n\n## La limite d''autrui\n« La liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui » (Déclaration des droits de l''homme et du citoyen, 1789, article 4). La liberté sans limite est la **licence** : elle se détruit elle-même, puisque la liberté de chacun y devient la proie de la force du plus fort.\n\n## Se libérer de soi\nD''où le renversement de toute la tradition : être libre, ce n''est pas assouvir ses désirs, c''est en devenir le maître. Épicure trie ses désirs, les stoïciens s''attachent à ce qui dépend d''eux, Rousseau écrit que « l''impulsion du seul appétit est esclavage, et l''obéissance à la loi qu''on s''est prescrite est liberté ». La liberté cesse d''être un point de départ : elle devient une conquête.', 1),
  ('d553cb6e-02b6-564b-aabf-a525ad6d7928', 'ec09b321-34f9-5e16-88ea-7d5fcebe79ab', 'Sommes-nous les auteurs de nos actes ?', E'Le libre arbitre est le pouvoir de choisir entre plusieurs possibles, et d''avoir pu faire autrement. Sans lui, la responsabilité et le mérite s''effondrent : on ne juge pas une pierre qui tombe.\n\n## Le pouvoir de la volonté\nDescartes fait de la volonté ce qu''il y a de plus grand en nous : « elle est si ample qu''elle nous rend en quelque façon semblables à Dieu ». Mais il ajoute une nuance qu''on oublie souvent : la **liberté d''indifférence** — choisir sans aucune raison, à pile ou face — est « le plus bas degré de la liberté ». Choisir librement, c''est choisir en connaissance de cause.\n\n## Le déterminisme\nToute chose a une cause ; nos actes aussi. Spinoza y voit une illusion tenace, et Laplace pousse l''idée jusqu''au bout : une intelligence qui connaîtrait toutes les forces et toutes les positions à un instant donné saurait l''avenir. Les sciences humaines rendent l''objection concrète — origine sociale, éducation, neurologie, contexte : nos décisions sont conditionnées.\n\n## Une confusion à éviter\nLe **fatalisme** dit que l''avenir arrivera quoi que je fasse : mes actes ne changent rien. Le **déterminisme** dit que mes actes ont des causes — mais ils sont bien des causes à leur tour. C''est très différent : un déterministe conséquent peut soutenir que ce que je fais compte, tout en niant que j''aurais pu faire autrement.\n\n## Sauver la liberté\nKant sépare les plans : comme phénomène, je suis soumis aux lois de la nature ; comme sujet moral, je dois me penser libre, sinon le devoir n''aurait aucun sens. Sartre va plus loin : l''homme est « condamné à être libre », il ne peut pas ne pas choisir, et invoquer ses déterminations est déjà un choix — celui de la mauvaise foi.', 1),
  ('2a09ce1a-02f2-5b2f-88f8-cb11d6730277', '00a8ab06-4e88-5e98-ac95-4c986eb57c10', 'Obéir à la loi qu’on s’est prescrite', E'Comment être libre dans une société qui impose des lois ? La réponse dépend de ce que l''on met sous le mot : ou bien la loi est l''ennemie de la liberté, ou bien elle en est la condition.\n\n## La loi rend libre\nPour Rousseau, l''obéissance n''est pas la servitude quand la loi est l''expression de la **volonté générale** : le citoyen obéit à ce qu''il a voulu comme membre du souverain. Ce qui compte n''est donc pas la quantité de lois, mais leur origine. Sans loi, ce n''est pas la liberté qui règne : c''est la force.\n\n## Deux libertés\nBenjamin Constant distingue la liberté des **Anciens** — participer directement aux décisions collectives, quitte à ce que l''individu soit entièrement soumis à la cité — et la liberté des **Modernes** : jouir paisiblement de son indépendance privée, avec des droits garantis contre le pouvoir. Une démocratie sérieuse tient les deux, sans sacrifier l''une à l''autre.\n\n## Les garanties\nLa liberté politique ne repose pas sur la vertu des gouvernants mais sur des **institutions**. Montesquieu : « pour qu''on ne puisse abuser du pouvoir, il faut que, par la disposition des choses, le pouvoir arrête le pouvoir » — d''où la séparation des pouvoirs, l''État de droit, l''indépendance de la justice et la liberté de la presse.\n\n## Les menaces\nTocqueville avertit contre la **tyrannie de la majorité** : un pouvoir légitime par le nombre peut écraser les minorités et l''esprit d''indépendance. Mill pose la limite : la seule raison d''user de la contrainte envers un individu est d''**empêcher qu''il ne nuise à autrui**. Reste la question limite : que faire quand la loi est injuste ? La désobéissance civile assume la sanction, publiquement, au nom du droit lui-même.', 1),
  ('36b90773-556c-5572-a5ca-cf6df7f13e6c', '8db367be-d98a-518c-8116-d39e8f5f129d', 'Parler, penser, agir', E'Le **langage** est la faculté de communiquer par des signes ; une **langue** est le système particulier d''une communauté ; la **parole** en est l''usage individuel. Trois mots à ne pas confondre.\n\n## Le signe et la convention\nSaussure décompose le signe en **signifiant** (l''image sonore) et **signifié** (le concept), et pose que leur lien est **arbitraire** : rien dans l''animal n''impose le mot « chien » plutôt que *dog*. Arbitraire ne veut pas dire libre : le locuteur ne peut pas changer sa langue à volonté, elle lui préexiste.\n\n## Le langage et la pensée\nPeut-on penser sans mots ? Hegel soutient que c''est dans le mot que la pensée trouve son existence : sans langage, elle reste une brume. Bergson objecte que le mot commun écrase la nuance et la singularité du vécu : « le mot brutal, qui emmagasine ce qu''il y a de stable, d''impersonnel dans les impressions de l''humanité, écrase les impressions délicates et fugitives de notre conscience individuelle ». Les deux ont raison contre un tiers : le langage rend la pensée possible **et** la trahit.\n\n## Parler, c''est agir\nAustin remarque que certaines phrases ne décrivent rien : « je promets », « je te baptise », « la séance est ouverte » — ce sont des **performatifs**, elles font ce qu''elles disent. D''où le pouvoir des mots : promettre, insulter, ordonner, séduire, propager. Une langue truquée fabrique une pensée truquée — c''est ce que montrent les analyses de la propagande.\n\n## Le propre de l''homme ?\nLes abeilles transmettent des informations, certains animaux communiquent. Mais Benveniste souligne une différence : leur code est fixe, sans dialogue ni combinaison libre. Descartes en tirait un argument : ce qui manque aux animaux n''est pas la voix, c''est le pouvoir d''arranger des mots pour répondre à toute situation nouvelle.', 1),
  ('f6af7cb3-adb7-5cc3-8297-377e7a69610b', '36834bd6-7806-517b-9ff1-2ce9ee56f042', 'Ce qui se dit du discours', E'Une chose n''est ni vraie ni fausse : elle est. Le vrai et le faux se disent d''un **jugement**, d''une proposition. C''est la première précaution à prendre, et elle règle déjà la moitié des confusions.\n\n## La définition classique\nEst vrai le discours **conforme à ce qui est** : c''est la vérité-correspondance, ou adéquation. La difficulté saute aux yeux : pour comparer mon idée à la chose, il faudrait sortir de ma pensée. D''où d''autres critères — la **cohérence** (pas de contradiction), l''**évidence** (Descartes : ce qui se présente si clairement à l''esprit qu''on ne peut en douter), la **vérification** par l''expérience.\n\n## Vérité, réalité, opinion\nLe vrai n''est pas le réel, et il n''est pas non plus le vraisemblable. L''**opinion** (*doxa*) est un avis reçu sans examen : elle peut se trouver juste par accident, mais elle ne sait pas pourquoi elle l''est. Dans l''allégorie de la caverne, Platon décrit des prisonniers qui prennent les ombres pour la réalité — et qui n''accueillent pas volontiers celui qui revient leur dire qu''ils se trompent.\n\n## Le relativisme et sa réfutation\nProtagoras affirme que « l''homme est la mesure de toute chose » : à chacun sa vérité. L''objection est classique et redoutable — si toute vérité est relative, cette affirmation l''est aussi, et se détruit elle-même. Confondre la tolérance (respecter les personnes) et le relativisme (renoncer à distinguer le vrai du faux) revient à désarmer la discussion.\n\n## Vérité et pouvoir\nChercher la vérité n''est pas neutre : elle dérange les intérêts établis. Le procès de Socrate, celui de Galilée, la fabrication moderne du mensonge organisé rappellent que la vérité a besoin d''institutions — écoles, sciences, presse libre — pour être autre chose qu''une opinion parmi d''autres.', 1),
  ('8213594d-f142-5b3c-9d9a-7801d7e2892c', 'e96db71d-2388-59bd-ab80-9b5d2e71f4be', 'Expérience, hypothèse, réfutation', E'La science ne se définit pas par son objet mais par sa **méthode** : elle explique au lieu de raconter, elle démontre au lieu d''affirmer, et elle accepte d''avoir tort.\n\n## La rupture avec le mythe\nLe mythe raconte une origine ; la science cherche des lois. Galilée fait le pas décisif en écrivant que le grand livre de la nature « est écrit en langue mathématique » : mesurer, quantifier, idéaliser (le plan sans frottement, le corps sans résistance de l''air) — la science ne décrit pas le monde tel qu''il apparaît, elle en construit le modèle.\n\n## La méthode expérimentale\nClaude Bernard en donne la formule : l''**observation** fait naître une **hypothèse**, l''**expérience** la met à l''épreuve, et le savant doit être prêt à l''abandonner. « L''expérimentateur doit douter, fuir les idées fixes ». Le fait ne parle jamais seul : il ne répond qu''à une question qu''on lui pose.\n\n## Induire, ou réfuter\nPasser de « tous les cygnes observés sont blancs » à « tous les cygnes sont blancs », c''est induire — et Hume montre que rien ne le garantit. Popper renverse le problème : aucune expérience ne prouve définitivement une théorie, une seule peut la **réfuter**. Est donc scientifique un énoncé **falsifiable**, qui prend le risque d''être démenti ; une théorie que rien ne pourrait contredire n''est pas invincible, elle est hors du jeu.\n\n## Les révolutions\nBachelard montre que le savoir ne s''accumule pas sagement : il progresse contre des **obstacles épistémologiques**, des évidences familières qu''il faut détruire. Kuhn décrit des **paradigmes** qui se succèdent par crises. La science n''est donc pas un stock de vérités définitives, mais une pratique collective, faillible et contrôlée — ce qui fait sa force, non sa faiblesse.', 1),
  ('db024c6b-c9c6-52a7-a099-4912a6eccc78', '8922c185-ca43-55a7-bc0c-6505750bd2b8', 'Prolonger le corps, transformer le monde', E'La technique est l''ensemble des procédés et des outils par lesquels l''homme transforme son milieu. Elle n''est pas de la science appliquée : elle lui est bien antérieure — on taillait des silex avant d''avoir des théories.\n\n## L''outil et l''espèce\nBergson propose de nommer notre espèce *Homo faber* plutôt que *sapiens* : l''intelligence se reconnaît d''abord à sa capacité de fabriquer des outils, et des outils pour fabriquer des outils. L''outil prolonge le corps : le marteau prolonge le poing, la roue la marche, l''ordinateur la mémoire.\n\n## Le mythe de Prométhée\nDans le mythe raconté par Protagoras chez Platon, l''homme naît nu, sans griffes ni fourrure : la technique compense un défaut originel. Elle n''est donc pas un luxe mais la condition même de la survie humaine — et Descartes lui donne son programme moderne : connaître la nature pour nous en rendre « comme maîtres et possesseurs », notamment pour la santé.\n\n## Quand le moyen devient une fin\nLa question moderne n''est plus « la technique est-elle utile ? » mais « qui commande ? ». Heidegger soutient que la technique moderne n''est pas un simple outil neutre : elle impose un regard qui traite tout ce qui existe — la forêt, le fleuve, l''homme — comme un stock disponible. Jacques Ellul décrit un **système technicien** qui se développe selon sa propre logique d''efficacité, sans qu''aucune décision politique ne l''oriente vraiment.\n\n## La responsabilité\nLe pouvoir technique a changé d''échelle : il engage désormais des générations qui ne sont pas nées. D''où l''impératif de Hans Jonas : « agis de telle sorte que les effets de ton action soient compatibles avec la permanence d''une vie authentiquement humaine sur terre ». Ce que nous pouvons faire ne dit toujours pas ce que nous devons faire.', 1),
  ('b82cf841-4bad-53ad-ba5b-2ad563b3e801', '3f486caa-bf4f-5818-aa58-17f56f064407', 'Le beau, l’œuvre et le génie', E'« Art » a d''abord voulu dire savoir-faire — l''*ars* latine traduit la *technè* grecque. L''art au sens des beaux-arts, activité désintéressée qui produit des œuvres, est une idée récente : elle date du XVIIIe siècle.\n\n## Le beau n''est pas l''agréable\nKant distingue trois jugements. L''**agréable** plaît aux sens, et ne se discute pas (chacun ses goûts). Le **bon** plaît par le concept qu''on en a. Le **beau** plaît « universellement sans concept » : le jugement de goût est **désintéressé** — je ne veux pas posséder ni consommer l''objet — et pourtant je prétends que les autres devraient en juger comme moi. C''est le paradoxe du goût : subjectif, mais qui exige un accord.\n\n## L''œuvre et le produit\nL''artisan sait d''avance ce qu''il fabrique, et il peut le refaire à l''identique. L''artiste, dit Kant, travaille par **génie** : « le talent par lequel la nature donne ses règles à l''art » — il produit une œuvre exemplaire dont il ne peut pas expliquer la recette. Walter Benjamin ajoute que la reproduction technique (photo, cinéma, écran) fait perdre à l''œuvre son *hic et nunc*, ce qu''il appelle son **aura**.\n\n## Imiter ou créer\nPlaton condamne l''art comme imitation d''imitation, éloigné deux fois du vrai. Aristote le réhabilite : la **mimèsis** n''est pas une copie, elle donne à comprendre, et la tragédie opère une **catharsis**, une purgation des passions. L''art moderne, lui, rompt souvent avec la ressemblance : ce qu''il vise n''est plus de reproduire le visible, mais de rendre visible.\n\n## À quoi bon\nHegel voit dans l''art une présentation sensible de la vérité, une manière de penser autrement que par concepts. D''autres y voient une contestation, un plaisir, un marché. Une œuvre peut déplaire et compter ; c''est ce qui distingue l''art du divertissement.', 1),
  ('eadab307-3c87-5e3d-be6d-c51a8eb447a3', 'fc07b499-c020-5144-a6e4-f41d140f9b20', 'Croire, savoir, relier', E'Deux étymologies se disputent le mot : *religare*, relier les hommes entre eux et au divin ; *relegere*, recueillir avec scrupule ce qui a été transmis. Les deux disent quelque chose de vrai du phénomène.\n\n## Un fait humain\nUne religion, ce n''est pas seulement une croyance : c''est un ensemble de **rites**, de textes, d''interdits et une **communauté**. Durkheim en propose une définition sociologique : elle repose sur le partage du **sacré** et du **profane**, et la société y célèbre aussi, sans le savoir, sa propre unité.\n\n## Croire n''est pas savoir\nLa foi n''est pas une connaissance imparfaite : elle est d''un autre ordre. Le savant démontre et doit céder devant la preuve contraire ; le croyant adhère et engage sa vie. Les preuves classiques de l''existence de Dieu (l''ordre du monde, la cause première) ont été discutées puis critiquées par Kant : elles dépassent ce que la raison peut établir. Pascal en tire son **pari** — puisque la raison ne tranche pas, il faut miser, et l''enjeu est infini.\n\n## Les soupçons\nFeuerbach y voit une **projection** : l''homme met en Dieu ce qu''il y a de meilleur en lui, et s''appauvrit d''autant. Marx la dit « opium du peuple » — consolation réelle d''une misère réelle, mais qui la fait supporter au lieu de la supprimer. Freud parle d''une **illusion** née du désir infantile de protection. Ces critiques ne prouvent pas que Dieu n''existe pas : elles expliquent pourquoi on y croit.\n\n## Tolérance et laïcité\nSpinoza et Locke posent une distinction devenue politique : le salut relève de la conscience, l''ordre public relève de l''État. La **laïcité** n''est pas l''hostilité aux religions mais la neutralité de l''État, qui garantit à chacun la liberté de croire, de changer de croyance ou de n''en avoir aucune.', 1),
  ('261e2a92-32b0-59a4-968a-0dd99fcf40aa', 'a90225b2-7929-556f-b864-1970231596e3', 'Le passage, la durée, la mort', E'« Qu''est-ce donc que le temps ? Si personne ne me le demande, je le sais ; si je veux l''expliquer à qui me le demande, je ne le sais plus. » L''aveu d''Augustin dit l''essentiel : rien n''est plus familier ni plus obscur.\n\n## Mesurer le temps\nAristote le définit comme « le nombre du mouvement selon l''antérieur et le postérieur » : sans changement, pas de temps mesurable. Newton en fait au contraire un cadre absolu, qui s''écoule uniformément, indépendant de ce qui s''y produit. Kant renverse encore : le temps n''est ni une chose ni une propriété des choses, c''est la **forme de notre sensibilité**, la manière dont un sujet ordonne nécessairement ses expériences.\n\n## Le temps vécu\nAugustin remarque le paradoxe : le passé n''est plus, le futur n''est pas encore, et le présent n''a pas d''épaisseur. Il propose de parler de trois présents : le présent du passé (la mémoire), le présent du présent (l''attention), le présent de l''avenir (l''attente). Bergson oppose le temps **spatialisé** des horloges — des instants juxtaposés, tous équivalents — à la **durée** vécue, continue et hétérogène, où une heure d''ennui et une heure de joie n''ont rien de commun.\n\n## Le temps et la mort\nLe temps humain est celui d''un être qui sait qu''il finira. Épicure veut désamorcer la crainte : « la mort n''est rien pour nous, car quand nous sommes, la mort n''est pas là, et quand elle est là, nous ne sommes plus ». Sénèque déplace la question : « ce n''est pas que nous ayons peu de temps, c''est que nous en perdons beaucoup » — et Horace en tire le *carpe diem*, cueille le jour.\n\n## Ce que le temps rend possible\nL''irréversibilité fait le regret, le remords, le vieillissement. Mais elle fait aussi le projet, la promesse et l''histoire : parce que le temps passe, mes actes engagent quelque chose. Une existence sans temps ne serait pas éternelle : elle serait sans conséquence.', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('838a8894-bd60-528c-8013-1ee41388b86b'::uuid, 'Quiz — Être présent à soi', 'Philosophie', 'Tle', 'La conscience', '5a495098-0f0b-54c2-a72b-98af1b556f14'::uuid),
    ('00381a34-88d3-50c2-bcfc-ede1a29124a7'::uuid, 'Quiz — Ce qui agit en nous à notre insu', 'Philosophie', 'Tle', 'L’inconscient', 'beaa53ba-0979-5b47-bc99-03b70556b658'::uuid),
    ('077ed8ea-a122-51b8-93a4-bc9998da3a29'::uuid, 'Quiz — Ce qui n’est pas l’œuvre de l’homme', 'Philosophie', 'Tle', 'La nature', '0bd1e271-9b33-568e-b2c6-9ec1aa206290'::uuid),
    ('7f48f82b-4e21-505e-bfcc-4fe052969229'::uuid, 'Quiz — Le souverain bien', 'Philosophie', 'Tle', 'Le bonheur', '4cf96624-f485-50df-886b-c186a4a2f0db'::uuid),
    ('52e9d6ae-7ed4-5b09-97a5-dce703827037'::uuid, 'Quiz — Peine, œuvre et valeur', 'Philosophie', 'Tle', 'Le travail', '36575839-2814-5d45-ae36-c615b7fa0781'::uuid),
    ('9b264d60-3308-540a-8f09-c86dea2466c6'::uuid, 'Quiz — Pourquoi obéir à un pouvoir commun', 'Philosophie', 'Tle', 'L’État', 'f23f1250-39b4-577f-9dba-baf7c1ec69cd'::uuid),
    ('72375769-d835-5f8b-b986-12bd150da77f'::uuid, 'Quiz — Le juste, le légal, le légitime', 'Philosophie', 'Tle', 'La justice et le droit', '88e01c95-541e-59cb-862a-b7cc29e5967c'::uuid),
    ('3e576c67-52f7-5497-b6b0-e3e3df64d7ea'::uuid, 'Quiz — Agir par devoir', 'Philosophie', 'Tle', 'Le devoir', '61be3b16-6148-5546-a407-615bd754c745'::uuid),
    ('96ad95b2-569e-5193-b582-d908b02016fd'::uuid, 'Quiz — Le pouvoir de rendre raison', 'Philosophie', 'Tle', 'La raison', '2c4e2f76-f1bd-5fda-bbec-01c6507fd790'::uuid),
    ('48a2768b-269d-5675-9640-336df83f209c'::uuid, 'Quiz — Indépendance, caprice et licence', 'Philosophie', 'Tle', 'La liberté de faire ce qui me plaît', 'ab5a70b2-64e8-54e4-8baf-88e509714119'::uuid),
    ('d11691f8-f5de-5412-a551-c3b2f22dda7a'::uuid, 'Quiz — Sommes-nous les auteurs de nos actes ?', 'Philosophie', 'Tle', 'Le libre arbitre', 'd553cb6e-02b6-564b-aabf-a525ad6d7928'::uuid),
    ('e5224a3c-0b19-5946-88a0-fea6e3615102'::uuid, 'Quiz — Obéir à la loi qu’on s’est prescrite', 'Philosophie', 'Tle', 'La liberté politique', '2a09ce1a-02f2-5b2f-88f8-cb11d6730277'::uuid),
    ('2fe7a0ab-548b-5b30-beb2-bea56837c10f'::uuid, 'Quiz — Parler, penser, agir', 'Philosophie', 'Tle', 'Le langage', '36b90773-556c-5572-a5ca-cf6df7f13e6c'::uuid),
    ('bed6745e-1f74-5093-a286-a2aecfc72199'::uuid, 'Quiz — Ce qui se dit du discours', 'Philosophie', 'Tle', 'La vérité', 'f6af7cb3-adb7-5cc3-8297-377e7a69610b'::uuid),
    ('c550c5e1-b309-519c-b30b-cff57514e651'::uuid, 'Quiz — Expérience, hypothèse, réfutation', 'Philosophie', 'Tle', 'La science', '8213594d-f142-5b3c-9d9a-7801d7e2892c'::uuid),
    ('31b0bf90-8830-577a-b43f-8e3f89264e8f'::uuid, 'Quiz — Prolonger le corps, transformer le monde', 'Philosophie', 'Tle', 'La technique', 'db024c6b-c9c6-52a7-a099-4912a6eccc78'::uuid),
    ('f6e6e8e5-696c-5e44-a41d-370eee81bd9f'::uuid, 'Quiz — Le beau, l’œuvre et le génie', 'Philosophie', 'Tle', 'L’art', 'b82cf841-4bad-53ad-ba5b-2ad563b3e801'::uuid),
    ('13cc6121-eeeb-5560-a9c3-5f24f2a16eba'::uuid, 'Quiz — Croire, savoir, relier', 'Philosophie', 'Tle', 'La religion', 'eadab307-3c87-5e3d-be6d-c51a8eb447a3'::uuid),
    ('8d2abe30-aeac-5f85-a003-88a7ebe10e58'::uuid, 'Quiz — Le passage, la durée, la mort', 'Philosophie', 'Tle', 'Le temps', '261e2a92-32b0-59a4-968a-0dd99fcf40aa'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('d77d2e3d-26ff-53b4-9b02-fc5fe29b0903'::uuid, '838a8894-bd60-528c-8013-1ee41388b86b'::uuid, 'Que dit l’étymologie latine du mot « conscience » (*cum scientia*) ?', 'mcq', '["Accompagné de savoir","Sans savoir","Au-dessus du savoir","Contre le savoir"]'::jsonb, 0, 'Être conscient, c’est savoir que l’on sait.', 1),
    ('5a69f645-8360-5085-aa61-edded5ec317b'::uuid, '838a8894-bd60-528c-8013-1ee41388b86b'::uuid, '« Je pense, donc je suis » est une formule de…', 'mcq', '["Descartes","Kant","Freud","Sartre"]'::jsonb, 0, 'Le cogito du *Discours de la méthode* (1637), seule certitude qui résiste au doute.', 2),
    ('427cf442-62f8-5395-ba9e-c5bc20b70fbc'::uuid, '838a8894-bd60-528c-8013-1ee41388b86b'::uuid, 'La conscience réfléchie désigne…', 'mcq', '["Le retour de la pensée sur elle-même","La perception spontanée du monde","Le jugement porté sur autrui","Le sommeil sans rêve"]'::jsonb, 0, 'Je ne me contente pas de voir : je sais que je vois.', 3),
    ('08b46727-340f-56f0-b73c-764ceea00a51'::uuid, '838a8894-bd60-528c-8013-1ee41388b86b'::uuid, 'La conscience morale porte sur ce qui est, et non sur ce qui vaut.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est l’inverse : elle juge la valeur de nos actes.', 4),
    ('9d522050-bb6f-505c-a777-a189586a5d38'::uuid, '838a8894-bd60-528c-8013-1ee41388b86b'::uuid, 'Le doute cartésien vise à détruire définitivement toute certitude.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est un doute méthodique : il cherche un point fixe, pas le scepticisme.', 5),
    ('9716a9ae-3d8e-5ab4-b93e-a9546a7d1db9'::uuid, '838a8894-bd60-528c-8013-1ee41388b86b'::uuid, 'Pour Sartre, la conscience est…', 'mcq', '["Un rapport au monde, non une chose","Une substance matérielle","Un organe du cerveau","Une illusion sans effet"]'::jsonb, 0, 'Elle n’est rien d’autre que le mouvement par lequel elle vise le monde.', 6),
    ('69ad10e5-3b36-5c3c-998e-3fdf323106c7'::uuid, '838a8894-bd60-528c-8013-1ee41388b86b'::uuid, 'Selon Kant, le « je pense » me donne à connaître ce que je suis en moi-même.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Je me saisis comme phénomène, pas comme chose en soi.', 7),
    ('63ff3c83-2333-5cce-b855-0ec05bd4b5c9'::uuid, '838a8894-bd60-528c-8013-1ee41388b86b'::uuid, 'Chez Pascal, la pensée fait de l’homme…', 'mcq', '["Un roseau pensant : faible, mais digne","Un animal comme les autres","Un être tout-puissant","Un pur esprit sans corps"]'::jsonb, 0, '« Toute notre dignité consiste en la pensée. »', 8),
    ('ceefec42-5294-5e14-b730-c61367a9570e'::uuid, '00381a34-88d3-50c2-bcfc-ede1a29124a7'::uuid, 'L’inconscient psychique freudien désigne…', 'mcq', '["Des représentations refoulées qui agissent à notre insu","Les fonctions du corps comme la digestion","Un simple manque d’attention","La perte de mémoire liée à l’âge"]'::jsonb, 0, 'Ce sont des pensées porteuses de sens, pas des mécanismes biologiques.', 1),
    ('5d4f685f-7a0d-5b57-8876-cd0d0f14773a'::uuid, '00381a34-88d3-50c2-bcfc-ede1a29124a7'::uuid, 'Pour Freud, le rêve est…', 'mcq', '["L’expression déguisée d’un désir refoulé","Un phénomène sans signification","Un message venu de l’extérieur","La preuve du libre arbitre"]'::jsonb, 0, 'Le rêve est « la voie royale » vers l’inconscient.', 2),
    ('36e1a9bc-e508-50ed-a2e3-6bae32193176'::uuid, '00381a34-88d3-50c2-bcfc-ede1a29124a7'::uuid, 'Un acte manqué est, du point de vue du désir, un acte réussi.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Il réalise une intention que le sujet ne s’avoue pas.', 3),
    ('9c980129-f464-5e45-a680-d6097b78683f'::uuid, '00381a34-88d3-50c2-bcfc-ede1a29124a7'::uuid, 'Dans la seconde topique, l’instance des interdits intériorisés s’appelle…', 'mcq', '["Le Surmoi","Le Ça","Le Moi","Le préconscient"]'::jsonb, 0, 'Il hérite des exigences parentales puis sociales.', 4),
    ('1ec292c0-d762-54ca-85b7-da4587cda69b'::uuid, '00381a34-88d3-50c2-bcfc-ede1a29124a7'::uuid, 'Le Ça est le siège…', 'mcq', '["Des pulsions","De la raison","De la morale","De la perception"]'::jsonb, 0, 'Il ignore la contradiction et le temps, et ne suit que le principe de plaisir.', 5),
    ('3d784c75-afa6-58a0-94ee-b81ce4590632'::uuid, '00381a34-88d3-50c2-bcfc-ede1a29124a7'::uuid, 'Sartre reprend à son compte l’hypothèse de l’inconscient.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il lui oppose la mauvaise foi, dont le sujet reste responsable.', 6),
    ('ef2ea855-0925-54e0-9bd5-ffa6492e0299'::uuid, '00381a34-88d3-50c2-bcfc-ede1a29124a7'::uuid, 'Le déterminisme psychique affirme que…', 'mcq', '["Aucun fait psychique n’est le fruit du hasard","Tout est décidé par la biologie","Rien ne peut être expliqué","La conscience contrôle tout"]'::jsonb, 0, 'Lapsus, oublis et rêves ont une cause psychique.', 7),
    ('c30cf98b-4de4-58d5-bc66-0bded61ee7e5'::uuid, '00381a34-88d3-50c2-bcfc-ede1a29124a7'::uuid, 'Reconnaître un inconscient supprime toute responsabilité du sujet.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est l’objection classique ; la cure vise au contraire à rendre le sujet responsable de son désir.', 8),
    ('15c28cf5-e3c2-5983-bb09-56a53bffd95e'::uuid, '077ed8ea-a122-51b8-93a4-bc9998da3a29'::uuid, 'À quoi les Grecs opposent-ils la *phusis* (la nature) ?', 'mcq', '["À la *technè*, ce qui est produit par l’art humain","Au *logos*","À la *polis*","À la *doxa*"]'::jsonb, 0, 'Ce qui pousse de soi-même s’oppose à ce qui est fabriqué.', 1),
    ('e6e59c4f-d618-5ca4-8268-64b1c70e59d0'::uuid, '077ed8ea-a122-51b8-93a4-bc9998da3a29'::uuid, 'Pour Aristote, la nature agit au hasard, sans finalité.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, '« La nature ne fait rien en vain » : chaque être tend vers sa fin.', 2),
    ('27525b84-07c1-58a4-9f6a-e57b61926fb9'::uuid, '077ed8ea-a122-51b8-93a4-bc9998da3a29'::uuid, 'Selon Lévi-Strauss, la prohibition de l’inceste est remarquable parce qu’elle est…', 'mcq', '["Universelle comme la nature et normative comme la culture","Propre à l’Occident","Purement biologique","Récente dans l’histoire"]'::jsonb, 0, 'Elle marque le passage de la nature à la culture.', 3),
    ('a33b3ad5-3ae2-55e5-b6b6-15f3214506ca'::uuid, '077ed8ea-a122-51b8-93a4-bc9998da3a29'::uuid, 'Chez Hobbes, l’état de nature est…', 'mcq', '["La guerre de tous contre tous","Un âge d’or pacifique","Une société avec des lois","Une invention des philosophes grecs"]'::jsonb, 0, 'D’où la nécessité d’un pouvoir commun qui fasse peur à tous.', 4),
    ('666469a5-5fad-5566-991e-44daa44c9286'::uuid, '077ed8ea-a122-51b8-93a4-bc9998da3a29'::uuid, 'Pour Rousseau, l’homme de l’état de nature est mû par l’amour de soi et la pitié.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Ce sont les rapports sociaux, non la nature, qui le rendent méchant.', 5),
    ('ad9edc45-94f4-5ab8-a8c3-53dcc9369bfb'::uuid, '077ed8ea-a122-51b8-93a4-bc9998da3a29'::uuid, 'L’état de nature désigne une époque historique attestée par l’archéologie.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est une hypothèse méthodique, un outil pour penser la société.', 6),
    ('bc218065-8d64-5405-a5dc-4d6f38d8da81'::uuid, '077ed8ea-a122-51b8-93a4-bc9998da3a29'::uuid, '« Comme maîtres et possesseurs de la nature » est une formule de…', 'mcq', '["Descartes","Rousseau","Aristote","Jonas"]'::jsonb, 0, 'Elle exprime le projet de la science moderne dans le *Discours de la méthode*.', 7),
    ('89de82a5-3675-5c8e-a72b-1996a94dae77'::uuid, '077ed8ea-a122-51b8-93a4-bc9998da3a29'::uuid, 'Quand Sartre écrit que « l’existence précède l’essence », il affirme…', 'mcq', '["Qu’il n’y a pas de nature humaine donnée d’avance","Que l’homme est déterminé par ses gènes","Que Dieu a créé l’homme","Que la culture n’existe pas"]'::jsonb, 0, 'L’homme est d’abord, et se définit ensuite par ses actes.', 8),
    ('05c8b491-6ac4-59cf-af3b-c505eddd8cff'::uuid, '7f48f82b-4e21-505e-bfcc-4fe052969229'::uuid, 'Le « souverain bien » désigne…', 'mcq', '["La fin recherchée pour elle-même","Le plaisir immédiat","La richesse","Le pouvoir politique"]'::jsonb, 0, 'Tout le reste est recherché en vue de lui.', 1),
    ('aa1406f4-1a2f-53fd-9bd6-0dd23cb4ebe2'::uuid, '7f48f82b-4e21-505e-bfcc-4fe052969229'::uuid, 'Pour Kant, le bonheur est un idéal de la raison, parfaitement définissable.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est « un idéal de l’imagination » : chacun le veut sans pouvoir en fixer le contenu.', 2),
    ('6701d4a3-b63c-5b63-88a4-09b60be6a6a9'::uuid, '7f48f82b-4e21-505e-bfcc-4fe052969229'::uuid, 'Chez Épicure, boire quand on a soif relève des désirs…', 'mcq', '["Naturels et nécessaires","Naturels mais non nécessaires","Ni naturels ni nécessaires","Interdits"]'::jsonb, 0, 'Seuls ceux-là doivent être satisfaits sans réserve.', 3),
    ('b074ef90-e8ba-54c9-887f-e9107e80496d'::uuid, '7f48f82b-4e21-505e-bfcc-4fe052969229'::uuid, 'L’*ataraxie* désigne…', 'mcq', '["L’absence de trouble de l’âme","L’accumulation de plaisirs","La colère maîtrisée","Le devoir accompli"]'::jsonb, 0, 'C’est le but de la sagesse épicurienne comme stoïcienne.', 4),
    ('6fc08465-f522-5023-956a-4f38411ccedd'::uuid, '7f48f82b-4e21-505e-bfcc-4fe052969229'::uuid, 'Les stoïciens conseillent de changer l’ordre du monde plutôt que ses propres désirs.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Épictète invite à l’inverse : distinguer ce qui dépend de nous de ce qui n’en dépend pas.', 5),
    ('76218903-4b22-5119-9a02-9859147cedce'::uuid, '7f48f82b-4e21-505e-bfcc-4fe052969229'::uuid, 'Pour Aristote, le bonheur consiste…', 'mcq', '["Dans l’activité de l’âme conforme à la vertu","Dans l’absence de toute activité","Dans la possession de richesses","Dans la suppression de tout désir"]'::jsonb, 0, 'Le bonheur est une manière de vivre, pas un état passif.', 6),
    ('1f4b6cda-9f1a-5f7d-b780-e86f8be4d102'::uuid, '7f48f82b-4e21-505e-bfcc-4fe052969229'::uuid, 'Selon Pascal, le divertissement nous détourne de notre condition.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, '« Tout le malheur des hommes vient d’une seule chose, qui est de ne savoir pas demeurer en repos. »', 7),
    ('c73987ce-8e83-58ed-aa41-fb8117422f54'::uuid, '7f48f82b-4e21-505e-bfcc-4fe052969229'::uuid, 'Pour Kant, la morale nous enseigne…', 'mcq', '["À nous rendre dignes d’être heureux","Le chemin le plus court vers le bonheur","À rechercher le plaisir","À fuir toute obligation"]'::jsonb, 0, 'Le bonheur n’est pas le principe du devoir, mais son espérance.', 8),
    ('68f20e0c-b305-5873-b7c6-491159e5893e'::uuid, '52e9d6ae-7ed4-5b09-97a5-dce703827037'::uuid, 'Le mot « travail » vient du latin *tripalium*, qui désignait…', 'mcq', '["Un instrument de torture","Une charrue","Un salaire","Un atelier"]'::jsonb, 0, 'L’étymologie garde la trace de la peine.', 1),
    ('5a90ac58-8eec-5f4c-815f-7a944f9a0bdc'::uuid, '52e9d6ae-7ed4-5b09-97a5-dce703827037'::uuid, 'Dans la dialectique hégélienne du maître et de l’esclave, qui se transforme en transformant la chose ?', 'mcq', '["L’esclave, par le travail","Le maître, par la jouissance","Aucun des deux","Le spectateur"]'::jsonb, 0, 'Le maître consomme, l’esclave forme le monde et se forme.', 2),
    ('265382f5-9915-523f-878a-984631fe985f'::uuid, '52e9d6ae-7ed4-5b09-97a5-dce703827037'::uuid, 'Pour Marx, ce qui distingue l’architecte de l’abeille, c’est…', 'mcq', '["Qu’il conçoit son ouvrage avant de le réaliser","Qu’il travaille plus vite","Qu’il travaille en groupe","Qu’il obéit à son instinct"]'::jsonb, 0, 'Le travail humain est d’abord une représentation.', 3),
    ('7cffe3ba-9135-5434-b556-cd422c3ca588'::uuid, '52e9d6ae-7ed4-5b09-97a5-dce703827037'::uuid, 'Chez les Grecs, le travail manuel était valorisé comme l’activité la plus noble.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il était réservé aux esclaves ; la liberté supposait le loisir (*skholè*).', 4),
    ('c2ffb8af-6bbc-5ea6-a2a6-bac40cafaee2'::uuid, '52e9d6ae-7ed4-5b09-97a5-dce703827037'::uuid, 'L’aliénation, au sens de Marx, désigne…', 'mcq', '["Le fait que le travailleur ne se reconnaisse plus dans son produit","Une maladie mentale","Le chômage","La retraite"]'::jsonb, 0, 'Le produit du travail lui devient étranger et hostile.', 5),
    ('6895aaa0-157c-5d52-88dd-2fd9b4ead0ff'::uuid, '52e9d6ae-7ed4-5b09-97a5-dce703827037'::uuid, 'La division du travail augmente la productivité sans aucun coût humain.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Smith en décrit les gains, Marx la parcellisation qui abrutit.', 6),
    ('771860ce-49c1-5cbe-a888-112e7660d69e'::uuid, '52e9d6ae-7ed4-5b09-97a5-dce703827037'::uuid, 'Hannah Arendt distingue le travail, l’œuvre et…', 'mcq', '["L’action","Le loisir","Le salaire","La technique"]'::jsonb, 0, 'L’action, c’est la parole et l’initiative dans l’espace public.', 7),
    ('f2f0e934-8e78-52e9-b6ea-fd91d17e8f4d'::uuid, '52e9d6ae-7ed4-5b09-97a5-dce703827037'::uuid, 'Le travail peut être à la fois source d’aliénation et d’émancipation.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est toute la tension de la notion : il fait l’homme et peut le défaire.', 8),
    ('23d3c268-2cf1-5868-8d2c-6d72a2695e40'::uuid, '9b264d60-3308-540a-8f09-c86dea2466c6'::uuid, 'Pour Hobbes, l’État naît…', 'mcq', '["D’un contrat par lequel chacun renonce à son droit sur tout","De la nature humaine sociable","De la volonté divine","De la conquête militaire uniquement"]'::jsonb, 0, 'C’est un artifice destiné à sortir de la guerre de tous contre tous.', 1),
    ('9349f77d-6f6d-554b-89ee-abfbb69c46d6'::uuid, '9b264d60-3308-540a-8f09-c86dea2466c6'::uuid, 'Max Weber définit l’État par…', 'mcq', '["Le monopole de la violence physique légitime","La taille de son territoire","La richesse de sa population","L’ancienneté de ses lois"]'::jsonb, 0, 'Seul l’État peut contraindre légalement, et cette contrainte est reconnue.', 2),
    ('0206b4ba-3c99-53e5-a04d-9febc08ffd73'::uuid, '9b264d60-3308-540a-8f09-c86dea2466c6'::uuid, 'Chez Locke, l’État a pour fin de garantir des droits naturels.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Vie, liberté, propriété : s’il les viole, il perd sa légitimité.', 3),
    ('1b077f89-27a2-5bb2-937e-d36240b1dbe9'::uuid, '9b264d60-3308-540a-8f09-c86dea2466c6'::uuid, 'Pour Rousseau, la loi doit exprimer…', 'mcq', '["La volonté générale","La volonté du prince","La somme des intérêts particuliers","La coutume ancienne"]'::jsonb, 0, 'Obéir à la loi qu’on s’est prescrite, c’est rester libre.', 4),
    ('35c4a173-3991-593a-8f7d-14a76e94bbfb'::uuid, '9b264d60-3308-540a-8f09-c86dea2466c6'::uuid, 'L’État et la société sont deux termes équivalents.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'La société est l’ensemble des relations humaines ; l’État en est l’institution politique.', 5),
    ('fe062478-e39d-5e49-ab31-7d108353c859'::uuid, '9b264d60-3308-540a-8f09-c86dea2466c6'::uuid, 'Pour Marx, l’État est un arbitre neutre entre les classes sociales.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il y voit l’instrument de domination de la classe dominante.', 6),
    ('eb415cf8-ac64-5af8-9c9f-b8766fadc392'::uuid, '9b264d60-3308-540a-8f09-c86dea2466c6'::uuid, 'La Boétie s’étonne surtout…', 'mcq', '["Que les hommes obéissent sans y être contraints","Que les tyrans soient nombreux","Que la guerre existe","Que les lois changent"]'::jsonb, 0, 'C’est le paradoxe de la servitude volontaire.', 7),
    ('c17cece6-e029-5174-8699-e0cb747aec1b'::uuid, '9b264d60-3308-540a-8f09-c86dea2466c6'::uuid, 'Le Léviathan désigne, chez Hobbes…', 'mcq', '["Le souverain, corps artificiel formé de tous","Un monstre marin réel","Le peuple révolté","La loi naturelle"]'::jsonb, 0, 'La figure biblique sert d’image à la puissance publique.', 8),
    ('e4084018-c9bb-5dfb-a853-959aa5eda56f'::uuid, '72375769-d835-5f8b-b986-12bd150da77f'::uuid, 'Le droit positif désigne…', 'mcq', '["Les règles effectivement en vigueur dans une société","Les principes universels de la morale","Les droits que l’on mérite","Les lois favorables aux citoyens"]'::jsonb, 0, 'Il s’oppose au droit naturel, qui sert à le juger.', 1),
    ('ea3c133d-07ce-5a29-8db9-e06e0a078357'::uuid, '72375769-d835-5f8b-b986-12bd150da77f'::uuid, 'Dans *Antigone*, l’héroïne oppose à l’édit de Créon…', 'mcq', '["Les lois non écrites","Un autre décret royal","La coutume militaire","Le droit de propriété"]'::jsonb, 0, 'La pièce met en scène le conflit du légal et du légitime.', 2),
    ('3b49034f-ac0c-5fca-92af-ecb32b7cc601'::uuid, '72375769-d835-5f8b-b986-12bd150da77f'::uuid, 'La justice distributive d’Aristote repose sur une égalité…', 'mcq', '["Proportionnelle au mérite","Strictement arithmétique","Décidée par le sort","Fondée sur la naissance"]'::jsonb, 0, 'À chacun selon sa contribution : ce n’est pas donner la même chose à tous.', 3),
    ('d0f53640-966a-5b7e-b8fe-7f0516949261'::uuid, '72375769-d835-5f8b-b986-12bd150da77f'::uuid, 'La justice corrective tient compte du mérite des personnes.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle répare un tort en ignorant qui l’a commis ou subi.', 4),
    ('a47c17a7-f880-52d4-a5e4-9b964b876148'::uuid, '72375769-d835-5f8b-b986-12bd150da77f'::uuid, 'Une loi peut être légale sans être légitime.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Les lois raciales ou esclavagistes en sont l’exemple historique.', 5),
    ('e1418842-414b-563d-93ef-97b1d574f70b'::uuid, '72375769-d835-5f8b-b986-12bd150da77f'::uuid, 'Le « voile d’ignorance » de Rawls consiste à choisir les règles…', 'mcq', '["Sans savoir quelle place on occupera dans la société","En ignorant les lois existantes","Sans consulter les citoyens","Au hasard"]'::jsonb, 0, 'L’impartialité vient de l’ignorance de son propre intérêt.', 6),
    ('f0b0ed30-16d9-5ed9-ac6e-a2266d26513c'::uuid, '72375769-d835-5f8b-b986-12bd150da77f'::uuid, 'Selon Beccaria, c’est la sévérité de la peine, plus que sa certitude, qui dissuade.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il soutient l’inverse : la certitude d’être puni compte davantage.', 7),
    ('67016a51-59bb-529f-adfa-e669eb362f9b'::uuid, '72375769-d835-5f8b-b986-12bd150da77f'::uuid, 'Punir par rétribution, c’est punir…', 'mcq', '["Parce que la faute a été commise","Pour l’exemple","Pour protéger la société","Pour rééduquer le condamné"]'::jsonb, 0, 'La peine y est due au crime, non calculée sur ses effets.', 8),
    ('ffc3c605-ece1-5cc3-8e1d-1a44c34d04d6'::uuid, '3e576c67-52f7-5497-b6b0-e3e3df64d7ea'::uuid, 'Chez Kant, agir « conformément au devoir » sans agir « par devoir », c’est…', 'mcq', '["Faire ce qu’il faut, mais par intérêt","Désobéir à la loi","Agir sans réfléchir","Agir par pitié"]'::jsonb, 0, 'L’acte est correct, mais sa valeur morale est nulle.', 1),
    ('1eb943ce-7931-556c-b21f-f3d69fdeaf65'::uuid, '3e576c67-52f7-5497-b6b0-e3e3df64d7ea'::uuid, 'Un impératif catégorique commande…', 'mcq', '["Sans condition","Si l’on veut être heureux","Si la loi l’exige","Si autrui l’approuve"]'::jsonb, 0, 'L’impératif hypothétique, lui, est un simple moyen en vue d’une fin.', 2),
    ('966f75c4-070f-5bb4-987d-8ffb571dc7d1'::uuid, '3e576c67-52f7-5497-b6b0-e3e3df64d7ea'::uuid, 'Kant demande de traiter l’humanité toujours en même temps comme une fin, jamais simplement comme un moyen.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est la deuxième formulation de l’impératif catégorique.', 3),
    ('c054d3cd-ce67-5dd3-a274-bede13cce6a1'::uuid, '3e576c67-52f7-5497-b6b0-e3e3df64d7ea'::uuid, 'Le critère d’universalisation kantien demande de se demander…', 'mcq', '["Ce qui se passerait si tout le monde agissait ainsi","Ce qui me rendrait heureux","Ce que la loi autorise","Ce que ferait la majorité"]'::jsonb, 0, 'Une maxime qui se détruit en devenant universelle est immorale.', 4),
    ('def7e331-e814-5563-8a91-ff74de6eea41'::uuid, '3e576c67-52f7-5497-b6b0-e3e3df64d7ea'::uuid, 'L’utilitarisme juge une action…', 'mcq', '["À ses conséquences sur le bonheur du plus grand nombre","À l’intention qui l’anime","À sa conformité à la coutume","À la sincérité de son auteur"]'::jsonb, 0, 'Bentham et Mill s’opposent en cela au formalisme kantien.', 5),
    ('db914ce5-e809-588d-8404-719808b175e4'::uuid, '3e576c67-52f7-5497-b6b0-e3e3df64d7ea'::uuid, 'Benjamin Constant objecte à Kant le cas du mensonge fait à un assassin.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'L’interdit absolu du mensonge se heurte là à une conséquence intolérable.', 6),
    ('5fd14ce5-054b-550b-89e3-c9b2a8b4874e'::uuid, '3e576c67-52f7-5497-b6b0-e3e3df64d7ea'::uuid, 'Pour Nietzsche, la morale du devoir…', 'mcq', '["Est suspecte : elle traduirait le ressentiment des faibles","Est le sommet de la civilisation","Vient directement de la nature","Est un fait scientifique"]'::jsonb, 0, 'Il en fait la généalogie plutôt que d’en accepter l’évidence.', 7),
    ('4fafd874-4c0a-5f77-9bd0-45b6ae59c3bd'::uuid, '3e576c67-52f7-5497-b6b0-e3e3df64d7ea'::uuid, 'L’éthique de responsabilité, chez Weber, juge l’acte sur son seul principe.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle le juge sur ses effets prévisibles ; c’est l’éthique de conviction qui s’en tient au principe.', 8),
    ('42d54a08-1caf-5d7b-8b99-5c62abb82944'::uuid, '96ad95b2-569e-5193-b582-d908b02016fd'::uuid, 'Le principe de raison suffisante, formulé par Leibniz, affirme que…', 'mcq', '["Rien n’arrive sans raison","Tout est le fruit du hasard","La raison est infaillible","Seule l’expérience compte"]'::jsonb, 0, 'Il interdit de se contenter du merveilleux ou de l’inexpliqué.', 1),
    ('29501907-e553-5a82-9926-4500bc7e029a'::uuid, '96ad95b2-569e-5193-b582-d908b02016fd'::uuid, 'Pour Hume, l’idée de causalité nécessaire vient…', 'mcq', '["De l’habitude née de l’expérience répétée","D’une intuition innée","D’une démonstration mathématique","De la révélation"]'::jsonb, 0, 'Nous voyons la succession, jamais le lien nécessaire.', 2),
    ('d5c1a08e-f13d-558d-984d-42d89beda9d8'::uuid, '96ad95b2-569e-5193-b582-d908b02016fd'::uuid, 'Descartes affirme que le bon sens est la chose du monde la mieux partagée.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'La raison est entière en chacun ; c’est la méthode qui manque.', 3),
    ('c98d8765-d220-5433-b2b3-939c5e5da0c4'::uuid, '96ad95b2-569e-5193-b582-d908b02016fd'::uuid, 'Selon Kant, « des intuitions sans concepts sont… »', 'mcq', '["Aveugles","Vides","Fausses","Inutiles"]'::jsonb, 0, 'Et « des pensées sans contenu sont vides » : connaissance = sensibilité + entendement.', 4),
    ('94b0bb88-2b8b-5e3c-a4c5-a0f5a0ec663e'::uuid, '96ad95b2-569e-5193-b582-d908b02016fd'::uuid, 'La raison peut connaître sans risque d’erreur ce qui dépasse toute expérience possible.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Kant montre qu’elle y produit des thèses contradictoires également démontrables.', 5),
    ('68ddd11a-c9eb-519d-802d-c8ee8b72ff37'::uuid, '96ad95b2-569e-5193-b582-d908b02016fd'::uuid, '« Sapere aude » — la devise des Lumières selon Kant — signifie…', 'mcq', '["Aie le courage de te servir de ton propre entendement","Crois ce que l’on t’enseigne","Doute de tout","Obéis à la loi"]'::jsonb, 0, 'Les Lumières sont la sortie de la minorité dont l’homme est responsable.', 6),
    ('e58f9bf8-68b4-5ae7-bea1-5f9acb58f232'::uuid, '96ad95b2-569e-5193-b582-d908b02016fd'::uuid, 'Pascal écrit que « le cœur a ses raisons que la raison ne connaît point » pour…', 'mcq', '["Marquer un autre ordre que celui de la démonstration","Rejeter toute pensée rationnelle","Défendre la superstition","Prouver l’existence de Dieu par la logique"]'::jsonb, 0, 'Il distingue les ordres, il ne congédie pas la raison.', 7),
    ('737d7f15-70df-5b5e-86ee-3b9b5e6a3a52'::uuid, '96ad95b2-569e-5193-b582-d908b02016fd'::uuid, 'Une rationalité purement instrumentale calcule les moyens sans interroger les fins.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est la critique adressée à la raison technicienne au XXe siècle.', 8),
    ('c98ae7fd-82c5-5914-b112-2abbdefec7b6'::uuid, '48a2768b-269d-5675-9640-336df83f209c'::uuid, 'Définir la liberté comme simple absence d’obstacle, c’est en rester…', 'mcq', '["À l’indépendance","À l’autonomie","Au libre arbitre","À la liberté politique"]'::jsonb, 0, 'C’est le premier sens, celui du mouvement sans entrave.', 1),
    ('7ea37924-cb9a-5c9d-847a-cd8a20839032'::uuid, '48a2768b-269d-5675-9640-336df83f209c'::uuid, 'Selon Spinoza, les hommes se croient libres parce qu’ils…', 'mcq', '["Ignorent les causes qui les déterminent","Connaissent parfaitement leurs raisons","Obéissent à la loi","Sont capables de résister à leurs désirs"]'::jsonb, 0, 'Ils ont conscience de leurs actions, non de leurs causes.', 2),
    ('ce5a6eec-29b1-56a5-bb93-2d561d31f7f3'::uuid, '48a2768b-269d-5675-9640-336df83f209c'::uuid, 'L’exemple spinoziste de l’ivrogne montre que la conscience de vouloir suffit à prouver la liberté.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il montre exactement le contraire : on peut se croire libre en étant déterminé.', 3),
    ('378ed783-702a-523e-9b86-bfdb4735bca2'::uuid, '48a2768b-269d-5675-9640-336df83f209c'::uuid, 'Selon l’article 4 de la Déclaration de 1789, la liberté consiste à pouvoir faire…', 'mcq', '["Tout ce qui ne nuit pas à autrui","Tout ce que l’on désire","Ce que la majorité décide","Ce que la nature commande"]'::jsonb, 0, 'La limite n’est pas une atteinte à la liberté : elle la rend possible pour tous.', 4),
    ('ef8c36f6-91f2-5998-ab20-a4dfd3ca059d'::uuid, '48a2768b-269d-5675-9640-336df83f209c'::uuid, 'La licence désigne…', 'mcq', '["Une liberté sans limite, qui se détruit elle-même","Une autorisation administrative","La liberté d’expression","L’obéissance à la loi"]'::jsonb, 0, 'Sans règle, la liberté de chacun devient la proie du plus fort.', 5),
    ('66ff4a93-ceed-54d9-be61-3bf8dba1e816'::uuid, '48a2768b-269d-5675-9640-336df83f209c'::uuid, 'Pour Rousseau, « l’impulsion du seul appétit est esclavage ».', 'true_false', '["Vrai","Faux"]'::jsonb, 0, '« …et l’obéissance à la loi qu’on s’est prescrite est liberté. »', 6),
    ('37560b26-b397-55ea-ab9f-dbc16e14cc05'::uuid, '48a2768b-269d-5675-9640-336df83f209c'::uuid, 'Le renversement opéré par la tradition philosophique consiste à dire qu’être libre, c’est…', 'mcq', '["Devenir maître de ses désirs","Satisfaire tous ses désirs","Supprimer toute règle","Ignorer autrui"]'::jsonb, 0, 'La liberté devient une conquête, non un point de départ.', 7),
    ('3c231803-f612-5a57-90fa-91106eb01593'::uuid, '48a2768b-269d-5675-9640-336df83f209c'::uuid, 'Mes désirs sont toujours entièrement les miens, sans influence extérieure.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Habitude, éducation, mode et publicité en façonnent une bonne part.', 8),
    ('cf3dd932-05d4-5ca8-bb4f-b12fb9636086'::uuid, 'd11691f8-f5de-5412-a551-c3b2f22dda7a'::uuid, 'Le libre arbitre est le pouvoir…', 'mcq', '["De choisir entre plusieurs possibles","De faire ce qui plaît","De vivre sans lois","De prévoir l’avenir"]'::jsonb, 0, 'Sans lui, il n’y a ni mérite ni responsabilité.', 1),
    ('7d2b8152-8b56-5f56-820a-d54304ed90b5'::uuid, 'd11691f8-f5de-5412-a551-c3b2f22dda7a'::uuid, 'Pour Descartes, la liberté d’indifférence — choisir sans raison — est…', 'mcq', '["Le plus bas degré de la liberté","La liberté la plus haute","Une impossibilité logique","Le fondement de la morale"]'::jsonb, 0, 'Choisir vraiment librement, c’est choisir éclairé.', 2),
    ('b6465f0f-66c6-5115-be84-9a528d206539'::uuid, 'd11691f8-f5de-5412-a551-c3b2f22dda7a'::uuid, 'Le déterminisme affirme que tout événement a une cause.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Y compris nos décisions, qui ne tombent pas du ciel.', 3),
    ('d17adb04-2c20-5fbe-99f5-d10534f4bb3a'::uuid, 'd11691f8-f5de-5412-a551-c3b2f22dda7a'::uuid, 'Fatalisme et déterminisme sont deux noms pour la même thèse.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Le fataliste dit que nos actes ne changent rien ; le déterministe dit qu’ils ont des causes, et produisent des effets.', 4),
    ('b3640c73-ad32-56ac-8c5c-c3e1ccab3e40'::uuid, 'd11691f8-f5de-5412-a551-c3b2f22dda7a'::uuid, 'L’intelligence imaginée par Laplace…', 'mcq', '["Connaîtrait tout l’avenir à partir de l’état présent du monde","Serait incapable de calculer","Créerait le monde","Déciderait de nos actes"]'::jsonb, 0, 'C’est la figure limite du déterminisme scientifique.', 5),
    ('aaa70576-f1cd-5464-8c37-3eccd9e2e074'::uuid, 'd11691f8-f5de-5412-a551-c3b2f22dda7a'::uuid, 'Pour Kant, la liberté est…', 'mcq', '["Un postulat que la loi morale exige","Un fait observable","Une illusion à écarter","Un privilège des savants"]'::jsonb, 0, 'Le « tu dois » n’aurait aucun sens sans le « tu peux ».', 6),
    ('ce1a0a2e-d17d-5492-9ad5-8cbf91338e75'::uuid, 'd11691f8-f5de-5412-a551-c3b2f22dda7a'::uuid, 'Selon Sartre, l’homme est « condamné à être libre ».', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Il n’a pas choisi d’exister, mais ne peut pas ne pas choisir.', 7),
    ('ebe85de9-8530-525b-b5a2-3035aa465801'::uuid, 'd11691f8-f5de-5412-a551-c3b2f22dda7a'::uuid, 'Invoquer ses déterminations pour s’excuser, c’est, selon Sartre…', 'mcq', '["Encore un choix, celui de la mauvaise foi","Une preuve scientifique","Un acte de courage","Une impossibilité"]'::jsonb, 0, 'La fuite devant la liberté est elle-même une conduite libre.', 8),
    ('77176d58-27f3-50bb-b528-6b8e2dafd76a'::uuid, 'e5224a3c-0b19-5946-88a0-fea6e3615102'::uuid, 'Pour Rousseau, l’obéissance à la loi est compatible avec la liberté quand la loi…', 'mcq', '["Exprime la volonté générale","Vient d’un roi éclairé","Est ancienne","Est peu contraignante"]'::jsonb, 0, 'Le citoyen obéit alors à ce qu’il a lui-même voulu.', 1),
    ('f6f4b998-2ba3-5241-9a9f-c93687b2e9db'::uuid, 'e5224a3c-0b19-5946-88a0-fea6e3615102'::uuid, 'La liberté des Anciens, selon Benjamin Constant, consiste à…', 'mcq', '["Participer directement aux décisions collectives","Jouir de son indépendance privée","Voyager librement","Choisir sa religion"]'::jsonb, 0, 'Celle des Modernes est au contraire l’indépendance individuelle garantie.', 2),
    ('e71c4528-d79d-50f7-94f2-445d3e5f0b7e'::uuid, 'e5224a3c-0b19-5946-88a0-fea6e3615102'::uuid, 'Montesquieu écrit qu’il faut que « le pouvoir arrête le pouvoir ».', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est le principe de la séparation des pouvoirs.', 3),
    ('d4d402e7-7b45-5e07-8e0c-1a439898c991'::uuid, 'e5224a3c-0b19-5946-88a0-fea6e3615102'::uuid, 'La liberté politique repose avant tout sur la vertu personnelle des gouvernants.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle repose sur des institutions et des contre-pouvoirs, précisément parce qu’on ne peut pas compter sur la vertu.', 4),
    ('2052e1e5-4cfc-54ef-a57f-427dae012a0c'::uuid, 'e5224a3c-0b19-5946-88a0-fea6e3615102'::uuid, 'La « tyrannie de la majorité » désigne, chez Tocqueville…', 'mcq', '["L’oppression exercée au nom du nombre","Le pouvoir d’un tyran isolé","Le règne des experts","L’absence de gouvernement"]'::jsonb, 0, 'Une décision majoritaire n’est pas pour autant juste.', 5),
    ('5ac3d1a5-992b-5c9e-b1f2-d6cba3b221d1'::uuid, 'e5224a3c-0b19-5946-88a0-fea6e3615102'::uuid, 'Selon Mill, la seule raison d’exercer une contrainte sur quelqu’un est…', 'mcq', '["D’empêcher qu’il ne nuise à autrui","De le rendre meilleur","De protéger la tradition","De faire respecter la majorité"]'::jsonb, 0, 'C’est le principe de non-nuisance, cœur du libéralisme politique.', 6),
    ('fd4c3425-992a-5f34-8a58-9f0530b461ec'::uuid, 'e5224a3c-0b19-5946-88a0-fea6e3615102'::uuid, 'L’absence totale de lois garantit la liberté de chacun.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Sans loi, c’est la force qui règne, et le plus fort qui décide.', 7),
    ('76cda25c-8c96-5fc0-8e2d-fbabec2aea03'::uuid, 'e5224a3c-0b19-5946-88a0-fea6e3615102'::uuid, 'La désobéissance civile se caractérise par…', 'mcq', '["Une infraction publique qui assume la sanction","Une révolte armée","Une fraude discrète","Un vote de protestation"]'::jsonb, 0, 'Elle conteste une loi injuste au nom du droit lui-même.', 8),
    ('cba5d875-b1d9-552a-abe3-bc4b7f59ef65'::uuid, '2fe7a0ab-548b-5b30-beb2-bea56837c10f'::uuid, 'Chez Saussure, le lien entre signifiant et signifié est…', 'mcq', '["Arbitraire","Naturel","Imposé par la logique","Décidé par chaque locuteur"]'::jsonb, 0, 'Rien dans l’animal n’impose le mot « chien » plutôt que *dog*.', 1),
    ('f9644d59-0dbb-5698-adb6-c181d0053532'::uuid, '2fe7a0ab-548b-5b30-beb2-bea56837c10f'::uuid, '« Arbitraire » signifie que chaque locuteur peut changer sa langue à volonté.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'La langue est une institution collective, qui préexiste à celui qui la parle.', 2),
    ('9d49e7ad-7e25-5774-afa9-47870a668c11'::uuid, '2fe7a0ab-548b-5b30-beb2-bea56837c10f'::uuid, 'La distinction langue / parole oppose…', 'mcq', '["Le système commun et son usage individuel","L’écrit et l’oral","Le vrai et le faux","La grammaire et le vocabulaire"]'::jsonb, 0, 'La langue est sociale, la parole est un acte.', 3),
    ('a00eb760-8fcd-56e9-a973-a29754724683'::uuid, '2fe7a0ab-548b-5b30-beb2-bea56837c10f'::uuid, 'Pour Bergson, le mot risque…', 'mcq', '["D’écraser la singularité de ce que nous ressentons","De rendre la pensée impossible","De remplacer la logique","De supprimer la mémoire"]'::jsonb, 0, 'Le mot commun ne dit que ce qu’il y a de stable et d’impersonnel.', 4),
    ('4f341fe6-5427-5de7-a996-6428bf9f1500'::uuid, '2fe7a0ab-548b-5b30-beb2-bea56837c10f'::uuid, 'Un énoncé performatif…', 'mcq', '["Accomplit l’acte qu’il énonce","Décrit un fait","Est toujours faux","Est une question"]'::jsonb, 0, '« Je promets », « la séance est ouverte » : dire, c’est faire.', 5),
    ('93f339dc-d5c8-51be-a455-c424232475a4'::uuid, '2fe7a0ab-548b-5b30-beb2-bea56837c10f'::uuid, 'Hegel estime que la pensée trouve son existence dans le mot.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Sans langage, elle reste indéterminée.', 6),
    ('b7ee3a27-9d80-51ce-a3dc-901d46fac1ea'::uuid, '2fe7a0ab-548b-5b30-beb2-bea56837c10f'::uuid, 'Ce qui distingue le langage humain de la communication animale, c’est notamment…', 'mcq', '["La combinaison libre des signes et le dialogue","Le volume sonore","Le nombre de signaux","La rapidité de transmission"]'::jsonb, 0, 'Le code des abeilles est fixe : il ne se répond pas.', 7),
    ('8d5384ff-d93a-523e-84b9-ecd4e272fe6a'::uuid, '2fe7a0ab-548b-5b30-beb2-bea56837c10f'::uuid, 'Le langage sert uniquement à décrire la réalité.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il agit aussi : promettre, ordonner, blesser, engager.', 8),
    ('17687c95-e77f-537c-9544-30e2ce2b693e'::uuid, 'bed6745e-1f74-5093-a286-a2aecfc72199'::uuid, 'Le vrai et le faux se disent proprement…', 'mcq', '["D’un jugement ou d’une proposition","D’une chose","d’une sensation","D’une personne"]'::jsonb, 0, 'Une chose est réelle ou non, elle n’est pas « vraie ».', 1),
    ('633eedb4-2276-53e2-8389-a917a89d8426'::uuid, 'bed6745e-1f74-5093-a286-a2aecfc72199'::uuid, 'La définition classique de la vérité est l’adéquation entre le discours et…', 'mcq', '["Ce qui est","L’opinion commune","L’intérêt général","La cohérence interne"]'::jsonb, 0, 'C’est la vérité-correspondance.', 2),
    ('0b08f896-480a-5797-a6e7-24ae3bacc83f'::uuid, 'bed6745e-1f74-5093-a286-a2aecfc72199'::uuid, 'Chez Platon, la *doxa* désigne…', 'mcq', '["L’opinion reçue sans examen","La science démontrée","Le mythe fondateur","La vertu politique"]'::jsonb, 0, 'Elle peut être juste par hasard, mais elle ignore pourquoi.', 3),
    ('0b5e5415-2a92-5e86-9148-dc96f9f62b20'::uuid, 'bed6745e-1f74-5093-a286-a2aecfc72199'::uuid, 'Dans l’allégorie de la caverne, les prisonniers prennent les ombres pour la réalité.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Et celui qui revient leur dire la vérité n’est pas bien accueilli.', 4),
    ('1ef4a25a-a8ef-57a6-bace-f4a50bf1b59b'::uuid, 'bed6745e-1f74-5093-a286-a2aecfc72199'::uuid, 'La formule « l’homme est la mesure de toute chose » est de…', 'mcq', '["Protagoras","Platon","Descartes","Kant"]'::jsonb, 0, 'Elle résume le relativisme des sophistes.', 5),
    ('96aee1d9-61d0-5245-97ed-20c8b515cdc8'::uuid, 'bed6745e-1f74-5093-a286-a2aecfc72199'::uuid, 'Le relativisme intégral se réfute lui-même.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Si toute vérité est relative, cette thèse l’est aussi.', 6),
    ('58d61fa2-8dba-55d1-a12b-fea64f4ad3f4'::uuid, 'bed6745e-1f74-5093-a286-a2aecfc72199'::uuid, 'Le critère cartésien de la vérité est…', 'mcq', '["L’évidence, ce qui est clair et distinct","L’accord de la majorité","L’utilité pratique","L’ancienneté de la thèse"]'::jsonb, 0, 'Ce que l’esprit ne peut pas mettre en doute.', 7),
    ('200beb73-da57-59f1-92e0-2f6700d2168e'::uuid, 'bed6745e-1f74-5093-a286-a2aecfc72199'::uuid, 'Tolérance et relativisme signifient la même chose.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'La tolérance respecte les personnes ; le relativisme renonce à distinguer le vrai du faux.', 8),
    ('5bb52e37-d25f-5d2c-9d82-e37bed01a0ba'::uuid, 'c550c5e1-b309-519c-b30b-cff57514e651'::uuid, 'Selon Galilée, le grand livre de la nature est écrit…', 'mcq', '["En langue mathématique","En grec ancien","Dans le langage des mythes","Par la seule observation"]'::jsonb, 0, 'Mesurer et quantifier fondent la science moderne.', 1),
    ('65de6c96-ba41-57d2-bece-85f3943b2273'::uuid, 'c550c5e1-b309-519c-b30b-cff57514e651'::uuid, 'Dans la méthode expérimentale de Claude Bernard, l’hypothèse vient…', 'mcq', '["Après l’observation et avant l’expérience","Après l’expérience","À la place de l’observation","Après la publication"]'::jsonb, 0, 'Observation → hypothèse → expérience, avec obligation de douter.', 2),
    ('3dd9926b-2010-5f91-bbe1-2cfbd8e453bc'::uuid, 'c550c5e1-b309-519c-b30b-cff57514e651'::uuid, 'Un fait scientifique parle de lui-même, sans hypothèse préalable.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il ne répond qu’à une question qu’on lui pose.', 3),
    ('2575f476-27ab-5ba8-9222-867bc4b00b68'::uuid, 'c550c5e1-b309-519c-b30b-cff57514e651'::uuid, 'Le problème de l’induction, souligné par Hume, est que…', 'mcq', '["Aucune répétition observée ne garantit la loi générale","L’expérience est impossible","Les mathématiques sont fausses","La logique est inutile"]'::jsonb, 0, 'Le passage du particulier au général n’est jamais démontré.', 4),
    ('27c84edb-3de2-577d-8816-96670dd8925e'::uuid, 'c550c5e1-b309-519c-b30b-cff57514e651'::uuid, 'Pour Popper, un énoncé est scientifique s’il est…', 'mcq', '["Falsifiable","Invérifiable","Approuvé par la majorité des savants","Utile"]'::jsonb, 0, 'Il doit prendre le risque d’être démenti par l’expérience.', 5),
    ('a74612e5-3ebd-50e2-b8aa-d0734ea099e2'::uuid, 'c550c5e1-b309-519c-b30b-cff57514e651'::uuid, 'Une théorie que rien ne pourrait réfuter est la plus solide des sciences.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Selon Popper, elle est simplement hors du champ scientifique.', 6),
    ('4bcf598f-fcfb-5157-9abe-8e86ba04c1a1'::uuid, 'c550c5e1-b309-519c-b30b-cff57514e651'::uuid, 'Un « obstacle épistémologique », chez Bachelard, désigne…', 'mcq', '["Une évidence familière qui empêche de connaître","Un manque de moyens financiers","Une erreur de calcul","Une censure politique"]'::jsonb, 0, 'On connaît contre une connaissance antérieure.', 7),
    ('a0f97fa5-7894-508f-8539-3fb752463689'::uuid, 'c550c5e1-b309-519c-b30b-cff57514e651'::uuid, 'Kuhn décrit l’histoire des sciences comme une succession de paradigmes.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Les périodes de science normale sont interrompues par des révolutions.', 8),
    ('59bb2538-4fb0-5ac6-8b68-dcfb749262b5'::uuid, '31b0bf90-8830-577a-b43f-8e3f89264e8f'::uuid, 'La technique est-elle née de la science ?', 'mcq', '["Non, elle lui est très antérieure","Oui, au XVIIe siècle","Oui, au XIXe siècle","Oui, dès l’Antiquité grecque"]'::jsonb, 0, 'On taillait des outils bien avant toute théorie scientifique.', 1),
    ('a8e48c0c-4a89-576e-b0c2-0bf67e1d9535'::uuid, '31b0bf90-8830-577a-b43f-8e3f89264e8f'::uuid, 'Bergson propose de nommer notre espèce…', 'mcq', '["*Homo faber*","*Homo sapiens*","*Homo economicus*","*Homo ludens*"]'::jsonb, 0, 'L’intelligence se mesure d’abord à la fabrication d’outils.', 2),
    ('138f944d-cad0-548a-9953-b55f8eed094e'::uuid, '31b0bf90-8830-577a-b43f-8e3f89264e8f'::uuid, 'Dans le mythe de Prométhée, la technique compense un défaut originel de l’homme.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Né nu et démuni, l’homme survit par l’art et le feu.', 3),
    ('962465a7-bcce-5cf1-a86b-63310d3c9f7a'::uuid, '31b0bf90-8830-577a-b43f-8e3f89264e8f'::uuid, 'Le programme cartésien de maîtrise de la nature visait notamment…', 'mcq', '["La conservation de la santé","La domination militaire","La contemplation désintéressée","La suppression du travail"]'::jsonb, 0, 'Descartes en fait explicitement « le premier bien » visé.', 4),
    ('10f24634-de65-5046-8138-8fa7d535411f'::uuid, '31b0bf90-8830-577a-b43f-8e3f89264e8f'::uuid, 'Pour Heidegger, la technique moderne est un outil parfaitement neutre.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle impose un rapport au monde qui traite tout comme un stock disponible.', 5),
    ('62dec725-ccf4-5609-9eb3-9da24d638a61'::uuid, '31b0bf90-8830-577a-b43f-8e3f89264e8f'::uuid, 'Jacques Ellul décrit un « système technicien » qui…', 'mcq', '["Se développe selon sa propre logique d’efficacité","Est piloté par les philosophes","Décline depuis 1950","Dépend uniquement des besoins"]'::jsonb, 0, 'L’efficacité y devient sa propre justification.', 6),
    ('d22e3e7b-0253-5f87-b71b-6cf719518db1'::uuid, '31b0bf90-8830-577a-b43f-8e3f89264e8f'::uuid, 'Le principe responsabilité de Jonas demande de tenir compte…', 'mcq', '["Des générations futures","Du seul intérêt présent","De la rentabilité","De la tradition"]'::jsonb, 0, 'Le pouvoir technique engage ceux qui ne sont pas nés.', 7),
    ('64a06e3a-cf3e-55b0-98fb-896c749e00bd'::uuid, '31b0bf90-8830-577a-b43f-8e3f89264e8f'::uuid, 'Ce que nous pouvons techniquement faire indique ce que nous devons faire.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Du pouvoir on ne déduit aucun devoir : c’est le cœur du problème éthique.', 8),
    ('018490b4-1dd8-56db-bb5d-0fdad1e06b99'::uuid, 'f6e6e8e5-696c-5e44-a41d-370eee81bd9f'::uuid, 'Pour Kant, le jugement de goût est…', 'mcq', '["Désintéressé et pourtant prétendument universel","Un simple goût personnel sans portée","Une connaissance par concepts","Un calcul d’utilité"]'::jsonb, 0, 'C’est tout le paradoxe du beau : subjectif, mais réclamant l’accord d’autrui.', 1),
    ('ab295297-bf35-5a0e-83fc-dd5cd7d31522'::uuid, 'f6e6e8e5-696c-5e44-a41d-370eee81bd9f'::uuid, 'L’agréable et le beau, chez Kant, désignent la même chose.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'L’agréable plaît aux sens et ne se discute pas ; le beau exige un assentiment.', 2),
    ('d26fef65-d934-56b4-b76e-c4cfdb59fe1b'::uuid, 'f6e6e8e5-696c-5e44-a41d-370eee81bd9f'::uuid, 'Le génie, selon Kant, est…', 'mcq', '["Le talent par lequel la nature donne ses règles à l’art","Un savoir-faire enseignable","Une intelligence supérieure","Le succès commercial"]'::jsonb, 0, 'L’artiste ne peut pas expliquer la recette de son œuvre.', 3),
    ('f27ced01-52c6-575c-8379-a1bf158df3dd'::uuid, 'f6e6e8e5-696c-5e44-a41d-370eee81bd9f'::uuid, 'Platon condamne l’art parce qu’il…', 'mcq', '["Imite ce qui n’est déjà qu’une copie","Coûte trop cher","Est réservé aux riches","Ne plaît à personne"]'::jsonb, 0, 'L’art serait éloigné deux fois de la vérité.', 4),
    ('206ef354-1429-5f2f-b52e-59a7961f4bab'::uuid, 'f6e6e8e5-696c-5e44-a41d-370eee81bd9f'::uuid, 'Pour Aristote, la tragédie opère une catharsis, c’est-à-dire…', 'mcq', '["Une purgation des passions","Une leçon de morale explicite","Une imitation exacte du réel","Un divertissement sans effet"]'::jsonb, 0, 'La terreur et la pitié y sont éprouvées puis épurées.', 5),
    ('d337ba09-c30c-50f6-af91-d69996d5e624'::uuid, 'f6e6e8e5-696c-5e44-a41d-370eee81bd9f'::uuid, 'Ce que Walter Benjamin appelle l’« aura » se perd avec la reproduction technique.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'L’œuvre perd son ici-et-maintenant unique.', 6),
    ('d8736ab8-d46c-5107-a41c-0149d4b19270'::uuid, 'f6e6e8e5-696c-5e44-a41d-370eee81bd9f'::uuid, 'L’artisan se distingue de l’artiste en ce qu’il…', 'mcq', '["Sait d’avance ce qu’il produit et peut le refaire","Travaille sans outil","Ne vend rien","Ignore les règles"]'::jsonb, 0, 'L’œuvre d’art, elle, n’est pas la réalisation d’un plan préexistant.', 7),
    ('ae00525b-ed71-553b-b5ee-b7cce879f265'::uuid, 'f6e6e8e5-696c-5e44-a41d-370eee81bd9f'::uuid, 'Une œuvre d’art doit nécessairement plaire pour avoir de la valeur.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle peut déranger, choquer, et compter davantage qu’une œuvre plaisante.', 8),
    ('5ad1781c-b82a-5c7a-8fcf-32f740465548'::uuid, '13cc6121-eeeb-5560-a9c3-5f24f2a16eba'::uuid, 'L’étymologie *religare* renvoie à l’idée…', 'mcq', '["De lien","De secret","De sacrifice","De loi écrite"]'::jsonb, 0, 'Relier les hommes entre eux et au divin.', 1),
    ('705d2ef2-5705-541e-b90d-605bd0072f37'::uuid, '13cc6121-eeeb-5560-a9c3-5f24f2a16eba'::uuid, 'Durkheim définit la religion par…', 'mcq', '["Le partage du sacré et du profane dans une communauté","La seule croyance individuelle","L’existence d’un livre saint","La croyance en un dieu unique"]'::jsonb, 0, 'Le fait religieux y est d’abord un fait social.', 2),
    ('ec0602ac-3d33-5cfc-8944-675d04c1adea'::uuid, '13cc6121-eeeb-5560-a9c3-5f24f2a16eba'::uuid, 'La foi est une connaissance scientifique imparfaite.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle relève d’un autre ordre : on démontre un savoir, on adhère à une foi.', 3),
    ('da092126-7604-5bea-bd2b-8184d7867bdc'::uuid, '13cc6121-eeeb-5560-a9c3-5f24f2a16eba'::uuid, 'Le pari de Pascal repose sur l’idée que…', 'mcq', '["La raison ne peut trancher, il faut donc miser","L’existence de Dieu est démontrable","La religion est inutile","La foi vient de l’expérience"]'::jsonb, 0, 'L’enjeu infini commande, selon lui, le choix.', 4),
    ('4d94b0ea-2574-54ee-bb27-3a64da8779e4'::uuid, '13cc6121-eeeb-5560-a9c3-5f24f2a16eba'::uuid, 'Pour Feuerbach, Dieu est…', 'mcq', '["Une projection des qualités humaines","Une hypothèse scientifique","Une invention des prêtres seuls","Une réalité démontrée"]'::jsonb, 0, 'L’homme s’appauvrit de ce qu’il attribue au ciel.', 5),
    ('f2b31c80-9274-52ea-9845-44cb980707fc'::uuid, '13cc6121-eeeb-5560-a9c3-5f24f2a16eba'::uuid, 'Marx appelle la religion « l’opium du peuple » pour dire qu’elle…', 'mcq', '["Console d’une misère réelle sans la supprimer","Rend les hommes violents","Est une drogue interdite","Enrichit les pauvres"]'::jsonb, 0, 'Elle est « le soupir de la créature opprimée ».', 6),
    ('84e5d786-4ef0-51ea-821f-07c970f190df'::uuid, '13cc6121-eeeb-5560-a9c3-5f24f2a16eba'::uuid, 'Les critiques de Feuerbach, Marx et Freud démontrent que Dieu n’existe pas.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elles expliquent la croyance, elles ne réfutent pas son objet.', 7),
    ('dd94ac9d-3291-5258-b6fb-94abc18a6597'::uuid, '13cc6121-eeeb-5560-a9c3-5f24f2a16eba'::uuid, 'La laïcité, au sens du droit français, signifie…', 'mcq', '["La neutralité de l’État et la liberté de conscience","L’interdiction des religions","L’obligation d’être athée","La religion d’État"]'::jsonb, 0, 'Chacun reste libre de croire, de changer de croyance ou de n’en avoir aucune.', 8),
    ('b8931e44-b32a-53dd-a396-465d93a1a2ca'::uuid, '8d2abe30-aeac-5f85-a003-88a7ebe10e58'::uuid, 'Qui écrit : « Si personne ne me le demande, je le sais ; si je veux l’expliquer, je ne le sais plus » ?', 'mcq', '["Augustin","Aristote","Bergson","Kant"]'::jsonb, 0, 'Le livre XI des *Confessions* est le texte de référence sur le temps.', 1),
    ('3a115514-79f9-5b68-ac80-8dbbf93a8ed0'::uuid, '8d2abe30-aeac-5f85-a003-88a7ebe10e58'::uuid, 'Aristote définit le temps comme…', 'mcq', '["Le nombre du mouvement","Une illusion de l’esprit","Un cadre absolu et vide","La forme de la sensibilité"]'::jsonb, 0, 'Sans changement, il n’y a pas de temps mesurable.', 2),
    ('f348a4e8-966b-5dc5-a6fa-7474f63da9ba'::uuid, '8d2abe30-aeac-5f85-a003-88a7ebe10e58'::uuid, 'Pour Kant, le temps est une propriété des choses elles-mêmes.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est la forme *a priori* de notre sensibilité, notre manière d’ordonner l’expérience.', 3),
    ('b82d0226-9252-5c5a-8bd2-9f0a6c55445d'::uuid, '8d2abe30-aeac-5f85-a003-88a7ebe10e58'::uuid, 'Les « trois présents » d’Augustin sont…', 'mcq', '["Mémoire, attention, attente","Passé, présent, futur","Enfance, âge adulte, vieillesse","Instant, durée, éternité"]'::jsonb, 0, 'Le passé n’est plus et le futur n’est pas encore : seul le présent de l’âme les tient.', 4),
    ('f94d8682-7d40-59b2-a41c-1226f3568370'::uuid, '8d2abe30-aeac-5f85-a003-88a7ebe10e58'::uuid, 'La durée bergsonienne s’oppose au temps des horloges parce qu’elle est…', 'mcq', '["Continue et hétérogène","Divisible en instants égaux","Mesurable avec précision","Identique pour tous"]'::jsonb, 0, 'Une heure d’ennui et une heure de joie ne se valent pas.', 5),
    ('f8441882-ca6b-5bda-84d9-3bbaa5c53e76'::uuid, '8d2abe30-aeac-5f85-a003-88a7ebe10e58'::uuid, 'Selon Épicure, « la mort n’est rien pour nous ».', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Quand nous sommes, elle n’est pas là ; quand elle est là, nous ne sommes plus.', 6),
    ('a2bf93b7-19d4-5435-a9ad-abcaccc6d7e6'::uuid, '8d2abe30-aeac-5f85-a003-88a7ebe10e58'::uuid, 'Sénèque soutient que…', 'mcq', '["Nous perdons beaucoup de temps plutôt que nous n’en manquons","La vie est trop courte par nature","Le temps n’existe pas","Il faut vivre pour l’avenir"]'::jsonb, 0, '« La vie est assez longue pour qui sait en user. »', 7),
    ('20b05356-b058-50b9-9ab6-e456b708e954'::uuid, '8d2abe30-aeac-5f85-a003-88a7ebe10e58'::uuid, 'L’irréversibilité du temps ne fait que des malheurs : regret, vieillissement.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle rend aussi possibles le projet, la promesse et l’histoire.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('philosophie');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('philosophie')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 225 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 225 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
