-- =============================================================================
-- Studuel — Migration 228 : ENSEIGNEMENT SCIENTIFIQUE Tle — LE PROGRAMME OFFICIEL
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 228 --slugs enseignement-scientifique
--
-- CONSTAT MESURÉ (sonde en lecture seule sur la base, 05/08/2026) :
-- l'enseignement scientifique de Terminale n'avait que 4 chapitres, taillés
-- dans un découpage maison (« L'atmosphère et le climat », « L'énergie :
-- conversions et enjeux », « Une histoire du vivant », « L'intelligence
-- artificielle ») qui résumait TOUT le programme en quatre fiches. Un élève qui
-- révisait le transport de l'électricité, les modèles démographiques, les
-- cycles de Milankovitch ou l'histoire de la lignée humaine ne trouvait rien.
-- Cette migration installe les 16 fiches du programme officiel, dans l'ordre
-- des 6 chapitres du BO, et retire les 4 fiches de synthèse qu'elles
-- recouvrent entièrement.
--
-- Cette migration apporte : 16 chapitres, 16 leçons,
-- 16 quiz et 128 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 0. Ménage ----------------------------------------------------------------
-- [enseignement-scientifique] La file « À revoir » d'abord : review_items.item_id n'a PAS de clé
-- [enseignement-scientifique] étrangère (il pointe soit une question, soit une carte). Rien ne casse si on
-- [enseignement-scientifique] l'oublie — le lecteur écarte déjà un contenu disparu — mais le compteur
-- [enseignement-scientifique] « X à revoir » continuerait de compter des questions qui n'existent plus.
DELETE FROM public.review_items ri
 USING public.quiz_questions qq, public.quizzes qz, public.lessons l,
       public.chapters c, public.subjects s
 WHERE ri.item_kind = 'question'
   AND ri.item_id = qq.id
   AND qq.quiz_id = qz.id
   AND qz.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'enseignement-scientifique'
   AND c.level = 'Tle'
   AND l.title IN ('L''essentiel du cours', 'Exercices types');

-- [enseignement-scientifique] Les quiz ensuite : quizzes.lesson_id est ON DELETE SET NULL, donc
-- [enseignement-scientifique] supprimer le chapitre laisserait derrière lui des quiz orphelins, rattachés à
-- [enseignement-scientifique] aucune leçon mais toujours servis par le moteur de révision.
DELETE FROM public.quizzes q
 USING public.lessons l, public.chapters c, public.subjects s
 WHERE q.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'enseignement-scientifique'
   AND c.level = 'Tle'
   AND l.title IN ('L''essentiel du cours', 'Exercices types');

-- [enseignement-scientifique] Puis les chapitres : leçons, fiches de révision, supports, progression
-- [enseignement-scientifique] et chapitres cochés partent en cascade (toutes les clés étrangères vers
-- [enseignement-scientifique] chapters et lessons sont ON DELETE CASCADE).
DELETE FROM public.chapters c
 USING public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'enseignement-scientifique'
   AND c.level = 'Tle'
   AND EXISTS (
     SELECT 1 FROM public.lessons l
      WHERE l.chapter_id = c.id
        AND l.title IN ('L''essentiel du cours', 'Exercices types')
   );

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position)
SELECT v.id, s.id, v.level, v.title, v.position
  FROM (VALUES
    ('9146be9f-e43b-5ce1-972f-a51bc834e8d6'::uuid, 'enseignement-scientifique', 'Tle', 'L’atmosphère terrestre : son rôle dans l’apparition et dans le maintien de la vie', 1),
    ('7b53f066-8239-5100-9ba5-2928d50e3915'::uuid, 'enseignement-scientifique', 'Tle', 'Le climat : un système complexe', 2),
    ('9ca80b90-2d09-5f1a-9206-b3914212f7de'::uuid, 'enseignement-scientifique', 'Tle', 'Variations passées, récentes et futures du climat', 3),
    ('f085ef8c-8240-5dbe-988b-e2a9a50103bc'::uuid, 'enseignement-scientifique', 'Tle', 'Modèles prédictifs du climat du futur', 4),
    ('931709de-4a64-51e3-a92c-373a328fb0c2'::uuid, 'enseignement-scientifique', 'Tle', 'L’énergie électrique au cours des deux derniers siècles : le XIXe siècle', 5),
    ('5a2d036e-f388-5878-a29f-91ef6e005013'::uuid, 'enseignement-scientifique', 'Tle', 'L’énergie électrique au cours des deux derniers siècles : le XXe siècle', 6),
    ('b64fe4db-1cd3-52aa-881c-5894a6ea0c04'::uuid, 'enseignement-scientifique', 'Tle', 'Le transport de l’électricité', 7),
    ('ac80328d-962c-5cfd-9fb1-6675d36ce25a'::uuid, 'enseignement-scientifique', 'Tle', 'Les atouts de l’électricité et ses enjeux dans le développement durable', 8),
    ('c7199117-4288-5ea0-96ae-042932b4df27'::uuid, 'enseignement-scientifique', 'Tle', 'La nécessité d’une transition énergétique pour agir sur le futur climatique', 9),
    ('8aeedf56-b872-52c0-9345-38c488aee030'::uuid, 'enseignement-scientifique', 'Tle', 'Le choix énergétique : une décision stratégique à fort impact sur les sociétés', 10),
    ('b1161592-55cd-578a-8797-38d6083799f8'::uuid, 'enseignement-scientifique', 'Tle', 'Origine et évolution de la biodiversité', 11),
    ('1b60335a-9e70-5956-a785-2c91e20c4239'::uuid, 'enseignement-scientifique', 'Tle', 'Modèles démographiques : comprendre l’évolution quantitative des populations', 12),
    ('e13a1e3c-740f-5aa8-b110-7e08ed9e1847'::uuid, 'enseignement-scientifique', 'Tle', 'L’évolution comme grille de lecture du monde', 13),
    ('64ffe19b-b878-5111-b0f4-c0298d22ac27'::uuid, 'enseignement-scientifique', 'Tle', 'Histoire évolutive de la lignée humaine', 14),
    ('909c8ea1-df1d-5ab5-bdcc-6cf7839c237c'::uuid, 'enseignement-scientifique', 'Tle', 'Automatisation du traitement de l’information : une évolution des capacités humaines', 15),
    ('4a9daae4-f705-51c1-a64f-73ac4724a894'::uuid, 'enseignement-scientifique', 'Tle', 'L’intelligence artificielle : enjeux et débats', 16)
  ) AS v(id, slug, level, title, position)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('d526f5bb-07bf-587d-8fa3-66beb2b0f434', '9146be9f-e43b-5ce1-972f-a51bc834e8d6', 'Une atmosphère fabriquée par le vivant', E'L''air que tu respires n''a rien d''un décor posé une fois pour toutes : sa composition actuelle est le PRODUIT de la vie, pas sa condition de départ.\n\n## L''atmosphère primitive\nIl y a environ **4,5 milliards d''années**, l''atmosphère issue du dégazage volcanique contient surtout de la **vapeur d''eau**, du **dioxyde de carbone** et du **diazote** — et **pas de dioxygène**. En se refroidissant, la vapeur d''eau se condense : les **océans** se forment il y a environ 4,4 à 4 milliards d''années. Une grande partie du CO₂ s''y dissout puis se fixe dans les roches carbonatées, ce qui fait chuter sa teneur.\n\n## L''irruption du dioxygène\nLa vie apparaît dans l''eau il y a au moins **3,8 milliards d''années**. Des micro-organismes photosynthétiques, les **cyanobactéries**, produisent du dioxygène. Il est d''abord consommé par l''oxydation du fer dissous dans l''océan — d''où les **fers rubanés** — puis s''accumule dans l''atmosphère à partir d''environ **2,4 milliards d''années** : c''est la **Grande Oxydation**.\n\n> La composition actuelle (78 % de diazote, 21 % de dioxygène, 0,04 % de CO₂) est une signature du vivant : aucune planète voisine n''a un tel taux de O₂.\n\n## Le bouclier d''ozone\nUne partie du dioxygène de la haute atmosphère est transformée en **ozone (O₃)** sous l''effet du rayonnement solaire. La **couche d''ozone**, constituée entre environ 2 milliards et 500 millions d''années, absorbe les **UV** les plus énergétiques. Sans elle, la vie ne pouvait rester qu''immergée : c''est son installation qui rend possible la **sortie des eaux**, il y a environ 500 à 400 millions d''années.\n\n## Ce que l''atmosphère fait aujourd''hui\n- elle fournit le **dioxygène** de la respiration et le **CO₂** de la photosynthèse ;\n- elle **filtre** les UV grâce à l''ozone ;\n- elle maintient, par l''**effet de serre**, une température moyenne compatible avec l''eau liquide ;\n- elle **redistribue** l''énergie reçue de l''équateur vers les pôles.', 1),
  ('d53caf39-cc57-584c-8c3c-633c6d94d741', '7b53f066-8239-5100-9ba5-2928d50e3915', 'Bilan radiatif, rétroactions et couplages', E'Le climat n''est pas la météo : c''est la **statistique** du temps sur au moins **30 ans**. Et cette statistique est pilotée par une comptabilité d''énergie.\n\n## Le bilan radiatif\nLa Terre reçoit du Soleil, en moyenne sur toute sa surface, environ **340 W/m²**. Environ **30 %** repartent aussitôt, réfléchis par les nuages, les glaces et les surfaces claires : c''est l''**albédo**. Le reste est absorbé, puis réémis vers l''espace sous forme de **rayonnement infrarouge**. À l''équilibre, entrées = sorties, et la température moyenne reste stable.\n\n## L''effet de serre\nCertains gaz — **vapeur d''eau**, **CO₂**, **méthane (CH₄)**, **protoxyde d''azote** — absorbent l''infrarouge émis par le sol et en réémettent une partie vers le bas. Sans cet effet de serre naturel, la température moyenne serait d''environ **−18 °C** au lieu de **+15 °C**.\n\n> Un **forçage radiatif** positif, c''est un déséquilibre : la Terre reçoit plus qu''elle ne renvoie, elle se réchauffe jusqu''à retrouver un équilibre à une température plus haute.\n\n## Les rétroactions\nLe système ne réagit pas proportionnellement, parce qu''il se répond à lui-même.\n- **Rétroaction positive (amplifie)** : la fonte des glaces diminue l''albédo, donc la surface absorbe davantage, donc elle fond encore plus. Idem pour la vapeur d''eau — un air plus chaud en contient plus, et elle est elle-même un gaz à effet de serre.\n- **Rétroaction négative (freine)** : un sol plus chaud rayonne plus d''infrarouge, ce qui évacue de l''énergie.\n\n## Les couplages\nL''**océan** stocke plus de 90 % de l''excès de chaleur et absorbe environ un quart du CO₂ émis. Il redistribue l''énergie par la **circulation thermohaline**, l''atmosphère par les **cellules de convection**. Les deux fluides sont couplés : **El Niño**, oscillation du Pacifique, dérègle les précipitations à l''échelle du globe.\n\n## Pourquoi « complexe »\nBeaucoup de variables, des échelles de temps très différentes (l''atmosphère réagit en jours, l''océan profond en siècles), des rétroactions, des seuils : la réponse du climat n''est ni linéaire ni immédiate.', 1),
  ('f6523cc3-3393-5169-84db-77f5b8a9ccb3', '9ca80b90-2d09-5f1a-9206-b3914212f7de', 'Lire le climat dans la glace', E'Le climat a toujours varié. L''argument n''infirme rien : ce qui distingue le réchauffement actuel, c''est sa **vitesse** et sa **cause**.\n\n## Les archives naturelles\nOn reconstitue les climats anciens sans thermomètre, grâce à des **indicateurs** :\n- les **carottes de glace** (Vostok, EPICA en Antarctique) remontent à plus de **800 000 ans** : les bulles d''air piégées donnent la composition de l''atmosphère d''alors ;\n- le rapport des **isotopes de l''oxygène** (δ¹⁸O) dans la glace ou les coquilles donne la température ;\n- **pollens**, **cernes des arbres**, sédiments complètent le tableau sur les périodes récentes.\n\n> Ces archives montrent une corrélation étroite entre teneur en CO₂ et température sur 800 000 ans, avec une alternance glaciaire / interglaciaire d''environ 100 000 ans.\n\n## Les causes des variations passées\nAux échelles de 10 000 à 100 000 ans, les **paramètres orbitaux** (cycles de **Milankovitch**) modifient la distribution de l''énergie reçue : **excentricité** (~100 000 ans), **obliquité** (~41 000 ans), **précession** (~21 000 ans). S''y ajoutent le volcanisme, l''activité solaire, la dérive des continents. Ces facteurs sont **naturels** — et ils sont trop lents ou trop faibles pour expliquer le siècle écoulé.\n\n## Le réchauffement récent\nDepuis 1850-1900, la température moyenne globale a augmenté d''environ **1,1 à 1,2 °C**. Dans le même temps, le CO₂ est passé d''environ **280 ppm** à plus de **420 ppm**, un niveau inédit depuis au moins 800 000 ans. La signature isotopique du carbone ajouté désigne les **combustibles fossiles**. Le **GIEC** conclut que l''influence humaine sur ce réchauffement est **sans équivoque**.\n\n## Les futurs possibles\nLes projections dépendent des **scénarios d''émissions** : de l''ordre de **+1,5 à +2 °C** à la fin du siècle si les émissions chutent vite, jusqu''à **+4 °C et au-delà** si elles se poursuivent. Conséquences attendues : montée du niveau marin, événements extrêmes plus intenses, déplacement des zones climatiques, acidification de l''océan.', 1),
  ('d62fc50e-d6af-5cc1-8d03-70c35d899589', 'f085ef8c-8240-5dbe-988b-e2a9a50103bc', 'Ce qu’un modèle peut dire, et ce qu’il ne peut pas', E'Un modèle climatique n''est pas une boule de cristal : c''est de la **physique résolue numériquement**, avec des incertitudes que les climatologues chiffrent eux-mêmes.\n\n## Comment fonctionne un modèle\nL''atmosphère et l''océan sont découpés en **mailles** (quelques dizaines de kilomètres de côté). Dans chaque maille, l''ordinateur résout les équations de la mécanique des fluides, du transfert radiatif, de la thermodynamique, pas de temps après pas de temps. Ce qui est plus petit que la maille — un nuage, un orage — doit être **paramétré**, c''est-à-dire représenté de façon approchée : c''est la principale source d''incertitude physique.\n\n## Comment on lui fait confiance\nOn **valide** un modèle en lui faisant rejouer le passé : s''il reproduit le climat du XXe siècle, les refroidissements qui suivent les grandes éruptions volcaniques et les climats anciens, il est jugé fiable. Test décisif : les modèles ne reproduisent le réchauffement observé que si on y injecte les **émissions humaines** — les seuls facteurs naturels donnent une courbe plate.\n\n## Prévoir le temps ≠ projeter le climat\nLa prévision météo perd toute valeur au-delà d''une dizaine de jours, parce que le système est **chaotique** : une erreur minuscule sur l''état initial enfle. Une projection climatique ne prétend pas dire le temps qu''il fera le 3 mai 2087 ; elle donne des **statistiques** (moyennes, extrêmes) en réponse à un forçage donné.\n\n## Les scénarios\nLes modèles ne connaissent pas nos décisions futures. On leur fournit donc des **scénarios d''émissions** contrastés, et chacun donne une trajectoire :\n- émissions fortement réduites → réchauffement contenu autour de **+1,5 à 2 °C** ;\n- émissions maintenues → **+4 °C** et au-delà à la fin du siècle.\n\n> Les trois sources d''incertitude : le scénario (nos choix), la physique du modèle, et la variabilité naturelle. La première est de loin la plus grande — c''est-à-dire que le futur climatique dépend surtout de nous.', 1),
  ('2522baa4-ca4f-5147-95e8-ad15f141745f', '931709de-4a64-51e3-a92c-373a328fb0c2', 'De la pile de Volta au réseau naissant', E'En un siècle, l''électricité passe du statut de curiosité de laboratoire à celui d''énergie industrielle. Tout tient à une découverte : on sait désormais la **produire en continu** et la **convertir**.\n\n## Produire un courant\n**1800** : Volta empile disques de zinc et de cuivre séparés par un tissu imbibé — la **pile** délivre pour la première fois un courant continu et durable. **1820** : Œrsted observe qu''un courant dévie une aiguille aimantée — l''électricité et le magnétisme sont liés. **1831** : **Faraday** découvre l''**induction électromagnétique** — un aimant en mouvement près d''une bobine y fait naître un courant.\n\n> L''induction, c''est le principe de TOUTE la production électrique actuelle : faire tourner un aimant devant des bobines. Une centrale nucléaire, un barrage et une éolienne ne diffèrent que par ce qui fait tourner l''aimant.\n\n## Les machines\n**1869** : Zénobe **Gramme** construit une dynamo capable de fournir du courant en quantité industrielle. Puis l''**alternateur** produit du courant alternatif. La machine tourne dans les deux sens : le même dispositif convertit l''énergie mécanique en énergie électrique (**générateur**) ou l''inverse (**moteur électrique**).\n\n## Les usages\n**1879** : Edison met au point une lampe à **incandescence** durable ; l''éclairage public et domestique se répand. Expositions universelles, tramways, premiers réseaux urbains : la « fée électricité » devient un symbole de modernité.\n\n## Les grandeurs à connaître\n- **P = U × I** (puissance en watts, tension en volts, intensité en ampères) ;\n- **E = P × t** (énergie en joules si t est en secondes) ;\n- **1 kWh = 3,6 × 10⁶ J** — l''unité de la facture ;\n- le **rendement** d''une conversion = énergie utile / énergie reçue ; il est toujours inférieur à 1, l''écart partant en chaleur.', 1),
  ('b2d37b80-f5b1-51bb-838d-9f180abf870b', '5a2d036e-f388-5878-a29f-91ef6e005013', 'Le siècle du réseau et des grandes centrales', E'Au XXe siècle, l''électricité cesse d''être un luxe urbain pour devenir une **infrastructure nationale**, puis la condition de tout ce qui suit — de l''électroménager à l''ordinateur.\n\n## L''électrification du territoire\nLes années 1920-1950 voient l''électrification des campagnes françaises : le réseau est étendu village par village. **EDF est créée en 1946** par nationalisation, ce qui unifie production, transport et distribution.\n\n## Les grandes filières de production\n- **Hydraulique** : les grands barrages d''après-guerre (Génissiat, Tignes, Serre-Ponçon) ; production souple, mobilisable en minutes.\n- **Thermique à flamme** : charbon, fioul, puis gaz — on chauffe de l''eau, la vapeur fait tourner la turbine.\n- **Nucléaire** : la **fission** de l''uranium remplace la flamme comme source de chaleur. Après le **choc pétrolier de 1973**, la France lance le **plan Messmer** : le parc de réacteurs est construit pour l''essentiel entre 1975 et 1990. L''électricité française devient **massivement nucléaire** (de l''ordre de 65 à 70 % de la production) et peu carbonée.\n\n> Toutes ces filières, sauf le photovoltaïque, se ramènent au même schéma : une source d''énergie fait tourner une turbine, la turbine entraîne un alternateur, l''alternateur produit le courant.\n\n## La consommation qui suit\nLa consommation d''électricité est multipliée par plusieurs dizaines sur le siècle : équipement des ménages, chauffage électrique, industrie, puis **électronique**. Le **transistor** (1947) puis le circuit intégré ouvrent l''informatique — un secteur entièrement dépendant de l''électricité.\n\n## Ce que le siècle laisse en héritage\nUn système centralisé, conçu pour de gros moyens de production pilotables, alors que le XXIe siècle y raccorde des sources **décentralisées et intermittentes** (éolien, solaire). Toute la question de la transition tient dans cet écart.', 1),
  ('3923cf72-b984-54ee-8c71-7788b89f07ed', 'b64fe4db-1cd3-52aa-881c-5894a6ea0c04', 'Pourquoi la très haute tension', E'L''électricité se produit rarement là où elle se consomme. Entre les deux, un réseau — et un problème de physique : les **pertes par effet Joule**.\n\n## L''effet Joule\nUn conducteur parcouru par un courant s''échauffe. La puissance perdue vaut :\n\n**P(perdue) = R × I²**\n\navec R la résistance de la ligne et I l''intensité. Le carré est décisif : **doubler l''intensité quadruple les pertes**.\n\n## La parade : monter la tension\nLa puissance transportée vaut P = U × I. Pour transporter la même puissance avec **moins d''intensité**, il faut donc une **tension plus élevée**. Multiplier U par 100 divise I par 100, donc les pertes par 10 000.\n\n> C''est pourquoi les grandes lignes fonctionnent en **très haute tension : 225 000 et 400 000 volts**. Les pertes sur le réseau français restent ainsi de l''ordre de 2 à 3 %.\n\n## Le transformateur, et pourquoi le courant est alternatif\nÉlever puis abaisser la tension se fait avec un **transformateur** — deux bobines couplées par un noyau magnétique. Or un transformateur **ne fonctionne qu''en courant alternatif** : c''est la variation du champ qui induit la tension au secondaire. C''est là l''origine de la « guerre des courants » entre Edison (continu) et Tesla / Westinghouse (alternatif) à la fin du XIXe : l''alternatif l''emporte parce qu''il se transporte.\n\n## La chaîne complète\nCentrale → transformateur **élévateur** → lignes THT (400 kV) → postes → réseau de distribution (20 kV) → transformateur **abaisseur** de quartier → 230 V chez toi.\n\n## L''équilibre permanent\nL''électricité ne se stocke pas à grande échelle : à chaque instant, la production doit **égaler** la consommation, sinon la **fréquence** (50 Hz en Europe) dérive et le réseau décroche. C''est le métier de **RTE**, qui pilote l''équilibre en temps réel. Les seuls stockages massifs disponibles sont les **STEP** (stations de pompage-turbinage) et, à plus petite échelle, les batteries.', 1),
  ('d46df2fa-a71d-515a-8278-695431e4082e', 'ac80328d-962c-5cfd-9fb1-6675d36ce25a', 'Un vecteur, pas une source', E'Première chose à ne pas confondre : l''électricité n''est pas une **source** d''énergie, c''est un **vecteur**. Elle ne se trouve pas dans le sol : on la fabrique à partir d''autre chose, et on la transporte.\n\n## Les atouts\n- **Polyvalence** : elle se convertit facilement en chaleur, lumière, mouvement, information.\n- **Transport** : sur des centaines de kilomètres avec des pertes de quelques pour cent.\n- **Rendement d''usage élevé** : un moteur électrique dépasse 90 % de rendement, contre environ 30 à 40 % pour un moteur thermique — pour la même énergie utile, il en faut bien moins.\n- **Aucune émission au point d''usage** : décisif en ville pour la qualité de l''air.\n\n## Le point de vigilance\nUne électricité n''est propre que si sa **production** l''est. On compare les filières par leur **intensité carbone**, en grammes de CO₂ par kWh sur tout le cycle de vie :\n- charbon : environ **820** g/kWh ;\n- gaz : environ **490** g/kWh ;\n- solaire photovoltaïque : quelques dizaines ;\n- éolien, hydraulique, nucléaire : de l''ordre de **5 à 15** g/kWh.\n\n> Une voiture électrique n''est vertueuse que branchée sur un mix décarboné : la même voiture émet très différemment selon le pays où elle se recharge.\n\n## L''analyse du cycle de vie\nOn ne juge pas une technologie sur sa seule utilisation : l''**ACV** compte l''extraction des matériaux, la fabrication, le transport, l''usage et la fin de vie. Un panneau solaire n''émet rien en fonctionnant, mais sa fabrication a un coût énergétique et matériel.\n\n## Les enjeux\n- **Électrifier les usages** (transport, chauffage) pour sortir des fossiles ;\n- gérer l''**intermittence** de l''éolien et du solaire (stockage, pilotage de la demande, interconnexions) ;\n- sécuriser les **ressources critiques** : cuivre, lithium, terres rares ;\n- ne pas oublier la **sobriété** : l''énergie la moins polluante reste celle qu''on ne consomme pas.', 1),
  ('18be7a45-2d60-55ac-a416-4df909426d83', 'c7199117-4288-5ea0-96ae-042932b4df27', 'Budget carbone et neutralité', E'Agir sur le climat futur ne se joue pas sur les gestes symboliques mais sur une comptabilité : celle des **gaz à effet de serre** que nous émettons encore.\n\n## D''où viennent les émissions\nLa consommation mondiale d''énergie repose encore à environ **80 %** sur les **combustibles fossiles** (charbon, pétrole, gaz). Or brûler un carbone fossile, c''est réinjecter dans l''atmosphère un carbone stocké depuis des millions d''années : le cycle du carbone en est déséquilibré. Les émissions se répartissent entre production d''énergie, industrie, transports, bâtiments et agriculture.\n\n## Le budget carbone\nLa hausse de température est à peu près **proportionnelle au CO₂ cumulé** émis depuis l''ère industrielle. On peut donc calculer un **budget carbone** : la quantité totale qu''il reste à émettre pour ne pas dépasser un seuil. Pour rester sous **+1,5 °C**, ce budget se compte en quelques centaines de milliards de tonnes — soit une poignée d''années au rythme actuel.\n\n> Conséquence directe : ce n''est pas le niveau des émissions annuelles qui fixe le réchauffement, c''est leur **somme**. Retarder la baisse consomme le budget.\n\n## Neutralité carbone\nÊtre **neutre en carbone** ne veut pas dire n''émettre plus rien : cela veut dire que les émissions résiduelles sont **compensées par des puits** (forêts, sols, océans, captage). L''**Accord de Paris (2015)** engage les États à contenir le réchauffement **bien en dessous de 2 °C** et à poursuivre les efforts pour **1,5 °C** ; l''Union européenne vise la neutralité en **2050**.\n\n## Les quatre leviers\n1. **Sobriété** : consommer moins d''énergie.\n2. **Efficacité** : consommer mieux à service rendu égal (isolation, rendement).\n3. **Décarbonation de l''énergie** : remplacer les fossiles par de l''électricité bas carbone et des renouvelables.\n4. **Puits de carbone** : préserver forêts et sols, développer le captage.\n\nAucun ne suffit seul : c''est leur combinaison, et leur **vitesse**, qui décident de la trajectoire.', 1),
  ('fd95840e-99b6-5314-8aad-b621ec541bbb', '8aeedf56-b872-52c0-9345-38c488aee030', 'Arbitrer avec des chiffres, pas avec des impressions', E'Choisir un mix énergétique n''est pas un débat d''opinion : c''est un arbitrage entre des critères **mesurables** qui ne pointent pas tous dans la même direction.\n\n## Les critères d''un choix\n- **Émissions de CO₂ par kWh** sur tout le cycle de vie ;\n- **coût** du kWh produit, en incluant l''investissement (le « coût complet ») ;\n- **disponibilité** : pilotable ou intermittente ;\n- **emprise au sol** et acceptabilité locale ;\n- **risques** (accident, déchets) ;\n- **dépendance** aux importations : combustible, mais aussi métaux et composants ;\n- **emplois** et filières industrielles.\n\n> Aucune filière n''est la meilleure sur tous les critères à la fois. C''est pourquoi ces choix se tranchent politiquement, mais doivent s''argumenter avec des données.\n\n## L''inertie, souvent sous-estimée\nUne centrale se construit en 5 à 15 ans et fonctionne 40 à 60 ans ; un parc de logements se renouvelle à environ 1 % par an. Une décision énergétique **engage donc plusieurs décennies** : c''est ce qui rend le retard si coûteux, et les revirements si difficiles.\n\n## Le rôle des sociétés\nLe mix d''un pays reflète son histoire et sa géographie autant que la physique : la France a fait le choix du nucléaire après 1973 pour son indépendance ; la Norvège s''appuie sur son hydraulique ; l''Allemagne a longtemps combiné sortie du nucléaire et charbon ; les pays du Golfe dépendent de leurs hydrocarbures.\n\n## Ce qu''on attend de toi au bac\nNon pas une opinion, mais un **raisonnement sur documents** : lire un graphique d''émissions ou de coûts, comparer deux filières sur un critère explicite, distinguer un **fait mesuré** d''un **jugement de valeur**, et énoncer les limites des données utilisées (périmètre, année, source).', 1),
  ('4cbf9833-4755-5d9a-9dff-ffb6c9655fd7', 'b1161592-55cd-578a-8797-38d6083799f8', 'Trois niveaux, cinq crises, et une sixième', E'La biodiversité n''est pas un catalogue d''espèces : c''est un **état instantané** d''un processus qui n''a jamais cessé de la produire et de la détruire.\n\n## Trois niveaux\n- **génétique** : la diversité des allèles au sein d''une même espèce ;\n- **spécifique** : la diversité des espèces d''un milieu ;\n- **écosystémique** : la diversité des milieux eux-mêmes.\n\nLes trois comptent : une espèce nombreuse mais génétiquement uniforme est fragile face à une maladie.\n\n## Ce qu''on en connaît\nEnviron **2 millions d''espèces** sont décrites, sur un total estimé entre **8 et 10 millions** — sans compter les micro-organismes. Une part majeure de la biodiversité n''a donc jamais été inventoriée.\n\n## Estimer sans tout compter\nOn ne dénombre pas une population entière : on **échantillonne**. La méthode de **capture-marquage-recapture** en est l''exemple type. On capture n₁ individus, on les marque, on les relâche ; lors d''une seconde capture de n₂ individus, m sont marqués. On estime alors :\n\n**N = (n₁ × n₂) / m**\n\nCette estimation suppose que les individus se sont **remélangés**, qu''aucun n''est né ni mort entre les deux captures, et que le marquage ne change pas leurs chances d''être repris. Toute estimation est donc assortie d''une **incertitude**.\n\n## Les crises biologiques\nL''histoire de la vie compte **cinq crises majeures**, définies par la disparition d''un grand nombre d''espèces en un temps géologiquement court :\n- **Permien-Trias**, il y a environ **252 millions d''années** : la plus grave, plus de 90 % des espèces marines disparaissent ;\n- **Crétacé-Paléogène**, il y a **66 millions d''années** : fin des dinosaures non aviens, liée à un astéroïde et à un volcanisme intense.\n\nAprès chaque crise, les groupes survivants se **diversifient** dans les niches libérées : les mammifères doivent leur essor à la cinquième.\n\n## La sixième\nLe rythme actuel d''extinction est estimé de **100 à 1 000 fois** supérieur au rythme naturel. Ses causes sont **anthropiques** : destruction des habitats, surexploitation, espèces invasives, pollutions, changement climatique.', 1),
  ('e035dbd8-732e-59fc-b6bd-4c6508effce3', '1b60335a-9e70-5956-a785-2c91e20c4239', 'Trois modèles, et leurs limites', E'Une population n''évolue pas au hasard : quelques modèles simples suffisent à décrire — et à prévoir un temps — son effectif.\n\n## Le vocabulaire\nLe **taux de variation** d''une population dépend des naissances, des morts, et des migrations. On note souvent **r** le taux d''accroissement (par exemple r = 0,02 pour +2 % par an).\n\n## Le modèle linéaire\nLa population augmente d''un **nombre constant** d''individus par unité de temps : N(t) = N₀ + a × t. Le graphique est une **droite**. Modèle rarement réaliste sur le vivant.\n\n## Le modèle exponentiel (ou géométrique)\nLa population augmente d''un **pourcentage constant** : chaque année, elle est multipliée par (1 + r).\n\n**N(t) = N₀ × (1 + r)^t**\n\nLe graphique s''envole : c''est la croissance qui donne un **temps de doublement** constant. Ordre de grandeur utile : avec r = 2 % par an, la population double en environ **35 ans** (règle des 70 : doublement ≈ 70 / taux en %).\n\n## Le modèle logistique\nAucun milieu n''est infini. Le modèle logistique introduit une **capacité biotique K** — l''effectif maximal que le milieu peut soutenir. La courbe est en **S** : croissance quasi exponentielle au départ, ralentissement quand N approche de K, puis plateau.\n\n> Le passage du modèle exponentiel au modèle logistique, c''est le moment où les **ressources** deviennent limitantes : nourriture, espace, prédation, maladies.\n\n## La démographie humaine\nLa population mondiale a franchi les **8 milliards en 2022**. Elle a été multipliée par 4 au XXe siècle, mais le taux d''accroissement **diminue** depuis les années 1970 : c''est la **transition démographique** — la mortalité baisse d''abord, la natalité ensuite, et l''écart entre les deux fait la poussée. Les projections situent un plafond autour de **10 milliards** au cours du XXIe siècle.\n\n## Ce qu''un modèle ne fait pas\nIl ne **prédit** pas : il **prolonge une hypothèse**. Changez le taux, la courbe change. Un modèle se juge à sa capacité à reproduire les données passées, et s''utilise en énonçant ses limites.', 1),
  ('518f103b-8469-51f6-a1d7-f11bed92d3ab', 'e13a1e3c-740f-5aa8-b110-7e08ed9e1847', 'Sélection naturelle et dérive génétique', E'La théorie de l''évolution n''est pas une hypothèse sur le passé lointain : c''est un **outil de lecture** du présent, qui explique la résistance aux antibiotiques comme la forme du bec d''un pinson.\n\n## Le mécanisme darwinien\nPublié en **1859** par Darwin, il tient en trois conditions, toutes observables :\n1. les individus d''une population **varient** ;\n2. une partie de cette variation est **héréditaire** ;\n3. tous n''ont pas le même **succès reproducteur** dans le milieu donné.\n\nAlors, mécaniquement, les caractères favorables deviennent plus fréquents à la génération suivante. C''est la **sélection naturelle**. Elle n''agit pas sur l''individu — qui ne change pas — mais sur la **fréquence des allèles dans la population**.\n\n> Attention au piège de formulation : une bactérie ne « devient » pas résistante pour survivre à l''antibiotique. Certaines l''étaient déjà par **mutation aléatoire** ; l''antibiotique élimine les autres, et les résistantes se multiplient.\n\n## La dérive génétique\nLe hasard aussi fait évoluer. À chaque génération, un échantillon d''allèles est transmis : dans une **petite population**, cet échantillonnage suffit à faire disparaître un allèle ou à l''imposer, **indépendamment de tout avantage**. C''est la **dérive génétique** — elle est d''autant plus forte que la population est réduite.\n\n## Ce que l''évolution n''est pas\n- Ce n''est pas un **progrès** : elle n''a ni but ni direction, elle ajuste à un milieu qui change lui-même.\n- Ce n''est pas une **hiérarchie** : une bactérie actuelle est aussi « évoluée » qu''un mammifère, même durée d''évolution derrière elle.\n- L''évolution ne cherche pas la perfection : elle bricole avec l''existant.\n\n## Applications concrètes\n- **Antibiorésistance** : chaque usage inutile d''antibiotique sélectionne des souches résistantes — enjeu de santé publique majeur.\n- **Résistance des insectes aux insecticides** et des adventices aux herbicides.\n- **Sélection artificielle** : c''est le même mécanisme, avec l''humain comme facteur de tri — d''où les races de chiens et les variétés de blé.\n- **Virus** : le virus de la grippe mute vite, d''où un vaccin reformulé chaque année.', 1),
  ('081055e0-11e3-5fe9-8bf2-18a772241486', '64ffe19b-b878-5111-b0f4-c0298d22ac27', 'Un buisson, pas une échelle', E'L''image de la « marche du progrès » — un singe courbé qui se redresse jusqu''à l''homme moderne — est **fausse**. La lignée humaine est un **buisson** : des branches qui coexistent, et dont une seule subsiste.\n\n## Notre place dans le vivant\nNous sommes des **primates**, très proches des chimpanzés et bonobos : nos génomes diffèrent d''environ **1 %**. Notre dernier ancêtre commun avec eux vivait il y a **7 à 10 millions d''années**. Nous ne descendons donc pas du chimpanzé : nous en sommes des **cousins**.\n\n## Les caractères dérivés du genre Homo\n- **bipédie permanente** : trou occipital avancé, bassin court et large, courbures de la colonne, pied à voûte plantaire ;\n- **volume crânien** croissant : environ 400 cm³ chez les australopithèques, 1 350 cm³ en moyenne chez *Homo sapiens* ;\n- **face réduite**, mâchoire moins puissante ;\n- **outils**, **feu**, **art**, **langage** — des caractères culturels que les fossiles n''attestent qu''indirectement.\n\n## Quelques repères fossiles\n- **Toumaï** (*Sahelanthropus*), environ **7 millions d''années**, Tchad ;\n- **Lucy** (*Australopithecus afarensis*), environ **3,2 millions d''années**, Éthiopie — bipède mais encore bonne grimpeuse ;\n- ***Homo habilis***, environ 2,4 Ma, premiers outils taillés ;\n- ***Homo erectus***, environ 1,9 Ma, premier à sortir d''Afrique ;\n- ***Homo neanderthalensis***, en Europe, éteint il y a environ **40 000 ans** ;\n- ***Homo sapiens***, dont les plus anciens fossiles connus (Jebel Irhoud, Maroc) datent d''environ **300 000 ans**.\n\n## Ce que dit la génétique\nL''ADN ancien a tranché plusieurs débats. *Homo sapiens* est d''**origine africaine** et a essaimé ensuite sur les autres continents. Il a **coexisté** avec Néandertal et Denisova, et s''est croisé avec eux : les populations non africaines actuelles portent environ **1 à 3 %** d''ADN néandertalien.\n\n> Plusieurs espèces d''*Homo* ont vécu en même temps. Être seuls sur la planète est une situation récente et exceptionnelle.', 1),
  ('4b84e413-e79a-5c2e-ad8f-f772a81a21bb', '909c8ea1-df1d-5ab5-bdcc-6cf7839c237c', 'De la Pascaline au circuit intégré', E'Automatiser le traitement de l''information, c''est confier à une machine une opération qu''un humain faisait de tête : compter, trier, comparer. L''histoire de cette délégation est ancienne — et elle s''accélère.\n\n## Mécaniser le calcul\n**1642** : Pascal construit la **Pascaline**, machine à additionner à roues dentées. Au XIXe, **Charles Babbage** conçoit une **machine analytique** programmable, jamais achevée ; **Ada Lovelace** en écrit le premier algorithme destiné à une machine et comprend, la première, qu''elle pourrait traiter autre chose que des nombres.\n\n## Le fondement théorique\n**1936** : **Alan Turing** définit un modèle abstrait de machine — la **machine de Turing** — qui délimite ce qui est **calculable**. Résultat décisif : certains problèmes ne sont **pas** calculables, quelle que soit la puissance de la machine. L''automatisation a donc des limites théoriques, pas seulement techniques.\n\n## L''électronique\n**1947** : le **transistor** remplace le tube à vide — plus petit, plus fiable, moins gourmand. Puis le **circuit intégré** en réunit des milliers sur une puce. La **loi de Moore** (1965) observe un doublement du nombre de transistors par puce environ tous les deux ans : c''est cette progression, tenue pendant des décennies, qui rend possibles l''ordinateur personnel, le smartphone, puis les données massives.\n\n## Algorithme et programme\n- un **algorithme** est une suite finie d''instructions non ambiguës résolvant un problème ;\n- un **programme** en est la traduction dans un langage exécutable par la machine.\n\nLe traitement automatisé suppose des **données** codées en binaire, et il traite d''autant mieux qu''elles sont nombreuses et bien structurées.\n\n## Ce que cela change pour nous\nLa machine **augmente** certaines capacités : mémoire, vitesse de calcul, accès à l''information. Elle en **délègue** d''autres : orientation, calcul mental, mémorisation. Ce transfert n''est pas neutre — il pose la question de ce que nous conservons la capacité de faire nous-mêmes, et de notre dépendance à des systèmes que nous ne contrôlons pas individuellement.', 1),
  ('89ee3993-c2c5-585c-b8c8-86a84118388a', '4a9daae4-f705-51c1-a64f-73ac4724a894', 'Ce qu’apprend une machine — et ce que ça coûte', E'L''intelligence artificielle désigne un ensemble de techniques permettant à une machine d''accomplir des tâches qui, faites par un humain, demanderaient de l''intelligence. Le mot est ancien (1956) ; ce qui est récent, c''est ce qui la fait fonctionner.\n\n## Apprendre au lieu d''être programmé\nUn programme classique applique des règles écrites par un humain. Un système d''**apprentissage automatique** (*machine learning*) fait l''inverse : on lui fournit un grand nombre d''**exemples**, il en **ajuste ses paramètres** jusqu''à reproduire la relation entrée-sortie. Les **réseaux de neurones artificiels** — vaguement inspirés des neurones biologiques, sans en être un modèle — sont aujourd''hui l''architecture dominante.\n\nTrois ingrédients l''ont rendue possible : des **données massives**, une **puissance de calcul** considérable, et des **algorithmes** d''optimisation efficaces.\n\n> Un système d''IA ne « comprend » pas : il **généralise à partir des données** qu''on lui a montrées. D''où sa force, et toutes ses faiblesses.\n\n## Les débats, sans caricature\n- **Biais** : un système entraîné sur des données biaisées reproduit et amplifie ces biais (recrutement, justice prédictive, reconnaissance faciale moins fiable selon les visages). Le biais vient des **données**, pas d''une intention de la machine.\n- **Explicabilité** : les grands modèles sont des « boîtes noires ». Difficile d''exiger la justification d''une décision médicale ou judiciaire.\n- **Responsabilité** : qui répond d''un accident de véhicule autonome — le constructeur, le programmeur, le propriétaire ?\n- **Emploi** : des tâches disparaissent, d''autres apparaissent ; le débat porte sur le rythme et sur qui en supporte le coût.\n- **Vie privée** : l''IA a faim de données personnelles.\n- **Coût énergétique** : entraîner et faire tourner de grands modèles consomme électricité, eau de refroidissement et métaux — un enjeu qui rejoint directement le thème du climat.\n\n## Ce que le programme attend\nDistinguer ce qui relève du **fait technique** (comment ça marche, ce que ça peut) de ce qui relève du **choix de société** (ce qu''on autorise, et sous quel contrôle). Une position argumentée s''appuie sur des données ; une crainte ou un enthousiasme, non.', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('6f79bfd1-09bb-50d2-8e91-60df26660460'::uuid, 'Quiz — Une atmosphère fabriquée par le vivant', 'Ens. scientifique', 'Tle', 'L’atmosphère terrestre : son rôle dans l’apparition et dans le maintien de la vie', 'd526f5bb-07bf-587d-8fa3-66beb2b0f434'::uuid),
    ('c51413bf-0d51-56fb-8979-79626c770cc0'::uuid, 'Quiz — Bilan radiatif, rétroactions et couplages', 'Ens. scientifique', 'Tle', 'Le climat : un système complexe', 'd53caf39-cc57-584c-8c3c-633c6d94d741'::uuid),
    ('7317c375-e6cd-5614-8121-d1193fe9c31a'::uuid, 'Quiz — Lire le climat dans la glace', 'Ens. scientifique', 'Tle', 'Variations passées, récentes et futures du climat', 'f6523cc3-3393-5169-84db-77f5b8a9ccb3'::uuid),
    ('c10e7e4f-591f-5ca6-b8b8-b2d9611a38aa'::uuid, 'Quiz — Ce qu’un modèle peut dire, et ce qu’il ne peut pas', 'Ens. scientifique', 'Tle', 'Modèles prédictifs du climat du futur', 'd62fc50e-d6af-5cc1-8d03-70c35d899589'::uuid),
    ('25d3d541-1d25-5d72-ad95-e8b69e1ca349'::uuid, 'Quiz — De la pile de Volta au réseau naissant', 'Ens. scientifique', 'Tle', 'L’énergie électrique au cours des deux derniers siècles : le XIXe siècle', '2522baa4-ca4f-5147-95e8-ad15f141745f'::uuid),
    ('c43f566b-1f84-5f2e-a90e-dcd11c011057'::uuid, 'Quiz — Le siècle du réseau et des grandes centrales', 'Ens. scientifique', 'Tle', 'L’énergie électrique au cours des deux derniers siècles : le XXe siècle', 'b2d37b80-f5b1-51bb-838d-9f180abf870b'::uuid),
    ('c19ba8e3-7f04-588c-a9ad-057853054c17'::uuid, 'Quiz — Pourquoi la très haute tension', 'Ens. scientifique', 'Tle', 'Le transport de l’électricité', '3923cf72-b984-54ee-8c71-7788b89f07ed'::uuid),
    ('a6b7676f-c562-5c60-b2a8-9386d8bd9c1c'::uuid, 'Quiz — Un vecteur, pas une source', 'Ens. scientifique', 'Tle', 'Les atouts de l’électricité et ses enjeux dans le développement durable', 'd46df2fa-a71d-515a-8278-695431e4082e'::uuid),
    ('ddab56e3-78b0-5aad-abd4-b04856c5d3ef'::uuid, 'Quiz — Budget carbone et neutralité', 'Ens. scientifique', 'Tle', 'La nécessité d’une transition énergétique pour agir sur le futur climatique', '18be7a45-2d60-55ac-a416-4df909426d83'::uuid),
    ('52629743-9808-5afb-bf1e-621d8437dd92'::uuid, 'Quiz — Arbitrer avec des chiffres, pas avec des impressions', 'Ens. scientifique', 'Tle', 'Le choix énergétique : une décision stratégique à fort impact sur les sociétés', 'fd95840e-99b6-5314-8aad-b621ec541bbb'::uuid),
    ('84b9ce5c-3a91-56ad-a992-ed1b1b68700e'::uuid, 'Quiz — Trois niveaux, cinq crises, et une sixième', 'Ens. scientifique', 'Tle', 'Origine et évolution de la biodiversité', '4cbf9833-4755-5d9a-9dff-ffb6c9655fd7'::uuid),
    ('b5a0fce7-4135-52e9-a611-51e0e22477f4'::uuid, 'Quiz — Trois modèles, et leurs limites', 'Ens. scientifique', 'Tle', 'Modèles démographiques : comprendre l’évolution quantitative des populations', 'e035dbd8-732e-59fc-b6bd-4c6508effce3'::uuid),
    ('eed38330-b961-5f35-9689-4b92421064fe'::uuid, 'Quiz — Sélection naturelle et dérive génétique', 'Ens. scientifique', 'Tle', 'L’évolution comme grille de lecture du monde', '518f103b-8469-51f6-a1d7-f11bed92d3ab'::uuid),
    ('2b26de16-1531-50c7-93c8-0bcb284cbc91'::uuid, 'Quiz — Un buisson, pas une échelle', 'Ens. scientifique', 'Tle', 'Histoire évolutive de la lignée humaine', '081055e0-11e3-5fe9-8bf2-18a772241486'::uuid),
    ('964bf06c-2641-5f91-b8dd-1563c053c8bd'::uuid, 'Quiz — De la Pascaline au circuit intégré', 'Ens. scientifique', 'Tle', 'Automatisation du traitement de l’information : une évolution des capacités humaines', '4b84e413-e79a-5c2e-ad8f-f772a81a21bb'::uuid),
    ('570771b6-2df4-52a0-a2a8-3e585284dd9b'::uuid, 'Quiz — Ce qu’apprend une machine — et ce que ça coûte', 'Ens. scientifique', 'Tle', 'L’intelligence artificielle : enjeux et débats', '89ee3993-c2c5-585c-b8c8-86a84118388a'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('adeaf5e1-9bcc-567e-aaff-50a6832bc08f'::uuid, '6f79bfd1-09bb-50d2-8e91-60df26660460'::uuid, 'Quel gaz était ABSENT de l’atmosphère primitive ?', 'mcq', '["Le dioxygène","Le dioxyde de carbone","La vapeur d’eau","Le diazote"]'::jsonb, 0, 'Le dioxygène est un produit tardif de la photosynthèse, pas un gaz du dégazage volcanique.', 1),
    ('90eb8462-3b19-5843-b6d0-a76542948dee'::uuid, '6f79bfd1-09bb-50d2-8e91-60df26660460'::uuid, 'Quels organismes sont à l’origine du dioxygène atmosphérique ?', 'mcq', '["Les cyanobactéries","Les premiers animaux","Les champignons","Les végétaux terrestres"]'::jsonb, 0, 'Ces micro-organismes photosynthétiques oxygènent l’océan puis l’atmosphère.', 2),
    ('1e6a56e9-a41e-5e01-94a3-f02d2eb1a16e'::uuid, '6f79bfd1-09bb-50d2-8e91-60df26660460'::uuid, 'La Grande Oxydation date d’environ 2,4 milliards d’années.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Le O₂ commence à s’accumuler une fois le fer océanique oxydé (fers rubanés).', 3),
    ('b1755882-6241-554d-a6fa-7da9790fe964'::uuid, '6f79bfd1-09bb-50d2-8e91-60df26660460'::uuid, 'Quelle est la composition approximative de l’atmosphère actuelle ?', 'mcq', '["78 % N₂, 21 % O₂","50 % N₂, 50 % O₂","78 % O₂, 21 % N₂","90 % CO₂, 10 % O₂"]'::jsonb, 0, 'Le CO₂ ne représente qu’environ 0,04 %, malgré son rôle climatique majeur.', 4),
    ('934b3bfc-a4a0-5230-b61d-8ea01eae52b3'::uuid, '6f79bfd1-09bb-50d2-8e91-60df26660460'::uuid, 'Quel rôle joue la couche d’ozone ?', 'mcq', '["Elle absorbe les UV les plus énergétiques","Elle produit le dioxygène","Elle refroidit la surface","Elle dissout le CO₂"]'::jsonb, 0, 'C’est ce filtre qui a rendu possible la vie hors de l’eau.', 5),
    ('c60c9658-b043-53be-9bea-6db29270a4e2'::uuid, '6f79bfd1-09bb-50d2-8e91-60df26660460'::uuid, 'La sortie des eaux a été possible avant la formation de la couche d’ozone.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Sans filtre à UV, la vie ne pouvait subsister qu’immergée : l’ozone précède la conquête des continents.', 6),
    ('4f3ee54e-0605-52aa-bc7b-b1cf8477c667'::uuid, '6f79bfd1-09bb-50d2-8e91-60df26660460'::uuid, 'Où est parti l’essentiel du CO₂ de l’atmosphère primitive ?', 'mcq', '["Dissous dans l’océan puis piégé dans les roches carbonatées","Détruit par les UV","Échappé dans l’espace","Transformé en ozone"]'::jsonb, 0, 'La formation des océans a lessivé l’atmosphère de son CO₂.', 7),
    ('7ddb5f65-3f6e-5792-8a3a-e6d77d21633a'::uuid, '6f79bfd1-09bb-50d2-8e91-60df26660460'::uuid, 'La composition de l’atmosphère actuelle est indépendante de la vie.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Les 21 % de dioxygène en sont directement issus : l’atmosphère est un produit du vivant.', 8),
    ('b699eefc-c6b9-5d79-8faa-edc2041354e9'::uuid, 'c51413bf-0d51-56fb-8979-79626c770cc0'::uuid, 'Quelle est la puissance solaire moyenne reçue par mètre carré de surface terrestre ?', 'mcq', '["Environ 340 W/m²","Environ 1 360 W/m²","Environ 100 W/m²","Environ 1 000 W/m²"]'::jsonb, 0, '1 360 W/m² est la constante solaire face au Soleil ; répartie sur toute la sphère, elle donne environ 340 W/m².', 1),
    ('50a42b21-248a-5b1b-a66c-1e0354db479e'::uuid, 'c51413bf-0d51-56fb-8979-79626c770cc0'::uuid, 'Que désigne l’albédo ?', 'mcq', '["La part du rayonnement réfléchie vers l’espace","La part absorbée par le sol","L’énergie émise en infrarouge","La quantité de CO₂ atmosphérique"]'::jsonb, 0, 'Il vaut environ 0,3 pour la Terre ; la glace et les nuages ont un albédo élevé.', 2),
    ('7614a973-bcc8-5166-b505-be5a9d3d8c87'::uuid, 'c51413bf-0d51-56fb-8979-79626c770cc0'::uuid, 'Sans effet de serre, la température moyenne de la Terre serait d’environ −18 °C.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Contre +15 °C aujourd’hui : l’effet de serre naturel vaut environ 33 °C.', 3),
    ('2e1481d3-6de6-5bd8-b234-6b652f1abb12'::uuid, 'c51413bf-0d51-56fb-8979-79626c770cc0'::uuid, 'La fonte des glaces qui diminue l’albédo est un exemple de…', 'mcq', '["Rétroaction positive","Rétroaction négative","Forçage négatif","Couplage thermohalin"]'::jsonb, 0, 'Moins de glace → plus d’absorption → plus de réchauffement → moins de glace.', 4),
    ('f58899d0-0d21-5e92-8d7d-0c4f6d86eda9'::uuid, 'c51413bf-0d51-56fb-8979-79626c770cc0'::uuid, 'Où va la plus grande partie de l’excès de chaleur accumulé ?', 'mcq', '["Dans l’océan","Dans l’atmosphère","Dans les sols","Dans les glaciers"]'::jsonb, 0, 'Plus de 90 % : c’est pourquoi le réchauffement se poursuit longtemps après les émissions.', 5),
    ('df91a67c-0378-59c0-ae2f-8aae24229f5f'::uuid, 'c51413bf-0d51-56fb-8979-79626c770cc0'::uuid, 'La différence entre météo et climat tient à la durée : le climat se définit sur au moins 30 ans.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Un hiver froid ne dit rien du climat, seule la statistique longue compte.', 6),
    ('52386355-2a10-5f22-9660-868ec55e8c8b'::uuid, 'c51413bf-0d51-56fb-8979-79626c770cc0'::uuid, 'Quel phénomène couple océan et atmosphère à l’échelle du Pacifique ?', 'mcq', '["El Niño","La mousson","L’effet de serre","La circulation de Hadley"]'::jsonb, 0, 'Cette oscillation dérègle les précipitations bien au-delà du Pacifique.', 7),
    ('5f5b6792-60c8-5234-8ceb-df6b21953b8d'::uuid, 'c51413bf-0d51-56fb-8979-79626c770cc0'::uuid, 'Un forçage radiatif positif refroidit la planète.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il signifie que la Terre reçoit plus d’énergie qu’elle n’en renvoie : elle se réchauffe.', 8),
    ('2e5f8880-805a-5462-a125-e22c744af203'::uuid, '7317c375-e6cd-5614-8121-d1193fe9c31a'::uuid, 'Jusqu’à quelle ancienneté les carottes de glace antarctiques renseignent-elles le climat ?', 'mcq', '["Plus de 800 000 ans","Environ 10 000 ans","Environ 100 000 ans","Plus de 10 millions d’années"]'::jsonb, 0, 'Les bulles d’air piégées y conservent la composition de l’atmosphère de l’époque.', 1),
    ('7c866731-28f8-557b-9d56-f28287926efb'::uuid, '7317c375-e6cd-5614-8121-d1193fe9c31a'::uuid, 'Quel cycle orbital dure environ 100 000 ans ?', 'mcq', '["L’excentricité","L’obliquité","La précession","La rotation"]'::jsonb, 0, 'Obliquité ≈ 41 000 ans, précession ≈ 21 000 ans.', 2),
    ('25f87053-9c61-5989-921f-5f54e1eb7e8b'::uuid, '7317c375-e6cd-5614-8121-d1193fe9c31a'::uuid, 'La teneur en CO₂ est passée d’environ 280 ppm en 1850 à plus de 420 ppm aujourd’hui.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Un niveau jamais atteint sur les 800 000 dernières années.', 3),
    ('88b94932-d73d-590f-8c46-7b7b3e5ff50f'::uuid, '7317c375-e6cd-5614-8121-d1193fe9c31a'::uuid, 'De combien la température moyenne globale a-t-elle augmenté depuis 1850-1900 ?', 'mcq', '["Environ 1,1 °C","Environ 0,1 °C","Environ 3 °C","Environ 5 °C"]'::jsonb, 0, 'L’essentiel de cette hausse s’est produit depuis 1975.', 4),
    ('7ace279d-aa38-5683-a0db-c1f5c3ac22db'::uuid, '7317c375-e6cd-5614-8121-d1193fe9c31a'::uuid, 'Les cycles de Milankovitch suffisent à expliquer le réchauffement depuis 1900.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Ils agissent sur des dizaines de milliers d’années : bien trop lents pour un siècle.', 5),
    ('ed826cb2-9947-561a-a3e4-8864f0d8c51f'::uuid, '7317c375-e6cd-5614-8121-d1193fe9c31a'::uuid, 'Que mesure-t-on avec le rapport isotopique δ¹⁸O ?', 'mcq', '["La température de l’époque","La teneur en CO₂","Le niveau de la mer","L’activité volcanique"]'::jsonb, 0, 'C’est le thermomètre des paléoclimatologues, lu dans la glace ou les coquilles.', 6),
    ('cb6bced8-bf78-593c-9c4e-58928d141c02'::uuid, '7317c375-e6cd-5614-8121-d1193fe9c31a'::uuid, 'Quel organisme évalue et synthétise l’état des connaissances sur le climat ?', 'mcq', '["Le GIEC","L’OMC","L’AIEA","L’UNESCO"]'::jsonb, 0, 'Il ne fait pas de recherche propre : il expertise la littérature scientifique existante.', 7),
    ('0ee77dc8-0214-5985-800a-a16469dedf92'::uuid, '7317c375-e6cd-5614-8121-d1193fe9c31a'::uuid, 'Le climat a toujours varié, donc le réchauffement actuel n’a rien de particulier.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Ce qui est inédit, c’est la vitesse de la hausse et sa cause, mesurée comme anthropique.', 8),
    ('c21a9486-8a8e-58f5-a908-a5f682d12f99'::uuid, 'c10e7e4f-591f-5ca6-b8b8-b2d9611a38aa'::uuid, 'Comment un modèle climatique découpe-t-il l’atmosphère ?', 'mcq', '["En mailles où il résout des équations physiques","En courbes statistiques ajustées aux données","En scénarios politiques","En archives naturelles"]'::jsonb, 0, 'Chaque maille échange énergie et matière avec ses voisines, pas de temps après pas de temps.', 1),
    ('07d65462-8d04-5951-a67f-0d6b3beacac0'::uuid, 'c10e7e4f-591f-5ca6-b8b8-b2d9611a38aa'::uuid, 'Comment valide-t-on un modèle climatique ?', 'mcq', '["En lui faisant rejouer des climats passés connus","En attendant la fin du siècle","En le comparant à la prévision météo","En le faisant valider par un vote"]'::jsonb, 0, 'S’il reproduit le passé observé, sa physique est jugée fiable pour projeter.', 2),
    ('cb8565bf-2c3f-5b7b-ae01-1957c1d47e0f'::uuid, 'c10e7e4f-591f-5ca6-b8b8-b2d9611a38aa'::uuid, 'Les modèles reproduisent le réchauffement observé même sans les émissions humaines.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Avec les seuls facteurs naturels, la courbe simulée reste plate : c’est le test d’attribution.', 3),
    ('40434600-80d0-54eb-9031-87170451523e'::uuid, 'c10e7e4f-591f-5ca6-b8b8-b2d9611a38aa'::uuid, 'Pourquoi la prévision météo est-elle limitée à une dizaine de jours ?', 'mcq', '["Parce que le système est chaotique","Parce que les ordinateurs sont trop lents","Parce que les satellites manquent","Parce que le climat change"]'::jsonb, 0, 'Une erreur infime sur l’état initial est amplifiée jusqu’à rendre la prévision inutile.', 4),
    ('d8cb728c-0ee5-5d53-b622-319bbc9c0836'::uuid, 'c10e7e4f-591f-5ca6-b8b8-b2d9611a38aa'::uuid, 'Que représentent les scénarios utilisés par les modèles ?', 'mcq', '["Des hypothèses d’émissions futures","Des erreurs de mesure","Des variantes de mailles","Des climats du passé"]'::jsonb, 0, 'Le modèle calcule la physique ; le scénario, lui, encode nos choix collectifs.', 5),
    ('5cc738e6-5b73-5a89-ba1d-77e64126cda7'::uuid, 'c10e7e4f-591f-5ca6-b8b8-b2d9611a38aa'::uuid, 'Une projection climatique prétend donner le temps qu’il fera à une date précise en 2087.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle donne des statistiques (moyennes, extrêmes) en réponse à un forçage, jamais un bulletin météo.', 6),
    ('d0a2c0b4-08a3-5da5-ac22-f0fd74f9cc09'::uuid, 'c10e7e4f-591f-5ca6-b8b8-b2d9611a38aa'::uuid, 'Quelle est la principale source d’incertitude sur le climat de 2100 ?', 'mcq', '["Le scénario d’émissions","La taille des mailles","La variabilité naturelle","La mesure des températures"]'::jsonb, 0, 'Autrement dit : nos décisions pèsent plus que les limites des modèles.', 7),
    ('53e77961-55ba-5ae7-a148-590fc88e745e'::uuid, 'c10e7e4f-591f-5ca6-b8b8-b2d9611a38aa'::uuid, 'Ce qui est plus petit que la maille, comme un nuage, doit être paramétré.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Cette représentation approchée est la principale source d’incertitude physique des modèles.', 8),
    ('ce16c87a-d73e-57d7-8e94-63a84b7a62c8'::uuid, '25d3d541-1d25-5d72-ad95-e8b69e1ca349'::uuid, 'Qui met au point la première pile en 1800 ?', 'mcq', '["Volta","Faraday","Edison","Gramme"]'::jsonb, 0, 'La pile de Volta fournit pour la première fois un courant continu durable.', 1),
    ('ae3fff9f-932e-53d1-bbb9-32c9f842b592'::uuid, '25d3d541-1d25-5d72-ad95-e8b69e1ca349'::uuid, 'Que découvre Faraday en 1831 ?', 'mcq', '["L’induction électromagnétique","La lampe à incandescence","L’effet Joule","Le transistor"]'::jsonb, 0, 'Un aimant en mouvement près d’une bobine y fait naître un courant : c’est le principe de toute production électrique.', 2),
    ('7a908d09-aa9c-5d7b-91c9-db5bf2c0f658'::uuid, '25d3d541-1d25-5d72-ad95-e8b69e1ca349'::uuid, 'Une centrale nucléaire et une éolienne produisent l’électricité par le même principe physique.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Dans les deux cas, l’induction : seule diffère la source qui fait tourner l’alternateur.', 3),
    ('c3c5832b-1009-5629-b06f-41a4107fbddc'::uuid, '25d3d541-1d25-5d72-ad95-e8b69e1ca349'::uuid, 'Que produit une dynamo ?', 'mcq', '["De l’énergie électrique à partir d’énergie mécanique","De l’énergie mécanique à partir d’électricité","De la chaleur à partir de lumière","Du courant alternatif à partir de courant continu"]'::jsonb, 0, 'La machine est réversible : utilisée à l’envers, c’est un moteur.', 4),
    ('7eb3448f-a2a6-5947-a457-97b9cab01892'::uuid, '25d3d541-1d25-5d72-ad95-e8b69e1ca349'::uuid, 'Quelle relation donne la puissance électrique ?', 'mcq', '["P = U × I","P = U / I","P = R × I","P = E × t"]'::jsonb, 0, 'En watts, avec U en volts et I en ampères.', 5),
    ('7cafb901-609c-599c-9fda-be272bbaa6af'::uuid, '25d3d541-1d25-5d72-ad95-e8b69e1ca349'::uuid, 'Un kilowattheure vaut 3,6 millions de joules.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, '1 kWh = 1 000 W × 3 600 s = 3,6 × 10⁶ J : c’est l’unité de la facture.', 6),
    ('89e118f5-32d0-577f-b72c-1756f0fda420'::uuid, '25d3d541-1d25-5d72-ad95-e8b69e1ca349'::uuid, 'Qui rend l’éclairage électrique domestique praticable en 1879 ?', 'mcq', '["Edison","Œrsted","Volta","Ampère"]'::jsonb, 0, 'Sa lampe à incandescence est assez durable pour un usage courant.', 7),
    ('685aa14c-116c-5357-987c-351f22c8ed99'::uuid, '25d3d541-1d25-5d72-ad95-e8b69e1ca349'::uuid, 'Le rendement d’une conversion d’énergie peut dépasser 1.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il est toujours inférieur à 1 : une part de l’énergie est dégradée en chaleur.', 8),
    ('75e1e63d-2823-53e5-bb8d-4bf5a854f1b8'::uuid, 'c43f566b-1f84-5f2e-a90e-dcd11c011057'::uuid, 'Quand EDF est-elle créée ?', 'mcq', '["En 1946","En 1900","En 1973","En 1990"]'::jsonb, 0, 'Par nationalisation, ce qui unifie production, transport et distribution.', 1),
    ('336d1194-670e-5d6d-b01c-fee075d2056d'::uuid, 'c43f566b-1f84-5f2e-a90e-dcd11c011057'::uuid, 'Quel événement déclenche le programme nucléaire français ?', 'mcq', '["Le choc pétrolier de 1973","La Seconde Guerre mondiale","La création de l’Union européenne","L’accident de Tchernobyl"]'::jsonb, 0, 'Le plan Messmer vise l’indépendance énergétique après la flambée du pétrole.', 2),
    ('edf1f328-97f7-5bcb-9a41-344c0acdbc08'::uuid, 'c43f566b-1f84-5f2e-a90e-dcd11c011057'::uuid, 'Dans une centrale nucléaire, la fission remplace la flamme comme source de chaleur.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Le reste de la chaîne — vapeur, turbine, alternateur — est identique à une centrale thermique.', 3),
    ('9c4825bb-fdf3-5cc6-8ba2-560c551dbad3'::uuid, 'c43f566b-1f84-5f2e-a90e-dcd11c011057'::uuid, 'Quelle filière fournit l’essentiel de l’électricité française ?', 'mcq', '["Le nucléaire","Le charbon","L’éolien","Le gaz"]'::jsonb, 0, 'De l’ordre de 65 à 70 % de la production, d’où une électricité peu carbonée.', 4),
    ('0366be80-5943-5893-a383-0d304f447d36'::uuid, 'c43f566b-1f84-5f2e-a90e-dcd11c011057'::uuid, 'Quel composant, inventé en 1947, ouvre l’ère de l’électronique ?', 'mcq', '["Le transistor","L’alternateur","Le transformateur","La diode à vide"]'::jsonb, 0, 'Il permettra le circuit intégré, donc l’informatique.', 5),
    ('e1d94cef-392d-553a-a974-ff69d87dfe1d'::uuid, 'c43f566b-1f84-5f2e-a90e-dcd11c011057'::uuid, 'Le photovoltaïque produit du courant en faisant tourner une turbine.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est la seule grande filière sans machine tournante : la conversion y est directe.', 6),
    ('f80a9d23-84a5-5341-958d-981f5babf163'::uuid, 'c43f566b-1f84-5f2e-a90e-dcd11c011057'::uuid, 'Quel est l’atout de l’hydroélectricité dans un réseau ?', 'mcq', '["Elle est mobilisable en quelques minutes","Elle ne coûte rien à construire","Elle fonctionne sans eau","Elle produit de façon constante"]'::jsonb, 0, 'Cette souplesse en fait un outil d’ajustement de la production.', 7),
    ('3d61339e-8a38-562d-92e3-30fffdc65ecc'::uuid, 'c43f566b-1f84-5f2e-a90e-dcd11c011057'::uuid, 'Le réseau du XXe siècle a été conçu pour des sources décentralisées et intermittentes.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il a été bâti pour de grosses unités pilotables : c’est précisément la difficulté de la transition.', 8),
    ('a66724da-1948-5d61-854f-0554a38901e6'::uuid, 'c19ba8e3-7f04-588c-a9ad-057853054c17'::uuid, 'Quelle est l’expression des pertes par effet Joule dans une ligne ?', 'mcq', '["P = R × I²","P = U × I","P = R / I","P = U × R"]'::jsonb, 0, 'Le carré de l’intensité : doubler I quadruple les pertes.', 1),
    ('ec09a52f-4e39-5b57-b4db-712f992cc186'::uuid, 'c19ba8e3-7f04-588c-a9ad-057853054c17'::uuid, 'Pourquoi transporte-t-on l’électricité en très haute tension ?', 'mcq', '["Pour réduire l’intensité, donc les pertes","Pour augmenter la puissance transportée","Pour éviter les transformateurs","Pour produire du courant continu"]'::jsonb, 0, 'À puissance donnée, une tension élevée signifie une intensité faible.', 2),
    ('18c93809-dc55-587a-9682-2077a94453fa'::uuid, 'c19ba8e3-7f04-588c-a9ad-057853054c17'::uuid, 'Les grandes lignes du réseau français fonctionnent sous 400 000 volts.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, '400 kV et 225 kV pour le réseau de transport ; 230 V seulement en bout de chaîne.', 3),
    ('0cfe861d-6889-59cc-8202-f46c3e06ab85'::uuid, 'c19ba8e3-7f04-588c-a9ad-057853054c17'::uuid, 'Pourquoi le courant du réseau est-il alternatif ?', 'mcq', '["Parce que le transformateur n’agit qu’en alternatif","Parce qu’il est plus sûr","Parce qu’il se stocke mieux","Parce qu’il perd moins d’énergie dans les moteurs"]'::jsonb, 0, 'Sans transformateur, impossible d’élever puis d’abaisser la tension.', 4),
    ('d6d0ce38-7a86-574d-bee0-01f551344281'::uuid, 'c19ba8e3-7f04-588c-a9ad-057853054c17'::uuid, 'Quelle fréquence le réseau européen doit-il maintenir ?', 'mcq', '["50 Hz","60 Hz","100 Hz","400 Hz"]'::jsonb, 0, 'Un écart durable signale un déséquilibre entre production et consommation.', 5),
    ('0309fb94-5caf-5094-a4e2-2e738ca85dfa'::uuid, 'c19ba8e3-7f04-588c-a9ad-057853054c17'::uuid, 'L’électricité se stocke facilement en grande quantité.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est la contrainte majeure du réseau : production et consommation doivent s’égaler en permanence.', 6),
    ('163c5eba-b703-56dd-bddd-d88a8d43550e'::uuid, 'c19ba8e3-7f04-588c-a9ad-057853054c17'::uuid, 'Quel dispositif stocke aujourd’hui l’électricité à grande échelle ?', 'mcq', '["Les stations de pompage-turbinage (STEP)","Les batteries au lithium","Les condensateurs","Les lignes THT"]'::jsonb, 0, 'On remonte l’eau dans un bassin quand il y a surplus, on la turbine quand il manque.', 7),
    ('5cf861b4-daed-5f6d-9c29-16acf669f66c'::uuid, 'c19ba8e3-7f04-588c-a9ad-057853054c17'::uuid, 'Multiplier la tension de transport par 100 divise les pertes par 100.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Par 10 000 : l’intensité est divisée par 100 et les pertes varient comme son carré.', 8),
    ('ad4553b6-23a9-5012-ae3f-e7e2a6e6969f'::uuid, 'a6b7676f-c562-5c60-b2a8-9386d8bd9c1c'::uuid, 'L’électricité est-elle une source ou un vecteur d’énergie ?', 'mcq', '["Un vecteur","Une source","Une réserve naturelle","Un combustible"]'::jsonb, 0, 'Elle est produite à partir d’autre chose, puis transportée jusqu’à l’usage.', 1),
    ('50391a0e-5582-5e9f-aaab-d1fbe3ab65fa'::uuid, 'a6b7676f-c562-5c60-b2a8-9386d8bd9c1c'::uuid, 'Quel est l’ordre de grandeur du rendement d’un moteur électrique ?', 'mcq', '["Plus de 90 %","Environ 30 %","Environ 50 %","Environ 70 %"]'::jsonb, 0, 'Contre 30 à 40 % pour un moteur thermique : pour la même énergie utile, il en faut bien moins.', 2),
    ('9077b8ab-2a88-55ed-bffe-824b4f166c4f'::uuid, 'a6b7676f-c562-5c60-b2a8-9386d8bd9c1c'::uuid, 'Quelle filière émet le plus de CO₂ par kWh produit ?', 'mcq', '["Le charbon","Le gaz","Le solaire","L’éolien"]'::jsonb, 0, 'Environ 820 g/kWh, contre 490 pour le gaz et quelques grammes pour l’éolien.', 3),
    ('12122ef5-ad74-50d0-9111-80bd5c2380b7'::uuid, 'a6b7676f-c562-5c60-b2a8-9386d8bd9c1c'::uuid, 'Une voiture électrique est aussi vertueuse quel que soit le pays où elle se recharge.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Son bilan dépend entièrement de l’intensité carbone du mix électrique local.', 4),
    ('b27fb555-031d-5994-8d06-09ce70d88866'::uuid, 'a6b7676f-c562-5c60-b2a8-9386d8bd9c1c'::uuid, 'Que compte une analyse du cycle de vie (ACV) ?', 'mcq', '["L’extraction, la fabrication, l’usage et la fin de vie","Seulement les émissions à l’usage","Seulement le coût financier","Seulement la durée de vie du matériel"]'::jsonb, 0, 'C’est ce qui empêche de juger une technologie sur son seul fonctionnement.', 5),
    ('d3ea27e5-7e20-54e6-97ea-928230e12857'::uuid, 'a6b7676f-c562-5c60-b2a8-9386d8bd9c1c'::uuid, 'L’électricité n’émet aucun polluant au point d’usage.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Atout majeur pour la qualité de l’air urbain — les émissions sont reportées sur la production.', 6),
    ('0f435b9d-34ba-5d73-ac26-a59b13b0cf51'::uuid, 'a6b7676f-c562-5c60-b2a8-9386d8bd9c1c'::uuid, 'Quel est le principal frein au développement de l’éolien et du solaire ?', 'mcq', '["Leur intermittence","Leur coût de production du kWh","Leurs émissions de CO₂","Leur rendement de conversion"]'::jsonb, 0, 'Il faut du stockage, du pilotage de la demande et des interconnexions pour l’absorber.', 7),
    ('6d8925d8-5082-5679-9a07-69ee3138ec1f'::uuid, 'a6b7676f-c562-5c60-b2a8-9386d8bd9c1c'::uuid, 'La sobriété consiste à améliorer le rendement des appareils.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Cela, c’est l’efficacité. La sobriété consiste à réduire l’usage lui-même.', 8),
    ('14f53061-6875-56bb-a63f-89817e69391e'::uuid, 'ddab56e3-78b0-5aad-abd4-b04856c5d3ef'::uuid, 'Quelle part de l’énergie mondiale provient encore des combustibles fossiles ?', 'mcq', '["Environ 80 %","Environ 30 %","Environ 50 %","Environ 95 %"]'::jsonb, 0, 'Charbon, pétrole et gaz dominent encore largement le mix énergétique mondial.', 1),
    ('fa58f22b-8eb5-5e3d-a518-6caa5ccc160b'::uuid, 'ddab56e3-78b0-5aad-abd4-b04856c5d3ef'::uuid, 'À quoi la hausse de température est-elle à peu près proportionnelle ?', 'mcq', '["Au CO₂ cumulé émis","Aux émissions de l’année en cours","À la population mondiale","À la surface des forêts"]'::jsonb, 0, 'C’est ce qui permet de définir un budget carbone.', 2),
    ('89ad8c02-853b-58d0-9f21-90a42a3746e7'::uuid, 'ddab56e3-78b0-5aad-abd4-b04856c5d3ef'::uuid, 'La neutralité carbone signifie n’émettre plus aucun gaz à effet de serre.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle signifie que les émissions résiduelles sont compensées par des puits de carbone.', 3),
    ('4044318a-e296-5cee-a97c-896e1d18a70a'::uuid, 'ddab56e3-78b0-5aad-abd4-b04856c5d3ef'::uuid, 'Que fixe l’Accord de Paris de 2015 ?', 'mcq', '["Contenir le réchauffement bien en dessous de 2 °C","Interdire le charbon en 2030","Créer une taxe carbone mondiale","Fermer les centrales nucléaires"]'::jsonb, 0, 'Avec l’objectif de poursuivre les efforts pour ne pas dépasser 1,5 °C.', 4),
    ('f644bdbe-41a4-53be-a49e-b1396aece09b'::uuid, 'ddab56e3-78b0-5aad-abd4-b04856c5d3ef'::uuid, 'Quel levier consiste à réduire l’usage lui-même ?', 'mcq', '["La sobriété","L’efficacité","La décarbonation","La compensation"]'::jsonb, 0, 'L’efficacité, elle, rend le même service en consommant moins.', 5),
    ('acc0818f-ed97-5083-ba0c-7b352f9ffd70'::uuid, 'ddab56e3-78b0-5aad-abd4-b04856c5d3ef'::uuid, 'Retarder la baisse des émissions ne change rien puisque le total finira par baisser.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est le cumul qui compte : chaque année de retard consomme le budget carbone restant.', 6),
    ('44234e40-85fd-59a6-b1ba-3d9be613e666'::uuid, 'ddab56e3-78b0-5aad-abd4-b04856c5d3ef'::uuid, 'Qu’est-ce qu’un puits de carbone ?', 'mcq', '["Un milieu qui absorbe plus de carbone qu’il n’en émet","Un gisement de pétrole","Un site de stockage de déchets","Une centrale à charbon équipée de filtres"]'::jsonb, 0, 'Forêts, sols et océans en sont les principaux.', 7),
    ('647e9d6c-5d60-5953-b00d-a95757426a03'::uuid, 'ddab56e3-78b0-5aad-abd4-b04856c5d3ef'::uuid, 'Brûler un combustible fossile réinjecte dans l’atmosphère un carbone stocké depuis des millions d’années.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est exactement ce qui déséquilibre le cycle du carbone.', 8),
    ('801cf359-0c9d-54a7-942c-365ed607ff92'::uuid, '52629743-9808-5afb-bf1e-621d8437dd92'::uuid, 'Que signifie qu’une filière est « pilotable » ?', 'mcq', '["Sa production peut être ajustée à la demande","Elle ne produit aucun déchet","Elle fonctionne sans combustible","Son coût est fixe"]'::jsonb, 0, 'L’hydraulique et le gaz le sont ; l’éolien et le solaire ne le sont pas.', 1),
    ('0ecde033-f6cb-5091-ba17-1ae4b2181d80'::uuid, '52629743-9808-5afb-bf1e-621d8437dd92'::uuid, 'Une filière peut être la meilleure sur tous les critères à la fois.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Émissions, coût, disponibilité, risques et emprise se contredisent : le choix est un arbitrage.', 2),
    ('fd819fb1-3918-5e80-9765-fc155bbc2530'::uuid, '52629743-9808-5afb-bf1e-621d8437dd92'::uuid, 'Combien de temps fonctionne typiquement une grande centrale électrique ?', 'mcq', '["40 à 60 ans","5 à 10 ans","15 à 20 ans","Plus de 100 ans"]'::jsonb, 0, 'Cette inertie engage un pays pour plusieurs décennies.', 3),
    ('4a4a7aef-b441-5fc9-bb12-a6a82573777b'::uuid, '52629743-9808-5afb-bf1e-621d8437dd92'::uuid, 'Pourquoi la France a-t-elle massivement investi le nucléaire ?', 'mcq', '["Pour son indépendance énergétique après 1973","Parce qu’elle manquait de charbon depuis 1900","Pour respecter l’Accord de Paris","Pour exporter de l’uranium"]'::jsonb, 0, 'Le choc pétrolier a fait de la dépendance au pétrole un risque stratégique.', 4),
    ('0b183cbd-1f5a-52f8-832e-75c8f6125643'::uuid, '52629743-9808-5afb-bf1e-621d8437dd92'::uuid, 'Que compare-t-on avec les grammes de CO₂ par kWh ?', 'mcq', '["L’intensité carbone des filières de production","Le coût du kWh","Le rendement des turbines","La durée de vie des centrales"]'::jsonb, 0, 'Ce critère doit s’entendre sur tout le cycle de vie, pas seulement à l’usage.', 5),
    ('e9b3c879-2302-5560-ba50-ab2eafac2634'::uuid, '52629743-9808-5afb-bf1e-621d8437dd92'::uuid, 'Au bac, on attend une opinion personnelle sur le nucléaire.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'On attend un raisonnement sur documents : lire les données, comparer, distinguer fait et jugement.', 6),
    ('cad125b6-5c74-5ed2-a263-bde3ff675ac3'::uuid, '52629743-9808-5afb-bf1e-621d8437dd92'::uuid, 'Qu’est-ce que le coût complet d’un kWh ?', 'mcq', '["Un coût incluant l’investissement initial, pas seulement le fonctionnement","Le prix payé par le consommateur final","Le coût du combustible seul","Le coût du transport sur le réseau"]'::jsonb, 0, 'Sans lui, on compare des filières dont les charges sont réparties très différemment dans le temps.', 7),
    ('28a5af64-1dd8-5212-b505-1571c12b927f'::uuid, '52629743-9808-5afb-bf1e-621d8437dd92'::uuid, 'La dépendance aux importations ne concerne que les combustibles.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle porte aussi sur les métaux et composants nécessaires aux éoliennes, panneaux et batteries.', 8),
    ('9254c8e9-55e2-5ebe-ad21-da0185680827'::uuid, '84b9ce5c-3a91-56ad-a992-ed1b1b68700e'::uuid, 'Quels sont les trois niveaux de la biodiversité ?', 'mcq', '["Génétique, spécifique, écosystémique","Animale, végétale, microbienne","Terrestre, marine, aérienne","Locale, nationale, mondiale"]'::jsonb, 0, 'La diversité génétique interne aux espèces compte autant que le nombre d’espèces.', 1),
    ('7d16a003-514a-5fd9-b34b-c74bcbb288a0'::uuid, '84b9ce5c-3a91-56ad-a992-ed1b1b68700e'::uuid, 'Combien d’espèces sont décrites aujourd’hui ?', 'mcq', '["Environ 2 millions","Environ 100 000","Environ 20 millions","Environ 500 000"]'::jsonb, 0, 'Sur un total estimé entre 8 et 10 millions : l’essentiel reste à décrire.', 2),
    ('8ac9b908-7714-5be7-ac17-dab13c4c3f4e'::uuid, '84b9ce5c-3a91-56ad-a992-ed1b1b68700e'::uuid, 'Quelle formule estime un effectif par capture-marquage-recapture ?', 'mcq', '["N = (n₁ × n₂) / m","N = n₁ + n₂ − m","N = m / (n₁ × n₂)","N = (n₁ + n₂) × m"]'::jsonb, 0, 'Avec m le nombre d’individus marqués retrouvés lors de la seconde capture.', 3),
    ('51a5b3fe-59fd-518b-8bb4-fc16c4a993ec'::uuid, '84b9ce5c-3a91-56ad-a992-ed1b1b68700e'::uuid, 'Cette méthode d’estimation suppose que les individus se sont remélangés entre les deux captures.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Sans remélange, l’estimation est biaisée : c’est une des limites du modèle.', 4),
    ('9ff004fc-f5c7-5f05-bbb3-de9b91411b34'::uuid, '84b9ce5c-3a91-56ad-a992-ed1b1b68700e'::uuid, 'Quelle crise biologique est la plus grave de l’histoire de la vie ?', 'mcq', '["La crise Permien-Trias","La crise Crétacé-Paléogène","La crise Ordovicien-Silurien","La crise actuelle"]'::jsonb, 0, 'Il y a environ 252 Ma : plus de 90 % des espèces marines disparaissent.', 5),
    ('cba6bd0a-eb24-5776-8226-f05a4748309e'::uuid, '84b9ce5c-3a91-56ad-a992-ed1b1b68700e'::uuid, 'Après une crise biologique, les groupes survivants se diversifient.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Ils occupent les niches libérées : les mammifères doivent leur essor à la crise de −66 Ma.', 6),
    ('e85474d8-f457-557e-8250-afd2c5b302c5'::uuid, '84b9ce5c-3a91-56ad-a992-ed1b1b68700e'::uuid, 'De combien le rythme actuel d’extinction dépasse-t-il le rythme naturel ?', 'mcq', '["De 100 à 1 000 fois","De 2 à 3 fois","De 10 000 fois","Il ne le dépasse pas"]'::jsonb, 0, 'Un rythme qui justifie de parler d’une sixième crise, d’origine humaine.', 7),
    ('d80f012b-c7f3-5133-988b-523a9774c416'::uuid, '84b9ce5c-3a91-56ad-a992-ed1b1b68700e'::uuid, 'Une espèce nombreuse est toujours à l’abri de l’extinction.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Une population génétiquement uniforme peut être décimée par un seul agent pathogène.', 8),
    ('2d8e746a-b949-50d8-adc7-9a038dc4ed37'::uuid, 'b5a0fce7-4135-52e9-a611-51e0e22477f4'::uuid, 'Dans un modèle exponentiel, qu’est-ce qui est constant ?', 'mcq', '["Le pourcentage d’augmentation","Le nombre d’individus ajoutés","L’effectif total","La capacité du milieu"]'::jsonb, 0, 'D’où un temps de doublement constant, et une courbe qui s’envole.', 1),
    ('d21b1ff8-6be8-57c4-9cff-612948867bc5'::uuid, 'b5a0fce7-4135-52e9-a611-51e0e22477f4'::uuid, 'Que représente la capacité biotique K du modèle logistique ?', 'mcq', '["L’effectif maximal que le milieu peut soutenir","Le taux de natalité","La durée de vie moyenne","Le nombre de naissances annuelles"]'::jsonb, 0, 'C’est elle qui donne à la courbe sa forme en S.', 2),
    ('246409fc-536d-5c0c-a672-f983d223e7f8'::uuid, 'b5a0fce7-4135-52e9-a611-51e0e22477f4'::uuid, 'Avec un taux de croissance de 2 % par an, une population double en environ 35 ans.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Règle des 70 : temps de doublement ≈ 70 divisé par le taux exprimé en pourcentage.', 3),
    ('ffbe536c-857f-5882-8688-aec8e779160c'::uuid, 'b5a0fce7-4135-52e9-a611-51e0e22477f4'::uuid, 'Quelle forme a la courbe du modèle logistique ?', 'mcq', '["Une courbe en S","Une droite","Une exponentielle","Une courbe en cloche"]'::jsonb, 0, 'Croissance rapide, puis ralentissement à l’approche de K, puis plateau.', 4),
    ('91d74bc9-b7f7-5c2f-94e2-7dff0eb2d394'::uuid, 'b5a0fce7-4135-52e9-a611-51e0e22477f4'::uuid, 'Quand la population mondiale a-t-elle franchi les 8 milliards ?', 'mcq', '["En 2022","En 2000","En 2010","En 1990"]'::jsonb, 0, 'Elle a été multipliée par quatre au cours du XXe siècle.', 5),
    ('82fbe5f6-f688-53eb-9dab-8e7cb5dcb3e8'::uuid, 'b5a0fce7-4135-52e9-a611-51e0e22477f4'::uuid, 'Le taux d’accroissement de la population mondiale augmente depuis 1970.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il diminue : la transition démographique ramène la natalité vers la mortalité.', 6),
    ('793812a4-7662-57c7-b8f0-7c402867ea17'::uuid, 'b5a0fce7-4135-52e9-a611-51e0e22477f4'::uuid, 'Qu’est-ce qui fait la poussée démographique lors d’une transition démographique ?', 'mcq', '["La mortalité baisse avant la natalité","La natalité augmente brutalement","Les migrations s’intensifient","L’espérance de vie stagne"]'::jsonb, 0, 'L’écart entre les deux courbes, pendant qu’il dure, fait croître la population.', 7),
    ('62d30e3c-7014-5b58-8a43-7139c9bf9088'::uuid, 'b5a0fce7-4135-52e9-a611-51e0e22477f4'::uuid, 'Un modèle démographique prédit l’avenir avec certitude.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il prolonge une hypothèse : changez le taux retenu, la trajectoire change.', 8),
    ('99b44149-361a-5d3b-9aa5-15ed9c0b90c8'::uuid, 'eed38330-b961-5f35-9689-4b92421064fe'::uuid, 'Sur quoi agit la sélection naturelle ?', 'mcq', '["Sur la fréquence des allèles dans une population","Sur les caractères acquis d’un individu","Sur la volonté des organismes","Sur les mutations, qu’elle provoque"]'::jsonb, 0, 'L’individu ne change pas : c’est la composition de la population qui se déplace.', 1),
    ('b91f967d-11aa-5ed1-92e9-cd697a2baefe'::uuid, 'eed38330-b961-5f35-9689-4b92421064fe'::uuid, 'En quelle année Darwin publie-t-il sa théorie ?', 'mcq', '["1859","1809","1900","1953"]'::jsonb, 0, '« L’Origine des espèces » y expose la sélection naturelle.', 2),
    ('fcb9a758-945c-53eb-af4c-d357ef506258'::uuid, 'eed38330-b961-5f35-9689-4b92421064fe'::uuid, 'Une bactérie devient résistante parce qu’elle est exposée à l’antibiotique.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Certaines l’étaient déjà par mutation aléatoire ; l’antibiotique ne fait que trier.', 3),
    ('442751e0-0739-5c61-b9ea-d894266b141d'::uuid, 'eed38330-b961-5f35-9689-4b92421064fe'::uuid, 'Qu’est-ce que la dérive génétique ?', 'mcq', '["Une évolution due au hasard de l’échantillonnage des allèles","Une sélection des individus les plus forts","Une mutation dirigée par le milieu","Un transfert de gènes entre espèces"]'::jsonb, 0, 'Elle est d’autant plus forte que la population est petite.', 4),
    ('d03713ec-6519-5244-b23e-560868d52405'::uuid, 'eed38330-b961-5f35-9689-4b92421064fe'::uuid, 'Quelles sont les trois conditions de la sélection naturelle ?', 'mcq', '["Variation, hérédité, différence de succès reproducteur","Mutation, migration, isolement","Adaptation, croissance, reproduction","Compétition, coopération, prédation"]'::jsonb, 0, 'Réunies, elles suffisent : le tri devient mécanique.', 5),
    ('8d733a80-16a2-5857-9b5f-cce3340faefb'::uuid, 'eed38330-b961-5f35-9689-4b92421064fe'::uuid, 'L’évolution est un progrès orienté vers des formes de plus en plus perfectionnées.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle n’a ni but ni direction : elle ajuste à un milieu qui change lui-même.', 6),
    ('7209e1fd-8b87-55d5-9459-d7ebe565c657'::uuid, 'eed38330-b961-5f35-9689-4b92421064fe'::uuid, 'Pourquoi le vaccin contre la grippe est-il reformulé chaque année ?', 'mcq', '["Parce que le virus mute rapidement","Parce que le vaccin se périme","Parce que l’immunité disparaît en un an","Parce que la souche est détruite"]'::jsonb, 0, 'Les souches dominantes changent : l’évolution se joue à l’échelle d’une saison.', 7),
    ('7b515d33-2e0e-5ab4-bd55-532b04803bdd'::uuid, 'eed38330-b961-5f35-9689-4b92421064fe'::uuid, 'La sélection artificielle repose sur un mécanisme différent de la sélection naturelle.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est le même tri : seul change le facteur qui trie, l’humain au lieu du milieu.', 8),
    ('5063f48f-ffd6-5a09-98f8-51e0eddefb52'::uuid, '2b26de16-1531-50c7-93c8-0bcb284cbc91'::uuid, 'De quel pourcentage nos génomes diffèrent-ils de celui du chimpanzé ?', 'mcq', '["Environ 1 %","Environ 10 %","Environ 25 %","Environ 0,01 %"]'::jsonb, 0, 'Notre dernier ancêtre commun vivait il y a 7 à 10 millions d’années.', 1),
    ('1af95572-9fa2-5a4a-acef-7ee4783800e8'::uuid, '2b26de16-1531-50c7-93c8-0bcb284cbc91'::uuid, 'L’humain descend du chimpanzé.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Ce sont deux branches cousines issues d’un ancêtre commun, aujourd’hui disparu.', 2),
    ('cb52e47e-9c4a-573e-bb5d-37e3b02e07b9'::uuid, '2b26de16-1531-50c7-93c8-0bcb284cbc91'::uuid, 'Quel fossile, daté d’environ 3,2 millions d’années, appartient à Australopithecus afarensis ?', 'mcq', '["Lucy","Toumaï","Cro-Magnon","L’homme de Néandertal"]'::jsonb, 0, 'Bipède, mais dotée de caractères encore adaptés au grimper.', 3),
    ('9bc1503b-81a2-5176-a2e9-3f570fab88e7'::uuid, '2b26de16-1531-50c7-93c8-0bcb284cbc91'::uuid, 'Quel indice osseux atteste la bipédie permanente ?', 'mcq', '["La position avancée du trou occipital","La longueur des bras","La taille des dents","L’épaisseur du crâne"]'::jsonb, 0, 'Le crâne est posé en équilibre sur la colonne, signe d’une station verticale.', 4),
    ('a6e6a33b-32a4-5cca-a55d-749462ccc9d2'::uuid, '2b26de16-1531-50c7-93c8-0bcb284cbc91'::uuid, 'Où ont été trouvés les plus anciens fossiles connus d’Homo sapiens ?', 'mcq', '["À Jebel Irhoud, au Maroc","En Éthiopie","En France","En Indonésie"]'::jsonb, 0, 'Datés d’environ 300 000 ans, ils confirment l’origine africaine de notre espèce.', 5),
    ('e6f351cb-5f0e-59ca-aee1-81f0834be6c6'::uuid, '2b26de16-1531-50c7-93c8-0bcb284cbc91'::uuid, 'Homo sapiens et Homo neanderthalensis ont coexisté puis se sont croisés.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Les populations non africaines actuelles portent environ 1 à 3 % d’ADN néandertalien.', 6),
    ('60f6e3f6-54ea-5f2b-94aa-7098c1c8d1df'::uuid, '2b26de16-1531-50c7-93c8-0bcb284cbc91'::uuid, 'Quel volume crânien moyen a Homo sapiens ?', 'mcq', '["Environ 1 350 cm³","Environ 400 cm³","Environ 800 cm³","Environ 2 000 cm³"]'::jsonb, 0, 'Contre environ 400 cm³ chez les australopithèques.', 7),
    ('1eb6af79-f6b1-5b2a-8e04-87af7b1c4d9e'::uuid, '2b26de16-1531-50c7-93c8-0bcb284cbc91'::uuid, 'L’évolution humaine est une ligne droite d’espèces qui se succèdent.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est un buisson : plusieurs espèces d’Homo ont vécu en même temps.', 8),
    ('a12fbe33-6ef9-5c65-bfdf-1d8424777d10'::uuid, '964bf06c-2641-5f91-b8dd-1563c053c8bd'::uuid, 'Qui écrit le premier algorithme destiné à une machine ?', 'mcq', '["Ada Lovelace","Blaise Pascal","Alan Turing","Charles Babbage"]'::jsonb, 0, 'Pour la machine analytique de Babbage, jamais achevée.', 1),
    ('8ca0e43a-7c74-52e6-b4cf-117a3bb0be38'::uuid, '964bf06c-2641-5f91-b8dd-1563c053c8bd'::uuid, 'Qu’établit Turing en 1936 avec sa machine abstraite ?', 'mcq', '["Que certains problèmes ne sont pas calculables","Que tout problème peut être résolu par une machine","Que le transistor remplacera le tube","Que les données doivent être binaires"]'::jsonb, 0, 'L’automatisation a donc des limites théoriques, pas seulement techniques.', 2),
    ('fcc6a350-b170-5b1a-89f2-94ad4054a964'::uuid, '964bf06c-2641-5f91-b8dd-1563c053c8bd'::uuid, 'Qu’observe la loi de Moore ?', 'mcq', '["Le doublement du nombre de transistors par puce environ tous les deux ans","La baisse du prix de l’électricité","L’augmentation de la vitesse d’Internet","La croissance du nombre d’utilisateurs"]'::jsonb, 0, 'C’est une observation empirique, pas une loi physique.', 3),
    ('f911c910-d5a3-52e0-9d29-7660db809193'::uuid, '964bf06c-2641-5f91-b8dd-1563c053c8bd'::uuid, 'Quel composant remplace le tube à vide à partir de 1947 ?', 'mcq', '["Le transistor","Le circuit intégré","Le microprocesseur","Le condensateur"]'::jsonb, 0, 'Plus petit, plus fiable et moins gourmand en énergie.', 4),
    ('bad409d0-9c50-5b29-821b-4e71d5df60aa'::uuid, '964bf06c-2641-5f91-b8dd-1563c053c8bd'::uuid, 'Un algorithme et un programme sont la même chose.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'L’algorithme est la méthode ; le programme en est la traduction dans un langage exécutable.', 5),
    ('72435622-850d-5b1c-8df1-af9126fa7a2d'::uuid, '964bf06c-2641-5f91-b8dd-1563c053c8bd'::uuid, 'Qu’est-ce qu’un algorithme ?', 'mcq', '["Une suite finie d’instructions non ambiguës","Un langage de programmation","Un composant électronique","Un ensemble de données"]'::jsonb, 0, 'Il doit se terminer et ne laisser aucune instruction à l’interprétation.', 6),
    ('101b2a21-b15a-580e-8cb0-41897399ae59'::uuid, '964bf06c-2641-5f91-b8dd-1563c053c8bd'::uuid, 'La Pascaline, construite en 1642, sait effectuer des additions.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est l’un des premiers dispositifs mécanisant une opération intellectuelle.', 7),
    ('1b6aa852-87f9-5dc3-b017-7469c6a68a77'::uuid, '964bf06c-2641-5f91-b8dd-1563c053c8bd'::uuid, 'Quel effet l’automatisation a-t-elle sur les capacités humaines ?', 'mcq', '["Elle en augmente certaines et en délègue d’autres","Elle les augmente toutes","Elle ne change rien","Elle les remplace intégralement"]'::jsonb, 0, 'Le transfert n’est pas neutre : il pose la question de ce qu’on garde la capacité de faire soi-même.', 8),
    ('43251af8-7c20-5a30-9196-ba60a454e3d1'::uuid, '570771b6-2df4-52a0-a2a8-3e585284dd9b'::uuid, 'Qu’est-ce qui distingue l’apprentissage automatique d’un programme classique ?', 'mcq', '["Le système ajuste ses paramètres à partir d’exemples","Il fonctionne sans électricité","Il applique des règles écrites par un humain","Il n’a pas besoin de données"]'::jsonb, 0, 'Au lieu de recevoir les règles, il les infère des données montrées.', 1),
    ('0ccd38c5-b405-5425-8a8e-1cbe6e1b7361'::uuid, '570771b6-2df4-52a0-a2a8-3e585284dd9b'::uuid, 'D’où viennent les biais d’un système d’IA ?', 'mcq', '["Des données d’entraînement","D’une intention de la machine","Du langage de programmation","De la puissance de calcul"]'::jsonb, 0, 'Le système reproduit et amplifie ce que ses données contiennent déjà.', 2),
    ('045297c5-0aca-5bd4-a553-2a29c9f24930'::uuid, '570771b6-2df4-52a0-a2a8-3e585284dd9b'::uuid, 'Un système d’intelligence artificielle comprend le sens de ce qu’il traite.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il généralise à partir des exemples vus : c’est sa force et l’origine de ses erreurs.', 3),
    ('85d2673a-1dfd-5349-ae74-d4ff5212bbe4'::uuid, '570771b6-2df4-52a0-a2a8-3e585284dd9b'::uuid, 'Quels trois ingrédients ont permis l’essor récent de l’IA ?', 'mcq', '["Données massives, puissance de calcul, algorithmes d’optimisation","Internet, satellites, fibre optique","Robotique, capteurs, batteries","Cloud, blockchain, 5G"]'::jsonb, 0, 'Aucun des trois n’aurait suffi seul.', 4),
    ('7c0ee5ec-540c-5834-9b34-76fed805bc95'::uuid, '570771b6-2df4-52a0-a2a8-3e585284dd9b'::uuid, 'Que désigne le problème de l’explicabilité ?', 'mcq', '["La difficulté à justifier la décision d’un modèle","La lenteur des calculs","Le coût des serveurs","Le manque de données disponibles"]'::jsonb, 0, 'Problème sérieux dès que la décision engage une personne : santé, justice, crédit.', 5),
    ('4a37ec2b-cc2b-5c7b-96e8-f983d1daaefe'::uuid, '570771b6-2df4-52a0-a2a8-3e585284dd9b'::uuid, 'L’entraînement des grands modèles a un coût énergétique significatif.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Électricité, eau de refroidissement et métaux : l’enjeu rejoint celui du climat.', 6),
    ('6552599c-31b4-5a19-b19b-3f0ee8cc1e61'::uuid, '570771b6-2df4-52a0-a2a8-3e585284dd9b'::uuid, 'Sur quoi porte le débat sur la responsabilité en cas d’accident de véhicule autonome ?', 'mcq', '["Sur qui répond du dommage : constructeur, programmeur ou propriétaire","Sur la vitesse maximale autorisée","Sur le prix des véhicules","Sur le nombre de capteurs"]'::jsonb, 0, 'Le droit doit désigner un responsable là où la décision a été déléguée à un système.', 7),
    ('9119bf62-4f3d-5405-b0df-96e5859b7f79'::uuid, '570771b6-2df4-52a0-a2a8-3e585284dd9b'::uuid, 'Une position argumentée sur l’IA doit s’appuyer sur des données, pas sur une crainte.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Le programme attend qu’on distingue le fait technique du choix de société.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('enseignement-scientifique');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('enseignement-scientifique')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 228 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 228 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
