-- =============================================================================
-- Studuel — Migration 237 : LES ANNALES — session 2026
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/annales/*.mjs
--    Regénérer : node scripts/seed-annales.mjs --num 237 --sessions session-2026
--
-- CE QUE LA MIGRATION APPORTE : la STRUCTURE OFFICIELLE de chaque épreuve —
-- durée, coefficient, parties, barème, et les chapitres du programme que
-- chaque partie mobilise. Elle ne reproduit AUCUN énoncé de sujet tombé :
-- ceux-là viendront session par session, dans d’autres fichiers du dossier,
-- et le modèle est prévu pour (les colonnes `session` et `center` distinguent
-- « 2026 » de « 2025 · Amérique du Nord »).
--
-- POURQUOI LA STRUCTURE D’ABORD : c’est ce qu’un élève ignore le plus
-- longtemps et ce qui lui coûte le plus cher le jour J — combien de temps par
-- partie, combien de points, ce qu’on attend exactement. Un sujet tombé se
-- comprend une fois qu’on sait ça ; l’inverse est faux.
--
-- Cette migration apporte : 17 épreuves, 22 parties.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables, et
-- l’INSERT est gardé par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 008 (subjects), 236 (exam_papers). Idempotent.
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.exam_papers (id, subject_id, level, exam, session, center, title, duration_min, coefficient, outline, position)
SELECT v.id, s.id, v.level, v.exam, v.session, v.center, v.title, v.duration_min, v.coefficient, v.outline, v.position
  FROM (VALUES
    ('729e1573-19b2-563f-a71e-e9bde28e75ac'::uuid, 'francais', '3e', 'brevet', '2026', '', 'Brevet 2026 — Français', 180, 2, '[{"title":"Compréhension, interprétation et grammaire","minutes":70,"points":50,"chapters":["Le discours rapporté","Se raconter : l''autobiographie"],"expected":"Un texte littéraire, souvent accompagné d’une image. Des questions de compréhension et d’interprétation, puis des questions de grammaire et de compétences linguistiques (classes de mots, propositions, valeurs des temps, réécriture d’un passage sous contrainte). On répond en phrases complètes, et on cite le texte."},{"title":"Dictée","minutes":20,"points":10,"chapters":["Le discours rapporté"],"expected":"Un texte d’une vingtaine de lignes, lu trois fois. Les accords (participe passé, sujet-verbe éloigné) et l’homophonie grammaticale font l’essentiel du barème. Aucun point n’est retiré sous zéro."},{"title":"Rédaction","minutes":90,"points":40,"chapters":["Se raconter : l''autobiographie","Dénoncer les travers de la société","La poésie engagée"],"expected":"Un sujet au choix : sujet d’imagination (suite de texte, récit) ou sujet de réflexion (argumentation sur une question posée par le texte). Le brouillon est compté dans les 90 minutes — un plan de cinq lignes vaut mieux qu’une page rédigée deux fois."}]'::jsonb, 1),
    ('8dfcbcf0-a274-59ec-9e41-2b22630cae00'::uuid, 'maths', '3e', 'brevet', '2026', '', 'Brevet 2026 — Mathématiques', 120, 2, '[{"title":"Automatismes — sans calculatrice","minutes":20,"points":6,"chapters":["Arithmétique","Fonctions linéaires et affines"],"expected":"Une série de questions courtes, à traiter de tête ou en deux lignes : fractions, puissances, pourcentages, ordres de grandeur, priorités opératoires. Le sujet est ramassé au bout des 20 minutes, avant la distribution de la seconde partie. La calculatrice est interdite ici, et seulement ici."},{"title":"Raisonnement et problèmes — avec calculatrice","minutes":100,"points":14,"chapters":["Théorème de Thalès","Trigonométrie","Probabilités et statistiques","Fonctions linéaires et affines"],"expected":"Cinq à sept exercices indépendants, dont un exercice d’algorithmique (Scratch) et un exercice de tâche complexe. Les exercices sont indépendants : les traiter dans l’ordre du sujet n’est pas obligatoire. Les points de la démarche sont donnés même quand le résultat est faux — d’où l’intérêt d’écrire ce qu’on cherche."}]'::jsonb, 2),
    ('a99687ce-347e-5f94-af5d-268bda8d8547'::uuid, 'histoire-geo', '3e', 'brevet', '2026', '', 'Brevet 2026 — Histoire-Géographie', 90, 1.5, '[{"title":"Analyser et comprendre des documents","minutes":50,"points":20,"chapters":["La Première Guerre mondiale","La Seconde Guerre mondiale","L''Europe entre les deux guerres"],"expected":"Un ou deux documents (texte, affiche, graphique, carte) à situer, expliquer et confronter. On attend qu’on nomme la nature et la date du document avant d’en tirer quoi que ce soit — c’est la première ligne du barème."},{"title":"Maîtriser différents langages","minutes":40,"points":20,"chapters":["La France de 1944 à nos jours","Les aires urbaines en France"],"expected":"Un développement construit d’une vingtaine de lignes, plus un travail cartographique ou une frise. Les repères (dates, lieux) sont notés pour eux-mêmes : ils s’apprennent, ils ne se déduisent pas."}]'::jsonb, 3),
    ('81390a73-2e8e-57b5-a02a-32da087efc03'::uuid, 'emc', '3e', 'brevet', '2026', '', 'Brevet 2026 — EMC', 30, 0.5, '[{"title":"Enseignement moral et civique","minutes":30,"points":10,"chapters":["Libertés et laïcité","La justice en France","Citoyenneté et engagement"],"expected":"Depuis la session 2026, l’EMC est une sous-partie AUTONOME de l’épreuve d’histoire-géographie, avec sa note et son coefficient propres : 0,5, contre 1,5 pour l’histoire-géographie. Elle se passe dans la même demi-journée, à la suite. Un ou deux documents, des questions courtes, puis une réponse argumentée sur une situation civique — on attend un avis construit, appuyé sur le droit, pas une opinion."}]'::jsonb, 4),
    ('a1a2f5a4-dca2-50a6-8fae-6aa9a8050e52'::uuid, 'physique-chimie', '3e', 'brevet', '2026', '', 'Brevet 2026 — Sciences (partie physique-chimie)', 30, 1, '[{"title":"Physique-chimie","minutes":30,"points":25,"chapters":["L''énergie et ses conversions","Puissance et énergie électriques","Ions et pH","La gravitation"],"expected":"L’épreuve de Sciences dure 1 heure et porte sur DEUX disciplines parmi trois (physique-chimie, SVT, technologie) : pour la session 2026, physique-chimie et SVT. Chaque discipline compte pour la moitié de l’épreuve, et l’ensemble vaut coefficient 2. Exercices à partir de documents, calculs simples avec unités — l’unité oubliée coûte le point."}]'::jsonb, 5),
    ('09c58b96-ab96-5378-bdba-04c4803b888f'::uuid, 'svt', '3e', 'brevet', '2026', '', 'Brevet 2026 — Sciences (partie SVT)', 30, 1, '[{"title":"Sciences de la vie et de la Terre","minutes":30,"points":25,"chapters":["Le programme génétique","L''évolution des espèces","Le système immunitaire","Santé et responsabilité","Les risques géologiques"],"expected":"Seconde moitié de l’épreuve de Sciences (1 heure, coefficient 2 pour les deux disciplines réunies). On exploite des documents pour formuler une hypothèse, l’éprouver et conclure. La conclusion doit répondre à la question posée, avec ses mots à elle — recopier le document ne vaut aucun point."}]'::jsonb, 6),
    ('1443ae08-4148-56d8-b8ad-3b40e06a7e89'::uuid, 'francais', '1re', 'bac-anticipe', '2026', '', 'Bac de français 2026 — écrit', 240, 5, '[{"title":"Commentaire de texte OU dissertation — un seul sujet au choix","minutes":240,"points":20,"chapters":["La poésie du XIXe au XXIe siècle","Le roman : parcours bac","Le théâtre : parcours bac","La littérature d''idées","Dissertation et oral du bac"],"expected":"Quatre heures pour UN sujet. Le commentaire porte sur un texte hors programme ; la dissertation porte sur une des œuvres au programme et son parcours associé — impossible à traiter sans avoir lu l’œuvre. Une heure de préparation (analyse, plan détaillé, introduction au brouillon) sur les quatre est le partage que recommandent les correcteurs."}]'::jsonb, 7),
    ('ad48be9c-461d-5dcb-9609-e29ed0bb47a3'::uuid, 'francais', '1re', 'bac-anticipe', '2026', 'Oral', 'Bac de français 2026 — oral', 20, 5, '[{"title":"Explication linéaire et question de grammaire","minutes":12,"points":12,"chapters":["Dissertation et oral du bac"],"expected":"L’examinateur choisit un texte dans le descriptif de la classe. 30 minutes de préparation, puis 12 minutes : explication linéaire du passage (8 points) et une question de grammaire posée sur ce même texte (2 points), à quoi s’ajoute la lecture à voix haute (2 points). La lecture est notée — elle se prépare."},{"title":"Présentation d’une œuvre et entretien","minutes":8,"points":8,"chapters":["Dissertation et oral du bac"],"expected":"On présente une œuvre choisie parmi celles lues dans l’année et on justifie ce choix, puis on échange avec l’examinateur. C’est la partie où l’on est jugé sur sa capacité à défendre un avis personnel, pas à réciter une fiche."}]'::jsonb, 8),
    ('e7934e96-0698-5e9a-898e-25688f372ceb'::uuid, 'maths', '1re', 'bac-anticipe', '2026', '', 'Bac 2026 — Mathématiques (épreuve anticipée)', 120, 2, '[{"title":"Épreuve écrite","minutes":120,"points":20,"chapters":["Suites numériques","Second degré","Dérivation","Produit scalaire","Probabilités conditionnelles"],"expected":"NOUVEAUTÉ DE LA SESSION 2026 : les mathématiques, jusqu’ici évaluées en contrôle continu, deviennent une épreuve anticipée du bac, passée en fin de première par TOUS les élèves — voie générale comme voie technologique. Deux heures, coefficient 2, avec un sujet adapté selon qu’on suit ou non la spécialité mathématiques."}]'::jsonb, 9),
    ('771d24fa-1207-5188-bab9-5fa8a792c454'::uuid, 'philosophie', 'Tle', 'bac', '2026', '', 'Bac 2026 — Philosophie', 240, 8, '[{"title":"Trois sujets, un seul à traiter","minutes":240,"points":20,"chapters":["La conscience","Le libre arbitre","La liberté politique","La justice et le droit","La vérité","Le travail","L’art","La technique","L’État"],"expected":"Deux sujets de dissertation et une explication de texte ; on en choisit UN. Quatre heures, coefficient 8 en voie générale (4 en voie technologique). Le choix se fait en vingt minutes, pas en une heure : le sujet qu’on sait problématiser vaut mieux que celui dont on connaît le cours. L’explication de texte ne demande pas de connaître l’auteur, mais de suivre son raisonnement pas à pas."}]'::jsonb, 10),
    ('6eb54e42-c240-5613-9dfa-cfc3c3aeab74'::uuid, 'maths', 'Tle', 'bac', '2026', '', 'Bac 2026 — Spécialité Mathématiques', 240, 16, '[{"title":"Quatre exercices, dont un au choix","minutes":240,"points":20,"chapters":["Limites de fonctions","Continuité et convexité","Logarithme népérien","Primitives et équations différentielles","Lois de probabilité"],"expected":"Quatre heures, coefficient 16. Le sujet couvre les quatre parties du programme (algèbre et géométrie, analyse, probabilités, algorithmique) : suites et récurrence, géométrie dans l’espace, limites, convexité, logarithme, primitives et calcul intégral, loi binomiale et concentration. ⚠️ Le programme de Terminale n’est aujourd’hui couvert qu’en partie dans l’app (voir docs/audit-programmes-terminale.md)."}]'::jsonb, 11),
    ('1c095a31-f66e-5ca2-9d56-b547bf4ceec9'::uuid, 'physique-chimie', 'Tle', 'bac', '2026', '', 'Bac 2026 — Spécialité Physique-Chimie', 210, 16, '[{"title":"Épreuve écrite","minutes":210,"points":20,"chapters":["Cinétique chimique","Acides et bases","Mécanique : lois de Newton","Ondes lumineuses : diffraction","Énergie et thermodynamique"],"expected":"3 h 30 d’écrit sur les quatre thèmes du programme (constitution et transformations de la matière, mouvement et interactions, l’énergie, ondes et signaux), suivies d’une épreuve PRATIQUE d’une heure (les ECE, évaluation des compétences expérimentales) passée séparément, en laboratoire. L’ensemble vaut coefficient 16."}]'::jsonb, 12),
    ('b6cc51e7-4853-547e-84b2-de6fd35758a2'::uuid, 'svt', 'Tle', 'bac', '2026', '', 'Bac 2026 — Spécialité SVT', 210, 16, '[{"title":"Épreuve écrite","minutes":210,"points":20,"chapters":["Le brassage des génomes à chaque génération : la reproduction sexuée des eucaryotes","La chronologie absolue : décrypter le temps des roches par des mesures","La plante, productrice de la matière organique grâce à la photosynthèse","Comprendre les variations climatiques","Les réflexes","Le contrôle des flux de glucose, source essentielle d’énergie des cellules musculaires"],"expected":"3 h 30 d’écrit en deux exercices : un exercice de restitution organisée de connaissances et un exercice d’exploitation de documents. S’y ajoute l’épreuve pratique d’une heure (ECE), passée en salle de travaux pratiques. Coefficient 16 pour l’ensemble."}]'::jsonb, 13),
    ('da10b44b-c8c3-576e-bf19-a4db696057b5'::uuid, 'ses', 'Tle', 'bac', '2026', '', 'Bac 2026 — Spécialité SES', 240, 16, '[{"title":"Dissertation OU épreuve composée — au choix","minutes":240,"points":20,"chapters":["Croissance et environnement","Le commerce international","Les mutations du travail","La justice sociale"],"expected":"Quatre heures, coefficient 16, et un choix à faire d’emblée : la dissertation s’appuyant sur un dossier documentaire, ou l’épreuve composée en trois parties (mobilisation de connaissances, étude d’un document, raisonnement appuyé sur un dossier). ⚠️ Le programme de Terminale n’est aujourd’hui couvert qu’en partie dans l’app (voir docs/audit-programmes-terminale.md)."}]'::jsonb, 14),
    ('c5d238ec-811b-5ec8-9783-7a165405868a'::uuid, 'hggsp', 'Tle', 'bac', '2026', '', 'Bac 2026 — Spécialité HGGSP', 240, 16, '[{"title":"Dissertation et étude critique de documents","minutes":240,"points":20,"chapters":["Environnement : exploiter, préserver","Guerres et paix","L''enjeu de la connaissance","Le patrimoine"],"expected":"Quatre heures, coefficient 16. Deux exercices : une dissertation (choix entre deux sujets) et une étude critique d’un ou deux documents. Les deux portent sur des thèmes différents du programme — impasse impossible. ⚠️ Le programme de Terminale n’est aujourd’hui couvert qu’en partie dans l’app (voir docs/audit-programmes-terminale.md)."}]'::jsonb, 15),
    ('257dc3e0-8137-5b2d-84d3-f41d3e4883f9'::uuid, 'nsi', 'Tle', 'bac', '2026', '', 'Bac 2026 — Spécialité NSI', 210, 16, '[{"title":"Épreuve écrite","minutes":210,"points":20,"chapters":["Structures de données","Bases de données et SQL","Réseaux et protocoles","Algorithmique : les graphes"],"expected":"3 h 30 d’écrit : trois exercices sur cinq proposés, couvrant structures de données, bases de données, architectures matérielles, réseaux, langages et algorithmique. S’y ajoute une épreuve PRATIQUE d’une heure sur machine (programmation en Python). Coefficient 16 pour l’ensemble."}]'::jsonb, 16),
    ('cf63176a-dc00-5d10-b9d8-23716e6361fe'::uuid, 'hlp', 'Tle', 'bac', '2026', '', 'Bac 2026 — Spécialité HLP', 240, 16, '[{"title":"Interprétation littéraire et essai philosophique","minutes":240,"points":20,"chapters":["Méthode de l’épreuve"],"expected":"Quatre heures, coefficient 16. Deux textes, un par semestre du programme (« La recherche de soi », « L’Humanité en question ») ; sur chacun, une question d’interprétation littéraire et une question d’essai philosophique. On traite les deux textes, et pour chacun on choisit l’un des deux exercices. Chaque réponse vaut 10 points."}]'::jsonb, 17)
  ) AS v(id, slug, level, exam, session, center, title, duration_min, coefficient, outline, position)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : la table porte AUSSI UNIQUE(subject_id, level, session, center),
-- qu’un rejeu déclencherait avant même la clé primaire.
ON CONFLICT DO NOTHING;

-- Contrôle : une épreuve dont la matière n’existe pas est passée à la trappe
-- silencieusement par la jointure ci-dessus. On le dit plutôt que de le taire.
DO $$
DECLARE n INT;
BEGIN
  SELECT count(*) INTO n FROM public.exam_papers;
  RAISE NOTICE 'exam_papers : % épreuve(s) en base (la migration en apporte 17).', n;
END $$;
