-- =============================================================================
-- Studuel — Migration 271 : MATHS 1re (spécialité) — LE PROGRAMME OFFICIEL (11 fiches)
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 271 --modules maths-1re
--
-- CONSTAT MESURÉ (node _ASSOCIE/sonde-chapitres.mjs 1re maths, 21/08/2026) :
-- la spécialité de Première n'avait que CINQ fiches, alignées à plat et sans
-- chapitre — « Suites numériques », « Second degré », « Dérivation », « Produit
-- scalaire », « Probabilités conditionnelles ». La fonction exponentielle, les
-- fonctions trigonométriques, l'étude des variations et des courbes, la géométrie
-- repérée et les variables aléatoires n'avaient AUCUNE entrée : cinq des onze
-- fiches du programme, dont l'exponentielle, qui commande toute la Terminale.
-- Cette migration installe les 11 fiches du programme, rangées sous ses 4
-- chapitres (algèbre, analyse, géométrie, probabilités et statistiques), et retire
-- les 5 fiches héritées qu'elles recouvrent.
-- PÉRIMÈTRE : la PREMIÈRE SEULE. Les autres niveaux gardent leurs fiches : le
-- ménage est borné au niveau 1re. La Terminale a reçu les siennes avec la 255.
-- ⚠️ CE QUI EST PERDU AU PASSAGE : les cours et les quiz des 5 fiches héritées.
-- Les 11 fiches neuves les recouvrent, avec un cours et huit questions chacune.
--
-- Cette migration apporte : 11 chapitres, 11 leçons,
-- 11 quiz et 88 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 0. Ménage ----------------------------------------------------------------
-- [maths] La colonne chapters.theme (migration 234) conditionne tout ce qui suit :
-- [maths] ce module range ses 11 fiches sous 4 chapitres, et l'INSERT écrit la colonne.
-- [maths] Elle est REPRISE ici en ADD COLUMN IF NOT EXISTS parce que la 234 n'a jamais été
-- [maths] exécutée telle quelle — sans cette reprise, la migration échouerait sur
-- [maths] "column chapters.theme does not exist", les 5 anciennes fiches déjà supprimées
-- [maths] et les 11 neuves pas encore posées : une matière vide.
-- [maths] Le GRANT n'est pas décoratif : la migration 182 a révoqué le SELECT de table sur
-- [maths] chapters (pour cacher mind_map) et ne l'a rendu que colonne par colonne. Une
-- [maths] colonne ajoutée après elle n'hérite d'aucun droit — sans lui, l'app lirait
-- [maths] "permission denied" au lieu du chapitre.
ALTER TABLE public.chapters ADD COLUMN IF NOT EXISTS theme TEXT;
GRANT SELECT (theme) ON public.chapters TO anon;
GRANT SELECT (theme) ON public.chapters TO authenticated;

-- [maths] Les 5 fiches héritées partent, au niveau 1re SEULEMENT.
-- [maths] 
-- [maths] CE MÉNAGE N'EST PAS SEULEMENT UN NETTOYAGE, IL EST NÉCESSAIRE : la fiche
-- [maths] « Dérivation » existe en base ET dans ce module. La table chapters étant
-- [maths] UNIQUE(subject_id, level, title), l'INSERT tomberait sinon sur son ON CONFLICT
-- [maths] DO NOTHING, la fiche neuve ne serait jamais posée, et sa leçon échouerait sur
-- [maths] une clé étrangère absente. Le ménage tournant AVANT les insertions, l'ancienne
-- [maths] ligne part d'abord et la neuve prend sa place.
-- [maths] 
-- [maths] LE REPÈRE EST theme IS NULL, PAS LE TITRE : le critère « pas de chapitre de
-- [maths] programme » vise exactement les cinq lignes voulues, antérieures à la colonne
-- [maths] theme, tandis que les 11 fiches neuves en portent un dès l'INSERT — le ménage ne
-- [maths] peut donc jamais mordre sur elles, ni au premier passage ni au rejeu. C'est ce
-- [maths] qui rend la collision de titre inoffensive au rejeu : la « Dérivation » neuve
-- [maths] porte le thème « Analyse » et n'est pas visée.
-- [maths] 
-- [maths] L'ordre compte : la file « À revoir » d'abord (review_items.item_id n'a PAS de
-- [maths] clé étrangère — rien ne casserait, mais le compteur « X à revoir » continuerait
-- [maths] de compter des questions disparues), puis les quiz (quizzes.lesson_id est ON
-- [maths] DELETE SET NULL : ils survivraient orphelins à leur chapitre, et toujours
-- [maths] tirables par le moteur de questions), puis les chapitres, dont les leçons
-- [maths] partent en cascade.
DELETE FROM public.review_items ri
 USING public.quiz_questions qq, public.quizzes qz, public.lessons l,
       public.chapters c, public.subjects s
 WHERE ri.item_kind = 'question'
   AND ri.item_id = qq.id
   AND qq.quiz_id = qz.id
   AND qz.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'maths'
   AND c.level = '1re'
   AND c.theme IS NULL;

DELETE FROM public.quizzes q
 USING public.lessons l, public.chapters c, public.subjects s
 WHERE q.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'maths'
   AND c.level = '1re'
   AND c.theme IS NULL;

DELETE FROM public.chapters c
 USING public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'maths'
   AND c.level = '1re'
   AND c.theme IS NULL;

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position, theme)
SELECT v.id, s.id, v.level, v.title, v.position, v.theme
  FROM (VALUES
    ('fbef6f22-850c-5e27-9bd0-ee37f32d82f4'::uuid, 'maths', '1re', 'Les suites numériques', 1, 'Algèbre'),
    ('eeebd464-f6a5-54f6-a01f-7f7e881bc51e'::uuid, 'maths', '1re', 'Les suites arithmétiques et géométriques', 2, 'Algèbre'),
    ('f1f102fd-877d-5c7c-8d82-0b9e961183bf'::uuid, 'maths', '1re', 'Le second degré', 3, 'Algèbre'),
    ('b7e9b515-1990-52f7-8eed-93a4c14d2ff0'::uuid, 'maths', '1re', 'Dérivation', 4, 'Analyse'),
    ('0f37b297-bf85-5425-869c-9a597dcbc303'::uuid, 'maths', '1re', 'Variations et courbes représentatives de fonctions', 5, 'Analyse'),
    ('e6b74138-8a5a-5b0b-8d07-3e2b40009735'::uuid, 'maths', '1re', 'Fonction exponentielle', 6, 'Analyse'),
    ('9bf31f67-44bf-5ca0-963a-d1fd6e5a0efa'::uuid, 'maths', '1re', 'Fonctions trigonométriques', 7, 'Analyse'),
    ('f58e41b0-582c-5015-a57e-cb0694e50381'::uuid, 'maths', '1re', 'Calcul vectoriel et produit scalaire', 8, 'Géométrie'),
    ('7c396887-8da2-5d89-8ea1-1f50c893ed29'::uuid, 'maths', '1re', 'Géométrie repérée', 9, 'Géométrie'),
    ('0982f49a-453d-5c24-9144-85bf56d099e7'::uuid, 'maths', '1re', 'Probabilités conditionnelles et indépendance', 10, 'Probabilité et statistiques'),
    ('576b7c68-bf81-5696-b404-8641ef5b2b0a'::uuid, 'maths', '1re', 'Variable aléatoire et loi de probabilité', 11, 'Probabilité et statistiques')
  ) AS v(id, slug, level, title, position, theme)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 1 bis. Axes du programme -------------------------------------------------
-- `chapters.theme` (migration 234) : l’intitulé du programme officiel qui
-- coiffe le chapitre. La page matière s’en sert pour grouper au lieu
-- d’aligner 28 lignes à plat. UPDATE et non INSERT : le chapitre peut déjà
-- exister (l’INSERT précédent l’aurait alors ignoré).
UPDATE public.chapters c SET theme = v.theme
  FROM (VALUES
    ('fbef6f22-850c-5e27-9bd0-ee37f32d82f4'::uuid, 'Algèbre'),
    ('eeebd464-f6a5-54f6-a01f-7f7e881bc51e'::uuid, 'Algèbre'),
    ('f1f102fd-877d-5c7c-8d82-0b9e961183bf'::uuid, 'Algèbre'),
    ('b7e9b515-1990-52f7-8eed-93a4c14d2ff0'::uuid, 'Analyse'),
    ('0f37b297-bf85-5425-869c-9a597dcbc303'::uuid, 'Analyse'),
    ('e6b74138-8a5a-5b0b-8d07-3e2b40009735'::uuid, 'Analyse'),
    ('9bf31f67-44bf-5ca0-963a-d1fd6e5a0efa'::uuid, 'Analyse'),
    ('f58e41b0-582c-5015-a57e-cb0694e50381'::uuid, 'Géométrie'),
    ('7c396887-8da2-5d89-8ea1-1f50c893ed29'::uuid, 'Géométrie'),
    ('0982f49a-453d-5c24-9144-85bf56d099e7'::uuid, 'Probabilité et statistiques'),
    ('576b7c68-bf81-5696-b404-8641ef5b2b0a'::uuid, 'Probabilité et statistiques')
  ) AS v(id, theme)
 WHERE c.id = v.id AND c.theme IS DISTINCT FROM v.theme;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('a9e47258-bc70-5d43-9376-fd58a8abb9ce', 'fbef6f22-850c-5e27-9bd0-ee37f32d82f4', 'Définir, calculer, décrire le comportement', E'Une **suite numérique** est une fonction définie sur les entiers naturels : à chaque rang n elle associe un terme u(n). On la note (u) et son terme de rang n, u(n) — jamais u × n.\n\n## Deux façons de définir une suite\n- **Explicite** : u(n) est donné directement en fonction de n. u(n) = 3n − 2 permet de calculer u(100) sans connaître les précédents.\n- **Par récurrence** : on donne le **premier terme** et une relation qui lie u(n+1) à u(n). u(0) = 5 et u(n+1) = 2 × u(n) + 1 obligent à calculer tous les termes intermédiaires.\n\n> Les deux définitions ne se valent pas à l’usage : la forme explicite donne n’importe quel terme immédiatement, la forme récurrente décrit un processus pas à pas — un capital qui évolue chaque année, une population qui se renouvelle.\n\n## Sens de variation\n- (u) est **croissante** si u(n+1) ≥ u(n) pour tout n ; **décroissante** si u(n+1) ≤ u(n).\n- La méthode standard : étudier le **signe de la différence** u(n+1) − u(n).\n- Si tous les termes sont strictement positifs, on peut aussi comparer le **quotient** u(n+1) / u(n) à 1.\n- Si la suite est définie explicitement par u(n) = f(n), le sens de variation de la fonction f sur les réels positifs se transmet à la suite.\n\n## Suites majorées, minorées, bornées\n(u) est **majorée** s’il existe un réel M tel que u(n) ≤ M pour tout n ; **minorée** s’il existe m tel que u(n) ≥ m ; **bornée** si elle est les deux à la fois.\n\n## Représenter une suite\nSur un graphique, une suite se représente par des **points isolés** de coordonnées (n ; u(n)) — jamais par une courbe continue, puisque n ne prend que des valeurs entières.\n\nPour une suite définie par récurrence, on trace la courbe de la fonction f et la droite d’équation y = x : le va-et-vient entre les deux, en escalier ou en escargot, donne à voir le comportement des termes.', 1),
  ('ce231c53-a54b-56d0-8581-6468d6fbbeeb', 'eeebd464-f6a5-54f6-a01f-7f7e881bc51e', 'Deux modèles, deux croissances', E'Deux familles de suites décrivent l’essentiel des évolutions modélisées en Première.\n\n## La suite arithmétique\nOn passe d’un terme au suivant en **ajoutant** toujours le même nombre, la **raison** r :\n\nu(n+1) = u(n) + r\n\nForme explicite, à partir du rang 0 : **u(n) = u(0) + n × r**. Plus généralement, u(n) = u(p) + (n − p) × r.\n\nElle est **croissante si r > 0**, décroissante si r < 0. Sa représentation graphique est faite de points **alignés** : la croissance est **linéaire**.\n\nSomme des premiers termes : 1 + 2 + … + n = n × (n + 1) / 2.\n\n## La suite géométrique\nOn passe d’un terme au suivant en **multipliant** par un même nombre, la **raison** q :\n\nu(n+1) = u(n) × q\n\nForme explicite : **u(n) = u(0) × q puissance n**.\n\nPour u(0) > 0 : la suite est **croissante si q > 1**, décroissante si 0 < q < 1, constante si q = 1. La croissance est **exponentielle** — elle finit toujours par dépasser n’importe quelle croissance linéaire.\n\nSomme des premiers termes, pour q ≠ 1 :\n\n1 + q + q² + … + q(n) = (1 − q puissance (n+1)) / (1 − q)\n\n## Reconnaître laquelle\n- Une **différence** constante entre termes consécutifs : arithmétique.\n- Un **quotient** constant : géométrique.\n\n> Le cas concret le plus utile : une évolution de **t %** par période revient à multiplier par le **coefficient multiplicateur** 1 + t / 100. Une hausse de 5 % par an, c’est une suite géométrique de raison 1,05 ; une baisse de 5 %, de raison 0,95.\n\nAttention au piège : deux baisses de 10 % ne font pas une baisse de 20 %, mais 0,90 × 0,90 = 0,81, soit une baisse de 19 %.', 1),
  ('cde48910-2f2d-55e4-bc79-3a0cf0e61196', 'f1f102fd-877d-5c7c-8d82-0b9e961183bf', 'Discriminant, racines et signe', E'Un **trinôme du second degré** s’écrit f(x) = a x² + b x + c, avec a ≠ 0. Sa courbe est une **parabole**, tournée vers le haut si a > 0, vers le bas si a < 0.\n\n## Le discriminant\nΔ = b² − 4 a c\n\nIl décide de tout :\n- **Δ > 0** : deux racines distinctes, x1 = (−b − √Δ) / (2a) et x2 = (−b + √Δ) / (2a). La parabole coupe l’axe des abscisses en deux points.\n- **Δ = 0** : une racine double, x0 = −b / (2a). La parabole est tangente à l’axe.\n- **Δ < 0** : aucune racine réelle. La parabole ne coupe pas l’axe des abscisses.\n\n## Les formes du trinôme\n- **développée** : a x² + b x + c, commode pour lire c (l’ordonnée à l’origine) et calculer Δ ;\n- **factorisée**, quand Δ ≥ 0 : a (x − x1)(x − x2), commode pour lire les racines ;\n- **canonique** : a (x − α)² + β, avec α = −b / (2a) et β = f(α), commode pour lire le **sommet** de la parabole, de coordonnées (α ; β).\n\n> Choisir la bonne forme selon la question posée fait gagner plus de temps que n’importe quel calcul astucieux.\n\n## Signe du trinôme\nLa règle tient en une phrase : **le trinôme est du signe de a partout, sauf entre les racines**.\n- Si Δ < 0, il est du signe de a sur tout l’ensemble des réels — il ne s’annule jamais.\n- Si Δ = 0, il est du signe de a partout, et s’annule en x0.\n- Si Δ > 0, il est du signe **opposé** à celui de a strictement entre x1 et x2.\n\n## Variations et extremum\nLe sommet donne l’extremum : si a > 0, f admet un **minimum** en α ; si a < 0, un **maximum**. La parabole est symétrique par rapport à la droite verticale d’équation x = α.\n\nDeux relations utiles : la somme des racines vaut −b / a, leur produit c / a.', 1),
  ('26b82b25-e998-5a5a-bac7-88f376aea0a1', 'b7e9b515-1990-52f7-8eed-93a4c14d2ff0', 'Nombre dérivé, tangente et formules', E'Le **nombre dérivé** de f en a, noté f’(a), est la limite du taux de variation quand h tend vers 0 :\n\nf’(a) = limite de [f(a + h) − f(a)] / h\n\nIl se lit géométriquement : c’est le **coefficient directeur de la tangente** à la courbe au point d’abscisse a.\n\n## Équation de la tangente\ny = f’(a) × (x − a) + f(a)\n\nCette formule tombe à chaque devoir. Elle se retient en la lisant : une droite de coefficient directeur f’(a) qui passe par le point (a ; f(a)).\n\n## Les dérivées à connaître\n- f(x) = k (constante) → f’(x) = 0\n- f(x) = x → f’(x) = 1\n- f(x) = x² → f’(x) = 2x\n- f(x) = x puissance n → f’(x) = n × x puissance (n − 1)\n- f(x) = 1 / x → f’(x) = −1 / x²\n- f(x) = √x → f’(x) = 1 / (2√x), pour x > 0\n\n## Les opérations\n- (u + v)’ = u’ + v’\n- (k × u)’ = k × u’\n- **(u × v)’ = u’v + uv’** — le produit des dérivées serait faux\n- (1 / v)’ = −v’ / v²\n- **(u / v)’ = (u’v − uv’) / v²** — attention à l’ordre au numérateur, la soustraction n’est pas commutative\n\n## Dérivée et variations\nLe lien fondamental, celui qui donne tout son intérêt à la dérivation :\n- f’ **positive** sur un intervalle : f est **croissante** sur cet intervalle ;\n- f’ **négative** : f est **décroissante** ;\n- f’ qui **s’annule en changeant de signe** : f admet un **extremum local** en ce point.\n\n> Attention à la réciproque : f’ peut s’annuler sans qu’il y ait d’extremum. C’est le cas de f(x) = x³ en 0, où la tangente est horizontale mais la fonction reste croissante.', 1),
  ('458a0715-8326-56e3-845f-439f24e17973', '0f37b297-bf85-5425-869c-9a597dcbc303', 'Du tableau de signes au tracé', E'Étudier une fonction, c’est suivre un enchaînement fixe. Le respecter fait gagner des points même quand un calcul échoue.\n\n## La méthode\n1. Déterminer l’**ensemble de définition** : ce qui interdit une valeur, c’est une division par zéro ou une racine carrée d’un nombre négatif.\n2. Calculer **f’(x)**, puis la factoriser autant que possible.\n3. Étudier le **signe de f’(x)** : c’est ici que servent le second degré et les règles de signe d’un produit ou d’un quotient.\n4. Dresser le **tableau de variations**, en y portant les valeurs de f aux bornes et aux extremums.\n5. Conclure : extremums, éventuelles solutions d’une équation, tracé.\n\n## Extremums\nUn extremum **local** est une valeur maximale ou minimale sur un intervalle autour du point. Un extremum **global** l’est sur tout l’ensemble de définition. Un extremum local n’est pas nécessairement global — un devoir attend souvent la distinction.\n\n## Lecture graphique\n- f(a) se lit en **ordonnée** au point d’abscisse a ;\n- résoudre f(x) = k revient à chercher les **abscisses des points d’intersection** avec la droite horizontale d’équation y = k ;\n- résoudre f(x) > 0 revient à repérer les intervalles où la **courbe est au-dessus** de l’axe des abscisses ;\n- les tangentes **horizontales** signalent les points où f’ s’annule.\n\n## Le théorème des valeurs intermédiaires\nSi f est **continue** et **strictement monotone** sur un intervalle [a ; b], et si k est compris entre f(a) et f(b), alors l’équation f(x) = k admet une **unique** solution dans cet intervalle.\n\n> On l’encadre ensuite par **balayage** à la calculatrice, chiffre après chiffre. Attention : sans stricte monotonie, le théorème garantit l’existence d’une solution mais non son unicité.\n\n## Parité et symétries\nUne fonction **paire** vérifie f(−x) = f(x) : sa courbe est symétrique par rapport à l’axe des ordonnées. Une fonction **impaire** vérifie f(−x) = −f(x) : sa courbe est symétrique par rapport à l’origine. Le repérer permet de n’étudier que la moitié du domaine.', 1),
  ('9b24a3fc-131e-5dee-86b2-83ebeb664649', 'e6b74138-8a5a-5b0b-8d07-3e2b40009735', 'La fonction qui est sa propre dérivée', E'La **fonction exponentielle**, notée exp ou x → e puissance x, est l’unique fonction dérivable sur l’ensemble des réels telle que :\n\nf’ = f et f(0) = 1\n\nC’est cette propriété qui la fait apparaître partout où une grandeur varie proportionnellement à elle-même : intérêts composés, désintégration radioactive, croissance d’une population, refroidissement d’un corps.\n\n## Propriétés algébriques\nPour tous réels a et b :\n- e puissance (a + b) = e puissance a × e puissance b\n- e puissance (−a) = 1 / (e puissance a)\n- e puissance (a − b) = e puissance a / e puissance b\n- (e puissance a) puissance n = e puissance (n × a)\n\nAutrement dit : **l’exponentielle transforme les sommes en produits**. C’est la propriété qui organise tous les calculs du chapitre.\n\n## Signe, variations, limites\n- e puissance x est **strictement positive** pour tout réel x : l’équation e puissance x = 0 n’a **aucune** solution, et le signe d’un produit contenant une exponentielle ne dépend jamais d’elle.\n- Sa dérivée étant elle-même, donc positive, la fonction est **strictement croissante** sur tout l’ensemble des réels.\n- e puissance 0 = 1 et e ≈ 2,718.\n- Quand x tend vers moins l’infini, e puissance x tend vers 0 ; quand x tend vers plus l’infini, elle tend vers plus l’infini, et **plus vite que n’importe quelle puissance de x**.\n\n## Équations et inéquations\nLa stricte croissance donne les équivalences :\n\ne puissance a = e puissance b équivaut à a = b\ne puissance a < e puissance b équivaut à a < b\n\nLe passage à l’exposant **conserve l’ordre** — contrairement à ce qui se passe quand on multiplie par un nombre négatif.\n\n## Dérivée composée\nLa formule à retenir, et le piège le plus fréquent :\n\n(e puissance u)’ = u’ × e puissance u\n\nAinsi la dérivée de e puissance (3x) vaut 3 e puissance (3x), et non e puissance (3x). Oublier le facteur u’ coûte le résultat de tout un exercice.', 1),
  ('95efa03d-890b-5da2-b29d-2cf993c54657', '9bf31f67-44bf-5ca0-963a-d1fd6e5a0efa', 'Cercle trigonométrique, cosinus et sinus', E'Le **cercle trigonométrique** est le cercle de rayon 1 centré à l’origine, orienté dans le sens direct (antihoraire). À tout réel x on associe le point M du cercle obtenu en parcourant une longueur x depuis le point de coordonnées (1 ; 0).\n\n## Cosinus et sinus\nLes coordonnées de M sont (cos x ; sin x). Il en découle immédiatement :\n- −1 ≤ cos x ≤ 1 et −1 ≤ sin x ≤ 1 ;\n- **cos² x + sin² x = 1**, qui n’est que le théorème de Pythagore dans un cercle de rayon 1.\n\n## Le radian\nLe **radian** mesure un angle par la longueur d’arc qu’il intercepte sur le cercle de rayon 1. Un tour complet vaut 2π radians, soit 360°. La conversion se fait par proportionnalité : π radians valent 180°.\n\nLes valeurs remarquables à connaître par cœur :\n- cos 0 = 1 et sin 0 = 0\n- cos(π/6) = √3 / 2 et sin(π/6) = 1/2\n- cos(π/4) = sin(π/4) = √2 / 2\n- cos(π/3) = 1/2 et sin(π/3) = √3 / 2\n- cos(π/2) = 0 et sin(π/2) = 1\n\n## Périodicité et parité\nLes deux fonctions sont **périodiques de période 2π** : cos(x + 2π) = cos x. Il suffit donc de les étudier sur un intervalle de longueur 2π.\n\n- **cosinus est paire** : cos(−x) = cos x, courbe symétrique par rapport à l’axe des ordonnées ;\n- **sinus est impaire** : sin(−x) = −sin x, courbe symétrique par rapport à l’origine.\n\n## Angles associés\n- cos(π − x) = −cos x et sin(π − x) = sin x\n- cos(π + x) = −cos x et sin(π + x) = −sin x\n\nLe cercle les redonne tous : plutôt que de les apprendre, on les **relit** sur une figure, ce qui évite les erreurs de signe.\n\n## Dérivées\n(sin x)’ = cos x et (cos x)’ = −sin x\n\nLe signe moins sur la dérivée du cosinus se retrouve sur la courbe : le cosinus décroît là où le sinus est positif.', 1),
  ('5748579e-4af5-58e8-80ac-e98c14cebb44', 'f58e41b0-582c-5015-a57e-cb0694e50381', 'Quatre expressions, une seule notion', E'Le **produit scalaire** de deux vecteurs est un **nombre réel**, non un vecteur. C’est la première chose à ne pas confondre.\n\n## Les quatre expressions\nSelon les données de l’énoncé, on choisit celle qui se calcule :\n1. **Avec les coordonnées**, dans un repère orthonormé : u(x ; y) et v(x’ ; y’) donnent u · v = x x’ + y y’.\n2. **Avec les normes et l’angle** : u · v = ||u|| × ||v|| × cos θ.\n3. **Par projection orthogonale** : on projette l’un des vecteurs sur la direction de l’autre, et l’on multiplie les mesures algébriques.\n4. **Avec les normes seules** : u · v = ½ (||u + v||² − ||u||² − ||v||²).\n\n> Savoir passer de l’une à l’autre est l’essentiel du chapitre : c’est le choix de l’expression, plus que le calcul, qui décide de la difficulté d’un exercice.\n\n## Propriétés\n- **Symétrie** : u · v = v · u\n- **Bilinéarité** : u · (v + w) = u · v + u · w, et (k u) · v = k (u · v)\n- u · u = ||u||², ce qui donne la norme à partir du produit scalaire.\n\n## L’orthogonalité\nDeux vecteurs **non nuls** sont orthogonaux **si et seulement si** leur produit scalaire est nul. C’est le critère le plus utilisé du chapitre : il transforme une question de géométrie en un calcul.\n\nEn coordonnées : x x’ + y y’ = 0.\n\n## Les applications\n- **Longueurs et angles** : la deuxième expression donne cos θ, donc l’angle.\n- **Théorème d’Al-Kashi** : dans un triangle quelconque, a² = b² + c² − 2 b c cos A. C’est la généralisation du théorème de Pythagore, qu’on retrouve pour A = 90°, puisque cos 90° = 0.\n- **Lieux de points**, ensembles de points vérifiant une relation vectorielle : cercles, droites, médiatrices.', 1),
  ('775ca120-5dc1-5f1c-89af-4cce639f4be0', '7c396887-8da2-5d89-8ea1-1f50c893ed29', 'Droites, cercles et équations', E'La géométrie repérée traduit les figures en **équations** : ce qui se démontrait par construction se calcule.\n\n## Droites\n- **Équation cartésienne** : a x + b y + c = 0, avec a et b non tous deux nuls. Un **vecteur directeur** est u(−b ; a) ; un **vecteur normal** est n(a ; b).\n- **Équation réduite** : y = m x + p, où m est le **coefficient directeur** et p l’ordonnée à l’origine. Elle ne convient pas aux droites verticales, d’équation x = k.\n\nLe coefficient directeur d’une droite passant par A(x(A) ; y(A)) et B(x(B) ; y(B)) vaut :\n\nm = (y(B) − y(A)) / (x(B) − x(A))\n\n## Parallélisme et orthogonalité\n- Deux droites sont **parallèles** si leurs coefficients directeurs sont égaux, ou si leurs vecteurs directeurs sont **colinéaires** (déterminant nul : x y’ − y x’ = 0).\n- Deux droites sont **perpendiculaires** si le produit de leurs coefficients directeurs vaut **−1**, ou si leurs vecteurs directeurs ont un produit scalaire nul.\n\n## Cercles\nLe cercle de centre Ω(a ; b) et de rayon r a pour équation :\n\n(x − a)² + (y − b)² = r²\n\nUne équation développée du type x² + y² + α x + β y + γ = 0 se ramène à cette forme en **complétant les carrés** — la même technique que la forme canonique du second degré. Si le membre obtenu à droite est négatif, l’ensemble est **vide** ; s’il est nul, il se réduit à un point.\n\nAutre caractérisation utile : le cercle de **diamètre** [AB] est l’ensemble des points M tels que le produit scalaire des vecteurs MA et MB soit nul — c’est-à-dire tels que l’angle en M soit droit.\n\n## Les formules de base\n- Milieu de [AB] : ((x(A) + x(B)) / 2 ; (y(A) + y(B)) / 2)\n- Distance AB = √((x(B) − x(A))² + (y(B) − y(A))²)\n\n> Beaucoup de problèmes se résolvent en traduisant l’énoncé en équations, puis en résolvant un système — sans figure, ou avec une figure qui ne sert qu’à contrôler la vraisemblance.', 1),
  ('a969cfd6-63f4-55b2-bc7b-0ae1b463389a', '0982f49a-453d-5c24-9144-85bf56d099e7', 'Arbre pondéré et probabilités totales', E'La **probabilité conditionnelle** de B sachant A, notée P(A)(B), est la probabilité que B se réalise **une fois qu’on sait que A est réalisé**. Pour P(A) ≠ 0 :\n\nP(A)(B) = P(A inter B) / P(A)\n\nd’où la relation la plus utilisée du chapitre :\n\nP(A inter B) = P(A) × P(A)(B)\n\n## L’arbre pondéré\nC’est l’outil du chapitre, et trois règles le gouvernent :\n- la somme des probabilités des branches **issues d’un même nœud** vaut 1 ;\n- la probabilité d’un **chemin** est le **produit** des probabilités portées par ses branches ;\n- la probabilité d’un **événement** est la **somme** des probabilités des chemins qui y mènent.\n\n> Les branches du deuxième niveau portent des probabilités **conditionnelles** : c’est là que se joue la lecture correcte d’un énoncé.\n\n## La formule des probabilités totales\nSi A et son contraire partitionnent l’univers :\n\nP(B) = P(A inter B) + P(A barre inter B) = P(A) × P(A)(B) + P(A barre) × P(A barre)(B)\n\nC’est exactement la troisième règle de l’arbre, écrite en formule.\n\n## L’indépendance\nA et B sont **indépendants** si la réalisation de l’un ne change pas la probabilité de l’autre :\n\nP(A inter B) = P(A) × P(B), ou de façon équivalente P(A)(B) = P(B)\n\nDeux confusions à éviter :\n- indépendants ≠ **incompatibles**. Deux événements incompatibles de probabilités non nulles ne sont jamais indépendants — si l’un se réalise, l’autre devient impossible, donc sa probabilité change ;\n- l’indépendance se **démontre** par le calcul ; elle ne se devine pas à l’intuition.\n\n## Ce qu’il faut savoir inverser\nBeaucoup d’exercices demandent P(B)(A) alors que l’énoncé donne P(A)(B) — un test médical dont on connaît la fiabilité, et dont on cherche la probabilité d’être malade sachant le test positif. On y répond en calculant P(A inter B) et P(B), puis en formant le quotient.', 1),
  ('3f35456e-4ea1-5355-abef-8358f14d0b07', '576b7c68-bf81-5696-b404-8641ef5b2b0a', 'Espérance, variance, écart type', E'Une **variable aléatoire** X associe un **nombre réel** à chaque issue d’une expérience aléatoire. Elle transforme un univers d’issues quelconques en un ensemble de valeurs numériques, sur lesquelles on peut calculer.\n\n## La loi de probabilité\nDonner la **loi de X**, c’est donner toutes ses valeurs possibles et la probabilité de chacune. On la présente en tableau. Contrôle obligatoire : **la somme des probabilités vaut 1**.\n\n## L’espérance\nE(X) = somme des x(i) × P(X = x(i))\n\nC’est la **valeur moyenne** que prendrait X sur un très grand nombre de répétitions. Interprétation à savoir formuler : dans un jeu d’argent, une espérance de gain **positive** est favorable au joueur, **négative** favorable à l’organisateur, **nulle** rend le jeu **équitable**.\n\n> L’espérance n’est pas forcément une valeur atteignable : l’espérance du lancer d’un dé équilibré vaut 3,5.\n\n## Variance et écart type\nV(X) = somme des x(i)² × P(X = x(i)) − [E(X)]²\n\nσ(X) = √(V(X))\n\nLa variance mesure la **dispersion** autour de l’espérance ; l’**écart type** la ramène à l’unité de X, ce qui le rend interprétable. Deux variables de même espérance peuvent avoir des écarts types très différents : la même moyenne ne dit rien du risque.\n\n## Les propriétés\nPour tous réels a et b :\n- E(aX + b) = a E(X) + b\n- V(aX + b) = a² V(X) — le **b disparaît**, car une translation ne change pas la dispersion, et le a est **au carré**.\n\n## L’échantillonnage\nSi l’on répète n fois la même expérience de façon indépendante, la moyenne des résultats se rapproche de l’espérance quand n grandit : c’est la **loi des grands nombres**. C’est elle qui justifie les simulations, et qui explique pourquoi un casino ne perd pas sur le long terme même s’il perd sur un coup.', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('a59d63eb-1bae-5ea0-aa35-ae4481d3e359'::uuid, 'Quiz — Définir, calculer, décrire le comportement', 'Maths', '1re', 'Les suites numériques', 'a9e47258-bc70-5d43-9376-fd58a8abb9ce'::uuid),
    ('d1abd593-d0a4-5165-bda5-7edfee053cdb'::uuid, 'Quiz — Deux modèles, deux croissances', 'Maths', '1re', 'Les suites arithmétiques et géométriques', 'ce231c53-a54b-56d0-8581-6468d6fbbeeb'::uuid),
    ('ac7fdb4e-445d-5603-bd6a-84017b7a744a'::uuid, 'Quiz — Discriminant, racines et signe', 'Maths', '1re', 'Le second degré', 'cde48910-2f2d-55e4-bc79-3a0cf0e61196'::uuid),
    ('81ffad8a-09fb-54fc-9dd4-e3bea97449e8'::uuid, 'Quiz — Nombre dérivé, tangente et formules', 'Maths', '1re', 'Dérivation', '26b82b25-e998-5a5a-bac7-88f376aea0a1'::uuid),
    ('e1615c80-440e-590c-90ff-928640e5ce43'::uuid, 'Quiz — Du tableau de signes au tracé', 'Maths', '1re', 'Variations et courbes représentatives de fonctions', '458a0715-8326-56e3-845f-439f24e17973'::uuid),
    ('afb3f71c-d5c1-5657-9821-ef365e07e69a'::uuid, 'Quiz — La fonction qui est sa propre dérivée', 'Maths', '1re', 'Fonction exponentielle', '9b24a3fc-131e-5dee-86b2-83ebeb664649'::uuid),
    ('68827c48-d75c-58de-b861-01079b36ce57'::uuid, 'Quiz — Cercle trigonométrique, cosinus et sinus', 'Maths', '1re', 'Fonctions trigonométriques', '95efa03d-890b-5da2-b29d-2cf993c54657'::uuid),
    ('fe904eb8-85c5-5586-9673-41d3a48958f6'::uuid, 'Quiz — Quatre expressions, une seule notion', 'Maths', '1re', 'Calcul vectoriel et produit scalaire', '5748579e-4af5-58e8-80ac-e98c14cebb44'::uuid),
    ('786064c9-635c-5ce5-b8b7-132c4805a62e'::uuid, 'Quiz — Droites, cercles et équations', 'Maths', '1re', 'Géométrie repérée', '775ca120-5dc1-5f1c-89af-4cce639f4be0'::uuid),
    ('818f0273-d748-55c6-ab3f-3023ece55895'::uuid, 'Quiz — Arbre pondéré et probabilités totales', 'Maths', '1re', 'Probabilités conditionnelles et indépendance', 'a969cfd6-63f4-55b2-bc7b-0ae1b463389a'::uuid),
    ('edff98fe-76fb-54c1-ac8f-eeffa181e891'::uuid, 'Quiz — Espérance, variance, écart type', 'Maths', '1re', 'Variable aléatoire et loi de probabilité', '3f35456e-4ea1-5355-abef-8358f14d0b07'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('cd6921c1-c930-54c0-8c84-9fa46ecb1056'::uuid, 'a59d63eb-1bae-5ea0-aa35-ae4481d3e359'::uuid, 'Une suite numérique est une fonction définie sur…', 'mcq', '["les entiers naturels","les réels","les rationnels","un intervalle de réels"]'::jsonb, 0, 'C’est pourquoi on la représente par des points isolés.', 1),
    ('c214b4b9-ac6e-5af2-85e9-72722cd7a08f'::uuid, 'a59d63eb-1bae-5ea0-aa35-ae4481d3e359'::uuid, 'Que faut-il pour définir une suite par récurrence ?', 'mcq', '["Un premier terme et une relation entre u(n+1) et u(n)","Une expression de u(n) en fonction de n","Le sens de variation","La limite de la suite"]'::jsonb, 0, 'Sans premier terme, la relation ne suffit pas à déterminer la suite.', 2),
    ('b2ef1395-14dd-59fc-a5b3-0c082d59ca62'::uuid, 'a59d63eb-1bae-5ea0-aa35-ae4481d3e359'::uuid, 'Comment détermine-t-on le sens de variation d’une suite ?', 'mcq', '["En étudiant le signe de u(n+1) − u(n)","En calculant u(0)","En traçant la courbe de f","En comparant u(n) à n"]'::jsonb, 0, 'Pour une suite à termes strictement positifs, le quotient comparé à 1 marche aussi.', 3),
    ('c7e779ab-76f8-5760-b336-23525c357fc9'::uuid, 'a59d63eb-1bae-5ea0-aa35-ae4481d3e359'::uuid, 'Une suite se représente graphiquement par une courbe continue.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Par des POINTS ISOLÉS : n ne prend que des valeurs entières.', 4),
    ('fd004a41-7584-5a0a-9f4f-a65220e25f27'::uuid, 'a59d63eb-1bae-5ea0-aa35-ae4481d3e359'::uuid, 'Qu’est-ce qu’une suite bornée ?', 'mcq', '["Une suite à la fois majorée et minorée","Une suite croissante","Une suite qui a une limite","Une suite définie par récurrence"]'::jsonb, 0, 'Ses termes restent tous dans un intervalle fixé.', 5),
    ('56c1fb47-0e49-5154-97ab-69dea8a8e180'::uuid, 'a59d63eb-1bae-5ea0-aa35-ae4481d3e359'::uuid, 'Avec une définition explicite, peut-on calculer u(100) sans calculer les termes précédents ?', 'mcq', '["Oui, directement","Non, jamais","Seulement si la suite est croissante","Seulement si la suite est arithmétique"]'::jsonb, 0, 'C’est le principal avantage de la forme explicite.', 6),
    ('30989456-1516-5b48-a522-e1cc798ed1a8'::uuid, 'a59d63eb-1bae-5ea0-aa35-ae4481d3e359'::uuid, 'Si u(n) = f(n) avec f croissante sur les réels positifs, alors la suite est croissante.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Le sens de variation de la fonction se transmet à la suite.', 7),
    ('d1049968-ebf2-591b-81fe-b0b2f2a0d58f'::uuid, 'a59d63eb-1bae-5ea0-aa35-ae4481d3e359'::uuid, 'Que note u(n) ?', 'mcq', '["Le terme de rang n de la suite","Le produit de u par n","La somme des n premiers termes","La limite de la suite"]'::jsonb, 0, 'La confusion avec un produit est l’erreur de notation la plus fréquente.', 8),
    ('5bb83515-aeec-5701-bec4-8c2121a37477'::uuid, 'd1abd593-d0a4-5165-bda5-7edfee053cdb'::uuid, 'Comment reconnaît-on une suite géométrique ?', 'mcq', '["Le quotient de deux termes consécutifs est constant","La différence de deux termes consécutifs est constante","Les termes sont alignés graphiquement","La suite est croissante"]'::jsonb, 0, 'La différence constante, elle, caractérise une suite arithmétique.', 1),
    ('30061e77-8a19-5c25-a258-f3ff7031193d'::uuid, 'd1abd593-d0a4-5165-bda5-7edfee053cdb'::uuid, 'Quelle est la forme explicite d’une suite arithmétique de premier terme u(0) ?', 'mcq', '["u(n) = u(0) + n × r","u(n) = u(0) × r puissance n","u(n) = u(0) × n + r","u(n) = u(0) + r puissance n"]'::jsonb, 0, 'La croissance est linéaire : les points sont alignés.', 2),
    ('e765edb6-af10-526a-9cc8-5bbf2f592d0f'::uuid, 'd1abd593-d0a4-5165-bda5-7edfee053cdb'::uuid, 'Une suite géométrique de raison 0,95 et de premier terme positif est décroissante.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Une raison strictement comprise entre 0 et 1 fait décroître la suite.', 3),
    ('100ffa55-e802-5b69-8114-83040c30276e'::uuid, 'd1abd593-d0a4-5165-bda5-7edfee053cdb'::uuid, 'Par quel coefficient multiplie-t-on pour une hausse de 5 % ?', 'mcq', '["1,05","0,05","5","0,95"]'::jsonb, 0, 'Le coefficient multiplicateur vaut 1 + t / 100.', 4),
    ('0735c9f6-5a87-594c-8ae8-e877291cfeae'::uuid, 'd1abd593-d0a4-5165-bda5-7edfee053cdb'::uuid, 'Deux baisses successives de 10 % équivalent à une baisse de 20 %.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, '0,90 × 0,90 = 0,81, soit une baisse de 19 %.', 5),
    ('c3d668a2-30b1-5a6a-bae0-959c325256be'::uuid, 'd1abd593-d0a4-5165-bda5-7edfee053cdb'::uuid, 'Quelle est la forme explicite d’une suite géométrique de premier terme u(0) ?', 'mcq', '["u(n) = u(0) × q puissance n","u(n) = u(0) + n × q","u(n) = q × n","u(n) = u(0) puissance n"]'::jsonb, 0, 'La croissance y est exponentielle.', 6),
    ('4b9e3a0e-fb34-5731-b787-5370c74a9e5c'::uuid, 'd1abd593-d0a4-5165-bda5-7edfee053cdb'::uuid, 'Combien vaut la somme 1 + 2 + … + n ?', 'mcq', '["n × (n + 1) / 2","n² / 2","n × (n − 1)","2n + 1"]'::jsonb, 0, 'C’est la somme des n premiers entiers naturels non nuls.', 7),
    ('58be3dea-4a57-5cb2-980d-df23f35eb52b'::uuid, 'd1abd593-d0a4-5165-bda5-7edfee053cdb'::uuid, 'Une croissance exponentielle finit toujours par dépasser une croissance linéaire.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Quels que soient les coefficients de départ, si la raison est supérieure à 1.', 8),
    ('fc3188e2-30ec-526f-ac9d-7c33911a4732'::uuid, 'ac7fdb4e-445d-5603-bd6a-84017b7a744a'::uuid, 'Quelle est l’expression du discriminant ?', 'mcq', '["Δ = b² − 4ac","Δ = b² + 4ac","Δ = 4ac − b²","Δ = b − 4ac"]'::jsonb, 0, 'Son signe décide du nombre de racines réelles.', 1),
    ('a0a51864-e5f7-5b00-8106-478e0da2bd1c'::uuid, 'ac7fdb4e-445d-5603-bd6a-84017b7a744a'::uuid, 'Que peut-on dire d’un trinôme dont le discriminant est négatif ?', 'mcq', '["Il ne s’annule jamais et garde le signe de a","Il a deux racines","Il est toujours positif","Sa courbe est une droite"]'::jsonb, 0, 'La parabole ne coupe pas l’axe des abscisses.', 2),
    ('45b8cad1-e94b-54ff-9020-6b0c74c48670'::uuid, 'ac7fdb4e-445d-5603-bd6a-84017b7a744a'::uuid, 'Un trinôme est du signe de a sauf entre ses racines.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est la règle de signe à retenir, valable quand Δ > 0.', 3),
    ('8811880e-5949-5419-9947-892454fe65a3'::uuid, 'ac7fdb4e-445d-5603-bd6a-84017b7a744a'::uuid, 'Quelle est l’abscisse du sommet d’une parabole d’équation a x² + b x + c ?', 'mcq', '["−b / (2a)","b / (2a)","−c / a","−b / a"]'::jsonb, 0, 'C’est aussi l’axe de symétrie de la parabole.', 4),
    ('5d1fed5f-d902-5b2d-8e40-b2662bc1838d'::uuid, 'ac7fdb4e-445d-5603-bd6a-84017b7a744a'::uuid, 'Quelle forme du trinôme permet de lire directement les racines ?', 'mcq', '["La forme factorisée","La forme développée","La forme canonique","Aucune"]'::jsonb, 0, 'a (x − x1)(x − x2) : les racines s’y lisent immédiatement.', 5),
    ('d07c181d-3ecd-5d5e-a729-9d5ce1315faa'::uuid, 'ac7fdb4e-445d-5603-bd6a-84017b7a744a'::uuid, 'Si a est positif, la fonction du second degré admet un maximum.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle admet un MINIMUM : la parabole est tournée vers le haut.', 6),
    ('0f703654-5716-54c9-a31f-2b698e810dc7'::uuid, 'ac7fdb4e-445d-5603-bd6a-84017b7a744a'::uuid, 'Combien vaut la somme des racines d’un trinôme ?', 'mcq', '["−b / a","b / a","c / a","−c / a"]'::jsonb, 0, 'Leur produit vaut c / a.', 7),
    ('93e292e6-90eb-54b2-b8a4-b2d5e1f1eaf5'::uuid, 'ac7fdb4e-445d-5603-bd6a-84017b7a744a'::uuid, 'Que se passe-t-il quand le discriminant est nul ?', 'mcq', '["Il y a une racine double et la parabole est tangente à l’axe des abscisses","Il n’y a aucune racine","Il y a deux racines opposées","La courbe est une droite"]'::jsonb, 0, 'La racine vaut alors −b / (2a).', 8),
    ('e06314ce-877b-5285-92a8-b4894f1a816f'::uuid, '81ffad8a-09fb-54fc-9dd4-e3bea97449e8'::uuid, 'Que représente géométriquement le nombre dérivé f’(a) ?', 'mcq', '["Le coefficient directeur de la tangente au point d’abscisse a","L’ordonnée du point d’abscisse a","L’aire sous la courbe","La limite de la fonction en a"]'::jsonb, 0, 'C’est la lecture géométrique de la limite du taux de variation.', 1),
    ('b9cfae1d-00d0-54c5-ae46-10b37eee3b78'::uuid, '81ffad8a-09fb-54fc-9dd4-e3bea97449e8'::uuid, 'Quelle est l’équation de la tangente à la courbe de f au point d’abscisse a ?', 'mcq', '["y = f’(a)(x − a) + f(a)","y = f(a)(x − a) + f’(a)","y = f’(a) × x + a","y = f(a) × x + f’(a)"]'::jsonb, 0, 'Une droite de coefficient directeur f’(a) passant par (a ; f(a)).', 2),
    ('3b3c3f15-b709-578c-9985-7e3fcde2272d'::uuid, '81ffad8a-09fb-54fc-9dd4-e3bea97449e8'::uuid, 'Quelle est la dérivée de x puissance n ?', 'mcq', '["n × x puissance (n − 1)","x puissance (n − 1)","n × x puissance n","(n − 1) × x puissance n"]'::jsonb, 0, 'Cas particulier : la dérivée de x² vaut 2x.', 3),
    ('66ca62cc-5f0d-55e2-b3a4-20971fb7585d'::uuid, '81ffad8a-09fb-54fc-9dd4-e3bea97449e8'::uuid, 'La dérivée d’un produit est le produit des dérivées.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, '(u × v)’ = u’v + uv’ : c’est l’erreur la plus fréquente du chapitre.', 4),
    ('342d70da-3c61-5c47-b545-506f9ae6884b'::uuid, '81ffad8a-09fb-54fc-9dd4-e3bea97449e8'::uuid, 'Que peut-on dire de f si f’ est négative sur un intervalle ?', 'mcq', '["f est décroissante sur cet intervalle","f est croissante","f est négative","f admet un maximum"]'::jsonb, 0, 'Le signe de la dérivée donne le sens de variation.', 5),
    ('77d7bb3a-eef6-5c1f-b062-a47e92a223f4'::uuid, '81ffad8a-09fb-54fc-9dd4-e3bea97449e8'::uuid, 'Quelle est la dérivée de 1 / x ?', 'mcq', '["−1 / x²","1 / x²","−1 / x","ln x"]'::jsonb, 0, 'Le signe négatif traduit la décroissance de la fonction inverse.', 6),
    ('f10306ea-9e96-53b7-a5c1-452acdc285c3'::uuid, '81ffad8a-09fb-54fc-9dd4-e3bea97449e8'::uuid, 'Si f’ s’annule en un point, f y admet nécessairement un extremum.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il faut qu’elle CHANGE DE SIGNE : la fonction cube en 0 est un contre-exemple.', 7),
    ('805ab245-6c43-54bf-b3ac-cd21834b3eeb'::uuid, '81ffad8a-09fb-54fc-9dd4-e3bea97449e8'::uuid, 'Quelle est la formule de dérivation d’un quotient u / v ?', 'mcq', '["(u’v − uv’) / v²","(u’v + uv’) / v²","(uv’ − u’v) / v²","u’ / v’"]'::jsonb, 0, 'L’ordre au numérateur est décisif : la soustraction n’est pas commutative.', 8),
    ('7e2f0956-948c-519b-a8fe-4737c48a08a6'::uuid, 'e1615c80-440e-590c-90ff-928640e5ce43'::uuid, 'Quelle est la première étape de l’étude d’une fonction ?', 'mcq', '["Déterminer son ensemble de définition","Calculer sa dérivée","Tracer sa courbe","Chercher ses extremums"]'::jsonb, 0, 'Division par zéro et racine d’un négatif sont les deux interdits usuels.', 1),
    ('913fc673-d0f8-5d7e-8cca-475780a0edd0'::uuid, 'e1615c80-440e-590c-90ff-928640e5ce43'::uuid, 'Que signale une tangente horizontale sur une courbe ?', 'mcq', '["Que la dérivée s’y annule","Que la fonction s’y annule","Que la fonction y est discontinue","Que la courbe coupe l’axe des abscisses"]'::jsonb, 0, 'Un extremum s’y trouve si la dérivée change de signe.', 2),
    ('c90c7828-42d6-5006-856a-398050f8fecf'::uuid, 'e1615c80-440e-590c-90ff-928640e5ce43'::uuid, 'Un extremum local est nécessairement un extremum global.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il ne l’est que sur un intervalle autour du point.', 3),
    ('474a97ab-f39e-5abc-bbfc-29c3b8d05702'::uuid, 'e1615c80-440e-590c-90ff-928640e5ce43'::uuid, 'Que faut-il pour que le théorème des valeurs intermédiaires garantisse une solution UNIQUE ?', 'mcq', '["La continuité et la stricte monotonie sur l’intervalle","La continuité seule","La dérivabilité seule","La parité de la fonction"]'::jsonb, 0, 'Sans stricte monotonie, l’existence est acquise mais pas l’unicité.', 4),
    ('2b585933-f881-51ad-8c13-8741449e547e'::uuid, 'e1615c80-440e-590c-90ff-928640e5ce43'::uuid, 'Comment résout-on graphiquement f(x) = k ?', 'mcq', '["En cherchant les abscisses des points d’intersection avec la droite y = k","En cherchant les ordonnées des points d’abscisse k","En regardant où la courbe coupe l’axe des ordonnées","En calculant la dérivée"]'::jsonb, 0, 'C’est la lecture graphique la plus demandée.', 5),
    ('f5e01dd3-0cc0-5eef-aca3-23a56b482340'::uuid, 'e1615c80-440e-590c-90ff-928640e5ce43'::uuid, 'Une fonction paire a une courbe symétrique par rapport à l’axe des ordonnées.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Une fonction impaire, elle, est symétrique par rapport à l’origine.', 6),
    ('4bbeda06-c1e3-5039-b7f4-11a632b8e093'::uuid, 'e1615c80-440e-590c-90ff-928640e5ce43'::uuid, 'Où résout-on f(x) > 0 sur un graphique ?', 'mcq', '["Là où la courbe est au-dessus de l’axe des abscisses","Là où la courbe est croissante","Là où la dérivée est positive","Là où la courbe coupe l’axe des ordonnées"]'::jsonb, 0, 'Ne pas confondre signe de f et signe de f’.', 7),
    ('5462069f-5847-5db0-9dcd-cf9bb8ce68a8'::uuid, 'e1615c80-440e-590c-90ff-928640e5ce43'::uuid, 'Comment encadre-t-on une solution après avoir appliqué le théorème des valeurs intermédiaires ?', 'mcq', '["Par balayage à la calculatrice","Par dérivation successive","Par factorisation","Par le discriminant"]'::jsonb, 0, 'On affine l’encadrement chiffre après chiffre.', 8),
    ('7e6018ce-46a8-582c-95b2-cf37ae558fa3'::uuid, 'afb3f71c-d5c1-5657-9821-ef365e07e69a'::uuid, 'Quelle propriété caractérise la fonction exponentielle ?', 'mcq', '["Elle est égale à sa propre dérivée et vaut 1 en 0","Elle est égale à son inverse","Sa dérivée est nulle","Elle s’annule en 0"]'::jsonb, 0, 'f’ = f et f(0) = 1 la définissent entièrement.', 1),
    ('0450fbc8-58c9-5bb7-bc74-ee03bfd77c78'::uuid, 'afb3f71c-d5c1-5657-9821-ef365e07e69a'::uuid, 'Que vaut e puissance (a + b) ?', 'mcq', '["e puissance a × e puissance b","e puissance a + e puissance b","e puissance (a × b)","e puissance a / e puissance b"]'::jsonb, 0, 'L’exponentielle transforme les sommes en produits.', 2),
    ('0b53d442-498f-581c-9a9b-a964fa79786a'::uuid, 'afb3f71c-d5c1-5657-9821-ef365e07e69a'::uuid, 'L’équation e puissance x = 0 admet-elle une solution ?', 'mcq', '["Non, l’exponentielle est strictement positive","Oui, x = 0","Oui, x = 1","Oui, quand x tend vers moins l’infini"]'::jsonb, 0, 'Elle tend vers 0 sans jamais l’atteindre.', 3),
    ('3e91aede-1b06-5c92-8a6e-8fa43bb22a8d'::uuid, 'afb3f71c-d5c1-5657-9821-ef365e07e69a'::uuid, 'La fonction exponentielle est strictement croissante sur l’ensemble des réels.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Sa dérivée, égale à elle-même, est strictement positive.', 4),
    ('e62bef37-4367-5f73-a894-c7d9a04bd048'::uuid, 'afb3f71c-d5c1-5657-9821-ef365e07e69a'::uuid, 'Quelle est la dérivée de e puissance u ?', 'mcq', '["u’ × e puissance u","e puissance u","u × e puissance u","e puissance u’"]'::jsonb, 0, 'Oublier le facteur u’ est le piège le plus fréquent du chapitre.', 5),
    ('7506b340-421d-5777-ad7c-06cadbd8bdb9'::uuid, 'afb3f71c-d5c1-5657-9821-ef365e07e69a'::uuid, 'Que vaut la dérivée de e puissance (3x) ?', 'mcq', '["3 e puissance (3x)","e puissance (3x)","3x e puissance (3x)","e puissance 3"]'::jsonb, 0, 'Application directe de (e puissance u)’ = u’ × e puissance u.', 6),
    ('0838e6ea-edd1-51e7-9c96-958e8fb32f16'::uuid, 'afb3f71c-d5c1-5657-9821-ef365e07e69a'::uuid, 'L’inéquation e puissance a < e puissance b équivaut à a < b.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'La stricte croissance de l’exponentielle conserve l’ordre.', 7),
    ('4f8e7788-12e0-5543-b05e-e12aaf8027e3'::uuid, 'afb3f71c-d5c1-5657-9821-ef365e07e69a'::uuid, 'Vers quoi tend e puissance x quand x tend vers moins l’infini ?', 'mcq', '["Vers 0","Vers moins l’infini","Vers 1","Vers plus l’infini"]'::jsonb, 0, 'Sans jamais atteindre 0 : l’axe des abscisses est asymptote.', 8),
    ('b9049c59-5961-58e7-b012-d54c25f54861'::uuid, '68827c48-d75c-58de-b861-01079b36ce57'::uuid, 'Quelles sont les coordonnées du point associé au réel x sur le cercle trigonométrique ?', 'mcq', '["(cos x ; sin x)","(sin x ; cos x)","(x ; cos x)","(1 ; x)"]'::jsonb, 0, 'Le cercle a pour rayon 1 et pour centre l’origine.', 1),
    ('8eb492f5-e23f-5cbd-aa25-3e754d8c21b5'::uuid, '68827c48-d75c-58de-b861-01079b36ce57'::uuid, 'Quelle relation lie cosinus et sinus d’un même réel ?', 'mcq', '["cos² x + sin² x = 1","cos x + sin x = 1","cos x × sin x = 1","cos² x − sin² x = 1"]'::jsonb, 0, 'C’est le théorème de Pythagore dans un cercle de rayon 1.', 2),
    ('9e91031e-c2de-52a7-a02a-77ad4dba32e7'::uuid, '68827c48-d75c-58de-b861-01079b36ce57'::uuid, 'Combien de radians vaut un tour complet ?', 'mcq', '["2π","π","360","π/2"]'::jsonb, 0, 'π radians valent 180 degrés.', 3),
    ('21f2e1d3-a474-5416-a82e-c1161d0a140d'::uuid, '68827c48-d75c-58de-b861-01079b36ce57'::uuid, 'La fonction sinus est paire.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle est IMPAIRE : sin(−x) = −sin x. C’est le cosinus qui est pair.', 4),
    ('2e0b6be5-2a7a-5b95-ae7b-16897c9c7112'::uuid, '68827c48-d75c-58de-b861-01079b36ce57'::uuid, 'Que vaut cos(π/3) ?', 'mcq', '["1/2","√3 / 2","√2 / 2","0"]'::jsonb, 0, 'Et sin(π/3) vaut √3 / 2 : ne pas les intervertir.', 5),
    ('f940bcda-5e0b-5ca0-ad7b-06443220f77f'::uuid, '68827c48-d75c-58de-b861-01079b36ce57'::uuid, 'Quelle est la dérivée de la fonction cosinus ?', 'mcq', '["−sin x","sin x","cos x","−cos x"]'::jsonb, 0, 'Le signe moins est ce qu’on oublie le plus souvent.', 6),
    ('e14fba4f-98ef-5bdf-a598-59a340584d69'::uuid, '68827c48-d75c-58de-b861-01079b36ce57'::uuid, 'Les fonctions cosinus et sinus sont périodiques de période 2π.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Il suffit donc de les étudier sur un intervalle de longueur 2π.', 7),
    ('56c64a46-aa8e-541a-8754-dcb140fba92d'::uuid, '68827c48-d75c-58de-b861-01079b36ce57'::uuid, 'Que vaut sin(π/2) ?', 'mcq', '["1","0","1/2","√2 / 2"]'::jsonb, 0, 'Au quart de tour, le point est en haut du cercle : ordonnée 1.', 8),
    ('2030750c-3b3a-5e53-9b18-3e8214350965'::uuid, 'fe904eb8-85c5-5586-9673-41d3a48958f6'::uuid, 'Le produit scalaire de deux vecteurs est…', 'mcq', '["un nombre réel","un vecteur","un angle","une longueur toujours positive"]'::jsonb, 0, 'La confusion avec un vecteur est l’erreur d’entrée du chapitre.', 1),
    ('abff2287-6804-560d-8825-b5fe70583fa5'::uuid, 'fe904eb8-85c5-5586-9673-41d3a48958f6'::uuid, 'Comment calcule-t-on le produit scalaire en repère orthonormé ?', 'mcq', '["x x’ + y y’","x x’ − y y’","x y’ + y x’","x y’ − y x’"]'::jsonb, 0, 'La dernière expression est celle du déterminant, pas du produit scalaire.', 2),
    ('e86a5938-72c8-5387-8b62-098eb4f3f706'::uuid, 'fe904eb8-85c5-5586-9673-41d3a48958f6'::uuid, 'Deux vecteurs non nuls sont orthogonaux si et seulement si leur produit scalaire est nul.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est le critère le plus employé du chapitre.', 3),
    ('44f43bce-d86b-5366-b8a0-d840c52a42b3'::uuid, 'fe904eb8-85c5-5586-9673-41d3a48958f6'::uuid, 'Quelle expression fait intervenir l’angle entre les deux vecteurs ?', 'mcq', '["||u|| × ||v|| × cos θ","x x’ + y y’","½ (||u + v||² − ||u||² − ||v||²)","u · u"]'::jsonb, 0, 'Elle permet de calculer un angle à partir des coordonnées.', 4),
    ('a4f1eeec-4e89-5a5a-8bbd-b8fcc933c671'::uuid, 'fe904eb8-85c5-5586-9673-41d3a48958f6'::uuid, 'Que vaut u · u ?', 'mcq', '["Le carré de la norme de u","La norme de u","Zéro","Le double de la norme de u"]'::jsonb, 0, 'C’est ce qui relie produit scalaire et longueur.', 5),
    ('42dda11f-c84a-5c0d-a8cd-8387a16dd7d4'::uuid, 'fe904eb8-85c5-5586-9673-41d3a48958f6'::uuid, 'Que devient le théorème d’Al-Kashi quand l’angle A vaut 90° ?', 'mcq', '["Le théorème de Pythagore","La loi des sinus","L’inégalité triangulaire","Rien de connu"]'::jsonb, 0, 'cos 90° = 0 fait disparaître le troisième terme.', 6),
    ('3f3afa66-2f00-5795-8590-040bcb0a83d5'::uuid, 'fe904eb8-85c5-5586-9673-41d3a48958f6'::uuid, 'Le produit scalaire est symétrique : u · v = v · u.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Il est aussi bilinéaire, ce qui autorise à développer comme avec des nombres.', 7),
    ('5f8fcba6-a5af-5a60-b103-03bd46afb4bb'::uuid, 'fe904eb8-85c5-5586-9673-41d3a48958f6'::uuid, 'Quelle méthode consiste à ramener un vecteur sur la direction de l’autre ?', 'mcq', '["La projection orthogonale","Le calcul par coordonnées","Le théorème d’Al-Kashi","La bilinéarité"]'::jsonb, 0, 'On multiplie ensuite les mesures algébriques obtenues.', 8),
    ('db21f296-8159-50ca-8df9-44187095d4b1'::uuid, '786064c9-635c-5ce5-b8b7-132c4805a62e'::uuid, 'Quel est un vecteur directeur de la droite d’équation a x + b y + c = 0 ?', 'mcq', '["u(−b ; a)","u(a ; b)","u(b ; a)","u(a ; −b)"]'::jsonb, 0, 'Le vecteur n(a ; b), lui, est normal à la droite.', 1),
    ('72b8311d-3237-5d5f-9ad1-89a83e9c635c'::uuid, '786064c9-635c-5ce5-b8b7-132c4805a62e'::uuid, 'Quelle est l’équation d’un cercle de centre Ω(a ; b) et de rayon r ?', 'mcq', '["(x − a)² + (y − b)² = r²","(x + a)² + (y + b)² = r²","x² + y² = a² + b²","(x − a) + (y − b) = r"]'::jsonb, 0, 'La forme développée s’y ramène en complétant les carrés.', 2),
    ('2177bac4-4513-5d09-adbc-58b52ca9f132'::uuid, '786064c9-635c-5ce5-b8b7-132c4805a62e'::uuid, 'Deux droites sont perpendiculaires si le produit de leurs coefficients directeurs vaut −1.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'On peut aussi le voir par un produit scalaire nul entre vecteurs directeurs.', 3),
    ('247960a0-1267-5c6d-9077-2975355279cc'::uuid, '786064c9-635c-5ce5-b8b7-132c4805a62e'::uuid, 'Comment reconnaît-on que deux vecteurs sont colinéaires ?', 'mcq', '["Leur déterminant x y’ − y x’ est nul","Leur produit scalaire est nul","Leurs normes sont égales","Leur somme est nulle"]'::jsonb, 0, 'Le produit scalaire nul, lui, caractérise l’orthogonalité.', 4),
    ('8745b111-2188-5068-b7c5-b31d8409bd67'::uuid, '786064c9-635c-5ce5-b8b7-132c4805a62e'::uuid, 'Quelle droite ne peut pas s’écrire sous la forme y = m x + p ?', 'mcq', '["Une droite verticale","Une droite horizontale","Une droite passant par l’origine","Une droite de coefficient directeur négatif"]'::jsonb, 0, 'Elle s’écrit x = k.', 5),
    ('6323545b-e6e5-5672-a443-3cd60646f49a'::uuid, '786064c9-635c-5ce5-b8b7-132c4805a62e'::uuid, 'Comment ramène-t-on une équation développée de cercle à sa forme canonique ?', 'mcq', '["En complétant les carrés","En calculant le discriminant","En dérivant","En factorisant par x"]'::jsonb, 0, 'Même technique que pour la forme canonique du trinôme.', 6),
    ('03eb2b0d-f4a1-503c-931e-d6e5e72a5515'::uuid, '786064c9-635c-5ce5-b8b7-132c4805a62e'::uuid, 'Le cercle de diamètre [AB] est l’ensemble des points M tels que le produit scalaire des vecteurs MA et MB soit nul.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'L’angle en M est alors droit : c’est une caractérisation très commode.', 7),
    ('41b21911-e572-57df-9726-0e18b85923bb'::uuid, '786064c9-635c-5ce5-b8b7-132c4805a62e'::uuid, 'Quelle est la formule de la distance entre A et B en repère orthonormé ?', 'mcq', '["√((x(B) − x(A))² + (y(B) − y(A))²)","(x(B) − x(A)) + (y(B) − y(A))","√(x(B) × x(A) + y(B) × y(A))","|x(B) − x(A)| + |y(B) − y(A)|"]'::jsonb, 0, 'C’est le théorème de Pythagore appliqué aux coordonnées.', 8),
    ('e1cd0112-ccbc-5e55-ab4e-7f08c6e62a49'::uuid, '818f0273-d748-55c6-ab3f-3023ece55895'::uuid, 'Quelle est la formule de la probabilité conditionnelle de B sachant A ?', 'mcq', '["P(A inter B) / P(A)","P(A inter B) / P(B)","P(A) × P(B)","P(A) + P(B)"]'::jsonb, 0, 'Elle suppose P(A) non nulle.', 1),
    ('238fe8d9-02b1-55a3-aea4-4c1e96156de5'::uuid, '818f0273-d748-55c6-ab3f-3023ece55895'::uuid, 'Comment calcule-t-on la probabilité d’un chemin dans un arbre pondéré ?', 'mcq', '["En multipliant les probabilités des branches du chemin","En les additionnant","En prenant la plus petite","En prenant la dernière"]'::jsonb, 0, 'La probabilité d’un événement est ensuite la somme des chemins qui y mènent.', 2),
    ('ed1eab0c-4b38-5b0d-b878-a95a77a253c3'::uuid, '818f0273-d748-55c6-ab3f-3023ece55895'::uuid, 'La somme des probabilités des branches issues d’un même nœud vaut 1.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est le premier contrôle à faire sur un arbre.', 3),
    ('1d322e83-0457-5333-84b5-c7684911131b'::uuid, '818f0273-d748-55c6-ab3f-3023ece55895'::uuid, 'Que dit la formule des probabilités totales ?', 'mcq', '["P(B) se décompose selon les événements d’une partition de l’univers","P(B) est toujours égale à P(A)","P(B) est le produit des probabilités conditionnelles","P(B) vaut 1 moins P(A)"]'::jsonb, 0, 'C’est la troisième règle de l’arbre, écrite en formule.', 4),
    ('96de825e-61ae-5557-b30a-8692b5468520'::uuid, '818f0273-d748-55c6-ab3f-3023ece55895'::uuid, 'Quelle égalité caractérise deux événements indépendants ?', 'mcq', '["P(A inter B) = P(A) × P(B)","P(A inter B) = 0","P(A) = P(B)","P(A union B) = P(A) + P(B)"]'::jsonb, 0, 'Équivalente à P(A)(B) = P(B) lorsque P(A) est non nulle.', 5),
    ('2eef88d8-3ca2-5ae0-8334-a34fbe6b4a2e'::uuid, '818f0273-d748-55c6-ab3f-3023ece55895'::uuid, 'Deux événements incompatibles de probabilités non nulles sont indépendants.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Si l’un se réalise, l’autre devient impossible : sa probabilité change.', 6),
    ('00fcab17-09b8-5218-8573-c314218988fc'::uuid, '818f0273-d748-55c6-ab3f-3023ece55895'::uuid, 'Que portent les branches du deuxième niveau d’un arbre pondéré ?', 'mcq', '["Des probabilités conditionnelles","Des probabilités simples","Des effectifs","Des fréquences cumulées"]'::jsonb, 0, 'C’est ce que la lecture d’un énoncé doit permettre d’identifier.', 7),
    ('6fd9dd16-9511-515e-a4e0-3f7f3de4ab29'::uuid, '818f0273-d748-55c6-ab3f-3023ece55895'::uuid, 'Comment obtient-on P(B)(A) quand l’énoncé donne P(A)(B) ?', 'mcq', '["En calculant P(A inter B) et P(B), puis leur quotient","En inversant simplement les lettres","En multipliant par P(A)","C’est impossible"]'::jsonb, 0, 'C’est la structure de tous les exercices de test médical.', 8),
    ('cb71121a-9757-57d5-a241-8d417317a5a3'::uuid, 'edff98fe-76fb-54c1-ac8f-eeffa181e891'::uuid, 'Qu’est-ce qu’une variable aléatoire ?', 'mcq', '["Une fonction qui associe un nombre réel à chaque issue d’une expérience aléatoire","Un événement de probabilité inconnue","Une probabilité qui varie","Un tirage au hasard"]'::jsonb, 0, 'Elle rend l’univers numérique, donc calculable.', 1),
    ('524d32a2-c042-568e-8da8-919d24b5b8a5'::uuid, 'edff98fe-76fb-54c1-ac8f-eeffa181e891'::uuid, 'Que vaut la somme des probabilités d’une loi de probabilité ?', 'mcq', '["1","0","L’espérance","Le nombre de valeurs possibles"]'::jsonb, 0, 'C’est le contrôle à faire systématiquement sur un tableau de loi.', 2),
    ('0f382f1f-0ce1-588b-bb0c-78cf2b039f43'::uuid, 'edff98fe-76fb-54c1-ac8f-eeffa181e891'::uuid, 'Comment calcule-t-on l’espérance d’une variable aléatoire ?', 'mcq', '["En sommant les produits de chaque valeur par sa probabilité","En faisant la moyenne des valeurs possibles","En prenant la valeur la plus probable","En divisant la somme des valeurs par leur nombre"]'::jsonb, 0, 'Ce n’est pas une moyenne simple : chaque valeur est pondérée.', 3),
    ('ab487385-70a4-5c8a-b6fd-2883689aee18'::uuid, 'edff98fe-76fb-54c1-ac8f-eeffa181e891'::uuid, 'L’espérance d’une variable aléatoire est toujours une valeur qu’elle peut prendre.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'L’espérance du lancer d’un dé équilibré vaut 3,5, valeur impossible.', 4),
    ('1c084380-f4b3-5814-93f2-4b9c71a70e66'::uuid, 'edff98fe-76fb-54c1-ac8f-eeffa181e891'::uuid, 'Que signifie une espérance de gain nulle dans un jeu d’argent ?', 'mcq', '["Le jeu est équitable","Le jeu est favorable au joueur","Le jeu est favorable à l’organisateur","Le jeu est impossible"]'::jsonb, 0, 'Ni le joueur ni l’organisateur ne gagnent en moyenne.', 5),
    ('d9ace3ed-be5f-56f3-bb36-68e48ef5d2f3'::uuid, 'edff98fe-76fb-54c1-ac8f-eeffa181e891'::uuid, 'Que vaut V(aX + b) ?', 'mcq', '["a² V(X)","a V(X) + b","a² V(X) + b²","a V(X)"]'::jsonb, 0, 'Le b disparaît : une translation ne change pas la dispersion.', 6),
    ('709e0a12-61a8-5ed1-9527-d97e4d26aad6'::uuid, 'edff98fe-76fb-54c1-ac8f-eeffa181e891'::uuid, 'À quoi sert l’écart type par rapport à la variance ?', 'mcq', '["Il ramène la dispersion à l’unité de la variable, donc l’interprète","Il est plus facile à calculer","Il est toujours plus grand","Il donne l’espérance"]'::jsonb, 0, 'C’est la racine carrée de la variance.', 7),
    ('0beb2785-9931-5488-83e0-a0cec43c14c9'::uuid, 'edff98fe-76fb-54c1-ac8f-eeffa181e891'::uuid, 'Que dit la loi des grands nombres ?', 'mcq', '["La moyenne d’un grand nombre de répétitions se rapproche de l’espérance","Chaque tirage compense le précédent","La probabilité augmente avec le nombre d’essais","L’écart type tend vers l’espérance"]'::jsonb, 0, 'C’est ce qui explique qu’un casino ne perde pas sur le long terme.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('maths');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('maths')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 271 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 271 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
