-- =============================================================================
-- Studuel — Migration 277 : EMC 1re — « COHÉSION ET DIVERSITÉ DANS UNE SOCIÉTÉ DÉMOCRATIQUE »
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 277 --modules emc-1re
--
-- LE DÉFAUT (sondé le 21/08/2026, node _ASSOCIE/sonde-chapitres.mjs 1re emc) :
-- l'EMC de Première n'avait que les 3 fiches du socle lycée de la migration 216 —
-- « La liberté d'expression et ses limites », « Démocratie et État de droit »,
-- « Enjeux du numérique et de l'information » —, écrites pour la 2de, la 1re et la
-- Tle à la fois. Le programme propre à la Première n'existait nulle part : ni la
-- fraternité, ni la loi de 1905, ni la loi Pleven, ni la décentralisation, ni le
-- droit du sol, ni la sécurité nationale.
-- LE TEXTE QUI FAIT FOI : le programme d'EMC du BO n° 24 du 13 juin 2024,
-- applicable à tous les niveaux à la rentrée 2026-2027. L'année de Première y a
-- pour thématique « Cohésion et diversité dans une société démocratique » et pour
-- chapitres ses deux thèmes de 9 heures : « Les valeurs et les principes de la
-- République à l'épreuve de la cohésion sociale » et « La République et la
-- Nation ». Cette migration installe leurs 12 fiches, aux positions 1 à 12.
-- LES 3 FICHES DU SOCLE PARTENT, AU SEUL NIVEAU 1re — décision prise en 250 pour
-- la Terminale, pour la même raison : trois lignes hors programme en tête de liste
-- rouvrent le doute sur les douze autres. Deux d'entre elles relèvent d'ailleurs,
-- dans le programme de 2024, de la SECONDE (« Liberté et responsabilité :
-- l'exemple de l'information »). La 2de les garde : elle n'a pas encore son
-- programme propre, et rien ne viendrait les remplacer.
-- ⚠️ LA 216 EST REJOUABLE : la recoller ferait revenir les 3 fiches au niveau 1re.
--
-- Cette migration apporte : 12 chapitres, 12 leçons,
-- 12 quiz et 96 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 0. Ménage ----------------------------------------------------------------
-- [emc] La colonne de rangement d'abord : theme (migration 234) porte le chapitre du
-- [emc] programme, et l'INSERT l'écrit pour les 12 fiches. Elle est REPRISE ici en ADD
-- [emc] COLUMN IF NOT EXISTS, comme dans les migrations 243 à 276 — la 234 n'a jamais été
-- [emc] exécutée telle quelle. Sans cette reprise, la migration échouerait sur « column
-- [emc] chapters.theme does not exist », les 3 anciennes fiches déjà supprimées et les 12
-- [emc] neuves pas encore posées : une matière vide.
-- [emc] Le GRANT n'est pas décoratif : la 182 a révoqué le SELECT de table sur chapters
-- [emc] (pour cacher mind_map) et ne l'a rendu que colonne par colonne ; une colonne
-- [emc] ajoutée après elle n'hérite d'aucun droit, et l'app lirait « permission denied »
-- [emc] au lieu du chapitre.
ALTER TABLE public.chapters ADD COLUMN IF NOT EXISTS theme TEXT;
GRANT SELECT (theme) ON public.chapters TO anon;
GRANT SELECT (theme) ON public.chapters TO authenticated;

-- [emc] Les 3 fiches du socle lycée partent, au niveau 1re SEULEMENT.
-- [emc] 
-- [emc] LE REPÈRE EST theme IS NULL, PAS LE TITRE — même choix qu'en anglais (266), en
-- [emc] espagnol (267) et en allemand (276). La 250 avait supprimé les mêmes fiches par
-- [emc] leurs titres exacts au niveau Tle, en prenant soin de l'apostrophe typographique ;
-- [emc] deux de ces trois titres en portent une, et un DELETE qui se tromperait
-- [emc] d'apostrophe ne trouverait rien EN SILENCE. Le critère « pas de chapitre de
-- [emc] programme » vise exactement les trois lignes voulues : elles datent de la 216,
-- [emc] bien avant la colonne theme, tandis que les 12 fiches neuves en portent un dès
-- [emc] l'INSERT — le ménage tourne AVANT les insertions et ne peut donc jamais mordre
-- [emc] sur elles, ni au premier passage ni au rejeu.
-- [emc] Le filtre level = '1re' est indispensable : ces mêmes fiches sont la seule chose
-- [emc] que la 2de possède en EMC. Sans la borne, le ménage la viderait sans rien mettre
-- [emc] à la place. Le collège, qui a ses propres chapitres dans la 216, n'est pas
-- [emc] concerné par le critère mais l'est par la borne.
-- [emc] L'ordre compte : la file « À revoir » d'abord (review_items.item_id n'a PAS de
-- [emc] clé étrangère — rien ne casserait, mais le compteur « X à revoir » continuerait
-- [emc] de compter des questions disparues), puis les quiz (quizzes.lesson_id est ON
-- [emc] DELETE SET NULL : ils survivraient orphelins, sans leçon mais toujours rattachés
-- [emc] à « EMC / 1re » par subject + grade_level, donc toujours tirables par le moteur
-- [emc] de questions), puis les chapitres, dont les leçons partent en cascade.
DELETE FROM public.review_items ri
 USING public.quiz_questions qq, public.quizzes qz, public.lessons l,
       public.chapters c, public.subjects s
 WHERE ri.item_kind = 'question'
   AND ri.item_id = qq.id
   AND qq.quiz_id = qz.id
   AND qz.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'emc'
   AND c.level = '1re'
   AND c.theme IS NULL;

DELETE FROM public.quizzes q
 USING public.lessons l, public.chapters c, public.subjects s
 WHERE q.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'emc'
   AND c.level = '1re'
   AND c.theme IS NULL;

DELETE FROM public.chapters c
 USING public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'emc'
   AND c.level = '1re'
   AND c.theme IS NULL;

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position, theme)
SELECT v.id, s.id, v.level, v.title, v.position, v.theme
  FROM (VALUES
    ('ffeec1c1-803f-56b3-aa0d-67f29b016f68'::uuid, 'emc', '1re', 'Solidarité et fraternité', 1, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('f528c350-34ff-546a-8dae-67ccca604594'::uuid, 'emc', '1re', 'Lutter contre les inégalités économiques et sociales', 2, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('2d2e06e1-de83-557f-bb3d-e6852dfd4774'::uuid, 'emc', '1re', 'L’égalité entre les femmes et les hommes', 3, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('87f5e9ae-40ba-5df4-b79b-6b8045bc37f2'::uuid, 'emc', '1re', 'Les discriminations : les définir, les mesurer, les combattre', 4, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('5b7b35a4-e4f7-56fe-b5f4-f197cfb6d39c'::uuid, 'emc', '1re', 'Vers une société inclusive : la question du handicap', 5, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('4adecebe-8eff-5410-b73d-3ae75a40033c'::uuid, 'emc', '1re', 'Racisme, antisémitisme, xénophobie et haine anti-LGBT', 6, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('367f457f-4a36-501c-9939-6cda87bc1606'::uuid, 'emc', '1re', 'Laïcité et pluralisme', 7, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('27f47db5-6f14-5c5e-b867-1d2dd49f4583'::uuid, 'emc', '1re', 'Une République indivisible et décentralisée', 8, 'La République et la Nation'),
    ('9009928d-f52b-592a-9efb-1496daf3785f'::uuid, 'emc', '1re', 'La décentralisation depuis 1982 et la diversité des territoires', 9, 'La République et la Nation'),
    ('f4ef57a8-9602-55b3-ae15-dbec3c034cb5'::uuid, 'emc', '1re', 'Nationalité et citoyenneté', 10, 'La République et la Nation'),
    ('65ff5d37-8556-5758-ace0-d6e503f49374'::uuid, 'emc', '1re', 'Les questions mémorielles et le patriotisme constitutionnel', 11, 'La République et la Nation'),
    ('cf92abfb-c5c4-5cee-86d2-c26537206f93'::uuid, 'emc', '1re', 'La défense et la sécurité nationale', 12, 'La République et la Nation')
  ) AS v(id, slug, level, title, position, theme)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 1 bis. Axes du programme -------------------------------------------------
-- `chapters.theme` (migration 234) : l’intitulé du programme officiel qui
-- coiffe le chapitre. La page matière s’en sert pour grouper au lieu
-- d’aligner 28 lignes à plat. UPDATE et non INSERT : le chapitre peut déjà
-- exister (l’INSERT précédent l’aurait alors ignoré).
UPDATE public.chapters c SET theme = v.theme
  FROM (VALUES
    ('ffeec1c1-803f-56b3-aa0d-67f29b016f68'::uuid, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('f528c350-34ff-546a-8dae-67ccca604594'::uuid, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('2d2e06e1-de83-557f-bb3d-e6852dfd4774'::uuid, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('87f5e9ae-40ba-5df4-b79b-6b8045bc37f2'::uuid, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('5b7b35a4-e4f7-56fe-b5f4-f197cfb6d39c'::uuid, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('4adecebe-8eff-5410-b73d-3ae75a40033c'::uuid, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('367f457f-4a36-501c-9939-6cda87bc1606'::uuid, 'Les valeurs et les principes de la République à l’épreuve de la cohésion sociale'),
    ('27f47db5-6f14-5c5e-b867-1d2dd49f4583'::uuid, 'La République et la Nation'),
    ('9009928d-f52b-592a-9efb-1496daf3785f'::uuid, 'La République et la Nation'),
    ('f4ef57a8-9602-55b3-ae15-dbec3c034cb5'::uuid, 'La République et la Nation'),
    ('65ff5d37-8556-5758-ace0-d6e503f49374'::uuid, 'La République et la Nation'),
    ('cf92abfb-c5c4-5cee-86d2-c26537206f93'::uuid, 'La République et la Nation')
  ) AS v(id, theme)
 WHERE c.id = v.id AND c.theme IS DISTINCT FROM v.theme;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('edbb73b6-fbe8-51be-ac69-8a3706119137', 'ffeec1c1-803f-56b3-aa0d-67f29b016f68', 'Le troisième mot de la devise', E'« Liberté, Égalité, Fraternité » : le troisième terme est longtemps resté le moins juridique des trois. Il ne l''est plus.\n\n## Un projet social inscrit dans les textes\nL''**article 1er de la Constitution** de 1958 dispose que la France est une République « indivisible, **laïque**, **démocratique** et **sociale** ».\n\n> Le mot *sociale* engage : la Nation porte un projet qui suppose à la fois de **lutter contre les inégalités** et de **tisser des liens** entre citoyens.\n\n## Fraternité et solidarité\n| Le mot | Ce qu''il est | Peut-on l''exiger |\n| **Fraternité** | Une **valeur** : le lien moral entre membres d''une même communauté politique | **Non**, on ne l''impose pas |\n| **Solidarité** | Sa traduction **organisée** : impôts, cotisations, prestations, services publics | **Oui** |\n\n## Assurance ou assistance\nLa protection sociale, bâtie à partir de **1945**, combine deux logiques.\n\n| La logique | Son principe | Ses exemples |\n| **Assurance** | On **cotise**, on est couvert | Chômage, retraite, maladie |\n| **Assistance** | On reçoit **sans avoir cotisé**, parce qu''on en a besoin | RSA, allocations, fonds sociaux des établissements |\n\nS''y ajoutent des gestes **volontaires** — don du sang, dons aux associations, bénévolat — qui ne remplacent pas l''impôt mais complètent ce qu''il finance.\n\n## La fraternité devient un principe constitutionnel\n| L''élément | Le détail |\n| La décision | Conseil constitutionnel, **6 juillet 2018** |\n| Ce qu''elle reconnaît | Au principe de fraternité une **valeur constitutionnelle** |\n| Ce qu''elle en tire | La « liberté d''aider autrui, dans un but humanitaire, sans considération de la régularité de son séjour » |\n| Son effet | Le « délit de solidarité » est limité : l''aide au séjour désintéressée ne peut plus être punie |\n\n> À retenir pour une copie : la fraternité n''est plus seulement un mot sur un fronton, c''est une norme dont un juge peut se servir pour écarter une loi.', 1),
  ('cd22cca0-130c-598c-85b9-c3ba195ededd', 'f528c350-34ff-546a-8dae-67ccca604594', 'Quand l’écart menace le lien', E'Le programme pose la question sans détour : les inégalités économiques et sociales peuvent présenter un danger pour la cohésion sociale et la démocratie. Pourquoi ?\n\n## Mesurer avant de juger\n| La notion | Sa définition | L''ordre de grandeur en France |\n| Le **seuil de pauvreté** monétaire | **60 %** du niveau de vie médian | Environ **9 millions** de personnes en dessous, près de **15 %** |\n| Le **niveau de vie médian** | Il partage la population en deux moitiés | Ce n''est **pas** la moyenne, que quelques très hauts revenus tireraient vers le haut |\n| La **pauvreté en conditions de vie** | Logement, santé, mobilité, accès au numérique | Elle ne se réduit pas au revenu |\n\n## Pourquoi c''est un problème politique\n| Ce qui est fragilisé | Comment |\n| L''**égalité des chances** | À l''école, l''origine sociale pèse fortement sur les résultats |\n| La **confiance** | Dans les institutions et dans les autres |\n| La **participation** | L''abstention est nettement plus élevée dans les milieux populaires, ce qui déforme la représentation |\n\n## Ce que fait l''État\n| L''outil | Son effet |\n| La **redistribution** — impôts progressifs, prestations | Elle réduit d''environ un **tiers** les écarts de revenus avant transferts |\n| Les **minima sociaux** et la **prime d''activité** | Ils soutiennent les bas revenus |\n| La **politique de la ville** et l''**ANCT** (2020) | Elles agissent sur les inégalités **territoriales** : quartiers prioritaires, ruralité, services publics |\n| La **loi SRU** (2000) | Un quota de **logements sociaux** — 25 % en zone tendue : un outil de **mixité sociale** |\n\n> Nuance attendue dans une copie : réduire les inégalités n''est pas supprimer les différences. La République garantit l''**égalité des droits**, et cherche à corriger les inégalités qui empêchent d''en user réellement.', 1),
  ('0d016bee-b36b-55d2-b6fa-9db5ae08277b', '2d2e06e1-de83-557f-bb3d-e6852dfd4774', 'Un principe, des lois, et une réalité qui résiste', E'L''égalité femmes-hommes montre comment un principe transforme lentement une société — et où il se heurte encore à des résistances.\n\n## Une conquête juridique par étapes\n| La date | L''avancée |\n| **1944** | Droit de vote et d''éligibilité des femmes ; premier vote en 1945 |\n| **1965** | Les femmes mariées peuvent travailler et ouvrir un compte sans l''autorisation de leur mari |\n| **1972** | Égalité de rémunération « à travail de valeur égale » |\n| **1975** | Loi Veil sur l''**IVG**, définitive en 1979 |\n| **1983** | Loi Roudy sur l''égalité professionnelle |\n| **1999-2000** | Révision constitutionnelle et lois sur la **parité** en politique |\n| **2019** | **Index de l''égalité professionnelle**, obligatoire dès 50 salariés |\n| **4 mars 2024** | La **liberté garantie** de recourir à l''IVG entre dans la **Constitution** |\n\n## Ce que disent les chiffres\n| L''écart de revenu salarial | Sa valeur |\n| Tous temps de travail confondus | Environ **20 %** |\n| À poste et temps de travail comparables | Environ **4 %** |\n\n| La cause de l''écart | Ce qu''elle recouvre |\n| Le **temps partiel** | Très majoritairement féminin |\n| La **ségrégation professionnelle** | Des métiers très féminins, souvent moins rémunérés |\n| Le **plafond de verre** | L''accès aux postes de direction |\n\n## Les causes, et l''école\nStéréotypes et préjugés se forment tôt : la **représentation genrée des formations** oriente les choix bien avant le marché du travail.\n\n> D''où les actions sur l''orientation, dans les filières scientifiques et techniques notamment.\n\n## Violences sexistes et sexuelles\n| Le repère | Ce qu''il est |\n| Le **3919** | Écoute, gratuit, 24 h/24 |\n| La **Convention d''Istanbul** | 2011, ratifiée par la France en 2014 |\n| Les dispositifs de protection | Ordonnance de protection, bracelet anti-rapprochement |\n\n> Point de méthode : distinguer l''**égalité en droit**, acquise depuis longtemps, de l''**égalité réelle**, encore inachevée. C''est l''écart entre les deux que le programme demande d''examiner.', 1),
  ('278e9c80-e4e1-5501-8ac1-eda0f263a074', '87f5e9ae-40ba-5df4-b79b-6b8045bc37f2', 'Ce que le droit appelle une discrimination', E'Une discrimination n''est pas un simple sentiment d''injustice : c''est une notion juridique, définie et sanctionnée.\n\n## La définition du Code pénal\nL''**article 225-1** définit la discrimination comme toute distinction entre personnes **à raison d''un critère prohibé**. Le droit français en compte plus de **vingt-cinq** : origine, sexe, situation de famille, apparence physique, état de santé, **handicap**, âge, opinions politiques, activités syndicales, appartenance vraie ou supposée à une ethnie ou une **religion**, **orientation sexuelle**, identité de genre, lieu de résidence…\n\n| La condition | Ce qu''elle exige |\n| Un **critère prohibé** | Parmi ceux que la loi énumère |\n| Une **situation visée par la loi** | Refus d''embauche, licenciement, refus de fourniture d''un bien ou d''un service, refus de louer |\n\nLes peines vont jusqu''à **3 ans d''emprisonnement et 45 000 € d''amende**.\n\n## Directe ou indirecte\n| Le type | Son mécanisme | Un exemple |\n| **Directe** | Le critère est explicitement utilisé | « Nous ne prenons pas de femmes » |\n| **Indirecte** | Une règle apparemment neutre défavorise en fait un groupe | Un critère de taille pour un métier où elle n''est pas nécessaire |\n\n## Ressenti et preuve\nLes discriminations sont **ressenties** bien plus souvent qu''elles ne sont **prouvées** : la victime connaît rarement la vraie raison d''un refus.\n\n| L''outil | Ce qu''il permet |\n| Le **testing** | Comparer deux candidatures identiques ne différant que par le critère suspecté — admis comme mode de preuve |\n| L''**aménagement de la charge de la preuve** | La victime présente des éléments de fait ; c''est ensuite au défendeur de prouver que sa décision était justifiée |\n\n## Qui agit\n| L''acteur | Son rôle |\n| Le **Défenseur des droits** | Autorité constitutionnelle indépendante créée en 2011, saisissable gratuitement par toute personne |\n| La **DILCRAH** | Elle coordonne l''action contre le racisme, l''antisémitisme et la haine anti-LGBT |\n| La **CNCDH** | Elle remet chaque année un rapport sur le racisme |\n| Les **associations habilitées** | Elles peuvent se porter partie civile |\n\n> Attention au sens du mot dans une copie : distinguer devient **discriminer** seulement quand la distinction repose sur un critère interdit, dans une situation visée par la loi.', 1),
  ('97d168e4-af70-5f80-a4b6-74f20f344be7', '5b7b35a4-e4f7-56fe-b5f4-f197cfb6d39c', 'Adapter la société, pas seulement la personne', E'La société inclusive ajoute au principe d''égalité un impératif de solidarité : ce n''est plus à la personne de s''adapter seule, c''est à la société de lever les obstacles.\n\n## Deux façons de voir le handicap\n| L''approche | Où elle situe le handicap | Ce qu''elle demande |\n| **Médicale** | Une déficience **individuelle** | La compenser |\n| **Sociale**, retenue aujourd''hui | La **rencontre** entre une déficience et un environnement inadapté | Adapter l''environnement |\n\n> Un fauteuil ne handicape pas dans un bâtiment accessible.\n\n## La loi du 11 février 2005\n« Pour l''égalité des droits et des chances, la participation et la citoyenneté des personnes handicapées ». Elle donne une définition légale du handicap et pose trois piliers.\n\n| Le pilier | Son contenu |\n| L''**accessibilité généralisée** | Bâtiments, transports, écoles, information |\n| La **compensation** | Prestation de compensation du handicap, **AAH** |\n| Le **guichet unique** | La **MDPH**, une par département |\n\n## À l''école\nLe principe : la scolarisation en **milieu ordinaire**, dans l''établissement le plus proche du domicile.\n\n| L''outil | Ce qu''il apporte |\n| Le **PPS** | Le projet personnalisé de scolarisation |\n| Les **AESH** | Des accompagnants |\n| Les **Ulis** | Des unités localisées pour l''inclusion scolaire |\n| Les **aménagements d''examens** | Temps majoré, secrétaire, matériel adapté |\n\n## Au travail\n| L''obligation | Son contenu |\n| Loi de **1987** | **6 %** de travailleurs handicapés dès 20 salariés ; à défaut, une contribution est due |\n| Les **aménagements raisonnables** | L''employeur doit adapter le poste |\n\n## Le cadre international\nLa **Convention de l''ONU relative aux droits des personnes handicapées** (2006), ratifiée par la France en **2010**, consacre le droit à la vie autonome et à l''inclusion.\n\n> Le mot juste : on parle de **personne en situation de handicap** — la situation dépend autant de l''environnement que de la personne.', 1),
  ('1cc8e186-2ffc-5148-ba1b-1cbb0be922a1', '4adecebe-8eff-5410-b73d-3ae75a40033c', 'Ce que la loi punit, et pourquoi', E'Racisme, antisémitisme, antitsiganisme, xénophobie et haine anti-LGBT ne sont pas des opinions comme les autres : la loi les punit.\n\n## Trois lois repères\n| La loi | Sa date | Ce qu''elle apporte |\n| Loi **Pleven** | 1er juillet **1972** | Elle punit la **provocation à la haine**, la **diffamation** et l''**injure** à caractère raciste, et permet aux associations de se porter partie civile |\n| Loi **Gayssot** | 13 juillet **1990** | Elle punit la **contestation de crimes contre l''humanité** et aggrave le dispositif de 1972 |\n| Loi du 30 décembre **2004** | 2004 | Elle étend la répression aux motifs **sexistes**, **homophobes** et liés au **handicap** ; elle crée la HALDE, remplacée en 2011 par le Défenseur des droits |\n\n> La loi de 1972 est le premier texte à sortir ces propos du champ de la simple liberté d''expression.\n\n## L''aggravation par mobile\nQuand une infraction — violences, dégradation, harcèlement — est commise **à raison** de l''origine, de la religion, de l''orientation sexuelle ou du handicap de la victime, le **mobile discriminatoire** est une **circonstance aggravante** : la peine encourue est alourdie.\n\n## Où passe la limite\n| Ce qui est permis | Ce qui est puni |\n| **Critiquer une idée**, une doctrine, une religion | **Attaquer une personne ou un groupe** pour ce qu''il est |\n\nL''**abus** de la liberté d''expression est défini par la loi de **1881** sur la presse, complétée par celles de 1972, 1990 et 2004.\n\n## Signaler\n| Le dispositif | Ce qu''il fait |\n| La plateforme **PHAROS** | Elle recueille les signalements de contenus illicites en ligne |\n| L''obligation des plateformes | Retirer promptement les contenus manifestement illicites qui leur sont notifiés |\n\n> Piège fréquent : la loi ne punit pas le fait de **penser**, mais des **actes de langage publics** — provoquer, injurier, diffamer, nier un crime contre l''humanité.', 1),
  ('0dd08b2d-e0b6-591b-9c5d-0d459ab216cf', '367f457f-4a36-501c-9939-6cda87bc1606', 'Ce que la laïcité rend possible', E'La laïcité n''est pas une opinion sur les religions : c''est un principe d''organisation qui rend possible la coexistence pacifique de convictions différentes.\n\n## La loi du 9 décembre 1905\n| L''article | Ce qu''il pose | Ce qu''il garantit |\n| **Article 1er** | La République « assure la **liberté de conscience** » et « garantit le **libre exercice des cultes** » | Une **liberté** |\n| **Article 2** | Elle « **ne reconnaît, ne salarie ni ne subventionne** aucun culte » | Une **neutralité** de l''État |\n\n## Trois exigences indissociables\n| L''exigence | Son contenu |\n| La **liberté de conscience** | Croire, ne pas croire, changer de conviction |\n| La **neutralité** | De l''État et de ses agents : un service public ne prend pas parti |\n| L''**égalité** | Aucune conviction n''ouvre de privilège ni ne justifie de discrimination |\n\n## L''arbitrage de l''État\nLes **articles 27 et 28** de la loi de 1905 encadrent la **police des cultes** : sonneries, manifestations extérieures, emblèmes dans les lieux publics.\n\n> Loin d''être hostile aux religions, cet arbitrage crée les conditions du **pluralisme** : personne n''impose sa croyance dans l''espace commun.\n\n## À l''école\n| La règle | À qui elle s''applique |\n| La **loi du 15 mars 2004** interdit les signes ou tenues manifestant **ostensiblement** une appartenance religieuse | Aux **élèves** des écoles, collèges et lycées publics |\n| La **stricte neutralité** | Aux **agents publics** |\n| La **Charte de la laïcité à l''école** (2013) | Elle rassemble ces règles |\n\n## Et en Europe\nLa **Cour européenne des droits de l''homme** admet des restrictions à la liberté de manifester sa religion lorsqu''elles sont prévues par la loi, poursuivent un but légitime et restent proportionnées.\n\n> La laïcité française n''est donc pas le seul modèle possible en Europe.\n\n> Distinction utile : la laïcité oblige l''**État** à la neutralité ; elle n''impose pas la neutralité aux **citoyens**, libres de manifester leurs convictions dans les limites de l''ordre public.', 1),
  ('59d5500e-cbaa-513b-8ff3-963034dca6c3', '27f47db5-6f14-5c5e-b867-1d2dd49f4583', 'Une seule Nation, des territoires divers', E'L''article 1er de la Constitution tient ensemble deux affirmations qui pourraient sembler contradictoires : la République est indivisible, et son organisation est décentralisée.\n\n## Ce que veut dire « indivisible »\n| L''affirmation | Sa portée |\n| Il n''existe qu''**un seul peuple français** | Le Conseil constitutionnel a censuré en **1991** la mention d''un « peuple corse, composante du peuple français » |\n| La **loi est la même pour tous** | Partout sur le territoire |\n| L''État conserve les fonctions **régaliennes** | Défense, justice, monnaie, police, diplomatie |\n| Les collectivités n''ont **pas de pouvoir législatif** | Elles administrent, elles ne légifèrent pas |\n\n## Ce que veut dire « décentralisée »\nLa décentralisation transfère des compétences à des collectivités dotées de la **personnalité juridique**, d''un **budget** et d''organes **élus**.\n\n| Le principe | Son article | Son contenu |\n| La **libre administration** | Article 72 | Les collectivités s''administrent librement par des conseils élus |\n| La **subsidiarité** | Article 72 | La décision au niveau le plus adapté |\n\nL''ajout de « décentralisée » à l''article 1er date de la révision de **2003**.\n\n## Trois notions à ne pas confondre\n| La notion | Qui exerce | Le pouvoir transféré |\n| **Décentralisation** | Des collectivités **élues** — commune, département, région | Des compétences **administratives** |\n| **Déconcentration** | Les représentants locaux de l''État, le **préfet** | Aucun : l''État garde ses compétences ; le préfet exerce le **contrôle de légalité** |\n| **Fédéralisme** | Des entités fédérées | Un pouvoir **législatif** propre — ce n''est pas le cas en France |\n\n## Qui fait quoi\n| La collectivité | Ses compétences principales |\n| **Commune** | École primaire, urbanisme, état civil, action sociale de proximité |\n| **Département** | Collèges, action sociale (RSA, protection de l''enfance), routes départementales |\n| **Région** | Lycées, formation professionnelle, transports régionaux, développement économique |\n\n> Formule à retenir : la France est un **État unitaire décentralisé**, pas un État fédéral.', 1),
  ('50633b63-d2ed-5f6b-98ab-82ed1d9ae5cb', '9009928d-f52b-592a-9efb-1496daf3785f', 'Quarante ans de transferts, et l’outre-mer', E'Depuis 1982, la République a transféré aux collectivités une part croissante de ce que l''État faisait seul — sans jamais renoncer à l''unité de la Nation.\n\n## Les grandes étapes\n| La date | Le texte | Ce qu''il change |\n| **2 mars 1982** | Loi **Defferre**, « acte I » | Le préfet perd la tutelle *a priori*, remplacée par le **contrôle de légalité** *a posteriori* ; la région devient une collectivité de plein exercice |\n| **2003-2004** | « Acte II » | La décentralisation entre dans la **Constitution** : autonomie financière, référendum local, droit de pétition, expérimentation ; transferts des routes nationales et des personnels techniques |\n| **2014** | Loi **MAPTAM** | Les métropoles |\n| **2015** | Loi **NOTRe** | Compétences clarifiées ; les régions passent de 22 à **13** en métropole |\n\n## L''outre-mer : une unité qui admet des statuts différents\n| L''article | Les territoires | Leur régime |\n| **73** | Guadeloupe, Martinique, Guyane, La Réunion, Mayotte | Les lois de la République, avec des **adaptations** possibles |\n| **74** | Polynésie française, Saint-Barthélemy, Saint-Martin, Saint-Pierre-et-Miquelon, Wallis-et-Futuna | Un **statut particulier** par loi organique, avec une part d''autonomie |\n| Titre **XIII** | Nouvelle-Calédonie | Accord de Nouméa (1998) : citoyenneté calédonienne, « lois du pays », transferts de compétences |\n\n## Les langues régionales\n| L''article | Ce qu''il dispose |\n| **Article 2** | La langue de la République est le **français** |\n| **Article 75-1**, ajouté en **2008** | « Les langues régionales appartiennent au **patrimoine de la France** » |\n\n> Reconnaître une diversité culturelle n''entame pas l''unité juridique : c''est exactement l''équilibre que cherche le programme.\n\n> Idée directrice : l''unité de la Nation n''exige pas l''uniformité des territoires ; elle exige que la loi commune s''applique partout, y compris quand elle s''adapte.', 1),
  ('50e857da-0149-5652-af2f-9ad2c65b54df', 'f4ef57a8-9602-55b3-ae15-dbec3c034cb5', 'Une communauté nationale ouverte', E'Dans la République française, la communauté nationale n''est pas fermée sur une origine : elle est ouverte, marquée par la possibilité d''acquérir la nationalité.\n\n## Deux notions distinctes\n| La notion | Ce qu''elle est |\n| La **nationalité** | Un lien **juridique** entre une personne et un État |\n| La **citoyenneté** | Elle y ajoute des **droits politiques** : voter, être élu |\n\n> En France, la citoyenneté est en principe attachée à la nationalité — avec une exception : les citoyens de l''Union résidant en France votent aux élections **municipales** et **européennes**.\n\n## Comment devient-on français\n| La voie | Sa condition |\n| **Droit du sang** | Au moins un **parent français**, où que l''enfant naisse |\n| **Droit du sol** | Né en France de parents étrangers, français **à 18 ans** s''il y réside depuis ses 11 ans (5 ans au moins) ; anticipation possible à 16 ou 13 ans |\n| **Double droit du sol** | Né en France d''un parent lui-même né en France : français **dès la naissance** |\n| **Naturalisation** | Par décret, après en principe **5 ans** de résidence régulière, sous conditions d''intégration : langue, droits et devoirs, valeurs de la République |\n| **Par mariage** | Par déclaration, après **4 ans** de vie commune |\n\nLa cérémonie d''accueil dans la citoyenneté française remet la **charte des droits et devoirs du citoyen français**.\n\n## La citoyenneté européenne\nInstituée par le traité de **Maastricht** (1992), elle **complète** la citoyenneté nationale sans la remplacer.\n\n| Le droit | Son contenu |\n| **Libre circulation et séjour** | Dans toute l''Union |\n| **Vote et éligibilité** | Aux municipales et aux européennes, dans l''État de résidence |\n| **Protection consulaire** | Par tout État membre |\n| **Pétition** | Au Parlement européen |\n| **Initiative citoyenne européenne** | Un million de signatures dans un quart des États |\n\n> À ne pas confondre : la **nationalité** (lien juridique), la **citoyenneté** (droits politiques), l''**identité** (sentiment d''appartenance). Le programme travaille les deux premières.', 1),
  ('68e87187-fe27-5dac-bee6-7930d64309b7', '65ff5d37-8556-5758-ace0-d6e503f49374', 'Ce dont une nation choisit de se souvenir', E'Les questions mémorielles nourrissent une réflexion sur l''identité de la Nation : tantôt ferment de son unité, tantôt champ d''affrontements.\n\n## Mémoire et histoire\n| La notion | Sa nature | Qui la porte |\n| La **mémoire** | Un rapport **vécu**, sélectif et affectif au passé | Des groupes |\n| L''**histoire** | Une démarche **critique**, fondée sur des sources et le débat scientifique | Une communauté savante |\n\n> Une commémoration n''est pas un cours d''histoire : elle **choisit** ce qu''elle rappelle.\n\n## Les commémorations françaises\n| La date | Ce qu''elle rappelle |\n| **11 novembre** | L''armistice de 1918, et tous les morts pour la France |\n| **8 mai** | La victoire de 1945 |\n| **27 janvier** | Les victimes de la Shoah |\n| **10 mai** | La traite, l''esclavage et leurs abolitions |\n| **18 juin** | L''appel du général de Gaulle |\n\nLe **Panthéon** honore par ses panthéonisations une certaine idée du mérite national.\n\n## Les lois dites mémorielles\n| La loi | Sa date | Ce qu''elle établit |\n| Loi **Gayssot** | 1990 | Elle punit la contestation des crimes contre l''humanité |\n| Loi **Taubira** | 2001 | Elle reconnaît la **traite et l''esclavage** comme **crime contre l''humanité** |\n\nElles font débat : des historiens rappellent qu''il n''appartient pas au législateur d''écrire l''histoire.\n\n> Le **Conseil constitutionnel** a censuré en **2012** la loi pénalisant la négation du génocide arménien, au nom de la **liberté d''expression**.\n\n## Le « devoir de mémoire », et ses limites\n| L''objection | Son argument |\n| Contre la formule | Trop large, elle fige le passé en obligation |\n| Pour la formule | La refuser laisse le champ libre à l''oubli |\n\nLe recueil **Portraits de France** (2021) illustre une autre voie : rendre visibles des figures d''origine étrangère ayant compté dans l''histoire nationale.\n\n## Le patriotisme constitutionnel\nAssociée au philosophe **Jürgen Habermas**, la notion désigne l''attachement des citoyens non à une origine commune, mais aux **principes fondateurs** de la République et de la démocratie — et le souci de les voir mieux réalisés.\n\n> C''est un patriotisme **par adhésion**, ouvert à qui adhère.\n\n> Bon réflexe de copie : distinguer ce qui relève du **droit** (les lois mémorielles), de la **science** (le travail des historiens) et de la **politique** (les commémorations).', 1),
  ('0604678c-49dc-5daf-bf87-213a400f1669', 'cf92abfb-c5c4-5cee-86d2-c26537206f93', 'Protéger la Nation, et s’y engager', E'La communauté nationale se matérialise aussi par l''existence d''une défense nationale, aujourd''hui confrontée à des enjeux renouvelés.\n\n## De la « défense » à la « sécurité nationale »\nLe **Livre blanc de 2008** introduit la notion de **sécurité nationale** : la protection de la population ne se joue plus seulement face à une armée étrangère.\n\n| La menace nouvelle | Ce qu''elle vise |\n| Le **terrorisme** | La population civile |\n| Les **cyberattaques** | Les systèmes d''information |\n| Les crises **sanitaires** | La santé publique |\n| Les atteintes aux **infrastructures critiques** | Énergie, eau, santé, transports |\n\n## Les réponses\n| La menace | Le dispositif |\n| Terrorisme | Le plan **Vigipirate**, l''opération **Sentinelle** |\n| Cyberattaques | L''**ANSSI**, qui protège l''État et les opérateurs d''importance vitale |\n| **Guerres hybrides** | Actions militaires, économiques, cyber et **informationnelles** menées sous le seuil de la guerre déclarée |\n\n> Désinformation, manipulation de l''information, ingérences électorales en font partie : savoir vérifier une information relève ainsi de la défense.\n\n## Une défense européenne\n| Le cadre | Ce qu''il prévoit |\n| L''**OTAN** | La défense collective de l''Alliance |\n| L''**article 42-7** du traité sur l''Union européenne | Une **clause d''assistance mutuelle** entre États membres |\n\nElle a été invoquée pour la première fois par la France après les attentats du **13 novembre 2015**.\n\n## S''engager, aujourd''hui\nDepuis la **suspension de la conscription en 1997**, le lien armée-Nation passe par :\n\n| Le dispositif | Ce qu''il est |\n| Le **recensement à 16 ans** et la **JDC** | Obligatoires |\n| Le **service national universel** | Il vise l''engagement des jeunes et la cohésion nationale |\n| La **réserve opérationnelle** et la réserve citoyenne | Un engagement volontaire |\n| Les parcours de formation | Service militaire volontaire, cadets de la République, classes de défense, lycées labellisés |\n\n> À retenir : la défense n''est plus l''affaire des seuls militaires. La « sécurité nationale » associe l''État, les entreprises, les collectivités — et les citoyens.', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('617c98fc-7d40-5ef9-ae84-70764337f09c'::uuid, 'Quiz — Le troisième mot de la devise', 'EMC', '1re', 'Solidarité et fraternité', 'edbb73b6-fbe8-51be-ac69-8a3706119137'::uuid),
    ('99140644-c2d2-5e04-812f-f3e3eabf98a1'::uuid, 'Quiz — Quand l’écart menace le lien', 'EMC', '1re', 'Lutter contre les inégalités économiques et sociales', 'cd22cca0-130c-598c-85b9-c3ba195ededd'::uuid),
    ('863bd76f-d3aa-5ebb-9f76-1358889417ed'::uuid, 'Quiz — Un principe, des lois, et une réalité qui résiste', 'EMC', '1re', 'L’égalité entre les femmes et les hommes', '0d016bee-b36b-55d2-b6fa-9db5ae08277b'::uuid),
    ('cb7c07f8-41f6-5691-a613-ca3cc195cd06'::uuid, 'Quiz — Ce que le droit appelle une discrimination', 'EMC', '1re', 'Les discriminations : les définir, les mesurer, les combattre', '278e9c80-e4e1-5501-8ac1-eda0f263a074'::uuid),
    ('b51d0ac3-a3d1-57eb-a6d6-f2919bded050'::uuid, 'Quiz — Adapter la société, pas seulement la personne', 'EMC', '1re', 'Vers une société inclusive : la question du handicap', '97d168e4-af70-5f80-a4b6-74f20f344be7'::uuid),
    ('86767891-83f0-547e-84c7-e8ce032f34ce'::uuid, 'Quiz — Ce que la loi punit, et pourquoi', 'EMC', '1re', 'Racisme, antisémitisme, xénophobie et haine anti-LGBT', '1cc8e186-2ffc-5148-ba1b-1cbb0be922a1'::uuid),
    ('d20885ac-de5a-524e-be2f-1f1610a5dbdf'::uuid, 'Quiz — Ce que la laïcité rend possible', 'EMC', '1re', 'Laïcité et pluralisme', '0dd08b2d-e0b6-591b-9c5d-0d459ab216cf'::uuid),
    ('06666c80-95b8-5630-8690-2473929cb5de'::uuid, 'Quiz — Une seule Nation, des territoires divers', 'EMC', '1re', 'Une République indivisible et décentralisée', '59d5500e-cbaa-513b-8ff3-963034dca6c3'::uuid),
    ('c63aa7e3-e245-557d-9d5a-f8abf3d7c709'::uuid, 'Quiz — Quarante ans de transferts, et l’outre-mer', 'EMC', '1re', 'La décentralisation depuis 1982 et la diversité des territoires', '50633b63-d2ed-5f6b-98ab-82ed1d9ae5cb'::uuid),
    ('cd547844-3454-52b8-a8dd-2a86c8f84bbe'::uuid, 'Quiz — Une communauté nationale ouverte', 'EMC', '1re', 'Nationalité et citoyenneté', '50e857da-0149-5652-af2f-9ad2c65b54df'::uuid),
    ('56dd3da6-c693-5517-8407-c8e8642305d2'::uuid, 'Quiz — Ce dont une nation choisit de se souvenir', 'EMC', '1re', 'Les questions mémorielles et le patriotisme constitutionnel', '68e87187-fe27-5dac-bee6-7930d64309b7'::uuid),
    ('a63e5f85-aa35-5786-a522-a0402b1ae5fb'::uuid, 'Quiz — Protéger la Nation, et s’y engager', 'EMC', '1re', 'La défense et la sécurité nationale', '0604678c-49dc-5daf-bf87-213a400f1669'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('7ea21d1e-b472-5828-ad35-086844f5aa7c'::uuid, '617c98fc-7d40-5ef9-ae84-70764337f09c'::uuid, 'Comment l’article 1er de la Constitution qualifie-t-il la République ?', 'mcq', '["Indivisible, laïque, démocratique et sociale","Libre, égalitaire et fraternelle","Unitaire, laïque et décentralisée","Souveraine, sociale et européenne"]'::jsonb, 0, 'Le mot « sociale » engage la Nation dans un projet de justice sociale.', 1),
    ('3f58b32e-44e5-565f-9799-e3347c56214a'::uuid, '617c98fc-7d40-5ef9-ae84-70764337f09c'::uuid, 'Quelle décision reconnait la valeur constitutionnelle de la fraternité ?', 'mcq', '["Conseil constitutionnel, 6 juillet 2018","Conseil d’État, 26 août 2016","Cour de cassation, 1972","Conseil constitutionnel, 1971"]'::jsonb, 0, 'Elle en tire la liberté d’aider autrui dans un but humanitaire.', 2),
    ('15013931-1040-5261-9637-3b57e8689cd2'::uuid, '617c98fc-7d40-5ef9-ae84-70764337f09c'::uuid, 'Quelle est la différence entre une logique d’assurance et une logique d’assistance ?', 'mcq', '["L’assurance suppose d’avoir cotisé, l’assistance non","L’assistance est privée, l’assurance publique","L’assurance est facultative, l’assistance obligatoire","Il n’y en a aucune"]'::jsonb, 0, 'Chômage et retraite relèvent de l’assurance ; le RSA de l’assistance.', 3),
    ('3a1babbc-bbf9-5a69-9179-da002c8a13fa'::uuid, '617c98fc-7d40-5ef9-ae84-70764337f09c'::uuid, 'En quelle année la Sécurité sociale est-elle créée ?', 'mcq', '["1945","1905","1958","1988"]'::jsonb, 0, 'Elle est le socle de la solidarité nationale organisée.', 4),
    ('e5c7f30b-1769-5873-a3fd-71a58b8936d4'::uuid, '617c98fc-7d40-5ef9-ae84-70764337f09c'::uuid, 'La fraternité peut être imposée par la loi comme l’égalité.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est une valeur ; c’est la solidarité, sa traduction organisée, que le droit peut exiger.', 5),
    ('251f8f19-a019-5018-9552-eca80825e090'::uuid, '617c98fc-7d40-5ef9-ae84-70764337f09c'::uuid, 'Qu’a permis concrètement la décision de 2018 sur la fraternité ?', 'mcq', '["Limiter le « délit de solidarité » pour l’aide désintéressée","Créer le RSA","Rendre le don du sang obligatoire","Supprimer l’impôt sur le revenu"]'::jsonb, 0, 'L’aide humanitaire au séjour ne peut plus être punie comme telle.', 6),
    ('bd73cf29-e3ef-5100-a42d-73a9e3827e27'::uuid, '617c98fc-7d40-5ef9-ae84-70764337f09c'::uuid, 'Lequel de ces dispositifs relève d’une solidarité volontaire ?', 'mcq', '["Le don du sang","La cotisation retraite","La CSG","Le RSA"]'::jsonb, 0, 'Il complète, sans les remplacer, les mécanismes obligatoires.', 7),
    ('5f87c9be-723d-564d-9d9e-cf598ba0d760'::uuid, '617c98fc-7d40-5ef9-ae84-70764337f09c'::uuid, 'Les fonds sociaux des établissements scolaires relèvent de la solidarité.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Ils aident les familles à faire face aux frais de scolarité : c’est de l’assistance.', 8),
    ('1f1a2f89-48b0-558f-8f57-436388bf297f'::uuid, '99140644-c2d2-5e04-812f-f3e3eabf98a1'::uuid, 'À quel seuil la pauvreté monétaire est-elle mesurée en France ?', 'mcq', '["60 % du niveau de vie médian","50 % du revenu moyen","Le montant du RSA","Le SMIC net"]'::jsonb, 0, 'C’est la définition retenue au niveau européen.', 1),
    ('141f6419-8f12-5d66-9207-bf8e3876d93e'::uuid, '99140644-c2d2-5e04-812f-f3e3eabf98a1'::uuid, 'Que crée l’État en 2020 pour lutter contre les inégalités territoriales ?', 'mcq', '["L’Agence nationale de la cohésion des territoires","Le Défenseur des droits","La DILCRAH","Le Conseil économique et social"]'::jsonb, 0, 'L’ANCT appuie les collectivités : quartiers prioritaires, ruralité, services publics.', 2),
    ('6fdc79ee-de55-51a3-9d02-ba4b23ee0587'::uuid, '99140644-c2d2-5e04-812f-f3e3eabf98a1'::uuid, 'Que vise la loi SRU de 2000 ?', 'mcq', '["Imposer un quota de logements sociaux aux communes","Créer le RSA","Fixer le SMIC","Interdire les discriminations à l’embauche"]'::jsonb, 0, 'Jusqu’à 25 % dans les zones tendues : un levier de mixité sociale.', 3),
    ('306fe2e4-089e-5971-813d-34305fa2d7f3'::uuid, '99140644-c2d2-5e04-812f-f3e3eabf98a1'::uuid, 'Le niveau de vie médian et le revenu moyen désignent la même chose.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Le médian partage la population en deux moitiés ; la moyenne est tirée par les hauts revenus.', 4),
    ('0b13fa61-197c-5898-b711-7de01e5175e6'::uuid, '99140644-c2d2-5e04-812f-f3e3eabf98a1'::uuid, 'Quel effet la redistribution a-t-elle sur les écarts de revenus ?', 'mcq', '["Elle les réduit d’environ un tiers","Elle les supprime","Elle les augmente","Elle est sans effet mesurable"]'::jsonb, 0, 'Impôts progressifs et prestations sociales agissent ensemble.', 5),
    ('ad83e827-c174-5a25-9c71-729aeb76c212'::uuid, '99140644-c2d2-5e04-812f-f3e3eabf98a1'::uuid, 'Pourquoi les inégalités menacent-elles la démocratie ?', 'mcq', '["Elles minent la confiance et creusent l’écart de participation","Elles empêchent d’organiser des élections","Elles suppriment le droit de vote","Elles rendent la Constitution caduque"]'::jsonb, 0, 'L’abstention est plus forte dans les milieux populaires, ce qui déforme la représentation.', 6),
    ('65f5e00a-aa4a-511d-ade1-d5f5a5b70e88'::uuid, '99140644-c2d2-5e04-812f-f3e3eabf98a1'::uuid, 'La pauvreté se mesure uniquement en euros.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'La pauvreté en conditions de vie prend en compte logement, santé, mobilité, numérique.', 7),
    ('f75bfd1a-acd2-5406-8672-ca1e7de95d54'::uuid, '99140644-c2d2-5e04-812f-f3e3eabf98a1'::uuid, 'Qu’est-ce que la prime d’activité ?', 'mcq', '["Un complément de revenu pour les travailleurs modestes","Une prime versée aux entreprises","Une aide au logement","Une allocation chômage"]'::jsonb, 0, 'Elle vise à ce que le travail reste plus avantageux que l’inactivité.', 8),
    ('f6ba252f-db21-5b5e-804a-445588d62016'::uuid, '863bd76f-d3aa-5ebb-9f76-1358889417ed'::uuid, 'En quelle année les femmes obtiennent-elles le droit de vote en France ?', 'mcq', '["1944","1936","1946","1965"]'::jsonb, 0, 'Ordonnance de 1944 ; premier vote effectif en 1945.', 1),
    ('bfc61167-4f1d-5d90-8398-9d267f6c881d'::uuid, '863bd76f-d3aa-5ebb-9f76-1358889417ed'::uuid, 'Que permet la loi de 1965 aux femmes mariées ?', 'mcq', '["Travailler et ouvrir un compte sans l’autorisation du mari","Voter aux élections locales","Divorcer par consentement mutuel","Accéder à la fonction publique"]'::jsonb, 0, 'Une étape décisive de l’autonomie juridique.', 2),
    ('75135b4f-fb79-5347-bfdc-b81ee7fd723b'::uuid, '863bd76f-d3aa-5ebb-9f76-1358889417ed'::uuid, 'Qu’est-ce qui a été inscrit dans la Constitution le 4 mars 2024 ?', 'mcq', '["La liberté garantie de recourir à l’IVG","La parité dans les entreprises","L’égalité salariale","Le congé parental partagé"]'::jsonb, 0, 'La révision complète l’article 34 de la Constitution.', 3),
    ('dd47ad79-a3f6-5ecf-b1a7-24a189c341f1'::uuid, '863bd76f-d3aa-5ebb-9f76-1358889417ed'::uuid, 'À quoi sert l’index de l’égalité professionnelle (2019) ?', 'mcq', '["Mesurer et publier les écarts femmes-hommes en entreprise","Fixer un quota de femmes cadres","Calculer les retraites","Sanctionner le harcèlement"]'::jsonb, 0, 'Il est obligatoire dans les entreprises d’au moins 50 salariés.', 4),
    ('1a473cd4-5791-5b19-b3f1-11f7e3db14e2'::uuid, '863bd76f-d3aa-5ebb-9f76-1358889417ed'::uuid, 'À poste et temps de travail comparables, l’écart de rémunération est nul.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il subsiste de l’ordre de 4 %, contre environ 20 % tous temps de travail confondus.', 5),
    ('f56c9fc0-74b7-5375-8e65-7b61da47c218'::uuid, '863bd76f-d3aa-5ebb-9f76-1358889417ed'::uuid, 'Quel numéro national écoute les femmes victimes de violences ?', 'mcq', '["Le 3919","Le 3020","Le 119","Le 17"]'::jsonb, 0, 'Gratuit et disponible 24 h/24.', 6),
    ('03c85070-e76f-51f8-933f-924ac895b2a4'::uuid, '863bd76f-d3aa-5ebb-9f76-1358889417ed'::uuid, 'Qu’appelle-t-on le « plafond de verre » ?', 'mcq', '["Les obstacles invisibles à l’accès aux postes de direction","L’écart de salaire à l’embauche","Le temps partiel imposé","La ségrégation des filières scolaires"]'::jsonb, 0, 'Il désigne ce qui bloque la progression sans être écrit nulle part.', 7),
    ('9599fc3d-0637-5e2c-8d97-6866df8b7ede'::uuid, '863bd76f-d3aa-5ebb-9f76-1358889417ed'::uuid, 'La Convention d’Istanbul porte sur les violences faites aux femmes.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Adoptée en 2011 par le Conseil de l’Europe, ratifiée par la France en 2014.', 8),
    ('65c0b0b6-e480-54ae-bc36-8bae3349268b'::uuid, 'cb7c07f8-41f6-5691-a613-ca3cc195cd06'::uuid, 'Quel article du Code pénal définit la discrimination ?', 'mcq', '["L’article 225-1","L’article 1er","L’article 434-3","L’article 121-1"]'::jsonb, 0, 'Il énumère les critères prohibés, aujourd’hui plus de vingt-cinq.', 1),
    ('4b609c14-ce83-5c94-bf76-5e93f1aa9eb5'::uuid, 'cb7c07f8-41f6-5691-a613-ca3cc195cd06'::uuid, 'Quelle peine maximale encourt l’auteur d’une discrimination ?', 'mcq', '["3 ans de prison et 45 000 € d’amende","1 an et 15 000 €","5 ans et 75 000 €","Une simple amende"]'::jsonb, 0, 'Les peines sont aggravées lorsque l’auteur est dépositaire de l’autorité publique.', 2),
    ('c2e1ce41-b022-5c8c-a117-a37b65950268'::uuid, 'cb7c07f8-41f6-5691-a613-ca3cc195cd06'::uuid, 'Qu’est-ce qu’une discrimination indirecte ?', 'mcq', '["Une règle neutre en apparence qui défavorise un groupe","Une discrimination commise par un tiers","Une discrimination non intentionnelle et donc légale","Une discrimination hors du travail"]'::jsonb, 0, 'Elle est illicite au même titre que la discrimination directe.', 3),
    ('9b48e323-2bda-571f-93e5-8403b5e3e989'::uuid, 'cb7c07f8-41f6-5691-a613-ca3cc195cd06'::uuid, 'Quelle autorité indépendante peut être saisie gratuitement par une victime ?', 'mcq', '["Le Défenseur des droits","Le Conseil constitutionnel","La CNIL","Le Conseil d’État"]'::jsonb, 0, 'Créé en 2011, il a rang d’autorité constitutionnelle.', 4),
    ('db5d92f0-f9fc-5c22-9282-19f7118d7d6b'::uuid, 'cb7c07f8-41f6-5691-a613-ca3cc195cd06'::uuid, 'Le testing est admis comme mode de preuve d’une discrimination.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Il compare deux candidatures identiques ne différant que par le critère suspecté.', 5),
    ('686d7917-f6b0-521f-af71-2723822cb891'::uuid, 'cb7c07f8-41f6-5691-a613-ca3cc195cd06'::uuid, 'Que fait la DILCRAH ?', 'mcq', '["Elle coordonne la lutte contre le racisme, l’antisémitisme et la haine anti-LGBT","Elle juge les discriminations","Elle indemnise les victimes","Elle publie les statistiques ethniques"]'::jsonb, 0, 'C’est une délégation interministérielle, rattachée au Premier ministre.', 6),
    ('83044324-11d5-5911-bc7c-c4b80c85c7b1'::uuid, 'cb7c07f8-41f6-5691-a613-ca3cc195cd06'::uuid, 'Que change l’aménagement de la charge de la preuve ?', 'mcq', '["La victime présente des faits, au défendeur de se justifier","La victime doit tout prouver seule","Le juge enquête à la place des parties","La preuve n’est plus nécessaire"]'::jsonb, 0, 'Sans lui, presque aucune discrimination ne serait établie.', 7),
    ('b3129d76-ac12-5426-b165-43a216a3dce0'::uuid, 'cb7c07f8-41f6-5691-a613-ca3cc195cd06'::uuid, 'Toute distinction entre deux personnes est une discrimination.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il faut un critère prohibé ET une situation visée par la loi (emploi, logement, service…).', 8),
    ('b05b607f-f6f8-5e4f-b569-ac74c9a704bc'::uuid, 'b51d0ac3-a3d1-57eb-a6d6-f2919bded050'::uuid, 'Quelle loi fonde l’égalité des droits et des chances des personnes handicapées ?', 'mcq', '["La loi du 11 février 2005","La loi du 30 juin 1975","La loi du 10 juillet 1987","La loi du 8 juillet 2013"]'::jsonb, 0, 'Elle pose l’accessibilité, la compensation et la MDPH.', 1),
    ('86306aa6-7ba0-5469-aac5-8cfdec245cd1'::uuid, 'b51d0ac3-a3d1-57eb-a6d6-f2919bded050'::uuid, 'Que désigne le sigle MDPH ?', 'mcq', '["Maison départementale des personnes handicapées","Ministère du handicap","Mission d’aide au handicap","Mutuelle des personnes handicapées"]'::jsonb, 0, 'C’est le guichet unique départemental créé par la loi de 2005.', 2),
    ('0a6bf7e9-1a42-54ac-988a-b63e2f0ae653'::uuid, 'b51d0ac3-a3d1-57eb-a6d6-f2919bded050'::uuid, 'Quel quota d’emploi de travailleurs handicapés la loi de 1987 impose-t-elle ?', 'mcq', '["6 % des effectifs","3 % des effectifs","10 % des effectifs","Aucun quota, une simple incitation"]'::jsonb, 0, 'Il s’applique aux employeurs d’au moins 20 salariés.', 3),
    ('5e5965ff-fefc-5739-bc66-0b8326afb2fb'::uuid, 'b51d0ac3-a3d1-57eb-a6d6-f2919bded050'::uuid, 'Selon l’approche sociale, d’où vient le handicap ?', 'mcq', '["De la rencontre entre une déficience et un environnement inadapté","De la seule déficience de la personne","D’un défaut de soins","D’un manque de volonté individuelle"]'::jsonb, 0, 'C’est pourquoi on adapte l’environnement, et pas seulement la personne.', 4),
    ('33190076-507f-5e2c-8790-154a70cd5f71'::uuid, 'b51d0ac3-a3d1-57eb-a6d6-f2919bded050'::uuid, 'La loi de 2005 pose le principe de la scolarisation en milieu ordinaire.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Dans l’établissement le plus proche du domicile, avec un PPS et, si besoin, un AESH.', 5),
    ('e760b162-c739-5934-b877-0ae7148f5581'::uuid, 'b51d0ac3-a3d1-57eb-a6d6-f2919bded050'::uuid, 'Que fait un AESH ?', 'mcq', '["Il accompagne un élève en situation de handicap en classe","Il enseigne dans un établissement spécialisé","Il évalue le taux d’incapacité","Il verse les prestations"]'::jsonb, 0, 'Accompagnant d’élèves en situation de handicap, il intervient en milieu ordinaire.', 6),
    ('95b6c093-0ddf-511c-81b1-73ec0b3b0049'::uuid, 'b51d0ac3-a3d1-57eb-a6d6-f2919bded050'::uuid, 'Quel texte international la France a-t-elle ratifié en 2010 ?', 'mcq', '["La Convention de l’ONU relative aux droits des personnes handicapées","La Convention d’Istanbul","La Charte sociale européenne","La Convention de Genève"]'::jsonb, 0, 'Adoptée en 2006, elle consacre le droit à la vie autonome et à l’inclusion.', 7),
    ('8b1bdcb8-5f1e-515e-ba9b-697660870c8c'::uuid, 'b51d0ac3-a3d1-57eb-a6d6-f2919bded050'::uuid, 'On dit « personne en situation de handicap » parce que la situation dépend aussi de l’environnement.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'La formule traduit l’approche sociale du handicap.', 8),
    ('42acce4a-913a-5aeb-bf29-872390907936'::uuid, '86767891-83f0-547e-84c7-e8ce032f34ce'::uuid, 'Que punit la loi Pleven du 1er juillet 1972 ?', 'mcq', '["La provocation à la haine, la diffamation et l’injure racistes","Le négationnisme","Les discriminations à l’embauche","Les fausses nouvelles"]'::jsonb, 0, 'Elle permet aussi aux associations de se porter partie civile.', 1),
    ('5e3e65bd-aab5-587a-bc89-726008a9cf0f'::uuid, '86767891-83f0-547e-84c7-e8ce032f34ce'::uuid, 'Que punit la loi Gayssot du 13 juillet 1990 ?', 'mcq', '["La contestation de crimes contre l’humanité","Le port de signes religieux à l’école","Le refus de louer un logement","L’injure homophobe"]'::jsonb, 0, 'Le négationnisme est un délit depuis ce texte.', 2),
    ('ca060a4d-56c7-50d6-9435-eb1dd03665ef'::uuid, '86767891-83f0-547e-84c7-e8ce032f34ce'::uuid, 'Qu’ajoute la loi du 30 décembre 2004 ?', 'mcq', '["La répression des injures sexistes, homophobes et handiphobes","La création du Défenseur des droits","L’interdiction du testing","La liberté de la presse"]'::jsonb, 0, 'Elle crée aussi la HALDE, remplacée en 2011 par le Défenseur des droits.', 3),
    ('b5338b9c-f18a-5ca4-9b5d-c972f226cedc'::uuid, '86767891-83f0-547e-84c7-e8ce032f34ce'::uuid, 'Qu’est-ce qu’une circonstance aggravante à mobile discriminatoire ?', 'mcq', '["Une peine alourdie quand l’infraction vise la victime pour ce qu’elle est","Une infraction distincte du Code pénal","Une aggravation réservée aux récidivistes","Une amende doublée automatiquement"]'::jsonb, 0, 'Elle s’applique aux violences, dégradations ou harcèlements à motif raciste, homophobe, etc.', 4),
    ('d61ad12e-c348-532a-9b3b-340a72fefd27'::uuid, '86767891-83f0-547e-84c7-e8ce032f34ce'::uuid, 'La loi punit les opinions racistes gardées pour soi.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle punit des actes de langage publics : provoquer, injurier, diffamer, nier.', 5),
    ('5efd051d-2b07-5e66-93c9-62c843ed4ee7'::uuid, '86767891-83f0-547e-84c7-e8ce032f34ce'::uuid, 'Quel texte fixe le cadre général des abus de la liberté d’expression ?', 'mcq', '["La loi du 29 juillet 1881 sur la liberté de la presse","La loi de 1905","La loi de 2004 sur la laïcité","Le Code civil"]'::jsonb, 0, 'Les lois de 1972, 1990 et 2004 la complètent.', 6),
    ('832cef1b-75db-59e0-adb1-b6f078b9757a'::uuid, '86767891-83f0-547e-84c7-e8ce032f34ce'::uuid, 'À quoi sert la plateforme PHAROS ?', 'mcq', '["Signaler des contenus illicites en ligne","Porter plainte pour discrimination à l’embauche","Saisir le Défenseur des droits","Demander le retrait d’un compte bancaire"]'::jsonb, 0, 'Elle est gérée par la police et la gendarmerie.', 7),
    ('342ce4d4-ccc6-540c-9d24-7066f17fe28c'::uuid, '86767891-83f0-547e-84c7-e8ce032f34ce'::uuid, 'L’antitsiganisme désigne la haine visant les personnes roms et gens du voyage.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Le programme le nomme explicitement, aux côtés du racisme et de l’antisémitisme.', 8),
    ('f8d46ea2-0388-5333-95e8-545dcbd8c972'::uuid, 'd20885ac-de5a-524e-be2f-1f1610a5dbdf'::uuid, 'Que garantit l’article 1er de la loi de 1905 ?', 'mcq', '["La liberté de conscience et le libre exercice des cultes","La suppression des cultes","Le financement des cultes reconnus","La neutralité des citoyens"]'::jsonb, 0, 'L’article 2 ajoute que la République ne reconnait ni ne subventionne aucun culte.', 1),
    ('f7db0016-5be3-5542-b80d-a5976ab6e53a'::uuid, 'd20885ac-de5a-524e-be2f-1f1610a5dbdf'::uuid, 'Quelle loi interdit les signes religieux ostensibles aux élèves des écoles publiques ?', 'mcq', '["La loi du 15 mars 2004","La loi du 9 décembre 1905","La loi du 13 juillet 1990","La loi du 24 août 2021"]'::jsonb, 0, 'Elle vise les écoles, collèges et lycées publics.', 2),
    ('7702a4c2-cf88-5910-b70a-c8ec00ff5f62'::uuid, 'd20885ac-de5a-524e-be2f-1f1610a5dbdf'::uuid, 'À quoi servent les articles 27 et 28 de la loi de 1905 ?', 'mcq', '["Encadrer la police des cultes et les manifestations extérieures","Financer les lieux de culte","Fixer le calendrier des fêtes","Interdire les processions"]'::jsonb, 0, 'Cet arbitrage crée les conditions du pluralisme.', 3),
    ('2a2653e1-1222-5568-ac4b-dcf987fa9667'::uuid, 'd20885ac-de5a-524e-be2f-1f1610a5dbdf'::uuid, 'La laïcité impose la neutralité aux citoyens.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle l’impose à l’État et à ses agents ; les citoyens restent libres, dans les limites de l’ordre public.', 4),
    ('5c001a1a-7027-56c1-92db-07e2729233e1'::uuid, 'd20885ac-de5a-524e-be2f-1f1610a5dbdf'::uuid, 'Quelles sont les trois exigences de la laïcité ?', 'mcq', '["Liberté de conscience, neutralité de l’État, égalité","Tolérance, morale, tradition","Neutralité des citoyens, silence religieux, laïcisation","Séparation, subvention, contrôle"]'::jsonb, 0, 'Elles sont indissociables : retirer l’une déforme les deux autres.', 5),
    ('6c85fab2-5673-5329-8019-e1b21b831b26'::uuid, 'd20885ac-de5a-524e-be2f-1f1610a5dbdf'::uuid, 'Que dit la Cour européenne des droits de l’homme sur la liberté religieuse ?', 'mcq', '["Des restrictions sont possibles si elles sont légales et proportionnées","Elle est absolue et sans limite","Elle relève des seuls États","Elle interdit toute laïcité"]'::jsonb, 0, 'Les États disposent d’une marge nationale d’appréciation.', 6),
    ('62297c3c-5eb7-5ea0-9295-6a8b29f6e7bd'::uuid, 'd20885ac-de5a-524e-be2f-1f1610a5dbdf'::uuid, 'Quel document rassemble les règles de laïcité à l’école ?', 'mcq', '["La Charte de la laïcité à l’école (2013)","Le Code de l’éducation seul","La loi de 1905","Le règlement intérieur type"]'::jsonb, 0, 'Elle est affichée dans les établissements et expliquée aux élèves.', 7),
    ('88edacfa-baf4-56bf-be42-798df3fee247'::uuid, 'd20885ac-de5a-524e-be2f-1f1610a5dbdf'::uuid, 'La laïcité est hostile aux religions.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle garantit au contraire le libre exercice des cultes, en interdisant à l’État de prendre parti.', 8),
    ('fd6a954f-6c92-575e-8fa7-20f76e3f017d'::uuid, '06666c80-95b8-5630-8690-2473929cb5de'::uuid, 'Quelle révision constitutionnelle inscrit que l’organisation de la République est décentralisée ?', 'mcq', '["Celle de 2003","Celle de 1958","Celle de 1982","Celle de 2008"]'::jsonb, 0, 'La phrase est ajoutée à l’article 1er de la Constitution.', 1),
    ('f77d1466-01cb-57ce-9faf-4129b85b3a50'::uuid, '06666c80-95b8-5630-8690-2473929cb5de'::uuid, 'Qu’a censuré le Conseil constitutionnel en 1991 ?', 'mcq', '["La mention d’un « peuple corse, composante du peuple français »","Le statut de la Nouvelle-Calédonie","La loi Defferre","La reconnaissance des langues régionales"]'::jsonb, 0, 'Il n’existe qu’un seul peuple français : c’est l’indivisibilité.', 2),
    ('a88d7639-8f0b-552d-a577-893a26cec2fe'::uuid, '06666c80-95b8-5630-8690-2473929cb5de'::uuid, 'Quelle est la différence entre décentralisation et déconcentration ?', 'mcq', '["La première transfère à des élus locaux, la seconde à des agents de l’État","Elles sont synonymes","La première concerne l’outre-mer seulement","La seconde crée des collectivités"]'::jsonb, 0, 'Le préfet, agent de l’État, incarne la déconcentration et exerce le contrôle de légalité.', 3),
    ('ebbae619-9b31-5fb3-a80d-55b57c7bc8a4'::uuid, '06666c80-95b8-5630-8690-2473929cb5de'::uuid, 'Quelle collectivité a la charge des lycées ?', 'mcq', '["La région","Le département","La commune","L’État"]'::jsonb, 0, 'Le département a les collèges, la commune les écoles primaires.', 4),
    ('f8cb7951-4d7b-5a8c-90d9-8e85bb1a7683'::uuid, '06666c80-95b8-5630-8690-2473929cb5de'::uuid, 'Les collectivités territoriales disposent d’un pouvoir législatif propre.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elles s’administrent librement mais ne votent pas la loi : la France est un État unitaire.', 5),
    ('9b7bb816-1674-5a4e-9178-8bee6fef3e35'::uuid, '06666c80-95b8-5630-8690-2473929cb5de'::uuid, 'Que garantit l’article 72 de la Constitution aux collectivités ?', 'mcq', '["La libre administration par des conseils élus","Le droit de faire des lois","L’indépendance financière totale","Le droit de sécession"]'::jsonb, 0, 'La libre administration s’exerce dans les conditions prévues par la loi.', 6),
    ('4200d105-950f-59ef-9a29-e1abaf190d55'::uuid, '06666c80-95b8-5630-8690-2473929cb5de'::uuid, 'Qui exerce le contrôle de légalité des actes des collectivités ?', 'mcq', '["Le préfet","Le maire","Le Conseil constitutionnel","Le président de région"]'::jsonb, 0, 'Il peut déférer un acte illégal au tribunal administratif.', 7),
    ('99a0d98e-21b1-5bb9-a604-74942a17a86a'::uuid, '06666c80-95b8-5630-8690-2473929cb5de'::uuid, 'Le principe de subsidiarité veut que la décision soit prise au niveau le plus adapté.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Il est inscrit à l’article 72 depuis 2003.', 8),
    ('cdeec7bc-5f7f-53f8-9432-7deb8529e58e'::uuid, 'c63aa7e3-e245-557d-9d5a-f8abf3d7c709'::uuid, 'Quelle loi ouvre l’acte I de la décentralisation ?', 'mcq', '["La loi Defferre du 2 mars 1982","La loi NOTRe de 2015","La loi MAPTAM de 2014","La révision de 2003"]'::jsonb, 0, 'Elle supprime la tutelle a priori du préfet et fait de la région une collectivité de plein exercice.', 1),
    ('029bac9e-949c-5b61-8ce0-850963c86bbf'::uuid, 'c63aa7e3-e245-557d-9d5a-f8abf3d7c709'::uuid, 'Qu’apporte l’acte II de 2003-2004 ?', 'mcq', '["La décentralisation entre dans la Constitution","La création des départements","La suppression des régions","La fin du contrôle de légalité"]'::jsonb, 0, 'Autonomie financière, référendum local, droit de pétition, expérimentation.', 2),
    ('514e837f-0457-522f-be36-b7371341758d'::uuid, 'c63aa7e3-e245-557d-9d5a-f8abf3d7c709'::uuid, 'Combien de régions compte la France métropolitaine depuis 2016 ?', 'mcq', '["13","22","18","26"]'::jsonb, 0, 'La loi NOTRe de 2015 a réduit leur nombre de 22 à 13.', 3),
    ('8e1e6dcb-f9e4-5ab0-9ac3-e1520d01eee5'::uuid, 'c63aa7e3-e245-557d-9d5a-f8abf3d7c709'::uuid, 'Que prévoit l’article 73 de la Constitution ?', 'mcq', '["Les lois s’appliquent en outre-mer avec des adaptations possibles","Les collectivités d’outre-mer votent leurs lois","La Nouvelle-Calédonie est indépendante","L’outre-mer est hors du territoire national"]'::jsonb, 0, 'Il concerne les départements et régions d’outre-mer.', 4),
    ('2259a846-c623-5cee-af14-e3ab1cbbb48d'::uuid, 'c63aa7e3-e245-557d-9d5a-f8abf3d7c709'::uuid, 'La Nouvelle-Calédonie relève d’un titre spécifique de la Constitution.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Le titre XIII, issu de l’accord de Nouméa de 1998.', 5),
    ('10201125-3242-5756-bb48-696c17a7ad92'::uuid, 'c63aa7e3-e245-557d-9d5a-f8abf3d7c709'::uuid, 'Que dit l’article 75-1 de la Constitution ?', 'mcq', '["Les langues régionales appartiennent au patrimoine de la France","Le français est la langue de la République","Les langues régionales sont langues officielles","L’enseignement bilingue est obligatoire"]'::jsonb, 0, 'Ajouté en 2008 ; l’article 2 maintient le français comme langue de la République.', 6),
    ('7a51154e-758b-51b0-a0fd-0ff35715e499'::uuid, 'c63aa7e3-e245-557d-9d5a-f8abf3d7c709'::uuid, 'Quelle collectivité gère le RSA et la protection de l’enfance ?', 'mcq', '["Le département","La région","La commune","L’État"]'::jsonb, 0, 'L’action sociale est le cœur des compétences départementales.', 7),
    ('23216707-e69c-5063-9a0f-fd8d22d249e5'::uuid, 'c63aa7e3-e245-557d-9d5a-f8abf3d7c709'::uuid, 'Reconnaitre la diversité des territoires contredit l’indivisibilité de la République.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'L’unité tient à la loi commune, pas à l’uniformité des statuts.', 8),
    ('da4f02ca-a528-59be-b839-b2bc98c4a57a'::uuid, 'cd547844-3454-52b8-a8dd-2a86c8f84bbe'::uuid, 'Sur quoi repose le droit du sang ?', 'mcq', '["La nationalité d’au moins un parent","Le lieu de naissance","La durée de résidence","Le mariage"]'::jsonb, 0, 'L’enfant est français où qu’il naisse.', 1),
    ('c6e5c924-fb1c-5306-a563-ba14a847dc08'::uuid, 'cd547844-3454-52b8-a8dd-2a86c8f84bbe'::uuid, 'À quel âge l’enfant né en France de parents étrangers devient-il français de plein droit ?', 'mcq', '["À 18 ans, sous condition de résidence","À la naissance","À 13 ans","Jamais sans naturalisation"]'::jsonb, 0, 'Il doit résider en France depuis l’âge de 11 ans, au moins 5 ans.', 2),
    ('af9277fe-b82b-5eef-bc7e-0955da401ffb'::uuid, 'cd547844-3454-52b8-a8dd-2a86c8f84bbe'::uuid, 'Après combien d’années de résidence régulière peut-on en principe demander la naturalisation ?', 'mcq', '["5 ans","2 ans","10 ans","15 ans"]'::jsonb, 0, 'Des réductions existent, notamment pour les diplômés d’un établissement français.', 3),
    ('6dc4136e-3b56-58ef-9a80-f9cf3a6c7918'::uuid, 'cd547844-3454-52b8-a8dd-2a86c8f84bbe'::uuid, 'Quel traité institue la citoyenneté européenne ?', 'mcq', '["Le traité de Maastricht (1992)","Le traité de Rome (1957)","Le traité de Lisbonne (2007)","L’Acte unique (1986)"]'::jsonb, 0, 'Elle complète la citoyenneté nationale sans la remplacer.', 4),
    ('d10f3640-2efd-592f-8721-7acbaa4b8799'::uuid, 'cd547844-3454-52b8-a8dd-2a86c8f84bbe'::uuid, 'Un citoyen européen résidant en France peut voter aux élections présidentielles françaises.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il vote aux municipales et aux européennes, pas aux élections nationales.', 5),
    ('a98fee73-d8e0-59f7-b377-105c03fa314b'::uuid, 'cd547844-3454-52b8-a8dd-2a86c8f84bbe'::uuid, 'Qu’est-ce que le double droit du sol ?', 'mcq', '["Être français dès la naissance si un parent est né en France","Cumuler deux nationalités","Naitre à l’étranger de parents français","Acquérir la nationalité par mariage"]'::jsonb, 0, 'Le lien avec le territoire s’établit alors sur deux générations.', 6),
    ('475419b6-b778-55bf-962e-4cb54c296c3f'::uuid, 'cd547844-3454-52b8-a8dd-2a86c8f84bbe'::uuid, 'Que garantit la protection consulaire au citoyen européen ?', 'mcq', '["L’aide de tout État membre à l’étranger","Un passeport européen unique","Le droit d’asile","La double nationalité"]'::jsonb, 0, 'Lorsque son propre État n’est pas représenté dans le pays.', 7),
    ('b681da7a-3c5c-5172-9f29-bc5cd6040ea4'::uuid, 'cd547844-3454-52b8-a8dd-2a86c8f84bbe'::uuid, 'La nationalité et la citoyenneté sont exactement la même chose.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'La citoyenneté ajoute les droits politiques ; l’Union européenne en donne un exemple dissocié.', 8),
    ('bb90aaeb-797b-55de-9a2d-54692f20f132'::uuid, '56dd3da6-c693-5517-8407-c8e8642305d2'::uuid, 'Quelle est la différence entre mémoire et histoire ?', 'mcq', '["La mémoire est vécue et sélective, l’histoire est critique et fondée sur des sources","Aucune, ce sont deux mots pour la même chose","L’histoire est officielle, la mémoire est privée","La mémoire est écrite, l’histoire est orale"]'::jsonb, 0, 'Une commémoration choisit ce qu’elle rappelle : ce n’est pas un cours d’histoire.', 1),
    ('b48ee272-00ae-5f5c-9ebb-d73c09d26486'::uuid, '56dd3da6-c693-5517-8407-c8e8642305d2'::uuid, 'Que reconnait la loi Taubira de 2001 ?', 'mcq', '["La traite et l’esclavage comme crime contre l’humanité","Le génocide arménien","La Shoah comme crime imprescriptible","Les crimes de la colonisation"]'::jsonb, 0, 'La journée du 10 mai lui est associée.', 2),
    ('b1519b75-c320-529e-98d3-4308c6861890'::uuid, '56dd3da6-c693-5517-8407-c8e8642305d2'::uuid, 'Qu’a censuré le Conseil constitutionnel en 2012 ?', 'mcq', '["La loi pénalisant la négation du génocide arménien","La loi Gayssot","La loi Taubira","La loi de 1905"]'::jsonb, 0, 'Au nom de la liberté d’expression.', 3),
    ('47511cf9-4091-5c7d-b8ea-e56637eaf90d'::uuid, '56dd3da6-c693-5517-8407-c8e8642305d2'::uuid, 'Que commémore le 27 janvier ?', 'mcq', '["La mémoire des victimes de la Shoah","L’armistice de 1918","L’abolition de l’esclavage","La victoire de 1945"]'::jsonb, 0, 'Journée internationale, à la date de la libération d’Auschwitz.', 4),
    ('a88ccdcc-1c5b-54eb-af1d-7f7bc9f1eea4'::uuid, '56dd3da6-c693-5517-8407-c8e8642305d2'::uuid, 'Le patriotisme constitutionnel repose sur une origine commune.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il repose sur l’adhésion aux principes fondateurs de la République et de la démocratie.', 5),
    ('5f2acca1-b121-56aa-b1b7-614d2c5dc062'::uuid, '56dd3da6-c693-5517-8407-c8e8642305d2'::uuid, 'Quel recueil met en lumière des personnalités d’origine étrangère de l’histoire nationale ?', 'mcq', '["Portraits de France","Le Panthéon des Français","Les Grands Hommes","Mémoires de la Nation"]'::jsonb, 0, 'Publié en 2021, il sert de support en classe.', 6),
    ('56739da4-6de6-5782-ad0d-4112cf3e3619'::uuid, '56dd3da6-c693-5517-8407-c8e8642305d2'::uuid, 'Pourquoi les lois mémorielles font-elles débat ?', 'mcq', '["Parce qu’il n’appartient pas au législateur d’écrire l’histoire","Parce qu’elles sont inconstitutionnelles par nature","Parce qu’elles interdisent les commémorations","Parce qu’elles ne prévoient aucune sanction"]'::jsonb, 0, 'C’est l’argument principal des historiens qui les contestent.', 7),
    ('87917d27-dbca-5dad-b00a-2fb0a7e8be94'::uuid, '56dd3da6-c693-5517-8407-c8e8642305d2'::uuid, 'Le 10 mai est la journée de mémoire de la traite, de l’esclavage et de leurs abolitions.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Elle est associée à la loi Taubira du 21 mai 2001.', 8),
    ('11592550-1e64-558e-acb5-4a70a8e730ad'::uuid, 'a63e5f85-aa35-5786-a522-a0402b1ae5fb'::uuid, 'Quel document introduit la notion de « sécurité nationale » ?', 'mcq', '["Le Livre blanc sur la défense et la sécurité nationale de 2008","La Constitution de 1958","Le traité de Lisbonne","La loi de programmation militaire de 1997"]'::jsonb, 0, 'Il élargit la défense au terrorisme, au cyber et aux crises majeures.', 1),
    ('100667c5-56b9-5fa8-ad77-3ad249216f89'::uuid, 'a63e5f85-aa35-5786-a522-a0402b1ae5fb'::uuid, 'Que désigne une « guerre hybride » ?', 'mcq', '["Une combinaison d’actions militaires, cyber, économiques et informationnelles","Une guerre menée par deux armées régulières","Un conflit civil","Une guerre sans armes"]'::jsonb, 0, 'Elle se joue souvent sous le seuil de la guerre déclarée.', 2),
    ('0d4444fc-5214-5a10-849d-70ecfc43cbf0'::uuid, 'a63e5f85-aa35-5786-a522-a0402b1ae5fb'::uuid, 'Quelle agence protège l’État français contre les cyberattaques ?', 'mcq', '["L’ANSSI","La DGSE","La CNIL","L’ANCT"]'::jsonb, 0, 'Elle protège aussi les opérateurs d’importance vitale.', 3),
    ('06b48b4a-0687-575e-a955-79aaa6ee9238'::uuid, 'a63e5f85-aa35-5786-a522-a0402b1ae5fb'::uuid, 'Que prévoit l’article 42-7 du traité sur l’Union européenne ?', 'mcq', '["Une clause d’assistance mutuelle entre États membres","La création d’une armée européenne","Le budget de la défense","L’adhésion automatique à l’OTAN"]'::jsonb, 0, 'La France l’a invoquée après les attentats du 13 novembre 2015.', 4),
    ('89f2d044-6d73-5702-b88a-2e5b27b08e06'::uuid, 'a63e5f85-aa35-5786-a522-a0402b1ae5fb'::uuid, 'La conscription obligatoire a été supprimée en France.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Elle est suspendue depuis 1997 ; restent le recensement à 16 ans et la JDC.', 5),
    ('bf401cb8-d38b-5fa6-9c1b-83edb8d42772'::uuid, 'a63e5f85-aa35-5786-a522-a0402b1ae5fb'::uuid, 'Quelle démarche est obligatoire pour tous les jeunes Français ?', 'mcq', '["Le recensement à 16 ans et la journée défense et citoyenneté","Le service national universel","La réserve opérationnelle","Le service militaire volontaire"]'::jsonb, 0, 'La JDC conditionne l’inscription aux examens et au permis.', 6),
    ('2f5890ec-2236-5aba-a011-3c9c75bd3f9a'::uuid, 'a63e5f85-aa35-5786-a522-a0402b1ae5fb'::uuid, 'Quelle opération militaire assure une présence de sécurité sur le territoire français ?', 'mcq', '["Sentinelle","Barkhane","Chammal","Daman"]'::jsonb, 0, 'Elle est associée au plan Vigipirate.', 7),
    ('b43f10d0-ba29-5b77-9005-010483f7dc07'::uuid, 'a63e5f85-aa35-5786-a522-a0402b1ae5fb'::uuid, 'Savoir vérifier une information relève des enjeux de défense.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'La manipulation de l’information est un volet des guerres hybrides.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('emc');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('emc')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 277 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 277 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
