-- =============================================================================
-- Studuel — Migration 284 : EMC 2de — « LA LIBERTÉ, LES LIBERTÉS » (10 fiches)
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 284 --modules emc-2de
--
-- LE DÉFAUT : l'EMC de Seconde n'avait que les 3 fiches du socle lycée de la
-- migration 216 — « La liberté d'expression et ses limites », « Démocratie et État
-- de droit », « Enjeux du numérique et de l'information » —, écrites pour la 2de,
-- la 1re et la Tle à la fois. Un élève de 2de qui révisait la hiérarchie des
-- normes, la séparation des pouvoirs, la loi de 1905, l'ordre public, le rôle du
-- Défenseur des droits, la Charte de l'environnement, la Convention citoyenne pour
-- le climat ou le statut juridique de l'animal ne trouvait RIEN.
-- LE TEXTE QUI FAIT FOI : le programme d'EMC du BO n° 24 du 13 juin 2024,
-- applicable à tous les niveaux à la rentrée 2026-2027. L'année de Seconde y a pour
-- thématique « La liberté, les libertés » et se déplie en trois chapitres :
-- l'État de droit, les libertés et la responsabilité face à l'information, le droit
-- et la responsabilité en matière d'environnement et de biodiversité. Cette
-- migration installe leurs 10 fiches, aux positions 1 à 10.
-- LES 3 FICHES DU SOCLE PARTENT, AU SEUL NIVEAU 2de — décision prise en 250 pour la
-- Terminale et en 277 pour la Première, pour la même raison : trois lignes hors
-- chapitre en tête de liste rouvrent le doute sur les dix autres. La 2de était le
-- dernier niveau du lycée à les garder, faute de remplacement : ce n'est plus le
-- cas.
-- ⚠️ LA 216 EST REJOUABLE : la recoller ferait revenir les 3 fiches au niveau 2de.
--
-- Cette migration apporte : 10 chapitres, 10 leçons,
-- 10 quiz et 80 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 0. Ménage ----------------------------------------------------------------
-- [emc] La colonne de rangement d'abord : theme (migration 234) porte le chapitre du
-- [emc] programme, et l'INSERT l'écrit pour les 10 fiches. Elle est REPRISE ici en ADD
-- [emc] COLUMN IF NOT EXISTS, comme dans les migrations 243 à 283 — la 234 n'a jamais été
-- [emc] exécutée telle quelle. Sans cette reprise, la migration échouerait sur « column
-- [emc] chapters.theme does not exist », les 3 anciennes fiches déjà supprimées et les 10
-- [emc] neuves pas encore posées : une matière vide.
-- [emc] Le GRANT n'est pas décoratif : la 182 a révoqué le SELECT de table sur chapters
-- [emc] (pour cacher mind_map) et ne l'a rendu que colonne par colonne ; une colonne
-- [emc] ajoutée après elle n'hérite d'aucun droit, et l'app lirait « permission denied »
-- [emc] au lieu du chapitre.
ALTER TABLE public.chapters ADD COLUMN IF NOT EXISTS theme TEXT;
GRANT SELECT (theme) ON public.chapters TO anon;
GRANT SELECT (theme) ON public.chapters TO authenticated;

-- [emc] Les 3 fiches du socle lycée partent, au niveau 2de SEULEMENT.
-- [emc] 
-- [emc] LE REPÈRE EST theme IS NULL, PAS LE TITRE — même choix qu'en anglais (266), en
-- [emc] espagnol (267), en allemand (276) et en EMC de Première (277). Deux des trois
-- [emc] titres portent une apostrophe TYPOGRAPHIQUE, et un DELETE qui se tromperait
-- [emc] d'apostrophe ne trouverait rien EN SILENCE. Le critère « pas de chapitre de
-- [emc] programme » vise exactement les trois lignes voulues : elles datent de la 216,
-- [emc] bien avant la colonne theme, tandis que les 10 fiches neuves en portent un dès
-- [emc] l'INSERT — le ménage tourne AVANT les insertions et ne peut donc jamais mordre
-- [emc] sur elles, ni au premier passage ni au rejeu.
-- [emc] Le filtre level = '2de' est indispensable : le collège a ses propres chapitres
-- [emc] dans la 216, eux aussi sans theme, et rien ne viendrait les remplacer.
-- [emc] L'ordre compte : la file « À revoir » d'abord (review_items.item_id n'a PAS de
-- [emc] clé étrangère), puis les quiz (quizzes.lesson_id est ON DELETE SET NULL : ils
-- [emc] survivraient orphelins à leur chapitre, mais toujours tirables par le moteur de
-- [emc] questions), puis les chapitres, dont les leçons partent en cascade.
DELETE FROM public.review_items ri
 USING public.quiz_questions qq, public.quizzes qz, public.lessons l,
       public.chapters c, public.subjects s
 WHERE ri.item_kind = 'question'
   AND ri.item_id = qq.id
   AND qq.quiz_id = qz.id
   AND qz.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'emc'
   AND c.level = '2de'
   AND c.theme IS NULL;

DELETE FROM public.quizzes q
 USING public.lessons l, public.chapters c, public.subjects s
 WHERE q.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'emc'
   AND c.level = '2de'
   AND c.theme IS NULL;

DELETE FROM public.chapters c
 USING public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'emc'
   AND c.level = '2de'
   AND c.theme IS NULL;

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position, theme)
SELECT v.id, s.id, v.level, v.title, v.position, v.theme
  FROM (VALUES
    ('c3ba5e5b-b29c-50b5-b5cb-9e66d44134ba'::uuid, 'emc', '2de', 'Qu’est-ce que l’État de droit ?', 1, 'L’État de droit : garant des droits, libertés et d’un pluralisme démocratique'),
    ('c30bf9d1-1f5f-542c-a395-2dc384c3a50d'::uuid, 'emc', '2de', 'L’État de droit : le fruit d’une longue évolution', 2, 'L’État de droit : garant des droits, libertés et d’un pluralisme démocratique'),
    ('00ce64fb-084e-5285-93f2-e8883a782347'::uuid, 'emc', '2de', 'La laïcité en France', 3, 'L’État de droit : garant des droits, libertés et d’un pluralisme démocratique'),
    ('11f62154-d6e1-5fee-b539-bac2fad85fc5'::uuid, 'emc', '2de', 'Libertés fondamentales et ordre public', 4, 'L’État de droit : garant des droits, libertés et d’un pluralisme démocratique'),
    ('52823780-bb9b-56dd-b2e7-c6006a612e39'::uuid, 'emc', '2de', 'La liberté de la presse', 5, 'Libertés et responsabilité : l’information'),
    ('9683105d-f114-5d2c-ade7-fa4371b506c0'::uuid, 'emc', '2de', 'La liberté d’expression', 6, 'Libertés et responsabilité : l’information'),
    ('e0f45b58-fa55-5bca-80a1-99f073ef6717'::uuid, 'emc', '2de', 'Comment réguler les réseaux sociaux ?', 7, 'Libertés et responsabilité : l’information'),
    ('fe688608-fb41-590d-80ef-5dbea17dfe23'::uuid, 'emc', '2de', 'Droits environnementaux dans un contexte de transition écologique', 8, 'Droit et responsabilité : la protection de l’environnement et la sauvegarde de la biodiversité'),
    ('3c245a26-2036-5157-80f5-622fb7cf9929'::uuid, 'emc', '2de', 'S’engager en faveur d’une démocratie environnementale', 9, 'Droit et responsabilité : la protection de l’environnement et la sauvegarde de la biodiversité'),
    ('88781286-2838-5796-be60-916c0bb0de6d'::uuid, 'emc', '2de', 'Quelle protection et quels droits pour les animaux ?', 10, 'Droit et responsabilité : la protection de l’environnement et la sauvegarde de la biodiversité')
  ) AS v(id, slug, level, title, position, theme)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 1 bis. Axes du programme -------------------------------------------------
-- `chapters.theme` (migration 234) : l’intitulé du programme officiel qui
-- coiffe le chapitre. La page matière s’en sert pour grouper au lieu
-- d’aligner 28 lignes à plat. UPDATE et non INSERT : le chapitre peut déjà
-- exister (l’INSERT précédent l’aurait alors ignoré).
UPDATE public.chapters c SET theme = v.theme
  FROM (VALUES
    ('c3ba5e5b-b29c-50b5-b5cb-9e66d44134ba'::uuid, 'L’État de droit : garant des droits, libertés et d’un pluralisme démocratique'),
    ('c30bf9d1-1f5f-542c-a395-2dc384c3a50d'::uuid, 'L’État de droit : garant des droits, libertés et d’un pluralisme démocratique'),
    ('00ce64fb-084e-5285-93f2-e8883a782347'::uuid, 'L’État de droit : garant des droits, libertés et d’un pluralisme démocratique'),
    ('11f62154-d6e1-5fee-b539-bac2fad85fc5'::uuid, 'L’État de droit : garant des droits, libertés et d’un pluralisme démocratique'),
    ('52823780-bb9b-56dd-b2e7-c6006a612e39'::uuid, 'Libertés et responsabilité : l’information'),
    ('9683105d-f114-5d2c-ade7-fa4371b506c0'::uuid, 'Libertés et responsabilité : l’information'),
    ('e0f45b58-fa55-5bca-80a1-99f073ef6717'::uuid, 'Libertés et responsabilité : l’information'),
    ('fe688608-fb41-590d-80ef-5dbea17dfe23'::uuid, 'Droit et responsabilité : la protection de l’environnement et la sauvegarde de la biodiversité'),
    ('3c245a26-2036-5157-80f5-622fb7cf9929'::uuid, 'Droit et responsabilité : la protection de l’environnement et la sauvegarde de la biodiversité'),
    ('88781286-2838-5796-be60-916c0bb0de6d'::uuid, 'Droit et responsabilité : la protection de l’environnement et la sauvegarde de la biodiversité')
  ) AS v(id, theme)
 WHERE c.id = v.id AND c.theme IS DISTINCT FROM v.theme;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('5ce2260a-9e9c-5b65-a12f-ed68d5f1d78c', 'c3ba5e5b-b29c-50b5-b5cb-9e66d44134ba', 'Un pouvoir qui obéit à ses propres règles', E'L''État de droit est un État dans lequel tous — gouvernants comme gouvernés — sont soumis au droit.\n\n> Son contraire n''est pas l''absence de lois : un État autoritaire en a beaucoup. Son contraire, c''est l''**arbitraire** : un pouvoir qui n''est pas lié par les règles qu''il édicte.\n\n## Trois conditions\n| La condition | Ce qu''elle exige |\n| Une **hiérarchie des normes** respectée | Chaque règle est conforme à celle du dessus |\n| Une **séparation des pouvoirs** effective | Aucun organe ne cumule tout |\n| Des **juges indépendants** | Chacun peut contester une décision publique |\n\n## La hiérarchie des normes\n| Le rang | La norme |\n| 1 | La **Constitution**, et le bloc de constitutionnalité : Déclaration de 1789, Préambule de 1946 |\n| 2 | Les **traités** internationaux et le droit de l''Union européenne |\n| 3 | La **loi**, votée par le Parlement |\n| 4 | Les **règlements** : décrets, arrêtés |\n| 5 | Les contrats |\n\nUne norme inférieure qui contredit une norme supérieure peut être **annulée**.\n\n> Ce n''est pas la force qui valide une règle, c''est sa conformité à la règle du dessus.\n\n## La séparation des pouvoirs\n| Le pouvoir | Sa fonction |\n| **Législatif** | Il fait la loi |\n| **Exécutif** | Il l''applique |\n| **Judiciaire** | Il la fait respecter |\n\nFormulée par **Montesquieu** en 1748 : « il faut que le pouvoir arrête le pouvoir ».\n\n## Les gardiens\n| L''institution | Ce qu''elle contrôle |\n| Le **Conseil constitutionnel** | La conformité des lois à la Constitution, y compris après leur entrée en vigueur, par la **QPC** depuis 2010 |\n| Le **Conseil d''État** | L''administration |\n| La **Cour de cassation** | L''interprétation du droit |\n| La **CEDH**, à Strasbourg | Elle peut condamner la France |\n\n## Ce que ça change pour un citoyen\nContester un refus de l''administration, demander réparation d''un dommage causé par l''État, faire écarter une loi contraire à la Constitution.\n\n> Sans État de droit, ces recours n''existent pas.', 1),
  ('fe3a4b6d-6db4-5686-b47b-b00132254938', 'c30bf9d1-1f5f-542c-a395-2dc384c3a50d', 'Huit siècles pour limiter le pouvoir', E'L''État de droit n''a pas été décrété : il s''est construit par étapes, presque toujours après une crise.\n\n## Les premières limites\n| La date | Le texte | Ce qu''il pose |\n| **1215** | La **Magna Carta** anglaise | Le roi ne peut emprisonner un homme libre sans jugement |\n| **1679** | L''**habeas corpus** | Le contrôle judiciaire de la détention |\n\nEn France, l''Ancien Régime connaît des « lois fondamentales du royaume », mais le roi n''est jugé par personne.\n\n## 1789 et la Déclaration\n| L''article | Ce qu''il pose |\n| **1** | Les hommes naissent libres et égaux en droits |\n| **4** | La liberté consiste à pouvoir faire tout ce qui ne nuit pas à autrui |\n| **8** | Nul ne peut être puni qu''en vertu d''une loi antérieure |\n| **16** | Toute société où la garantie des droits n''est pas assurée n''a point de Constitution |\n\n> L''article 16 est la définition la plus courte de l''État de droit.\n\n## Le XIXe et le XXe siècle\n| La date | La liberté conquise |\n| **1881** | Liberté de la presse, et école |\n| **1884** | Liberté syndicale |\n| **1901** | Liberté d''association |\n| **1905** | Séparation des Églises et de l''État |\n| **1944** | Droit de vote des femmes |\n\n## Après 1945\nFace à ce qu''ont fait des États **légaux mais criminels**, la garantie devient internationale.\n\n| La date | Le texte |\n| **1948** | Déclaration universelle des droits de l''homme |\n| **1950** | Convention européenne des droits de l''homme |\n| **1958** | La Constitution crée le **Conseil constitutionnel** |\n| **1971** | Il s''émancipe en donnant valeur constitutionnelle au Préambule — donc à la Déclaration de 1789 |\n\n## Aujourd''hui\n| La date | L''avancée |\n| **1981** | Abolition de la peine de mort |\n| **2010** | La **question prioritaire de constitutionnalité** |\n| **2011** | Création du **Défenseur des droits** |\n\n> Rien n''est acquis : chaque état d''urgence rouvre la question de l''équilibre entre sécurité et libertés.', 1),
  ('b131654f-e9c1-5fa4-a4f4-1ea9fcba7855', '00ce64fb-084e-5285-93f2-e8883a782347', 'Ce que la loi de 1905 dit, et ce qu’elle ne dit pas', E'La laïcité n''est pas une opinion sur la religion : c''est une règle d''organisation de l''État.\n\n## Les deux articles fondateurs\n| L''article de la loi du 9 décembre **1905** | Ce qu''il pose |\n| **Article 1** | La République assure la **liberté de conscience** et garantit le libre exercice des cultes |\n| **Article 2** | La République ne reconnaît, ne salarie ni ne subventionne aucun culte |\n\n> D''abord la liberté, ensuite la séparation : l''ordre des deux articles n''est pas un détail, c''est le sens même de la loi.\n\n## Ce qui en découle\n| Qui | Ce à quoi il est tenu |\n| L''**État** | La **neutralité** : il ne privilégie aucune religion, n''en combat aucune |\n| Les **agents publics** | Une **stricte neutralité** dans l''exercice de leurs fonctions |\n| Les **usagers** du service public | Ils restent **libres**, sauf exceptions prévues par la loi |\n\n## À l''école\n| Le texte | Sa règle |\n| La loi du **15 mars 2004** | Elle interdit aux **élèves** des écoles, collèges et lycées publics les signes ou tenues manifestant **ostensiblement** une appartenance religieuse |\n| La **Charte de la laïcité à l''école** (2013) | Elle explicite ces principes |\n| À l''**université** | La règle est différente : les étudiants sont majeurs et libres |\n\n## Ce que la laïcité n''est pas\n| L''idée fausse | La réalité |\n| L''interdiction de croire | Elle **garantit** la liberté de conscience |\n| L''effacement des religions de l''espace public | La rue, un commerce, une association ne sont pas soumis à la neutralité |\n| Une arme contre une religion en particulier | Elle vaut pour toutes, de la même façon |\n\n## Les particularités\n| Le territoire | Son régime |\n| L''**Alsace-Moselle**, allemande en 1905 | Le régime **concordataire** subsiste |\n| La **Guyane** | Un statut propre |\n\n> La laïcité française reste un cas particulier en Europe : d''autres démocraties financent des cultes, ou ont une religion d''État, tout en garantissant la liberté religieuse.', 1),
  ('bb09eebe-51ea-5414-badf-5561d863a821', '11f62154-d6e1-5fee-b539-bac2fad85fc5', 'Jusqu’où l’État peut-il limiter une liberté ?', E'Aucune liberté n''est absolue, mais aucune limitation n''est libre : le droit encadre très précisément la manière dont l''État peut restreindre une liberté.\n\n## Les libertés fondamentales\nProtégées par la Constitution et les traités : aller et venir, conscience, expression, réunion, association, manifestation, vie privée, propriété, procès équitable, liberté d''entreprendre.\n\n## L''ordre public\n| Sa composante | Ce qu''elle protège |\n| La **sécurité** | Les personnes et les biens |\n| La **tranquillité** | Le calme public |\n| La **salubrité** | La santé publique |\n| La **dignité** de la personne humaine | Ajoutée par la jurisprudence |\n\n> L''ordre public n''est pas un pouvoir de tout interdire : c''est un **motif**, qui doit être prouvé, et une **mesure**, qui doit être proportionnée.\n\n## Le test de proportionnalité\n| Le critère | Sa question |\n| **Adaptée** | La mesure sert-elle bien le but invoqué ? |\n| **Nécessaire** | Une mesure moins sévère suffirait-elle ? |\n| **Proportionnée** | L''atteinte est-elle excessive par rapport au bénéfice ? |\n\n> Une interdiction **générale et absolue** est presque toujours annulée : la règle est l''autorisation, l''exception est l''interdiction.\n\n## Le juge du référé\n| Le recours | Son délai |\n| Le **référé-liberté** | Le juge administratif doit statuer en **48 heures**, lorsqu''une liberté fondamentale est gravement et manifestement atteinte |\n\n## Les régimes d''exception\nL''**état d''urgence**, prévu par la loi de 1955 et appliqué de 2015 à 2017, élargit les pouvoirs de police. Il reste sous contrôle du juge et du Parlement.\n\n> Le risque principal : des mesures d''exception qui passent peu à peu dans le **droit commun**.\n\n## Manifester\n| La formalité | Sa nature |\n| La **déclaration** préalable | Obligatoire |\n| L''**autorisation** | Elle n''est **pas** exigée |\n\nUne interdiction doit être justifiée par un risque précis de trouble, pas par une gêne.', 1),
  ('a639c551-5804-5c3c-8bdb-818285f724b8', '52823780-bb9b-56dd-b2e7-c6006a612e39', 'Une liberté qui protège d’abord le lecteur', E'La liberté de la presse n''est pas un privilège de journaliste : c''est le droit du public d''être informé.\n\n## Le texte de référence\nLa **loi du 29 juillet 1881** pose que l''imprimerie et la librairie sont libres.\n\n| Le contrôle | Sa nature | Le régime |\n| **A priori** | Autorisation préalable, censure administrative | **Supprimé** |\n| **A posteriori** | On répond devant un tribunal de ce qu''on a publié | Le régime actuel |\n\n> On ne juge pas un journal avant qu''il paraisse : on le juge après, sur ce qu''il a réellement écrit.\n\n## Les limites prévues par la loi\n| L''abus | Sa définition |\n| La **diffamation** | Imputer un fait précis portant atteinte à l''honneur |\n| L''**injure** | Une expression outrageante, sans imputation de fait |\n| La **provocation** | À la haine ou à la violence |\n| L''**apologie** de crimes | Présenter un crime sous un jour favorable |\n| Les **fausses nouvelles** | Lorsqu''elles troublent l''ordre public |\n\nLes lois **Pleven** (1972) et **Gayssot** (1990) ont renforcé la répression du racisme et de la négation des crimes contre l''humanité.\n\n## Les garanties du métier\n| La garantie | Son contenu |\n| La **protection des sources** | Loi de 2010 ; elle ne cède que devant un impératif prépondérant d''intérêt public |\n| La **clause de conscience** | Un journaliste peut quitter un journal qui change de ligne |\n| L''indépendance des rédactions | Loi Bloche, 2016 |\n\n## Qui régule\n| L''acteur | Son rôle |\n| Le **juge** | Il tranche les abus |\n| L''**Arcom** | Née en 2022 de la fusion du CSA et de l''Hadopi : audiovisuel et plateformes |\n| Les instances professionnelles | Conseils de déontologie, sociétés de journalistes |\n\n## Les menaces contemporaines\n| La menace | Son effet |\n| La **concentration** des médias | Peu de propriétaires |\n| La dépendance à la **publicité** | Un contenu orienté par l''audience |\n| Les **procédures-bâillons** | Épuiser financièrement un média |\n| Le danger physique | Reporters menacés |\n| La difficulté économique | L''information de qualité face aux contenus gratuits |', 1),
  ('8a21c4b0-0fa5-541d-b0fc-34a9938face4', '9683105d-f114-5d2c-ade7-fa4371b506c0', 'Dire ce qu’on veut, répondre de ce qu’on dit', E'La liberté d''expression est reconnue par l''article 11 de la Déclaration de 1789 et par l''article 10 de la Convention européenne des droits de l''homme.\n\n> « La libre communication des pensées et des opinions est un des droits les plus précieux de l''homme. »\n\n## Une liberté large\nElle protège les idées qui **heurtent, choquent ou inquiètent**, et pas seulement celles qui plaisent : c''est une formule constante de la Cour européenne.\n\n| Ce qu''elle protège | Ce qui reste possible |\n| La **caricature** | Se moquer |\n| La **satire** | Détourner |\n| La **critique** des institutions et des religions | Contester une idée |\n\n## Une liberté responsable\nL''article 11 le dit lui-même : chacun répond de l''abus de cette liberté « dans les cas déterminés par la loi ».\n\n| Ce qui est sanctionné | Sa nature |\n| L''**injure** et la **diffamation** | Contre des personnes |\n| La **provocation** à la haine, à la violence, à la discrimination | Contre des groupes |\n| L''**apologie du terrorisme** | Un délit spécifique |\n| La **négation** de crimes contre l''humanité | Un délit |\n| Le **harcèlement** en ligne, les **menaces** | Des délits |\n| L''atteinte à la **vie privée** et au droit à l''image | Un délit civil et pénal |\n\n## La ligne de partage\n| L''objet visé | Le régime |\n| Une **idée**, une doctrine, une religion, un parti | Critiquable : cela relève du **débat** |\n| Des **personnes**, en raison de leur origine, religion, sexe, orientation sexuelle, handicap | Attaque interdite : cela relève du **délit** |\n\n## En ligne\n| Le point | La règle |\n| Un message **public** sur un réseau | C''est une **publication** : il peut fonder des poursuites |\n| L''**anonymat** d''un pseudonyme | Il ne protège pas d''une identification judiciaire |\n| Depuis 2018 et 2022 | Plusieurs textes ont renforcé la lutte contre le cyberharcèlement |\n\n## Au lycée\nLes élèves disposent d''une liberté d''expression individuelle et collective, dans le respect du **pluralisme** et de la **neutralité** du service public, sans propos injurieux ni diffamatoires.\n\nElle s''exerce notamment par les délégués, le CVL et les journaux lycéens.', 1),
  ('88459ae9-0ded-5e77-b45b-c4319f31e065', 'e0f45b58-fa55-5bca-80a1-99f073ef6717', 'Des plateformes privées, un espace public', E'Les réseaux sociaux posent un problème inédit : ce sont des entreprises privées, régies par des conditions d''utilisation, qui organisent une part majeure du débat public.\n\n## Ce qui rend la régulation difficile\n| L''obstacle | Son contenu |\n| Le **volume** | Des millions de contenus par heure |\n| La **vitesse** | La diffusion précède la vérification |\n| Le caractère **transnational** | Une plateforme, des dizaines de droits nationaux |\n| La modération par **algorithmes** et sous-traitants | Selon des règles **privées**, non votées |\n\n## Les algorithmes de recommandation\nIls ne choisissent pas ce qui est vrai, mais ce qui **retient l''attention** — donc souvent ce qui indigne.\n\n| Le phénomène | Son effet |\n| La **bulle de filtres** | On ne voit plus que ce qui nous ressemble |\n| La **chambre d''écho** | On croit que tout le monde pense comme soi |\n| L''emballement du faux | Les contenus faux circulent en moyenne plus vite que les vrais |\n\n> Le problème n''est pas seulement ce qui est publié : c''est ce qui est **mis en avant**.\n\n## Les leviers juridiques\n| Le texte | Sa date | Ce qu''il impose |\n| La **LCEN** | 2004 | Les hébergeurs ne sont pas responsables a priori, mais doivent **retirer promptement** un contenu manifestement illicite signalé |\n| Le **Digital Services Act** | Applicable depuis 2023-2024 | Transparence des algorithmes, analyse des risques, signalement facilité, audit indépendant pour les très grandes plateformes |\n| Le **RGPD** | 2018 | L''usage des données personnelles ; la **CNIL** contrôle |\n\n## Les autres leviers\n| Le levier | Son acteur |\n| La **modération** | Les plateformes elles-mêmes |\n| L''**éducation aux médias** | L''école |\n| Le **fact-checking** | Les rédactions et les utilisateurs |\n| Le **signalement** | **Pharos** pour les contenus illicites, **3018** pour le cyberharcèlement |\n\n## Le débat de fond\n| L''excès | Son risque |\n| Trop **réguler** | La **surcensure** : une plateforme menacée d''amende retire par précaution des contenus légaux |\n| Trop **peu** | Haine et désinformation prospèrent |\n\n> La question centrale : qui décide, selon quelles règles, et avec quel recours pour l''utilisateur ?', 1),
  ('37a37c29-293c-5829-869e-7a9394c55411', 'fe688608-fb41-590d-80ef-5dbea17dfe23', 'Quand l’environnement entre dans la Constitution', E'Le droit de l''environnement est récent : il naît dans les années 1970 et prend en France une valeur constitutionnelle en 2005.\n\n## La Charte de l''environnement\n| Le point | Son contenu |\n| Sa date | **2005**, adossée à la Constitution |\n| Sa valeur | La **même** que la Déclaration de 1789 |\n| Ce qu''elle proclame | Le droit de vivre dans un environnement équilibré et respectueux de la santé, et le **devoir** de prendre part à sa préservation |\n\n## Quatre principes\n| Le principe | Ce qu''il impose |\n| **Prévention** | Agir en amont pour éviter les atteintes **connues** |\n| **Précaution** | Face à un risque **incertain** mais grave et irréversible, prendre des mesures provisoires sans attendre la certitude scientifique |\n| **Pollueur-payeur** | Celui qui pollue supporte le coût de la réparation |\n| **Participation** | Chacun accède à l''information et participe aux décisions |\n\n> Prévention et précaution ne sont pas la même chose : la première vise un risque **connu**, la seconde un risque encore **incertain**.\n\n## Les textes internationaux\n| La date | Le texte | Son apport |\n| **1992** | Le sommet de **Rio** | Le développement durable |\n| **1998** | La convention d''**Aarhus** | Information, participation, accès à la justice |\n| **2015** | L''**accord de Paris** | Contenir le réchauffement bien en dessous de 2 °C |\n| **2015** | Les **objectifs de développement durable** de l''ONU | Un cap commun à l''horizon 2030 |\n\n## Le juge s''en mêle\n| L''affaire | Sa décision |\n| L''**Affaire du siècle**, 2021 | La justice administrative reconnaît la responsabilité de l''État pour **carence fautive** dans la lutte contre le changement climatique |\n| Aux Pays-Bas, en Allemagne | Des décisions comparables |\n\n> Le contentieux climatique est devenu un levier réel.\n\n## Le nouveau vocabulaire pénal\nLa loi **Climat et résilience** de **2021** a créé un délit général de pollution des milieux et un délit d''**écocide** pour les atteintes les plus graves et durables, commises intentionnellement.', 1),
  ('2f8c43fd-aa6f-5257-8b8f-e251665b8d51', '3c245a26-2036-5157-80f5-622fb7cf9929', 'Décider ensemble ce qui engage tout le monde', E'La démocratie environnementale repose sur une idée simple : les décisions qui modifient durablement un territoire ou un climat doivent associer ceux qui les subiront.\n\n## Les trois piliers\nIssus de la convention d''**Aarhus**, 1998 :\n\n| Le pilier | Ce qu''il garantit |\n| L''**accès à l''information** | Environnementale, et compréhensible |\n| La **participation** | Au processus décisionnel |\n| L''**accès à la justice** | Pour contester une décision |\n\n## Les outils français\n| L''outil | Son moment |\n| L''**enquête publique** | Avant les grands projets |\n| La **Commission nationale du débat public** | Elle organise les débats sur les projets d''ampleur |\n| L''**étude d''impact** | Elle évalue les effets d''un aménagement |\n| La **consultation en ligne** | Pour réagir à un projet de décret |\n| L''action des **associations agréées** | Elles peuvent agir en justice |\n\n> Participer n''est pas décider : la consultation éclaire la décision, elle ne la remplace pas — et c''est là que naissent la plupart des conflits.\n\n## La Convention citoyenne pour le climat\n| Le point | Son contenu |\n| Sa période | 2019-2020 |\n| Sa composition | **150 citoyens tirés au sort** |\n| Sa mission | Proposer des mesures de réduction des émissions, dans un esprit de justice sociale |\n| Son résultat | **149 propositions**, dont une partie a nourri la loi Climat et résilience de 2021 |\n| Son bilan | Débattu : expérience démocratique inédite pour les uns, promesses non tenues pour les autres |\n\n## Les formes d''engagement\nLe vote et l''engagement politique, l''adhésion associative, le bénévolat, la **pétition**, la **manifestation**, la consommation responsable, le lancement d''alerte, l''action en justice.\n\n## Les limites et les tensions\n| La tension | Ce qui s''oppose |\n| Emploi contre protection | Deux intérêts légitimes |\n| Propriété contre intérêt général | Deux droits |\n| Urgence contre concertation | Deux temporalités |\n\n> Certaines actions — occupations, blocages, dégradations — posent la question des limites de la **désobéissance civile** : agir pour une cause n''exonère pas de la loi.\n\n## Au lycée\nÉco-délégués, projets d''établissement, semaine du développement durable : le programme fait de l''engagement une **compétence à exercer**, pas seulement une notion à connaître.', 1),
  ('bc5d54bd-8b08-5b3e-be9b-ad9820d46d76', '88781286-2838-5796-be60-916c0bb0de6d', 'Ni chose, ni personne : le statut juridique de l’animal', E'Le droit français a longtemps rangé l''animal parmi les biens. Depuis 2015, il occupe une place à part, qui reste discutée.\n\n## L''évolution du statut\n| La date | Le texte | Ce qu''il pose |\n| **1850** | La loi **Grammont** | Elle punit les mauvais traitements infligés **publiquement** aux animaux domestiques |\n| **1976** | La loi | L''animal est un **être sensible** |\n| **2015** | L''article 515-14 du Code civil | « Les animaux sont des êtres vivants doués de sensibilité » — tout en restant soumis au régime des biens |\n\n> L''animal n''est plus un meuble, mais il n''est pas une personne : le droit lui a créé une catégorie intermédiaire, et personne ne s''accorde sur ce qu''elle devrait devenir.\n\n## Ce que la loi protège\n| L''infraction ou la règle | Son cadre |\n| **Sévices graves**, **actes de cruauté**, **abandon** | Punis par le Code pénal, aggravés par la loi de **2021** |\n| La vente en ligne | Encadrée par cette même loi |\n| Animaux sauvages en cirque itinérant, delphinariums | Interdits progressivement |\n| Le **bien-être animal** en élevage, transport, abattoir | Largement du droit européen |\n\n## Le débat philosophique\n| La position | Ce qu''elle demande |\n| Le **welfarisme** | Réduire la souffrance, sans remettre en cause l''usage |\n| Les **droits des animaux** (Tom Regan) | Reconnaître des droits fondamentaux à certains animaux |\n| L''**antispécisme** | Contester la légitimité même de la hiérarchie entre espèces |\n| La continuité des usages | Défendre élevage, chasse et recherche, au nom de traditions, d''équilibres économiques ou d''un statut particulier de l''humain |\n\n## Biodiversité et animaux sauvages\n| L''instrument | Son objet |\n| La convention de Washington — **CITES**, 1973 | Le commerce des espèces menacées |\n| Les directives européennes **Oiseaux** et **Habitats** | Les espèces et les milieux |\n| Le réseau **Natura 2000** | Des sites protégés |\n| Les **listes rouges** de l''UICN | L''état des espèces |\n| L''Office français de la biodiversité | La police et l''expertise |\n\n## Une tension à assumer\n> Protéger un **animal individuel** et protéger une **espèce** ne demandent pas les mêmes règles — et peuvent parfois s''opposer, par exemple lors de la régulation d''une espèce invasive.', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('7ba02124-810a-58a9-9034-b0d4e6853c08'::uuid, 'Quiz — Un pouvoir qui obéit à ses propres règles', 'EMC', '2de', 'Qu’est-ce que l’État de droit ?', '5ce2260a-9e9c-5b65-a12f-ed68d5f1d78c'::uuid),
    ('4c9eb283-8f7f-54d9-b2e7-77aa9383b4a4'::uuid, 'Quiz — Huit siècles pour limiter le pouvoir', 'EMC', '2de', 'L’État de droit : le fruit d’une longue évolution', 'fe3a4b6d-6db4-5686-b47b-b00132254938'::uuid),
    ('0e632bf6-61c3-5226-a31d-aae74f9ed6b1'::uuid, 'Quiz — Ce que la loi de 1905 dit, et ce qu’elle ne dit pas', 'EMC', '2de', 'La laïcité en France', 'b131654f-e9c1-5fa4-a4f4-1ea9fcba7855'::uuid),
    ('d4b9499c-634f-5fcb-a604-0021194c0ea4'::uuid, 'Quiz — Jusqu’où l’État peut-il limiter une liberté ?', 'EMC', '2de', 'Libertés fondamentales et ordre public', 'bb09eebe-51ea-5414-badf-5561d863a821'::uuid),
    ('966a5e67-62a9-58d9-aef5-77eecabe19c9'::uuid, 'Quiz — Une liberté qui protège d’abord le lecteur', 'EMC', '2de', 'La liberté de la presse', 'a639c551-5804-5c3c-8bdb-818285f724b8'::uuid),
    ('32f1b7e2-74d5-5d36-ae48-8444a1de9aae'::uuid, 'Quiz — Dire ce qu’on veut, répondre de ce qu’on dit', 'EMC', '2de', 'La liberté d’expression', '8a21c4b0-0fa5-541d-b0fc-34a9938face4'::uuid),
    ('dea761c5-b15c-5b70-ae05-4f6d9e55b9ef'::uuid, 'Quiz — Des plateformes privées, un espace public', 'EMC', '2de', 'Comment réguler les réseaux sociaux ?', '88459ae9-0ded-5e77-b45b-c4319f31e065'::uuid),
    ('bc8bf7d4-602a-5369-93b3-d8f75f54b1be'::uuid, 'Quiz — Quand l’environnement entre dans la Constitution', 'EMC', '2de', 'Droits environnementaux dans un contexte de transition écologique', '37a37c29-293c-5829-869e-7a9394c55411'::uuid),
    ('15f6b8eb-0ecd-56c3-84f5-3572a6aaec7b'::uuid, 'Quiz — Décider ensemble ce qui engage tout le monde', 'EMC', '2de', 'S’engager en faveur d’une démocratie environnementale', '2f8c43fd-aa6f-5257-8b8f-e251665b8d51'::uuid),
    ('8f216152-50c5-5afd-b2e3-c3bd6857b003'::uuid, 'Quiz — Ni chose, ni personne : le statut juridique de l’animal', 'EMC', '2de', 'Quelle protection et quels droits pour les animaux ?', 'bc5d54bd-8b08-5b3e-be9b-ad9820d46d76'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('e008f9fa-af47-5aea-aeb2-42250472654c'::uuid, '7ba02124-810a-58a9-9034-b0d4e6853c08'::uuid, 'Qu’est-ce qu’un État de droit ?', 'mcq', '["Un État où gouvernants et gouvernés sont soumis au droit","Un État qui a beaucoup de lois","Un État dirigé par des juges","Un État sans Constitution"]'::jsonb, 0, 'Son contraire n’est pas l’absence de lois, mais l’arbitraire.', 1),
    ('5b2f8018-91ac-57ba-a1fe-5e923e355a06'::uuid, '7ba02124-810a-58a9-9034-b0d4e6853c08'::uuid, 'Quelle norme se trouve au sommet de la hiérarchie en France ?', 'mcq', '["La Constitution","La loi","Le décret","L’arrêté municipal"]'::jsonb, 0, 'Avec le bloc de constitutionnalité qu’elle entraîne.', 2),
    ('4e6dcf9b-29e3-5f2f-be97-be84941f5621'::uuid, '7ba02124-810a-58a9-9034-b0d4e6853c08'::uuid, 'Qui a formulé le principe de séparation des pouvoirs en 1748 ?', 'mcq', '["Montesquieu","Rousseau","Voltaire","Diderot"]'::jsonb, 0, 'Dans De l’esprit des lois : « il faut que le pouvoir arrête le pouvoir ».', 3),
    ('b179858f-7c0e-5a65-841c-44857b0e741f'::uuid, '7ba02124-810a-58a9-9034-b0d4e6853c08'::uuid, 'Quels sont les trois pouvoirs ?', 'mcq', '["Législatif, exécutif, judiciaire","Politique, économique, médiatique","Local, national, européen","Civil, pénal, administratif"]'::jsonb, 0, 'Chacun limite les deux autres.', 4),
    ('28143ce3-88a4-5f4e-8b50-a6287c36706f'::uuid, '7ba02124-810a-58a9-9034-b0d4e6853c08'::uuid, 'Que permet la question prioritaire de constitutionnalité, créée en 2010 ?', 'mcq', '["Contester la constitutionnalité d’une loi déjà en vigueur","Modifier la Constitution","Faire appel d’un jugement pénal","Saisir la CEDH directement"]'::jsonb, 0, 'Le contrôle ne s’arrête plus à la promulgation.', 5),
    ('ad0651cd-1daf-5580-aba2-e57c128677dd'::uuid, '7ba02124-810a-58a9-9034-b0d4e6853c08'::uuid, 'Quelle juridiction juge les litiges avec l’administration ?', 'mcq', '["Le Conseil d’État","La Cour de cassation","Le Conseil constitutionnel","La Cour des comptes"]'::jsonb, 0, 'Il est au sommet de l’ordre administratif.', 6),
    ('7377fd75-8ac0-5425-ad0a-d34e23fabf73'::uuid, '7ba02124-810a-58a9-9034-b0d4e6853c08'::uuid, 'Un décret contraire à la loi peut être annulé par le juge.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'C’est le principe de la hiérarchie des normes.', 7),
    ('5780e291-6464-576e-83fe-d2db66455c24'::uuid, '7ba02124-810a-58a9-9034-b0d4e6853c08'::uuid, 'Quelle cour européenne peut condamner la France pour violation des droits fondamentaux ?', 'mcq', '["La Cour européenne des droits de l’homme, à Strasbourg","La Cour de justice de l’Union européenne, à Luxembourg","La Cour pénale internationale, à La Haye","Le Conseil de l’Europe, à Bruxelles"]'::jsonb, 0, 'Après épuisement des recours internes.', 8),
    ('fcb38042-3da6-5abf-9964-311cd377af63'::uuid, '4c9eb283-8f7f-54d9-b2e7-77aa9383b4a4'::uuid, 'Quel texte anglais de 1215 limite pour la première fois le pouvoir royal ?', 'mcq', '["La Magna Carta","L’Habeas Corpus","Le Bill of Rights","La Pétition de droit"]'::jsonb, 0, 'Elle interdit d’emprisonner un homme libre sans jugement.', 1),
    ('131613ac-3310-571c-8a5e-f7ccb62d60a0'::uuid, '4c9eb283-8f7f-54d9-b2e7-77aa9383b4a4'::uuid, 'Que dit l’article 16 de la Déclaration de 1789 ?', 'mcq', '["Sans garantie des droits ni séparation des pouvoirs, il n’y a pas de Constitution","Les hommes naissent libres et égaux","Nul ne peut être puni sans loi antérieure","La propriété est un droit inviolable"]'::jsonb, 0, 'C’est la définition la plus courte de l’État de droit.', 2),
    ('c7e27891-d2c5-5875-81af-ad6497493be8'::uuid, '4c9eb283-8f7f-54d9-b2e7-77aa9383b4a4'::uuid, 'Que garantit la loi de 1901 ?', 'mcq', '["La liberté d’association","La liberté de la presse","La liberté syndicale","La laïcité"]'::jsonb, 0, '1881 pour la presse, 1884 pour les syndicats, 1905 pour la laïcité.', 3),
    ('194940dd-0317-5f11-8105-98730622cee2'::uuid, '4c9eb283-8f7f-54d9-b2e7-77aa9383b4a4'::uuid, 'En quelle année les femmes obtiennent-elles le droit de vote en France ?', 'mcq', '["1944","1918","1936","1958"]'::jsonb, 0, 'Par ordonnance du Gouvernement provisoire.', 4),
    ('ffca520e-7392-52b3-91d4-4043fb64ab3b'::uuid, '4c9eb283-8f7f-54d9-b2e7-77aa9383b4a4'::uuid, 'Quel texte international est adopté en 1948 ?', 'mcq', '["La Déclaration universelle des droits de l’homme","La Convention européenne des droits de l’homme","La Charte des Nations unies","La Convention de Genève"]'::jsonb, 0, 'La Convention européenne date de 1950.', 5),
    ('34b82457-89db-5075-b5df-057d1873d2e2'::uuid, '4c9eb283-8f7f-54d9-b2e7-77aa9383b4a4'::uuid, 'Que se passe-t-il en 1971 pour le Conseil constitutionnel ?', 'mcq', '["Il donne valeur constitutionnelle au Préambule, donc à la Déclaration de 1789","Il est créé","Il est supprimé","Il devient élu"]'::jsonb, 0, 'Une décision qui élargit considérablement son contrôle.', 6),
    ('2a11cd62-1b12-5492-8115-5b5854c95f81'::uuid, '4c9eb283-8f7f-54d9-b2e7-77aa9383b4a4'::uuid, 'En quelle année la peine de mort est-elle abolie en France ?', 'mcq', '["1981","1974","1958","1995"]'::jsonb, 0, 'Portée par le garde des Sceaux Robert Badinter.', 7),
    ('90c62c39-0aa1-55f0-92b3-11f0ce69864a'::uuid, '4c9eb283-8f7f-54d9-b2e7-77aa9383b4a4'::uuid, 'L’État de droit une fois établi ne peut plus reculer.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Chaque état d’urgence rouvre la question de son équilibre.', 8),
    ('977401c0-170f-56ca-bbd2-9427f679b7f5'::uuid, '0e632bf6-61c3-5226-a31d-aae74f9ed6b1'::uuid, 'Que garantit l’article 1 de la loi de 1905 ?', 'mcq', '["La liberté de conscience et le libre exercice des cultes","La séparation des Églises et de l’État","La neutralité des agents publics","La gratuité de l’école"]'::jsonb, 0, 'La liberté vient avant la séparation, énoncée à l’article 2.', 1),
    ('332740f7-5655-57fd-b043-20b1e338d34f'::uuid, '0e632bf6-61c3-5226-a31d-aae74f9ed6b1'::uuid, 'Que dit l’article 2 de la loi de 1905 ?', 'mcq', '["La République ne reconnaît, ne salarie ni ne subventionne aucun culte","Les cultes sont interdits","L’État nomme les ministres du culte","Les bâtiments religieux sont détruits"]'::jsonb, 0, 'C’est le principe de séparation.', 2),
    ('4c767957-0ab3-501e-9b19-fd65a374cb22'::uuid, '0e632bf6-61c3-5226-a31d-aae74f9ed6b1'::uuid, 'Qui est soumis à une stricte neutralité religieuse dans le service public ?', 'mcq', '["Les agents publics dans l’exercice de leurs fonctions","Tous les citoyens en tout lieu","Les usagers du service public","Les commerçants"]'::jsonb, 0, 'Les usagers restent libres, sauf exceptions prévues par la loi.', 3),
    ('ce5205bb-d6a8-5684-907e-82fe5c36f92c'::uuid, '0e632bf6-61c3-5226-a31d-aae74f9ed6b1'::uuid, 'Que prévoit la loi du 15 mars 2004 ?', 'mcq', '["L’interdiction des signes religieux ostensibles pour les élèves des écoles publiques","L’interdiction du voile dans la rue","La suppression de l’enseignement du fait religieux","La neutralité des parents d’élèves"]'::jsonb, 0, 'Elle vise les élèves des écoles, collèges et lycées publics.', 4),
    ('3018a976-e292-5900-bcfa-57cbc265b56a'::uuid, '0e632bf6-61c3-5226-a31d-aae74f9ed6b1'::uuid, 'La règle de 2004 s’applique-t-elle à l’université ?', 'mcq', '["Non, les étudiants y sont majeurs et libres","Oui, de la même manière","Oui, mais seulement en licence","Elle s’applique aux enseignants seulement"]'::jsonb, 0, 'Le régime universitaire est distinct.', 5),
    ('bac88036-67f5-5f2a-8340-18eef1937c09'::uuid, '0e632bf6-61c3-5226-a31d-aae74f9ed6b1'::uuid, 'Quel territoire conserve un régime concordataire ?', 'mcq', '["L’Alsace-Moselle","La Corse","La Bretagne","La Savoie"]'::jsonb, 0, 'Elle était allemande au moment du vote de la loi de 1905.', 6),
    ('bc32cc28-f1c9-5864-986b-dd7b541e9cb4'::uuid, '0e632bf6-61c3-5226-a31d-aae74f9ed6b1'::uuid, 'La laïcité interdit de croire et de pratiquer une religion.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle garantit au contraire la liberté de conscience et de culte.', 7),
    ('1b3a35f6-cc07-545a-8875-d30d9df45f91'::uuid, '0e632bf6-61c3-5226-a31d-aae74f9ed6b1'::uuid, 'Quel document de 2013 explicite les principes de laïcité à destination des élèves ?', 'mcq', '["La Charte de la laïcité à l’école","La loi Debré","Le Code de l’éducation","La circulaire Jospin"]'::jsonb, 0, 'Elle est affichée dans les établissements.', 8),
    ('378eaea8-a98e-5ee1-ad7a-b7391c84a047'::uuid, 'd4b9499c-634f-5fcb-a604-0021194c0ea4'::uuid, 'Quelles sont les trois composantes classiques de l’ordre public ?', 'mcq', '["Sécurité, tranquillité et salubrité publiques","Liberté, égalité, fraternité","Police, justice, armée","Santé, éducation, transport"]'::jsonb, 0, 'La jurisprudence y a ajouté la dignité de la personne humaine.', 1),
    ('3827930c-844c-5910-ac5f-034c01cb9d50'::uuid, 'd4b9499c-634f-5fcb-a604-0021194c0ea4'::uuid, 'Que vérifie le test de proportionnalité ?', 'mcq', '["Que la mesure est adaptée, nécessaire et proportionnée","Que la mesure est votée par le Parlement","Que la mesure est publiée au Journal officiel","Que la mesure a l’accord du maire"]'::jsonb, 0, 'Trois conditions cumulatives contrôlées par le juge.', 2),
    ('624ecc07-65dc-50d2-80c0-2ae205f2afbc'::uuid, 'd4b9499c-634f-5fcb-a604-0021194c0ea4'::uuid, 'Quel est le sort d’une interdiction générale et absolue ?', 'mcq', '["Elle est presque toujours annulée par le juge","Elle est automatiquement valable","Elle doit être votée par référendum","Elle relève du Conseil constitutionnel seul"]'::jsonb, 0, 'La règle est la liberté, l’exception est l’interdiction.', 3),
    ('b59180ef-c863-5ea0-8beb-4242f372cb36'::uuid, 'd4b9499c-634f-5fcb-a604-0021194c0ea4'::uuid, 'En combien de temps le juge doit-il statuer dans un référé-liberté ?', 'mcq', '["48 heures","Un mois","Une semaine","Trois jours ouvrés"]'::jsonb, 0, 'C’est ce qui en fait une garantie efficace.', 4),
    ('7c39b151-5d4f-5a4a-a36a-4a99f56312f4'::uuid, 'd4b9499c-634f-5fcb-a604-0021194c0ea4'::uuid, 'La manifestation est-elle soumise à autorisation ?', 'mcq', '["Non, à déclaration préalable","Oui, à autorisation du préfet","Oui, à autorisation du maire","Elle est libre sans aucune formalité"]'::jsonb, 0, 'Une interdiction doit être justifiée par un risque précis.', 5),
    ('b67e482c-940a-527b-96e0-a3bef09a9a95'::uuid, 'd4b9499c-634f-5fcb-a604-0021194c0ea4'::uuid, 'De quand date la loi permettant de déclarer l’état d’urgence ?', 'mcq', '["1955","1905","1958","2015"]'::jsonb, 0, 'Elle a été appliquée de 2015 à 2017 après les attentats.', 6),
    ('a61b8035-6769-540a-82a9-cf2a0103919c'::uuid, 'd4b9499c-634f-5fcb-a604-0021194c0ea4'::uuid, 'Une liberté fondamentale ne peut jamais être limitée.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle peut l’être, mais sous conditions strictes et sous contrôle du juge.', 7),
    ('58704dd1-776f-5948-bbed-b1b8ed5bdfc2'::uuid, 'd4b9499c-634f-5fcb-a604-0021194c0ea4'::uuid, 'Quel risque principal les régimes d’exception font-ils courir ?', 'mcq', '["Que des mesures exceptionnelles passent dans le droit commun","Qu’ils coûtent trop cher","Qu’ils soient inefficaces contre la délinquance","Qu’ils soient impopulaires"]'::jsonb, 0, 'D’où l’importance du contrôle parlementaire et juridictionnel.', 8),
    ('b9aa1a5b-9745-5965-81de-6736512ecd52'::uuid, '966a5e67-62a9-58d9-aef5-77eecabe19c9'::uuid, 'Que change la loi du 29 juillet 1881 ?', 'mcq', '["Elle supprime l’autorisation préalable et instaure un contrôle a posteriori","Elle crée la censure administrative","Elle interdit les journaux d’opinion","Elle nationalise la presse"]'::jsonb, 0, 'On répond de ce qu’on publie, on ne demande plus la permission.', 1),
    ('26fa189b-c00a-5e2b-8f0c-0fc66aae1a10'::uuid, '966a5e67-62a9-58d9-aef5-77eecabe19c9'::uuid, 'Qu’est-ce que la diffamation ?', 'mcq', '["Imputer un fait précis portant atteinte à l’honneur d’une personne","Insulter quelqu’un sans imputer de fait","Publier une information vraie","Critiquer une idée"]'::jsonb, 0, 'L’injure, elle, n’impute aucun fait précis.', 2),
    ('1b304162-52d4-5ff5-9209-d36d490d1655'::uuid, '966a5e67-62a9-58d9-aef5-77eecabe19c9'::uuid, 'Que renforce la loi Pleven de 1972 ?', 'mcq', '["La répression des propos racistes","La protection des sources","L’indépendance des rédactions","Le financement de la presse"]'::jsonb, 0, 'La loi Gayssot de 1990 vise la négation des crimes contre l’humanité.', 3),
    ('80c622cc-e760-5a3f-8310-3bb2fbcc3191'::uuid, '966a5e67-62a9-58d9-aef5-77eecabe19c9'::uuid, 'Depuis quelle année la protection des sources des journalistes est-elle inscrite dans la loi ?', 'mcq', '["2010","1881","1972","2016"]'::jsonb, 0, 'Elle ne peut être levée que pour un impératif prépondérant d’intérêt public.', 4),
    ('9cad4792-c32a-5f9e-bb61-adc54abe0bb8'::uuid, '966a5e67-62a9-58d9-aef5-77eecabe19c9'::uuid, 'Quelle autorité régule l’audiovisuel et les plateformes depuis 2022 ?', 'mcq', '["L’Arcom","Le CSA","L’Hadopi","La CNIL"]'::jsonb, 0, 'Née de la fusion du CSA et de l’Hadopi.', 5),
    ('09c0f173-675e-5153-8ae1-b9018da35b00'::uuid, '966a5e67-62a9-58d9-aef5-77eecabe19c9'::uuid, 'Qu’est-ce qu’une procédure-bâillon ?', 'mcq', '["Une action en justice destinée à épuiser financièrement un média","Une interdiction de publier","Un droit de réponse","Une saisie de journaux"]'::jsonb, 0, 'Elle vise à décourager l’enquête plus qu’à gagner le procès.', 6),
    ('92734993-e70b-52c3-9f83-5d75022de431'::uuid, '966a5e67-62a9-58d9-aef5-77eecabe19c9'::uuid, 'La liberté de la presse profite surtout aux journalistes.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle protège d’abord le droit du public à être informé.', 7),
    ('df872a01-7e73-5262-825b-3461179affc2'::uuid, '966a5e67-62a9-58d9-aef5-77eecabe19c9'::uuid, 'Que permet la clause de conscience d’un journaliste ?', 'mcq', '["Quitter son journal en cas de changement de ligne éditoriale, avec indemnités","Refuser toute enquête","Publier sans signer","Ne pas révéler ses sources"]'::jsonb, 0, 'C’est une garantie d’indépendance professionnelle.', 8),
    ('701a5ef1-2582-5718-9b48-dfd6433bb010'::uuid, '32f1b7e2-74d5-5d36-ae48-8444a1de9aae'::uuid, 'Quel article de la Déclaration de 1789 consacre la liberté d’expression ?', 'mcq', '["L’article 11","L’article 4","L’article 16","L’article 1"]'::jsonb, 0, 'La libre communication des pensées et des opinions.', 1),
    ('ea93357d-0811-590e-9bc4-1dfb3d9eca2e'::uuid, '32f1b7e2-74d5-5d36-ae48-8444a1de9aae'::uuid, 'Que protège aussi la liberté d’expression, selon la Cour européenne ?', 'mcq', '["Les idées qui heurtent, choquent ou inquiètent","Uniquement les idées consensuelles","Uniquement les propos scientifiques","Uniquement la parole publique officielle"]'::jsonb, 0, 'C’est une formule constante de sa jurisprudence.', 2),
    ('ca1fe3eb-c01b-5efd-8eac-4adcb27f0507'::uuid, '32f1b7e2-74d5-5d36-ae48-8444a1de9aae'::uuid, 'Où passe la ligne de partage entre critique et délit ?', 'mcq', '["Entre la critique d’une idée et l’attaque de personnes pour ce qu’elles sont","Entre l’oral et l’écrit","Entre le public et le privé","Entre les majeurs et les mineurs"]'::jsonb, 0, 'La première relève du débat, la seconde de la loi pénale.', 3),
    ('6b9b7d5d-c69a-5b3f-89d1-bfd0a9cdb629'::uuid, '32f1b7e2-74d5-5d36-ae48-8444a1de9aae'::uuid, 'A-t-on le droit de critiquer une religion en France ?', 'mcq', '["Oui, critiquer une religion est licite","Non, c’est un délit","Seulement dans un cadre universitaire","Seulement si l’on est croyant"]'::jsonb, 0, 'Attaquer des personnes en raison de leur foi, en revanche, est un délit.', 4),
    ('de8da585-87b0-5038-8aff-b7e09daf0125'::uuid, '32f1b7e2-74d5-5d36-ae48-8444a1de9aae'::uuid, 'Un message public publié sous pseudonyme échappe-t-il aux poursuites ?', 'mcq', '["Non, l’anonymat n’empêche pas l’identification judiciaire","Oui, toujours","Oui, sauf sur les forums","Seulement si le compte est privé"]'::jsonb, 0, 'Une publication en ligne reste une publication.', 5),
    ('4ad6ba72-119b-501b-905a-504e4b15a55d'::uuid, '32f1b7e2-74d5-5d36-ae48-8444a1de9aae'::uuid, 'Lequel de ces propos est sanctionné par la loi ?', 'mcq', '["La provocation à la haine en raison de l’origine","La critique d’un parti politique","La caricature d’un ministre","La contestation d’une réforme"]'::jsonb, 0, 'La provocation à la haine ou à la discrimination est un délit.', 6),
    ('080aee94-ac42-598f-b35f-bf4d72bdbba9'::uuid, '32f1b7e2-74d5-5d36-ae48-8444a1de9aae'::uuid, 'Les élèves de lycée disposent d’une liberté d’expression individuelle et collective.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Dans le respect du pluralisme et de la neutralité du service public.', 7),
    ('ad260e6e-a86f-5584-aa9e-18aab785c7d3'::uuid, '32f1b7e2-74d5-5d36-ae48-8444a1de9aae'::uuid, 'Que prévoit l’article 11 au sujet des abus de cette liberté ?', 'mcq', '["Que chacun en répond dans les cas déterminés par la loi","Qu’il n’existe aucune limite","Que le roi en décide","Que les tribunaux sont incompétents"]'::jsonb, 0, 'La responsabilité est inscrite dans le texte fondateur lui-même.', 8),
    ('1a2b31da-b04d-5e99-8c43-323d5bdd69ee'::uuid, 'dea761c5-b15c-5b70-ae05-4f6d9e55b9ef'::uuid, 'Quel texte européen impose depuis 2023-2024 des obligations aux très grandes plateformes ?', 'mcq', '["Le Digital Services Act (DSA)","Le RGPD","La LCEN","La directive e-commerce"]'::jsonb, 0, 'Transparence des algorithmes, analyse des risques, audits indépendants.', 1),
    ('3fece9d1-81bf-53d0-baac-6b3f7a3dc13f'::uuid, 'dea761c5-b15c-5b70-ae05-4f6d9e55b9ef'::uuid, 'Que prévoit la LCEN de 2004 pour les hébergeurs ?', 'mcq', '["Ils doivent retirer promptement un contenu manifestement illicite signalé","Ils sont responsables de tout contenu publié","Ils n’ont aucune obligation","Ils doivent valider chaque publication"]'::jsonb, 0, 'Pas de responsabilité a priori, mais une obligation de retrait après signalement.', 2),
    ('7767f0dd-c866-5052-a180-f0bda32dd668'::uuid, 'dea761c5-b15c-5b70-ae05-4f6d9e55b9ef'::uuid, 'Sur quoi les algorithmes de recommandation sont-ils optimisés ?', 'mcq', '["L’attention et l’engagement","La véracité des informations","La diversité des opinions","La qualité rédactionnelle"]'::jsonb, 0, 'Ce qui indigne retient l’attention, donc circule.', 3),
    ('1854e276-f333-5fea-bb91-35948e113998'::uuid, 'dea761c5-b15c-5b70-ae05-4f6d9e55b9ef'::uuid, 'Qu’appelle-t-on chambre d’écho ?', 'mcq', '["Un environnement où l’on ne rencontre que des avis semblables au sien","Un forum de discussion animé","Un studio d’enregistrement","Un espace de modération"]'::jsonb, 0, 'Elle donne l’illusion que tout le monde pense comme soi.', 4),
    ('a282a1ef-585c-545f-b7d9-b45f3cfa7f1b'::uuid, 'dea761c5-b15c-5b70-ae05-4f6d9e55b9ef'::uuid, 'Quelle autorité française contrôle l’usage des données personnelles ?', 'mcq', '["La CNIL","L’Arcom","L’Autorité de la concurrence","Le Défenseur des droits"]'::jsonb, 0, 'Dans le cadre du RGPD, applicable depuis 2018.', 5),
    ('d33d72f5-001a-559b-bffb-02c060d48180'::uuid, 'dea761c5-b15c-5b70-ae05-4f6d9e55b9ef'::uuid, 'Quelle plateforme permet de signaler des contenus illicites en ligne en France ?', 'mcq', '["Pharos","Pronote","Ameli","FranceConnect"]'::jsonb, 0, 'Le 3018 est dédié au cyberharcèlement des jeunes.', 6),
    ('305a1fb9-93a4-502d-a1b8-d57ef1bd32ce'::uuid, 'dea761c5-b15c-5b70-ae05-4f6d9e55b9ef'::uuid, 'Une régulation trop stricte peut conduire les plateformes à la surcensure.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Menacées d’amende, elles retirent par précaution des contenus légaux.', 7),
    ('9e79282d-b390-59a8-b06f-49dae8fca832'::uuid, 'dea761c5-b15c-5b70-ae05-4f6d9e55b9ef'::uuid, 'Quelle est la difficulté propre à la modération des plateformes ?', 'mcq', '["Elle applique des règles privées, à très grande échelle et très vite","Elle est décidée par le Parlement","Elle est confiée aux tribunaux","Elle ne concerne que les contenus payants"]'::jsonb, 0, 'D’où l’exigence de transparence et de voies de recours.', 8),
    ('623c90ec-4564-50a7-a6e1-78a42d3c28c2'::uuid, 'bc8bf7d4-602a-5369-93b3-d8f75f54b1be'::uuid, 'Depuis quand la Charte de l’environnement a-t-elle valeur constitutionnelle ?', 'mcq', '["2005","1992","2015","2021"]'::jsonb, 0, 'Elle est adossée à la Constitution, comme la Déclaration de 1789.', 1),
    ('48203d1a-ca71-5ed3-bcf8-e7df008dfd8a'::uuid, 'bc8bf7d4-602a-5369-93b3-d8f75f54b1be'::uuid, 'Que signifie le principe de précaution ?', 'mcq', '["Prendre des mesures face à un risque incertain mais grave et irréversible","Réparer les dommages après coup","Interdire toute activité industrielle","Attendre la certitude scientifique avant d’agir"]'::jsonb, 0, 'Il se distingue de la prévention, qui vise un risque déjà connu.', 2),
    ('1443af13-6556-5a73-b0d0-a9a40e520b63'::uuid, 'bc8bf7d4-602a-5369-93b3-d8f75f54b1be'::uuid, 'Que veut dire le principe pollueur-payeur ?', 'mcq', '["Celui qui pollue supporte le coût de la réparation","La pollution est autorisée si elle est payée","L’État paie les dégâts environnementaux","Les consommateurs financent la dépollution"]'::jsonb, 0, 'Il internalise le coût environnemental dans l’activité.', 3),
    ('f1a371af-c648-5ce1-817f-0843636be139'::uuid, 'bc8bf7d4-602a-5369-93b3-d8f75f54b1be'::uuid, 'Que garantit la convention d’Aarhus de 1998 ?', 'mcq', '["L’information, la participation du public et l’accès à la justice","La réduction des gaz à effet de serre","La protection des espèces menacées","Le financement des énergies renouvelables"]'::jsonb, 0, 'C’est le socle de la démocratie environnementale.', 4),
    ('574b32a6-aaa0-5303-9fa6-b9258fa5c346'::uuid, 'bc8bf7d4-602a-5369-93b3-d8f75f54b1be'::uuid, 'Quel objectif fixe l’accord de Paris de 2015 ?', 'mcq', '["Contenir le réchauffement bien en dessous de 2 °C","Interdire le charbon en 2030","Créer une taxe carbone mondiale","Doubler les surfaces protégées"]'::jsonb, 0, 'Avec un effort visant 1,5 °C.', 5),
    ('800612b7-942c-58ca-a860-826a49e6f263'::uuid, 'bc8bf7d4-602a-5369-93b3-d8f75f54b1be'::uuid, 'Qu’a reconnu la justice dans l’Affaire du siècle en 2021 ?', 'mcq', '["La responsabilité de l’État pour carence fautive en matière climatique","L’interdiction des pesticides","La nullité de l’accord de Paris","Le droit de manifester pour le climat"]'::jsonb, 0, 'Le contentieux climatique est devenu un levier réel.', 6),
    ('4a7fa74a-3399-51d9-ac48-2fd73b27d7fb'::uuid, 'bc8bf7d4-602a-5369-93b3-d8f75f54b1be'::uuid, 'Quel délit la loi Climat et résilience de 2021 a-t-elle créé ?', 'mcq', '["Le délit d’écocide","Le délit de fuite écologique","Le délit de greenwashing","Le délit de surconsommation"]'::jsonb, 0, 'Il vise les atteintes graves, durables et intentionnelles.', 7),
    ('9085e9da-bab1-5a62-9747-bd54af4ff7f2'::uuid, 'bc8bf7d4-602a-5369-93b3-d8f75f54b1be'::uuid, 'La Charte de l’environnement crée seulement des droits, sans devoirs.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle énonce aussi le devoir de prendre part à la préservation de l’environnement.', 8),
    ('cf80f558-b5df-5e0e-a0fb-dcb83a6d0164'::uuid, '15f6b8eb-0ecd-56c3-84f5-3572a6aaec7b'::uuid, 'Quels sont les trois piliers de la démocratie environnementale ?', 'mcq', '["Information, participation, accès à la justice","Vote, référendum, pétition","Prévention, précaution, réparation","État, entreprises, associations"]'::jsonb, 0, 'Ils viennent de la convention d’Aarhus de 1998.', 1),
    ('8664315d-fc99-5f90-80cb-b1852cae9796'::uuid, '15f6b8eb-0ecd-56c3-84f5-3572a6aaec7b'::uuid, 'Qu’est-ce qu’une enquête publique ?', 'mcq', '["Une procédure de consultation qui précède un grand projet d’aménagement","Un sondage d’opinion","Une enquête de police","Un référendum local obligatoire"]'::jsonb, 0, 'Elle permet au public de consulter le dossier et de faire des observations.', 2),
    ('c3115945-6750-50b5-af6b-acac5321297d'::uuid, '15f6b8eb-0ecd-56c3-84f5-3572a6aaec7b'::uuid, 'Que fait la Commission nationale du débat public ?', 'mcq', '["Elle organise des débats sur les projets d’ampleur","Elle juge les atteintes à l’environnement","Elle vote les lois environnementales","Elle délivre les permis de construire"]'::jsonb, 0, 'Une autorité indépendante saisie en amont des projets.', 3),
    ('f9fbbae5-1ae0-5fd8-8ac1-7548528e707b'::uuid, '15f6b8eb-0ecd-56c3-84f5-3572a6aaec7b'::uuid, 'Combien de citoyens composaient la Convention citoyenne pour le climat ?', 'mcq', '["150, tirés au sort","577, élus","300, désignés par les associations","1 000, volontaires"]'::jsonb, 0, 'Réunie en 2019-2020, elle a produit 149 propositions.', 4),
    ('09f5874f-3314-5e5b-8f4d-d87219271f9e'::uuid, '15f6b8eb-0ecd-56c3-84f5-3572a6aaec7b'::uuid, 'Une partie de ces propositions a nourri quelle loi ?', 'mcq', '["La loi Climat et résilience de 2021","La loi Grenelle de 2009","La loi biodiversité de 2016","La loi énergie de 2015"]'::jsonb, 0, 'Le bilan de cette reprise reste discuté.', 5),
    ('b7050936-2a00-5b21-97df-8ecda8eddf51'::uuid, '15f6b8eb-0ecd-56c3-84f5-3572a6aaec7b'::uuid, 'Que peuvent faire les associations agréées de protection de l’environnement ?', 'mcq', '["Agir en justice contre des décisions ou des atteintes","Voter les lois","Délivrer des autorisations","Sanctionner les entreprises"]'::jsonb, 0, 'L’agrément leur ouvre l’accès au juge.', 6),
    ('af3202e3-4c74-57ff-aebd-29d2e1dfa22d'::uuid, '15f6b8eb-0ecd-56c3-84f5-3572a6aaec7b'::uuid, 'Participer à une consultation publique revient à décider.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'La consultation éclaire la décision, elle ne la remplace pas.', 7),
    ('155a37d6-8652-55e0-a0a9-3668b8c6a41d'::uuid, '15f6b8eb-0ecd-56c3-84f5-3572a6aaec7b'::uuid, 'Une action militante illégale est-elle justifiée par la cause défendue ?', 'mcq', '["Non, agir pour une cause n’exonère pas du respect de la loi","Oui, si la cause est écologique","Oui, si aucune violence n’est commise","Oui, si elle est médiatisée"]'::jsonb, 0, 'C’est tout l’enjeu du débat sur la désobéissance civile.', 8),
    ('b8398f2f-fce9-5a71-b46c-a3a789c98e59'::uuid, '8f216152-50c5-5afd-b2e3-c3bd6857b003'::uuid, 'Que dit l’article 515-14 du Code civil depuis 2015 ?', 'mcq', '["Que les animaux sont des êtres vivants doués de sensibilité","Que les animaux sont des personnes juridiques","Que les animaux sont des meubles","Que les animaux appartiennent à l’État"]'::jsonb, 0, 'Ils restent toutefois soumis au régime des biens sous réserve des lois protectrices.', 1),
    ('090a7f1c-8b27-50c1-9f76-558877e29505'::uuid, '8f216152-50c5-5afd-b2e3-c3bd6857b003'::uuid, 'En quelle année la loi reconnaît-elle pour la première fois l’animal comme un être sensible ?', 'mcq', '["1976","1850","2015","2021"]'::jsonb, 0, 'La loi Grammont de 1850 ne visait que les mauvais traitements publics.', 2),
    ('2bebaed7-2c37-5d21-906b-37f1e7ef3d7f'::uuid, '8f216152-50c5-5afd-b2e3-c3bd6857b003'::uuid, 'Que prévoit la loi de 2021 contre la maltraitance animale ?', 'mcq', '["Un durcissement des sanctions et la fin progressive des animaux sauvages en cirque itinérant","La reconnaissance de la personnalité juridique des animaux","L’interdiction de l’élevage","La suppression des refuges"]'::jsonb, 0, 'Elle encadre aussi la vente d’animaux en ligne.', 3),
    ('c91f9b94-b3f2-5923-9d12-b1ba53d35323'::uuid, '8f216152-50c5-5afd-b2e3-c3bd6857b003'::uuid, 'Qu’est-ce que le welfarisme ?', 'mcq', '["La position qui vise à réduire la souffrance animale sans abolir les usages","Le refus de toute hiérarchie entre espèces","La reconnaissance de droits fondamentaux aux animaux","La défense inconditionnelle de la chasse"]'::jsonb, 0, 'Il s’oppose aux positions abolitionnistes.', 4),
    ('0ebfaf9e-457e-580a-b23e-85ced29db10e'::uuid, '8f216152-50c5-5afd-b2e3-c3bd6857b003'::uuid, 'Que conteste l’antispécisme ?', 'mcq', '["La légitimité d’une hiérarchie morale entre les espèces","L’existence des espèces","La protection des animaux domestiques","Le droit de propriété"]'::jsonb, 0, 'C’est une position philosophique, distincte du welfarisme.', 5),
    ('68dd35e6-3ee4-598d-a4be-96fe1986bd99'::uuid, '8f216152-50c5-5afd-b2e3-c3bd6857b003'::uuid, 'Que régule la convention CITES de 1973 ?', 'mcq', '["Le commerce international des espèces menacées","Les conditions d’abattage","La chasse en Europe","Les expérimentations scientifiques"]'::jsonb, 0, 'Signée à Washington, elle protège faune et flore menacées.', 6),
    ('30bff78f-1680-5553-ba65-d9aeb1220710'::uuid, '8f216152-50c5-5afd-b2e3-c3bd6857b003'::uuid, 'Quel réseau européen protège des sites naturels remarquables ?', 'mcq', '["Natura 2000","Erasmus","Interreg","Copernicus"]'::jsonb, 0, 'Issu des directives Oiseaux et Habitats.', 7),
    ('40d02387-eeeb-5ebd-92fc-570b5ba7ceea'::uuid, '8f216152-50c5-5afd-b2e3-c3bd6857b003'::uuid, 'Protéger un animal individuel et protéger une espèce reviennent au même.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Les deux logiques peuvent s’opposer, par exemple face à une espèce invasive.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('emc');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('emc')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 284 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 284 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
