-- =============================================================================
-- Studuel — Migration 291 : HISTOIRE 3e — LE PROGRAMME COMPLET (14 fiches)
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 291 --modules histoire-3e
--
-- CONSTAT : la Troisième n'avait que QUATRE fiches d'histoire, héritées du
-- premier jeu de données de l'app, pour un programme qui en demande quatorze —
-- l'Europe dans les guerres totales, le monde depuis 1945, et la République
-- française repensée. Un élève de 3e qui révisait les régimes totalitaires des
-- années 1930, la France de Vichy, la décolonisation, les deux temps de la guerre
-- froide, la construction européenne, la géopolitique du monde actuel, la
-- refondation de 1944-1947, les années de Gaulle ou les Trente Glorieuses ne
-- trouvait RIEN. Cette migration installe les 14 fiches, rangées sous leurs 3
-- chapitres, et retire les 4 fiches génériques que ce découpage recouvre.
-- LA GÉOGRAPHIE DE 3e N'EST PAS TRAITÉE ICI : sa seule fiche héritée ("Les aires
-- urbaines en France") est CONSERVÉE, car la supprimer laisserait la géographie
-- entièrement vide.
--
-- Cette migration apporte : 14 chapitres, 14 leçons,
-- 14 quiz et 112 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 0. Ménage ----------------------------------------------------------------
-- [histoire-geo] Les colonnes chapters.theme (migration 234) et chapters.discipline
-- [histoire-geo] (migration 247) conditionnent tout ce qui suit : ce module range ses 14 fiches
-- [histoire-geo] sous 3 chapitres et un rayon, et l'INSERT écrit les deux colonnes. Elles sont
-- [histoire-geo] REPRISES ici en ADD COLUMN IF NOT EXISTS parce qu'on ne peut pas garantir que la
-- [histoire-geo] 234 et la 247 soient passées en production — sans cette reprise, la migration
-- [histoire-geo] échouerait sur "column chapters.theme does not exist", les 4 anciens chapitres
-- [histoire-geo] déjà supprimés et les 14 neufs pas encore posés : une matière vide.
-- [histoire-geo] Le GRANT n'est pas décoratif : la migration 182 a révoqué le SELECT de table sur
-- [histoire-geo] chapters (pour cacher mind_map) et ne l'a rendu que colonne par colonne. Une
-- [histoire-geo] colonne ajoutée après elle n'hérite d'aucun droit — sans lui, l'app lirait
-- [histoire-geo] "permission denied" au lieu du chapitre.
ALTER TABLE public.chapters ADD COLUMN IF NOT EXISTS theme TEXT;
GRANT SELECT (theme) ON public.chapters TO anon;
GRANT SELECT (theme) ON public.chapters TO authenticated;

ALTER TABLE public.chapters ADD COLUMN IF NOT EXISTS discipline TEXT;
GRANT SELECT (discipline) ON public.chapters TO anon;
GRANT SELECT (discipline) ON public.chapters TO authenticated;

-- [histoire-geo] Les 4 fiches d'histoire héritées partent. Toutes les quatre sont
-- [histoire-geo] recouvertes au titre près par le nouveau découpage : les garder ferait deux
-- [histoire-geo] objets voisins à deux places différentes, un en-tête de section et une ligne
-- [histoire-geo] dans la liste.
-- [histoire-geo] "Les aires urbaines en France" N'EST PAS DANS LA LISTE, et c'est volontaire :
-- [histoire-geo] c'est la seule fiche de géographie de la 3e, et ce module ne traite que
-- [histoire-geo] l'histoire. La supprimer laisserait la géographie entièrement vide.
-- [histoire-geo] ATTENTION À L'APOSTROPHE : les titres de la 008 s'écrivent avec l'apostrophe
-- [histoire-geo] DROITE, pas la typographique qu'emploient les fiches neuves. Un DELETE qui se
-- [histoire-geo] tromperait de signe ne trouverait rien EN SILENCE.
-- [histoire-geo] Le filtre level = '3e' est indispensable : "La Première Guerre mondiale" et "La
-- [histoire-geo] Seconde Guerre mondiale" sont aussi des titres de 1re et de Tle, et le ménage
-- [histoire-geo] mordrait sur le lycée.
-- [histoire-geo] L'ordre compte : la file "À revoir" d'abord (review_items.item_id n'a PAS de clé
-- [histoire-geo] étrangère), puis les quiz (quizzes.lesson_id est ON DELETE SET NULL : ils
-- [histoire-geo] survivraient orphelins à leur chapitre, mais toujours tirables par le moteur de
-- [histoire-geo] questions), puis les chapitres, dont les leçons partent en cascade.
-- [histoire-geo] Le ménage tourne AVANT les insertions à CHAQUE passage : sans la borne des
-- [histoire-geo] quatre titres, un rejeu effacerait les quiz des 14 fiches neuves.
DELETE FROM public.review_items ri
 USING public.quiz_questions qq, public.quizzes qz, public.lessons l,
       public.chapters c, public.subjects s
 WHERE ri.item_kind = 'question'
   AND ri.item_id = qq.id
   AND qq.quiz_id = qz.id
   AND qz.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'histoire-geo'
   AND c.level = '3e'
   AND c.title IN ('La Première Guerre mondiale',
                   'L''Europe entre les deux guerres',
                   'La Seconde Guerre mondiale',
                   'La France de 1944 à nos jours');

DELETE FROM public.quizzes q
 USING public.lessons l, public.chapters c, public.subjects s
 WHERE q.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'histoire-geo'
   AND c.level = '3e'
   AND c.title IN ('La Première Guerre mondiale',
                   'L''Europe entre les deux guerres',
                   'La Seconde Guerre mondiale',
                   'La France de 1944 à nos jours');

DELETE FROM public.chapters c
 USING public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'histoire-geo'
   AND c.level = '3e'
   AND c.title IN ('La Première Guerre mondiale',
                   'L''Europe entre les deux guerres',
                   'La Seconde Guerre mondiale',
                   'La France de 1944 à nos jours');

-- [histoire-geo] La fiche de géographie survivante est repoussée en position 99. Sans cet
-- [histoire-geo] UPDATE elle resterait en position 5 et s'intercalerait au milieu du programme
-- [histoire-geo] d'histoire, que ce module numérote de 1 à 14 : la page matière trie par
-- [histoire-geo] position, et un chapitre de géographie tomberait entre deux fiches sur la guerre
-- [histoire-geo] froide. En 99, elle ferme la liste, sous l'en-tête "Autres chapitres" que
-- [histoire-geo] ChapterList réserve aux chapitres sans thème.
-- [histoire-geo] L'UPDATE est idempotent : rejoué, il repose la même valeur.
UPDATE public.chapters c
   SET position = 99
  FROM public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'histoire-geo'
   AND c.level = '3e'
   AND c.title = 'Les aires urbaines en France'
   AND c.position IS DISTINCT FROM 99;

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position, theme, discipline)
SELECT v.id, s.id, v.level, v.title, v.position, v.theme, v.discipline
  FROM (VALUES
    ('6583dbde-d239-5bcb-a891-6ab8836842bd'::uuid, 'histoire-geo', '3e', 'La Première Guerre mondiale : vers une guerre totale', 1, 'L’Europe, un théâtre majeur des guerres totales (1914-1945)', 'histoire'),
    ('7a8b009c-6876-5432-bbd4-573d70718708'::uuid, 'histoire-geo', '3e', 'Les régimes totalitaires dans les années 1930', 2, 'L’Europe, un théâtre majeur des guerres totales (1914-1945)', 'histoire'),
    ('4901829b-81f4-559d-a2d7-6b3b4b9ba763'::uuid, 'histoire-geo', '3e', 'La France durant l’entre-deux-guerres', 3, 'L’Europe, un théâtre majeur des guerres totales (1914-1945)', 'histoire'),
    ('b0de9d40-355e-5c3e-b17d-9d2f5aa87a43'::uuid, 'histoire-geo', '3e', 'La Seconde Guerre mondiale : une guerre d’anéantissement', 4, 'L’Europe, un théâtre majeur des guerres totales (1914-1945)', 'histoire'),
    ('12f21afe-be64-544d-9d90-6558e3384b6f'::uuid, 'histoire-geo', '3e', 'La France de Vichy (1940-1944)', 5, 'L’Europe, un théâtre majeur des guerres totales (1914-1945)', 'histoire'),
    ('e0803bfa-c2f5-5ae6-bfdc-284d5e9dbbee'::uuid, 'histoire-geo', '3e', 'La décolonisation', 6, 'Le monde depuis 1945', 'histoire'),
    ('ec58f7aa-3ac6-522b-a154-d39c11aff8b0'::uuid, 'histoire-geo', '3e', 'Le monde durant la guerre froide (1947-1962)', 7, 'Le monde depuis 1945', 'histoire'),
    ('c715f435-ea13-5b1c-9d45-a1440d2aa8fb'::uuid, 'histoire-geo', '3e', 'Le monde durant la guerre froide (1963-1991)', 8, 'Le monde depuis 1945', 'histoire'),
    ('4a141259-43ec-58de-ae70-e895bf65edab'::uuid, 'histoire-geo', '3e', 'La construction européenne', 9, 'Le monde depuis 1945', 'histoire'),
    ('ffa4d950-59b4-5e27-acbe-c80fb3ae0682'::uuid, 'histoire-geo', '3e', 'La géopolitique du monde actuel', 10, 'Le monde depuis 1945', 'histoire'),
    ('d47a1340-11ae-5fcc-8d34-f0b41d7e2e36'::uuid, 'histoire-geo', '3e', '1944-1947 : refonder la République, redéfinir la démocratie', 11, 'Françaises et Français dans une République repensée', 'histoire'),
    ('a6a17bba-64cd-5ff0-b38c-324ae198fc0d'::uuid, 'histoire-geo', '3e', 'Les années de Gaulle (1958-1969)', 12, 'Françaises et Français dans une République repensée', 'histoire'),
    ('23f482c1-6c94-510f-9a71-dc22f6c9ebea'::uuid, 'histoire-geo', '3e', 'Les Trente Glorieuses', 13, 'Françaises et Français dans une République repensée', 'histoire'),
    ('4b5a2da3-153c-58c8-a59b-04f04d792b1c'::uuid, 'histoire-geo', '3e', 'La Ve République à l’épreuve de la durée (1958-2012)', 14, 'Françaises et Français dans une République repensée', 'histoire')
  ) AS v(id, slug, level, title, position, theme, discipline)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 1 bis. Axes du programme -------------------------------------------------
-- `chapters.theme` (migration 234) : l’intitulé du programme officiel qui
-- coiffe le chapitre. La page matière s’en sert pour grouper au lieu
-- d’aligner 28 lignes à plat. UPDATE et non INSERT : le chapitre peut déjà
-- exister (l’INSERT précédent l’aurait alors ignoré).
UPDATE public.chapters c SET theme = v.theme
  FROM (VALUES
    ('6583dbde-d239-5bcb-a891-6ab8836842bd'::uuid, 'L’Europe, un théâtre majeur des guerres totales (1914-1945)'),
    ('7a8b009c-6876-5432-bbd4-573d70718708'::uuid, 'L’Europe, un théâtre majeur des guerres totales (1914-1945)'),
    ('4901829b-81f4-559d-a2d7-6b3b4b9ba763'::uuid, 'L’Europe, un théâtre majeur des guerres totales (1914-1945)'),
    ('b0de9d40-355e-5c3e-b17d-9d2f5aa87a43'::uuid, 'L’Europe, un théâtre majeur des guerres totales (1914-1945)'),
    ('12f21afe-be64-544d-9d90-6558e3384b6f'::uuid, 'L’Europe, un théâtre majeur des guerres totales (1914-1945)'),
    ('e0803bfa-c2f5-5ae6-bfdc-284d5e9dbbee'::uuid, 'Le monde depuis 1945'),
    ('ec58f7aa-3ac6-522b-a154-d39c11aff8b0'::uuid, 'Le monde depuis 1945'),
    ('c715f435-ea13-5b1c-9d45-a1440d2aa8fb'::uuid, 'Le monde depuis 1945'),
    ('4a141259-43ec-58de-ae70-e895bf65edab'::uuid, 'Le monde depuis 1945'),
    ('ffa4d950-59b4-5e27-acbe-c80fb3ae0682'::uuid, 'Le monde depuis 1945'),
    ('d47a1340-11ae-5fcc-8d34-f0b41d7e2e36'::uuid, 'Françaises et Français dans une République repensée'),
    ('a6a17bba-64cd-5ff0-b38c-324ae198fc0d'::uuid, 'Françaises et Français dans une République repensée'),
    ('23f482c1-6c94-510f-9a71-dc22f6c9ebea'::uuid, 'Françaises et Français dans une République repensée'),
    ('4b5a2da3-153c-58c8-a59b-04f04d792b1c'::uuid, 'Françaises et Français dans une République repensée')
  ) AS v(id, theme)
 WHERE c.id = v.id AND c.theme IS DISTINCT FROM v.theme;

-- 1 ter. Rayons du dossier -------------------------------------------------
-- `chapters.discipline` (migration 247) : le rayon de la matière auquel la
-- fiche appartient. La page matière en fait un onglet par rayon.
UPDATE public.chapters c SET discipline = v.discipline
  FROM (VALUES
    ('6583dbde-d239-5bcb-a891-6ab8836842bd'::uuid, 'histoire'),
    ('7a8b009c-6876-5432-bbd4-573d70718708'::uuid, 'histoire'),
    ('4901829b-81f4-559d-a2d7-6b3b4b9ba763'::uuid, 'histoire'),
    ('b0de9d40-355e-5c3e-b17d-9d2f5aa87a43'::uuid, 'histoire'),
    ('12f21afe-be64-544d-9d90-6558e3384b6f'::uuid, 'histoire'),
    ('e0803bfa-c2f5-5ae6-bfdc-284d5e9dbbee'::uuid, 'histoire'),
    ('ec58f7aa-3ac6-522b-a154-d39c11aff8b0'::uuid, 'histoire'),
    ('c715f435-ea13-5b1c-9d45-a1440d2aa8fb'::uuid, 'histoire'),
    ('4a141259-43ec-58de-ae70-e895bf65edab'::uuid, 'histoire'),
    ('ffa4d950-59b4-5e27-acbe-c80fb3ae0682'::uuid, 'histoire'),
    ('d47a1340-11ae-5fcc-8d34-f0b41d7e2e36'::uuid, 'histoire'),
    ('a6a17bba-64cd-5ff0-b38c-324ae198fc0d'::uuid, 'histoire'),
    ('23f482c1-6c94-510f-9a71-dc22f6c9ebea'::uuid, 'histoire'),
    ('4b5a2da3-153c-58c8-a59b-04f04d792b1c'::uuid, 'histoire')
  ) AS v(id, discipline)
 WHERE c.id = v.id AND c.discipline IS DISTINCT FROM v.discipline;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('9bed4dd1-f2c0-5b81-9e62-b30b541d85af', '6583dbde-d239-5bcb-a891-6ab8836842bd', '1914-1918 : quand la guerre engloutit les sociétés', E'La Première Guerre mondiale (**28 juillet 1914 – 11 novembre 1918**) oppose la **Triple-Entente** (France, Royaume-Uni, Russie, rejoints par l’Italie en 1915 et les États-Unis en 1917) aux **Empires centraux** (Allemagne, Autriche-Hongrie, Empire ottoman). Elle inaugure un type de conflit nouveau : la **guerre totale**.\n\n## Trois phases\n- **1914 : la guerre de mouvement.** L’attentat de Sarajevo (28 juin) déclenche le jeu des alliances. Les armées avancent, puis se bloquent après la bataille de la Marne (septembre).\n- **1915-1917 : la guerre de position.** Le front se fige sur 700 km de **tranchées**. **Verdun** (février-décembre 1916) et la **Somme** (1916) coûtent des centaines de milliers de vies pour quelques kilomètres.\n- **1917-1918 : le tournant.** La Russie sort du conflit après la révolution bolchevique ; les **États-Unis** entrent en guerre en avril 1917. La guerre de mouvement reprend et l’Allemagne signe l’armistice le 11 novembre 1918.\n\n## Qu’est-ce qu’une guerre totale ?\nC’est une guerre qui mobilise **toutes** les ressources d’un pays :\n- **militaires** : plus de 70 millions d’hommes mobilisés, conscription générale ;\n- **économiques** : usines converties à l’armement, femmes à l’usine, emprunts de guerre ;\n- **scientifiques** : gaz de combat, chars, aviation, sous-marins ;\n- **morales** : censure, **propagande**, « bourrage de crâne ».\n\n> La frontière entre le front et l’arrière s’efface : les civils deviennent une cible et une ressource.\n\n## La violence de masse\nLa vie dans les **tranchées** — boue, rats, poux, bombardements, attaques à la baïonnette — provoque des **mutineries** en 1917. Le **génocide des Arméniens** (1915-1916), organisé par le gouvernement jeune-turc, fait environ 1,2 million de morts : c’est le premier génocide du siècle.\n\n## Un bilan écrasant\nPrès de **10 millions de morts** et 20 millions de blessés, dont les **« gueules cassées »**. Le **traité de Versailles** (28 juin 1919) impose à l’Allemagne la responsabilité de la guerre, des réparations et des pertes territoriales : elle y voit un **diktat**. Quatre empires disparaissent (allemand, austro-hongrois, ottoman, russe) et la **Société des Nations** est créée pour garantir la paix — sans les États-Unis, qui refusent d’y entrer.', 1),
  ('b3b5edd6-d735-51cb-a099-3191ae091989', '7a8b009c-6876-5432-bbd4-573d70718708', 'URSS, Italie, Allemagne : l’État contre l’individu', E'Un régime **totalitaire** ne se contente pas d’exercer le pouvoir : il veut **transformer l’homme** et contrôler la société tout entière — le travail, les loisirs, la famille, la pensée. Trois régimes en donnent le modèle dans l’entre-deux-guerres.\n\n## Les traits communs\n- Un **parti unique** et un **chef** placé au-dessus des lois, objet d’un **culte de la personnalité**.\n- Une **idéologie** officielle qui prétend expliquer le monde entier.\n- La **propagande** (radio, cinéma, affiches, défilés) et l’**embrigadement de la jeunesse**.\n- La **terreur** : police politique, camps, procès truqués, dénonciation.\n- La suppression des **libertés** : presse, réunion, opposition, syndicats.\n- Une **économie dirigée** par l’État.\n\n## L’URSS de Staline\nAprès la révolution de 1917 et la mort de Lénine (1924), **Staline** impose son pouvoir. La **collectivisation** des terres liquide les paysans propriétaires (les « koulaks ») et provoque une famine terrible en Ukraine (**Holodomor**, 1932-1933). Les **plans quinquennaux** industrialisent le pays à marche forcée. Les **Grandes Purges** (1936-1938) et le **Goulag** frappent jusqu’aux cadres du parti.\n\n## L’Italie de Mussolini\nArrivé au pouvoir en **1922** (marche sur Rome), Mussolini instaure le **fascisme** : parti unique, chemises noires, culte du *Duce*, encadrement de la jeunesse (*Balilla*), conquête coloniale de l’Éthiopie en 1935.\n\n## L’Allemagne d’Hitler\nNommé chancelier le **30 janvier 1933**, Hitler obtient les pleins pouvoirs en quelques semaines. Le **IIIe Reich** repose sur une idéologie **raciste** et **antisémite** : les **lois de Nuremberg** (1935) privent les Juifs de la citoyenneté, la **Nuit de Cristal** (novembre 1938) déchaîne la violence. La Gestapo, les SS et les premiers camps (Dachau) installent la terreur, tandis que le réarmement prépare la guerre.\n\n> Trois régimes, une même ambition : fabriquer un « homme nouveau » et faire disparaître l’individu dans la masse.\n\n## Des différences réelles\nLe communisme stalinien vise une société sans classes et s’appuie sur la lutte des classes ; le nazisme repose sur la **race** et la conquête d’un « espace vital ». Les moyens se ressemblent, les buts s’opposent.', 1),
  ('4cd2f9a3-4a09-5826-86e2-24b0258e5ab9', '4901829b-81f4-559d-a2d7-6b3b4b9ba763', 'Une République ébranlée, du deuil au Front populaire', E'Sortie victorieuse mais **saignée** de la Grande Guerre — 1,4 million de morts, des régions dévastées, une dette immense —, la France de l’entre-deux-guerres traverse la reconstruction, la crise, puis une profonde crise politique.\n\n## Le poids du deuil et la reconstruction\nChaque commune élève son **monument aux morts** ; les anciens combattants s’organisent ; les « gueules cassées » rappellent le prix payé. Les régions du Nord et de l’Est sont reconstruites. Les **années 1920** apportent une relative prospérité et l’espoir d’une paix durable (accords de Locarno, 1925).\n\n## La crise des années 1930\nLa crise venue des États-Unis atteint la France en **1931-1932** : chute de la production, chômage, faillites agricoles. Les gouvernements se succèdent sans stabilité. La confiance dans la République s’effrite.\n\n## Le 6 février 1934\nDes **ligues d’extrême droite** (Croix-de-Feu, Action française, Jeunesses patriotes) manifestent devant la Chambre des députés ; l’affrontement fait une quinzaine de morts. Une partie de la gauche y voit une tentative de coup de force **antiparlementaire** et décide de s’unir.\n\n> Le 6 février 1934 est le déclencheur : la peur du fascisme fait naître l’union des gauches.\n\n## Le Front populaire (1936-1938)\nLa coalition des **socialistes** (SFIO), **radicaux** et **communistes** remporte les élections de mai 1936. **Léon Blum** devient président du Conseil. Une immense vague de grèves avec occupation d’usines accompagne cette victoire et débouche sur les **accords Matignon** (7 juin 1936) :\n- **hausse des salaires** d’environ 12 % ;\n- **conventions collectives** et reconnaissance des délégués du personnel ;\n- **semaine de 40 heures** ;\n- **deux semaines de congés payés**.\nS’y ajoutent la scolarité obligatoire jusqu’à 14 ans et la création d’un sous-secrétariat aux Sports et Loisirs.\n\n## Un héritage durable, une fin rapide\nLe Front populaire se défait dès 1938, miné par les divisions, la crise économique et la guerre d’Espagne. Mais les congés payés, les 40 heures et les conventions collectives marquent durablement la société française — et le mot « vacances » change de sens pour des millions de familles.', 1),
  ('7c6ae354-926e-55fe-8308-3eabc3e60311', 'b0de9d40-355e-5c3e-b17d-9d2f5aa87a43', '1939-1945 : une guerre qui vise des peuples', E'La Seconde Guerre mondiale (**1er septembre 1939 – 2 septembre 1945**) dépasse la guerre totale : elle devient une **guerre d’anéantissement**, où l’ennemi n’est plus seulement une armée à battre mais un peuple à détruire.\n\n## Les grandes étapes\n- **1939-1941 : les victoires de l’Axe.** Invasion de la Pologne, **Blitzkrieg** à l’Ouest, défaite française de juin 1940, bataille d’Angleterre, invasion de l’URSS (opération Barbarossa, juin 1941).\n- **1941-1942 : la mondialisation.** **Pearl Harbor** (7 décembre 1941) fait entrer les États-Unis. Le conflit devient planétaire.\n- **1942-1943 : le tournant.** **Stalingrad**, El-Alamein, Midway, Guadalcanal : l’Axe recule sur tous les fronts.\n- **1943-1945 : la victoire des Alliés.** Débarquements en Sicile (1943), en **Normandie** (6 juin 1944) et en Provence, libération de Paris, capitulation allemande le **8 mai 1945**, bombes atomiques sur **Hiroshima et Nagasaki** (6 et 9 août), capitulation japonaise le 2 septembre.\n\n## Une guerre d’anéantissement\nLe nazisme mène à l’Est une guerre idéologique : populations slaves considérées comme inférieures, prisonniers soviétiques laissés mourir par millions, villages entiers détruits. Les bombardements massifs frappent les villes (Londres, Coventry, Dresde, Tokyo). L’arme nucléaire, employée deux fois, change la nature même de la guerre.\n\n## La Shoah\nL’extermination des Juifs d’Europe se fait en deux temps : les **Einsatzgruppen** fusillent à l’Est dès 1941 (la « Shoah par balles », Babi Yar) ; la **conférence de Wannsee** (janvier 1942) organise ensuite la déportation vers les **camps d’extermination** (Auschwitz-Birkenau, Treblinka, Sobibor…). Environ **5 à 6 millions de Juifs** sont assassinés. Le **génocide des Tsiganes** fait entre 200 000 et 500 000 victimes.\n\n> Un **camp de concentration** enferme et fait travailler jusqu’à la mort ; un **camp d’extermination** est conçu pour tuer dès l’arrivée. La distinction est essentielle.\n\n## Un bilan sans précédent\nEntre **50 et 60 millions de morts**, dont une majorité de **civils** — l’inverse de 1914-1918. L’Europe est en ruines. En 1945 naissent l’**ONU** (juin 1945) et le **procès de Nuremberg**, qui invente la notion de **crime contre l’humanité**.', 1),
  ('a1b6ad62-1710-53f0-bc15-c547c4251b22', '12f21afe-be64-544d-9d90-6558e3384b6f', 'Défaite, collaboration, Résistance', E'En **juin 1940**, l’armée française s’effondre en six semaines. Le 17 juin, **Pétain** annonce qu’il faut « cesser le combat » ; le **22 juin**, l’armistice est signé. Le **10 juillet 1940**, l’Assemblée nationale lui accorde les pleins pouvoirs : la République laisse place à l’**État français**, dont la capitale est **Vichy**.\n\n## Un régime autoritaire\nLa devise devient « **Travail, Famille, Patrie** ». Le Parlement ne siège plus, les partis et les syndicats sont dissous, la presse est censurée, un **culte du Maréchal** est organisé. La **Révolution nationale** prétend redresser le pays par le retour à la terre, à l’ordre et à la religion, et désigne des responsables de la défaite : la République, les communistes, les étrangers, les Juifs.\n\n## L’antisémitisme d’État\nSans qu’aucune autorité allemande ne l’exige, Vichy promulgue le **statut des Juifs** (**3 octobre 1940**, aggravé en juin 1941) qui les exclut de la fonction publique, de l’enseignement, de la presse. La **rafle du Vél’ d’Hiv’** (16-17 juillet 1942), menée par la **police française**, arrête plus de 13 000 personnes, dont plus de 4 000 enfants. Environ **75 000 Juifs** sont déportés de France ; moins de 3 % reviennent.\n\n## La collaboration\nL’entrevue de **Montoire** (24 octobre 1940) scelle la politique de collaboration. Elle devient économique (livraisons, **STO** — service du travail obligatoire — en 1943), policière (Milice créée en janvier 1943) et idéologique.\n\n> Une **collaboration d’État**, décidée à Vichy, s’ajoute à la contrainte de l’occupation : c’est ce que la France a mis un demi-siècle à reconnaître officiellement (discours de Jacques Chirac, 1995).\n\n## La Résistance\nLe **18 juin 1940**, depuis Londres, **de Gaulle** appelle à poursuivre le combat : c’est l’acte de naissance de la **France libre**. À l’intérieur, des réseaux et des mouvements se forment (Combat, Libération, Franc-Tireur), publient des journaux clandestins, renseignent, sabotent. **Jean Moulin** unifie les mouvements au sein du **Conseil national de la Résistance**, qui se réunit le **27 mai 1943** et adopte en 1944 un programme de réformes.\n\n## La Libération\nAprès les débarquements de 1944, Paris est libéré en août. Le **Gouvernement provisoire de la République française** rétablit la légalité républicaine, et les femmes obtiennent le **droit de vote** par l’ordonnance du **21 avril 1944**.', 1),
  ('e772cec2-f46a-5b63-9a05-75c56c7ac3c0', 'e0803bfa-c2f5-5ae6-bfdc-284d5e9dbbee', 'La fin des empires coloniaux', E'En 1945, l’Europe domine encore une grande partie de l’Afrique et de l’Asie. En 1975, presque tous ces territoires sont indépendants : c’est la **décolonisation**, l’un des grands bouleversements du siècle.\n\n## Pourquoi maintenant ?\n- Les puissances coloniales sortent **affaiblies** de la guerre.\n- Les colonies ont **participé** à la victoire et réclament une contrepartie.\n- Les mouvements **nationalistes** sont organisés autour de chefs formés en Europe.\n- Les **États-Unis** et l’**URSS**, pour des raisons opposées, sont hostiles aux empires.\n- La **Charte de l’ONU** consacre le **droit des peuples à disposer d’eux-mêmes**.\n\n## Deux voies\n- **Négociée** : l’**Inde** obtient son indépendance en **1947** (Gandhi, Nehru), au prix d’une partition sanglante avec le Pakistan. La plupart des colonies françaises d’Afrique noire accèdent pacifiquement à l’indépendance en **1960**, « l’année de l’Afrique ».\n- **Par la guerre** : l’**Indochine** (1946-1954) s’achève par la défaite française de **Diên Biên Phu** et les accords de Genève ; l’**Algérie** (**1954-1962**) est la plus longue et la plus douloureuse.\n\n## La guerre d’Algérie\nElle commence le **1er novembre 1954** (« Toussaint rouge ») à l’initiative du **FLN**. Elle mêle attentats, guérilla, torture, déplacements de populations. Elle provoque en France la chute de la IVe République (1958) et le retour de **de Gaulle**. Les **accords d’Évian** (18 mars 1962) et le référendum d’autodétermination conduisent à l’indépendance le 5 juillet 1962. Suivent l’exode de près d’un million de **pieds-noirs** et l’abandon de nombreux **harkis**.\n\n## Le tiers-monde\nRéunis à **Bandung** en **1955**, vingt-neuf pays d’Asie et d’Afrique affirment leur refus de choisir entre les deux blocs et condamnent le colonialisme. Le **mouvement des non-alignés** naît en 1961. Le mot « **tiers-monde** », forgé par Alfred Sauvy en 1952, désigne ces pays pauvres et nouvellement indépendants.\n\n> L’indépendance politique ne suffit pas : frontières héritées, économies dépendantes, instabilité politique pèsent longtemps sur les nouveaux États.', 1),
  ('c9a14604-caad-5620-9f44-e14e807dbdfc', 'ec58f7aa-3ac6-522b-a154-d39c11aff8b0', 'Deux blocs, une paix impossible et une guerre improbable', E'Alliés contre l’Allemagne jusqu’en 1945, les **États-Unis** et l’**URSS** deviennent adversaires dès 1947. La **guerre froide** est un affrontement global — idéologique, économique, militaire, culturel — entre deux superpuissances qui ne s’affrontent jamais directement.\n\n## La rupture de 1947\nLa **doctrine Truman** (mars 1947) promet d’aider tout pays menacé par le communisme : c’est l’**endiguement** (*containment*). Le **plan Marshall** apporte une aide économique massive à l’Europe de l’Ouest. En réponse, l’URSS crée le **Kominform** et la doctrine Jdanov, qui divise le monde en deux camps.\n\n> Churchill avait annoncé dès 1946 qu’un « **rideau de fer** » était tombé à travers l’Europe.\n\n## Berlin, symbole du monde coupé en deux\nLe **blocus de Berlin** (juin 1948 – mai 1949) répond à la réforme monétaire occidentale ; les Alliés ravitaillent la ville par un **pont aérien**. En 1949 naissent la **RFA** et la **RDA**, l’**OTAN** (1949) puis le **pacte de Varsovie** (1955). Le **mur de Berlin** est construit dans la nuit du **12 au 13 août 1961** pour arrêter l’hémorragie des départs vers l’Ouest.\n\n## Des guerres par procuration\nFaute de s’affronter directement, les blocs s’affrontent ailleurs : **guerre de Corée** (1950-1953), qui fige la péninsule au 38e parallèle ; guerres d’Indochine ; coups d’État et soutiens à des régimes amis en Amérique latine, en Afrique, au Moyen-Orient.\n\n## La crise de Cuba (octobre 1962)\nL’installation de missiles soviétiques à Cuba, à 150 km des côtes américaines, provoque la crise la plus dangereuse du siècle. Kennedy impose un blocus naval ; après treize jours, Khrouchtchev retire les missiles contre l’engagement américain de ne pas envahir Cuba et le retrait discret des missiles de Turquie. Un « téléphone rouge » est installé.\n\n## L’équilibre de la terreur\nLes deux camps possèdent l’arme nucléaire (URSS depuis 1949). La **dissuasion** rend la guerre directe suicidaire : c’est ce que Raymond Aron résume par « **paix impossible, guerre improbable** ».', 1),
  ('7bb91aaa-c500-5433-9fc5-ef7983701ee6', 'c715f435-ea13-5b1c-9d45-a1440d2aa8fb', 'De la détente à l’effondrement du bloc de l’Est', E'Après la peur d’octobre 1962, les deux blocs cherchent à encadrer leur rivalité — sans y renoncer. Trois temps se succèdent : la **détente**, la **guerre fraîche**, puis l’**effondrement**.\n\n## La détente (1963-1975)\nLes traités se multiplient : interdiction des essais atmosphériques (1963), traité de **non-prolifération** (1968), accords **SALT I** (1972), reconnaissance mutuelle des deux Allemagnes (*Ostpolitik* de Willy Brandt), acte final d’**Helsinki** (1975) sur les frontières et les droits de l’homme. La coexistence n’efface pas la répression à l’intérieur du bloc de l’Est : **Prague, 1968**, où les chars du pacte de Varsovie écrasent le « socialisme à visage humain ».\n\n## La guerre fraîche (1975-1985)\nLa **guerre du Vietnam** s’achève en 1975 par la défaite américaine. L’**invasion de l’Afghanistan** par l’URSS (1979), la crise des euromissiles et l’arrivée de **Reagan** relancent la tension et la course aux armements.\n\n## L’URSS à bout de souffle\nL’économie soviétique stagne : pénuries, retard technologique, coût de l’armement et de la guerre d’Afghanistan. En 1985, **Mikhaïl Gorbatchev** lance la **perestroïka** (restructuration économique) et la **glasnost** (transparence). La catastrophe de **Tchernobyl** (1986) frappe la confiance dans le régime.\n\n## 1989 : l’année charnière\nGorbatchev renonce à intervenir militairement chez les satellites. En quelques mois, la Pologne (Solidarność), la Hongrie, la Tchécoslovaquie (« révolution de velours ») et la RDA basculent. Le **mur de Berlin tombe le 9 novembre 1989** ; l’Allemagne est réunifiée le 3 octobre 1990.\n\n> La chute du Mur n’est pas une victoire militaire : c’est un régime qui cesse d’être cru par ses propres populations.\n\n## 1991 : la fin de l’URSS\nLe pacte de Varsovie est dissous en juillet 1991 ; après un putsch manqué en août, les républiques se déclarent indépendantes et l’**URSS disparaît le 25 décembre 1991**. Les États-Unis restent seule superpuissance : on parle alors d’un monde **unipolaire**.', 1),
  ('aa1f8f90-e5e6-5461-b0ef-c6cbfa4b7758', '4a141259-43ec-58de-ae70-e895bf65edab', 'De la CECA à l’Union européenne', E'Après deux guerres nées en Europe, des responsables politiques cherchent à rendre la guerre entre voisins **matériellement impossible**. C’est le point de départ de la construction européenne.\n\n## Les débuts (1951-1957)\nLa **déclaration Schuman** (9 mai 1950), inspirée par Jean Monnet, propose de mettre en commun le charbon et l’acier — les matières premières de l’armement. La **CECA** naît en 1951 avec six pays : France, RFA, Italie, Belgique, Pays-Bas, Luxembourg. Le **traité de Rome** (25 mars 1957) crée la **CEE**, un marché commun fondé sur la libre circulation des marchandises, des personnes, des services et des capitaux, et une politique agricole commune (**PAC**).\n\n## Les élargissements\nDe 6 membres en 1957, l’Europe passe à 9 (1973, dont le Royaume-Uni), 12 (Espagne et Portugal en 1986), 15 (1995), puis 25 en **2004** avec l’entrée des pays d’Europe centrale et orientale sortis du bloc soviétique, 27 en 2007 et 28 en 2013. Le **Royaume-Uni quitte l’Union en 2020** (Brexit) : l’Union compte 27 membres.\n\n## L’approfondissement\n- **Accords de Schengen** (1985, appliqués en 1995) : suppression des contrôles aux frontières intérieures.\n- **Traité de Maastricht** (1992) : l’Union européenne remplace la CEE, la **citoyenneté européenne** est créée, la monnaie unique est programmée.\n- L’**euro** devient monnaie de compte en 1999 et circule en pièces et billets le **1er janvier 2002**.\n- Le **traité de Lisbonne** (2007) réforme les institutions après l’échec du projet de Constitution rejeté par référendum en France et aux Pays-Bas en 2005.\n\n## Les institutions\nLe **Parlement européen** est élu au suffrage universel direct depuis **1979**. La **Commission** propose les textes et veille aux traités ; le **Conseil de l’Union** réunit les ministres ; le **Conseil européen** rassemble les chefs d’État et de gouvernement ; la **Cour de justice** tranche les litiges.\n\n> Deux logiques cohabitent : la **supranationale** (des décisions s’imposent aux États) et l’**intergouvernementale** (les États décident ensemble). Tout l’équilibre européen tient dans ce dosage.\n\n## Débats\nL’Union est critiquée pour son déficit démocratique, la lourdeur de ses décisions, les écarts économiques entre membres ; elle est défendue comme un espace de paix, de libre circulation, de normes protectrices et de poids commercial.', 1),
  ('81c610e1-e0d5-51b3-8009-52e5d40e1085', 'ffa4d950-59b4-5e27-acbe-c80fb3ae0682', 'Un monde multipolaire et ses conflits', E'Après 1991, on a cru à un monde simple, dominé par une seule puissance. Trente ans plus tard, le monde est **multipolaire** : plusieurs pôles, plusieurs modèles, et des conflits d’un type nouveau.\n\n## De l’unipolarité au multipolaire\nLes **États-Unis** restent la première puissance militaire, mais la **Chine** est devenue une puissance économique, technologique et navale de premier plan ; la **Russie** réaffirme ses ambitions par la force ; l’**Union européenne** pèse par son marché et ses normes ; l’**Inde**, le **Brésil** et d’autres puissances émergentes revendiquent leur place.\n\n## Le terrorisme international\nLes attentats du **11 septembre 2001** ouvrent une nouvelle séquence : interventions en Afghanistan (2001) et en Irak (2003), essor puis recul de **Daech**, attentats en Europe — dont la France en 2015 et 2016. Le terrorisme frappe des civils pour peser sur des sociétés entières.\n\n## Les grands foyers de tension\n- Le **Proche et Moyen-Orient** : conflit israélo-palestinien, guerre en Syrie, rivalités régionales.\n- L’**Europe orientale** : après l’annexion de la Crimée en 2014, la Russie envahit l’**Ukraine** en février 2022.\n- L’**Asie** : tensions autour de Taïwan et en mer de Chine méridionale.\n- L’**Afrique sahélienne** : États fragiles, groupes armés, coups d’État.\n\n## Les défis communs\nAucun État ne peut traiter seul le **changement climatique** (accord de Paris, 2015), les **migrations**, les **pandémies** (Covid-19), la **cybersécurité**, ni la régulation du numérique et de l’intelligence artificielle.\n\n> Les menaces sont devenues **transnationales** alors que les décisions restent **nationales** : c’est la principale difficulté de la gouvernance mondiale.\n\n## Une gouvernance contestée\nL’**ONU** reste le cadre du droit international, mais le **droit de veto** des cinq membres permanents du Conseil de sécurité bloque souvent l’action. D’autres enceintes (G7, G20, OMC, ONG) participent à la régulation, sans autorité contraignante. Le débat sur la réforme du Conseil de sécurité est ouvert depuis des décennies.', 1),
  ('6f0a4ce0-8176-5292-aaa8-55c393882603', 'd47a1340-11ae-5fcc-8d34-f0b41d7e2e36', 'La IVe République et l’État providence', E'À la Libération, il ne s’agit pas de rétablir l’ordre d’avant-guerre mais de **refonder** la République sur de nouvelles bases sociales et politiques. Le programme du **Conseil national de la Résistance**, adopté en mars 1944 sous le titre *Les Jours heureux*, en fixe la feuille de route.\n\n## Rétablir la légalité républicaine\nLe **Gouvernement provisoire de la République française** (GPRF), dirigé par de Gaulle, rétablit les libertés et organise l’**épuration** — légale par des cours de justice, parfois sauvage dans les premières semaines. Les Françaises obtiennent le **droit de vote** (ordonnance du 21 avril 1944) et votent pour la première fois en avril 1945.\n\n## Les grandes réformes sociales\n- Création de la **Sécurité sociale** (ordonnances d’octobre 1945) : maladie, accidents du travail, vieillesse, famille.\n- **Nationalisations** : Renault, charbonnages, Banque de France, EDF-GDF, Air France.\n- **Comités d’entreprise**, statut de la fonction publique.\n- Renforcement de l’école publique et de la recherche.\n\n> L’idée directrice : protéger chacun contre les risques de l’existence, par la solidarité nationale plutôt que par la charité.\n\n## La IVe République\nLa Constitution est adoptée par référendum en **octobre 1946**, après un premier projet rejeté. Elle donne l’essentiel du pouvoir à l’**Assemblée nationale** : le gouvernement dépend d’une majorité fragile. De Gaulle, hostile à ce régime, a démissionné dès **janvier 1946**.\n\n## Réussites et faiblesses\nLa IVe République reconstruit le pays, engage la construction européenne et la modernisation économique. Mais l’**instabilité ministérielle** est chronique — plus de vingt gouvernements en douze ans — et les guerres coloniales, en Indochine puis en Algérie, finissent par emporter le régime en **1958**.\n\n## Un héritage vivant\nLa Sécurité sociale, les nationalisations, le préambule de 1946 (droit au travail, à la santé, à l’instruction, égalité femmes-hommes) constituent le socle du modèle social français, encore discuté aujourd’hui.', 1),
  ('ceaf2712-7638-57fd-ac05-be6654eeace4', 'a6a17bba-64cd-5ff0-b38c-324ae198fc0d', 'Une République nouvelle et un pouvoir présidentiel', E'La crise du **13 mai 1958** en Algérie ramène **de Gaulle** au pouvoir. Il obtient les pleins pouvoirs pour rédiger une nouvelle Constitution, approuvée par référendum le **28 septembre 1958** : c’est la **Ve République**.\n\n## Une Constitution qui renverse l’équilibre\nLe **président de la République** devient la clé de voûte des institutions : il nomme le Premier ministre, peut dissoudre l’Assemblée nationale, soumettre un texte au **référendum** (article 11) et disposer de pouvoirs exceptionnels (article 16). Le Parlement voit son domaine de compétence délimité. En **1962**, un référendum instaure l’**élection du président au suffrage universel direct**, appliquée dès 1965.\n\n> Le référendum devient l’instrument privilégié du général : il pose sa propre légitimité en jeu à chaque consultation.\n\n## Régler la question algérienne\nDe Gaulle passe de l’ambiguïté à l’autodétermination, affronte le putsch des généraux (avril 1961) et les attentats de l’**OAS**, puis conclut les **accords d’Évian** (mars 1962). L’indépendance de l’Algérie est proclamée le 5 juillet 1962.\n\n## L’indépendance nationale\nLa France se dote de l’**arme nucléaire** (premier essai en 1960), quitte le commandement intégré de l’**OTAN** (1966), reconnaît la Chine populaire (1964), critique la guerre du Vietnam (discours de Phnom Penh, 1966) et se rapproche de l’Allemagne (**traité de l’Élysée**, 1963).\n\n## Mai 1968\nParti des universités, le mouvement s’étend aux lycées puis à une **grève générale** de plusieurs millions de salariés. Les **accords de Grenelle** accordent une forte hausse du SMIG et des droits syndicaux. Au-delà des salaires, la contestation vise l’autorité, la famille, l’école, la place des femmes : la société française change plus vite que ses institutions.\n\n## Le départ\nDe Gaulle dissout l’Assemblée et remporte les législatives de juin 1968, mais perd le **référendum d’avril 1969** sur la régionalisation et la réforme du Sénat. Fidèle à sa pratique, il démissionne le lendemain. Georges Pompidou lui succède.', 1),
  ('80a35dc0-76ff-587a-b1e5-a7647662920d', '23f482c1-6c94-510f-9a71-dc22f6c9ebea', '1945-1975 : trente ans qui transforment la société', E'L’expression **Trente Glorieuses**, forgée par Jean Fourastié, désigne les trois décennies de forte croissance qui suivent la Seconde Guerre mondiale, entre **1945 et 1973-1975**. La France y change plus vite qu’en un siècle.\n\n## Une croissance exceptionnelle\nLa croissance dépasse **5 % par an** en moyenne. Elle repose sur la reconstruction, le plan Marshall, la modernisation industrielle, la planification, l’ouverture du marché commun, une main-d’œuvre nombreuse (**baby-boom** et immigration) et un pétrole bon marché.\n\n## La société de consommation\nLe pouvoir d’achat double. Les ménages s’équipent : réfrigérateur, machine à laver, télévision, automobile. Les **grandes surfaces** apparaissent, la publicité s’installe, le crédit se répand, les **congés payés** deviennent départs en vacances. Un nouveau mode de vie se diffuse à toute la société.\n\n## L’exode rural et l’urbanisation\nLa population agricole s’effondre ; les villes s’étendent. Les **grands ensembles**, construits vite pour loger les rapatriés, les migrants et les familles mal logées, apportent d’abord le confort moderne (eau chaude, chauffage, salle de bains) avant de poser, plus tard, des problèmes d’enclavement.\n\n## Le travail et les femmes\nLe salariat devient la norme, le **secteur tertiaire** dépasse l’industrie. Le **travail des femmes** progresse fortement, accompagné de conquêtes juridiques : capacité d’ouvrir un compte bancaire sans l’accord du mari (1965), autorisation de la contraception (**loi Neuwirth**, 1967), dépénalisation de l’IVG (**loi Veil**, 1975).\n\n> La croissance ne fait pas que produire des biens : elle déplace les gens, change les familles et redessine les paysages.\n\n## La fin d’un cycle\nLe **choc pétrolier de 1973** met fin à cette période : ralentissement, inflation, montée du **chômage** de masse. Les Trente Glorieuses laissent un héritage considérable — équipement du pays, protection sociale, élévation du niveau de vie — mais aussi une facture environnementale et des inégalités territoriales durables.', 1),
  ('4c4d40c0-27c3-553b-9eb5-9b32f402dece', '4b5a2da3-153c-58c8-a59b-04f04d792b1c', 'Alternances, cohabitations et réformes', E'Conçue pour un homme et une crise, la Ve République a duré : elle a résisté au départ de son fondateur, à l’alternance politique et à la cohabitation. Sa **plasticité** est sa principale caractéristique.\n\n## Les présidences successives\n- **Georges Pompidou** (1969-1974) : modernisation industrielle et urbaine.\n- **Valéry Giscard d’Estaing** (1974-1981) : majorité à **18 ans**, loi Veil (1975), divorce par consentement mutuel, réforme du collège unique — mais aussi le premier choc du chômage.\n- **François Mitterrand** (1981-1995) : première **alternance** de gauche, abolition de la **peine de mort** (1981), retraite à 60 ans, cinquième semaine de congés payés, décentralisation, lois Auroux ; puis le tournant de la rigueur (1983).\n- **Jacques Chirac** (1995-2007) : fin du service militaire, passage au **quinquennat** (2000), loi sur la laïcité à l’école (2004).\n- **Nicolas Sarkozy** (2007-2012) : réforme constitutionnelle de 2008, crise financière de 2008.\n\n## L’alternance et la cohabitation\nL’**alternance** de 1981 prouve que la Constitution fonctionne quel que soit le camp au pouvoir. Trois **cohabitations** (1986-1988, 1993-1995, 1997-2002) mettent face à face un président et un Premier ministre d’orientations opposées : le président conserve la défense et les affaires étrangères, le gouvernement conduit la politique intérieure.\n\n> Le **quinquennat** (2000) et l’inversion du calendrier électoral visent précisément à rendre la cohabitation improbable.\n\n## La décentralisation\nLes lois **Defferre** (1982) transfèrent des compétences aux communes, départements et régions, qui deviennent des collectivités de plein exercice. La révision de 2003 inscrit dans la Constitution que la République est **décentralisée**.\n\n## Une société qui se transforme\nLe droit suit les évolutions sociales : parité (1999-2000), PACS (1999), lutte contre les discriminations, place croissante du **Conseil constitutionnel** — saisine élargie en 1974, **question prioritaire de constitutionnalité** en 2008 — et poids grandissant du droit européen.\n\n## Les débats permanents\nPuissance du président, place du Parlement, abstention croissante, montée des extrêmes, rôle des corps intermédiaires : la Ve République vit depuis soixante ans avec le même débat sur l’équilibre entre efficacité et représentation.', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('b3981abc-163f-5e7f-8425-d9518be21920'::uuid, 'Quiz — 1914-1918 : quand la guerre engloutit les sociétés', 'Histoire-Géographie', '3e', 'La Première Guerre mondiale : vers une guerre totale', '9bed4dd1-f2c0-5b81-9e62-b30b541d85af'::uuid),
    ('77414f0a-4461-5d91-8b41-9ce4b92eece8'::uuid, 'Quiz — URSS, Italie, Allemagne : l’État contre l’individu', 'Histoire-Géographie', '3e', 'Les régimes totalitaires dans les années 1930', 'b3b5edd6-d735-51cb-a099-3191ae091989'::uuid),
    ('b7309ee0-716b-51d1-af0c-bd07dda9784e'::uuid, 'Quiz — Une République ébranlée, du deuil au Front populaire', 'Histoire-Géographie', '3e', 'La France durant l’entre-deux-guerres', '4cd2f9a3-4a09-5826-86e2-24b0258e5ab9'::uuid),
    ('7e5af191-641a-5dc1-a550-a9caa519c68d'::uuid, 'Quiz — 1939-1945 : une guerre qui vise des peuples', 'Histoire-Géographie', '3e', 'La Seconde Guerre mondiale : une guerre d’anéantissement', '7c6ae354-926e-55fe-8308-3eabc3e60311'::uuid),
    ('af15f7e7-6ff7-5b6d-af6e-f6da26443cb5'::uuid, 'Quiz — Défaite, collaboration, Résistance', 'Histoire-Géographie', '3e', 'La France de Vichy (1940-1944)', 'a1b6ad62-1710-53f0-bc15-c547c4251b22'::uuid),
    ('99b1276b-e36a-5e0a-a56d-f8121b55d7fc'::uuid, 'Quiz — La fin des empires coloniaux', 'Histoire-Géographie', '3e', 'La décolonisation', 'e772cec2-f46a-5b63-9a05-75c56c7ac3c0'::uuid),
    ('23bd4a29-12d7-5628-b216-73e17cd7e641'::uuid, 'Quiz — Deux blocs, une paix impossible et une guerre improbable', 'Histoire-Géographie', '3e', 'Le monde durant la guerre froide (1947-1962)', 'c9a14604-caad-5620-9f44-e14e807dbdfc'::uuid),
    ('1cc48ce7-adf6-5136-9261-a437d4fc9ce3'::uuid, 'Quiz — De la détente à l’effondrement du bloc de l’Est', 'Histoire-Géographie', '3e', 'Le monde durant la guerre froide (1963-1991)', '7bb91aaa-c500-5433-9fc5-ef7983701ee6'::uuid),
    ('cd7f0e9d-ecd7-5c3a-b751-2f9a96bb71f8'::uuid, 'Quiz — De la CECA à l’Union européenne', 'Histoire-Géographie', '3e', 'La construction européenne', 'aa1f8f90-e5e6-5461-b0ef-c6cbfa4b7758'::uuid),
    ('f66d54db-e6ce-5791-a489-c7d06a463700'::uuid, 'Quiz — Un monde multipolaire et ses conflits', 'Histoire-Géographie', '3e', 'La géopolitique du monde actuel', '81c610e1-e0d5-51b3-8009-52e5d40e1085'::uuid),
    ('4e4f149a-ca7b-59a2-a569-e10cdd43f499'::uuid, 'Quiz — La IVe République et l’État providence', 'Histoire-Géographie', '3e', '1944-1947 : refonder la République, redéfinir la démocratie', '6f0a4ce0-8176-5292-aaa8-55c393882603'::uuid),
    ('39c0a7b7-54df-592d-8d1d-e31bf19a9c6b'::uuid, 'Quiz — Une République nouvelle et un pouvoir présidentiel', 'Histoire-Géographie', '3e', 'Les années de Gaulle (1958-1969)', 'ceaf2712-7638-57fd-ac05-be6654eeace4'::uuid),
    ('365d5bdb-1c9d-55ab-90b6-457b1eaf6a52'::uuid, 'Quiz — 1945-1975 : trente ans qui transforment la société', 'Histoire-Géographie', '3e', 'Les Trente Glorieuses', '80a35dc0-76ff-587a-b1e5-a7647662920d'::uuid),
    ('47f6cabf-1f1f-55af-b99b-47f18eec5ff8'::uuid, 'Quiz — Alternances, cohabitations et réformes', 'Histoire-Géographie', '3e', 'La Ve République à l’épreuve de la durée (1958-2012)', '4c4d40c0-27c3-553b-9eb5-9b32f402dece'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('38c2bff3-be6b-5753-bb9a-0a8762ca1c36'::uuid, 'b3981abc-163f-5e7f-8425-d9518be21920'::uuid, 'Quelles dates encadrent la Première Guerre mondiale ?', 'mcq', '["28 juillet 1914 – 11 novembre 1918","1er septembre 1914 – 8 mai 1918","3 août 1914 – 28 juin 1919","28 juin 1914 – 11 novembre 1919"]'::jsonb, 0, 'L’armistice du 11 novembre 1918 précède le traité de Versailles de 1919.', 1),
    ('60b4a11a-74d7-56a1-9aef-9d7199815516'::uuid, 'b3981abc-163f-5e7f-8425-d9518be21920'::uuid, 'Quelle bataille de 1916 est devenue le symbole de l’enfer des tranchées françaises ?', 'mcq', '["Verdun","La Marne","Stalingrad","Waterloo"]'::jsonb, 0, 'Elle dure de février à décembre 1916.', 2),
    ('2fd4ea20-6784-52d2-bf9a-7f60d0d2f34b'::uuid, 'b3981abc-163f-5e7f-8425-d9518be21920'::uuid, 'Qu’est-ce qu’une guerre totale ?', 'mcq', '["Une guerre qui mobilise toutes les ressources d’un pays","Une guerre menée sur tous les continents","Une guerre sans prisonniers","Une guerre qui dure plus de quatre ans"]'::jsonb, 0, 'Militaires, économiques, scientifiques et morales.', 3),
    ('22016fec-f2ee-5563-8b9a-7be787e67bcf'::uuid, 'b3981abc-163f-5e7f-8425-d9518be21920'::uuid, 'Quel pays entre en guerre en avril 1917 aux côtés de l’Entente ?', 'mcq', '["Les États-Unis","L’Italie","Le Japon","L’Espagne"]'::jsonb, 0, 'Leur entrée compense la sortie de la Russie.', 4),
    ('37175198-eecd-59e3-aa69-e9be1f41b754'::uuid, 'b3981abc-163f-5e7f-8425-d9518be21920'::uuid, 'Pourquoi la Russie quitte-t-elle le conflit en 1917-1918 ?', 'mcq', '["À cause de la révolution bolchevique","Parce qu’elle a été envahie entièrement","Parce qu’elle change d’alliance en 1915","Parce qu’elle a épuisé ses réserves de charbon"]'::jsonb, 0, 'Le traité de Brest-Litovsk est signé en mars 1918.', 5),
    ('64146b04-fe97-5e5f-821f-f5ab93a7e9ee'::uuid, 'b3981abc-163f-5e7f-8425-d9518be21920'::uuid, 'Quel génocide est perpétré en 1915-1916 par le gouvernement jeune-turc ?', 'mcq', '["Le génocide des Arméniens","Le génocide des Tutsi","La Shoah","Le massacre de Katyn"]'::jsonb, 0, 'Environ 1,2 million de morts : le premier génocide du siècle.', 6),
    ('066aa3ba-66c0-5f15-a0c2-c2602b0d47c9'::uuid, 'b3981abc-163f-5e7f-8425-d9518be21920'::uuid, 'Quel traité met fin à la guerre avec l’Allemagne en 1919 ?', 'mcq', '["Le traité de Versailles","Le traité de Brest-Litovsk","Le traité de Rome","Le pacte Briand-Kellogg"]'::jsonb, 0, 'Signé le 28 juin 1919, l’Allemagne le juge comme un diktat.', 7),
    ('e647c4b6-953f-55cd-96c0-7a1bff1731bb'::uuid, 'b3981abc-163f-5e7f-8425-d9518be21920'::uuid, 'La Société des Nations est créée après 1918 avec la participation des États-Unis.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Le Sénat américain refuse d’y adhérer, ce qui affaiblit l’organisation.', 8),
    ('c6c8ecd5-6a73-5c89-bcde-431447d87f2d'::uuid, '77414f0a-4461-5d91-8b41-9ce4b92eece8'::uuid, 'Qu’est-ce qui caractérise un régime totalitaire ?', 'mcq', '["Il veut contrôler la société entière et transformer l’homme","Il limite son action à l’économie","Il organise des élections libres","Il respecte l’indépendance de la justice"]'::jsonb, 0, 'Travail, loisirs, famille et pensée sont encadrés.', 1),
    ('a24397b9-a61f-521d-8b4e-0e1ef47c8b5a'::uuid, '77414f0a-4461-5d91-8b41-9ce4b92eece8'::uuid, 'Quelle famine frappe l’Ukraine en 1932-1933 ?', 'mcq', '["L’Holodomor","La Grande Famine irlandaise","La famine du Bengale","La famine de la Volga de 1891"]'::jsonb, 0, 'Elle résulte de la collectivisation forcée des terres.', 2),
    ('1f32a8ab-ada0-5cf4-9a1e-b2b516f21846'::uuid, '77414f0a-4461-5d91-8b41-9ce4b92eece8'::uuid, 'Comment s’appelle le système de camps soviétique ?', 'mcq', '["Le Goulag","Le Kolkhoze","Le Komintern","Le Politburo"]'::jsonb, 0, 'Les Grandes Purges de 1936-1938 y envoient des millions de personnes.', 3),
    ('c5360baa-7a18-5c89-b499-082d4fe74540'::uuid, '77414f0a-4461-5d91-8b41-9ce4b92eece8'::uuid, 'En quelle année Mussolini arrive-t-il au pouvoir en Italie ?', 'mcq', '["1922","1917","1933","1936"]'::jsonb, 0, 'La marche sur Rome lui ouvre la présidence du Conseil.', 4),
    ('3943c8ff-4c1d-5e32-9908-2f9206a49a62'::uuid, '77414f0a-4461-5d91-8b41-9ce4b92eece8'::uuid, 'Quand Hitler devient-il chancelier d’Allemagne ?', 'mcq', '["Le 30 janvier 1933","Le 1er septembre 1939","Le 9 novembre 1918","Le 30 avril 1945"]'::jsonb, 0, 'Il obtient les pleins pouvoirs dans les semaines qui suivent.', 5),
    ('9306990c-c7b7-5cdb-8c52-802885123738'::uuid, '77414f0a-4461-5d91-8b41-9ce4b92eece8'::uuid, 'Que font les lois de Nuremberg de 1935 ?', 'mcq', '["Elles privent les Juifs de la citoyenneté allemande","Elles instaurent le suffrage universel","Elles interdisent le réarmement","Elles créent la Société des Nations"]'::jsonb, 0, 'L’antisémitisme devient une législation d’État.', 6),
    ('1f037f16-1164-58e0-93a4-40bfdd5cf66f'::uuid, '77414f0a-4461-5d91-8b41-9ce4b92eece8'::uuid, 'Qu’est-ce que la Nuit de Cristal de novembre 1938 ?', 'mcq', '["Un pogrom organisé contre les Juifs d’Allemagne","Une manifestation ouvrière à Berlin","Un défilé de la jeunesse hitlérienne","Une conférence internationale sur la paix"]'::jsonb, 0, 'Synagogues incendiées, commerces saccagés, arrestations massives.', 7),
    ('e622e2a8-aeaf-594f-b8bb-a94eb024928a'::uuid, '77414f0a-4461-5d91-8b41-9ce4b92eece8'::uuid, 'Le nazisme et le stalinisme poursuivent exactement les mêmes buts.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Les moyens se ressemblent, mais l’un se fonde sur la race, l’autre sur la classe.', 8),
    ('0d649ca7-6bd2-59b7-a6a1-982bf20882d6'::uuid, 'b7309ee0-716b-51d1-af0c-bd07dda9784e'::uuid, 'Combien de morts la Première Guerre mondiale coûte-t-elle à la France ?', 'mcq', '["Environ 1,4 million","Environ 400 000","Environ 3 millions","Environ 700 000"]'::jsonb, 0, 'Chaque commune élève un monument aux morts.', 1),
    ('2bf2a7ee-7e90-598e-8625-41eff35aab62'::uuid, 'b7309ee0-716b-51d1-af0c-bd07dda9784e'::uuid, 'Quand la crise économique mondiale atteint-elle la France ?', 'mcq', '["En 1931-1932","Dès octobre 1929","En 1936","En 1925"]'::jsonb, 0, 'Elle y arrive avec deux ans de décalage sur les États-Unis.', 2),
    ('3e3256a7-92ff-599c-9d78-94380a9eaa78'::uuid, 'b7309ee0-716b-51d1-af0c-bd07dda9784e'::uuid, 'Que se passe-t-il le 6 février 1934 à Paris ?', 'mcq', '["Des ligues d’extrême droite manifestent devant la Chambre des députés","Le Front populaire remporte les élections","Léon Blum est nommé président du Conseil","La France signe les accords de Locarno"]'::jsonb, 0, 'L’affrontement fait une quinzaine de morts.', 3),
    ('da033173-d5e6-565e-8a67-ffdf69fc3045'::uuid, 'b7309ee0-716b-51d1-af0c-bd07dda9784e'::uuid, 'Quelles forces composent le Front populaire ?', 'mcq', '["Socialistes, radicaux et communistes","Radicaux et ligues nationalistes","Communistes et Croix-de-Feu","Socialistes et monarchistes"]'::jsonb, 0, 'L’union naît de la peur du fascisme après février 1934.', 4),
    ('657ca6ce-c76d-5d6d-87f6-d0a8397c5750'::uuid, 'b7309ee0-716b-51d1-af0c-bd07dda9784e'::uuid, 'Qui dirige le gouvernement du Front populaire en 1936 ?', 'mcq', '["Léon Blum","Édouard Daladier","Maurice Thorez","Raymond Poincaré"]'::jsonb, 0, 'Il est le premier socialiste président du Conseil.', 5),
    ('e868edc2-c968-52b3-a7d7-b121caa3d5f6'::uuid, 'b7309ee0-716b-51d1-af0c-bd07dda9784e'::uuid, 'Quelle durée hebdomadaire de travail les accords de 1936 instaurent-ils ?', 'mcq', '["40 heures","35 heures","48 heures","44 heures"]'::jsonb, 0, 'Elle accompagne les congés payés et les conventions collectives.', 6),
    ('1b9bf6d9-8fcb-5a1a-b4b4-7c5422952627'::uuid, 'b7309ee0-716b-51d1-af0c-bd07dda9784e'::uuid, 'Combien de semaines de congés payés le Front populaire accorde-t-il ?', 'mcq', '["Deux semaines","Une semaine","Quatre semaines","Cinq semaines"]'::jsonb, 0, 'C’est la mesure la plus emblématique de 1936.', 7),
    ('a4c56d97-4ca7-507a-852c-1f4d71ad5c2b'::uuid, 'b7309ee0-716b-51d1-af0c-bd07dda9784e'::uuid, 'Les accords Matignon prévoient une hausse générale des salaires.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Environ 12 %, en plus des conventions collectives.', 8),
    ('f49ae79c-3b61-54f4-9e73-e402de49dea3'::uuid, '7e5af191-641a-5dc1-a550-a9caa519c68d'::uuid, 'Quelle date marque le début de la Seconde Guerre mondiale en Europe ?', 'mcq', '["Le 1er septembre 1939","Le 3 septembre 1939","Le 10 mai 1940","Le 22 juin 1941"]'::jsonb, 0, 'L’Allemagne envahit la Pologne ; France et Royaume-Uni déclarent la guerre deux jours plus tard.', 1),
    ('1a4a8d7f-279b-57ae-ab80-ee64a9c6431c'::uuid, '7e5af191-641a-5dc1-a550-a9caa519c68d'::uuid, 'Quel événement fait entrer les États-Unis dans le conflit ?', 'mcq', '["L’attaque de Pearl Harbor","La bataille de Stalingrad","Le débarquement de Normandie","L’invasion de la Pologne"]'::jsonb, 0, 'Le 7 décembre 1941, la flotte américaine du Pacifique est attaquée.', 2),
    ('bd8a4a8a-c7b9-5b22-a53a-e8793cec4e08'::uuid, '7e5af191-641a-5dc1-a550-a9caa519c68d'::uuid, 'Quelle bataille marque le tournant du front de l’Est ?', 'mcq', '["Stalingrad","Verdun","La Marne","Dunkerque"]'::jsonb, 0, 'La VIe armée allemande y capitule en février 1943.', 3),
    ('114a3ca1-e638-5ed7-968a-c90f9ad645f4'::uuid, '7e5af191-641a-5dc1-a550-a9caa519c68d'::uuid, 'Quelle date correspond au débarquement de Normandie ?', 'mcq', '["6 juin 1944","8 mai 1945","15 août 1944","11 novembre 1943"]'::jsonb, 0, 'L’opération Overlord ouvre un second front à l’Ouest.', 4),
    ('cf2f125e-c04a-5f8e-8e32-b5b6d716c482'::uuid, '7e5af191-641a-5dc1-a550-a9caa519c68d'::uuid, 'Que décide la conférence de Wannsee en janvier 1942 ?', 'mcq', '["L’organisation de la déportation vers les camps d’extermination","La création de la Société des Nations","La capitulation de l’Italie","Le partage de l’Allemagne en zones"]'::jsonb, 0, 'Elle planifie administrativement la « solution finale ».', 5),
    ('472a655c-3b88-5989-b755-1422e1da4926'::uuid, '7e5af191-641a-5dc1-a550-a9caa519c68d'::uuid, 'Quelle différence entre camp de concentration et camp d’extermination ?', 'mcq', '["Le premier enferme et fait travailler, le second est conçu pour tuer dès l’arrivée","Le premier est en Allemagne, le second en Pologne","Le premier est militaire, le second civil","Il n’y a aucune différence"]'::jsonb, 0, 'La distinction est essentielle pour comprendre la Shoah.', 6),
    ('f7e04354-a0d4-5c45-aa5c-1096e31d5adb'::uuid, '7e5af191-641a-5dc1-a550-a9caa519c68d'::uuid, 'Quel bilan humain la Seconde Guerre mondiale laisse-t-elle ?', 'mcq', '["Entre 50 et 60 millions de morts, en majorité des civils","Environ 10 millions de morts, en majorité des soldats","Environ 20 millions de morts, uniquement militaires","Moins de 5 millions de morts"]'::jsonb, 0, 'C’est l’inverse du rapport de 1914-1918.', 7),
    ('47e89aab-cef7-5e77-b114-6c8225e88935'::uuid, '7e5af191-641a-5dc1-a550-a9caa519c68d'::uuid, 'Le procès de Nuremberg invente la notion de crime contre l’humanité.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Elle entre à cette occasion dans le droit international.', 8),
    ('5d2f1757-5cff-5098-bf40-53ed5cec90ca'::uuid, 'af15f7e7-6ff7-5b6d-af6e-f6da26443cb5'::uuid, 'Quelle devise remplace « Liberté, Égalité, Fraternité » sous Vichy ?', 'mcq', '["Travail, Famille, Patrie","Ordre, Force, Nation","Terre, Peuple, Chef","Honneur, Patrie, Discipline"]'::jsonb, 0, 'Elle résume le programme de la Révolution nationale.', 1),
    ('d0ffffc4-8e74-58b1-a67f-880270aa8db5'::uuid, 'af15f7e7-6ff7-5b6d-af6e-f6da26443cb5'::uuid, 'Quand l’Assemblée nationale accorde-t-elle les pleins pouvoirs à Pétain ?', 'mcq', '["Le 10 juillet 1940","Le 18 juin 1940","Le 22 juin 1940","Le 3 octobre 1940"]'::jsonb, 0, 'L’État français succède alors à la IIIe République.', 2),
    ('9d50e4ec-40c5-5520-ad2d-b19a69787ee4'::uuid, 'af15f7e7-6ff7-5b6d-af6e-f6da26443cb5'::uuid, 'Qu’instaure le statut des Juifs du 3 octobre 1940 ?', 'mcq', '["Leur exclusion de la fonction publique, de l’enseignement et de la presse","Leur obligation de porter l’étoile jaune","Leur déportation immédiate","La confiscation de tous leurs biens"]'::jsonb, 0, 'Vichy le promulgue sans qu’aucune autorité allemande ne l’ait exigé.', 3),
    ('c32b12db-b74f-58dd-93db-69b14bf71fce'::uuid, 'af15f7e7-6ff7-5b6d-af6e-f6da26443cb5'::uuid, 'Qui mène la rafle du Vél’ d’Hiv’ des 16-17 juillet 1942 ?', 'mcq', '["La police française","La Wehrmacht","La Gestapo seule","La Milice"]'::jsonb, 0, 'Plus de 13 000 personnes sont arrêtées, dont plus de 4 000 enfants.', 4),
    ('0abc6eff-7c82-5ec5-9f87-39f00e5eb12f'::uuid, 'af15f7e7-6ff7-5b6d-af6e-f6da26443cb5'::uuid, 'Que met en place le STO en 1943 ?', 'mcq', '["L’envoi obligatoire de travailleurs français en Allemagne","Un service militaire dans l’armée de Vichy","Un impôt exceptionnel sur les entreprises","Un contrôle des prix agricoles"]'::jsonb, 0, 'Il pousse de nombreux jeunes à rejoindre les maquis.', 5),
    ('35017cf3-48fe-5c2f-8702-a3a0bdd2c87b'::uuid, 'af15f7e7-6ff7-5b6d-af6e-f6da26443cb5'::uuid, 'Quel appel de Gaulle lance-t-il depuis Londres le 18 juin 1940 ?', 'mcq', '["L’appel à poursuivre le combat","L’appel à signer l’armistice","L’appel au rationnement","L’appel à l’insurrection de Paris"]'::jsonb, 0, 'C’est l’acte de naissance de la France libre.', 6),
    ('5903437e-51aa-5165-a15f-5a6edc39e6db'::uuid, 'af15f7e7-6ff7-5b6d-af6e-f6da26443cb5'::uuid, 'Quel rôle joue Jean Moulin dans la Résistance ?', 'mcq', '["Il unifie les mouvements au sein du Conseil national de la Résistance","Il commande les Forces françaises libres","Il dirige le gouvernement de Vichy","Il négocie l’armistice de 1940"]'::jsonb, 0, 'Le CNR se réunit pour la première fois le 27 mai 1943.', 7),
    ('5f794743-097a-5c1f-b9d2-a97cb76ccf18'::uuid, 'af15f7e7-6ff7-5b6d-af6e-f6da26443cb5'::uuid, 'Les Françaises obtiennent le droit de vote par l’ordonnance du 21 avril 1944.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Elles votent pour la première fois aux municipales d’avril 1945.', 8),
    ('47939cf1-0841-5be4-a74f-449d06f28206'::uuid, '99b1276b-e36a-5e0a-a56d-f8121b55d7fc'::uuid, 'Quel principe de la Charte de l’ONU sert d’appui aux mouvements de décolonisation ?', 'mcq', '["Le droit des peuples à disposer d’eux-mêmes","La liberté de circulation","La souveraineté des empires","L’égalité devant l’impôt"]'::jsonb, 0, 'Il est inscrit dans la Charte signée en 1945.', 1),
    ('575ee7ff-fb34-5c4f-8c5e-6b438582e62e'::uuid, '99b1276b-e36a-5e0a-a56d-f8121b55d7fc'::uuid, 'En quelle année l’Inde devient-elle indépendante ?', 'mcq', '["1947","1945","1954","1960"]'::jsonb, 0, 'La partition avec le Pakistan s’accompagne de violences massives.', 2),
    ('a054417f-be26-5abc-8e1e-ee27310a8818'::uuid, '99b1276b-e36a-5e0a-a56d-f8121b55d7fc'::uuid, 'Quelle défaite met fin à la guerre d’Indochine en 1954 ?', 'mcq', '["Diên Biên Phu","Sedan","Dunkerque","Alger"]'::jsonb, 0, 'Elle conduit aux accords de Genève.', 3),
    ('86e25fd3-67f3-5b15-8e4d-355ae3b83e5f'::uuid, '99b1276b-e36a-5e0a-a56d-f8121b55d7fc'::uuid, 'Quelles dates encadrent la guerre d’Algérie ?', 'mcq', '["1954-1962","1945-1954","1956-1968","1958-1962"]'::jsonb, 0, 'Elle commence le 1er novembre 1954, la Toussaint rouge.', 4),
    ('b0c0479e-db71-5ef2-ad21-1de6d32c4a42'::uuid, '99b1276b-e36a-5e0a-a56d-f8121b55d7fc'::uuid, 'Quel accord conduit à l’indépendance de l’Algérie ?', 'mcq', '["Les accords d’Évian","Les accords de Genève","Les accords de Matignon","Les accords de Yalta"]'::jsonb, 0, 'Signés le 18 mars 1962, ils sont suivis d’un référendum.', 5),
    ('95fc09b0-344e-5c45-8d9a-6e82cc5522d8'::uuid, '99b1276b-e36a-5e0a-a56d-f8121b55d7fc'::uuid, 'Pourquoi 1960 est-elle appelée « l’année de l’Afrique » ?', 'mcq', '["Dix-sept pays africains accèdent à l’indépendance cette année-là","La conférence de Bandung s’y tient","L’ONU y est créée","La guerre d’Algérie s’y termine"]'::jsonb, 0, 'La plupart des colonies françaises d’Afrique noire deviennent indépendantes.', 6),
    ('f3cd277c-b3d5-59c7-9902-abdb53f8cd8c'::uuid, '99b1276b-e36a-5e0a-a56d-f8121b55d7fc'::uuid, 'Que proclame la conférence de Bandung en 1955 ?', 'mcq', '["Le refus de choisir entre les deux blocs et la condamnation du colonialisme","La création du Pacte de Varsovie","La fin de la guerre de Corée","La création de la CEE"]'::jsonb, 0, 'Vingt-neuf pays d’Asie et d’Afrique y participent.', 7),
    ('d15768ee-c1c1-507e-940b-2f7ec93b39e8'::uuid, '99b1276b-e36a-5e0a-a56d-f8121b55d7fc'::uuid, 'L’indépendance politique a suffi à régler les difficultés économiques des nouveaux États.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Frontières héritées, dépendance économique et instabilité ont longtemps pesé.', 8),
    ('b8c086d7-23d2-551d-bc09-203af5c43a2a'::uuid, '23bd4a29-12d7-5628-b216-73e17cd7e641'::uuid, 'Qu’annonce la doctrine Truman en mars 1947 ?', 'mcq', '["L’aide américaine à tout pays menacé par le communisme","Le retrait des troupes américaines d’Europe","La création de l’ONU","Le désarmement nucléaire"]'::jsonb, 0, 'C’est la politique dite d’endiguement.', 1),
    ('49afb078-0148-55ed-ae7d-17cff9263f0b'::uuid, '23bd4a29-12d7-5628-b216-73e17cd7e641'::uuid, 'Quel plan apporte une aide économique massive à l’Europe de l’Ouest ?', 'mcq', '["Le plan Marshall","Le plan Schuman","Le plan Dawes","Le plan Monnet"]'::jsonb, 0, 'L’URSS le refuse et l’interdit à ses satellites.', 2),
    ('189593ee-c44b-5009-ba41-08eb5cc67dc0'::uuid, '23bd4a29-12d7-5628-b216-73e17cd7e641'::uuid, 'Comment les Alliés répondent-ils au blocus de Berlin en 1948-1949 ?', 'mcq', '["Par un pont aérien","Par une offensive terrestre","Par un embargo sur l’URSS","En abandonnant la ville"]'::jsonb, 0, 'Berlin-Ouest est ravitaillée par avion pendant onze mois.', 3),
    ('471dac77-caa7-5f20-9bf7-9828e45054c8'::uuid, '23bd4a29-12d7-5628-b216-73e17cd7e641'::uuid, 'Quelles alliances militaires s’opposent pendant la guerre froide ?', 'mcq', '["L’OTAN et le pacte de Varsovie","La SDN et le Kominform","La CEE et le CAEM","L’ONU et l’OTAN"]'::jsonb, 0, 'L’OTAN date de 1949, le pacte de Varsovie de 1955.', 4),
    ('8f574dde-f036-5d08-8435-3d6f3d110454'::uuid, '23bd4a29-12d7-5628-b216-73e17cd7e641'::uuid, 'Quand le mur de Berlin est-il construit ?', 'mcq', '["Dans la nuit du 12 au 13 août 1961","En juin 1948","En octobre 1962","En mai 1949"]'::jsonb, 0, 'Il vise à arrêter les départs vers l’Ouest.', 5),
    ('d84a6a22-2731-5feb-929a-e3c6fb3fd588'::uuid, '23bd4a29-12d7-5628-b216-73e17cd7e641'::uuid, 'Quel conflit fige une péninsule au 38e parallèle entre 1950 et 1953 ?', 'mcq', '["La guerre de Corée","La guerre du Vietnam","La guerre d’Indochine","La guerre d’Afghanistan"]'::jsonb, 0, 'La frontière est toujours en place aujourd’hui.', 6),
    ('fb745c3f-af90-5da7-9b9f-ecd3dd4c3e0e'::uuid, '23bd4a29-12d7-5628-b216-73e17cd7e641'::uuid, 'Comment se règle la crise des missiles de Cuba en 1962 ?', 'mcq', '["Khrouchtchev retire les missiles contre l’engagement américain de ne pas envahir Cuba","Les États-Unis envahissent Cuba","L’ONU place l’île sous tutelle","L’URSS annexe Cuba"]'::jsonb, 0, 'Un téléphone rouge est ensuite installé entre les deux capitales.', 7),
    ('383c84d9-2552-5b8d-938a-5b0a369dc3c9'::uuid, '23bd4a29-12d7-5628-b216-73e17cd7e641'::uuid, 'Les deux superpuissances se sont affrontées directement sur un champ de bataille.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'La dissuasion nucléaire les en a dissuadées : « paix impossible, guerre improbable ».', 8),
    ('bea94edf-2228-5c1a-bd60-a2fe3d6b6ed1'::uuid, '1cc48ce7-adf6-5136-9261-a437d4fc9ce3'::uuid, 'Que désigne la « détente » entre 1963 et 1975 ?', 'mcq', '["Une période d’accords limitant la rivalité sans y renoncer","La fin définitive de la guerre froide","L’alliance militaire des deux blocs","Le désarmement total des deux camps"]'::jsonb, 0, 'SALT I, non-prolifération et Helsinki en sont les jalons.', 1),
    ('f9a1aa50-f893-5811-b580-352203550104'::uuid, '1cc48ce7-adf6-5136-9261-a437d4fc9ce3'::uuid, 'Que se passe-t-il à Prague en 1968 ?', 'mcq', '["Les chars du pacte de Varsovie écrasent le Printemps de Prague","Le mur de Berlin est construit","L’URSS quitte l’Afghanistan","La Tchécoslovaquie rejoint l’OTAN"]'::jsonb, 0, 'Le « socialisme à visage humain » est brisé.', 2),
    ('7719d5a3-61f8-58c8-96c7-f2f51a8a302c'::uuid, '1cc48ce7-adf6-5136-9261-a437d4fc9ce3'::uuid, 'Quel événement de 1979 relance la tension entre les blocs ?', 'mcq', '["L’invasion de l’Afghanistan par l’URSS","La chute de Saigon","La signature des accords SALT I","La catastrophe de Tchernobyl"]'::jsonb, 0, 'Elle ouvre la période dite de la guerre fraîche.', 3),
    ('f9258d26-bcc4-511f-a6a4-2e29ed491d47'::uuid, '1cc48ce7-adf6-5136-9261-a437d4fc9ce3'::uuid, 'Quelles réformes Gorbatchev lance-t-il à partir de 1985 ?', 'mcq', '["La perestroïka et la glasnost","Les plans quinquennaux","La collectivisation et les purges","Le Kominform et la doctrine Jdanov"]'::jsonb, 0, 'Restructuration économique et transparence.', 4),
    ('42268720-ff4e-590a-9131-e1cc9c767af9'::uuid, '1cc48ce7-adf6-5136-9261-a437d4fc9ce3'::uuid, 'Quelle catastrophe de 1986 ébranle la confiance dans le régime soviétique ?', 'mcq', '["Tchernobyl","Bhopal","Fukushima","Seveso"]'::jsonb, 0, 'L’accident nucléaire et son silence initial marquent les esprits.', 5),
    ('9d6d01f4-f1c6-5881-b042-64ca570d5fee'::uuid, '1cc48ce7-adf6-5136-9261-a437d4fc9ce3'::uuid, 'Quand le mur de Berlin tombe-t-il ?', 'mcq', '["Le 9 novembre 1989","Le 3 octobre 1990","Le 25 décembre 1991","Le 13 août 1961"]'::jsonb, 0, 'L’Allemagne est réunifiée moins d’un an plus tard.', 6),
    ('ca146b3c-4666-55f3-be59-6c2161a1aba6'::uuid, '1cc48ce7-adf6-5136-9261-a437d4fc9ce3'::uuid, 'Quand l’URSS disparaît-elle officiellement ?', 'mcq', '["Le 25 décembre 1991","Le 9 novembre 1989","En juillet 1991","En mars 1985"]'::jsonb, 0, 'Le pacte de Varsovie avait été dissous quelques mois plus tôt.', 7),
    ('5263ff75-8ede-5b99-9c0f-feca57c8e655'::uuid, '1cc48ce7-adf6-5136-9261-a437d4fc9ce3'::uuid, 'Après 1991, on qualifie le monde d’unipolaire, dominé par les États-Unis.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Ils restent la seule superpuissance militaire et économique.', 8),
    ('f64aa61c-7407-54a2-ac84-d25fb637a7c0'::uuid, 'cd7f0e9d-ecd7-5c3a-b751-2f9a96bb71f8'::uuid, 'Quelle déclaration du 9 mai 1950 lance la construction européenne ?', 'mcq', '["La déclaration Schuman","Le traité de Rome","Le traité de Maastricht","La déclaration de Messine"]'::jsonb, 0, 'Elle propose de mettre en commun le charbon et l’acier.', 1),
    ('0d9c7be2-70fc-5f3a-a8d3-b0f4e16265c5'::uuid, 'cd7f0e9d-ecd7-5c3a-b751-2f9a96bb71f8'::uuid, 'Combien de pays fondent la CECA puis la CEE ?', 'mcq', '["Six","Neuf","Douze","Quatre"]'::jsonb, 0, 'France, RFA, Italie, Belgique, Pays-Bas, Luxembourg.', 2),
    ('3455d9a5-79d8-5d64-b29a-919b9e013b3d'::uuid, 'cd7f0e9d-ecd7-5c3a-b751-2f9a96bb71f8'::uuid, 'Que crée le traité de Rome de 1957 ?', 'mcq', '["La Communauté économique européenne et le marché commun","L’euro","L’espace Schengen","Le Parlement européen"]'::jsonb, 0, 'Il pose les quatre libertés de circulation.', 3),
    ('47229f1b-507b-5dc5-9a9e-2f16a7684de3'::uuid, 'cd7f0e9d-ecd7-5c3a-b751-2f9a96bb71f8'::uuid, 'Que change le traité de Maastricht de 1992 ?', 'mcq', '["Il crée l’Union européenne et la citoyenneté européenne","Il crée la CECA","Il organise le Brexit","Il supprime la PAC"]'::jsonb, 0, 'Il programme aussi la monnaie unique.', 4),
    ('7c231226-dbaf-50ee-85ec-16ef4c36c465'::uuid, 'cd7f0e9d-ecd7-5c3a-b751-2f9a96bb71f8'::uuid, 'Quand l’euro entre-t-il en circulation sous forme de pièces et billets ?', 'mcq', '["Le 1er janvier 2002","En 1999","En 1992","En 2007"]'::jsonb, 0, 'Il existait comme monnaie de compte depuis 1999.', 5),
    ('a014e5c3-4b78-557f-9c97-2db87d3a41a4'::uuid, 'cd7f0e9d-ecd7-5c3a-b751-2f9a96bb71f8'::uuid, 'Que permettent les accords de Schengen ?', 'mcq', '["La suppression des contrôles aux frontières intérieures","La création d’une armée européenne","L’adhésion automatique des pays candidats","L’harmonisation des impôts"]'::jsonb, 0, 'Signés en 1985, ils s’appliquent à partir de 1995.', 6),
    ('235bf28f-cced-520f-aed5-8632a64089c7'::uuid, 'cd7f0e9d-ecd7-5c3a-b751-2f9a96bb71f8'::uuid, 'Depuis quand le Parlement européen est-il élu au suffrage universel direct ?', 'mcq', '["Depuis 1979","Depuis 1957","Depuis 1992","Depuis 2004"]'::jsonb, 0, 'C’est la seule institution européenne élue directement par les citoyens.', 7),
    ('a95f93b1-602d-5dc5-9def-7d78ee1f6b64'::uuid, 'cd7f0e9d-ecd7-5c3a-b751-2f9a96bb71f8'::uuid, 'Le Royaume-Uni a quitté l’Union européenne en 2020.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'L’Union est passée de 28 à 27 membres.', 8),
    ('8728076e-9d31-5471-977d-218a60f5d776'::uuid, 'f66d54db-e6ce-5791-a489-c7d06a463700'::uuid, 'Que signifie « monde multipolaire » ?', 'mcq', '["Plusieurs pôles de puissance coexistent","Une seule puissance domine","Deux blocs s’affrontent","Aucun État n’a de puissance militaire"]'::jsonb, 0, 'C’est la situation qui succède à l’unipolarité des années 1990.', 1),
    ('417517f9-bff3-545e-bd6f-bb52ee4c322b'::uuid, 'f66d54db-e6ce-5791-a489-c7d06a463700'::uuid, 'Quel événement de 2001 ouvre une nouvelle séquence géopolitique ?', 'mcq', '["Les attentats du 11 septembre","L’invasion de l’Irak","La création de l’euro","L’élargissement de l’Union européenne"]'::jsonb, 0, 'Ils entraînent l’intervention en Afghanistan.', 2),
    ('db767bc0-8d4f-5711-a18b-29e7961665e3'::uuid, 'f66d54db-e6ce-5791-a489-c7d06a463700'::uuid, 'Quel territoire la Russie annexe-t-elle en 2014 ?', 'mcq', '["La Crimée","La Géorgie","La Moldavie","La Biélorussie"]'::jsonb, 0, 'L’invasion de l’Ukraine suit en février 2022.', 3),
    ('0ea003d3-1b98-5d9f-b2be-c95e6a07c93a'::uuid, 'f66d54db-e6ce-5791-a489-c7d06a463700'::uuid, 'Quel accord international sur le climat est signé en 2015 ?', 'mcq', '["L’accord de Paris","Le protocole de Kyoto","La convention de Genève","Le traité de Lisbonne"]'::jsonb, 0, 'Il vise à contenir le réchauffement global.', 4),
    ('2a686350-a6c3-56c9-ab1a-769d11769118'::uuid, 'f66d54db-e6ce-5791-a489-c7d06a463700'::uuid, 'Qu’est-ce qui bloque souvent l’action du Conseil de sécurité de l’ONU ?', 'mcq', '["Le droit de veto des cinq membres permanents","L’absence de siège permanent","Le vote à la majorité simple","Le refus des ONG"]'::jsonb, 0, 'Sa réforme est débattue depuis des décennies.', 5),
    ('2ec37f25-3a92-5cbf-8a1a-d9b9fe223417'::uuid, 'f66d54db-e6ce-5791-a489-c7d06a463700'::uuid, 'Pourquoi parle-t-on de menaces transnationales ?', 'mcq', '["Elles dépassent les frontières alors que les décisions restent nationales","Elles ne concernent qu’un seul pays","Elles sont uniquement militaires","Elles sont traitées par l’ONU seule"]'::jsonb, 0, 'Climat, pandémies et cybersécurité en sont les exemples.', 6),
    ('3d1b3f6c-a0f1-5908-9bf1-38b6f0337454'::uuid, 'f66d54db-e6ce-5791-a489-c7d06a463700'::uuid, 'Quelle zone est marquée par des tensions autour de Taïwan ?', 'mcq', '["L’Asie orientale","L’Afrique sahélienne","L’Amérique centrale","L’Europe du Nord"]'::jsonb, 0, 'La mer de Chine méridionale est un foyer de rivalités.', 7),
    ('545ac053-891d-5e24-a3d5-6c034bf4c5ab'::uuid, 'f66d54db-e6ce-5791-a489-c7d06a463700'::uuid, 'La Chine est aujourd’hui une puissance économique et technologique de premier plan.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Elle est l’un des principaux pôles du monde multipolaire.', 8),
    ('a83e9659-3673-5c4f-81aa-15326c87c20b'::uuid, '4e4f149a-ca7b-59a2-a569-e10cdd43f499'::uuid, 'Quel texte adopté en 1944 sert de feuille de route à la refondation ?', 'mcq', '["Le programme du Conseil national de la Résistance","La Charte de l’ONU","Le préambule de 1958","Les accords Matignon"]'::jsonb, 0, 'Il est intitulé Les Jours heureux.', 1),
    ('26c99546-a96b-5748-8e4d-87ac06a30d6b'::uuid, '4e4f149a-ca7b-59a2-a569-e10cdd43f499'::uuid, 'Quand les Françaises votent-elles pour la première fois ?', 'mcq', '["En avril 1945","En 1944","En 1946","En 1936"]'::jsonb, 0, 'L’ordonnance leur accordant le droit de vote date du 21 avril 1944.', 2),
    ('df139acf-3941-54d7-a0c4-8367de092d10'::uuid, '4e4f149a-ca7b-59a2-a569-e10cdd43f499'::uuid, 'Quelle grande institution sociale est créée en octobre 1945 ?', 'mcq', '["La Sécurité sociale","Le RMI","Pôle emploi","Les allocations chômage"]'::jsonb, 0, 'Elle couvre maladie, accidents du travail, vieillesse et famille.', 3),
    ('8aed2758-fe21-5070-8bec-f2c405727f69'::uuid, '4e4f149a-ca7b-59a2-a569-e10cdd43f499'::uuid, 'Quelles entreprises sont nationalisées à la Libération ?', 'mcq', '["Renault, les charbonnages, EDF-GDF, Air France","Peugeot, Michelin, Danone","Les banques privées uniquement","Aucune entreprise"]'::jsonb, 0, 'L’État prend le contrôle de secteurs jugés stratégiques.', 4),
    ('93132138-88ee-5370-85d1-86f872d1085a'::uuid, '4e4f149a-ca7b-59a2-a569-e10cdd43f499'::uuid, 'Quand la Constitution de la IVe République est-elle adoptée ?', 'mcq', '["En octobre 1946","En 1944","En 1945","En 1958"]'::jsonb, 0, 'Un premier projet avait été rejeté en mai 1946.', 5),
    ('091439f9-195d-524c-a752-e56e74f73bae'::uuid, '4e4f149a-ca7b-59a2-a569-e10cdd43f499'::uuid, 'Quelle est la principale faiblesse de la IVe République ?', 'mcq', '["L’instabilité ministérielle","L’absence d’élections","L’absence de Parlement","Le refus de la construction européenne"]'::jsonb, 0, 'Plus de vingt gouvernements se succèdent en douze ans.', 6),
    ('8bc243e0-5343-507c-964f-a06d26e2fcfd'::uuid, '4e4f149a-ca7b-59a2-a569-e10cdd43f499'::uuid, 'Quel conflit emporte la IVe République en 1958 ?', 'mcq', '["La guerre d’Algérie","La guerre de Corée","La guerre d’Indochine","La crise de Suez"]'::jsonb, 0, 'La crise du 13 mai 1958 ramène de Gaulle au pouvoir.', 7),
    ('442f62f4-8c45-5b8c-98cc-b6a9cc2c1407'::uuid, '4e4f149a-ca7b-59a2-a569-e10cdd43f499'::uuid, 'De Gaulle a dirigé la IVe République pendant toute sa durée.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Hostile à ce régime, il démissionne dès janvier 1946.', 8),
    ('16511ae2-61e4-5e49-b42a-333a1283368a'::uuid, '39c0a7b7-54df-592d-8d1d-e31bf19a9c6b'::uuid, 'Quel événement ramène de Gaulle au pouvoir en 1958 ?', 'mcq', '["La crise du 13 mai 1958 en Algérie","Mai 1968","La guerre d’Indochine","La crise de Suez"]'::jsonb, 0, 'Il obtient les pleins pouvoirs pour rédiger une Constitution.', 1),
    ('6e2eb115-86f9-51c5-a186-593c0c3b0795'::uuid, '39c0a7b7-54df-592d-8d1d-e31bf19a9c6b'::uuid, 'Quand la Constitution de la Ve République est-elle approuvée ?', 'mcq', '["Le 28 septembre 1958","En octobre 1946","En 1962","En 1969"]'::jsonb, 0, 'Elle est adoptée par référendum.', 2),
    ('dd3bea4b-0383-58d5-ae7c-ad3e28213dd2'::uuid, '39c0a7b7-54df-592d-8d1d-e31bf19a9c6b'::uuid, 'Que change le référendum de 1962 ?', 'mcq', '["Le président est désormais élu au suffrage universel direct","Le Sénat est supprimé","Le président est élu par le Parlement","La durée du mandat passe à cinq ans"]'::jsonb, 0, 'La première élection de ce type a lieu en 1965.', 3),
    ('5c3571ee-017c-56c2-982a-97e289970d8d'::uuid, '39c0a7b7-54df-592d-8d1d-e31bf19a9c6b'::uuid, 'Quel article permet au président de soumettre un texte au référendum ?', 'mcq', '["L’article 11","L’article 16","L’article 49","L’article 5"]'::jsonb, 0, 'L’article 16 concerne les pouvoirs exceptionnels.', 4),
    ('6bccefd7-7da8-5916-8723-3d1612b6070b'::uuid, '39c0a7b7-54df-592d-8d1d-e31bf19a9c6b'::uuid, 'Quelle décision marque la politique d’indépendance nationale en 1966 ?', 'mcq', '["La sortie du commandement intégré de l’OTAN","L’entrée dans le pacte de Varsovie","Le renoncement à l’arme nucléaire","La rupture avec l’Allemagne"]'::jsonb, 0, 'La France conserve son alliance mais reprend son autonomie militaire.', 5),
    ('3fa9fe91-7127-56fe-bf2f-782e62ca5b9c'::uuid, '39c0a7b7-54df-592d-8d1d-e31bf19a9c6b'::uuid, 'Quel traité franco-allemand est signé en 1963 ?', 'mcq', '["Le traité de l’Élysée","Le traité de Rome","Le traité de Maastricht","Le traité de Versailles"]'::jsonb, 0, 'Il scelle la réconciliation entre les deux pays.', 6),
    ('09d55818-6c95-5b0a-9f67-d36806005414'::uuid, '39c0a7b7-54df-592d-8d1d-e31bf19a9c6b'::uuid, 'Qu’accordent les accords de Grenelle en mai 1968 ?', 'mcq', '["Une forte hausse du SMIG et des droits syndicaux","La semaine de 35 heures","La retraite à 60 ans","La cinquième semaine de congés payés"]'::jsonb, 0, 'La contestation dépassait toutefois les seules revendications salariales.', 7),
    ('b004a8d1-fdb7-5076-a98d-731270c3846f'::uuid, '39c0a7b7-54df-592d-8d1d-e31bf19a9c6b'::uuid, 'De Gaulle démissionne après avoir perdu le référendum d’avril 1969.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Il quitte le pouvoir dès le lendemain du scrutin.', 8),
    ('7d202ea4-85f0-5879-bf7f-265787be9783'::uuid, '365d5bdb-1c9d-55ab-90b6-457b1eaf6a52'::uuid, 'Qui a forgé l’expression « Trente Glorieuses » ?', 'mcq', '["Jean Fourastié","Alfred Sauvy","Raymond Aron","Fernand Braudel"]'::jsonb, 0, 'Elle désigne les trois décennies de forte croissance après 1945.', 1),
    ('06afe814-7bb6-501d-bae1-571203eb35fe'::uuid, '365d5bdb-1c9d-55ab-90b6-457b1eaf6a52'::uuid, 'Quel taux de croissance annuel moyen caractérise cette période en France ?', 'mcq', '["Plus de 5 %","Environ 1 %","Environ 2 %","Plus de 10 %"]'::jsonb, 0, 'Un rythme jamais retrouvé depuis.', 2),
    ('6a609178-ed75-5c88-856f-342b50f3b9ec'::uuid, '365d5bdb-1c9d-55ab-90b6-457b1eaf6a52'::uuid, 'Qu’est-ce que le baby-boom ?', 'mcq', '["Une forte hausse des naissances après 1945","Une vague d’immigration","Une politique de logement social","Une réforme scolaire"]'::jsonb, 0, 'Il fournit une main-d’œuvre nombreuse à la croissance.', 3),
    ('6f5427d7-6059-5e76-93e8-9fad3466cdb3'::uuid, '365d5bdb-1c9d-55ab-90b6-457b1eaf6a52'::uuid, 'Quel équipement se diffuse massivement dans les foyers durant cette période ?', 'mcq', '["Le réfrigérateur, la machine à laver, la télévision","L’ordinateur personnel","Le téléphone portable","Le four à micro-ondes uniquement"]'::jsonb, 0, 'La société de consommation se met en place.', 4),
    ('5b900867-7137-5918-a514-c03067f86a66'::uuid, '365d5bdb-1c9d-55ab-90b6-457b1eaf6a52'::uuid, 'Que sont les grands ensembles ?', 'mcq', '["De vastes quartiers de logements construits rapidement","Des zones industrielles","Des centres commerciaux","Des complexes agricoles"]'::jsonb, 0, 'Ils apportent d’abord un confort moderne inédit.', 5),
    ('50e81357-cc51-54ef-8077-5d3c4e5a9b45'::uuid, '365d5bdb-1c9d-55ab-90b6-457b1eaf6a52'::uuid, 'Quelle loi de 1967 autorise la contraception en France ?', 'mcq', '["La loi Neuwirth","La loi Veil","La loi Haby","La loi Royer"]'::jsonb, 0, 'La loi Veil dépénalise l’IVG en 1975.', 6),
    ('0cf849ee-7ccd-5cbf-a972-a79a3feb8d90'::uuid, '365d5bdb-1c9d-55ab-90b6-457b1eaf6a52'::uuid, 'Quel événement met fin aux Trente Glorieuses ?', 'mcq', '["Le choc pétrolier de 1973","Mai 1968","La chute du mur de Berlin","Le traité de Rome"]'::jsonb, 0, 'Il ouvre une période d’inflation et de chômage de masse.', 7),
    ('3aa8c561-4f16-5113-bc9e-a4fd57babc8d'::uuid, '365d5bdb-1c9d-55ab-90b6-457b1eaf6a52'::uuid, 'Le secteur tertiaire dépasse l’industrie durant les Trente Glorieuses.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Le salariat devient la norme et les services se développent.', 8),
    ('a04d8798-1390-5ddc-8bf2-c7f63a23493b'::uuid, '47f6cabf-1f1f-55af-b99b-47f18eec5ff8'::uuid, 'Quelle réforme majeure Valéry Giscard d’Estaing fait-il adopter dès 1974 ?', 'mcq', '["La majorité à 18 ans","L’abolition de la peine de mort","Le quinquennat","La retraite à 60 ans"]'::jsonb, 0, 'La loi Veil sur l’IVG suit en 1975.', 1),
    ('6aa2adc8-5aef-5920-8766-3c730b8ac632'::uuid, '47f6cabf-1f1f-55af-b99b-47f18eec5ff8'::uuid, 'Quelle grande réforme marque l’arrivée de François Mitterrand en 1981 ?', 'mcq', '["L’abolition de la peine de mort","Le passage au quinquennat","La fin du service militaire","La loi sur la laïcité à l’école"]'::jsonb, 0, 'Elle est portée par Robert Badinter.', 2),
    ('eaae3e12-0f91-54b1-bae4-fdde09d9ba37'::uuid, '47f6cabf-1f1f-55af-b99b-47f18eec5ff8'::uuid, 'Qu’est-ce qu’une cohabitation ?', 'mcq', '["Un président et un Premier ministre d’orientations politiques opposées","Deux présidents en exercice","Un gouvernement sans majorité","Une alliance entre deux partis de même camp"]'::jsonb, 0, 'La France en a connu trois entre 1986 et 2002.', 3),
    ('3dabef0a-7995-531a-88a4-1b1178d2c697'::uuid, '47f6cabf-1f1f-55af-b99b-47f18eec5ff8'::uuid, 'Combien de temps dure le mandat présidentiel depuis la réforme de 2000 ?', 'mcq', '["Cinq ans","Sept ans","Quatre ans","Six ans"]'::jsonb, 0, 'Le quinquennat rend la cohabitation improbable.', 4),
    ('de8f4641-b8a4-5ce1-bf39-ff8cef4d1e52'::uuid, '47f6cabf-1f1f-55af-b99b-47f18eec5ff8'::uuid, 'Que transfèrent les lois Defferre de 1982 ?', 'mcq', '["Des compétences de l’État aux communes, départements et régions","Des compétences des régions vers l’État","Les impôts locaux à l’État","Le pouvoir législatif au président"]'::jsonb, 0, 'C’est l’acte fondateur de la décentralisation.', 5),
    ('d5aad537-c9cf-5c17-bfeb-4bdcbe275222'::uuid, '47f6cabf-1f1f-55af-b99b-47f18eec5ff8'::uuid, 'Qu’instaure la réforme constitutionnelle de 2008 en matière de justice ?', 'mcq', '["La question prioritaire de constitutionnalité","La suppression du Conseil constitutionnel","Le référendum obligatoire","La nomination des juges par le Parlement"]'::jsonb, 0, 'Elle permet à tout justiciable de contester une loi appliquée à son cas.', 6),
    ('cb9353db-83ed-51d1-91b4-0c0952debd72'::uuid, '47f6cabf-1f1f-55af-b99b-47f18eec5ff8'::uuid, 'Que prouve l’alternance de 1981 ?', 'mcq', '["Que la Constitution fonctionne quel que soit le camp au pouvoir","Que le président doit être issu de la droite","Que le Parlement domine l’exécutif","Que la cohabitation est impossible"]'::jsonb, 0, 'La Ve République survit à son fondateur et au changement de majorité.', 7),
    ('12b4c097-fd39-5c33-83ef-854282bba43a'::uuid, '47f6cabf-1f1f-55af-b99b-47f18eec5ff8'::uuid, 'Pendant une cohabitation, le président conserve la défense et les affaires étrangères.', 'true_false', '["Vrai","Faux"]'::jsonb, 0, 'Le gouvernement conduit alors la politique intérieure.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('histoire-geo');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('histoire-geo')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 291 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 291 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
