-- =============================================================================
-- Studuel — Migration 293 : GÉOGRAPHIE 3e — LE PROGRAMME COMPLET (12 fiches)
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 293 --modules geographie-3e
--
-- CONSTAT : la Troisième n'avait qu'UNE SEULE fiche de géographie, héritée du
-- premier jeu de données de l'app ("Les aires urbaines en France"), pour un
-- programme qui compte trois chapitres — les dynamiques territoriales de la France
-- contemporaine, l'aménagement du territoire, la France et l'Union européenne. Un
-- élève de 3e qui révisait les espaces productifs, les espaces de faible densité,
-- les territoires ultramarins, la politique de la ville, la construction
-- européenne ou la place de l'Europe dans le monde ne trouvait RIEN. Cette
-- migration installe les 12 fiches de la maquette, rangées sous leurs 3 chapitres,
-- et retire la fiche générique que la première d'entre elles reprend.
-- ELLE DÉDOUBLE AUSSI L'ONGLET DU DOSSIER : les 14 fiches d'histoire (migration
-- 291) portent le rayon "histoire", les 12 fiches d'ici portent "geographie", et
-- la page matière rend un onglet par rayon dès qu'il y en a DEUX. Le dossier
-- d'histoire-géo de 3e s'ouvre donc désormais sur "Histoire" et "Géographie",
-- comme en 2de, en 1re et en Terminale.
--
-- Cette migration apporte : 12 chapitres, 12 leçons,
-- 12 quiz et 96 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 0. Ménage ----------------------------------------------------------------
-- [histoire-geo] Les colonnes chapters.theme (migration 234) et chapters.discipline
-- [histoire-geo] (migration 247) conditionnent tout ce qui suit : ce module range ses 12 fiches
-- [histoire-geo] sous 3 chapitres et un rayon, et l'INSERT écrit les deux colonnes. Elles sont
-- [histoire-geo] REPRISES ici en ADD COLUMN IF NOT EXISTS parce qu'on ne peut pas garantir que la
-- [histoire-geo] 234 et la 247 soient passées en production — sans cette reprise, la migration
-- [histoire-geo] échouerait sur "column chapters.theme does not exist", la fiche héritée déjà
-- [histoire-geo] supprimée et les 12 neuves pas encore posées : une géographie vide.
-- [histoire-geo] Le ménage qui suit LIT la colonne theme : elle doit exister avant lui, pas
-- [histoire-geo] seulement avant les insertions.
-- [histoire-geo] Le GRANT n'est pas décoratif : la migration 182 a révoqué le SELECT de table sur
-- [histoire-geo] chapters (pour cacher mind_map) et ne l'a rendu que colonne par colonne. Une
-- [histoire-geo] colonne ajoutée après elle n'hérite d'aucun droit — sans lui, l'app lirait
-- [histoire-geo] "permission denied" au lieu du chapitre, et l'onglet ne se dédoublerait pas.
ALTER TABLE public.chapters ADD COLUMN IF NOT EXISTS theme TEXT;
GRANT SELECT (theme) ON public.chapters TO anon;
GRANT SELECT (theme) ON public.chapters TO authenticated;

ALTER TABLE public.chapters ADD COLUMN IF NOT EXISTS discipline TEXT;
GRANT SELECT (discipline) ON public.chapters TO anon;
GRANT SELECT (discipline) ON public.chapters TO authenticated;

-- [histoire-geo] La fiche de géographie héritée part. "Les aires urbaines en France" est la
-- [histoire-geo] première fiche du chapitre 1 de la maquette, et la fiche neuve porte le MÊME
-- [histoire-geo] TITRE : la table chapters est UNIQUE(subject_id, level, title), donc sans ce
-- [histoire-geo] ménage l'INSERT tomberait dans le ON CONFLICT DO NOTHING et la leçon échouerait
-- [histoire-geo] ensuite sur une clé étrangère absente — la migration s'arrêterait à mi-parcours.
-- [histoire-geo] LA BORNE theme IS NULL EST LE POINT CRITIQUE. Le ménage tourne AVANT les
-- [histoire-geo] insertions à chaque passage : borné au seul titre, un REJEU supprimerait la fiche
-- [histoire-geo] neuve et ses quiz, puisqu'elle porte le même titre. L'ancienne fiche est d'avant
-- [histoire-geo] la colonne theme (migration 234) et n'en porte donc aucun ; les 12 neuves en
-- [histoire-geo] portent un dès l'INSERT. La distinction est exacte et stable.
-- [histoire-geo] Le filtre level = '3e' est indispensable : sans lui le ménage mordrait sur les
-- [histoire-geo] chapitres d'urbanisation des autres niveaux.
-- [histoire-geo] L'ordre compte : la file "À revoir" d'abord (review_items.item_id n'a PAS de clé
-- [histoire-geo] étrangère), puis les quiz (quizzes.lesson_id est ON DELETE SET NULL : ils
-- [histoire-geo] survivraient orphelins à leur chapitre, mais toujours tirables par le moteur de
-- [histoire-geo] questions), puis le chapitre, dont la leçon part en cascade.
DELETE FROM public.review_items ri
 USING public.quiz_questions qq, public.quizzes qz, public.lessons l,
       public.chapters c, public.subjects s
 WHERE ri.item_kind = 'question'
   AND ri.item_id = qq.id
   AND qq.quiz_id = qz.id
   AND qz.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'histoire-geo'
   AND c.level = '3e'
   AND c.title = 'Les aires urbaines en France'
   AND c.theme IS NULL;

DELETE FROM public.quizzes q
 USING public.lessons l, public.chapters c, public.subjects s
 WHERE q.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'histoire-geo'
   AND c.level = '3e'
   AND c.title = 'Les aires urbaines en France'
   AND c.theme IS NULL;

DELETE FROM public.chapters c
 USING public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'histoire-geo'
   AND c.level = '3e'
   AND c.title = 'Les aires urbaines en France'
   AND c.theme IS NULL;

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position, theme, discipline)
SELECT v.id, s.id, v.level, v.title, v.position, v.theme, v.discipline
  FROM (VALUES
    ('2a360b9e-58d4-5d2c-99aa-1ed25cbbb4c8'::uuid, 'histoire-geo', '3e', 'Les aires urbaines en France', 15, 'Dynamiques territoriales de la France contemporaine', 'geographie'),
    ('174488ca-afc4-5157-984c-e59610dde149'::uuid, 'histoire-geo', '3e', 'Les espaces productifs : la France industrielle', 16, 'Dynamiques territoriales de la France contemporaine', 'geographie'),
    ('d0b9a0a7-1354-5e70-b8a7-ca9d337f0a05'::uuid, 'histoire-geo', '3e', 'Les espaces productifs : la France agricole', 17, 'Dynamiques territoriales de la France contemporaine', 'geographie'),
    ('0cacb155-eb80-5424-8bdb-844960d264cd'::uuid, 'histoire-geo', '3e', 'Les espaces productifs : la France des services', 18, 'Dynamiques territoriales de la France contemporaine', 'geographie'),
    ('2222b08d-0800-5557-8246-9c0ac13b4a44'::uuid, 'histoire-geo', '3e', 'Les espaces de faible densité', 19, 'Dynamiques territoriales de la France contemporaine', 'geographie'),
    ('9b55af5a-e29d-5cbb-87e7-2fc8d2f43360'::uuid, 'histoire-geo', '3e', 'L’aménagement comme réponse aux inégalités territoriales', 20, 'Pourquoi et comment aménager le territoire ?', 'geographie'),
    ('0d896e0b-f92e-567e-a3fb-6306c0b0b0ff'::uuid, 'histoire-geo', '3e', 'La politique de la ville', 21, 'Pourquoi et comment aménager le territoire ?', 'geographie'),
    ('5f5f3f5f-1797-5381-829b-8fda245c1ba1'::uuid, 'histoire-geo', '3e', 'Les territoires ultra-marins français', 22, 'Pourquoi et comment aménager le territoire ?', 'geographie'),
    ('470832dc-e0a6-54b4-b10d-8a22ce95e228'::uuid, 'histoire-geo', '3e', 'L’Union européenne : un territoire en construction', 23, 'La France et l’Union européenne', 'geographie'),
    ('b330d15a-2c67-5816-8f56-bca0736238c2'::uuid, 'histoire-geo', '3e', 'Les contrastes territoriaux à l’intérieur de l’Union européenne', 24, 'La France et l’Union européenne', 'geographie'),
    ('53f85f17-1b08-543a-8e26-c9b9568ded36'::uuid, 'histoire-geo', '3e', 'L’Europe dans le monde', 25, 'La France et l’Union européenne', 'geographie'),
    ('7d06202f-144f-56d7-a58b-526573dc5c78'::uuid, 'histoire-geo', '3e', 'La France dans l’Union européenne', 26, 'La France et l’Union européenne', 'geographie')
  ) AS v(id, slug, level, title, position, theme, discipline)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 1 bis. Axes du programme -------------------------------------------------
-- `chapters.theme` (migration 234) : l’intitulé du programme officiel qui
-- coiffe le chapitre. La page matière s’en sert pour grouper au lieu
-- d’aligner 28 lignes à plat. UPDATE et non INSERT : le chapitre peut déjà
-- exister (l’INSERT précédent l’aurait alors ignoré).
UPDATE public.chapters c SET theme = v.theme
  FROM (VALUES
    ('2a360b9e-58d4-5d2c-99aa-1ed25cbbb4c8'::uuid, 'Dynamiques territoriales de la France contemporaine'),
    ('174488ca-afc4-5157-984c-e59610dde149'::uuid, 'Dynamiques territoriales de la France contemporaine'),
    ('d0b9a0a7-1354-5e70-b8a7-ca9d337f0a05'::uuid, 'Dynamiques territoriales de la France contemporaine'),
    ('0cacb155-eb80-5424-8bdb-844960d264cd'::uuid, 'Dynamiques territoriales de la France contemporaine'),
    ('2222b08d-0800-5557-8246-9c0ac13b4a44'::uuid, 'Dynamiques territoriales de la France contemporaine'),
    ('9b55af5a-e29d-5cbb-87e7-2fc8d2f43360'::uuid, 'Pourquoi et comment aménager le territoire ?'),
    ('0d896e0b-f92e-567e-a3fb-6306c0b0b0ff'::uuid, 'Pourquoi et comment aménager le territoire ?'),
    ('5f5f3f5f-1797-5381-829b-8fda245c1ba1'::uuid, 'Pourquoi et comment aménager le territoire ?'),
    ('470832dc-e0a6-54b4-b10d-8a22ce95e228'::uuid, 'La France et l’Union européenne'),
    ('b330d15a-2c67-5816-8f56-bca0736238c2'::uuid, 'La France et l’Union européenne'),
    ('53f85f17-1b08-543a-8e26-c9b9568ded36'::uuid, 'La France et l’Union européenne'),
    ('7d06202f-144f-56d7-a58b-526573dc5c78'::uuid, 'La France et l’Union européenne')
  ) AS v(id, theme)
 WHERE c.id = v.id AND c.theme IS DISTINCT FROM v.theme;

-- 1 ter. Rayons du dossier -------------------------------------------------
-- `chapters.discipline` (migration 247) : le rayon de la matière auquel la
-- fiche appartient. La page matière en fait un onglet par rayon.
UPDATE public.chapters c SET discipline = v.discipline
  FROM (VALUES
    ('2a360b9e-58d4-5d2c-99aa-1ed25cbbb4c8'::uuid, 'geographie'),
    ('174488ca-afc4-5157-984c-e59610dde149'::uuid, 'geographie'),
    ('d0b9a0a7-1354-5e70-b8a7-ca9d337f0a05'::uuid, 'geographie'),
    ('0cacb155-eb80-5424-8bdb-844960d264cd'::uuid, 'geographie'),
    ('2222b08d-0800-5557-8246-9c0ac13b4a44'::uuid, 'geographie'),
    ('9b55af5a-e29d-5cbb-87e7-2fc8d2f43360'::uuid, 'geographie'),
    ('0d896e0b-f92e-567e-a3fb-6306c0b0b0ff'::uuid, 'geographie'),
    ('5f5f3f5f-1797-5381-829b-8fda245c1ba1'::uuid, 'geographie'),
    ('470832dc-e0a6-54b4-b10d-8a22ce95e228'::uuid, 'geographie'),
    ('b330d15a-2c67-5816-8f56-bca0736238c2'::uuid, 'geographie'),
    ('53f85f17-1b08-543a-8e26-c9b9568ded36'::uuid, 'geographie'),
    ('7d06202f-144f-56d7-a58b-526573dc5c78'::uuid, 'geographie')
  ) AS v(id, discipline)
 WHERE c.id = v.id AND c.discipline IS DISTINCT FROM v.discipline;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('862c3561-4f2a-5ad3-ba94-1bdd4a46a895', '2a360b9e-58d4-5d2c-99aa-1ed25cbbb4c8', 'Où vivent les Français ? La ville qui s’étale', E'La France est un pays **urbain** : plus de **80 % des Français** habitent une ville, et **95 %** vivent sous l’influence d’une ville — pour y travailler, y étudier, s’y soigner ou y faire leurs courses.\n\n## L’aire urbaine, l’outil qui mesure la ville réelle\nUne **aire urbaine** réunit deux morceaux :\n- le **pôle urbain** — la ville-centre et sa banlieue, une zone bâtie en continu qui offre au moins 1 500 emplois ;\n- la **couronne périurbaine** — les communes d’où **au moins 40 % des actifs** partent travailler dans le pôle.\n\n> La commune s’arrête à sa limite administrative ; l’aire urbaine, elle, dit jusqu’où la ville fait vivre les gens. (Depuis 2020, l’INSEE parle d’**aire d’attraction des villes** : le principe est le même.)\n\n## Une hiérarchie urbaine très inégale\n- **Paris** domine tout : environ **13 millions d’habitants**, soit un Français sur cinq. C’est la seule **métropole mondiale** française.\n- Une douzaine de **métropoles régionales** suivent de loin : Lyon, Marseille, Lille, Toulouse, Bordeaux, Nantes, Nice, Strasbourg, Rennes, Montpellier…\n- Puis les **villes moyennes** et les **petites villes**, dont beaucoup perdent commerces et services.\n\n## La métropolisation, effet de la mondialisation\nLa **métropolisation** est la concentration des hommes, des richesses et des **fonctions de commandement** dans les plus grandes villes : sièges sociaux, universités, laboratoires, hôpitaux de pointe, musées, aéroports internationaux. Les quartiers d’affaires en sont le symbole — **La Défense** à Paris, la Part-Dieu à Lyon, Euralille.\n\n## Une ville qui s’étale\nDepuis les années 1960, la ville grandit surtout **en surface** : c’est l’**étalement urbain**, nourri par le prix du logement, la voiture et le rêve de la maison avec jardin. Il produit la **périurbanisation**, des **mobilités pendulaires** (les navettes domicile-travail) toujours plus longues, l’**artificialisation des sols** et le **mitage** des campagnes. La loi vise désormais le « **zéro artificialisation nette** ».\n\n## Une ville qui sépare\nLa **ségrégation socio-spatiale** trie les quartiers selon les revenus : centres rénovés et chers (**gentrification**) d’un côté, **quartiers prioritaires** de l’autre. Habiter la même aire urbaine ne veut pas dire vivre la même ville.', 1),
  ('052b14e8-f923-5fbe-840f-83e398d6e6f5', '174488ca-afc4-5157-984c-e59610dde149', 'Des mines fermées aux technopôles', E'Un **espace productif** est un espace aménagé pour produire des richesses. L’industrie française a changé de visage — et de carte — en cinquante ans.\n\n## La désindustrialisation\nDepuis les années 1970, l’industrie a perdu la moitié de ses emplois. Trois causes :\n- la **concurrence mondiale** et les **délocalisations** vers des pays à main-d’œuvre moins chère ;\n- l’**automatisation**, qui produit autant avec moins d’ouvriers ;\n- l’épuisement ou l’abandon des ressources locales (charbon, minerai de fer).\n\nLes vieilles régions industrielles du **Nord**, de **Lorraine** et de **Saint-Étienne** en gardent des **friches industrielles**, un chômage élevé et une population qui part.\n\n## Les espaces industriels qui gagnent\n- Les **technopôles** : des parcs qui associent entreprises de haute technologie, laboratoires et universités — **Sophia Antipolis** près de Nice, l’Aerospace Valley à Toulouse.\n- Les **pôles de compétitivité**, labellisés par l’État pour faire travailler ensemble industriels et chercheurs.\n- Les **métropoles**, où se concentrent recherche, ingénierie et sièges sociaux.\n\n## La littoralisation\nLes industries lourdes qui consomment des matières premières importées s’installent sur les **littoraux**, au contact des grands ports : ce sont les **zones industrialo-portuaires (ZIP)** de **Dunkerque**, du **Havre**, de **Marseille-Fos**. Le littoral est une **interface** — le lieu de contact entre le territoire national et le monde.\n\n> Ce n’est pas l’industrie qui disparaît, ce sont ses lieux qui se déplacent : du bassin minier vers le port, le technopôle et la métropole.\n\n## Des industries de pointe qui font la puissance française\nAéronautique (**Airbus**, Toulouse), spatial, nucléaire, pharmacie, luxe et agroalimentaire restent des points forts, très exportateurs.', 1),
  ('7b2e8345-f3fc-5f7c-ae86-ab7ad0a003ee', 'd0b9a0a7-1354-5e70-b8a7-ca9d337f0a05', 'Une agriculture puissante, sous tension', E'La France est le **premier producteur agricole de l’Union européenne**, alors que l’agriculture n’occupe plus que **2 % des actifs**. Ce paradoxe s’explique par un demi-siècle de modernisation.\n\n## Une agriculture productiviste\nDepuis les années 1960, l’agriculture française cherche le **rendement maximal** :\n- **mécanisation** (tracteurs, moissonneuses) et agrandissement des exploitations ;\n- **engrais**, **pesticides**, semences sélectionnées, irrigation ;\n- **spécialisation** de chaque région dans une production.\n\nElle est **intégrée aux marchés** : reliée en amont aux entreprises qui vendent machines et intrants, en aval aux **industries agroalimentaires** et à la grande distribution.\n\n## Une carte très spécialisée\n- Les **grandes cultures céréalières** de la Beauce et du Bassin parisien, dans de vastes champs ouverts (**openfield**).\n- L’**élevage** de l’Ouest — dont l’élevage **hors-sol** de porcs et de volailles en Bretagne.\n- La **viticulture** de Bordeaux, de Bourgogne, de Champagne et du Languedoc.\n- Les **fruits et légumes** du Midi méditerranéen et des vallées irriguées.\n\n## Le rôle de l’Europe\nLa **PAC** (Politique agricole commune) verse des aides aux agriculteurs et oriente les productions depuis 1962. Sans elle, une grande partie des exploitations ne serait pas rentable.\n\n## Des tensions fortes\n- **Environnement** : nitrates et algues vertes en Bretagne, érosion des sols, perte de biodiversité.\n- **Revenus** : les prix imposés par la grande distribution étranglent beaucoup d’exploitations.\n- Une autre agriculture progresse : **bio**, labels de qualité (**AOP**, AOC, Label rouge) et **circuits courts** qui rapprochent producteur et consommateur.\n\n> Produire plus ou produire mieux : c’est le débat qui traverse aujourd’hui les campagnes françaises.', 1),
  ('38600747-2322-595f-b32a-b14422a4e41b', '0cacb155-eb80-5424-8bdb-844960d264cd', 'Le pays des services et le premier pays touristique du monde', E'Les **services** (le secteur tertiaire) emploient aujourd’hui près de **80 % des actifs** français : c’est la **tertiarisation** de l’économie.\n\n## Deux familles de services\n- Les **services marchands**, vendus : commerce, banque, assurance, transport, conseil, informatique, tourisme.\n- Les **services non marchands**, financés par l’impôt : école, hôpital public, justice, sécurité, administration.\n\n## Une géographie très concentrée\nLes services à **haute valeur ajoutée** (finance, conseil, recherche, médias) se concentrent dans les **métropoles**, et d’abord à Paris : **La Défense** rassemble plus de 180 000 salariés. Les villes moyennes et les campagnes gardent surtout les services **de proximité** (commerces, écoles, médecins) — et souffrent quand ceux-ci ferment.\n\n## La France, première destination touristique mondiale\nLa France accueille chaque année environ **90 millions de touristes étrangers**, un record mondial. Le tourisme représente près de **8 % du PIB**.\n\nQuatre grands types d’espaces touristiques :\n- le **tourisme urbain et culturel** : Paris, les châteaux de la Loire, les villes d’art ;\n- le **tourisme balnéaire** : Côte d’Azur, littoral atlantique, Languedoc ;\n- le **tourisme de montagne** : stations des Alpes et des Pyrénées, hiver comme été ;\n- le **tourisme vert**, dans les campagnes et les parcs naturels.\n\n## Aménager pour accueillir… et ses limites\nStations balnéaires, remontées mécaniques, parcs de loisirs (Disneyland Paris) créent des emplois, souvent **saisonniers**. Mais l’afflux touristique bétonne les littoraux, use les milieux fragiles de montagne et provoque un **surtourisme** dans certains sites.\n\n> Le tourisme fait vivre des territoires entiers — et menace parfois ce qui les rend attirants.', 1),
  ('304004d4-2e67-50e5-a475-b5f0e17e5788', '2222b08d-0800-5557-8246-9c0ac13b4a44', 'La France des campagnes et des montagnes', E'Un **espace de faible densité** compte moins de **30 habitants par km²**. Ces espaces couvrent près de **la moitié du territoire français** mais n’abritent qu’environ **6 % de la population**.\n\n## Où sont-ils ?\nIls dessinent une **diagonale des faibles densités** (l’ancienne « diagonale du vide ») qui traverse la France des Ardennes aux Landes, en passant par la Champagne, le Massif central et les Pyrénées. S’y ajoutent les hautes montagnes et une partie de la Corse.\n\n## Des difficultés réelles\n- **L’exode rural** puis la **déprise** : des villages qui perdent des habitants depuis un siècle.\n- Le **vieillissement** de la population.\n- La fermeture des **services** : école, bureau de poste, commerce, et parfois **déserts médicaux** où l’on cherche un médecin à 40 km.\n- La dépendance à la **voiture**, faute de transports collectifs.\n\n## Mais de vrais atouts\n- Une **agriculture de qualité** : élevage extensif, AOP fromagères, vignobles.\n- Le **tourisme vert** et le tourisme de montagne : randonnée, sports d’hiver, gîtes.\n- Les **énergies renouvelables** : éolien, solaire, hydroélectricité, biomasse.\n- Un **cadre de vie** recherché : des **néoruraux** s’y installent, et le **télétravail** a accéléré le mouvement depuis 2020.\n- Une **biodiversité** protégée par les **parcs naturels régionaux** et les parcs nationaux.\n\n> La faible densité n’est pas le vide : ces espaces produisent l’eau, l’énergie, les paysages et une partie de l’alimentation du pays.\n\n## Des dynamiques opposées\nLes campagnes proches des villes ou touristiques **gagnent** des habitants ; les campagnes isolées de montagne moyenne continuent souvent d’en perdre. Parler « des » espaces de faible densité au pluriel n’est pas une précaution de style : ce sont des mondes différents.', 1),
  ('fd71fcf7-2b42-5ece-b954-bf2c5854a9ac', '9b55af5a-e29d-5cbb-87e7-2fc8d2f43360', 'Qui transforme le territoire, et pour corriger quoi ?', E'**Aménager le territoire**, c’est le transformer volontairement pour le rendre plus attractif, plus accessible ou plus juste. En France, l’aménagement poursuit depuis les années 1960 un objectif affiché : réduire les **inégalités territoriales**.\n\n## Les inégalités à corriger\n- **Métropoles / périphéries** : les grandes villes captent emplois qualifiés et investissements ; villes moyennes et campagnes isolées décrochent.\n- **Centres / marges** au sein d’une même région : accès aux soins, à l’école, au très haut débit.\n- **Hexagone / outre-mer** : chômage deux à trois fois plus élevé, vie chère.\n\n## Trois grands objectifs\n- **Corriger les déséquilibres** entre les territoires.\n- **Rendre le territoire compétitif** dans la mondialisation : LGV, ports, aéroports, très haut débit, pôles de compétitivité.\n- **Répondre au défi environnemental** : transports collectifs, énergies renouvelables, limitation de l’étalement urbain.\n\n## Une multitude d’acteurs\n- L’**État**, qui fixe les orientations et finance (autrefois la DATAR, aujourd’hui l’**ANCT**, Agence nationale de la cohésion des territoires).\n- Les **collectivités territoriales** : la **région** (développement économique, transports, lycées), le **département** (routes, collèges, action sociale), la **commune** et l’**intercommunalité** (urbanisme, écoles, déchets).\n- L’**Union européenne**, par ses fonds (**FEDER**) qui cofinancent des projets régionaux.\n- Les **entreprises**, qui investissent, et les **habitants et associations**, consultés lors des enquêtes publiques — parfois opposés aux projets.\n\n> Aucun aménagement d’ampleur n’a un seul auteur : c’est toujours une négociation entre plusieurs échelles.\n\n## Des exemples et leurs limites\nLGV, **Grand Paris Express**, **Action cœur de ville** pour les centres de villes moyennes, **maisons France Services**, plan **France Très Haut Débit**, maisons de santé. Mais un aménagement peut aussi creuser l’écart : une LGV qui met une métropole à deux heures de Paris peut vider les villes qu’elle traverse sans s’y arrêter — c’est l’**effet tunnel**.', 1),
  ('2eca5177-22e7-5c25-bb57-d7f3688d6ba8', '0d896e0b-f92e-567e-a3fb-6306c0b0b0ff', 'Réparer la ville là où elle sépare', E'La **politique de la ville** est l’ensemble des mesures destinées aux quartiers urbains les plus en difficulté. Elle est née dans les années 1980, après les premières émeutes urbaines dans les banlieues.\n\n## Les quartiers concernés\nCe sont les **quartiers prioritaires de la politique de la ville (QPV)** : environ 1 500 quartiers, 5 millions d’habitants. Un seul critère les désigne depuis 2014 — le **revenu des habitants**. On y trouve souvent :\n- des **grands ensembles** construits dans les années 1950-1970, aujourd’hui dégradés ;\n- un **taux de pauvreté** trois fois supérieur à la moyenne nationale ;\n- un chômage élevé, en particulier chez les jeunes ;\n- un **enclavement** : mal desservis, coupés du reste de la ville par une rocade ou une voie ferrée.\n\n## Deux volets d’action\n**1. Le volet urbain : rénover.** L’**ANRU** (Agence nationale pour la rénovation urbaine) démolit les barres les plus dégradées, reconstruit des immeubles plus petits, réaménage les espaces publics, ouvre des rues et amène le **tramway** pour désenclaver.\n\n**2. Le volet humain : accompagner.** Éducation prioritaire (**REP** et **REP+**) avec des classes allégées, dispositifs de réussite éducative, maisons de justice, associations de quartier, **zones franches urbaines** qui exonèrent d’impôts les entreprises qui s’installent.\n\n## L’objectif : la mixité sociale\nLa **loi SRU** impose aux communes d’au moins 3 500 habitants un minimum de **25 % de logements sociaux**, pour que le logement social cesse d’être concentré dans les mêmes communes.\n\n> Rénover les immeubles ne suffit pas : sans emploi, sans école et sans transports, un quartier rénové reste un quartier relégué.\n\n## Un bilan discuté\nLes quartiers ont changé de visage, mais les écarts de revenus et de chômage avec le reste de la ville se sont peu réduits. Beaucoup de communes préfèrent encore payer l’amende que construire des logements sociaux.', 1),
  ('8a3e82bb-6c2f-5ca0-ae7e-ac218a901609', '5f5f3f5f-1797-5381-829b-8fda245c1ba1', 'La France des trois océans', E'La France ne s’arrête pas à l’Hexagone : ses **territoires ultramarins**, répartis dans les trois océans, portent environ **2,8 millions d’habitants** et font d’elle une puissance mondiale.\n\n## Des statuts différents\n- Les cinq **DROM** (départements et régions d’outre-mer) : **Guadeloupe, Martinique, Guyane, La Réunion, Mayotte**. Ce sont des départements français à part entière, et des **régions ultrapériphériques (RUP)** de l’Union européenne.\n- Les **COM** (collectivités d’outre-mer), plus autonomes : Polynésie française, Saint-Pierre-et-Miquelon, Saint-Martin, Saint-Barthélemy, Wallis-et-Futuna.\n- La **Nouvelle-Calédonie**, au statut particulier, et les **TAAF** (Terres australes et antarctiques françaises), sans population permanente.\n\n## Trois contraintes lourdes\n- L’**éloignement** et la **discontinuité territoriale** : des milliers de kilomètres séparent ces territoires de l’Hexagone, ce qui renchérit tout — c’est la **vie chère**.\n- L’**insularité** et l’exiguïté, sauf en Guyane.\n- Les **risques naturels** : cyclones, séismes, volcans (la Soufrière, le Piton de la Fournaise), submersion.\n\nS’y ajoutent un **chômage** deux à trois fois supérieur à celui de l’Hexagone, une forte dépendance aux importations et aux transferts publics.\n\n## De vrais atouts\n- Une **biodiversité** exceptionnelle : l’outre-mer abrite 80 % de la biodiversité française.\n- Le **tourisme**, l’agriculture tropicale (banane, canne à sucre, vanille), la pêche.\n- Le **centre spatial de Kourou**, en Guyane, base de lancement européenne.\n- Une immense **zone économique exclusive (ZEE)** : grâce à l’outre-mer, la France possède le **deuxième domaine maritime du monde**, environ 11 millions de km².\n\n> Sans l’outre-mer, la France serait une puissance européenne ; avec lui, elle est présente dans tous les océans du globe.', 1),
  ('c8878fe5-c475-5fb6-a60f-13eb32154f64', '470832dc-e0a6-54b4-b10d-8a22ce95e228', 'Comment 27 États font un territoire commun', E'L’**Union européenne** réunit **27 États** et environ **450 millions d’habitants**. Elle est née de la volonté d’empêcher le retour de la guerre en Europe.\n\n## Les grandes étapes\n- **1951** : la **CECA** met en commun le charbon et l’acier de six pays, dont la France et l’Allemagne.\n- **1957** : le **traité de Rome** crée la **CEE** — un marché commun à six.\n- **1992** : le **traité de Maastricht** crée l’**Union européenne** et la **citoyenneté européenne**.\n- **2002** : l’**euro** entre en circulation ; il est aujourd’hui la monnaie de 20 États.\n- **2004** : le grand élargissement à l’Est fait entrer dix pays d’un coup.\n- **2020** : le **Brexit** fait sortir le Royaume-Uni — l’Union passe de 28 à 27 membres.\n\n## Un territoire qui s’élargit et s’approfondit\nS’**élargir**, c’est accueillir de nouveaux États (de 6 en 1957 à 27 aujourd’hui, avec des candidats dans les Balkans et en Ukraine). S’**approfondir**, c’est mettre en commun toujours plus de compétences : marché unique, monnaie, frontières, recherche, environnement.\n\n## Ce que l’Union change au quotidien\n- La **libre circulation** des personnes, des marchandises, des services et des capitaux (le **marché unique**).\n- L’espace **Schengen**, où l’on franchit les frontières intérieures sans contrôle.\n- La **citoyenneté européenne** : voter aux élections municipales et européennes dans son pays de résidence, étudier ailleurs avec **Erasmus**, être soigné partout.\n\n## Qui décide ?\n- Le **Parlement européen** (Strasbourg), élu au suffrage universel direct tous les cinq ans.\n- La **Commission européenne** (Bruxelles), qui propose les lois et fait appliquer les traités.\n- Le **Conseil de l’Union européenne** et le **Conseil européen**, où siègent les États.\n\n> L’Union n’est ni un État, ni une simple alliance : les États lui ont transféré une part de leur souveraineté, et gardent le reste.', 1),
  ('fecda087-9d01-50c5-98b9-8702ef431794', 'b330d15a-2c67-5816-8f56-bca0736238c2', 'Un centre, des périphéries, des frontières qui s’effacent', E'L’Union européenne forme un territoire **très inégal** : d’une région à l’autre, la richesse par habitant peut varier du simple au sextuple.\n\n## Un centre : la mégalopole européenne\nUne **dorsale** urbaine et industrielle court de **Londres à Milan**, en passant par les Pays-Bas, la vallée du Rhin et la Suisse — parfois appelée « banane bleue ». On y trouve :\n- les plus fortes densités de population ;\n- les grandes places financières (Francfort, Amsterdam, Paris) ;\n- les plus grands ports d’Europe : **Rotterdam**, Anvers, Hambourg ;\n- les axes de transport les plus chargés.\n\n## Des périphéries multiples\n- Les **périphéries méridionales** (Sud de l’Italie, Grèce, une partie de l’Espagne et du Portugal), touchées par le chômage.\n- Les **périphéries orientales**, entrées en 2004-2013 : elles rattrapent vite leur retard, portées par les investissements industriels, mais restent plus pauvres.\n- Les **régions ultrapériphériques** : DROM français, Açores, Madère, Canaries.\n\n## Ce qui rapproche les territoires\n- La **politique de cohésion** et ses fonds (**FEDER**, Fonds social européen) : environ un tiers du budget de l’Union, dirigé en priorité vers les régions les moins riches.\n- Les **eurorégions** et les programmes transfrontaliers (**Interreg**), qui font coopérer des régions voisines de deux pays.\n- Les **corridors de transport** européens : LGV, autoroutes, tunnels alpins.\n\n> Un habitant de Lille travaille parfois en Belgique, un Alsacien en Allemagne : dans les régions frontalières, la frontière est devenue une ressource plutôt qu’une barrière.\n\n## Des contrastes qui se déplacent\nL’élargissement à l’Est a déplacé le **centre de gravité** de l’Union vers l’est, et des délocalisations d’Ouest en Est ont suivi. Les écarts se réduisent entre pays, mais se creusent souvent **à l’intérieur** de chaque pays, entre capitales et campagnes.', 1),
  ('dfab3d3e-19d5-55f7-acd0-32a2322259be', '53f85f17-1b08-543a-8e26-c9b9568ded36', 'Une puissance commerciale, une puissance politique inachevée', E'Avec 450 millions d’habitants et environ **17 % du PIB mondial**, l’Union européenne est un géant économique. Sa puissance politique, elle, reste très en deçà.\n\n## Une puissance économique de premier rang\n- **Première puissance commerciale du monde** : premier exportateur de services, deuxième exportateur de marchandises.\n- Un **marché unique** de 450 millions de consommateurs, que toute entreprise du monde veut atteindre.\n- L’**euro**, deuxième monnaie de réserve mondiale après le dollar.\n- Des **normes** (sécurité alimentaire, environnement, données personnelles avec le RGPD) que les entreprises étrangères doivent respecter pour vendre en Europe : c’est le pouvoir de la norme.\n\n## Une puissance culturelle et diplomatique réelle\nPremier **pôle touristique** mondial, premier donateur d’**aide publique au développement**, moteur des négociations climatiques (accord de Paris, 2015). L’Union pèse par ses idées et ses règles autant que par ses marchés.\n\n## Mais une puissance politique inachevée\n- Pas d’**armée commune** : la défense repose largement sur l’**OTAN** et sur les armées nationales.\n- Une diplomatie qui exige souvent l’**unanimité des 27** : un seul État peut bloquer une décision.\n- Une **dépendance énergétique** (pétrole, gaz) et technologique (numérique) qui limite sa liberté d’action.\n\n> L’Union pèse par ses marchés et ses normes, beaucoup moins par ses armes.\n\n## Un monde plus concurrentiel\nLa montée de la **Chine** et de l’**Inde**, la rivalité entre la Chine et les États-Unis et le retour de la guerre en Europe avec l’invasion de l’**Ukraine** (2022) obligent l’Union à repenser son autonomie : production de vaccins, de semi-conducteurs, d’énergie, d’armement.', 1),
  ('359b0746-bd2b-56f8-985a-9e348b518386', '7d06202f-144f-56d7-a58b-526573dc5c78', 'Un membre fondateur, un carrefour, une puissance mondiale', E'La France est l’un des **six États fondateurs** de la construction européenne : CECA en 1951, traité de Rome en 1957. Elle en est aujourd’hui la **deuxième économie** et le pays le plus **étendu**.\n\n## Une place centrale dans l’Union\n- **Politique** : avec l’Allemagne, elle forme le « couple franco-allemand », moteur historique des grandes décisions européennes.\n- **Institutionnelle** : le **Parlement européen** siège à **Strasbourg**.\n- **Économique** : premier bénéficiaire de la **PAC**, membre de la zone **euro** et de l’espace **Schengen**.\n- **Territoriale** : ses **régions frontalières** (Nord, Grand Est, Alsace, Savoie) vivent au quotidien avec la Belgique, l’Allemagne, la Suisse, l’Italie et l’Espagne ; des dizaines de milliers de **travailleurs transfrontaliers** franchissent chaque jour la frontière.\n\n## Un carrefour de circulation\nSituée entre l’Europe du Nord et la péninsule Ibérique, entre l’Atlantique et la Méditerranée, la France est traversée par les grands **corridors européens** : LGV vers Londres et Barcelone, tunnels alpins, autoroutes du Rhône et du Rhin, ports du Havre et de Marseille.\n\n## Une puissance mondiale par ses propres moyens\n- Membre **permanent** du Conseil de sécurité de l’**ONU**, avec droit de veto.\n- **Dissuasion nucléaire** et armée projetable.\n- Deuxième **réseau diplomatique** et deuxième **ZEE** du monde, grâce à l’outre-mer.\n- Un fort *soft power* : la **francophonie** (plus de 320 millions de locuteurs), la première fréquentation touristique du monde, un réseau d’instituts culturels et de lycées français sur tous les continents.\n\n> La France agit à deux échelles : seule quand il s’agit de son siège à l’ONU ou de sa défense, à 27 quand il s’agit de commerce, de climat ou de normes.', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('445ae1cb-9e2c-59cc-9699-0f01f702a461'::uuid, 'Quiz — Où vivent les Français ? La ville qui s’étale', 'Histoire-Géographie', '3e', 'Les aires urbaines en France', '862c3561-4f2a-5ad3-ba94-1bdd4a46a895'::uuid),
    ('6dadc070-5e01-5885-b040-238edcd4937b'::uuid, 'Quiz — Des mines fermées aux technopôles', 'Histoire-Géographie', '3e', 'Les espaces productifs : la France industrielle', '052b14e8-f923-5fbe-840f-83e398d6e6f5'::uuid),
    ('11bf05ed-d0b4-51a2-a0c7-9ac554937505'::uuid, 'Quiz — Une agriculture puissante, sous tension', 'Histoire-Géographie', '3e', 'Les espaces productifs : la France agricole', '7b2e8345-f3fc-5f7c-ae86-ab7ad0a003ee'::uuid),
    ('8f481c03-16d1-5fcf-bbfc-ead04026fd01'::uuid, 'Quiz — Le pays des services et le premier pays touristique du monde', 'Histoire-Géographie', '3e', 'Les espaces productifs : la France des services', '38600747-2322-595f-b32a-b14422a4e41b'::uuid),
    ('090615df-51f7-5c5b-a950-7fea5d685d67'::uuid, 'Quiz — La France des campagnes et des montagnes', 'Histoire-Géographie', '3e', 'Les espaces de faible densité', '304004d4-2e67-50e5-a475-b5f0e17e5788'::uuid),
    ('ea4ce6d7-7218-5e6d-8f0f-f7c254ea4e76'::uuid, 'Quiz — Qui transforme le territoire, et pour corriger quoi ?', 'Histoire-Géographie', '3e', 'L’aménagement comme réponse aux inégalités territoriales', 'fd71fcf7-2b42-5ece-b954-bf2c5854a9ac'::uuid),
    ('0a65fb50-47fc-54fb-91d6-548f5e177b3e'::uuid, 'Quiz — Réparer la ville là où elle sépare', 'Histoire-Géographie', '3e', 'La politique de la ville', '2eca5177-22e7-5c25-bb57-d7f3688d6ba8'::uuid),
    ('3326a4f6-5202-5ca2-a284-647e91eadaca'::uuid, 'Quiz — La France des trois océans', 'Histoire-Géographie', '3e', 'Les territoires ultra-marins français', '8a3e82bb-6c2f-5ca0-ae7e-ac218a901609'::uuid),
    ('e6530d3c-908f-5b29-82a3-48afdafd6dc0'::uuid, 'Quiz — Comment 27 États font un territoire commun', 'Histoire-Géographie', '3e', 'L’Union européenne : un territoire en construction', 'c8878fe5-c475-5fb6-a60f-13eb32154f64'::uuid),
    ('5779ecb2-93d4-5fba-ac5d-12aaa81958c2'::uuid, 'Quiz — Un centre, des périphéries, des frontières qui s’effacent', 'Histoire-Géographie', '3e', 'Les contrastes territoriaux à l’intérieur de l’Union européenne', 'fecda087-9d01-50c5-98b9-8702ef431794'::uuid),
    ('a66d7f19-42ca-584d-876f-5b3eda027cd4'::uuid, 'Quiz — Une puissance commerciale, une puissance politique inachevée', 'Histoire-Géographie', '3e', 'L’Europe dans le monde', 'dfab3d3e-19d5-55f7-acd0-32a2322259be'::uuid),
    ('e568f789-0367-5ee3-8fe4-7e37cd05284c'::uuid, 'Quiz — Un membre fondateur, un carrefour, une puissance mondiale', 'Histoire-Géographie', '3e', 'La France dans l’Union européenne', '359b0746-bd2b-56f8-985a-9e348b518386'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('efa6ceba-9e5f-501a-8957-f3d6b9e1ceec'::uuid, '445ae1cb-9e2c-59cc-9699-0f01f702a461'::uuid, 'Que réunit une aire urbaine ?', 'mcq', '["Un pôle urbain et sa couronne périurbaine","Une commune et ses hameaux","Un département et sa préfecture","Une région et ses métropoles"]'::jsonb, 0, 'Le pôle est la zone bâtie en continu, la couronne les communes qui envoient leurs actifs y travailler.', 1),
    ('e9fa5903-05e0-5555-8c81-db77443d0bcb'::uuid, '445ae1cb-9e2c-59cc-9699-0f01f702a461'::uuid, 'À partir de quel seuil d’actifs travaillant dans le pôle une commune entre-t-elle dans la couronne périurbaine ?', 'mcq', '["40 %","10 %","25 %","75 %"]'::jsonb, 0, 'C’est le critère retenu par l’INSEE pour délimiter l’aire urbaine.', 2),
    ('3a7a9168-b3a0-5ea0-9ed7-4b576df3daaa'::uuid, '445ae1cb-9e2c-59cc-9699-0f01f702a461'::uuid, 'Quelle part des Français vit sous l’influence d’une aire urbaine ?', 'mcq', '["Environ 95 %","Environ 50 %","Environ 65 %","Environ 30 %"]'::jsonb, 0, 'Même en habitant à la campagne, on dépend le plus souvent d’une ville pour l’emploi et les services.', 3),
    ('d90ea80e-932c-5daa-823e-9df048ef0083'::uuid, '445ae1cb-9e2c-59cc-9699-0f01f702a461'::uuid, 'Combien d’habitants compte environ l’aire urbaine de Paris ?', 'mcq', '["Environ 13 millions","Environ 2 millions","Environ 6 millions","Environ 20 millions"]'::jsonb, 0, 'Soit près d’un Français sur cinq : aucune autre ville française n’approche ce poids.', 4),
    ('dbfeefdb-2e97-5bd3-b340-9cfe95d8f749'::uuid, '445ae1cb-9e2c-59cc-9699-0f01f702a461'::uuid, 'Qu’appelle-t-on la métropolisation ?', 'mcq', '["La concentration des hommes, des richesses et des fonctions de commandement dans les grandes villes","La construction de villes nouvelles","Le départ des habitants vers les campagnes","La fusion de plusieurs communes en une seule"]'::jsonb, 0, 'Sièges sociaux, universités, hôpitaux de pointe et aéroports s’y regroupent.', 5),
    ('e507e83d-50bf-5100-9dad-2965b4093864'::uuid, '445ae1cb-9e2c-59cc-9699-0f01f702a461'::uuid, 'Que sont les mobilités pendulaires ?', 'mcq', '["Les déplacements quotidiens entre le domicile et le travail","Les migrations saisonnières des touristes","Les déménagements d’une région à l’autre","Les voyages scolaires"]'::jsonb, 0, 'Elles s’allongent à mesure que la ville s’étale.', 6),
    ('85e884d2-790e-5892-8c28-a7279465c840'::uuid, '445ae1cb-9e2c-59cc-9699-0f01f702a461'::uuid, 'Qu’est-ce que la gentrification d’un centre-ville ?', 'mcq', '["L’arrivée d’habitants aisés qui fait monter les prix et repousse les plus modestes","La destruction des immeubles anciens","Le départ des commerces vers la périphérie","La piétonnisation des rues"]'::jsonb, 0, 'Rénovation et hausse des loyers vont de pair.', 7),
    ('c1b56ad7-abb5-55f5-8d11-a8fe71abb553'::uuid, '445ae1cb-9e2c-59cc-9699-0f01f702a461'::uuid, 'Toutes les villes françaises profitent également de la métropolisation.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Les métropoles gagnent habitants et emplois qualifiés, quand beaucoup de villes moyennes perdent commerces et services.', 8),
    ('d838c59e-f738-55c9-9ec2-86515b4e1abe'::uuid, '6dadc070-5e01-5885-b040-238edcd4937b'::uuid, 'Qu’est-ce qu’un espace productif ?', 'mcq', '["Un espace aménagé pour produire des richesses","Un espace protégé de toute activité humaine","Un quartier réservé aux logements","Une zone uniquement agricole"]'::jsonb, 0, 'Il peut être industriel, agricole ou de services.', 1),
    ('53ea55f2-01a7-5032-96ba-dbfc75cbcca6'::uuid, '6dadc070-5e01-5885-b040-238edcd4937b'::uuid, 'Qu’appelle-t-on la désindustrialisation ?', 'mcq', '["La perte massive d’emplois industriels depuis les années 1970","La création de nouvelles usines en centre-ville","Le passage de l’artisanat à l’industrie","L’automatisation des exploitations agricoles"]'::jsonb, 0, 'Concurrence mondiale, délocalisations et automatisation en sont les causes.', 2),
    ('826b22b6-7149-5222-8831-79eba7d485e5'::uuid, '6dadc070-5e01-5885-b040-238edcd4937b'::uuid, 'Que reste-t-il des anciennes usines fermées dans le Nord et en Lorraine ?', 'mcq', '["Des friches industrielles","Des zones franches","Des technopôles","Des ZIP"]'::jsonb, 0, 'Terrains et bâtiments abandonnés, souvent en attente de reconversion.', 3),
    ('4f567842-73d3-5d35-a15f-d687091690a9'::uuid, '6dadc070-5e01-5885-b040-238edcd4937b'::uuid, 'Qu’est-ce qu’un technopôle ?', 'mcq', '["Un parc associant entreprises de haute technologie, laboratoires et universités","Un port spécialisé dans les conteneurs","Une zone commerciale de périphérie","Un quartier d’affaires de centre-ville"]'::jsonb, 0, 'Sophia Antipolis, près de Nice, en est l’exemple pionnier en France.', 4),
    ('40f335ad-aaad-5662-b77a-c9f22e92105a'::uuid, '6dadc070-5e01-5885-b040-238edcd4937b'::uuid, 'Que désigne une ZIP ?', 'mcq', '["Une zone industrialo-portuaire","Une zone d’intérêt patrimonial","Une zone d’installation prioritaire","Une zone d’industrie protégée"]'::jsonb, 0, 'Dunkerque, Le Havre et Marseille-Fos en sont les principales en France.', 5),
    ('b4183007-5df9-54d6-87ca-88f0211562c8'::uuid, '6dadc070-5e01-5885-b040-238edcd4937b'::uuid, 'Pourquoi les industries lourdes s’installent-elles sur les littoraux ?', 'mcq', '["Pour être au contact des ports qui importent les matières premières","Parce que la main-d’œuvre y est moins chère","Parce que l’État y interdit toute autre activité","Parce que le climat y est plus doux"]'::jsonb, 0, 'C’est la littoralisation : le littoral devient une interface avec le monde.', 6),
    ('4c7d232f-85e5-542e-bc05-3e9fe215eada'::uuid, '6dadc070-5e01-5885-b040-238edcd4937b'::uuid, 'Quelle métropole est le cœur de l’industrie aéronautique française ?', 'mcq', '["Toulouse","Lille","Strasbourg","Rennes"]'::jsonb, 0, 'Airbus et l’Aerospace Valley y regroupent constructeurs et sous-traitants.', 7),
    ('04e86a43-49a1-54cf-bb8e-5b5670ab73eb'::uuid, '6dadc070-5e01-5885-b040-238edcd4937b'::uuid, 'La désindustrialisation signifie que la France ne produit plus rien.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Aéronautique, nucléaire, pharmacie, luxe et agroalimentaire restent des industries de pointe très exportatrices.', 8),
    ('321dce08-63a5-5514-b2f8-e68cebda0c66'::uuid, '11bf05ed-d0b4-51a2-a0c7-9ac554937505'::uuid, 'Quelle place occupe la France dans l’agriculture européenne ?', 'mcq', '["Elle est le premier producteur agricole de l’Union européenne","Elle est le dernier producteur de l’Union","Elle n’exporte aucun produit agricole","Elle importe la totalité de ses céréales"]'::jsonb, 0, 'Et pourtant l’agriculture n’occupe plus que 2 % des actifs.', 1),
    ('cad47117-93fc-5f1d-9776-5479be32ae4c'::uuid, '11bf05ed-d0b4-51a2-a0c7-9ac554937505'::uuid, 'Qu’est-ce qu’une agriculture productiviste ?', 'mcq', '["Une agriculture qui cherche le rendement maximal par la mécanisation et les intrants","Une agriculture sans engrais ni pesticides","Une agriculture destinée à la seule consommation familiale","Une agriculture pratiquée uniquement en montagne"]'::jsonb, 0, 'Mécanisation, engrais, irrigation et spécialisation régionale en sont les moyens.', 2),
    ('8312afea-80a9-590c-8481-77576b093697'::uuid, '11bf05ed-d0b4-51a2-a0c7-9ac554937505'::uuid, 'Quel paysage agricole domine la Beauce ?', 'mcq', '["L’openfield, de vastes champs ouverts céréaliers","Le bocage, quadrillé de haies","La vigne en terrasses","La forêt de conifères"]'::jsonb, 0, 'C’est le grenier à blé du Bassin parisien.', 3),
    ('5c4e4573-76dc-5e95-b671-ec5cc869a87a'::uuid, '11bf05ed-d0b4-51a2-a0c7-9ac554937505'::uuid, 'Qu’est-ce que l’élevage hors-sol ?', 'mcq', '["Un élevage en bâtiment, où les animaux ne pâturent pas","Un élevage pratiqué en altitude","Un élevage sans aucune alimentation industrielle","Un élevage nomade"]'::jsonb, 0, 'Il est très développé en Bretagne pour les porcs et les volailles.', 4),
    ('bfcabb39-6b36-5977-bd7f-410476be2912'::uuid, '11bf05ed-d0b4-51a2-a0c7-9ac554937505'::uuid, 'Que signifie la PAC ?', 'mcq', '["La Politique agricole commune","Le Programme agricole des campagnes","Le Plan d’aide aux cultures","La Production agricole certifiée"]'::jsonb, 0, 'Elle verse des aides européennes aux agriculteurs depuis 1962.', 5),
    ('57c65a5c-7163-5e5e-b89c-ef68bfada571'::uuid, '11bf05ed-d0b4-51a2-a0c7-9ac554937505'::uuid, 'Que garantit un label AOP ?', 'mcq', '["L’origine géographique et le savoir-faire d’un produit","L’absence totale de transformation","Un prix de vente maximal","Une production entièrement exportée"]'::jsonb, 0, 'AOP, AOC et Label rouge misent sur la qualité plutôt que sur le volume.', 6),
    ('67f0917f-41c3-5d64-8175-ba29cd2db549'::uuid, '11bf05ed-d0b4-51a2-a0c7-9ac554937505'::uuid, 'Quel problème environnemental l’élevage intensif provoque-t-il en Bretagne ?', 'mcq', '["La pollution aux nitrates et les algues vertes sur les littoraux","La désertification des sols","La fonte des glaciers","Les pluies acides venues d’Allemagne"]'::jsonb, 0, 'Le lisier épandu enrichit les eaux en nitrates jusqu’à la mer.', 7),
    ('46fd7bc8-0a14-502d-aaff-af37c810ee83'::uuid, '11bf05ed-d0b4-51a2-a0c7-9ac554937505'::uuid, 'Un circuit court désigne une vente qui passe par un maximum d’intermédiaires.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est l’inverse : il rapproche le producteur du consommateur, avec un intermédiaire au plus.', 8),
    ('a3e88b1d-b27b-5c91-86fc-d7334d01e945'::uuid, '8f481c03-16d1-5fcf-bbfc-ead04026fd01'::uuid, 'Quelle part des actifs français travaille dans les services ?', 'mcq', '["Près de 80 %","Environ 25 %","Environ 50 %","Moins de 10 %"]'::jsonb, 0, 'C’est la tertiarisation de l’économie française.', 1),
    ('dbe52929-3ca8-584f-9c37-05b9b07944ff'::uuid, '8f481c03-16d1-5fcf-bbfc-ead04026fd01'::uuid, 'Qu’est-ce qu’un service non marchand ?', 'mcq', '["Un service financé par l’impôt, comme l’école ou l’hôpital public","Un service vendu à un prix libre","Un service réservé aux entreprises","Un service exporté à l’étranger"]'::jsonb, 0, 'Il ne se vend pas : il est assuré par la collectivité.', 2),
    ('c78d491c-a856-5273-9a6c-a73985e18b21'::uuid, '8f481c03-16d1-5fcf-bbfc-ead04026fd01'::uuid, 'Où se concentrent les services à haute valeur ajoutée ?', 'mcq', '["Dans les métropoles, et d’abord à Paris","Dans les espaces de faible densité","Dans les zones industrialo-portuaires","Dans les stations de montagne"]'::jsonb, 0, 'Finance, conseil, recherche et médias suivent la métropolisation.', 3),
    ('3bc193ae-af04-5dbc-a51b-9fc27da9b518'::uuid, '8f481c03-16d1-5fcf-bbfc-ead04026fd01'::uuid, 'Combien de touristes étrangers la France accueille-t-elle chaque année ?', 'mcq', '["Environ 90 millions","Environ 20 millions","Environ 45 millions","Environ 200 millions"]'::jsonb, 0, 'C’est la première destination touristique du monde.', 4),
    ('4859e4d2-fbde-5469-95db-187fe41e660d'::uuid, '8f481c03-16d1-5fcf-bbfc-ead04026fd01'::uuid, 'Quelle part du PIB français le tourisme représente-t-il environ ?', 'mcq', '["Près de 8 %","Près de 25 %","Moins de 1 %","Près de 40 %"]'::jsonb, 0, 'Un poids considérable, très inégalement réparti sur le territoire.', 5),
    ('ccf3119e-5966-54ca-8736-97223b1d99a3'::uuid, '8f481c03-16d1-5fcf-bbfc-ead04026fd01'::uuid, 'Quel espace touristique correspond à la Côte d’Azur ?', 'mcq', '["Le tourisme balnéaire","Le tourisme vert","Le tourisme de montagne","Le tourisme d’affaires exclusivement"]'::jsonb, 0, 'Le littoral méditerranéen est le premier espace balnéaire français.', 6),
    ('bcf53cf5-e7a3-599e-bdb9-f4bb61b15d5b'::uuid, '8f481c03-16d1-5fcf-bbfc-ead04026fd01'::uuid, 'Quelle est une limite majeure des aménagements touristiques ?', 'mcq', '["Ils bétonnent les littoraux et fragilisent les milieux de montagne","Ils ne créent jamais d’emplois","Ils font disparaître les services publics","Ils sont interdits par l’Union européenne"]'::jsonb, 0, 'Le surtourisme menace ce qui attire les visiteurs.', 7),
    ('340b420a-41d7-5cd6-8bb7-e0384d8bd9cf'::uuid, '8f481c03-16d1-5fcf-bbfc-ead04026fd01'::uuid, 'Les emplois du tourisme sont majoritairement stables et à l’année.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Beaucoup sont saisonniers, concentrés sur quelques semaines d’été ou d’hiver.', 8),
    ('4587db93-a259-526d-9533-99d89fdb1968'::uuid, '090615df-51f7-5c5b-a950-7fea5d685d67'::uuid, 'En dessous de quelle densité parle-t-on d’espace de faible densité ?', 'mcq', '["30 habitants par km²","100 habitants par km²","5 habitants par km²","250 habitants par km²"]'::jsonb, 0, 'Ces espaces couvrent près de la moitié du territoire français.', 1),
    ('b71e37cd-ca71-5d01-bf87-1079459f3908'::uuid, '090615df-51f7-5c5b-a950-7fea5d685d67'::uuid, 'Quelle part de la population française vit dans les espaces de faible densité ?', 'mcq', '["Environ 6 %","Environ 30 %","Environ 20 %","Environ 45 %"]'::jsonb, 0, 'Beaucoup d’espace, très peu d’habitants.', 2),
    ('8b3a8c50-0ba8-5b47-89f0-dcdd3ae5cd3c'::uuid, '090615df-51f7-5c5b-a950-7fea5d685d67'::uuid, 'Comment appelle-t-on la bande de faibles densités qui traverse la France des Ardennes aux Landes ?', 'mcq', '["La diagonale des faibles densités","Le croissant fertile","La dorsale européenne","Le sillon rhodanien"]'::jsonb, 0, 'On l’appelait autrefois « diagonale du vide », une expression aujourd’hui contestée.', 3),
    ('7b591b4d-deae-5f6f-b8ff-24852cecc284'::uuid, '090615df-51f7-5c5b-a950-7fea5d685d67'::uuid, 'Qu’est-ce qu’un désert médical ?', 'mcq', '["Un territoire où l’accès à un médecin est très difficile","Une zone sans pharmacie autorisée","Un hôpital fermé pendant l’été","Une région sans épidémie"]'::jsonb, 0, 'Conséquence directe du départ des services dans les espaces peu peuplés.', 4),
    ('6b051b8c-9cb0-5f44-b959-434f357c15be'::uuid, '090615df-51f7-5c5b-a950-7fea5d685d67'::uuid, 'Qui sont les néoruraux ?', 'mcq', '["Des citadins venus s’installer à la campagne","Des agriculteurs partis vivre en ville","Des touristes de passage","Des habitants nés au village et qui n’en sont jamais partis"]'::jsonb, 0, 'Le télétravail a accéléré ces installations depuis 2020.', 5),
    ('143e196d-1e21-52fd-8075-7a07f632b6f9'::uuid, '090615df-51f7-5c5b-a950-7fea5d685d67'::uuid, 'Quel atout énergétique portent souvent les espaces de faible densité ?', 'mcq', '["Les énergies renouvelables : éolien, solaire, hydroélectricité, biomasse","Le raffinage du pétrole","La production de gaz naturel","Le stockage des déchets nucléaires exclusivement"]'::jsonb, 0, 'L’espace disponible et le relief y sont des ressources.', 6),
    ('135ee7a2-20b5-55cb-82bf-5b1cfa55f0c8'::uuid, '090615df-51f7-5c5b-a950-7fea5d685d67'::uuid, 'Quel outil protège la biodiversité et le patrimoine de ces espaces ?', 'mcq', '["Les parcs naturels régionaux et les parcs nationaux","Les zones franches urbaines","Les pôles de compétitivité","Les zones industrialo-portuaires"]'::jsonb, 0, 'Ils concilient protection des milieux et développement local.', 7),
    ('2f5f7519-1694-5cc1-86d9-273ab01cd80f'::uuid, '090615df-51f7-5c5b-a950-7fea5d685d67'::uuid, 'Tous les espaces de faible densité perdent des habitants.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Les campagnes proches des villes ou touristiques en gagnent ; les montagnes isolées en perdent.', 8),
    ('514835b2-1213-53c2-b48f-e35a84e9a5a2'::uuid, 'ea4ce6d7-7218-5e6d-8f0f-f7c254ea4e76'::uuid, 'Qu’est-ce qu’aménager le territoire ?', 'mcq', '["Le transformer volontairement pour le rendre plus attractif, accessible ou juste","Le laisser évoluer sans intervention","Le diviser en nouvelles régions administratives","Le protéger de toute construction"]'::jsonb, 0, 'C’est une action publique volontaire, menée à plusieurs échelles.', 1),
    ('cd566b57-b2dc-5f6b-8a70-5e398df30a8b'::uuid, 'ea4ce6d7-7218-5e6d-8f0f-f7c254ea4e76'::uuid, 'Quelle agence de l’État conduit aujourd’hui la politique d’aménagement ?', 'mcq', '["L’ANCT, Agence nationale de la cohésion des territoires","L’INSEE","La Banque de France","L’Agence spatiale européenne"]'::jsonb, 0, 'Elle a succédé à la DATAR, créée en 1963.', 2),
    ('58ef572d-3229-5481-9467-4b523a9f5b1e'::uuid, 'ea4ce6d7-7218-5e6d-8f0f-f7c254ea4e76'::uuid, 'Quelle collectivité est chef de file du développement économique et des transports ?', 'mcq', '["La région","La commune","Le département","L’intercommunalité"]'::jsonb, 0, 'Le département gère surtout routes, collèges et action sociale.', 3),
    ('0eec111b-a698-5d65-89b0-5f666bcaf10d'::uuid, 'ea4ce6d7-7218-5e6d-8f0f-f7c254ea4e76'::uuid, 'Quel fonds européen cofinance des projets d’aménagement régionaux ?', 'mcq', '["Le FEDER","La PAC","Le FMI","Le fonds Schengen"]'::jsonb, 0, 'Le Fonds européen de développement régional soutient la politique de cohésion.', 4),
    ('1a2ad7b5-790c-557a-b8d9-f581ebff81c7'::uuid, 'ea4ce6d7-7218-5e6d-8f0f-f7c254ea4e76'::uuid, 'À quoi sert le programme Action cœur de ville ?', 'mcq', '["À réhabiliter les centres des villes moyennes désertés par le commerce","À agrandir les métropoles régionales","À construire des zones commerciales périphériques","À financer les stations de ski"]'::jsonb, 0, 'Logement, commerce et services publics y sont traités ensemble.', 5),
    ('2d097adc-8104-516d-bb47-5788aa44d4f0'::uuid, 'ea4ce6d7-7218-5e6d-8f0f-f7c254ea4e76'::uuid, 'Quel plan vise à apporter la fibre optique sur tout le territoire ?', 'mcq', '["Le plan France Très Haut Débit","Le plan Marshall","Le plan Vigipirate","Le plan Grand Froid"]'::jsonb, 0, 'La fracture numérique est devenue une inégalité territoriale majeure.', 6),
    ('da8c8f79-3247-576b-841a-f866370fd2f3'::uuid, 'ea4ce6d7-7218-5e6d-8f0f-f7c254ea4e76'::uuid, 'Qu’est-ce que l’effet tunnel d’une ligne à grande vitesse ?', 'mcq', '["La LGV traverse des territoires sans s’y arrêter, et peut les affaiblir","La LGV passe sous une montagne","La LGV double le trafic des gares intermédiaires","La LGV supprime toutes les lignes régionales"]'::jsonb, 0, 'Un aménagement peut creuser l’écart qu’il prétend réduire.', 7),
    ('de018158-4487-50d7-b9d5-5f8400e04ee5'::uuid, 'ea4ce6d7-7218-5e6d-8f0f-f7c254ea4e76'::uuid, 'L’aménagement du territoire est décidé par l’État seul.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'État, collectivités, Union européenne, entreprises et habitants y prennent part.', 8),
    ('7c347b26-2938-538e-9f1b-ab2414ef9d48'::uuid, '0a65fb50-47fc-54fb-91d6-548f5e177b3e'::uuid, 'Que désigne le sigle QPV ?', 'mcq', '["Quartier prioritaire de la politique de la ville","Quartier public de valorisation","Quartier péri-urbain de veille","Quartier protégé et vert"]'::jsonb, 0, 'Environ 1 500 quartiers et 5 millions d’habitants sont concernés.', 1),
    ('45b80c10-defd-5a11-8f09-d736db099da2'::uuid, '0a65fb50-47fc-54fb-91d6-548f5e177b3e'::uuid, 'Quel critère sert depuis 2014 à désigner un quartier prioritaire ?', 'mcq', '["Le revenu des habitants","La densité de population","L’âge des bâtiments","La distance au centre-ville"]'::jsonb, 0, 'Un critère unique, qui remplace les zonages superposés d’avant.', 2),
    ('6d2b72c0-bd73-5095-be40-53223e00c3bb'::uuid, '0a65fb50-47fc-54fb-91d6-548f5e177b3e'::uuid, 'Que fait l’ANRU ?', 'mcq', '["Elle démolit, reconstruit et désenclave les grands ensembles","Elle finance les exploitations agricoles","Elle gère les parcs nationaux","Elle construit les lignes à grande vitesse"]'::jsonb, 0, 'Rénovation des immeubles et réaménagement des espaces publics.', 3),
    ('16b38728-fe97-5679-a547-9d9eceabcf88'::uuid, '0a65fb50-47fc-54fb-91d6-548f5e177b3e'::uuid, 'Que désignent les sigles REP et REP+ ?', 'mcq', '["Les réseaux d’éducation prioritaire","Les régions économiques prioritaires","Les réseaux express parisiens","Les réserves écologiques protégées"]'::jsonb, 0, 'Classes allégées et moyens renforcés dans les établissements concernés.', 4),
    ('fd53f78c-aa68-50d5-8682-1eae46215c60'::uuid, '0a65fb50-47fc-54fb-91d6-548f5e177b3e'::uuid, 'Qu’est-ce qu’une zone franche urbaine ?', 'mcq', '["Un quartier où les entreprises qui s’installent sont exonérées d’impôts","Un quartier interdit à la circulation automobile","Une zone commerciale de périphérie","Un quartier entièrement piétonnier"]'::jsonb, 0, 'L’objectif est d’y ramener de l’emploi.', 5),
    ('efa75b96-a86d-52e9-b445-4f3b6b91c5ae'::uuid, '0a65fb50-47fc-54fb-91d6-548f5e177b3e'::uuid, 'Quel pourcentage de logements sociaux la loi SRU impose-t-elle aux communes concernées ?', 'mcq', '["25 %","10 %","50 %","5 %"]'::jsonb, 0, 'Pour éviter que le logement social reste concentré dans les mêmes communes.', 6),
    ('543cc99c-fc7a-5fbe-a50c-af71d810298d'::uuid, '0a65fb50-47fc-54fb-91d6-548f5e177b3e'::uuid, 'Quel aménagement sert souvent à désenclaver un quartier prioritaire ?', 'mcq', '["L’arrivée du tramway et l’ouverture de nouvelles rues","La construction d’une rocade supplémentaire","La fermeture des commerces de proximité","L’installation d’une zone industrialo-portuaire"]'::jsonb, 0, 'L’enclavement est l’une des causes majeures de la relégation.', 7),
    ('957a2f5b-c31e-50b2-9347-2ecbdb3de78d'::uuid, '0a65fb50-47fc-54fb-91d6-548f5e177b3e'::uuid, 'La politique de la ville a fait disparaître les écarts entre les quartiers prioritaires et le reste de la ville.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Le bâti a changé, mais les écarts de revenus et de chômage se sont peu réduits.', 8),
    ('ae551d88-49f7-5b24-bb3e-c628a4443716'::uuid, '3326a4f6-5202-5ca2-a284-647e91eadaca'::uuid, 'Combien de DROM la France compte-t-elle ?', 'mcq', '["Cinq","Trois","Sept","Dix"]'::jsonb, 0, 'Guadeloupe, Martinique, Guyane, La Réunion et Mayotte.', 1),
    ('c63a9de7-f470-5fd3-80ee-0174d74d584a'::uuid, '3326a4f6-5202-5ca2-a284-647e91eadaca'::uuid, 'Qu’est-ce qu’une région ultrapériphérique (RUP) ?', 'mcq', '["Un territoire ultramarin qui fait partie de l’Union européenne","Un territoire totalement indépendant de la France","Une région frontalière de l’Hexagone","Une réserve naturelle protégée par l’ONU"]'::jsonb, 0, 'Les DROM sont à ce titre éligibles aux fonds européens.', 2),
    ('1648b583-aed1-5b28-be4e-29ab50fa7456'::uuid, '3326a4f6-5202-5ca2-a284-647e91eadaca'::uuid, 'Qu’appelle-t-on la discontinuité territoriale ?', 'mcq', '["Le fait que ces territoires soient séparés de l’Hexagone par des milliers de kilomètres","Le morcellement des parcelles agricoles","L’absence de routes entre deux villes","La rupture d’un câble sous-marin"]'::jsonb, 0, 'Elle renchérit les transports et explique en partie la vie chère.', 3),
    ('e15dc4f6-fd7c-57de-b941-0561a2153864'::uuid, '3326a4f6-5202-5ca2-a284-647e91eadaca'::uuid, 'Quel volcan est situé à La Réunion ?', 'mcq', '["Le Piton de la Fournaise","La Soufrière","La montagne Pelée","Le Stromboli"]'::jsonb, 0, 'La Soufrière est en Guadeloupe, la montagne Pelée en Martinique.', 4),
    ('d7821cef-5f4d-5465-bb2c-ce75b4b12f0a'::uuid, '3326a4f6-5202-5ca2-a284-647e91eadaca'::uuid, 'Où se trouve le centre spatial européen de lancement ?', 'mcq', '["À Kourou, en Guyane","À Papeete, en Polynésie","À Saint-Denis, à La Réunion","À Nouméa, en Nouvelle-Calédonie"]'::jsonb, 0, 'Sa proximité de l’équateur facilite les lancements.', 5),
    ('1dc5cf97-5d79-5c02-a5b4-0e35dbe901e7'::uuid, '3326a4f6-5202-5ca2-a284-647e91eadaca'::uuid, 'Quelle part de la biodiversité française l’outre-mer abrite-t-il ?', 'mcq', '["Environ 80 %","Environ 10 %","Environ 30 %","Environ 50 %"]'::jsonb, 0, 'Récifs coralliens, forêt amazonienne et espèces endémiques.', 6),
    ('64ad7e8b-37a6-5d32-95fc-726f96150638'::uuid, '3326a4f6-5202-5ca2-a284-647e91eadaca'::uuid, 'Grâce à l’outre-mer, quel rang la France occupe-t-elle pour son domaine maritime ?', 'mcq', '["Le deuxième rang mondial","Le premier rang mondial","Le cinquième rang mondial","Le dixième rang mondial"]'::jsonb, 0, 'Environ 11 millions de km² de zone économique exclusive.', 7),
    ('5da8d952-4249-5b90-aeda-c29d6af3b42f'::uuid, '3326a4f6-5202-5ca2-a284-647e91eadaca'::uuid, 'Le chômage dans les DROM est comparable à celui de l’Hexagone.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il y est deux à trois fois plus élevé, avec une vie plus chère.', 8),
    ('eafd0448-289e-51e6-b962-a7e233514ae5'::uuid, 'e6530d3c-908f-5b29-82a3-48afdafd6dc0'::uuid, 'Combien d’États membres compte l’Union européenne depuis 2020 ?', 'mcq', '["27","25","28","30"]'::jsonb, 0, 'Le Brexit a fait sortir le Royaume-Uni en 2020.', 1),
    ('3e4e2ca9-1e75-5b82-b3ae-a9612b4f4dbf'::uuid, 'e6530d3c-908f-5b29-82a3-48afdafd6dc0'::uuid, 'Quel traité de 1957 crée le marché commun ?', 'mcq', '["Le traité de Rome","Le traité de Maastricht","Le traité de Lisbonne","Le traité de Versailles"]'::jsonb, 0, 'Il donne naissance à la CEE, à six États.', 2),
    ('1732bf8d-e4e9-5185-beb8-19dce120c2e3'::uuid, 'e6530d3c-908f-5b29-82a3-48afdafd6dc0'::uuid, 'Que crée le traité de Maastricht en 1992 ?', 'mcq', '["L’Union européenne et la citoyenneté européenne","La CECA","L’espace Schengen","L’OTAN"]'::jsonb, 0, 'Il pose aussi les bases de la monnaie unique.', 3),
    ('65ad9f78-a895-5b82-af89-646823a811fc'::uuid, 'e6530d3c-908f-5b29-82a3-48afdafd6dc0'::uuid, 'En quelle année l’euro entre-t-il en circulation ?', 'mcq', '["2002","1992","1999","2010"]'::jsonb, 0, 'Il est aujourd’hui la monnaie de 20 des 27 États membres.', 4),
    ('c34b72c2-65b6-57b4-ac42-98ba2f34f502'::uuid, 'e6530d3c-908f-5b29-82a3-48afdafd6dc0'::uuid, 'Qu’est-ce que l’espace Schengen ?', 'mcq', '["Un espace où l’on franchit les frontières intérieures sans contrôle","La zone qui utilise l’euro","Le siège du Parlement européen","La zone de libre-échange avec les États-Unis"]'::jsonb, 0, 'Il ne se confond ni avec l’UE ni avec la zone euro.', 5),
    ('b237116e-bdf8-5e2e-b0fa-b0c91e6a301b'::uuid, 'e6530d3c-908f-5b29-82a3-48afdafd6dc0'::uuid, 'Quelle institution européenne est élue au suffrage universel direct ?', 'mcq', '["Le Parlement européen","La Commission européenne","Le Conseil européen","La Cour de justice"]'::jsonb, 0, 'Les citoyens le renouvellent tous les cinq ans ; il siège à Strasbourg.', 6),
    ('705bfd27-55b5-5e71-828e-67d7fc44ea36'::uuid, 'e6530d3c-908f-5b29-82a3-48afdafd6dc0'::uuid, 'Quel programme permet aux étudiants d’étudier dans un autre pays de l’Union ?', 'mcq', '["Erasmus","Schengen","Interreg","Horizon"]'::jsonb, 0, 'C’est l’une des expériences les plus concrètes de la citoyenneté européenne.', 7),
    ('90245107-647a-5694-b908-3f65924190b7'::uuid, 'e6530d3c-908f-5b29-82a3-48afdafd6dc0'::uuid, 'Élargir l’Union et l’approfondir désignent la même chose.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'S’élargir, c’est accueillir de nouveaux États ; s’approfondir, c’est mettre en commun davantage de compétences.', 8),
    ('5f73182a-dadb-502f-b7fc-4cf7d3045ce7'::uuid, '5779ecb2-93d4-5fba-ac5d-12aaa81958c2'::uuid, 'Comment nomme-t-on la dorsale urbaine et industrielle qui va de Londres à Milan ?', 'mcq', '["La mégalopole européenne","La diagonale du vide","Le croissant fertile","L’arc atlantique"]'::jsonb, 0, 'On l’a aussi surnommée la « banane bleue ».', 1),
    ('e7d7824d-5698-5310-9efa-6180c5cd3cc2'::uuid, '5779ecb2-93d4-5fba-ac5d-12aaa81958c2'::uuid, 'Quel est le plus grand port de l’Union européenne ?', 'mcq', '["Rotterdam","Marseille","Gênes","Le Pirée"]'::jsonb, 0, 'Aux Pays-Bas, à l’embouchure du Rhin.', 2),
    ('6ca1e4a6-af4d-5236-8fb4-c1fa4c8bb865'::uuid, '5779ecb2-93d4-5fba-ac5d-12aaa81958c2'::uuid, 'Quelles régions ont rejoint l’Union lors du grand élargissement de 2004 ?', 'mcq', '["Les pays d’Europe centrale et orientale","Les pays scandinaves","Les pays du Maghreb","Les îles britanniques"]'::jsonb, 0, 'Dix pays sont entrés d’un coup, dont la Pologne et la Hongrie.', 3),
    ('03a2dee5-1254-55a2-98ee-8db46c9e6993'::uuid, '5779ecb2-93d4-5fba-ac5d-12aaa81958c2'::uuid, 'Que finance la politique de cohésion de l’Union ?', 'mcq', '["La réduction des écarts de développement entre régions","La défense commune","Les aides aux agriculteurs uniquement","La construction du Parlement européen"]'::jsonb, 0, 'Elle mobilise environ un tiers du budget européen.', 4),
    ('775ddb48-7457-5d64-a352-bca510317f21'::uuid, '5779ecb2-93d4-5fba-ac5d-12aaa81958c2'::uuid, 'À quoi servent les programmes Interreg et les eurorégions ?', 'mcq', '["À faire coopérer des régions voisines situées de part et d’autre d’une frontière","À fermer les frontières intérieures","À financer les capitales européennes","À sélectionner les nouveaux États membres"]'::jsonb, 0, 'Transports, santé et emploi y sont pensés à deux pays.', 5),
    ('4d49cd32-ca7d-5e67-a5ed-7aacdb50bd13'::uuid, '5779ecb2-93d4-5fba-ac5d-12aaa81958c2'::uuid, 'Quelles sont les régions ultrapériphériques de l’Union ?', 'mcq', '["Les DROM français, les Açores, Madère et les Canaries","Les pays candidats des Balkans","Les régions frontalières de la Russie","Les capitales insulaires de la Méditerranée"]'::jsonb, 0, 'Éloignées du continent mais pleinement européennes.', 6),
    ('a8aaa96d-8820-5a45-a7fc-ff9650422de5'::uuid, '5779ecb2-93d4-5fba-ac5d-12aaa81958c2'::uuid, 'Quel effet l’élargissement à l’Est a-t-il eu sur le territoire européen ?', 'mcq', '["Il a déplacé le centre de gravité de l’Union vers l’est","Il a vidé les pays de l’Est de toute industrie","Il a supprimé la politique de cohésion","Il a fait sortir plusieurs États de l’Union"]'::jsonb, 0, 'Des délocalisations d’Ouest en Est ont suivi.', 7),
    ('32e94527-badb-5766-a112-2db0022b2dcf'::uuid, '5779ecb2-93d4-5fba-ac5d-12aaa81958c2'::uuid, 'Les écarts de richesse entre régions européennes sont aujourd’hui négligeables.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'D’une région à l’autre, le PIB par habitant peut varier du simple au sextuple.', 8),
    ('2d5836c1-e260-5c31-8318-e0bcaa2c48cc'::uuid, 'a66d7f19-42ca-584d-876f-5b3eda027cd4'::uuid, 'Quel rang commercial l’Union européenne occupe-t-elle dans le monde ?', 'mcq', '["Le premier rang","Le troisième rang","Le cinquième rang","Le dixième rang"]'::jsonb, 0, 'Premier exportateur de services, deuxième de marchandises.', 1),
    ('6596c0b5-da29-5cd2-9582-53fe16463dd9'::uuid, 'a66d7f19-42ca-584d-876f-5b3eda027cd4'::uuid, 'Quelle place occupe l’euro parmi les monnaies mondiales ?', 'mcq', '["La deuxième monnaie de réserve, après le dollar","La première monnaie de réserve","La cinquième monnaie de réserve","Une monnaie sans usage hors d’Europe"]'::jsonb, 0, 'Il donne à l’Union un poids monétaire international.', 2),
    ('64039f25-4788-5962-aac2-01f2c37f064e'::uuid, 'a66d7f19-42ca-584d-876f-5b3eda027cd4'::uuid, 'Que montre l’exemple du RGPD sur les données personnelles ?', 'mcq', '["Que les normes européennes s’imposent aux entreprises étrangères qui veulent vendre en Europe","Que l’Union possède une armée commune","Que l’Union fixe les prix mondiaux","Que l’Union interdit le commerce extérieur"]'::jsonb, 0, 'C’est le pouvoir de la norme, un levier de puissance discret mais réel.', 3),
    ('599a8bf7-4c1c-56e8-b1e4-438729fa4543'::uuid, 'a66d7f19-42ca-584d-876f-5b3eda027cd4'::uuid, 'Quelle est la principale faiblesse de l’Union européenne comme puissance ?', 'mcq', '["Sa faiblesse politique et militaire","Son poids commercial insuffisant","L’absence de monnaie commune","Sa population trop réduite"]'::jsonb, 0, 'Pas d’armée commune, une diplomatie à l’unanimité, une dépendance à l’OTAN.', 4),
    ('19957df2-e03c-5f49-8b7f-6370024383ce'::uuid, 'a66d7f19-42ca-584d-876f-5b3eda027cd4'::uuid, 'Pourquoi la diplomatie européenne est-elle souvent lente ?', 'mcq', '["Parce que de nombreuses décisions exigent l’unanimité des 27","Parce que le Parlement ne siège qu’une fois par an","Parce que la Commission n’a aucun pouvoir","Parce que les États n’ont pas d’ambassades"]'::jsonb, 0, 'Un seul État peut bloquer une décision commune.', 5),
    ('2852ae0c-9b15-56d4-ba15-0a4a8aabf99b'::uuid, 'a66d7f19-42ca-584d-876f-5b3eda027cd4'::uuid, 'Quel accord climatique de 2015 l’Union a-t-elle fortement soutenu ?', 'mcq', '["L’accord de Paris","Le protocole de Montréal","Le traité de Rome","Les accords de Schengen"]'::jsonb, 0, 'L’Union est l’un des moteurs des négociations climatiques mondiales.', 6),
    ('295444e4-3dab-5cf4-b32d-ba9957d8891d'::uuid, 'a66d7f19-42ca-584d-876f-5b3eda027cd4'::uuid, 'Quel événement de 2022 a relancé le débat sur l’autonomie européenne ?', 'mcq', '["L’invasion de l’Ukraine par la Russie","Le Brexit","L’entrée de la Croatie dans l’Union","La création de l’euro"]'::jsonb, 0, 'Énergie, armement et industrie stratégique sont redevenus des sujets européens.', 7),
    ('60723e9d-72c3-559d-997a-7875f4b61104'::uuid, 'a66d7f19-42ca-584d-876f-5b3eda027cd4'::uuid, 'L’Union européenne dispose d’une armée commune.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Sa défense repose sur l’OTAN et sur les armées nationales.', 8),
    ('6e051f03-a721-535d-9bb3-d9bd2bfd3054'::uuid, 'e568f789-0367-5ee3-8fe4-7e37cd05284c'::uuid, 'La France fait-elle partie des États fondateurs de la construction européenne ?', 'mcq', '["Oui, dès la CECA en 1951","Non, elle a rejoint l’Union en 1973","Non, elle est entrée en 1992","Oui, mais seulement depuis 1986"]'::jsonb, 0, 'Elle signe la CECA en 1951 puis le traité de Rome en 1957.', 1),
    ('ceaf1e38-c0db-5289-b750-95e8521debc0'::uuid, 'e568f789-0367-5ee3-8fe4-7e37cd05284c'::uuid, 'Quelle ville française accueille le Parlement européen ?', 'mcq', '["Strasbourg","Paris","Lyon","Lille"]'::jsonb, 0, 'La Commission siège à Bruxelles, le Parlement à Strasbourg.', 2),
    ('95542a97-26c3-541b-af73-936e3cee0173'::uuid, 'e568f789-0367-5ee3-8fe4-7e37cd05284c'::uuid, 'Comment appelle-t-on le moteur historique des grandes décisions européennes ?', 'mcq', '["Le couple franco-allemand","Le trio latin","Le groupe de Visegrád","L’alliance atlantique"]'::jsonb, 0, 'France et Allemagne portent ensemble la plupart des avancées de l’Union.', 3),
    ('e154e417-18a4-58dd-9212-e1c6f1608628'::uuid, 'e568f789-0367-5ee3-8fe4-7e37cd05284c'::uuid, 'Qui sont les travailleurs transfrontaliers ?', 'mcq', '["Des habitants qui franchissent chaque jour la frontière pour aller travailler","Des saisonniers venus d’un autre continent","Des diplomates en poste à l’étranger","Des routiers du transport international"]'::jsonb, 0, 'Ils sont des dizaines de milliers dans le Grand Est, le Nord et la Savoie.', 4),
    ('c1c2ff8d-4cf4-512a-8f84-eab1318682db'::uuid, 'e568f789-0367-5ee3-8fe4-7e37cd05284c'::uuid, 'De quelle politique européenne la France est-elle la première bénéficiaire ?', 'mcq', '["La Politique agricole commune (PAC)","La politique de défense commune","La politique spatiale","La politique de la pêche uniquement"]'::jsonb, 0, 'Sa puissance agricole en fait la première destinataire des aides.', 5),
    ('6a4fee46-ea00-53b9-82be-45b26c4c30de'::uuid, 'e568f789-0367-5ee3-8fe4-7e37cd05284c'::uuid, 'Quel siège la France occupe-t-elle à l’ONU ?', 'mcq', '["Un siège permanent au Conseil de sécurité, avec droit de veto","Un siège tournant à l’Assemblée générale","La présidence permanente de l’UNESCO","Aucun siège permanent"]'::jsonb, 0, 'Elle est l’un des cinq membres permanents.', 6),
    ('047cc942-49d0-537c-b12a-de121164601f'::uuid, 'e568f789-0367-5ee3-8fe4-7e37cd05284c'::uuid, 'Qu’est-ce que le soft power de la France ?', 'mcq', '["Son influence par la culture, la langue et les idées","Sa puissance militaire nucléaire","Son excédent commercial","Son droit de veto à l’ONU"]'::jsonb, 0, 'Francophonie, tourisme, instituts culturels et lycées français à l’étranger.', 7),
    ('0826465a-eeab-5015-98c8-ba74c6c14efd'::uuid, 'e568f789-0367-5ee3-8fe4-7e37cd05284c'::uuid, 'La France agit uniquement à l’échelle européenne dans les affaires du monde.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle agit seule pour son siège à l’ONU et sa défense, et à 27 pour le commerce, le climat ou les normes.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('histoire-geo');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('histoire-geo')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 293 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 293 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
