-- =============================================================================
-- Studuel — Migration 300 : FRANÇAIS 4e — LE PROGRAMME COMPLET (18 fiches)
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 300 --modules francais-4e
--
-- CONSTAT : le français de 4e n'avait que les 5 fiches du premier jeu de données
-- de l'app — « La lettre et l'épistolaire », « Le fantastique », « La ville en
-- poésie », « Les propositions subordonnées », « Cause, conséquence et but ». Un
-- élève de 4e qui révisait la poésie lyrique, Bérénice, Marivaux, Lorenzaccio, Le
-- Cid, L'Assommoir, « La Parure », « La Chute de la maison Usher », la lecture de
-- la presse, la propagande ou la ville en littérature ne trouvait RIEN. Cette
-- migration installe les 18 fiches, rangées sous les 5 chapitres de la maquette —
-- les quatre questionnements du BO plus un questionnement complémentaire — et
-- retire les 5 fiches génériques.
-- DEUX DES CINQ FICHES RETIRÉES SONT DES POINTS DE LANGUE (« Les propositions
-- subordonnées », « Cause, conséquence et but ») : la grammaire a son propre rayon
-- en Première (migration 259) et le collège n'en a pas encore ; les laisser au
-- milieu des œuvres brouillerait le dossier.
--
-- Cette migration apporte : 18 chapitres, 18 leçons,
-- 18 quiz et 144 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 0. Ménage ----------------------------------------------------------------
-- [francais] La colonne chapters.theme (migration 234) conditionne tout ce qui suit : ce
-- [francais] module range ses 18 fiches sous 5 chapitres, et l'INSERT écrit la colonne. Elle
-- [francais] est REPRISE ici en ADD COLUMN IF NOT EXISTS parce qu'on ne peut pas garantir que
-- [francais] la 234 soit passée en production — sans cette reprise, la migration échouerait
-- [francais] sur "column chapters.theme does not exist", les 5 anciens chapitres déjà
-- [francais] supprimés et les 18 neufs pas encore posés : une matière vide.
-- [francais] Le ménage qui suit LIT cette colonne : elle doit exister avant lui.
-- [francais] Le GRANT n'est pas décoratif : la migration 182 a révoqué le SELECT de table sur
-- [francais] chapters (pour cacher mind_map) et ne l'a rendu que colonne par colonne.
ALTER TABLE public.chapters ADD COLUMN IF NOT EXISTS theme TEXT;
GRANT SELECT (theme) ON public.chapters TO anon;
GRANT SELECT (theme) ON public.chapters TO authenticated;

-- [francais] Les 5 chapitres hérités de la 008 partent, au niveau 4e SEULEMENT.
-- [francais] 
-- [francais] LE REPÈRE EST theme IS NULL, PAS LE TITRE : « La lettre et l'épistolaire » porte
-- [francais] une apostrophe, et rien ne garantit que la base porte la même que ce fichier
-- [francais] (droite dans le contenu ancien, typographique dans le récent) ; un DELETE par
-- [francais] titre ne trouverait alors pas la ligne, EN SILENCE. Le critère « pas de chapitre
-- [francais] de programme » vise exactement les cinq lignes voulues : elles datent de la 008,
-- [francais] bien avant la colonne theme, tandis que les 18 fiches neuves en portent une dès
-- [francais] l'INSERT — le ménage tourne AVANT les insertions et ne peut donc jamais mordre
-- [francais] sur elles, ni au premier passage ni au rejeu.
-- [francais] Le filtre level = '4e' est indispensable : le français existe sur six niveaux, et
-- [francais] « Le fantastique » comme « La ville en poésie » sont des titres qu'on retrouve
-- [francais] ailleurs.
-- [francais] L'ordre compte : la file « À revoir » d'abord (review_items.item_id n'a PAS de
-- [francais] clé étrangère), puis les quiz (quizzes.lesson_id est ON DELETE SET NULL), puis
-- [francais] les chapitres, dont les leçons partent en cascade.
DELETE FROM public.review_items ri
 USING public.quiz_questions qq, public.quizzes qz, public.lessons l,
       public.chapters c, public.subjects s
 WHERE ri.item_kind = 'question'
   AND ri.item_id = qq.id
   AND qq.quiz_id = qz.id
   AND qz.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'francais'
   AND c.level = '4e'
   AND c.theme IS NULL;

DELETE FROM public.quizzes q
 USING public.lessons l, public.chapters c, public.subjects s
 WHERE q.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'francais'
   AND c.level = '4e'
   AND c.theme IS NULL;

DELETE FROM public.chapters c
 USING public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'francais'
   AND c.level = '4e'
   AND c.theme IS NULL;

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position, theme)
SELECT v.id, s.id, v.level, v.title, v.position, v.theme
  FROM (VALUES
    ('a5ca98d8-8b8f-5cfa-b1e9-d855937fa78f'::uuid, 'francais', '4e', 'La poésie lyrique et amoureuse de l’Antiquité à nos jours', 1, 'Se chercher, se construire — Dire l’amour'),
    ('e44539ef-c1f1-509f-bb81-3f1246281327'::uuid, 'francais', '4e', '« Demain, dès l’aube… », Victor Hugo', 2, 'Se chercher, se construire — Dire l’amour'),
    ('77d56b69-676a-5c71-93dc-e13260eee0ca'::uuid, 'francais', '4e', 'La tragédie au XVIIe siècle : Bérénice de Racine', 3, 'Se chercher, se construire — Dire l’amour'),
    ('35a5afc0-a4ac-5dd2-b136-d64c98aaaf75'::uuid, 'francais', '4e', 'La comédie au XVIIIe siècle', 4, 'Se chercher, se construire — Dire l’amour'),
    ('dcbb94fb-6cd1-5461-b9ca-a4fb206add7d'::uuid, 'francais', '4e', 'Un exemple de comédie du XVIIIe siècle : Le Jeu de l’amour et du hasard, Marivaux', 5, 'Se chercher, se construire — Dire l’amour'),
    ('46988e38-b7a3-509b-a4b7-9df5e4264aa3'::uuid, 'francais', '4e', 'Le drame du XIXe siècle : Lorenzaccio, Alfred de Musset', 6, 'Se chercher, se construire — Dire l’amour'),
    ('92914028-1f3d-5b10-9383-a7c16ea1d813'::uuid, 'francais', '4e', 'La tragi-comédie au XVIIe siècle : Le Cid, Corneille', 7, 'Vivre en société, participer à la société — Individu et société : confrontations de valeurs ?'),
    ('a5c44eab-38c6-5217-9e7b-4a722e681f01'::uuid, 'francais', '4e', 'La nouvelle du XVIIIe siècle à nos jours', 8, 'Vivre en société, participer à la société — Individu et société : confrontations de valeurs ?'),
    ('47687896-757b-5f82-9a14-52626788c308'::uuid, 'francais', '4e', 'Un roman naturaliste : L’Assommoir de Zola', 9, 'Regarder le monde, inventer des mondes — La fiction pour interroger le réel'),
    ('5f0dd17a-731e-58c2-b628-990bc5b014c7'::uuid, 'francais', '4e', 'Une nouvelle réaliste : « La Parure » de Maupassant et l’adaptation éponyme de Claude Chabrol', 10, 'Regarder le monde, inventer des mondes — La fiction pour interroger le réel'),
    ('b02b1c1e-c59d-57e1-89d8-f06af97b87f2'::uuid, 'francais', '4e', 'Une nouvelle fantastique : « La Chute de la maison Usher » d’Edgar Allan Poe', 11, 'Regarder le monde, inventer des mondes — La fiction pour interroger le réel'),
    ('c7aa5303-cee8-5f65-982a-d7988ca78342'::uuid, 'francais', '4e', 'Lire et comprendre la presse et les médias', 12, 'Agir sur le monde — Informer, s’informer, déformer ?'),
    ('e104a714-229a-5083-b718-e27552811460'::uuid, 'francais', '4e', 'Étude de textes et documents produits à des fins de propagande', 13, 'Agir sur le monde — Informer, s’informer, déformer ?'),
    ('b270ad70-ec61-5760-b00d-1f57aa02685f'::uuid, 'francais', '4e', 'Le journalisme à travers les romans et les films du XIXe siècle à nos jours', 14, 'Agir sur le monde — Informer, s’informer, déformer ?'),
    ('b0642ad8-fd82-5098-a691-f2de6b6d856e'::uuid, 'francais', '4e', 'La ville comme sujet de roman', 15, 'Questionnements complémentaires — La ville, lieu de tous les possibles ?'),
    ('5b9ab20a-14af-58fa-a25c-bd2a53961130'::uuid, 'francais', '4e', 'La ville comme objet poétique', 16, 'Questionnements complémentaires — La ville, lieu de tous les possibles ?'),
    ('575652f4-6c8a-521c-942e-a10d9c4f3fb9'::uuid, 'francais', '4e', 'L’importance de la ville dans le roman policier', 17, 'Questionnements complémentaires — La ville, lieu de tous les possibles ?'),
    ('25408f17-a202-5e42-9aaa-740ad9343e15'::uuid, 'francais', '4e', 'La ville dans la photographie, les films et la bande-dessinée', 18, 'Questionnements complémentaires — La ville, lieu de tous les possibles ?')
  ) AS v(id, slug, level, title, position, theme)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 1 bis. Axes du programme -------------------------------------------------
-- `chapters.theme` (migration 234) : l’intitulé du programme officiel qui
-- coiffe le chapitre. La page matière s’en sert pour grouper au lieu
-- d’aligner 28 lignes à plat. UPDATE et non INSERT : le chapitre peut déjà
-- exister (l’INSERT précédent l’aurait alors ignoré).
UPDATE public.chapters c SET theme = v.theme
  FROM (VALUES
    ('a5ca98d8-8b8f-5cfa-b1e9-d855937fa78f'::uuid, 'Se chercher, se construire — Dire l’amour'),
    ('e44539ef-c1f1-509f-bb81-3f1246281327'::uuid, 'Se chercher, se construire — Dire l’amour'),
    ('77d56b69-676a-5c71-93dc-e13260eee0ca'::uuid, 'Se chercher, se construire — Dire l’amour'),
    ('35a5afc0-a4ac-5dd2-b136-d64c98aaaf75'::uuid, 'Se chercher, se construire — Dire l’amour'),
    ('dcbb94fb-6cd1-5461-b9ca-a4fb206add7d'::uuid, 'Se chercher, se construire — Dire l’amour'),
    ('46988e38-b7a3-509b-a4b7-9df5e4264aa3'::uuid, 'Se chercher, se construire — Dire l’amour'),
    ('92914028-1f3d-5b10-9383-a7c16ea1d813'::uuid, 'Vivre en société, participer à la société — Individu et société : confrontations de valeurs ?'),
    ('a5c44eab-38c6-5217-9e7b-4a722e681f01'::uuid, 'Vivre en société, participer à la société — Individu et société : confrontations de valeurs ?'),
    ('47687896-757b-5f82-9a14-52626788c308'::uuid, 'Regarder le monde, inventer des mondes — La fiction pour interroger le réel'),
    ('5f0dd17a-731e-58c2-b628-990bc5b014c7'::uuid, 'Regarder le monde, inventer des mondes — La fiction pour interroger le réel'),
    ('b02b1c1e-c59d-57e1-89d8-f06af97b87f2'::uuid, 'Regarder le monde, inventer des mondes — La fiction pour interroger le réel'),
    ('c7aa5303-cee8-5f65-982a-d7988ca78342'::uuid, 'Agir sur le monde — Informer, s’informer, déformer ?'),
    ('e104a714-229a-5083-b718-e27552811460'::uuid, 'Agir sur le monde — Informer, s’informer, déformer ?'),
    ('b270ad70-ec61-5760-b00d-1f57aa02685f'::uuid, 'Agir sur le monde — Informer, s’informer, déformer ?'),
    ('b0642ad8-fd82-5098-a691-f2de6b6d856e'::uuid, 'Questionnements complémentaires — La ville, lieu de tous les possibles ?'),
    ('5b9ab20a-14af-58fa-a25c-bd2a53961130'::uuid, 'Questionnements complémentaires — La ville, lieu de tous les possibles ?'),
    ('575652f4-6c8a-521c-942e-a10d9c4f3fb9'::uuid, 'Questionnements complémentaires — La ville, lieu de tous les possibles ?'),
    ('25408f17-a202-5e42-9aaa-740ad9343e15'::uuid, 'Questionnements complémentaires — La ville, lieu de tous les possibles ?')
  ) AS v(id, theme)
 WHERE c.id = v.id AND c.theme IS DISTINCT FROM v.theme;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('eaab7c70-0277-5a51-8ed0-d66d03328374', 'a5ca98d8-8b8f-5cfa-b1e9-d855937fa78f', 'Vingt-cinq siècles pour dire « je t’aime »', E'Dire l’amour, c’est presque toujours dire aussi le temps. Les deux thèmes sont inséparables depuis Ronsard.\n\n## Le mot\n= Lyrique vient de la LYRE, l’instrument des poètes grecs\n\nÀ l’origine, la poésie lyrique se **chantait**. Elle exprime les **sentiments personnels** du poète.\n\n## Les grandes étapes\n@ VIe siècle av. J.-C. — Sappho dit le trouble amoureux ; plus tard, Ovide écrit L’Art d’aimer\n@ Moyen Âge — Les troubadours inventent l’amour courtois\n@ XVIe siècle — La Pléiade : Ronsard, Louise Labé, et le sonnet venu de Pétrarque\n@ XIXe siècle — Le romantisme : Lamartine, Hugo, Musset\n@ XXe siècle — Apollinaire, Éluard, Aragon renouvellent la forme\n\n| Le poète | Son vers célèbre |\n| **Ronsard** | « Mignonne, allons voir si la rose… » |\n| **Apollinaire** | « Le Pont Mirabeau » |\n| **Éluard** | « Liberté » |\n| **Aragon** | « Les Yeux d’Elsa » |\n\nDans l’**amour courtois**, le poète sert une dame inaccessible, et cette souffrance l’élève.\n\n## Les marques du lyrisme\n| La marque | Exemple |\n| La **première personne** | *je*, *mon*, *mes* |\n| L’**apostrophe** | « Ô temps, suspends ton vol ! » |\n| La **ponctuation expressive** | Exclamations, interrogations, points de suspension |\n| Le **champ lexical** du sentiment | |\n| Les **images** | Comparaison et métaphore |\n\n## Les formes\n| La forme | Ce qu’elle est |\n| Le **sonnet** | **14 vers** : deux quatrains, deux tercets |\n| L’**ode** | Un poème de célébration |\n| L’**élégie** | Le poème de la **plainte** |\n| La **ballade** | |\n| Le **vers libre**, le **poème en prose** | Depuis le XIXe siècle |\n\n> La beauté qui passe, l’absence, la mort : le temps est le compagnon obligé du sentiment amoureux en poésie.', 1),
  ('a968fe8b-b52a-5588-b909-f7a52186e283', 'e44539ef-c1f1-509f-bb81-3f1246281327', 'Un poème d’amour qui est un poème de deuil', E'Pendant onze vers, on croit lire un poème d’amour. Un seul mot, au dernier vers, renverse tout.\n\n## Le contexte\n@ Septembre 1843 — Léopoldine, fille de Victor Hugo, se noie à 19 ans dans la Seine à Villequier\n@ 1856 — Publication des Contemplations, où figure « Demain, dès l’aube… »\n\n## La forme\n= Trois quatrains d’alexandrins, en rimes croisées (ABAB)\n\nUne forme **simple, presque nue**.\n\n## Le mouvement du poème\n| La strophe | Ce qui s’y passe |\n| **1** | L’annonce du départ, au **futur** : « Je partirai. Vois-tu, je sais que tu m’attends. » |\n| **2** | Le voyage, replié : « Je marcherai les yeux fixés sur mes pensées » |\n| **3** | L’arrivée, et la **chute** : « Je mettrai sur ta tombe / Un bouquet de houx vert et de bruyère en fleur. » |\n\n~ On croit lire un poème d’amour → le mot « tombe » tombe → tout se relit autrement\n\n!> Les indices étaient là : les **yeux baissés**, le refus de voir l’or du soir, le dos tourné au monde. On ne les comprend qu’à la **relecture**.\n\n## Les procédés à relever\n| Le procédé | Son effet |\n| Le **futur** de la certitude | Le voyage devient inéluctable |\n| L’**anaphore** du « je » | Le poème est tourné vers un seul geste |\n| Les **négations** de la strophe 2 | « ni l’or du soir qui tombe / Ni les voiles au loin descendant vers Harfleur » |\n| L’**antithèse** finale | Le **houx** persistant et piquant, la **bruyère en fleur** fragile |\n\nFidélité et deuil dans un même bouquet.\n\n> Le poème ne dit jamais le mot « fille », ni le mot « mort ». C’est cette **retenue** qui le rend bouleversant.', 1),
  ('943e7157-df1b-5416-a569-602abd7194e2', '77d56b69-676a-5c71-93dc-e13260eee0ca', 'Aimer et renoncer', E'Un héros tragique n’a aucune issue : quel que soit son choix, il perd. C’est ce qui distingue le tragique du dramatique.\n\n## Les règles de la tragédie classique\n| La règle | Ce qu’elle impose |\n| Les **trois unités** | Une seule **action**, en un seul **lieu**, en une seule **journée** |\n| La **vraisemblance** | Rien d’invraisemblable sur scène |\n| La **bienséance** | Ni sang, ni violence, ni mort devant le public : on les **raconte** |\n| Le rang | Des personnages **élevés** — rois, princes |\n| La forme | L’**alexandrin** en rimes plates ; une **fin malheureuse** |\n\n= La catharsis : purger les passions du spectateur par la terreur et la pitié\n\nC’est le but assigné par **Aristote**.\n\n## Bérénice (1670)\n| Le personnage | Sa situation |\n| **Titus** | Devenu empereur de Rome, il aime Bérénice |\n| **Bérénice** | Reine de Palestine — et Rome interdit à son empereur d’épouser une **reine étrangère** |\n| **Antiochus** | Roi de Comagène, ami de Titus, il aime Bérénice en silence |\n\n~ Titus renonce → Bérénice part → Antiochus reste seul\n\n!> **Personne ne meurt.** La pièce s’achève sur un **triple renoncement** — et c’est pourtant une tragédie.\n\n> Racine l’écrit dans sa préface : « Ce n’est point une nécessité qu’il y ait du sang et des morts dans une tragédie ; il suffit que l’action en soit grande. »\n\n## Le conflit tragique\n= L’amour contre le devoir\n\nLa passion personnelle contre la loi de Rome.\n\n## Le style de Racine\nUne langue **simple**, un vocabulaire volontairement **restreint**, une musicalité fondée sur les sonorités.\n\n> Le dernier mot de Bérénice — « Hélas ! » — est le plus court sommet d’une pièce entière.', 1),
  ('90df0ebf-e497-5343-8ae1-7d86b12fa4ca', '35a5afc0-a4ac-5dd2-b136-d64c98aaaf75', 'Rire, mais pour dire quelque chose', E'Au XVIIIe siècle, la comédie continue de faire rire — mais elle critique de plus en plus la société.\n\n## Ce qu’elle garde de Molière\n| Les **types** | Le valet rusé, le barbon, l’amoureux, la coquette |\n| Le **quiproquo** | Le moteur de l’intrigue |\n| Le **double jeu** | |\n\n| Le comique | Ses moyens |\n| De **mots** | Jeux de mots, patois, répétitions |\n| De **gestes** | Chutes, coups de bâton, déguisements |\n| De **situation** | Quiproquo, malentendu, hasard |\n| De **caractère** | Le défaut poussé à l’excès |\n| De **répétition** | Une même réplique qui revient |\n\n## Ce qui change au XVIIIe siècle\n| Le changement | Ce qu’il produit |\n| Le **valet** devient l’égal intellectuel de son maître | Et parfois plus lucide que lui |\n| La **critique sociale** s’installe | Inégalité des conditions, mariage arrangé, pouvoir des pères |\n| Naît la **comédie sensible** | Elle mêle rire et émotion, et prépare le **drame** |\n\n= Figaro reproche à son maître de « s’être donné la peine de naître »\n\n## Marivaux et le marivaudage\n**Marivaux** (1688-1763) fait de l’amour un **jeu de langage**.\n\n= Le marivaudage : un dialogue léger et spirituel, où chaque réplique avance masquée\n\nLes personnages parlent **pour ne pas s’avouer** ce qu’ils ressentent, et le spectateur comprend avant eux.\n\n!> Chez Marivaux, l’obstacle n’est **ni le père ni la société** : c’est l’**amour-propre** des personnages, qui refusent de reconnaître leur sentiment.\n\n## Beaumarchais\n@ 1775 — Le Barbier de Séville\n@ 1784 — Le Mariage de Figaro\n\nLa critique va si loin que **Louis XVI** en interdit d’abord la représentation.', 1),
  ('38ee677d-858e-52a9-8d84-80e822475a08', 'dcbb94fb-6cd1-5461-b9ca-a4fb206add7d', 'Deux déguisements, un même aveu', E'Deux personnages ont exactement la même idée au même moment : c’est tout le mécanisme de la pièce.\n\n## L’intrigue\n@ 1730 — Création du Jeu de l’amour et du hasard, comédie en trois actes et en prose\n\n~ Silvia échange son habit avec sa servante Lisette → Dorante a eu la MÊME idée et se présente en valet → les quatre personnages sont masqués deux à deux, sans le savoir\n\n| Le personnage | Son déguisement |\n| **Silvia** | En servante |\n| **Lisette**, sa servante | En maîtresse |\n| **Dorante** | En valet |\n| **Arlequin**, son valet | En maître |\n\nSilvia (en servante) tombe amoureuse de Dorante (en valet), et réciproquement ; Lisette et Arlequin se plaisent aussi.\n\n## Le double registre\n!> Le spectateur, lui, **sait tout**. **Monsieur Orgon**, père de Silvia, et son frère **Mario** sont dans la confidence et laissent faire. Ce **double registre** est le ressort comique principal.\n\n## Le vrai sujet\n= L’épreuve du sentiment face au préjugé social\n\nSilvia et Dorante s’aiment **en croyant aimer un domestique** : chacun doit choisir entre son cœur et son rang.\n\n| Le personnage | Ce qu’il fait |\n| **Dorante** | Il cède le premier et révèle son identité **par amour** |\n| **Silvia** | Elle **prolonge** l’épreuve : elle veut être aimée **pour elle-même** |\n\n= « Il se fait justice ! »\n\n!> La pièce s’achève sur la victoire du sentiment — mais **l’ordre social n’est pas renversé** : maîtres et valets se marient chacun dans leur condition.\n\n## Les procédés à connaître\nLe **quiproquo** généralisé, l’**ironie dramatique** (le public en sait plus), le **langage** qui trahit le rang malgré l’habit, et l’**aparté** — ces répliques dites au public que les autres personnages n’entendent pas.', 1),
  ('256ecacb-cae7-5554-ba0f-76819bd0a65f', '46988e38-b7a3-509b-a4b7-9df5e4264aa3', 'Le théâtre romantique brise les règles', E'Le drame romantique rejette en bloc les règles classiques. Hugo en écrit le manifeste, Musset en donne le chef-d’œuvre.\n\n## Le drame romantique\n@ 1827 — Victor Hugo le théorise dans la Préface de Cromwell\n\n| La règle classique | Ce que le drame en fait |\n| Les **trois unités** | Il les **abolit** : l’action se déplace, s’étale sur des années |\n| La séparation des genres | Il **mélange** le sublime et le grotesque, le comique et le tragique |\n| L’unité de langue | Il mêle rois et gens du peuple, vers et prose |\n| Les personnages tranchés | Il les veut **complexes**, ni bons ni mauvais |\n| Le décor conventionnel | Il exige la **couleur locale** : décors, costumes, détails historiques précis |\n\n## Lorenzaccio (1834)\nMusset a **24 ans**. La pièce compte **cinq actes**, **39 scènes** et une trentaine de personnages.\n\n@ 1834 — Écriture de la pièce\n@ 1896 — Première création, avec Sarah Bernhardt dans le rôle-titre\n\n!> Elle est jugée **injouable** pendant plus de soixante ans, tant elle ignore les contraintes de la scène de son temps.\n\n## L’intrigue\nFlorence, 1537.\n\n~ Alexandre de Médicis est un tyran → Lorenzo se fait son complice et son entremetteur → c’est un MASQUE : il prépare son assassinat → il le tue → et rien ne change\n\nLes Florentins, indifférents, laissent aussitôt élire un autre Médicis, **Côme**. Lorenzo est assassiné à son tour.\n\n## Le personnage de Lorenzo\nSurnommé par mépris **Lorenzaccio**, « le mauvais Lorenzo ».\n\n> « Le vice a été pour moi un vêtement ; maintenant il est collé à ma peau. »\n\n!> À force de jouer le débauché pour approcher le tyran, il l’est **devenu**. Il agit sans plus croire à l’utilité de son acte : il tue **pour rester fidèle** à celui qu’il a été.\n\n## Ce que la pièce interroge\nL’**engagement** et son inutilité, le rapport entre l’**être** et le **paraître**, et le désenchantement d’une génération née trop tard pour la Révolution : le « **mal du siècle** ».', 1),
  ('5539221b-a0e0-5d81-8496-34a271254cf1', '92914028-1f3d-5b10-9383-a7c16ea1d813', 'L’honneur contre l’amour', E'Le dilemme cornélien : choisir entre deux valeurs également hautes, sans pouvoir les concilier.\n\n## Une tragi-comédie\n@ 1637 — Création du Cid\n@ 1648 — Corneille la rebaptise « tragédie »\n\nElle a la **gravité** d’une tragédie mais une **fin heureuse**, et son intrigue est plus libre que les règles ne l’autorisent.\n\n## L’intrigue\n| Le personnage | Son lien |\n| **Rodrigue** et **Chimène** | Ils s’aiment et vont se marier |\n| **Don Gomès** | Père de Chimène ; il insulte et gifle Don Diègue |\n| **Don Diègue** | Père de Rodrigue, trop vieux pour se venger lui-même |\n\n~ L’affront → Rodrigue doit choisir → il tue Don Gomès en duel → Chimène doit réclamer sa mort au roi → Rodrigue vainc les Maures → le roi accorde un délai d’un an\n\nVainqueur des **Maures**, Rodrigue est surnommé **le Cid**, « le seigneur ».\n\n## Le dilemme cornélien\n| Rodrigue peut… | Et alors il perd… |\n| **Venger son père** | **Chimène** |\n| **Renoncer à l’honneur** | Sa **valeur** et son nom |\n\n!> Quel que soit son choix, il perd quelque chose d’essentiel. C’est cela, un dilemme — et non une simple hésitation.\n\n= « Percé jusques au fond du cœur… »\n\nLes **stances** de Rodrigue (acte I, scène 6) sont le monologue où ce déchirement se déploie.\n\n## Le héros cornélien\n| Le héros de Corneille | Le héros de Racine |\n| Il se définit par sa **volonté** | Il est **écrasé** par une passion qu’il subit |\n| Il **choisit**, quoi qu’il en coûte | |\n| Il **grandit** par son choix | |\n\n## La querelle du Cid\nL’Académie française reprocha à la pièce de violer les **unités** et la **bienséance** — Chimène épouserait le meurtrier de son père.\n\n> Cette querelle contribua à **fixer les règles** du théâtre classique. Une polémique a fait une doctrine.', 1),
  ('96dd1b4e-bed8-5783-9426-e3f86307dc5b', 'a5c44eab-38c6-5217-9e7b-4a722e681f01', 'Un récit court qui frappe fort', E'Le roman prend son temps, la nouvelle vise. C’est la différence entre un portrait à l’huile et un instantané.\n\n## Ce qui définit une nouvelle\n| Le trait | Face au roman |\n| Une intrigue **resserrée** | Souvent une seule action |\n| **Peu de personnages** | Décrits en quelques traits |\n| Un cadre **limité** | Dans l’espace et dans le temps |\n| Un rythme **rapide** | Avec des **ellipses** |\n| Une **chute** | Une fin brève et frappante, qui souvent retourne le sens |\n\n## Les grandes étapes du genre\n@ XVIIIe siècle — Le conte philosophique de Voltaire : Candide, Micromégas\n@ XIXe siècle — L’âge d’or : la presse publie des nouvelles chaque semaine\n@ XXe-XXIe siècles — Science-fiction, absurde, quotidien\n\n| L’auteur | Son domaine |\n| **Maupassant** | Le réalisme (*La Parure*, *Boule de Suif*) et le fantastique (*Le Horla*) |\n| **Mérimée** | *La Vénus d’Ille* |\n| **Poe** | Aux États-Unis |\n| **Tchekhov** | En Russie |\n| **Bradbury**, **Buzzati**, **Carver** | Science-fiction, absurde, quotidien |\n\nEn France aujourd’hui : **Anna Gavalda**, **Bernard Werber**.\n\n## Les registres possibles\n| Le registre | Ce qu’il fait |\n| **Réaliste** | Peindre le réel tel qu’il est |\n| **Fantastique** | L’inexplicable fait irruption |\n| **Merveilleux** | Le surnaturel est admis |\n| **Policier**, **science-fiction**, **absurde** | |\n\n## La chute\n| Elle peut… | |\n| **Révéler** une information cachée | *La Parure* |\n| **Retourner** la morale attendue | |\n| **Laisser en suspens** | Sans réponse |\n\n!> Une bonne chute est toujours **préparée** : à la relecture, les indices étaient là. Une chute qui sort de nulle part n’est pas une chute, c’est une invraisemblance.', 1),
  ('07c147f3-7995-5255-9098-9e3412d2835d', '47687896-757b-5f82-9a14-52626788c308', 'Le roman comme enquête sociale', E'Zola ne condamne pas Gervaise : il montre comment le milieu défait une femme courageuse.\n\n## Du réalisme au naturalisme\n| Le mouvement | Son projet |\n| Le **réalisme** — Balzac, Flaubert, Maupassant | Peindre le réel **tel qu’il est**, sans idéaliser |\n| Le **naturalisme** — **Zola** | Appliquer au roman la **méthode scientifique** |\n\nLe romancier observe, se documente, expérimente. Il étudie l’effet de l’**hérédité** et du **milieu** sur ses personnages.\n\n> Zola l’écrit dans *Le Roman expérimental* : le romancier est « un observateur et un expérimentateur ».\n\n## Les Rougon-Macquart\n= 20 romans, de 1871 à 1893, sur cinq générations d’une même famille\n\nSous-titre : « **Histoire naturelle et sociale d’une famille sous le Second Empire** ».\n\n@ 1877 — L’Assommoir, septième roman du cycle\n\n## L’Assommoir\nLe premier grand roman français consacré au **monde ouvrier**.\n\n~ Gervaise arrive à Paris → elle épouse Coupeau → ils ouvrent une blanchisserie → Coupeau tombe d’un toit → il boit → dettes, faim, déchéance → elle meurt dans un réduit sous l’escalier\n\n**Gervaise Macquart** est blanchisseuse et boiteuse. Leur fille **Nana** deviendra l’héroïne d’un autre roman.\n\n## Le titre\n= L’assommoir : le nom populaire du débit d’alcool\n\nLa boutique du père Colombe, où l’alambic travaille jour et nuit.\n\n> Le mot dit tout : ce qui **assomme**.\n\n## Ce qui a fait scandale\n!> Zola fait entrer dans le roman la **langue du peuple** — argot, familiarités, tournures orales — **y compris dans la narration**, et non seulement dans les dialogues. C’est cette audace-là qui choqua.\n\nLe livre fut accusé de complaisance dans la misère ; il fut aussi son plus grand succès de librairie.', 1),
  ('96b89670-84cc-5533-a0bd-c96684e88730', '5f0dd17a-731e-58c2-b628-990bc5b014c7', 'Dix ans de misère pour un bijou faux', E'Une faute minuscule, une punition de dix ans, et un dernier mot qui rend tout absurde.\n\n## La nouvelle (1884)\n~ Mathilde emprunte une rivière de diamants → elle triomphe au bal → elle perd la parure → le couple la remplace pour 36 000 francs → dix ans à rembourser → la révélation\n\n| Le personnage | Qui il est |\n| **Mathilde Loisel** | Jolie femme d’un petit employé du ministère, elle souffre de sa condition modeste |\n| **Madame Forestier** | L’amie à qui elle emprunte la parure |\n\nPendant **dix ans**, le couple s’épuise : Mathilde renvoie la bonne, lave, marchande, vieillit prématurément.\n\n> « Oh ! ma pauvre Mathilde ! Mais la mienne était fausse. Elle valait au plus cinq cents francs !… »\n\n## Les procédés\n| Le procédé | Son effet |\n| Le **narrateur externe** | Il rapporte **sans commenter** |\n| Le **portrait initial** | Quelques lignes suffisent à installer l’insatisfaction |\n| L’**ellipse** des dix années | Condensées en un paragraphe : la nouvelle accélère là où le roman s’attarderait |\n| La **chute** | Préparée par des indices : la boîte qui n’est pas d’origine, le bijoutier qui ne reconnaît pas la parure |\n\n## Ce que la nouvelle interroge\nLe poids des **apparences** dans une société où le rang se joue au regard des autres, et la **disproportion** cruelle entre une faute minuscule et sa punition.\n\n!> Chez Maupassant, ce n’est pas la fatalité qui frappe : c’est le **hasard**. Et le hasard n’a pas de justice à rendre.\n\n## L’adaptation de Claude Chabrol (2007)\nRéalisée pour la télévision, dans la collection *Chez Maupassant*.\n\n| Ce que la caméra ajoute | Ce qu’elle perd |\n| Les **décors**, la lumière du bal | Le discours du **narrateur** |\n| La mesquinerie des logements | L’**ellipse instantanée** — dix ans en un paragraphe |\n| Le corps, le costume, la **durée réelle** | |', 1),
  ('ce72b0b3-6b46-5a50-a3c2-9bc221b8d37b', 'b02b1c1e-c59d-57e1-89d8-f06af97b87f2', 'Quand la maison et la famille s’effondrent ensemble', E'Le fantastique n’est ni le merveilleux ni la science-fiction : sa marque, c’est l’hésitation.\n\n## Les trois genres à distinguer\n| Le genre | Le statut du surnaturel |\n| Le **fantastique** | Il **fait irruption** dans un cadre réaliste, et on ne sait jamais s’il faut y croire |\n| Le **merveilleux** | Il **va de soi**, comme dans le conte |\n| La **science-fiction** | Il est **expliqué** par la science |\n\n!> L’**hésitation** est l’essentiel : surnaturel, ou bien folie, rêve, hallucination ? Un récit qui tranche cesse d’être fantastique.\n\n## La nouvelle (1839)\n~ Le narrateur est appelé au chevet de Roderick Usher → il découvre une maison lézardée au bord d’un étang noir → Madeline meurt → on l’enferme dans un caveau → elle reparaît, enterrée vivante → elle entraîne son frère dans la mort → la maison se fend et sombre\n\n| Le personnage | Ce qu’il est |\n| Le **narrateur** | Un ami d’enfance, dont on ne saura pas le nom |\n| **Roderick Usher** | Dernier héritier d’une famille éteinte ; hypersensible, terrifié par les sons, les lumières, les odeurs |\n| **Madeline** | Sa sœur **jumelle** |\n\n## Les procédés du fantastique chez Poe\n| Le procédé | Son rôle |\n| Le **narrateur interne**, témoin | On peut douter de lui |\n| Le **cadre** | Maison isolée, décrépitude, nuit, tempête |\n| La **gradation** de l’angoisse | Très progressive |\n| Le **lexique** de l’étrange et de la peur | |\n| Le **modalisateur** | « il me sembla », « comme si », « peut-être » : le doute reste ouvert |\n| La **correspondance** maison / habitant | Les deux se fissurent ensemble, et s’effondrent au même instant |\n\n> Le titre est double : la « chute de la maison Usher » désigne autant le **bâtiment** que la **lignée**. La langue anglaise dit *house* pour les deux.', 1),
  ('9083aed1-2a2b-58bd-b4f7-57f048abd040', 'c7aa5303-cee8-5f65-982a-d7988ca78342', 'Qui parle, d’où, et pour dire quoi ?', E'La première question devant un texte de presse : informe-t-il, ou donne-t-il un avis ?\n\n## Les genres journalistiques\n| Le genre | Ce qu’il fait |\n| La **brève** | Quelques lignes, l’essentiel |\n| L’**article informatif** | Il répond aux **cinq questions** : qui, quoi, quand, où, pourquoi |\n| Le **reportage** | Le journaliste s’est rendu sur place et raconte ce qu’il a vu |\n| L’**interview** | Questions et réponses rapportées |\n| L’**enquête** | Une recherche longue, avec recoupement de sources |\n| L’**éditorial**, la **chronique**, la **critique** | Des textes d’**opinion**, où l’auteur s’engage |\n\n!> Informer et donner un avis sont **tous deux légitimes**. Les **confondre** ne l’est pas.\n\n## L’architecture d’un article\n~ Le titre → le chapô → l’attaque → le corps → la chute\n\n| L’élément | Ce qu’il est |\n| Le **titre** | Informatif ou incitatif |\n| Le **chapô** | Le paragraphe d’introduction, en gras |\n| L’**attaque** | La première phrase |\n| L’**intertitre**, la **légende**, le **crédit photo** | Les repères de lecture |\n\n## Vérifier une information\n1. La **source** : d’où vient-elle ? est-elle nommée ?\n2. La **date** : une image ancienne remise en circulation change de sens ;\n3. le **recoupement** : plusieurs médias indépendants la donnent-ils ?\n4. l’**auteur** : signé ? par un journaliste identifiable ?\n5. l’**image** : une recherche d’image inversée dit souvent d’où elle vient réellement.\n\n## Les pièges du numérique\n| Le piège | Ce qu’il fait |\n| Le **titre-appât** (« putaclic ») | Il promet plus que l’article ne donne |\n| La **bulle de filtres** | Les algorithmes montrent surtout ce qui **confirme** ce qu’on pense déjà |\n| L’**infox** (fake news) | Une fausse information **fabriquée** pour tromper |\n| La **rumeur** | Une information non vérifiée, relayée **de bonne foi** |\n\n!> Une infox circule d’autant plus vite qu’elle **indigne**. L’émotion est son carburant, pas la vraisemblance.\n\n## Le rôle de la presse en démocratie\n@ 1881 — La loi garantit la liberté de la presse\n\nSes limites : diffamation, injure, incitation à la haine. Un journaliste doit protéger ses **sources** et vérifier ses informations : c’est la **déontologie** du métier.', 1),
  ('7e4e1113-609a-545a-a889-d3faa6e719d3', 'e104a714-229a-5083-b718-e27552811460', 'Reconnaître un discours qui veut faire penser', E'La propagande ne cherche pas à informer, mais à faire adhérer. Elle s’adresse à l’émotion, jamais au raisonnement.\n\n## Trois discours à distinguer\n| Le discours | Son but |\n| L’**information** | Faire savoir, avec du contradictoire |\n| La **publicité** | Vendre un **produit** |\n| La **propagande** | Faire **adhérer** à une idée politique ou idéologique |\n\n## Ses procédés\n| Le procédé | Comment il agit |\n| La **simplification** | Un problème complexe réduit à une formule |\n| La **répétition** | Le slogan martelé jusqu’à paraître évident |\n| La **désignation d’un ennemi** | Un « eux » responsable de tout, opposé à un « nous » |\n| L’**appel aux émotions** | Peur, fierté, colère, pitié |\n| Le **culte du chef** | Image héroïsée, contre-plongée, foule en arrière-plan |\n| La **falsification** | Chiffres tronqués, photos retouchées ou sorties de leur contexte |\n| L’**argument d’autorité** | « tout le monde le sait », « des millions y croient » |\n\n## Analyser un document\n~ Nature → auteur et commanditaire → date et contexte → destinataire → message explicite → message implicite\n\n| La question | Ce qu’elle cherche |\n| **Nature** | Affiche, discours, film, tract, publication en ligne ? |\n| **Auteur et commanditaire** | Qui parle, et pour le compte de qui ? |\n| **Date et contexte** | Que se passe-t-il au moment où ce document paraît ? |\n| **Procédés visuels** | Cadrage, couleurs, taille relative des personnages, symboles |\n\n!> Distinguer le message **explicite** — ce qu’il dit — du message **implicite** — ce qu’il fait croire **sans le dire**. C’est là que tout se joue.\n\n> Une image ne ment jamais toute seule : c’est le **cadrage**, la **légende** et le **contexte** qui lui font dire ce qu’elle ne montre pas.\n\n## Les contre-pouvoirs\nLa **pluralité** des médias, le **droit de réponse**, les journalistes de vérification des faits, l’éducation aux médias.\n\n= La question à garder : qui a intérêt à ce que je le croie ?', 1),
  ('00a0b9db-3c62-5c0c-a700-af8fb71b8150', 'b270ad70-ec61-5760-b00d-1f57aa02685f', 'La fiction regarde ceux qui informent', E'Chez Balzac comme chez Maupassant, le journaliste n’est pas un menteur isolé : c’est le système qui produit le mensonge.\n\n## Au XIXe siècle : la presse comme machine\n| L’œuvre | Ce qu’elle montre |\n| **Balzac**, *Illusions perdues* (1837-1843) | **Lucien de Rubempré** monte à Paris, réussit dans le journalisme — et s’y perd. L’**article se vend** ; on démolit une pièce qu’on n’a pas vue |\n| **Maupassant**, *Bel-Ami* (1885) | **Georges Duroy**, sans talent, gravit tous les échelons par les femmes et l’intrigue. Le journal est un instrument de **spéculation politique** |\n\n## Au XXe siècle : le journalisme comme contre-pouvoir\n| L’œuvre | Ce qu’elle montre |\n| **Albert Londres** | Il invente le grand **reportage** |\n| *Les Hommes du président* (1976) | Deux journalistes du *Washington Post* et le **Watergate**, jusqu’à la démission d’un président |\n| *Spotlight* (2015) | Une **enquête au long cours** : des mois de vérification avant publication |\n\n> Albert Londres : « Notre métier n’est pas de faire plaisir, non plus de faire du tort, il est de porter la plume dans la plaie. »\n\n## Au XXIe siècle\nLa fiction s’intéresse aux réseaux sociaux, à la vitesse, à la concurrence de l’attention, et interroge la **frontière** entre informer et faire du spectacle.\n\n## Ce que la fiction apporte\n!> Là où un article expose un **fait**, le roman ou le film montre **comment ce fait a été obtenu** — et ce qu’il a coûté.\n\nElle rend visibles les **conditions** du travail journalistique : les délais, la hiérarchie, les pressions économiques et politiques, le doute avant de publier.', 1),
  ('b79cd4cc-588a-52f2-b017-a33ea4678e2c', 'b0642ad8-fd82-5098-a691-f2de6b6d856e', 'Un décor qui devient un personnage', E'Depuis le XIXe siècle, la ville n’est plus le lieu où se passe l’histoire : elle en devient l’un des acteurs.\n\n## Pourquoi le XIXe siècle\n~ L’exode rural → la révolution industrielle → les grands travaux d’Haussmann → Paris devient méconnaissable en trente ans\n\nLe roman prend acte de cette transformation.\n\n## Trois façons de traiter la ville\n| Le romancier | Sa ville | Ce qu’elle fait |\n| **Balzac** | Un **champ de bataille** | Elle promet, elle donne — et elle **dévore** |\n| **Zola** | Un **milieu qui détermine** | Le quartier explique le destin : *L’Assommoir* se joue dans quelques rues de la Goutte-d’Or |\n| **Hugo** | Un **labyrinthe** | Ruelles, égouts et barricades : on s’y cache, on y fuit, on s’y perd |\n\n= Rastignac, du haut du Père-Lachaise : « À nous deux maintenant ! »\n\n## Les procédés à repérer\n| Le procédé | Son effet |\n| La **description en focalisation interne** | La ville vue **par** un personnage, souvent à son arrivée |\n| La **personnification** | La ville « gronde », « dévore », « respire » |\n| Les **champs lexicaux** | La foule, le bruit, la lumière, la boue |\n| Le **contraste** | Quartiers riches et pauvres, souvent à quelques rues d’écart |\n| Le **rythme** des phrases | Il mime l’agitation urbaine |\n\n!> Décrire une ville, c’est toujours porter un **jugement** sur elle. Le choix de ce qu’on montre — vitrines ou taudis — dit l’intention du romancier.', 1),
  ('15457769-8d94-551f-a753-e9fd3c178022', '5b9ab20a-14af-58fa-a25c-bd2a53961130', 'De la laideur, faire un poème', E'« Tu m’as donné ta boue et j’en ai fait de l’or. » La poésie entre dans la ville, et y trouve une beauté nouvelle.\n\n## Baudelaire, l’inventeur\n@ 1857 — Les Fleurs du mal ; la section « Tableaux parisiens » fait de Paris un sujet poétique à part entière\n\nLe poète y est un **flâneur** : il marche, observe, capte les visages d’un instant — la passante, la vieille femme, l’aveugle, le cygne échappé.\n\n= « Tu m’as donné ta boue et j’en ai fait de l’or »\n\n## Après lui\n| Le poète | Sa ville |\n| **Verlaine** | Pluvieuse et mélancolique : « Il pleure dans mon cœur / Comme il pleut sur la ville » |\n| **Rimbaud** | Rêvée et démesurée, dans les *Illuminations* |\n| **Apollinaire** | « Zone » (1913) ouvre *Alcools* sur un Paris moderne — tour Eiffel, affiches, hangars — **sans ponctuation** |\n| **Cendrars**, **Réda**, **Prévert** | Jusqu’à la chanson |\n\n## Les procédés\n| Le procédé | Ce qu’il permet |\n| La **personnification** | La ville devient un être |\n| L’**oxymore** et l’**antithèse** | Dire la beauté du laid : « soleil noir », « fangeuse grandeur » |\n| L’**énumération** | Elle mime le défilé du regard |\n| La **synesthésie** | Mêler bruits, odeurs et couleurs |\n| Le **vers libre** et le **poème en prose** | Des formes assez souples pour épouser le désordre urbain |\n\n!> La poésie de la ville **n’embellit pas** : elle **transfigure**. La distinction est capitale — Baudelaire ne cache pas la boue, il en fait de l’or.\n\n> Elle regarde ce que personne ne regarde, et le rend visible.', 1),
  ('4b43250c-f18f-5338-a266-3b2326f892f3', '575652f4-6c8a-521c-942e-a10d9c4f3fb9', 'Le crime a besoin d’une foule', E'Le roman policier naît avec la grande ville. Il lui faut une foule pour s’y cacher.\n\n## Les origines\n@ 1841 — Poe publie « Double assassinat dans la rue Morgue », premier récit d’énigme, avec le chevalier Dupin\n@ 1841 — Paris se dote d’une police criminelle moderne ; Vidocq, ancien bagnard devenu chef de la Sûreté, inspire les romanciers\n@ 1887 — Conan Doyle crée Sherlock Holmes dans un Londres de brouillard et de fiacres\n\nDupin résout par la seule **déduction**.\n\n## Les grandes figures françaises\n| L’auteur | Son héros ou son apport |\n| **Émile Gaboriau** | Il invente le roman judiciaire |\n| **Gaston Leroux** | *Le Mystère de la chambre jaune* (1907), modèle du **crime en chambre close** |\n| **Maurice Leblanc** | **Arsène Lupin**, gentleman-cambrioleur : le héros est le **voleur** |\n| **Georges Simenon** | Le commissaire **Maigret**, dont les enquêtes tiennent moins à l’indice qu’à l’**atmosphère** |\n\n## Trois sous-genres\n| Le sous-genre | Son ressort | Ses auteurs |\n| Le **roman à énigme** | Un mystère, des indices, une solution **logique** | Christie, Leroux |\n| Le **roman noir** | La société est **corrompue**, le détective désabusé | Chandler, Manchette |\n| Le **thriller** | Le **suspense** l’emporte sur l’énigme : on court après le criminel |\n\n## Le rôle de la ville\n| Ce qu’elle fournit | |\n| L’**anonymat** | On disparaît dans la foule |\n| La **variété sociale** | Le crime traverse les milieux |\n| Les **lieux typiques** | Bar, port, gare, terrain vague |\n| Une **atmosphère** | |\n\n!> Chez les meilleurs auteurs, changer la ville changerait le roman. **Maigret n’existe pas hors de Paris.**', 1),
  ('a8273617-e430-5768-9177-fd7caa56b0ba', '25408f17-a202-5e42-9aaa-740ad9343e15', 'Cadrer la ville, c’est déjà la raconter', E'Trois arts, une même leçon : ce qui est hors champ compte autant que ce qui est montré.\n\n## La photographie\n| Le photographe | Ce qu’il montre |\n| **Eugène Atget** | Le vieux Paris **avant sa disparition** : rues vides, boutiques, cours. Une archive devenue œuvre |\n| **Robert Doisneau**, **Willy Ronis** | Le Paris populaire de l’après-guerre : enfants, bistrots, amoureux |\n| Les documentaristes contemporains | Les périphéries, les grands ensembles, les chantiers |\n\n!> Le fameux **baiser de l’Hôtel de Ville** est une photo **mise en scène**. Une image « spontanée » ne l’est pas toujours.\n\n| La notion | Ce qu’elle désigne |\n| Le **cadrage** | Ce qu’on garde, ce qu’on exclut |\n| L’**angle de prise de vue** | Plongée, contre-plongée |\n| La **profondeur de champ** | |\n| L’**instant décisif** | Cher à Cartier-Bresson |\n\n## Le cinéma\n| Le film | Sa ville |\n| *Metropolis* (Fritz Lang, 1927) | La ville **verticale** : ouvriers sous terre, maîtres au sommet |\n| *Blade Runner* (1982) | Il en hérite directement |\n| *La Haine* (1995) | La banlieue, filmée comme on avait filmé les quais et les faubourgs |\n\n| La notion | Ce qu’elle désigne |\n| L’**échelle de plan** | Plan général pour situer, gros plan pour l’émotion |\n| Le **travelling**, le **plan-séquence** | Le mouvement |\n| La **bande-son** | Le bruit d’une ville est déjà un récit |\n\n## La bande dessinée\n| L’auteur | Sa ville |\n| **Hergé** | Il documente Bruxelles, Shanghai, New York |\n| **Schuiten et Peeters** | *Les Cités obscures* : des villes inventées, personnages à part entière |\n| **Tardi** | Le Paris de 1914, reconstitué rue par rue |\n\n| La notion | Ce qu’elle désigne |\n| La **case** et sa taille | L’unité de lecture |\n| La **planche** | La composition d’ensemble |\n| La **bulle** et le **cartouche** | La parole et le texte du narrateur |\n| L’**ellipse** entre deux cases | Ce que le **lecteur** comble lui-même |', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('98996db6-7f9f-5276-81b2-c569c6c867f6'::uuid, 'Quiz — Vingt-cinq siècles pour dire « je t’aime »', 'Français', '4e', 'La poésie lyrique et amoureuse de l’Antiquité à nos jours', 'eaab7c70-0277-5a51-8ed0-d66d03328374'::uuid),
    ('e132fcb4-ff31-5aec-a94f-e66f59bf8aa1'::uuid, 'Quiz — Un poème d’amour qui est un poème de deuil', 'Français', '4e', '« Demain, dès l’aube… », Victor Hugo', 'a968fe8b-b52a-5588-b909-f7a52186e283'::uuid),
    ('11f8df83-c23c-5927-8ff7-42af4811bfe8'::uuid, 'Quiz — Aimer et renoncer', 'Français', '4e', 'La tragédie au XVIIe siècle : Bérénice de Racine', '943e7157-df1b-5416-a569-602abd7194e2'::uuid),
    ('22fde46a-211e-538e-8ad8-f0c896b1d915'::uuid, 'Quiz — Rire, mais pour dire quelque chose', 'Français', '4e', 'La comédie au XVIIIe siècle', '90df0ebf-e497-5343-8ae1-7d86b12fa4ca'::uuid),
    ('11f10d9c-242a-5e5f-98fb-6133c5923478'::uuid, 'Quiz — Deux déguisements, un même aveu', 'Français', '4e', 'Un exemple de comédie du XVIIIe siècle : Le Jeu de l’amour et du hasard, Marivaux', '38ee677d-858e-52a9-8d84-80e822475a08'::uuid),
    ('84102ba6-6d18-55b4-9ccd-5664830b1a52'::uuid, 'Quiz — Le théâtre romantique brise les règles', 'Français', '4e', 'Le drame du XIXe siècle : Lorenzaccio, Alfred de Musset', '256ecacb-cae7-5554-ba0f-76819bd0a65f'::uuid),
    ('8d20e311-8a15-5fee-9755-aed5143fb367'::uuid, 'Quiz — L’honneur contre l’amour', 'Français', '4e', 'La tragi-comédie au XVIIe siècle : Le Cid, Corneille', '5539221b-a0e0-5d81-8496-34a271254cf1'::uuid),
    ('b084a9ab-63b9-558e-abb2-a1175533a742'::uuid, 'Quiz — Un récit court qui frappe fort', 'Français', '4e', 'La nouvelle du XVIIIe siècle à nos jours', '96dd1b4e-bed8-5783-9426-e3f86307dc5b'::uuid),
    ('da940e87-9dc8-5289-ae73-8a9345f169b7'::uuid, 'Quiz — Le roman comme enquête sociale', 'Français', '4e', 'Un roman naturaliste : L’Assommoir de Zola', '07c147f3-7995-5255-9098-9e3412d2835d'::uuid),
    ('7af5bf8d-528f-566a-a974-ef15f6f73e73'::uuid, 'Quiz — Dix ans de misère pour un bijou faux', 'Français', '4e', 'Une nouvelle réaliste : « La Parure » de Maupassant et l’adaptation éponyme de Claude Chabrol', '96b89670-84cc-5533-a0bd-c96684e88730'::uuid),
    ('efc6493b-a5c3-5b71-ac25-181b5fb94074'::uuid, 'Quiz — Quand la maison et la famille s’effondrent ensemble', 'Français', '4e', 'Une nouvelle fantastique : « La Chute de la maison Usher » d’Edgar Allan Poe', 'ce72b0b3-6b46-5a50-a3c2-9bc221b8d37b'::uuid),
    ('029d706e-6b92-51f6-bb06-0fceda218555'::uuid, 'Quiz — Qui parle, d’où, et pour dire quoi ?', 'Français', '4e', 'Lire et comprendre la presse et les médias', '9083aed1-2a2b-58bd-b4f7-57f048abd040'::uuid),
    ('4266b09c-f867-5d4a-b96a-a99c8993c624'::uuid, 'Quiz — Reconnaître un discours qui veut faire penser', 'Français', '4e', 'Étude de textes et documents produits à des fins de propagande', '7e4e1113-609a-545a-a889-d3faa6e719d3'::uuid),
    ('dd384a65-6e2e-5292-aefa-087e465b7138'::uuid, 'Quiz — La fiction regarde ceux qui informent', 'Français', '4e', 'Le journalisme à travers les romans et les films du XIXe siècle à nos jours', '00a0b9db-3c62-5c0c-a700-af8fb71b8150'::uuid),
    ('c630a319-c461-579a-a74f-1ba4cf2338ad'::uuid, 'Quiz — Un décor qui devient un personnage', 'Français', '4e', 'La ville comme sujet de roman', 'b79cd4cc-588a-52f2-b017-a33ea4678e2c'::uuid),
    ('075ce4d2-072d-5d6c-90e2-2cb9d643b3a3'::uuid, 'Quiz — De la laideur, faire un poème', 'Français', '4e', 'La ville comme objet poétique', '15457769-8d94-551f-a753-e9fd3c178022'::uuid),
    ('f9a12b39-2235-541e-9d4c-9282f050b100'::uuid, 'Quiz — Le crime a besoin d’une foule', 'Français', '4e', 'L’importance de la ville dans le roman policier', '4b43250c-f18f-5338-a266-3b2326f892f3'::uuid),
    ('97bcdad8-2a45-5017-819b-7270ddffbacd'::uuid, 'Quiz — Cadrer la ville, c’est déjà la raconter', 'Français', '4e', 'La ville dans la photographie, les films et la bande-dessinée', 'a8273617-e430-5768-9177-fd7caa56b0ba'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('2dc2b921-9320-57c9-9896-38ac6795ee89'::uuid, '98996db6-7f9f-5276-81b2-c569c6c867f6'::uuid, 'D’où vient le nom de la poésie lyrique ?', 'mcq', '["De la lyre, l’instrument des poètes grecs","Du grec « lyros », qui signifie amour","Du nom du poète Lyrios","Du mot « lire »"]'::jsonb, 0, 'À l’origine, cette poésie se chantait.', 1),
    ('acbdc652-1110-517c-a3cb-4925361b5a7d'::uuid, '98996db6-7f9f-5276-81b2-c569c6c867f6'::uuid, 'Qu’exprime la poésie lyrique ?', 'mcq', '["Les sentiments personnels du poète","Les exploits des héros","Les règles de la société","Des récits historiques"]'::jsonb, 0, 'Le « je » y est omniprésent.', 2),
    ('27ede890-115a-5fab-9b32-6c1869ed52c8'::uuid, '98996db6-7f9f-5276-81b2-c569c6c867f6'::uuid, 'Quelle poétesse grecque du VIe siècle avant J.-C. chante le trouble amoureux ?', 'mcq', '["Sappho","Antigone","Louise Labé","Marie de France"]'::jsonb, 0, 'Elle vivait sur l’île de Lesbos.', 3),
    ('a4b3e4dd-160f-5652-931e-204303390472'::uuid, '98996db6-7f9f-5276-81b2-c569c6c867f6'::uuid, 'Qu’est-ce que l’amour courtois ?', 'mcq', '["Le service d’une dame inaccessible par le poète","Un mariage arrangé à la cour","Un amour partagé et heureux","Une déclaration faite devant le roi"]'::jsonb, 0, 'Les troubadours l’inventent au Moyen Âge.', 4),
    ('e78251c6-3260-5969-9e93-168e185a18d8'::uuid, '98996db6-7f9f-5276-81b2-c569c6c867f6'::uuid, 'Quel poète du XVIe siècle a écrit « Mignonne, allons voir si la rose… » ?', 'mcq', '["Ronsard","Hugo","Musset","Apollinaire"]'::jsonb, 0, 'Il appartient à la Pléiade.', 5),
    ('0cca8cf1-5a6d-5167-b682-669e6f585d37'::uuid, '98996db6-7f9f-5276-81b2-c569c6c867f6'::uuid, 'Combien de vers compte un sonnet ?', 'mcq', '["14","12","10","16"]'::jsonb, 0, 'Deux quatrains suivis de deux tercets.', 6),
    ('b01a642f-4fe2-57e7-be72-2d78c77e6a75'::uuid, '98996db6-7f9f-5276-81b2-c569c6c867f6'::uuid, 'Quelle figure de style consiste à s’adresser directement à un être ou à une chose ?', 'mcq', '["L’apostrophe","La métaphore","L’antithèse","L’allitération"]'::jsonb, 0, '« Ô temps, suspends ton vol ! »', 7),
    ('5cbd5a10-560d-5207-b6a2-5f052ed437dd'::uuid, '98996db6-7f9f-5276-81b2-c569c6c867f6'::uuid, 'La poésie lyrique est un genre né au XIXe siècle.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle remonte à l’Antiquité grecque, avec Sappho.', 8),
    ('821f9ac8-ba49-5c2e-81a4-5a315bf62a40'::uuid, 'e132fcb4-ff31-5aec-a94f-e66f59bf8aa1'::uuid, 'Dans quel recueil « Demain, dès l’aube… » a-t-il été publié ?', 'mcq', '["Les Contemplations","Les Misérables","Les Fleurs du mal","Les Rayons et les Ombres"]'::jsonb, 0, 'Publié en 1856.', 1),
    ('28801e78-87f7-5acd-9ff4-dcda9b2ef952'::uuid, 'e132fcb4-ff31-5aec-a94f-e66f59bf8aa1'::uuid, 'À qui ce poème est-il adressé ?', 'mcq', '["À Léopoldine, la fille du poète, morte noyée","À une femme aimée","À la France","À un ami disparu"]'::jsonb, 0, 'Elle s’est noyée à 19 ans à Villequier, en 1843.', 2),
    ('58302433-6cf4-5fe5-9395-2bfe3c2da938'::uuid, 'e132fcb4-ff31-5aec-a94f-e66f59bf8aa1'::uuid, 'Quelle est la forme du poème ?', 'mcq', '["Trois quatrains d’alexandrins en rimes croisées","Un sonnet","Un poème en prose","Quatre tercets en vers libres"]'::jsonb, 0, 'Une forme simple, presque nue.', 3),
    ('26f688c0-ee1d-55d0-b491-40f988d79597'::uuid, 'e132fcb4-ff31-5aec-a94f-e66f59bf8aa1'::uuid, 'Quel mot du dernier vers renverse le sens du poème ?', 'mcq', '["« tombe »","« bouquet »","« bruyère »","« aube »"]'::jsonb, 0, 'Le lecteur croyait lire un poème d’amour.', 4),
    ('6fef855d-ba40-5226-8178-4ad30f2abccc'::uuid, 'e132fcb4-ff31-5aec-a94f-e66f59bf8aa1'::uuid, 'Quel temps domine dans le poème ?', 'mcq', '["Le futur","Le passé simple","L’imparfait","Le présent"]'::jsonb, 0, 'Il rend le voyage inéluctable.', 5),
    ('d1af8090-f23a-5fc2-9d74-bceadc494a7f'::uuid, 'e132fcb4-ff31-5aec-a94f-e66f59bf8aa1'::uuid, 'Que refuse de regarder le poète pendant son voyage ?', 'mcq', '["L’or du soir et les voiles descendant vers Harfleur","La foule sur les routes","La mer et le ciel","Les maisons du village"]'::jsonb, 0, 'Les négations montrent qu’il s’est fermé au monde.', 6),
    ('d5129f56-fedf-5ad7-9f21-ba42e372fdb3'::uuid, 'e132fcb4-ff31-5aec-a94f-e66f59bf8aa1'::uuid, 'Que dépose le poète sur la tombe ?', 'mcq', '["Un bouquet de houx vert et de bruyère en fleur","Une rose blanche","Une couronne de lauriers","Une lettre"]'::jsonb, 0, 'Le houx persistant et la bruyère fragile : fidélité et deuil.', 7),
    ('9e723703-4137-5ee1-b83c-3f1574842b96'::uuid, 'e132fcb4-ff31-5aec-a94f-e66f59bf8aa1'::uuid, 'Le poème nomme explicitement la mort de Léopoldine.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il ne dit ni « fille » ni « mort » : c’est cette retenue qui fait sa force.', 8),
    ('0e474cfa-2629-55a9-b4b4-13db3b24c5c6'::uuid, '11f8df83-c23c-5927-8ff7-42af4811bfe8'::uuid, 'En quoi consiste la règle des trois unités ?', 'mcq', '["Une seule action, un seul lieu, une seule journée","Trois actes, trois personnages, trois lieux","Trois unités de temps de trois heures","Une unité de ton, de style et de genre"]'::jsonb, 0, 'C’est la règle centrale du théâtre classique.', 1),
    ('b8305577-1d96-5bcc-9da9-5a14cc57f66e'::uuid, '11f8df83-c23c-5927-8ff7-42af4811bfe8'::uuid, 'Que signifie la règle de bienséance ?', 'mcq', '["Ni sang ni violence ne doivent être montrés sur scène","Les personnages doivent être polis","La pièce doit bien finir","Le public doit rester silencieux"]'::jsonb, 0, 'Les morts sont racontées, jamais représentées.', 2),
    ('d785c4bd-536a-525f-83fd-54e3590ce6a1'::uuid, '11f8df83-c23c-5927-8ff7-42af4811bfe8'::uuid, 'Qu’est-ce que la catharsis ?', 'mcq', '["La purgation des passions du spectateur par la terreur et la pitié","Le dénouement heureux d’une pièce","Le monologue final du héros","La règle de l’unité de lieu"]'::jsonb, 0, 'La notion vient d’Aristote.', 3),
    ('d68f9aae-3371-58c2-b608-c12ba9232f7a'::uuid, '11f8df83-c23c-5927-8ff7-42af4811bfe8'::uuid, 'Pourquoi Titus renonce-t-il à Bérénice ?', 'mcq', '["Parce que Rome interdit à son empereur d’épouser une reine étrangère","Parce qu’il ne l’aime plus","Parce qu’elle en aime un autre","Parce qu’elle est morte"]'::jsonb, 0, 'C’est le conflit entre l’amour et le devoir.', 4),
    ('27ff3375-8eec-5206-9d75-92addd34a9ff'::uuid, '11f8df83-c23c-5927-8ff7-42af4811bfe8'::uuid, 'Qui est Antiochus dans la pièce ?', 'mcq', '["Le roi de Comagène, ami de Titus, qui aime Bérénice en secret","Le père de Bérénice","Un sénateur romain","Le rival militaire de Titus"]'::jsonb, 0, 'Il forme le troisième sommet du triangle.', 5),
    ('643fa758-6990-5f55-8203-4e49469d6c87'::uuid, '11f8df83-c23c-5927-8ff7-42af4811bfe8'::uuid, 'Comment s’achève Bérénice ?', 'mcq', '["Par un triple renoncement, sans aucune mort","Par le suicide de Bérénice","Par le mariage des deux amants","Par la mort de Titus"]'::jsonb, 0, 'Racine prouve qu’une tragédie n’exige ni sang ni morts.', 6),
    ('f64002f8-143d-502d-8b77-4f0e483825b6'::uuid, '11f8df83-c23c-5927-8ff7-42af4811bfe8'::uuid, 'Quel vers l’alexandrin compte-t-il ?', 'mcq', '["Douze syllabes","Dix syllabes","Huit syllabes","Quatorze syllabes"]'::jsonb, 0, 'La tragédie classique s’écrit en alexandrins à rimes plates.', 7),
    ('e7f1ea5f-3d11-5d0e-b7ef-b93e44be32f9'::uuid, '11f8df83-c23c-5927-8ff7-42af4811bfe8'::uuid, 'Le héros tragique dispose toujours d’une issue favorable.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'C’est justement l’absence d’issue qui définit le tragique.', 8),
    ('747bd55e-f712-5b8d-826e-be92258be56f'::uuid, '22fde46a-211e-538e-8ad8-f0c896b1d915'::uuid, 'Quel dramaturge du XVIIe siècle la comédie du XVIIIe prend-elle pour modèle ?', 'mcq', '["Molière","Racine","Corneille","Voltaire"]'::jsonb, 0, 'Types et procédés comiques lui sont hérités.', 1),
    ('0adee0eb-b852-5dde-a8b8-fffeb9933377'::uuid, '22fde46a-211e-538e-8ad8-f0c896b1d915'::uuid, 'Qu’est-ce qu’un quiproquo ?', 'mcq', '["Un malentendu où l’on prend une chose ou une personne pour une autre","Un jeu de mots","Une chute sur scène","Un monologue adressé au public"]'::jsonb, 0, 'C’est un comique de situation.', 2),
    ('476e7dae-48a0-5a17-8fbc-6700ebf0e6cf'::uuid, '22fde46a-211e-538e-8ad8-f0c896b1d915'::uuid, 'Comment évolue le rôle du valet au XVIIIe siècle ?', 'mcq', '["Il devient l’égal intellectuel de son maître, souvent plus lucide","Il disparaît de la scène","Il devient muet","Il ne fait plus rire du tout"]'::jsonb, 0, 'Figaro en est l’aboutissement.', 3),
    ('a991ff7f-8ce3-5b23-8348-7fc8345461ad'::uuid, '22fde46a-211e-538e-8ad8-f0c896b1d915'::uuid, 'Qu’appelle-t-on le marivaudage ?', 'mcq', '["Un dialogue léger et spirituel où les personnages avancent masqués","Une farce grossière","Un long monologue tragique","Une critique politique directe"]'::jsonb, 0, 'Le spectateur comprend avant les personnages.', 4),
    ('eeaf8eff-ba1d-58b5-8181-f8f871c1eb76'::uuid, '22fde46a-211e-538e-8ad8-f0c896b1d915'::uuid, 'Quel est l’obstacle principal à l’amour chez Marivaux ?', 'mcq', '["L’amour-propre des personnages","L’opposition du père","La différence de religion","La guerre"]'::jsonb, 0, 'Ils refusent de reconnaître leur sentiment.', 5),
    ('db0fb488-1fde-50bb-b950-f3ceefd6d4e7'::uuid, '22fde46a-211e-538e-8ad8-f0c896b1d915'::uuid, 'Quelle pièce de Beaumarchais fut d’abord interdite par Louis XVI ?', 'mcq', '["Le Mariage de Figaro","Le Jeu de l’amour et du hasard","Bérénice","L’Assommoir"]'::jsonb, 0, 'Sa critique sociale était jugée trop hardie.', 6),
    ('f4ba9ecd-32c7-55c8-ba6f-8621888d36ab'::uuid, '22fde46a-211e-538e-8ad8-f0c896b1d915'::uuid, 'Qu’est-ce que la comédie sensible ?', 'mcq', '["Une comédie qui mêle le rire et l’émotion","Une comédie sans dialogue","Une comédie en un seul acte","Une comédie jouée sans décor"]'::jsonb, 0, 'Elle prépare le drame du siècle suivant.', 7),
    ('c71485e3-8453-57fe-b451-8f26ec1a2f7e'::uuid, '22fde46a-211e-538e-8ad8-f0c896b1d915'::uuid, 'La comédie du XVIIIe siècle se contente de faire rire, sans critiquer la société.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Sous l’influence des Lumières, la critique sociale y devient centrale.', 8),
    ('f665f6d2-2497-5433-9e3a-330f5dbf17d5'::uuid, '11f10d9c-242a-5e5f-98fb-6133c5923478'::uuid, 'En quelle année Le Jeu de l’amour et du hasard a-t-il été créé ?', 'mcq', '["1730","1670","1784","1856"]'::jsonb, 0, 'C’est une comédie en trois actes et en prose.', 1),
    ('a0420c1f-99aa-552a-9d22-e9597440484e'::uuid, '11f10d9c-242a-5e5f-98fb-6133c5923478'::uuid, 'Pourquoi Silvia échange-t-elle son rôle avec sa servante ?', 'mcq', '["Pour observer son futur époux sans être reconnue","Pour fuir le mariage","Pour punir Lisette","Pour obéir à son père"]'::jsonb, 0, 'Dorante a eu exactement la même idée.', 2),
    ('b65e6d6e-be93-5ddb-85c8-85ed16d0d246'::uuid, '11f10d9c-242a-5e5f-98fb-6133c5923478'::uuid, 'Comment s’appelle le valet de Dorante ?', 'mcq', '["Arlequin","Mario","Orgon","Figaro"]'::jsonb, 0, 'Il joue le rôle du maître pendant que Dorante joue le valet.', 3),
    ('8f7a5f6f-df8d-5b31-9528-4fc3e049ffa6'::uuid, '11f10d9c-242a-5e5f-98fb-6133c5923478'::uuid, 'Qu’est-ce que le double registre dans cette pièce ?', 'mcq', '["Le public sait ce que les personnages ignorent","Les personnages parlent deux langues","La pièce mêle vers et prose","Deux intrigues se déroulent en parallèle"]'::jsonb, 0, 'C’est le ressort comique principal.', 4),
    ('51d3a42c-0e30-57f5-a8a9-1b83ace0920f'::uuid, '11f10d9c-242a-5e5f-98fb-6133c5923478'::uuid, 'Quel est le véritable sujet de la pièce ?', 'mcq', '["L’épreuve du sentiment face au préjugé social","La lutte pour le pouvoir","La critique de la religion","La guerre entre deux familles"]'::jsonb, 0, 'Chacun doit choisir entre son cœur et son rang.', 5),
    ('1f774d6b-461c-579e-9f83-eb152bfb2f2d'::uuid, '11f10d9c-242a-5e5f-98fb-6133c5923478'::uuid, 'Qui révèle son identité le premier ?', 'mcq', '["Dorante","Silvia","Arlequin","Lisette"]'::jsonb, 0, 'Silvia prolonge l’épreuve pour être aimée pour elle-même.', 6),
    ('188e7b2e-a1b4-5cc4-bf93-a35a862b9875'::uuid, '11f10d9c-242a-5e5f-98fb-6133c5923478'::uuid, 'Qu’est-ce qu’un aparté ?', 'mcq', '["Une réplique adressée au public que les autres personnages n’entendent pas","Un monologue en fin d’acte","Un dialogue en coulisses","Une didascalie"]'::jsonb, 0, 'Marivaux en use abondamment.', 7),
    ('39b16741-88f3-5a5c-87b5-ae1ad740a7e6'::uuid, '11f10d9c-242a-5e5f-98fb-6133c5923478'::uuid, 'À la fin de la pièce, l’ordre social est renversé.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Maîtres et valets se marient chacun dans leur condition.', 8),
    ('a43d25f9-3569-5764-9c9e-f2ec1c0bdfc8'::uuid, '84102ba6-6d18-55b4-9ccd-5664830b1a52'::uuid, 'Dans quel texte Victor Hugo théorise-t-il le drame romantique ?', 'mcq', '["La Préface de Cromwell","Les Contemplations","La Préface de Bérénice","L’Art poétique"]'::jsonb, 0, 'Publiée en 1827.', 1),
    ('df621411-e182-538d-929d-523e739cc0c3'::uuid, '84102ba6-6d18-55b4-9ccd-5664830b1a52'::uuid, 'Quelle règle classique le drame romantique rejette-t-il ?', 'mcq', '["La règle des trois unités","L’usage de la prose","La présence d’un héros","La division en actes"]'::jsonb, 0, 'Il multiplie lieux, époques et intrigues.', 2),
    ('bb83920e-8e1c-5c5f-a060-213d22b9374f'::uuid, '84102ba6-6d18-55b4-9ccd-5664830b1a52'::uuid, 'Que mélange le drame romantique ?', 'mcq', '["Le sublime et le grotesque, le comique et le tragique","Le théâtre et le roman","La poésie et la musique","Le français et le latin"]'::jsonb, 0, 'Hugo en fait le principe même du genre.', 3),
    ('53a8662b-8ef4-59cf-b3bb-8d719ce250d5'::uuid, '84102ba6-6d18-55b4-9ccd-5664830b1a52'::uuid, 'En quelle année Lorenzaccio a-t-il été écrit ?', 'mcq', '["1834","1827","1896","1730"]'::jsonb, 0, 'Jugée injouable, la pièce ne sera créée qu’en 1896.', 4),
    ('5852afab-fdb8-5827-aef7-c3b5517d997d'::uuid, '84102ba6-6d18-55b4-9ccd-5664830b1a52'::uuid, 'Qui Lorenzo assassine-t-il ?', 'mcq', '["Alexandre de Médicis, le tyran de Florence","Côme de Médicis","Son propre père","Le duc de Milan"]'::jsonb, 0, 'Il prépare ce meurtre depuis des années.', 5),
    ('80e8804a-613d-5ded-8695-e948129ec96e'::uuid, '84102ba6-6d18-55b4-9ccd-5664830b1a52'::uuid, 'Que se passe-t-il après le meurtre ?', 'mcq', '["Rien ne change : un autre Médicis est élu","Florence devient une république","Lorenzo prend le pouvoir","Le peuple se soulève"]'::jsonb, 0, 'C’est l’échec total de l’engagement.', 6),
    ('28ce7fd7-4a62-5ac2-a4f4-476c2d1e26e2'::uuid, '84102ba6-6d18-55b4-9ccd-5664830b1a52'::uuid, 'Que signifie la réplique « Le vice a été pour moi un vêtement ; maintenant il est collé à ma peau » ?', 'mcq', '["À force de jouer le débauché, Lorenzo l’est devenu","Lorenzo regrette sa richesse","Lorenzo se déguise pour fuir","Lorenzo accuse le tyran"]'::jsonb, 0, 'Le masque a dévoré le visage.', 7),
    ('11035b7f-bb4e-50db-bd90-5de9c6fec135'::uuid, '84102ba6-6d18-55b4-9ccd-5664830b1a52'::uuid, 'Lorenzaccio a été jouée dès sa publication.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Jugée injouable, elle attend 1896 et Sarah Bernhardt.', 8),
    ('ef122a82-af65-5174-beb3-65d58e63144b'::uuid, '8d20e311-8a15-5fee-9755-aed5143fb367'::uuid, 'Pourquoi Le Cid est-il d’abord appelé tragi-comédie ?', 'mcq', '["Il a la gravité d’une tragédie mais une fin heureuse","Il alterne scènes comiques et tragiques","Il est joué par des comédiens amateurs","Il mêle vers et prose"]'::jsonb, 0, 'Corneille le rebaptisera « tragédie » en 1648.', 1),
    ('56dc5b4b-70a1-529d-a686-5abd6db0ca79'::uuid, '8d20e311-8a15-5fee-9755-aed5143fb367'::uuid, 'Pourquoi Rodrigue doit-il tuer le père de Chimène ?', 'mcq', '["Parce que celui-ci a giflé son propre père, trop vieux pour se venger","Parce qu’il convoite sa fortune","Parce que le roi le lui ordonne","Parce qu’il l’a trahi à la guerre"]'::jsonb, 0, 'L’honneur familial exige réparation.', 2),
    ('6087d75a-cba9-548f-8cb8-13afdf423466'::uuid, '8d20e311-8a15-5fee-9755-aed5143fb367'::uuid, 'Qu’est-ce qu’un dilemme cornélien ?', 'mcq', '["Un choix entre deux valeurs également hautes, impossibles à concilier","Un choix entre le bien et le mal","Une hésitation entre deux amours","Un pari sur l’avenir"]'::jsonb, 0, 'Quel que soit le choix, le héros perd quelque chose d’essentiel.', 3),
    ('eb804fbb-6101-5324-bd89-07856a486451'::uuid, '8d20e311-8a15-5fee-9755-aed5143fb367'::uuid, 'Comment appelle-t-on le monologue de Rodrigue à l’acte I ?', 'mcq', '["Les stances","L’aparté","La tirade des Maures","Le prologue"]'::jsonb, 0, '« Percé jusques au fond du cœur… »', 4),
    ('9212d09e-d2e6-5998-86ca-15dacd1d276d'::uuid, '8d20e311-8a15-5fee-9755-aed5143fb367'::uuid, 'Pourquoi Rodrigue est-il surnommé « le Cid » ?', 'mcq', '["Parce qu’il a vaincu les Maures, qui le nomment « le seigneur »","Parce que c’est son nom de naissance","Parce que le roi le lui a donné à sa naissance","Parce qu’il est le fils de Don Diègue"]'::jsonb, 0, 'Le mot vient de l’arabe et signifie « seigneur ».', 5),
    ('d85167db-c2ab-5f14-b935-15dcdc69cf5f'::uuid, '8d20e311-8a15-5fee-9755-aed5143fb367'::uuid, 'Qu’est-ce qui définit le héros cornélien ?', 'mcq', '["Sa volonté : il choisit et grandit par son choix","Sa passion, qu’il subit","Sa naissance illustre","Sa ruse"]'::jsonb, 0, 'C’est ce qui le distingue du héros racinien.', 6),
    ('c3638ef2-697c-5c0a-b707-fa304dfe9146'::uuid, '8d20e311-8a15-5fee-9755-aed5143fb367'::uuid, 'Qu’est-ce que la querelle du Cid ?', 'mcq', '["La polémique sur le respect des unités et de la bienséance dans la pièce","Un duel entre Corneille et Racine","Un procès intenté à Corneille","Une dispute entre deux troupes de théâtre"]'::jsonb, 0, 'Elle contribua à fixer les règles du théâtre classique.', 7),
    ('617cee0c-c098-508a-a5f4-0ffe3b8f71e3'::uuid, '8d20e311-8a15-5fee-9755-aed5143fb367'::uuid, 'Le Cid se termine par la mort des deux amants.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Le roi accorde un délai d’un an : la fin reste ouverte et heureuse.', 8),
    ('e7e8618e-9610-5f42-b44c-73924f06c8c4'::uuid, 'b084a9ab-63b9-558e-abb2-a1175533a742'::uuid, 'Qu’est-ce qui distingue une nouvelle d’un roman ?', 'mcq', '["Sa brièveté, son intrigue resserrée et sa chute","Sa forme versifiée","Son sujet toujours historique","Son absence de personnages"]'::jsonb, 0, 'Le roman prend son temps, la nouvelle vise.', 1),
    ('0a3b2684-8f7a-5daa-98a8-19d30efd1ac9'::uuid, 'b084a9ab-63b9-558e-abb2-a1175533a742'::uuid, 'Qu’est-ce que la chute d’une nouvelle ?', 'mcq', '["Une fin brève et frappante, qui retourne souvent le sens du récit","Le moment le plus dramatique du milieu","La description du décor","Le premier paragraphe"]'::jsonb, 0, 'Elle est toujours préparée par des indices.', 2),
    ('1c6dd4a8-527c-59b6-a117-7e096b3d25d4'::uuid, 'b084a9ab-63b9-558e-abb2-a1175533a742'::uuid, 'Quel auteur du XVIIIe siècle a fait du récit bref un outil philosophique ?', 'mcq', '["Voltaire","Maupassant","Poe","Zola"]'::jsonb, 0, 'Candide et Micromégas sont des contes philosophiques.', 3),
    ('8a536afc-4c43-56d4-a2a7-bdf1046bba29'::uuid, 'b084a9ab-63b9-558e-abb2-a1175533a742'::uuid, 'Quel siècle est l’âge d’or de la nouvelle en France ?', 'mcq', '["Le XIXe siècle","Le XVIIe siècle","Le XVIIIe siècle","Le XXe siècle"]'::jsonb, 0, 'La presse en publiait chaque semaine.', 4),
    ('754db117-c008-52f8-bf43-a22f85d2880d'::uuid, 'b084a9ab-63b9-558e-abb2-a1175533a742'::uuid, 'Quelle nouvelle fantastique Maupassant a-t-il écrite ?', 'mcq', '["Le Horla","La Parure","Boule de Suif","La Vénus d’Ille"]'::jsonb, 0, 'La Vénus d’Ille est de Mérimée.', 5),
    ('52f751a8-1604-530f-8bae-4e0d1eb7987c'::uuid, 'b084a9ab-63b9-558e-abb2-a1175533a742'::uuid, 'Que caractérise le registre fantastique ?', 'mcq', '["L’irruption de l’inexplicable dans un cadre réaliste","L’acceptation du surnaturel comme allant de soi","La peinture fidèle du réel","L’enquête policière"]'::jsonb, 0, 'Dans le merveilleux, au contraire, le surnaturel ne surprend personne.', 6),
    ('18688357-0079-5a7d-af59-5197a4a2c4c4'::uuid, 'b084a9ab-63b9-558e-abb2-a1175533a742'::uuid, 'Quel écrivain russe est un maître de la nouvelle ?', 'mcq', '["Tchekhov","Balzac","Bradbury","Buzzati"]'::jsonb, 0, 'Ses nouvelles peignent le quotidien avec une précision aiguë.', 7),
    ('9672795b-4aae-52e2-bc54-5cf09bf44ce8'::uuid, 'b084a9ab-63b9-558e-abb2-a1175533a742'::uuid, 'Une nouvelle peut comporter autant de personnages qu’un roman.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Sa brièveté impose peu de personnages, décrits en quelques traits.', 8),
    ('bde8f657-2436-5268-8d8c-341bdbcb1ee4'::uuid, 'da940e87-9dc8-5289-ae73-8a9345f169b7'::uuid, 'Qui a fondé le naturalisme ?', 'mcq', '["Émile Zola","Gustave Flaubert","Honoré de Balzac","Guy de Maupassant"]'::jsonb, 0, 'Il l’expose dans Le Roman expérimental.', 1),
    ('83bea1b1-4355-526e-90b0-b81362ef6268'::uuid, 'da940e87-9dc8-5289-ae73-8a9345f169b7'::uuid, 'Qu’est-ce qui distingue le naturalisme du réalisme ?', 'mcq', '["Il applique au roman la méthode scientifique, étudiant l’hérédité et le milieu","Il idéalise la réalité","Il refuse toute documentation","Il ne peint que la bourgeoisie"]'::jsonb, 0, 'Le romancier y est « observateur et expérimentateur ».', 2),
    ('bc3aabed-55ff-511c-b87e-32a22bc2d682'::uuid, 'da940e87-9dc8-5289-ae73-8a9345f169b7'::uuid, 'Comment s’appelle le cycle romanesque de Zola ?', 'mcq', '["Les Rougon-Macquart","La Comédie humaine","Les Misérables","Les Contemplations"]'::jsonb, 0, 'Vingt romans sur cinq générations d’une même famille.', 3),
    ('d58ce8c4-9131-5ce6-8819-53ea9ae3a8c9'::uuid, 'da940e87-9dc8-5289-ae73-8a9345f169b7'::uuid, 'Quel est le sujet de L’Assommoir ?', 'mcq', '["La vie et la déchéance d’une blanchisseuse dans le monde ouvrier","La montée d’un banquier","La guerre de 1870","La vie d’une comédienne"]'::jsonb, 0, 'C’est le premier grand roman français sur le monde ouvrier.', 4),
    ('fbc34b53-a734-5ded-ab9a-0b9222c53c18'::uuid, 'da940e87-9dc8-5289-ae73-8a9345f169b7'::uuid, 'Que désigne le mot « assommoir » ?', 'mcq', '["Un débit d’alcool populaire","Un atelier de blanchisserie","Un immeuble ouvrier","Un outil de zingueur"]'::jsonb, 0, 'La boutique du père Colombe, où travaille l’alambic.', 5),
    ('59f2a20b-e932-5206-b35e-bca395508e54'::uuid, 'da940e87-9dc8-5289-ae73-8a9345f169b7'::uuid, 'Comment s’appelle l’héroïne de L’Assommoir ?', 'mcq', '["Gervaise Macquart","Nana","Emma Bovary","Chimène"]'::jsonb, 0, 'Sa fille Nana sera l’héroïne d’un autre roman du cycle.', 6),
    ('43a85802-35dd-562c-bf3f-28545b0e2ec5'::uuid, 'da940e87-9dc8-5289-ae73-8a9345f169b7'::uuid, 'Qu’est-ce qui a fait scandale dans L’Assommoir ?', 'mcq', '["L’entrée de la langue populaire, argot compris, jusque dans la narration","La présence de personnages historiques","Sa longueur excessive","Son absence de dialogue"]'::jsonb, 0, 'Le roman fut accusé de complaisance dans la misère.', 7),
    ('113499ee-206f-554a-9e8a-0e94788651f2'::uuid, 'da940e87-9dc8-5289-ae73-8a9345f169b7'::uuid, 'Zola condamne moralement son héroïne.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il montre comment le milieu défait une femme courageuse.', 8),
    ('64759814-00d1-5389-b1c5-e5e74ff58125'::uuid, '7af5bf8d-528f-566a-a974-ef15f6f73e73'::uuid, 'Quel bijou Mathilde emprunte-t-elle ?', 'mcq', '["Une rivière de diamants","Un collier de perles","Une bague en or","Une broche de saphirs"]'::jsonb, 0, 'Elle appartient à son amie Madame Forestier.', 1),
    ('893d1881-328d-523b-91e5-5cdd67664a89'::uuid, '7af5bf8d-528f-566a-a974-ef15f6f73e73'::uuid, 'Combien de temps le couple Loisel met-il à rembourser la parure ?', 'mcq', '["Dix ans","Un an","Trois ans","Vingt ans"]'::jsonb, 0, 'Ces dix années sont condensées en une ellipse.', 2),
    ('59f4a746-5ebb-5cc0-8150-50746392a9ba'::uuid, '7af5bf8d-528f-566a-a974-ef15f6f73e73'::uuid, 'Quelle est la chute de la nouvelle ?', 'mcq', '["La parure empruntée était fausse","Mathilde retrouve le bijou perdu","Madame Forestier était ruinée","Le mari de Mathilde avait volé le bijou"]'::jsonb, 0, 'Elle valait au plus cinq cents francs.', 3),
    ('a7adc5a4-56a5-5ec2-9eef-2cc5a8f37b1f'::uuid, '7af5bf8d-528f-566a-a974-ef15f6f73e73'::uuid, 'Qu’est-ce qu’une ellipse dans un récit ?', 'mcq', '["Le passage sous silence d’une période de temps","Une description très détaillée","Un dialogue rapporté","Un retour en arrière"]'::jsonb, 0, 'Les dix années de remboursement tiennent en un paragraphe.', 4),
    ('9c50d750-cc4c-533d-b3b9-f4f3a6c3887a'::uuid, '7af5bf8d-528f-566a-a974-ef15f6f73e73'::uuid, 'Quel type de narrateur Maupassant emploie-t-il ?', 'mcq', '["Un narrateur externe, à la troisième personne","Un narrateur personnage","Un narrateur à la deuxième personne","Plusieurs narrateurs successifs"]'::jsonb, 0, 'Il rapporte sans commenter.', 5),
    ('5c4f0582-fe67-54dd-aed0-7416b98f10ea'::uuid, '7af5bf8d-528f-566a-a974-ef15f6f73e73'::uuid, 'Que dénonce la nouvelle ?', 'mcq', '["Le poids des apparences dans la société","La corruption des ministères","La guerre franco-prussienne","L’exploitation des ouvriers"]'::jsonb, 0, 'Une faute minuscule y entraîne une punition démesurée.', 6),
    ('8396ae0b-caba-5406-afe2-826f64fe1f25'::uuid, '7af5bf8d-528f-566a-a974-ef15f6f73e73'::uuid, 'Qui a réalisé l’adaptation télévisée de « La Parure » en 2007 ?', 'mcq', '["Claude Chabrol","François Truffaut","Jean Renoir","Louis Malle"]'::jsonb, 0, 'Dans la collection Chez Maupassant.', 7),
    ('fd6b8ed5-6bc4-5650-b786-3fedf30dd238'::uuid, '7af5bf8d-528f-566a-a974-ef15f6f73e73'::uuid, 'La chute de « La Parure » arrive sans aucun indice préalable.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'La boîte qui n’est pas d’origine et le bijoutier qui ne reconnaît pas la parure l’annonçaient.', 8),
    ('7d1bd550-13ec-53fd-a72f-e61d63c45bd6'::uuid, 'efc6493b-a5c3-5b71-ac25-181b5fb94074'::uuid, 'Qu’est-ce qui caractérise le récit fantastique ?', 'mcq', '["L’hésitation entre une explication rationnelle et le surnaturel","L’acceptation du surnaturel comme allant de soi","L’explication scientifique de l’étrange","L’absence de tout événement étrange"]'::jsonb, 0, 'C’est ce qui le distingue du merveilleux et de la science-fiction.', 1),
    ('53fab131-4159-5d12-8e6f-82958db6afd8'::uuid, 'efc6493b-a5c3-5b71-ac25-181b5fb94074'::uuid, 'Qui est Roderick Usher ?', 'mcq', '["Le dernier héritier d’une famille éteinte, ami du narrateur","Le médecin du village","Le père du narrateur","Un aubergiste"]'::jsonb, 0, 'Il est hypersensible et terrifié par les sensations.', 2),
    ('9e6f9c9e-629b-5e22-818f-89b4e61eaef6'::uuid, 'efc6493b-a5c3-5b71-ac25-181b5fb94074'::uuid, 'Que devient Madeline Usher ?', 'mcq', '["Elle est enterrée vivante et reparaît","Elle s’enfuit de la maison","Elle épouse le narrateur","Elle disparaît sans laisser de trace"]'::jsonb, 0, 'Elle entraîne son frère dans la mort.', 3),
    ('b0d55719-a43c-58fd-a950-378803d93a28'::uuid, 'efc6493b-a5c3-5b71-ac25-181b5fb94074'::uuid, 'Que se passe-t-il à la fin de la nouvelle ?', 'mcq', '["La maison se fend et sombre dans l’étang","Le narrateur hérite du domaine","La maison est vendue","Madeline survit seule"]'::jsonb, 0, 'La lignée et le bâtiment s’effondrent ensemble.', 4),
    ('cd9d6b21-bc1f-5d17-8055-225fdc8153a2'::uuid, 'efc6493b-a5c3-5b71-ac25-181b5fb94074'::uuid, 'Qu’est-ce qu’un modalisateur ?', 'mcq', '["Un mot qui exprime le doute, comme « il me sembla » ou « peut-être »","Un adjectif qui décrit un décor","Un verbe de mouvement","Un signe de ponctuation"]'::jsonb, 0, 'Il maintient l’hésitation propre au fantastique.', 5),
    ('42ffad63-cc5e-5d27-a05c-c233294319b2'::uuid, 'efc6493b-a5c3-5b71-ac25-181b5fb94074'::uuid, 'Quel type de narrateur Poe emploie-t-il ?', 'mcq', '["Un narrateur interne, témoin, dont on peut douter","Un narrateur omniscient","Un narrateur absent","Plusieurs narrateurs successifs"]'::jsonb, 0, 'Le doute sur sa fiabilité nourrit le fantastique.', 6),
    ('bf066a4a-980f-5781-b404-a3382a679c81'::uuid, 'efc6493b-a5c3-5b71-ac25-181b5fb94074'::uuid, 'Pourquoi le titre est-il double ?', 'mcq', '["« Maison » désigne à la fois le bâtiment et la lignée","La nouvelle comporte deux maisons","Le titre a été traduit deux fois","Usher possédait deux domaines"]'::jsonb, 0, 'L’anglais « house » porte les deux sens.', 7),
    ('8412fbf2-7228-506d-bcfa-d305dbf68343'::uuid, 'efc6493b-a5c3-5b71-ac25-181b5fb94074'::uuid, 'Dans le fantastique, le surnaturel est toujours expliqué à la fin.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'L’hésitation reste ouverte : c’est la définition même du genre.', 8),
    ('d276c0a2-2d6a-54a9-98d8-d70dc496cb69'::uuid, '029d706e-6b92-51f6-bb06-0fceda218555'::uuid, 'À quelles questions un article informatif doit-il répondre ?', 'mcq', '["Qui, quoi, quand, où, pourquoi","Comment, combien, pour qui","Qui, contre qui, pour quel prix","Quand et seulement quand"]'::jsonb, 0, 'La règle dite des cinq W.', 1),
    ('b7f239c6-a450-5505-b78c-e868ccd35240'::uuid, '029d706e-6b92-51f6-bb06-0fceda218555'::uuid, 'Qu’est-ce que le chapô d’un article ?', 'mcq', '["Le paragraphe d’introduction, souvent en gras","Le titre principal","La dernière phrase","La légende de la photo"]'::jsonb, 0, 'Il résume l’essentiel avant le corps de l’article.', 2),
    ('37e170bd-8d63-58d9-a4cd-45fddaaced7e'::uuid, '029d706e-6b92-51f6-bb06-0fceda218555'::uuid, 'Quel genre journalistique exprime une opinion ?', 'mcq', '["L’éditorial","La brève","Le reportage","L’interview"]'::jsonb, 0, 'La chronique et la critique aussi.', 3),
    ('8e3f8833-f744-51d5-89d7-4d473b6a9d61'::uuid, '029d706e-6b92-51f6-bb06-0fceda218555'::uuid, 'Que faut-il vérifier en premier devant une information ?', 'mcq', '["Sa source et sa date","Le nombre de partages","La qualité de l’image","La longueur du texte"]'::jsonb, 0, 'Une image ancienne remise en circulation change de sens.', 4),
    ('91092043-d533-52ab-aa56-0dc9247419df'::uuid, '029d706e-6b92-51f6-bb06-0fceda218555'::uuid, 'Qu’est-ce qu’un titre-appât (« putaclic ») ?', 'mcq', '["Un titre spectaculaire qui promet plus que l’article ne donne","Un titre trop long","Un titre sans verbe","Un titre en langue étrangère"]'::jsonb, 0, 'Il vise le clic, pas l’information.', 5),
    ('c908999d-4846-5e82-af35-06961aba1a12'::uuid, '029d706e-6b92-51f6-bb06-0fceda218555'::uuid, 'Qu’est-ce que la bulle de filtres ?', 'mcq', '["L’effet des algorithmes qui montrent surtout ce qui confirme nos idées","Un filtre appliqué aux photos de presse","Une technique de vérification","Un logiciel anti-spam"]'::jsonb, 0, 'Elle réduit la diversité des points de vue rencontrés.', 6),
    ('7314abc1-a208-56f5-bc5f-ef89fa009c04'::uuid, '029d706e-6b92-51f6-bb06-0fceda218555'::uuid, 'Quelle loi garantit la liberté de la presse en France ?', 'mcq', '["La loi de 1881","La loi de 1789","La loi de 1905","La loi de 1958"]'::jsonb, 0, 'Elle connaît des limites : diffamation, injure, incitation à la haine.', 7),
    ('2d6174d4-653a-51d4-9cc2-12984484ae51'::uuid, '029d706e-6b92-51f6-bb06-0fceda218555'::uuid, 'Une rumeur et une infox sont exactement la même chose.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'L’infox est fabriquée pour tromper ; la rumeur circule souvent de bonne foi.', 8),
    ('b4cd2082-1571-5e4e-a8da-9562ecaab285'::uuid, '4266b09c-f867-5d4a-b96a-a99c8993c624'::uuid, 'Quel est le but de la propagande ?', 'mcq', '["Faire adhérer à une opinion, pas informer","Vendre un produit commercial","Divertir le public","Enseigner une méthode"]'::jsonb, 0, 'Elle s’adresse à l’émotion plutôt qu’au raisonnement.', 1),
    ('52350164-0b1f-5401-9e1c-5a47332f4655'::uuid, '4266b09c-f867-5d4a-b96a-a99c8993c624'::uuid, 'Quel procédé consiste à réduire un problème complexe à une formule ?', 'mcq', '["La simplification","Le recoupement","La nuance","La citation"]'::jsonb, 0, 'Souvent associée à la répétition d’un slogan.', 2),
    ('30ebf2a4-5a11-5956-9dc0-aea9620616a3'::uuid, '4266b09c-f867-5d4a-b96a-a99c8993c624'::uuid, 'Qu’est-ce que la désignation d’un ennemi ?', 'mcq', '["La construction d’un « eux » responsable de tout, opposé à un « nous »","La déclaration de guerre officielle","La critique d’un adversaire politique argumentée","Le refus de nommer ses sources"]'::jsonb, 0, 'C’est l’un des ressorts les plus constants de la propagande.', 3),
    ('4478ddb7-9de7-586c-b483-5bce034a2ae0'::uuid, '4266b09c-f867-5d4a-b96a-a99c8993c624'::uuid, 'Qu’est-ce qu’un plan en contre-plongée dans une image de propagande ?', 'mcq', '["Un cadrage vu d’en bas, qui grandit le personnage","Un cadrage vu d’en haut, qui écrase le personnage","Un gros plan sur les mains","Un plan tourné de nuit"]'::jsonb, 0, 'Il sert le culte du chef.', 4),
    ('7881ea18-d3c2-572a-88d8-c2d4424c18f0'::uuid, '4266b09c-f867-5d4a-b96a-a99c8993c624'::uuid, 'Que faut-il identifier en premier dans un document de propagande ?', 'mcq', '["Son auteur et son commanditaire","Sa longueur","Le nombre de couleurs employées","Sa police de caractères"]'::jsonb, 0, 'Qui parle, et pour le compte de qui ?', 5),
    ('2de28630-687f-53e2-8b1e-b56918ed81c6'::uuid, '4266b09c-f867-5d4a-b96a-a99c8993c624'::uuid, 'Qu’est-ce qu’un message implicite ?', 'mcq', '["Ce que le document fait croire sans le dire","Le titre du document","La légende officielle","La signature de l’auteur"]'::jsonb, 0, 'Il se distingue du message explicite.', 6),
    ('1f46c670-4c89-5253-9f46-9232a414bbb6'::uuid, '4266b09c-f867-5d4a-b96a-a99c8993c624'::uuid, 'Comment une image peut-elle tromper sans être truquée ?', 'mcq', '["Par son cadrage, sa légende et son contexte de publication","Par sa taille","Par sa date de prise de vue seule","Par son format de fichier"]'::jsonb, 0, 'On lui fait dire ce qu’elle ne montre pas.', 7),
    ('86102f6d-c8f1-5581-8ed7-4541f49bbade'::uuid, '4266b09c-f867-5d4a-b96a-a99c8993c624'::uuid, 'La propagande et la publicité poursuivent le même objet.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'La publicité vend un produit ; la propagande vise l’adhésion politique ou idéologique.', 8),
    ('0c515e7e-e15c-5c45-866d-64bb692246d9'::uuid, 'dd384a65-6e2e-5292-aefa-087e465b7138'::uuid, 'Quel roman de Balzac décrit le monde du journalisme parisien ?', 'mcq', '["Illusions perdues","Le Père Goriot","Bel-Ami","L’Assommoir"]'::jsonb, 0, 'Lucien de Rubempré y réussit puis s’y perd.', 1),
    ('b411d456-e5fd-510a-b1dd-23158c91b479'::uuid, 'dd384a65-6e2e-5292-aefa-087e465b7138'::uuid, 'Qui est le héros de Bel-Ami ?', 'mcq', '["Georges Duroy","Lucien de Rubempré","Roderick Usher","Rodrigue"]'::jsonb, 0, 'Il gravit les échelons d’un journal par les femmes et l’intrigue.', 2),
    ('2a866d96-c5d2-5400-8d1e-8bb0927a5935'::uuid, 'dd384a65-6e2e-5292-aefa-087e465b7138'::uuid, 'Que dénoncent Balzac et Maupassant à propos de la presse ?', 'mcq', '["Un système qui produit le mensonge, au-delà des individus","L’incompétence technique des imprimeurs","Le prix trop élevé des journaux","Le manque de lecteurs"]'::jsonb, 0, 'L’article s’y vend, la critique dépend de qui paie.', 3),
    ('b4021496-206a-5c45-9912-7a28184c692d'::uuid, 'dd384a65-6e2e-5292-aefa-087e465b7138'::uuid, 'Quel journaliste a défini le métier comme « porter la plume dans la plaie » ?', 'mcq', '["Albert Londres","Émile Zola","Guy de Maupassant","Honoré de Balzac"]'::jsonb, 0, 'Il est l’inventeur du grand reportage.', 4),
    ('6314f74f-780c-5654-89aa-398ddd023366'::uuid, 'dd384a65-6e2e-5292-aefa-087e465b7138'::uuid, 'Quel film suit deux journalistes révélant le scandale du Watergate ?', 'mcq', '["Les Hommes du président","Spotlight","Citizen Kane","La Parure"]'::jsonb, 0, 'Leur enquête mène à la démission d’un président.', 5),
    ('d264c3f4-8a18-581f-aa54-f51c6fd650d1'::uuid, 'dd384a65-6e2e-5292-aefa-087e465b7138'::uuid, 'Que montre le film Spotlight ?', 'mcq', '["Une équipe menant une enquête au long cours avant publication","Un journaliste corrompu","La naissance d’un journal","Une rédaction de télévision en direct"]'::jsonb, 0, 'Des mois de vérification y précèdent la publication.', 6),
    ('d84cc74a-445b-58fb-a3ac-8468adc30aa9'::uuid, 'dd384a65-6e2e-5292-aefa-087e465b7138'::uuid, 'Qu’apporte la fiction par rapport à un article de presse ?', 'mcq', '["Elle montre comment le fait a été obtenu et ce qu’il a coûté","Elle donne des informations plus récentes","Elle garantit la véracité des faits","Elle remplace le travail des journalistes"]'::jsonb, 0, 'Elle rend visibles les conditions du métier.', 7),
    ('6b56471b-af21-5871-9dea-817d04939104'::uuid, 'dd384a65-6e2e-5292-aefa-087e465b7138'::uuid, 'Dans Bel-Ami, Georges Duroy réussit grâce à son talent d’écriture.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il réussit par les femmes et l’intrigue, sans talent particulier.', 8),
    ('005640b9-4536-5bda-8d39-377a3ff7948e'::uuid, 'c630a319-c461-579a-a74f-1ba4cf2338ad'::uuid, 'Pourquoi la ville devient-elle un sujet de roman au XIXe siècle ?', 'mcq', '["Parce que l’exode rural et l’industrialisation la transforment radicalement","Parce que les romanciers y habitent tous","Parce que la campagne n’intéresse plus personne","Parce que l’imprimerie s’y installe"]'::jsonb, 0, 'Les grands travaux d’Haussmann changent Paris en trente ans.', 1),
    ('28512568-be28-5e5e-8abb-e63a38c208a9'::uuid, 'c630a319-c461-579a-a74f-1ba4cf2338ad'::uuid, 'Quel personnage de Balzac lance « À nous deux maintenant ! » à Paris ?', 'mcq', '["Rastignac","Lucien de Rubempré","Georges Duroy","Jean Valjean"]'::jsonb, 0, 'Il le lance du haut du Père-Lachaise.', 2),
    ('1f2f83ef-6f31-5ffb-b95a-06aa602ffa73'::uuid, 'c630a319-c461-579a-a74f-1ba4cf2338ad'::uuid, 'Comment Zola traite-t-il la ville ?', 'mcq', '["Comme un milieu qui détermine le destin des personnages","Comme un décor neutre","Comme un lieu de villégiature","Comme un souvenir d’enfance"]'::jsonb, 0, 'L’Assommoir se joue dans quelques rues de la Goutte-d’Or.', 3),
    ('4880d1a6-dc99-548b-86d8-19418148187d'::uuid, 'c630a319-c461-579a-a74f-1ba4cf2338ad'::uuid, 'Dans quel roman Paris est-il un labyrinthe d’égouts et de barricades ?', 'mcq', '["Les Misérables","L’Assommoir","Bel-Ami","Illusions perdues"]'::jsonb, 0, 'Hugo y fait de la ville un dédale.', 4),
    ('66fe8f50-d67e-574b-942f-756d4f693b32'::uuid, 'c630a319-c461-579a-a74f-1ba4cf2338ad'::uuid, 'Qu’est-ce que la personnification appliquée à la ville ?', 'mcq', '["Lui prêter des attributs humains : elle gronde, dévore, respire","La comparer à une autre ville","La décrire en détail","La nommer par son quartier"]'::jsonb, 0, 'C’est ce qui en fait un personnage à part entière.', 5),
    ('0f1fac5b-c5dc-57ad-88e5-ccd8bb79e8a6'::uuid, 'c630a319-c461-579a-a74f-1ba4cf2338ad'::uuid, 'Qu’est-ce que la focalisation interne dans une description de ville ?', 'mcq', '["La ville vue par les yeux d’un personnage","Une description faite par le narrateur omniscient","Une description objective et chiffrée","Un plan de la ville"]'::jsonb, 0, 'Souvent au moment de son arrivée.', 6),
    ('dc59fb42-00c1-5103-acca-c800161dc118'::uuid, 'c630a319-c461-579a-a74f-1ba4cf2338ad'::uuid, 'Que révèle le choix de ce qu’on décrit dans une ville ?', 'mcq', '["L’intention du romancier, son jugement sur elle","La saison de l’année","Le budget du roman","La longueur du chapitre"]'::jsonb, 0, 'Montrer les vitrines ou les taudis n’est jamais neutre.', 7),
    ('0de9ef67-08be-5d84-89ef-23684f81931a'::uuid, 'c630a319-c461-579a-a74f-1ba4cf2338ad'::uuid, 'Dans le roman du XIXe siècle, la ville n’est qu’un décor sans influence.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle devient un acteur, et chez Zola elle détermine les destins.', 8),
    ('991bd030-8d55-5334-abc6-fc373140ccaa'::uuid, '075ce4d2-072d-5d6c-90e2-2cb9d643b3a3'::uuid, 'Quel recueil contient la section « Tableaux parisiens » ?', 'mcq', '["Les Fleurs du mal","Alcools","Les Contemplations","Illuminations"]'::jsonb, 0, 'Baudelaire y fait de Paris un sujet poétique.', 1),
    ('b0929aea-7070-5ff3-ad22-971b181b22c6'::uuid, '075ce4d2-072d-5d6c-90e2-2cb9d643b3a3'::uuid, 'Qu’est-ce qu’un flâneur chez Baudelaire ?', 'mcq', '["Un poète qui marche dans la ville et capte les instants","Un promeneur de campagne","Un journaliste enquêteur","Un habitant sans domicile"]'::jsonb, 0, 'Il observe la passante, la vieille femme, l’aveugle.', 2),
    ('b24da792-124b-5267-83a2-18bdd5d2f083'::uuid, '075ce4d2-072d-5d6c-90e2-2cb9d643b3a3'::uuid, 'Que signifie « Tu m’as donné ta boue et j’en ai fait de l’or » ?', 'mcq', '["Le poète transfigure la laideur de la ville en poésie","Le poète s’est enrichi grâce à la ville","La ville a été reconstruite en or","Le poète regrette la campagne"]'::jsonb, 0, 'C’est le programme de la poésie urbaine.', 3),
    ('b9cf8d7b-a501-528d-a98f-96d9a974a34c'::uuid, '075ce4d2-072d-5d6c-90e2-2cb9d643b3a3'::uuid, 'Quel poème d’Apollinaire ouvre Alcools sur un Paris moderne ?', 'mcq', '["« Zone »","« Le Pont Mirabeau »","« Demain, dès l’aube… »","« Le Cygne »"]'::jsonb, 0, 'Publié en 1913, sans ponctuation.', 4),
    ('3b68e7aa-0c03-54b7-a0a5-e78cdd46f561'::uuid, '075ce4d2-072d-5d6c-90e2-2cb9d643b3a3'::uuid, 'Qu’est-ce qu’un oxymore ?', 'mcq', '["L’association de deux mots de sens contraires, comme « soleil noir »","Une répétition de sons","Une comparaison développée","Une exagération"]'::jsonb, 0, 'Il permet de dire la beauté du laid.', 5),
    ('4d00b3a6-81be-5af0-9026-46daec914393'::uuid, '075ce4d2-072d-5d6c-90e2-2cb9d643b3a3'::uuid, 'Qu’est-ce qu’une synesthésie ?', 'mcq', '["Le mélange de sensations de natures différentes","La répétition d’un vers","Une rime intérieure","Un vers de douze syllabes"]'::jsonb, 0, 'Bruits, odeurs et couleurs y sont associés.', 6),
    ('67bd4d41-5756-504a-bb05-fd3b98c9b939'::uuid, '075ce4d2-072d-5d6c-90e2-2cb9d643b3a3'::uuid, 'Quelle forme poétique s’impose pour dire le désordre urbain ?', 'mcq', '["Le vers libre et le poème en prose","Le sonnet","L’alexandrin à rimes plates","La ballade"]'::jsonb, 0, 'Des formes assez souples pour épouser la ville moderne.', 7),
    ('3c014c7c-419c-542a-bd00-495d6816a87b'::uuid, '075ce4d2-072d-5d6c-90e2-2cb9d643b3a3'::uuid, 'La poésie de la ville cherche à embellir ce qu’elle décrit.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle transfigure : elle rend visible ce que personne ne regarde.', 8),
    ('c94661d6-c43f-5862-a28c-856b78c99f2b'::uuid, 'f9a12b39-2235-541e-9d4c-9282f050b100'::uuid, 'Quel récit de 1841 est considéré comme le premier roman policier ?', 'mcq', '["« Double assassinat dans la rue Morgue » de Poe","Le Mystère de la chambre jaune","Une étude en rouge","Arsène Lupin gentleman-cambrioleur"]'::jsonb, 0, 'Le chevalier Dupin y résout l’énigme par la déduction.', 1),
    ('19e9a078-8b13-5c62-a0e9-d60b2e9856c0'::uuid, 'f9a12b39-2235-541e-9d4c-9282f050b100'::uuid, 'Dans quelle ville Sherlock Holmes enquête-t-il ?', 'mcq', '["Londres","Paris","New York","Édimbourg"]'::jsonb, 0, 'Un Londres de brouillard, de fiacres et de bas-fonds.', 2),
    ('1fbd6e04-6f06-56a2-b9ea-83e282322e41'::uuid, 'f9a12b39-2235-541e-9d4c-9282f050b100'::uuid, 'Quel roman de Gaston Leroux est le modèle du crime en chambre close ?', 'mcq', '["Le Mystère de la chambre jaune","Bel-Ami","Les Misérables","La Parure"]'::jsonb, 0, 'Publié en 1907.', 3),
    ('ddc75d5c-c1a5-537f-945f-cf4cad6f7704'::uuid, 'f9a12b39-2235-541e-9d4c-9282f050b100'::uuid, 'Quel personnage de Maurice Leblanc inverse les rôles du policier et du voleur ?', 'mcq', '["Arsène Lupin","Maigret","Sherlock Holmes","Rouletabille"]'::jsonb, 0, 'Le gentleman-cambrioleur est le héros.', 4),
    ('f645f639-4b1a-5ecd-9d9f-a66fd878b476'::uuid, 'f9a12b39-2235-541e-9d4c-9282f050b100'::uuid, 'Sur quoi reposent les enquêtes du commissaire Maigret ?', 'mcq', '["Sur l’atmosphère d’un lieu plus que sur l’indice","Sur des analyses scientifiques","Sur des courses-poursuites","Sur des interrogatoires musclés"]'::jsonb, 0, 'Un café, un quartier, une pluie sur la Seine.', 5),
    ('6906fe3f-9f69-56f4-adba-e61b5507b79e'::uuid, 'f9a12b39-2235-541e-9d4c-9282f050b100'::uuid, 'Qu’est-ce qui caractérise le roman noir ?', 'mcq', '["Une société corrompue, un détective désabusé, une ville hostile","Une énigme résolue par la logique","Un suspense permanent sans enquête","Une intrigue historique"]'::jsonb, 0, 'Chandler et Manchette en sont des maîtres.', 6),
    ('91c60a88-4370-58a8-b642-14a8ee6c6d99'::uuid, 'f9a12b39-2235-541e-9d4c-9282f050b100'::uuid, 'Qu’apporte la grande ville au roman policier ?', 'mcq', '["L’anonymat, la variété sociale et une atmosphère","Un climat plus doux","Des personnages plus riches","Une intrigue plus courte"]'::jsonb, 0, 'Maigret n’existe pas hors de Paris.', 7),
    ('5c8d45a1-5a0a-5534-a3e4-73e0af8e926f'::uuid, 'f9a12b39-2235-541e-9d4c-9282f050b100'::uuid, 'Le roman policier existait bien avant les grandes villes modernes.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il naît avec elles, au XIXe siècle : il lui faut une foule et une police organisée.', 8),
    ('ba29c38a-8ff2-5786-8861-4514106b9748'::uuid, '97bcdad8-2a45-5017-819b-7270ddffbacd'::uuid, 'Quel photographe a documenté le vieux Paris avant sa disparition ?', 'mcq', '["Eugène Atget","Robert Doisneau","Willy Ronis","Henri Cartier-Bresson"]'::jsonb, 0, 'Rues vides, boutiques et cours, dans un travail d’archive.', 1),
    ('0f7b5fab-9007-5e7b-a16f-375802b5fbad'::uuid, '97bcdad8-2a45-5017-819b-7270ddffbacd'::uuid, 'Qu’est-ce que le cadrage en photographie ?', 'mcq', '["Le choix de ce que l’image garde et de ce qu’elle exclut","Le réglage de la lumière","Le format d’impression","Le choix de l’appareil"]'::jsonb, 0, 'Ce qui est hors champ compte autant que ce qui est montré.', 2),
    ('ad913064-a96d-532a-9d2d-7d2d7a228a5e'::uuid, '97bcdad8-2a45-5017-819b-7270ddffbacd'::uuid, 'Qu’est-ce qu’une contre-plongée ?', 'mcq', '["Une prise de vue d’en bas, qui grandit le sujet","Une prise de vue d’en haut","Une photo prise de nuit","Un cadrage très serré"]'::jsonb, 0, 'La plongée, à l’inverse, écrase le sujet.', 3),
    ('2b0ec515-fac2-5f85-b125-a983e0fde44d'::uuid, '97bcdad8-2a45-5017-819b-7270ddffbacd'::uuid, 'Quel film de 1927 met en scène une ville verticale et divisée ?', 'mcq', '["Metropolis","Blade Runner","La Haine","Les Hommes du président"]'::jsonb, 0, 'Fritz Lang y installe les ouvriers sous terre et les maîtres au sommet.', 4),
    ('36adeffd-8467-5740-8ae3-3574358f0f3f'::uuid, '97bcdad8-2a45-5017-819b-7270ddffbacd'::uuid, 'Qu’est-ce qu’un plan général au cinéma ?', 'mcq', '["Un plan large qui situe l’action dans son décor","Un gros plan sur un visage","Un plan filmé en mouvement","Un plan sans son"]'::jsonb, 0, 'Le gros plan sert, lui, l’émotion.', 5),
    ('5f49a0cf-55db-53c1-aa80-c246f4b8d184'::uuid, '97bcdad8-2a45-5017-819b-7270ddffbacd'::uuid, 'Comment appelle-t-on le texte du narrateur en bande dessinée ?', 'mcq', '["Le cartouche","La bulle","La case","La planche"]'::jsonb, 0, 'La bulle contient les paroles des personnages.', 6),
    ('302e85f0-4670-57a4-ad93-80c2b070a4fa'::uuid, '97bcdad8-2a45-5017-819b-7270ddffbacd'::uuid, 'Quelle série de bande dessinée invente des villes entières comme personnages ?', 'mcq', '["Les Cités obscures, de Schuiten et Peeters","Les Aventures de Tintin","Les Misérables en BD","Astérix"]'::jsonb, 0, 'La ville y est le sujet même du récit.', 7),
    ('f3736aac-32c5-5384-9b36-46f7e5caf79f'::uuid, '97bcdad8-2a45-5017-819b-7270ddffbacd'::uuid, 'En bande dessinée, tout ce qui se passe est montré dans les cases.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Entre deux cases, une ellipse laisse au lecteur le soin de combler.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('francais');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('francais')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 300 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 300 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
