-- =============================================================================
-- Studuel — Migration 307 : FRANÇAIS 5e — LE PROGRAMME COMPLET (13 fiches)
--
-- ⚠️ FICHIER GÉNÉRÉ — ne pas éditer à la main.
--    Source : scripts/contenu/*.mjs
--    Regénérer : node scripts/seed-contenu.mjs --num 307 --modules francais-5e
--
-- CONSTAT : le français de 5e n'avait que les 5 fiches du premier jeu de données de
-- l'app — « Le roman de chevalerie », « Voyages et découvertes », « Théâtre : la
-- comédie », « Les compléments de phrase », « Conjugaison : passé simple ». Un
-- élève de 5e qui révisait les récits de voyage, la poésie de l'ailleurs, le roman
-- d'aventures, L'École des femmes, les récits d'enfance, le conte merveilleux,
-- l'utopie, la dystopie, les héros médiévaux et antiques ou le rapport de l'homme à
-- la nature ne trouvait RIEN. Cette migration installe les 13 fiches, rangées sous
-- les 5 chapitres de la maquette — les quatre questionnements du BO plus un
-- questionnement complémentaire — et retire les 5 fiches génériques.
-- DEUX DES CINQ FICHES RETIRÉES SONT DES POINTS DE LANGUE (« Les compléments de
-- phrase », « Conjugaison : passé simple ») : la grammaire a son propre rayon en
-- Première (migration 259) et le collège n'en a pas encore ; les laisser au milieu
-- des œuvres brouillerait le dossier.
--
-- Cette migration apporte : 13 chapitres, 13 leçons,
-- 13 quiz et 104 questions, sur 1 matière.
--
-- CHOIX ASSUMÉS :
--  · tous les quiz sont `is_free = true`. Aucun compte ne peut aujourd’hui
--    passer `tier1` (aucun paiement n’existe), donc un quiz payant serait un
--    quiz INVISIBLE pour 100 % des élèves — le contraire du but ;
--  · chaque cours porte des sections `##`, ce qui rend sa carte mentale
--    dérivable (cf. lib/mind-map-auto) : aucune tuile ne promet dans le vide.
--
-- Idempotent : les UUID sont dérivés du contenu (SHA-1), donc stables ; les
-- INSERT sont tous gardés par ON CONFLICT DO NOTHING. Rejouable sans risque.
--
-- PRÉREQUIS : 002, 008, 191, 193 exécutées (les matières doivent exister).
-- À exécuter dans : Supabase Dashboard → SQL Editor → New query → Run.
-- =============================================================================

-- 0. Ménage ----------------------------------------------------------------
-- [francais] La colonne chapters.theme (migration 234) conditionne tout ce qui suit : ce
-- [francais] module range ses 13 fiches sous 5 chapitres, et l'INSERT écrit la colonne. Elle
-- [francais] est REPRISE ici en ADD COLUMN IF NOT EXISTS parce qu'on ne peut pas garantir que
-- [francais] la 234 soit passée en production — sans cette reprise, la migration échouerait
-- [francais] sur "column chapters.theme does not exist", les 5 anciens chapitres déjà
-- [francais] supprimés et les 13 neufs pas encore posés : une matière vide.
-- [francais] Le ménage qui suit LIT cette colonne : elle doit exister avant lui.
-- [francais] Le GRANT n'est pas décoratif : la migration 182 a révoqué le SELECT de table sur
-- [francais] chapters (pour cacher mind_map) et ne l'a rendu que colonne par colonne.
ALTER TABLE public.chapters ADD COLUMN IF NOT EXISTS theme TEXT;
GRANT SELECT (theme) ON public.chapters TO anon;
GRANT SELECT (theme) ON public.chapters TO authenticated;

-- [francais] Les 5 chapitres hérités de la 008 partent, au niveau 5e SEULEMENT.
-- [francais] 
-- [francais] LE REPÈRE EST theme IS NULL, PAS LE TITRE : « Théâtre : la comédie » et
-- [francais] « Voyages et découvertes » recouvrent des entrées que le programme neuf traite
-- [francais] sous d'autres titres, et un DELETE par titre demanderait de vérifier à chaque
-- [francais] relecture qu'aucune fiche neuve ne les reprend exactement. Le critère « pas de
-- [francais] chapitre de programme » vise exactement les cinq lignes voulues : elles datent de
-- [francais] la 008, bien avant la colonne theme, tandis que les 13 fiches neuves en portent
-- [francais] une dès l'INSERT — le ménage tourne AVANT les insertions et ne peut donc jamais
-- [francais] mordre sur elles, ni au premier passage ni au rejeu.
-- [francais] Le filtre level = '5e' est indispensable : le français existe sur six niveaux, et
-- [francais] la 4e comme la 3e sont traitées par leurs propres migrations.
-- [francais] L'ordre compte : la file "À revoir" d'abord (review_items.item_id n'a PAS de clé
-- [francais] étrangère), puis les quiz (quizzes.lesson_id est ON DELETE SET NULL), puis les
-- [francais] chapitres, dont les leçons partent en cascade.
DELETE FROM public.review_items ri
 USING public.quiz_questions qq, public.quizzes qz, public.lessons l,
       public.chapters c, public.subjects s
 WHERE ri.item_kind = 'question'
   AND ri.item_id = qq.id
   AND qq.quiz_id = qz.id
   AND qz.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'francais'
   AND c.level = '5e'
   AND c.theme IS NULL;

DELETE FROM public.quizzes q
 USING public.lessons l, public.chapters c, public.subjects s
 WHERE q.lesson_id = l.id
   AND l.chapter_id = c.id
   AND c.subject_id = s.id
   AND s.slug = 'francais'
   AND c.level = '5e'
   AND c.theme IS NULL;

DELETE FROM public.chapters c
 USING public.subjects s
 WHERE c.subject_id = s.id
   AND s.slug = 'francais'
   AND c.level = '5e'
   AND c.theme IS NULL;

-- 1. Chapitres -------------------------------------------------------------
-- Jointure sur le SLUG (et non le nom) : c’est la clé stable de `subjects`.
INSERT INTO public.chapters (id, subject_id, level, title, position, theme)
SELECT v.id, s.id, v.level, v.title, v.position, v.theme
  FROM (VALUES
    ('8f784bec-0277-5d05-b70e-7d47fb81e7bc'::uuid, 'francais', '5e', 'Les grandes découvertes', 1, 'Se chercher, se construire — Le voyage et l’aventure : pourquoi aller vers l’inconnu ?'),
    ('4366ab9b-8872-567d-bf24-2f2eb9c1a9ea'::uuid, 'francais', '5e', 'Les voyages et la séduction de l’ailleurs dans la poésie', 2, 'Se chercher, se construire — Le voyage et l’aventure : pourquoi aller vers l’inconnu ?'),
    ('6c916708-6b4d-586a-bacf-4aaff6a2264f'::uuid, 'francais', '5e', 'Le roman d’aventures', 3, 'Se chercher, se construire — Le voyage et l’aventure : pourquoi aller vers l’inconnu ?'),
    ('fde4fddf-3208-557a-829e-0de6fa170325'::uuid, 'francais', '5e', 'La comédie au XVIIe siècle : L’École des femmes, Molière', 4, 'Vivre en société, participer à la société — Avec autrui : famille, amis, réseaux'),
    ('6599efec-fefb-5c60-86a9-b028fa4f86ed'::uuid, 'francais', '5e', 'Les récits d’enfance et d’adolescence', 5, 'Vivre en société, participer à la société — Avec autrui : famille, amis, réseaux'),
    ('3a7a28dd-117c-5eac-9606-4dc594d578b4'::uuid, 'francais', '5e', 'Le conte merveilleux', 6, 'Regarder le monde, inventer des mondes — Imaginer des univers nouveaux'),
    ('c841f7b9-62c1-579c-9266-06e8246818e5'::uuid, 'francais', '5e', 'L’utopie', 7, 'Regarder le monde, inventer des mondes — Imaginer des univers nouveaux'),
    ('6b657546-53d8-51cd-8eaf-0b914516971f'::uuid, 'francais', '5e', 'La dystopie', 8, 'Regarder le monde, inventer des mondes — Imaginer des univers nouveaux'),
    ('a4a0a655-c66d-5180-9dba-7afc5b3d5891'::uuid, 'francais', '5e', 'Le héros médiéval', 9, 'Agir sur le monde — Héros / héroïnes et héroïsme'),
    ('01669d26-296b-5577-bdc5-f80eaba6227d'::uuid, 'francais', '5e', 'Le héros de l’Antiquité', 10, 'Agir sur le monde — Héros / héroïnes et héroïsme'),
    ('6a380608-689d-5a2d-b67e-70358a89b0d7'::uuid, 'francais', '5e', 'La révolution industrielle, facteur de rupture entre l’Homme et la nature', 11, 'Questionnements complémentaires — L’être humain est-il maître de la nature ?'),
    ('f4b8a80c-f446-52cc-b212-3153a99aa0ac'::uuid, 'francais', '5e', 'Le roman d’anticipation', 12, 'Questionnements complémentaires — L’être humain est-il maître de la nature ?'),
    ('720b0dcc-d36b-5605-8a79-d187aef534b0'::uuid, 'francais', '5e', 'L’art de discipliner ou de rêver la nature du Moyen Âge au XVIIe siècle', 13, 'Questionnements complémentaires — L’être humain est-il maître de la nature ?')
  ) AS v(id, slug, level, title, position, theme)
  JOIN public.subjects s ON s.slug = v.slug
-- ON CONFLICT NU : `chapters` porte aussi UNIQUE(subject_id, level, title).
ON CONFLICT DO NOTHING;

-- 1 bis. Axes du programme -------------------------------------------------
-- `chapters.theme` (migration 234) : l’intitulé du programme officiel qui
-- coiffe le chapitre. La page matière s’en sert pour grouper au lieu
-- d’aligner 28 lignes à plat. UPDATE et non INSERT : le chapitre peut déjà
-- exister (l’INSERT précédent l’aurait alors ignoré).
UPDATE public.chapters c SET theme = v.theme
  FROM (VALUES
    ('8f784bec-0277-5d05-b70e-7d47fb81e7bc'::uuid, 'Se chercher, se construire — Le voyage et l’aventure : pourquoi aller vers l’inconnu ?'),
    ('4366ab9b-8872-567d-bf24-2f2eb9c1a9ea'::uuid, 'Se chercher, se construire — Le voyage et l’aventure : pourquoi aller vers l’inconnu ?'),
    ('6c916708-6b4d-586a-bacf-4aaff6a2264f'::uuid, 'Se chercher, se construire — Le voyage et l’aventure : pourquoi aller vers l’inconnu ?'),
    ('fde4fddf-3208-557a-829e-0de6fa170325'::uuid, 'Vivre en société, participer à la société — Avec autrui : famille, amis, réseaux'),
    ('6599efec-fefb-5c60-86a9-b028fa4f86ed'::uuid, 'Vivre en société, participer à la société — Avec autrui : famille, amis, réseaux'),
    ('3a7a28dd-117c-5eac-9606-4dc594d578b4'::uuid, 'Regarder le monde, inventer des mondes — Imaginer des univers nouveaux'),
    ('c841f7b9-62c1-579c-9266-06e8246818e5'::uuid, 'Regarder le monde, inventer des mondes — Imaginer des univers nouveaux'),
    ('6b657546-53d8-51cd-8eaf-0b914516971f'::uuid, 'Regarder le monde, inventer des mondes — Imaginer des univers nouveaux'),
    ('a4a0a655-c66d-5180-9dba-7afc5b3d5891'::uuid, 'Agir sur le monde — Héros / héroïnes et héroïsme'),
    ('01669d26-296b-5577-bdc5-f80eaba6227d'::uuid, 'Agir sur le monde — Héros / héroïnes et héroïsme'),
    ('6a380608-689d-5a2d-b67e-70358a89b0d7'::uuid, 'Questionnements complémentaires — L’être humain est-il maître de la nature ?'),
    ('f4b8a80c-f446-52cc-b212-3153a99aa0ac'::uuid, 'Questionnements complémentaires — L’être humain est-il maître de la nature ?'),
    ('720b0dcc-d36b-5605-8a79-d187aef534b0'::uuid, 'Questionnements complémentaires — L’être humain est-il maître de la nature ?')
  ) AS v(id, theme)
 WHERE c.id = v.id AND c.theme IS DISTINCT FROM v.theme;

-- 2. Leçons ----------------------------------------------------------------
INSERT INTO public.lessons (id, chapter_id, title, content, position) VALUES
  ('a82f20bb-501f-5d1a-9c95-6c5c2fb01221', '8f784bec-0277-5d05-b70e-7d47fb81e7bc', 'Le récit de voyage, entre témoignage et invention', E'## Un genre ancien\nLe **récit de voyage** raconte un déplacement réel vers des terres lointaines. Il se développe considérablement aux **XVe et XVIe siècles**, quand les navigateurs européens atteignent l’Afrique, l’Amérique et l’Asie.\n\n## Les grands textes\n- **Marco Polo**, *Le Devisement du monde* (vers 1298) : le récit de ses années en Chine, dicté en prison. On l’a surnommé *Le Livre des merveilles* — et longtemps soupçonné d’exagération.\n- **Christophe Colomb**, son **journal de bord** (1492) : un texte administratif devenu document historique.\n- **Jean de Léry**, *Histoire d’un voyage en terre de Brésil* (1578) : l’un des premiers regards ethnographiques sur un peuple amérindien.\n- **Jacques Cartier**, **Bougainville**, plus tard **Chateaubriand**.\n\n## Les caractéristiques du genre\n- Un **narrateur** qui dit « je » et se porte garant de ce qu’il rapporte.\n- Un ordre **chronologique**, souvent daté — journal, lettres, mémoires.\n- Des **descriptions** de paysages, de plantes, d’animaux, de peuples.\n- Un vocabulaire de la **découverte** et de l’**étonnement** : « jamais vu », « merveille », « étrange ».\n- Le recours à la **comparaison** avec le connu, seul moyen de faire imaginer l’inconnu au lecteur.\n\n## Le regard sur l’autre\nC’est l’enjeu du chapitre. Le voyageur décrit toujours **depuis** sa propre culture :\n- il peut verser dans l’**émerveillement** ou dans le **mépris** ;\n- il invente parfois la figure du « **bon sauvage** », dont **Montaigne** se sert dans « Des cannibales » (*Essais*, 1580) pour critiquer sa propre société : les vrais barbares, écrit-il, ne sont peut-être pas ceux qu’on croit.\n\n> Un récit de voyage renseigne autant sur celui qui regarde que sur ce qu’il regarde.\n\n## Vérité et invention\nLe voyageur veut être cru : il multiplie les détails précis, les dates, les mesures. Mais il embellit aussi, pour tenir son lecteur — et certains récits mêlent l’observé et l’imaginé sans le signaler.', 1),
  ('be650aba-4083-5744-9cff-ae3b07707e28', '4366ab9b-8872-567d-bf24-2f2eb9c1a9ea', 'Partir, rêver de partir, regretter d’être parti', E'La poésie n’a pas attendu les navires pour voyager : l’**ailleurs** y est un thème constant, et souvent plus rêvé que parcouru.\n\n## Trois façons de traiter le voyage\n**1. Le voyage rêvé.**\n**Baudelaire**, « L’Invitation au voyage » : « Là, tout n’est qu’ordre et beauté, / Luxe, calme et volupté. » Le pays décrit n’existe pas : il est fait du désir du poète. C’est l’**exotisme** — l’ailleurs comme promesse.\n\n**2. Le voyage comme fuite.**\nFuir l’ennui, la médiocrité, soi-même. Baudelaire encore : « N’importe où hors du monde ». **Rimbaud** part vraiment, à dix-sept ans, et n’écrira plus.\n\n**3. Le retour et le regret.**\n**Du Bellay**, dans *Les Regrets* (1558), écrit depuis Rome le plus célèbre poème du mal du pays : « **Heureux qui, comme Ulysse, a fait un beau voyage…** » Le voyageur y préfère « le séjour qu’ont bâti mes aïeux » aux palais romains.\n\n## Les procédés à repérer\n- l’**apostrophe** et l’**impératif** : « Mon enfant, ma sœur, / Songe à la douceur… » ;\n- l’**énumération** des merveilles entrevues ;\n- les **images** — comparaison, métaphore — qui transforment le paysage en état d’âme ;\n- la **musicalité** : rythme, allitérations, refrains, qui imitent le bercement du départ ;\n- les **noms propres** exotiques, qui font rêver par leur seule sonorité.\n\n## Ulysse, la figure matrice\nDepuis l’*Odyssée*, le voyageur poétique est un homme **qui rentre**. Le voyage y vaut moins par les terres traversées que par le retour, et par ce qu’il a fait de celui qui part.\n\n> La poésie du voyage dit rarement un lieu : elle dit un **manque**. C’est pourquoi elle reste lisible quand les cartes ont changé.', 1),
  ('9ab7047e-6185-5a48-9981-59f55687f414', '6c916708-6b4d-586a-bacf-4aaff6a2264f', 'Un héros, un départ, des épreuves', E'## Ce qui fait un roman d’aventures\n- Un **héros** jeune, courageux, souvent seul, qui quitte son cadre habituel ;\n- un **départ** vers l’inconnu — île, jungle, mer, pays lointain ;\n- une succession d’**épreuves** et de **rebondissements** ;\n- des **péripéties** dangereuses : tempêtes, poursuites, captivités, trahisons ;\n- un **suspense** entretenu par les fins de chapitre ;\n- un **dénouement** où le héros revient transformé.\n\n## Les grands titres\n- **Daniel Defoe**, *Robinson Crusoé* (1719) : le naufragé qui reconstruit une civilisation sur son île ;\n- **Jules Verne**, *Le Tour du monde en 80 jours*, *Vingt mille lieues sous les mers*, *L’Île mystérieuse* ;\n- **Robert Louis Stevenson**, *L’Île au trésor* (1883) ;\n- **Jack London**, *L’Appel de la forêt* ;\n- **Alexandre Dumas**, *Les Trois Mousquetaires*, à la frontière du roman historique.\n\n## Le rythme du récit\nC’est le point technique du chapitre :\n- la **scène** : le récit prend le temps de l’action, dialogue compris ;\n- le **sommaire** : plusieurs jours résumés en quelques lignes ;\n- l’**ellipse** : un passage de temps passé sous silence ;\n- la **pause** : une description qui suspend l’action.\n\nUn roman d’aventures alterne ces vitesses : il accélère dans le danger, ralentit pour faire voir.\n\n## Le narrateur\nSouvent **interne** — le héros raconte lui-même, ce qui rend l’aventure plus vive et le lecteur plus proche. Parfois **externe**, pour ménager le suspense en montrant ce que le héros ignore.\n\n## Ce que le genre raconte vraiment\nSous les tempêtes et les trésors, le roman d’aventures est presque toujours un **récit d’apprentissage** : le héros part enfant et revient adulte. L’île, la jungle ou la mer sont les épreuves qui le construisent.\n\n> C’est pourquoi le genre parle si bien aux lecteurs de 5e : il raconte, sous forme d’exploits, ce que c’est que de grandir.', 1),
  ('fb01bb69-aa13-5463-a749-29f5dc443465', 'fde4fddf-3208-557a-829e-0de6fa170325', 'Faire rire, et faire réfléchir', E'## La comédie classique\nElle vise à « **corriger les mœurs par le rire** » (*castigat ridendo mores*). Elle met en scène des personnages ordinaires, dans un cadre quotidien, et se termine bien — le plus souvent par un mariage.\n\nComme la tragédie, elle respecte les **trois unités** (action, lieu, temps) et la **bienséance**.\n\n## Les procédés comiques\n- **de mots** : jeux de mots, patois, répétitions, quiproquos verbaux ;\n- **de gestes** : chutes, coups, grimaces, déguisements ;\n- **de situation** : quiproquo, malentendu, personnage caché qui entend tout ;\n- **de caractère** : un défaut poussé jusqu’à l’absurde ;\n- **de répétition** : une réplique qui revient et devient drôle par son retour même.\n\n## L’École des femmes (1662)\n**Arnolphe**, un homme mûr, terrifié à l’idée d’être trompé, a fait élever **Agnès** dans l’**ignorance** totale depuis l’âge de quatre ans, pour qu’elle devienne une épouse docile. Il compte l’épouser.\n\nMais Agnès rencontre **Horace**, jeune homme sans fortune — et, par une ironie parfaite, celui-ci raconte naïvement ses progrès amoureux à Arnolphe, sans savoir qu’il parle au rival. Agnès s’éveille à l’intelligence et au sentiment ; Arnolphe, qui l’aime réellement, échoue et reste seul.\n\n## Ce que la pièce met en jeu\n- L’**éducation** des filles : faut-il les instruire ou les tenir dans l’ignorance ?\n- Le **mariage** forcé et l’autorité des tuteurs ;\n- la **liberté** de choisir sa vie.\n\n> Agnès ne devient pas amoureuse **malgré** son ignorance : elle devient intelligente **en** devenant amoureuse. C’est l’ignorance, et non la nature, qui la tenait enfermée.\n\n## Un scandale\nLa pièce déclencha une violente querelle : on reprocha à Molière son immoralité et son irrespect. Il répondit par deux pièces, *La Critique de l’École des femmes* et *L’Impromptu de Versailles* — le théâtre se défendant par le théâtre.', 1),
  ('650901e0-b6d3-54eb-b7ae-1032c69d5370', '6599efec-fefb-5c60-86a9-b028fa4f86ed', 'Se raconter enfant, des années plus tard', E'## Le genre\nUn **récit d’enfance** est le récit que fait un adulte de ses jeunes années. Il relève le plus souvent de l’**autobiographie** : l’auteur, le narrateur et le personnage principal sont **la même personne** — c’est le « pacte autobiographique » défini par Philippe Lejeune.\n\n## Les grands textes\n- **Rousseau**, *Les Confessions* (1782), qui inaugure le genre moderne ;\n- **Marcel Pagnol**, *La Gloire de mon père*, *Le Château de ma mère* ;\n- **Romain Gary**, *La Promesse de l’aube* ;\n- **Nathalie Sarraute**, *Enfance* ;\n- **Hervé Bazin**, *Vipère au poing*, où la famille est un lieu de guerre ;\n- **Azouz Begag**, *Le Gone du Chaâba* ;\n- et, du côté du roman, **Hugo** avec Gavroche ou **Dickens** avec Oliver Twist.\n\n## Les deux « je »\nC’est la clé de lecture du chapitre. Deux voix se superposent :\n- le **je narrant** : l’adulte qui écrit, qui commente, qui juge, qui sait ce qui va arriver ;\n- le **je narré** : l’enfant qu’il était, qui ne savait pas.\n\nL’écart entre les deux crée l’**ironie**, la **tendresse** ou le **regret**, selon la distance que l’auteur choisit.\n\n## Les procédés\n- Les **temps du passé** : imparfait pour le décor et les habitudes, passé simple ou passé composé pour les événements ;\n- les **retours en arrière** et les **anticipations** (« je ne savais pas encore que… ») ;\n- les **sensations** — odeurs, sons, lumières —, qui font revenir le souvenir plus sûrement que les faits ;\n- le **portrait** des adultes, vus d’en bas, souvent agrandis par le regard de l’enfant.\n\n## Autobiographie ou roman ?\n- L’**autobiographie** promet la vérité.\n- Le **roman autobiographique** s’en inspire mais assume la fiction.\n- L’**autofiction** mêle les deux volontairement.\n\n> La mémoire n’enregistre pas, elle **reconstruit**. Tout récit d’enfance est donc en partie une invention — non par mensonge, mais par nature.', 1),
  ('5ae9469e-90d4-5c58-a7de-13d069e21987', '3a7a28dd-117c-5eac-9606-4dc594d578b4', 'Un monde où le surnaturel ne surprend personne', E'## Ce qui définit le merveilleux\nDans un conte merveilleux, le **surnaturel** est **admis d’emblée** : personne ne s’étonne qu’un animal parle ou qu’une fée apparaisse. C’est ce qui le distingue du **fantastique**, où l’inexplicable fait irruption dans un monde réaliste et provoque le doute.\n\n## Les marques du conte\n- une **formule d’ouverture** : « Il était une fois… », qui installe un temps et un lieu indéterminés ;\n- des **personnages types** plus que des individus : le héros, la princesse, l’ogre, la marâtre, la fée, l’adjuvant ;\n- des **objets magiques** : baguette, bottes de sept lieues, miroir, anneau ;\n- des **nombres symboliques** : trois épreuves, sept nains, cent ans de sommeil ;\n- une **fin heureuse** et souvent une **morale**.\n\n## Le schéma narratif\n1. **Situation initiale** — l’équilibre de départ ;\n2. **élément perturbateur** — ce qui rompt cet équilibre ;\n3. **péripéties** — les épreuves du héros ;\n4. **élément de résolution** — ce qui dénoue ;\n5. **situation finale** — le nouvel équilibre.\n\n## Le schéma actanciel\nLe héros (**sujet**) poursuit un **objet** ; il est aidé par des **adjuvants**, gêné par des **opposants** ; un **destinateur** l’envoie, un **destinataire** profite du résultat.\n\n## Les grands auteurs\n- **Charles Perrault** (*Contes*, 1697) : Le Petit Chaperon rouge, Cendrillon, Le Chat botté — versions écrites, avec moralités en vers ;\n- les **frères Grimm**, qui collectent les contes allemands au XIXe siècle ;\n- **Andersen**, qui les invente plus qu’il ne les recueille.\n\n## À quoi sert un conte\nIl divertit, mais il **enseigne** aussi : prudence, courage, patience, méfiance envers les apparences. Sous une forme simple, il met en scène des peurs profondes — l’abandon, la faim, la mort, la cruauté des adultes.\n\n> Le conte n’est pas naïf : c’est une histoire simple qui traite de choses très graves.', 1),
  ('fe4133bf-0980-5767-ad89-6cafe0de5b24', 'c841f7b9-62c1-579c-9266-06e8246818e5', 'Décrire un monde parfait pour juger le sien', E'## Le mot\n**Utopie** est un mot fabriqué par **Thomas More** en **1516**, à partir du grec : *ou-topos*, « **en aucun lieu** ». Le titre complet de son livre annonce déjà l’ambiguïté : il décrit une île parfaite… qui n’existe nulle part.\n\n## Ce qu’est une utopie\nLe récit d’une société **idéale**, généralement située :\n- dans un lieu **isolé** — une île, une vallée, une planète ;\n- hors du temps ordinaire ;\n- et découverte par un **voyageur**, qui sert de guide au lecteur.\n\n## Ses traits récurrents\n- **égalité** entre les habitants, absence de misère ;\n- **propriété commune** ou fortement encadrée ;\n- **travail** partagé et limité ;\n- **éducation** pour tous ;\n- **lois simples**, peu de crimes, peu de juges ;\n- une organisation **rationnelle** : villes identiques, horaires réglés, urbanisme géométrique.\n\n## Le vrai sujet : ici, pas là-bas\nUne utopie ne décrit jamais vraiment un ailleurs : elle **critique** la société de son auteur par contraste. Chez More, l’île d’Utopie sans propriété privée ni oisiveté vise l’Angleterre de son temps, ses enclosures et sa misère.\n\nC’est une **argumentation indirecte** : montrer ce qui pourrait être, pour faire voir ce qui ne va pas.\n\n## Les grands textes\nPlaton (*La République*), Thomas More, **Rabelais** avec l’**abbaye de Thélème** et sa règle unique — « Fais ce que voudras » —, Campanella, Fourier, et jusqu’aux cités idéales des architectes.\n\n## La limite, et le passage à la dystopie\nUne société parfaite suppose que tout le monde veuille la même chose. Ce qui garantit l’ordre — l’uniformité, la surveillance, l’absence de choix — peut vite devenir **oppressant**. C’est exactement le point où l’utopie bascule en **dystopie**, dès le XXe siècle.\n\n> Toute utopie contient sa propre inquiétude : qui décide de ce qui est parfait, et que fait-on de ceux qui ne sont pas d’accord ?', 1),
  ('8f49f49f-1a1d-58be-8dec-09530aadff73', '6b657546-53d8-51cd-8eaf-0b914516971f', 'Le cauchemar qui se présente comme un idéal', E'## La définition\nUne **dystopie** (ou contre-utopie) décrit une société **en apparence parfaite**, mais en réalité **totalitaire** : l’ordre y est obtenu au prix de la liberté. C’est l’inverse exact de l’utopie — et son prolongement logique.\n\n## Les traits du genre\n- Un **régime** qui contrôle tout : information, travail, loisirs, famille, pensée ;\n- une **surveillance** permanente ;\n- la **propagande** et la **réécriture** du passé ;\n- l’**uniformisation** des individus, souvent désignés par des numéros ;\n- l’élimination des **opposants** ;\n- un **héros** qui prend conscience et tente de résister — et qui, très souvent, échoue.\n\n## Les grands textes\n- **Evgueni Zamiatine**, *Nous autres* (1920), le premier du genre ;\n- **Aldous Huxley**, *Le Meilleur des mondes* (1932) : une société où l’on est heureux par conditionnement et par drogue ;\n- **George Orwell**, *1984* (1949) : Big Brother, la police de la pensée, la **novlangue** — une langue appauvrie pour rendre la révolte littéralement impensable ;\n- **Ray Bradbury**, *Fahrenheit 451* (1953) : des pompiers qui brûlent les livres ;\n- pour la jeunesse : *Hunger Games*, *Divergente*, *Le Passeur* de Lois Lowry.\n\n## Deux formes d’oppression\n- Chez **Orwell**, on obéit par **peur** : la surveillance et la torture.\n- Chez **Huxley**, on obéit par **plaisir** : le divertissement et le confort suffisent à faire renoncer à la liberté.\n\n> Huxley redoutait qu’on n’ait plus besoin d’interdire les livres, parce que plus personne n’aurait envie d’en lire.\n\n## Une fiction qui parle du présent\nComme l’utopie, la dystopie **avertit** : elle prend une tendance de son époque — la propagande, la technique, la surveillance, le divertissement de masse — et la pousse à l’extrême pour la rendre visible.\n\n## Le repérage en classe\nChercher **qui détient le pouvoir**, **ce qui est interdit**, **comment on surveille**, **ce que le héros découvre** et **ce que le récit reproche à notre monde**.', 1),
  ('6281cfa3-370a-5f02-ab91-7b42a2d7222b', 'a4a0a655-c66d-5180-9dba-7afc5b3d5891', 'Le chevalier, entre prouesse et courtoisie', E'## Deux grandes familles de récits\n- La **chanson de geste** (XIe-XIIe siècles) : un récit en vers, chanté par les **jongleurs**, qui célèbre les exploits guerriers et la fidélité au seigneur. Modèle : **La Chanson de Roland** (vers 1100).\n- Le **roman de chevalerie** (XIIe-XIIIe) : écrit pour être lu, il ajoute l’**amour** et la **quête** intérieure. Modèle : **Chrétien de Troyes** (*Yvain ou le Chevalier au lion*, *Perceval ou le Conte du Graal*, *Lancelot*).\n\n## Les valeurs du chevalier\n- la **prouesse** : le courage et la force au combat ;\n- la **loyauté** envers son seigneur — c’est le lien vassalique ;\n- la **foi** : le chevalier chrétien combat pour Dieu ;\n- la **générosité** (largesse) envers les pauvres et les vaincus ;\n- la **courtoisie** : le respect des dames, la maîtrise de soi, l’élégance des manières ;\n- la **démesure** est le défaut à éviter — Roland refuse de sonner l’olifant par orgueil, et tous ses hommes en meurent.\n\n## La Chanson de Roland\nL’arrière-garde de Charlemagne est attaquée à **Roncevaux**. **Roland**, neveu de l’empereur, refuse d’appeler à l’aide tant qu’il est temps ; il sonne son cor trop tard, meurt le visage tourné vers l’ennemi, et Charlemagne vient venger les siens. Le poème est écrit en **laisses** — des strophes de longueur variable, sur une même assonance.\n\n## L’amour courtois\nLe chevalier sert une **dame** souvent inaccessible ; il accomplit des exploits **pour** elle, et cette souffrance amoureuse le rend meilleur. La femme y prend, pour la première fois dans la littérature occidentale, une position **haute**.\n\n## Le merveilleux\nFées, enchanteurs (**Merlin**), objets magiques, animaux qui parlent, **Graal** : le surnaturel fait partie du monde, sans surprendre personne — comme dans le conte.\n\n> Le héros médiéval n’est pas seulement fort : il est **exemplaire**. Sa vie sert de modèle à ceux qui l’écoutent.', 1),
  ('5f222574-1d38-5015-bc9e-1ffb65c4ceaa', '01669d26-296b-5577-bdc5-f80eaba6227d', 'Demi-dieux, exploits et destin', E'## Qu’est-ce qu’un héros antique ?\nDans la mythologie grecque, le **héros** est un personnage exceptionnel, souvent né d’un dieu et d’une mortelle. Il n’est ni tout à fait dieu, ni tout à fait homme : il accomplit des exploits surhumains, mais il **meurt**.\n\n## Les grandes figures\n- **Achille**, le meilleur guerrier de l’*Iliade*, invulnérable sauf au talon. Il choisit une vie **courte et glorieuse** plutôt que longue et obscure.\n- **Ulysse**, héros de l’*Odyssée* : sa force est la **ruse** (le cheval de Troie, le Cyclope) et la **ténacité** — dix ans pour rentrer à Ithaque.\n- **Héraclès** (Hercule), et ses **douze travaux**, expiation d’une faute.\n- **Thésée** et le **Minotaure**, sauvé par le fil d’**Ariane**.\n- **Persée**, **Jason** et la Toison d’or, **Antigone** qui désobéit au roi au nom d’une loi supérieure.\n- Chez les Romains : **Énée**, héros de l’*Énéide* de Virgile, fondateur mythique de Rome.\n\n## Les traits communs\n- une **naissance** extraordinaire, souvent accompagnée d’un oracle ;\n- des **épreuves** imposées, presque toujours par les dieux ;\n- des **monstres** à vaincre : Cyclope, Hydre, Minotaure, Méduse ;\n- un **défaut** qui coûte cher — la colère d’Achille, la curiosité, l’orgueil (**hybris**), toujours puni par les dieux ;\n- un **destin** fixé d’avance, que le héros ne peut pas fuir.\n\n## Deux modèles d’héroïsme\nAchille et Ulysse s’opposent terme à terme : la **force** contre la **ruse**, la gloire contre le retour, la mort jeune contre la survie. Toute la littérature occidentale se partagera entre ces deux figures.\n\n## Les œuvres\nL’*Iliade* et l’*Odyssée*, attribuées à **Homère** (VIIIe siècle av. J.-C.), les *Métamorphoses* d’**Ovide**, l’*Énéide* de **Virgile**.\n\n> Le héros antique n’est pas un modèle moral : il est **admirable et faillible** à la fois. C’est cette ambiguïté qui le rend inépuisable.', 1),
  ('341f0455-2fc0-5400-9c76-37897d284452', '6a380608-689d-5a2d-b67e-70358a89b0d7', 'La littérature face aux machines', E'## Le contexte\nAu **XIXe siècle**, la machine à vapeur, le charbon, le chemin de fer et l’usine transforment l’Europe en quelques décennies. Les campagnes se vident, les villes industrielles enflent, un nouveau monde apparaît — et avec lui, une nouvelle **question littéraire** : que devient l’homme dans ce monde qu’il a fabriqué ?\n\n## Deux regards opposés\n**L’enthousiasme.** Le progrès promet de vaincre la maladie, la distance, la nuit. **Jules Verne** en fait la matière de ses romans ; **Hugo** salue le train comme un poème. La technique y est une conquête.\n\n**L’inquiétude.** La même machine détruit les paysages, épuise les corps et rompt le lien avec la nature.\n- **Zola**, *Germinal* (1885) : la mine est décrite comme un monstre vivant qui **dévore** les hommes — « une bête goulue » ;\n- **Zola**, *La Bête humaine* : la locomotive devient un personnage ;\n- **Hugo**, *Les Misérables*, sur la misère urbaine.\n\n## Le procédé central : la personnification\nLa machine, l’usine, la mine sont dotées d’un **corps** et d’une **volonté**. Elles respirent, avalent, grondent. À l’inverse, l’ouvrier est décrit comme une **chose** : un rouage, un outil. Ce **renversement** — la machine vivante et l’homme mécanisé — est la trouvaille majeure du roman industriel.\n\n## Le romantisme et la nature refuge\nFace à cela, les romantiques font de la **nature** un refuge et un miroir de l’âme : **Rousseau** déjà, puis **Lamartine**, **Hugo**, et plus tard **Giono**, qui oppose la vie paysanne à la modernité.\n\n## Ce que le chapitre met en jeu\nL’homme est-il **maître** de la nature — ou en fait-il partie ? La révolution industrielle donne à cette question une portée nouvelle : pour la première fois, l’activité humaine transforme la planète à grande échelle.\n\n> Les textes du XIXe siècle formulent, avec un siècle et demi d’avance, les questions écologiques d’aujourd’hui.', 1),
  ('c1f1cd41-1146-5bdb-8b5b-832397bf3d66', 'f4b8a80c-f446-52cc-b212-3153a99aa0ac', 'Raconter demain pour comprendre aujourd’hui', E'## La définition\nLe **roman d’anticipation** situe son récit dans le **futur** et imagine les conséquences d’une évolution scientifique, technique ou sociale déjà commencée. Il se distingue de la **science-fiction** au sens large par sa proximité avec le présent : il extrapole, il n’invente pas un univers entier.\n\n## Les fondateurs\n- **Jules Verne** (*De la Terre à la Lune*, *Vingt mille lieues sous les mers*, *Paris au XXe siècle*) : l’anticipation y est **technique**, documentée, optimiste — le sous-marin, la fusée, le visiophone.\n- **H. G. Wells** (*La Machine à explorer le temps*, *La Guerre des mondes*, *L’Île du docteur Moreau*) : l’anticipation y devient **sociale et morale**, et souvent inquiète.\n\n## Le siècle suivant\n**Barjavel** (*Ravage*, 1943), **Bradbury**, **Asimov** et ses lois de la robotique, **Orwell** et **Huxley** pour le versant dystopique, et aujourd’hui toute une production sur le climat, l’intelligence artificielle et la génétique.\n\n## Les grands thèmes\n- le **progrès technique** et ses effets non prévus ;\n- la **catastrophe écologique** ;\n- l’**intelligence artificielle** et la place de l’humain ;\n- la **manipulation** du vivant ;\n- la **surveillance** et la perte des libertés.\n\n## Les procédés d’écriture\n- Un **cadre** futur rendu crédible par des détails concrets ;\n- un **vocabulaire** technique, parfois inventé — le **néologisme** ;\n- une **date** qui ancre le récit et le rend mesurable ;\n- des **explications** données au lecteur par un personnage — le savant, le guide, le nouveau venu ;\n- le **contraste** entre le monde décrit et le nôtre, qui produit le sens.\n\n> L’anticipation ne prédit pas l’avenir : elle prend une tendance du présent et demande « **et si cela continuait ?** ». Ses erreurs de prédiction ne l’invalident pas, parce que ce n’était pas le but.\n\n## La lecture critique\nDevant un tel texte : quelle tendance actuelle est poussée à l’extrême ? qu’est-ce que l’auteur redoute ? qu’est-ce qu’il espère ? Et surtout : que dit ce futur du monde dans lequel il a été écrit ?', 1),
  ('90b8bd51-09fd-5216-80f7-6301ec642b51', '720b0dcc-d36b-5605-8a79-d187aef534b0', 'Le jardin comme réponse à une question', E'La façon dont une époque **représente** la nature dit ce qu’elle en pense. Trois moments, trois réponses.\n\n## Le Moyen Âge : la nature encadrée\n- Le **jardin clos** (*hortus conclusus*), entouré de murs : un espace protégé, utile (herbes médicinales, légumes) et symbolique — image du paradis retrouvé.\n- La **forêt**, à l’inverse, est le lieu du danger, de l’épreuve et du merveilleux : c’est là que les chevaliers de Chrétien de Troyes rencontrent fées, ermites et monstres.\n- Dans les **enluminures**, la nature est peinte sans profondeur, en aplats, sur fond d’or : elle est un **signe**, pas un paysage.\n\n## La Renaissance : la nature observée\n- L’**humanisme** réhabilite l’observation. **Léonard de Vinci** dessine des plantes, des eaux, des anatomies avec une précision inédite.\n- La **perspective** fait entrer la profondeur dans la peinture : le paysage devient un **espace**, et non plus un décor plat.\n- Les **jardins italiens** allient géométrie, statues, grottes et jeux d’eau — la nature y est mise en scène, pas contrainte.\n- **Ronsard** chante la rose et le temps qui passe : la nature devient miroir du sentiment.\n\n## Le XVIIe siècle : la nature soumise\n- Le **jardin à la française** — **Le Nôtre** à **Versailles** — pousse la maîtrise à son terme : axes de symétrie, perspectives infinies, parterres géométriques, arbres taillés, eaux domptées. La nature y devient une **démonstration de pouvoir** : ce que le roi fait aux arbres, il le fait au royaume.\n- **La Fontaine**, dans ses *Fables*, se sert au contraire des animaux pour dire la vérité des hommes — la nature y redevient une leçon.\n- **Descartes** formule le programme du siècle : l’homme doit se rendre « comme maître et possesseur de la nature ».\n\n> Jardin clos, jardin observé, jardin dompté : trois manières de répondre à la même question, et trois idées de la place de l’homme dans le monde.\n\n## Et après\nLe **jardin à l’anglaise** du XVIIIe siècle prendra le contre-pied de Versailles : allées sinueuses, faux désordre, ruines artificielles. La nature n’est plus à soumettre, elle est à **rêver**.', 1)
ON CONFLICT DO NOTHING;

-- 3. Quiz ------------------------------------------------------------------
-- Double garde : ON CONFLICT (id) protège du rejeu, et le NOT EXISTS protège
-- la leçon d’un SECOND quiz venu d’ailleurs — le hub de leçon lit son quiz en
-- .maybeSingle(), deux quiz feraient lever « multiple rows » à de vrais élèves.
INSERT INTO public.quizzes (id, title, subject, grade_level, chapter, is_free, lesson_id)
SELECT v.id, v.title, v.subject, v.grade_level, v.chapter, true, l.id
  FROM (VALUES
    ('c050ab68-6bdb-54cd-a5aa-cdeb1bda79b4'::uuid, 'Quiz — Le récit de voyage, entre témoignage et invention', 'Français', '5e', 'Les grandes découvertes', 'a82f20bb-501f-5d1a-9c95-6c5c2fb01221'::uuid),
    ('c6fca859-7a2e-54bb-9021-b384f8d2e62a'::uuid, 'Quiz — Partir, rêver de partir, regretter d’être parti', 'Français', '5e', 'Les voyages et la séduction de l’ailleurs dans la poésie', 'be650aba-4083-5744-9cff-ae3b07707e28'::uuid),
    ('cdc6285f-68a6-5c0b-8753-4ae0ec4882ac'::uuid, 'Quiz — Un héros, un départ, des épreuves', 'Français', '5e', 'Le roman d’aventures', '9ab7047e-6185-5a48-9981-59f55687f414'::uuid),
    ('8c8cb929-15ab-5f35-9587-4a0b19cfcd05'::uuid, 'Quiz — Faire rire, et faire réfléchir', 'Français', '5e', 'La comédie au XVIIe siècle : L’École des femmes, Molière', 'fb01bb69-aa13-5463-a749-29f5dc443465'::uuid),
    ('09ffe2cc-421a-5310-bcdb-b7436d1c3c53'::uuid, 'Quiz — Se raconter enfant, des années plus tard', 'Français', '5e', 'Les récits d’enfance et d’adolescence', '650901e0-b6d3-54eb-b7ae-1032c69d5370'::uuid),
    ('1085c544-4149-518c-be7a-bf2c1ee89d30'::uuid, 'Quiz — Un monde où le surnaturel ne surprend personne', 'Français', '5e', 'Le conte merveilleux', '5ae9469e-90d4-5c58-a7de-13d069e21987'::uuid),
    ('ffd21155-410e-5d3d-bd46-2ceb1711453a'::uuid, 'Quiz — Décrire un monde parfait pour juger le sien', 'Français', '5e', 'L’utopie', 'fe4133bf-0980-5767-ad89-6cafe0de5b24'::uuid),
    ('45911ff2-16c6-5203-b443-023cdea2830f'::uuid, 'Quiz — Le cauchemar qui se présente comme un idéal', 'Français', '5e', 'La dystopie', '8f49f49f-1a1d-58be-8dec-09530aadff73'::uuid),
    ('2780a9d7-75c9-5deb-9c28-66f323451bee'::uuid, 'Quiz — Le chevalier, entre prouesse et courtoisie', 'Français', '5e', 'Le héros médiéval', '6281cfa3-370a-5f02-ab91-7b42a2d7222b'::uuid),
    ('fbcd89e7-81df-5ce3-b822-9bf9f104bf3e'::uuid, 'Quiz — Demi-dieux, exploits et destin', 'Français', '5e', 'Le héros de l’Antiquité', '5f222574-1d38-5015-bc9e-1ffb65c4ceaa'::uuid),
    ('3bf16b64-72ca-5501-bd4e-65d53c34a206'::uuid, 'Quiz — La littérature face aux machines', 'Français', '5e', 'La révolution industrielle, facteur de rupture entre l’Homme et la nature', '341f0455-2fc0-5400-9c76-37897d284452'::uuid),
    ('600f0b00-3e2f-5b18-8a42-f54d14dfe4e9'::uuid, 'Quiz — Raconter demain pour comprendre aujourd’hui', 'Français', '5e', 'Le roman d’anticipation', 'c1f1cd41-1146-5bdb-8b5b-832397bf3d66'::uuid),
    ('33aa3d61-4613-571d-a372-388488850abb'::uuid, 'Quiz — Le jardin comme réponse à une question', 'Français', '5e', 'L’art de discipliner ou de rêver la nature du Moyen Âge au XVIIe siècle', '90b8bd51-09fd-5216-80f7-6301ec642b51'::uuid)
  ) AS v(id, title, subject, grade_level, chapter, lesson_id)
  JOIN public.lessons l ON l.id = v.lesson_id
 WHERE NOT EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.lesson_id = l.id)
ON CONFLICT (id) DO NOTHING;

-- 4. Questions -------------------------------------------------------------
INSERT INTO public.quiz_questions (id, quiz_id, question, kind, options, correct_index, explanation, position)
SELECT v.id, v.quiz_id, v.question, v.kind, v.options, v.correct_index, v.explanation, v.position
  FROM (VALUES
    ('a99dd68c-dfe8-5957-b5cb-5e3a7a6d61f3'::uuid, 'c050ab68-6bdb-54cd-a5aa-cdeb1bda79b4'::uuid, 'Qu’est-ce qu’un récit de voyage ?', 'mcq', '["Le récit d’un déplacement réel vers des terres lointaines","Un roman d’aventures imaginaire","Un poème sur l’exil","Une pièce de théâtre sur la mer"]'::jsonb, 0, 'Le narrateur s’y porte garant de ce qu’il rapporte.', 1),
    ('f1b2e554-8b0e-508e-8dd0-9cf53bef9414'::uuid, 'c050ab68-6bdb-54cd-a5aa-cdeb1bda79b4'::uuid, 'Quel voyageur a raconté ses années en Chine vers 1298 ?', 'mcq', '["Marco Polo","Christophe Colomb","Jean de Léry","Jacques Cartier"]'::jsonb, 0, 'Son livre est surnommé Le Livre des merveilles.', 2),
    ('f9ea24c9-40e8-5f9c-9718-23909d013338'::uuid, 'c050ab68-6bdb-54cd-a5aa-cdeb1bda79b4'::uuid, 'Quel texte de Jean de Léry porte un regard ethnographique sur le Brésil ?', 'mcq', '["Histoire d’un voyage en terre de Brésil","Le Devisement du monde","Les Essais","Le Journal de bord"]'::jsonb, 0, 'Publié en 1578.', 3),
    ('bd44b35f-4f51-5aae-856a-1a273db62430'::uuid, 'c050ab68-6bdb-54cd-a5aa-cdeb1bda79b4'::uuid, 'Quelle personne domine dans un récit de voyage ?', 'mcq', '["La première personne, le « je » du voyageur","La troisième personne","La deuxième personne","Un narrateur omniscient"]'::jsonb, 0, 'Elle garantit le témoignage.', 4),
    ('f1222dcf-3132-5eb0-8f62-1a808a165c71'::uuid, 'c050ab68-6bdb-54cd-a5aa-cdeb1bda79b4'::uuid, 'Quel procédé permet de faire imaginer l’inconnu au lecteur ?', 'mcq', '["La comparaison avec ce qu’il connaît déjà","L’ellipse","Le dialogue","Le monologue intérieur"]'::jsonb, 0, 'On décrit le nouveau par le familier.', 5),
    ('b2762589-2af1-5abb-8488-a7c6e2331f15'::uuid, 'c050ab68-6bdb-54cd-a5aa-cdeb1bda79b4'::uuid, 'Dans quel texte Montaigne interroge-t-il la notion de barbarie ?', 'mcq', '["« Des cannibales », dans les Essais","Le Devisement du monde","L’École des femmes","Le journal de Colomb"]'::jsonb, 0, 'Les vrais barbares ne sont peut-être pas ceux qu’on croit.', 6),
    ('4c9b56b5-5a5d-589f-8f40-a1598ef0afb3'::uuid, 'c050ab68-6bdb-54cd-a5aa-cdeb1bda79b4'::uuid, 'Qu’est-ce que la figure du « bon sauvage » ?', 'mcq', '["L’image d’un peuple lointain vertueux, qui sert à critiquer sa propre société","Un personnage de conte merveilleux","Un héros de roman d’aventures","Un navigateur célèbre"]'::jsonb, 0, 'Elle en dit plus sur l’Europe que sur les peuples décrits.', 7),
    ('b3277773-dbce-5cd0-aee2-d9d28e8305a5'::uuid, 'c050ab68-6bdb-54cd-a5aa-cdeb1bda79b4'::uuid, 'Un récit de voyage rapporte uniquement des faits vérifiés.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Le voyageur embellit souvent pour tenir son lecteur.', 8),
    ('1f6037bd-60ab-5e72-8a5b-e213190e397c'::uuid, 'c6fca859-7a2e-54bb-9021-b384f8d2e62a'::uuid, 'Quel poème de Baudelaire décrit un pays rêvé « ordre et beauté » ?', 'mcq', '["« L’Invitation au voyage »","« Le Pont Mirabeau »","« Demain, dès l’aube… »","« Le Dormeur du val »"]'::jsonb, 0, 'Le pays décrit n’existe pas : il est fait du désir du poète.', 1),
    ('c772fd9d-ffb8-5431-8400-2c6c330fdd5e'::uuid, 'c6fca859-7a2e-54bb-9021-b384f8d2e62a'::uuid, 'Qu’est-ce que l’exotisme en poésie ?', 'mcq', '["L’ailleurs présenté comme une promesse séduisante","Le récit exact d’un voyage réel","La description d’une ville natale","Un poème écrit en langue étrangère"]'::jsonb, 0, 'Il tient plus du rêve que de l’observation.', 2),
    ('f4e8ca5c-fada-5bc1-be84-6b3433a0046f'::uuid, 'c6fca859-7a2e-54bb-9021-b384f8d2e62a'::uuid, 'Quel poète écrit « Heureux qui, comme Ulysse, a fait un beau voyage » ?', 'mcq', '["Du Bellay","Baudelaire","Rimbaud","Hugo"]'::jsonb, 0, 'Dans Les Regrets, publié en 1558.', 3),
    ('b9ba093f-7dab-5daa-ada9-a1f573a183a9'::uuid, 'c6fca859-7a2e-54bb-9021-b384f8d2e62a'::uuid, 'Que regrette Du Bellay dans ce sonnet ?', 'mcq', '["Son village natal, préféré aux palais romains","Son départ manqué","Sa jeunesse perdue","Un amour disparu"]'::jsonb, 0, 'C’est le poème du mal du pays.', 4),
    ('f8f8ae32-9aa8-546c-bb3c-5109bfec14f8'::uuid, 'c6fca859-7a2e-54bb-9021-b384f8d2e62a'::uuid, 'Quelle figure antique sert de modèle au voyageur poétique ?', 'mcq', '["Ulysse","Achille","Hercule","Énée"]'::jsonb, 0, 'Le voyage y vaut par le retour.', 5),
    ('2c5d05b4-44b7-5300-85ab-59e5f3a57bdb'::uuid, 'c6fca859-7a2e-54bb-9021-b384f8d2e62a'::uuid, 'Quel procédé imite le bercement du départ ?', 'mcq', '["La musicalité : rythme, allitérations, refrains","L’ellipse narrative","Le dialogue","La chute"]'::jsonb, 0, 'La forme y produit une sensation autant que le sens.', 6),
    ('ac398019-c7d2-5ca0-bdb4-e26edf29d7b9'::uuid, 'c6fca859-7a2e-54bb-9021-b384f8d2e62a'::uuid, 'Pourquoi les noms propres exotiques sont-ils employés en poésie ?', 'mcq', '["Pour faire rêver par leur seule sonorité","Pour situer précisément l’action","Pour justifier le voyage","Pour dater le poème"]'::jsonb, 0, 'Le son y compte autant que le lieu désigné.', 7),
    ('19262bd5-4d4b-5092-9d45-fea38b59778f'::uuid, 'c6fca859-7a2e-54bb-9021-b384f8d2e62a'::uuid, 'Les poètes qui chantent l’ailleurs y sont toujours allés.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'L’ailleurs poétique est le plus souvent rêvé, pas parcouru.', 8),
    ('d3cc3882-2651-5413-8d26-9d43b7f61b6c'::uuid, 'cdc6285f-68a6-5c0b-8753-4ae0ec4882ac'::uuid, 'Qu’est-ce qui caractérise un roman d’aventures ?', 'mcq', '["Un héros qui quitte son cadre habituel et affronte des épreuves","Une intrigue sentimentale","Un récit sans action","Une enquête policière"]'::jsonb, 0, 'Rebondissements et suspense en sont les moteurs.', 1),
    ('6829fe79-ba50-5a6b-8f11-684383d58612'::uuid, 'cdc6285f-68a6-5c0b-8753-4ae0ec4882ac'::uuid, 'Quel roman de 1719 raconte l’histoire d’un naufragé sur une île ?', 'mcq', '["Robinson Crusoé","L’Île au trésor","L’Appel de la forêt","Vingt mille lieues sous les mers"]'::jsonb, 0, 'De Daniel Defoe.', 2),
    ('5cfc04ff-701f-522f-b06a-093dc6c7fa19'::uuid, 'cdc6285f-68a6-5c0b-8753-4ae0ec4882ac'::uuid, 'Qui a écrit L’Île au trésor ?', 'mcq', '["Robert Louis Stevenson","Jules Verne","Jack London","Alexandre Dumas"]'::jsonb, 0, 'Publié en 1883.', 3),
    ('3436069b-d65c-5764-b056-f992970407e2'::uuid, 'cdc6285f-68a6-5c0b-8753-4ae0ec4882ac'::uuid, 'Qu’est-ce qu’une ellipse narrative ?', 'mcq', '["Un passage de temps passé sous silence","Une description détaillée","Un dialogue rapporté","Un retour en arrière"]'::jsonb, 0, 'Elle accélère le récit.', 4),
    ('957e191e-966a-59fe-80e8-5c63a7d0b7bb'::uuid, 'cdc6285f-68a6-5c0b-8753-4ae0ec4882ac'::uuid, 'Qu’est-ce qu’une pause dans un récit ?', 'mcq', '["Une description qui suspend l’action","Un chapitre sans personnage","Une fin de chapitre","Un résumé de plusieurs jours"]'::jsonb, 0, 'Le sommaire, lui, résume.', 5),
    ('e19c8e0c-80e8-5537-b32f-dca344928d7e'::uuid, 'cdc6285f-68a6-5c0b-8753-4ae0ec4882ac'::uuid, 'Quel effet produit un narrateur interne ?', 'mcq', '["Il rend l’aventure plus vive et rapproche le lecteur du héros","Il permet de tout savoir","Il supprime le suspense","Il ralentit le récit"]'::jsonb, 0, 'Un narrateur externe permet, lui, de montrer ce que le héros ignore.', 6),
    ('4148c1ac-5c96-5333-b4dc-cb9372a2cdd3'::uuid, 'cdc6285f-68a6-5c0b-8753-4ae0ec4882ac'::uuid, 'Que raconte au fond un roman d’aventures ?', 'mcq', '["Un apprentissage : le héros part enfant et revient adulte","Une enquête historique","Une critique politique","Un amour contrarié"]'::jsonb, 0, 'Les épreuves construisent le personnage.', 7),
    ('dadf0a86-3413-52e4-962e-bf09f714e407'::uuid, 'cdc6285f-68a6-5c0b-8753-4ae0ec4882ac'::uuid, 'Un roman d’aventures maintient le même rythme du début à la fin.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il alterne scènes, sommaires, ellipses et pauses.', 8),
    ('39c62c03-961a-5b11-8cba-2520b3abaf7e'::uuid, '8c8cb929-15ab-5f35-9587-4a0b19cfcd05'::uuid, 'Quel est le but affiché de la comédie classique ?', 'mcq', '["Corriger les mœurs par le rire","Provoquer la terreur et la pitié","Raconter l’histoire des rois","Enseigner la religion"]'::jsonb, 0, 'La formule latine est castigat ridendo mores.', 1),
    ('08725d0a-2f1b-540f-a61b-0af08aa1e039'::uuid, '8c8cb929-15ab-5f35-9587-4a0b19cfcd05'::uuid, 'Qu’est-ce qu’un comique de caractère ?', 'mcq', '["Un défaut poussé jusqu’à l’absurde","Un jeu de mots répété","Une chute sur scène","Un malentendu entre personnages"]'::jsonb, 0, 'Le comique de situation repose, lui, sur le quiproquo.', 2),
    ('d7cd22ac-6e67-5577-82d1-d74b7e3f362e'::uuid, '8c8cb929-15ab-5f35-9587-4a0b19cfcd05'::uuid, 'Comment Arnolphe a-t-il fait élever Agnès ?', 'mcq', '["Dans l’ignorance totale, pour en faire une épouse docile","Au couvent, pour la protéger","Chez ses parents, à la campagne","Avec les meilleurs précepteurs"]'::jsonb, 0, 'Depuis l’âge de quatre ans.', 3),
    ('298754e7-8096-50da-a2a7-aa665a7f3fec'::uuid, '8c8cb929-15ab-5f35-9587-4a0b19cfcd05'::uuid, 'Quelle ironie structure la pièce ?', 'mcq', '["Horace raconte ses progrès amoureux à Arnolphe sans savoir qu’il est son rival","Agnès se déguise en homme","Arnolphe se fait passer pour Horace","Agnès ignore l’existence d’Horace"]'::jsonb, 0, 'Le spectateur en sait plus que les personnages.', 4),
    ('3ff5a365-af87-5e18-84b0-82a72cf4e918'::uuid, '8c8cb929-15ab-5f35-9587-4a0b19cfcd05'::uuid, 'Comment la pièce se termine-t-elle pour Arnolphe ?', 'mcq', '["Il échoue et reste seul","Il épouse Agnès","Il pardonne aux amoureux et les marie","Il quitte la ville avec Agnès"]'::jsonb, 0, 'Il l’aimait pourtant réellement.', 5),
    ('10c49f37-8dd8-5b84-8bb3-92459eec74d8'::uuid, '8c8cb929-15ab-5f35-9587-4a0b19cfcd05'::uuid, 'Quelle question la pièce pose-t-elle sur l’éducation ?', 'mcq', '["Faut-il instruire les filles ou les tenir dans l’ignorance ?","Faut-il envoyer les enfants à l’école publique ?","Faut-il enseigner le latin ?","Faut-il séparer garçons et filles ?"]'::jsonb, 0, 'Agnès s’éveille à l’intelligence en s’éveillant au sentiment.', 6),
    ('5cb0a1a9-c6a6-5d3b-b722-37f9b436bb72'::uuid, '8c8cb929-15ab-5f35-9587-4a0b19cfcd05'::uuid, 'Comment Molière a-t-il répondu à la querelle suscitée par la pièce ?', 'mcq', '["Par deux nouvelles pièces de théâtre","Par une lettre au roi","Par un procès","Par le silence"]'::jsonb, 0, 'La Critique de l’École des femmes et L’Impromptu de Versailles.', 7),
    ('7a0bd4ed-694b-5516-992d-3fa56c30c9cd'::uuid, '8c8cb929-15ab-5f35-9587-4a0b19cfcd05'::uuid, 'La comédie classique se termine généralement mal.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Elle finit bien, le plus souvent par un mariage.', 8),
    ('36063df7-3de3-5ac5-b1e7-1aa3f3c10e55'::uuid, '09ffe2cc-421a-5310-bcdb-b7436d1c3c53'::uuid, 'Qu’est-ce que le pacte autobiographique ?', 'mcq', '["L’auteur, le narrateur et le personnage principal sont la même personne","Un contrat entre l’auteur et son éditeur","La promesse de ne rien inventer","L’engagement d’écrire à la première personne"]'::jsonb, 0, 'La notion a été définie par Philippe Lejeune.', 1),
    ('2d937297-43a6-5ce6-8c70-b972cb5fd21a'::uuid, '09ffe2cc-421a-5310-bcdb-b7436d1c3c53'::uuid, 'Quelle œuvre de Rousseau inaugure l’autobiographie moderne ?', 'mcq', '["Les Confessions","Émile","Le Contrat social","La Nouvelle Héloïse"]'::jsonb, 0, 'Publiée en 1782.', 2),
    ('679a6f21-d808-599d-ac59-6c7e0b4f50cd'::uuid, '09ffe2cc-421a-5310-bcdb-b7436d1c3c53'::uuid, 'Que désigne le « je narrant » ?', 'mcq', '["L’adulte qui écrit et commente","L’enfant dont on parle","Le lecteur","Un personnage secondaire"]'::jsonb, 0, 'Le « je narré » est l’enfant qu’il était.', 3),
    ('9f3f1699-b4c1-5ae0-9f46-0cab4fdd2110'::uuid, '09ffe2cc-421a-5310-bcdb-b7436d1c3c53'::uuid, 'Qu’est-ce que l’écart entre les deux « je » produit ?', 'mcq', '["De l’ironie, de la tendresse ou du regret","Une erreur de narration","Un changement de genre","Une rupture de la chronologie"]'::jsonb, 0, 'C’est la distance choisie par l’auteur.', 4),
    ('5bf8ae21-57b5-5d1f-99f0-1d5fde3e4e9b'::uuid, '09ffe2cc-421a-5310-bcdb-b7436d1c3c53'::uuid, 'Quel temps sert au décor et aux habitudes dans un récit d’enfance ?', 'mcq', '["L’imparfait","Le passé simple","Le présent","Le futur"]'::jsonb, 0, 'Le passé simple ou composé porte, lui, les événements.', 5),
    ('1945e229-e2d1-50ef-a251-8b5fef9a8019'::uuid, '09ffe2cc-421a-5310-bcdb-b7436d1c3c53'::uuid, 'Qu’est-ce qui fait le plus sûrement revenir un souvenir dans ces récits ?', 'mcq', '["Les sensations : odeurs, sons, lumières","Les dates précises","Les noms des lieux","Les documents d’archives"]'::jsonb, 0, 'C’est le ressort du souvenir chez Proust comme chez Pagnol.', 6),
    ('66152a9b-9829-557d-88d8-3f8f7077e95d'::uuid, '09ffe2cc-421a-5310-bcdb-b7436d1c3c53'::uuid, 'Quelle différence y a-t-il entre autobiographie et autofiction ?', 'mcq', '["L’autobiographie promet la vérité, l’autofiction assume le mélange avec la fiction","L’autofiction est plus courte","L’autobiographie est écrite à la troisième personne","Il n’y a aucune différence"]'::jsonb, 0, 'Le roman autobiographique s’inspire du vécu en assumant la fiction.', 7),
    ('ae57659a-6187-575b-b226-7651da56f49b'::uuid, '09ffe2cc-421a-5310-bcdb-b7436d1c3c53'::uuid, 'Un récit d’enfance restitue fidèlement le passé.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'La mémoire reconstruit : tout récit d’enfance est en partie une invention.', 8),
    ('c38b6b67-902f-5ade-8601-abf9b2dc16cf'::uuid, '1085c544-4149-518c-be7a-bf2c1ee89d30'::uuid, 'Qu’est-ce qui caractérise le merveilleux ?', 'mcq', '["Le surnaturel y est admis sans étonner personne","Le surnaturel y provoque le doute","Il n’y a aucun élément surnaturel","Le surnaturel y est expliqué scientifiquement"]'::jsonb, 0, 'C’est ce qui le distingue du fantastique.', 1),
    ('c9b3cb36-98b2-5969-a6a7-fc4d3669ee9b'::uuid, '1085c544-4149-518c-be7a-bf2c1ee89d30'::uuid, 'Quelle formule ouvre traditionnellement un conte ?', 'mcq', '["« Il était une fois… »","« Ceci est une histoire vraie »","« En l’an de grâce… »","« Écoutez, bonnes gens »"]'::jsonb, 0, 'Elle installe un temps et un lieu indéterminés.', 2),
    ('d402e2ce-e54a-5283-8ab7-0af88a9ff9eb'::uuid, '1085c544-4149-518c-be7a-bf2c1ee89d30'::uuid, 'Quelles sont les cinq étapes du schéma narratif ?', 'mcq', '["Situation initiale, élément perturbateur, péripéties, résolution, situation finale","Introduction, développement, conclusion","Exposition, nœud, dénouement","Prologue, épreuves, épilogue"]'::jsonb, 0, 'C’est la structure de la plupart des contes.', 3),
    ('eaef37fc-8995-52ef-b9b8-86451ad3cd97'::uuid, '1085c544-4149-518c-be7a-bf2c1ee89d30'::uuid, 'Qu’est-ce qu’un adjuvant dans le schéma actanciel ?', 'mcq', '["Un personnage qui aide le héros","Un personnage qui s’oppose au héros","L’objet de la quête","Celui qui envoie le héros"]'::jsonb, 0, 'L’opposant le gêne.', 4),
    ('9fdf0f6e-8b80-597f-af5d-ee800cb8d41e'::uuid, '1085c544-4149-518c-be7a-bf2c1ee89d30'::uuid, 'Qui a publié les Contes en 1697 ?', 'mcq', '["Charles Perrault","Les frères Grimm","Andersen","La Fontaine"]'::jsonb, 0, 'Avec des moralités en vers.', 5),
    ('aeb92432-cb14-59d7-a408-7139f63ceedd'::uuid, '1085c544-4149-518c-be7a-bf2c1ee89d30'::uuid, 'Que font les frères Grimm au XIXe siècle ?', 'mcq', '["Ils collectent les contes populaires allemands","Ils inventent des contes entièrement nouveaux","Ils traduisent Perrault","Ils écrivent des romans d’aventures"]'::jsonb, 0, 'Andersen, lui, invente plus qu’il ne recueille.', 6),
    ('2e7a673f-4075-5e11-9af3-7b996f2dfd8f'::uuid, '1085c544-4149-518c-be7a-bf2c1ee89d30'::uuid, 'Quels nombres reviennent souvent dans les contes ?', 'mcq', '["Trois, sept et cent","Deux, quatre et huit","Cinq, dix et vingt","Six, neuf et douze"]'::jsonb, 0, 'Trois épreuves, sept nains, cent ans de sommeil.', 7),
    ('94cf792d-62b2-5118-b990-23dcfc358764'::uuid, '1085c544-4149-518c-be7a-bf2c1ee89d30'::uuid, 'Le conte merveilleux est une histoire naïve, sans profondeur.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Sous une forme simple, il traite de l’abandon, de la faim, de la mort et de la cruauté.', 8),
    ('d3d22be0-95b8-55f5-883f-2003558c3dd3'::uuid, 'ffd21155-410e-5d3d-bd46-2ceb1711453a'::uuid, 'Que signifie le mot « utopie » ?', 'mcq', '["« En aucun lieu », du grec ou-topos","« Monde parfait »","« Cité idéale »","« Rêve éveillé »"]'::jsonb, 0, 'Thomas More l’a forgé en 1516.', 1),
    ('40de34d6-003f-53a0-9ea1-572793caa045'::uuid, 'ffd21155-410e-5d3d-bd46-2ceb1711453a'::uuid, 'Qui a écrit L’Utopie en 1516 ?', 'mcq', '["Thomas More","Platon","Rabelais","Campanella"]'::jsonb, 0, 'Le livre décrit une île parfaite qui n’existe nulle part.', 2),
    ('38ca8e95-d9a1-5c86-a911-519224d91944'::uuid, 'ffd21155-410e-5d3d-bd46-2ceb1711453a'::uuid, 'Où se situe généralement une utopie ?', 'mcq', '["Dans un lieu isolé, comme une île","Dans une capitale européenne","Dans un futur proche daté","Dans un passé historique précis"]'::jsonb, 0, 'Un voyageur la découvre et sert de guide au lecteur.', 3),
    ('51bdf4cf-9601-5e97-8b9e-3bb73c0dd097'::uuid, 'ffd21155-410e-5d3d-bd46-2ceb1711453a'::uuid, 'Quel est le véritable sujet d’une utopie ?', 'mcq', '["La critique de la société de son auteur","La description d’un pays réel","La prédiction de l’avenir","L’éloge d’un roi"]'::jsonb, 0, 'C’est une argumentation indirecte.', 4),
    ('ba17071b-7786-5ad2-8fc9-43ab2a362ab8'::uuid, 'ffd21155-410e-5d3d-bd46-2ceb1711453a'::uuid, 'Quelle est la règle unique de l’abbaye de Thélème chez Rabelais ?', 'mcq', '["« Fais ce que voudras »","« Prie et travaille »","« Connais-toi toi-même »","« Obéis en silence »"]'::jsonb, 0, 'Une utopie fondée sur la liberté, non sur le règlement.', 5),
    ('253aebb0-3b22-5e39-bfa8-0338e322cdc4'::uuid, 'ffd21155-410e-5d3d-bd46-2ceb1711453a'::uuid, 'Quels traits reviennent dans les sociétés utopiques ?', 'mcq', '["Égalité, travail partagé, éducation pour tous et lois simples","Hiérarchie stricte et privilèges héréditaires","Guerre permanente","Absence de toute organisation"]'::jsonb, 0, 'L’organisation y est rationnelle, parfois jusqu’à l’excès.', 6),
    ('b025aab9-5970-572a-b498-3de227cc860c'::uuid, 'ffd21155-410e-5d3d-bd46-2ceb1711453a'::uuid, 'Pourquoi l’utopie peut-elle basculer en dystopie ?', 'mcq', '["Parce que l’uniformité et l’absence de choix deviennent oppressantes","Parce que les habitants s’ennuient","Parce que le voyageur repart","Parce que le lieu est trop isolé"]'::jsonb, 0, 'Qui décide de ce qui est parfait ?', 7),
    ('1567f73d-1fa5-527d-83b0-39ab3afe2f31'::uuid, 'ffd21155-410e-5d3d-bd46-2ceb1711453a'::uuid, 'Une utopie décrit un pays réel que l’auteur a visité.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Le mot lui-même signifie « en aucun lieu ».', 8),
    ('791f5013-6f1c-548d-8af3-cdceee59b313'::uuid, '45911ff2-16c6-5203-b443-023cdea2830f'::uuid, 'Qu’est-ce qu’une dystopie ?', 'mcq', '["Une société en apparence parfaite mais en réalité totalitaire","Une société idéale et libre","Un récit de voyage imaginaire","Un conte merveilleux moderne"]'::jsonb, 0, 'C’est l’inverse et le prolongement de l’utopie.', 1),
    ('dace686d-4596-5823-8699-ac9b4c5dbfd9'::uuid, '45911ff2-16c6-5203-b443-023cdea2830f'::uuid, 'Quel roman de 1949 met en scène Big Brother et la novlangue ?', 'mcq', '["1984, de George Orwell","Le Meilleur des mondes","Fahrenheit 451","Nous autres"]'::jsonb, 0, 'La police de la pensée y surveille jusqu’aux idées.', 2),
    ('4b313488-50f7-5a8d-ace0-6378ef603e9d'::uuid, '45911ff2-16c6-5203-b443-023cdea2830f'::uuid, 'Qu’est-ce que la novlangue dans 1984 ?', 'mcq', '["Une langue appauvrie pour rendre la révolte impensable","Une langue étrangère imposée","Le langage secret des résistants","Un code informatique"]'::jsonb, 0, 'Réduire le vocabulaire, c’est réduire ce qu’on peut penser.', 3),
    ('56acc374-13a5-566c-b09b-b984dbecc28f'::uuid, '45911ff2-16c6-5203-b443-023cdea2830f'::uuid, 'Comment obtient-on l’obéissance dans Le Meilleur des mondes ?', 'mcq', '["Par le plaisir, le conditionnement et la drogue","Par la peur et la torture","Par la famine","Par l’isolement complet"]'::jsonb, 0, 'Chez Orwell, à l’inverse, on obéit par peur.', 4),
    ('28964416-7a7d-5a14-a750-78f41962171a'::uuid, '45911ff2-16c6-5203-b443-023cdea2830f'::uuid, 'Que font les pompiers dans Fahrenheit 451 ?', 'mcq', '["Ils brûlent les livres","Ils éteignent les incendies","Ils surveillent les frontières","Ils réécrivent les journaux"]'::jsonb, 0, 'Le titre désigne la température d’inflammation du papier.', 5),
    ('a03ff984-3b82-56a4-b82c-0f8eedc48b8c'::uuid, '45911ff2-16c6-5203-b443-023cdea2830f'::uuid, 'Quel roman de 1920 est considéré comme la première dystopie ?', 'mcq', '["Nous autres, de Zamiatine","1984","Le Meilleur des mondes","L’Utopie"]'::jsonb, 0, 'Il a directement inspiré Orwell et Huxley.', 6),
    ('66efb171-b1d8-5008-8b96-73cf339421c1'::uuid, '45911ff2-16c6-5203-b443-023cdea2830f'::uuid, 'Que fait une dystopie à une tendance de son époque ?', 'mcq', '["Elle la pousse à l’extrême pour la rendre visible","Elle la décrit fidèlement","Elle l’ignore volontairement","Elle la situe dans le passé"]'::jsonb, 0, 'C’est un avertissement, pas une prédiction.', 7),
    ('f7f5d8b5-0b3b-5b90-9ae3-f9ae37ac6986'::uuid, '45911ff2-16c6-5203-b443-023cdea2830f'::uuid, 'Dans une dystopie, le héros triomphe généralement du régime.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il prend conscience et résiste, mais échoue le plus souvent : c’est ce qui rend l’avertissement efficace.', 8),
    ('15c7f7c3-e586-5bab-8815-d9d00b121254'::uuid, '2780a9d7-75c9-5deb-9c28-66f323451bee'::uuid, 'Qu’est-ce qu’une chanson de geste ?', 'mcq', '["Un récit en vers célébrant les exploits guerriers, chanté par les jongleurs","Un roman écrit pour être lu","Un poème d’amour courtois","Une pièce de théâtre médiévale"]'::jsonb, 0, 'La Chanson de Roland en est le modèle.', 1),
    ('36498e42-63b9-51fe-b083-55e3e5bc1c74'::uuid, '2780a9d7-75c9-5deb-9c28-66f323451bee'::uuid, 'Quel auteur écrit les grands romans de chevalerie au XIIe siècle ?', 'mcq', '["Chrétien de Troyes","Charles Perrault","François Rabelais","Joachim du Bellay"]'::jsonb, 0, 'Yvain, Perceval, Lancelot.', 2),
    ('f19fc8d6-e483-5a27-a001-7ff23da43cf6'::uuid, '2780a9d7-75c9-5deb-9c28-66f323451bee'::uuid, 'Quelle est la faute de Roland à Roncevaux ?', 'mcq', '["La démesure : il refuse par orgueil de sonner l’olifant à temps","La lâcheté devant l’ennemi","La trahison de Charlemagne","L’abandon de sa dame"]'::jsonb, 0, 'Tous ses hommes en meurent.', 3),
    ('cb5eb7f6-e259-5d4a-a94e-7934b341b2c1'::uuid, '2780a9d7-75c9-5deb-9c28-66f323451bee'::uuid, 'Qu’est-ce que la courtoisie ?', 'mcq', '["Le respect des dames, la maîtrise de soi et l’élégance des manières","La force au combat","La fidélité au seigneur","La générosité envers les pauvres"]'::jsonb, 0, 'La prouesse désigne, elle, le courage guerrier.', 4),
    ('2feb3845-11ab-5d20-901d-7e11896d72ef'::uuid, '2780a9d7-75c9-5deb-9c28-66f323451bee'::uuid, 'Comment appelle-t-on les strophes de La Chanson de Roland ?', 'mcq', '["Des laisses","Des quatrains","Des stances","Des couplets"]'::jsonb, 0, 'De longueur variable, sur une même assonance.', 5),
    ('24b40dfc-2686-5721-aac1-5a34b2c0fa00'::uuid, '2780a9d7-75c9-5deb-9c28-66f323451bee'::uuid, 'Qu’est-ce que l’amour courtois ?', 'mcq', '["Le service d’une dame souvent inaccessible, qui rend le chevalier meilleur","Un mariage arrangé","Un amour partagé et heureux","L’amour du seigneur pour son vassal"]'::jsonb, 0, 'La femme y occupe pour la première fois une position haute.', 6),
    ('3f343110-21fd-55ff-8d07-26cc4310be37'::uuid, '2780a9d7-75c9-5deb-9c28-66f323451bee'::uuid, 'Quelle place tient le merveilleux dans les romans de chevalerie ?', 'mcq', '["Il fait partie du monde sans surprendre personne","Il provoque le doute et la peur","Il est absent du genre","Il est expliqué rationnellement"]'::jsonb, 0, 'Fées, enchanteurs, Graal : comme dans le conte.', 7),
    ('3409e9bb-768c-5d04-bae6-ebe2a92ff455'::uuid, '2780a9d7-75c9-5deb-9c28-66f323451bee'::uuid, 'Le héros médiéval se définit uniquement par sa force au combat.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Loyauté, foi, générosité et courtoisie comptent autant que la prouesse.', 8),
    ('b9765a70-c233-5720-836f-fac6a0c61528'::uuid, 'fbcd89e7-81df-5ce3-b822-9bf9f104bf3e'::uuid, 'Qu’est-ce qu’un héros dans la mythologie grecque ?', 'mcq', '["Un personnage exceptionnel, souvent né d’un dieu et d’une mortelle, mais qui meurt","Un dieu immortel","Un roi élu par le peuple","Un prêtre du temple"]'::jsonb, 0, 'Ni tout à fait dieu, ni tout à fait homme.', 1),
    ('7e4c3d4d-1c5f-5629-933f-c1e70761e559'::uuid, 'fbcd89e7-81df-5ce3-b822-9bf9f104bf3e'::uuid, 'Quel choix Achille fait-il ?', 'mcq', '["Une vie courte et glorieuse plutôt que longue et obscure","Le retour à la maison","La fuite devant Troie","La paix avec les Troyens"]'::jsonb, 0, 'C’est le sens même de sa figure.', 2),
    ('0378e15a-804a-5b78-89a4-46403eed203f'::uuid, 'fbcd89e7-81df-5ce3-b822-9bf9f104bf3e'::uuid, 'Quelle est la force principale d’Ulysse ?', 'mcq', '["La ruse et la ténacité","La force physique","La richesse","La beauté"]'::jsonb, 0, 'Le cheval de Troie et le Cyclope en témoignent.', 3),
    ('32ed2c7e-df33-5c81-87a6-ff631eab16de'::uuid, 'fbcd89e7-81df-5ce3-b822-9bf9f104bf3e'::uuid, 'Combien de travaux Héraclès doit-il accomplir ?', 'mcq', '["Douze","Sept","Dix","Vingt"]'::jsonb, 0, 'En expiation d’une faute.', 4),
    ('2ee2ca4f-5bb8-5f07-a2cb-0eb7697eb3bc'::uuid, 'fbcd89e7-81df-5ce3-b822-9bf9f104bf3e'::uuid, 'Qu’est-ce que l’hybris ?', 'mcq', '["La démesure, l’orgueil excessif, toujours puni par les dieux","Le courage au combat","La fidélité à sa patrie","La ruse"]'::jsonb, 0, 'C’est le défaut central des héros antiques.', 5),
    ('466fc55d-424d-5626-8d71-52a65c8c0f87'::uuid, 'fbcd89e7-81df-5ce3-b822-9bf9f104bf3e'::uuid, 'Qui aide Thésée à sortir du labyrinthe ?', 'mcq', '["Ariane, avec son fil","Athéna","Le Minotaure lui-même","Dédale seul"]'::jsonb, 0, 'Le fil lui permet de retrouver son chemin.', 6),
    ('aeff4032-20df-506f-9f92-0f1c1ddf408e'::uuid, 'fbcd89e7-81df-5ce3-b822-9bf9f104bf3e'::uuid, 'Quel héros romain fonde mythiquement Rome dans l’Énéide ?', 'mcq', '["Énée","Ulysse","Achille","Romulus"]'::jsonb, 0, 'L’épopée est de Virgile.', 7),
    ('c40fd75a-e558-5a78-84b0-f101c37225ea'::uuid, 'fbcd89e7-81df-5ce3-b822-9bf9f104bf3e'::uuid, 'Le héros antique est un modèle moral irréprochable.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il est admirable et faillible à la fois : sa colère ou son orgueil le perdent souvent.', 8),
    ('0d7e9e00-d4fe-5418-81e4-152a827a1a10'::uuid, '3bf16b64-72ca-5501-bd4e-65d53c34a206'::uuid, 'Quelles inventions transforment l’Europe au XIXe siècle ?', 'mcq', '["La machine à vapeur, le charbon, le chemin de fer et l’usine","L’électricité et l’informatique","L’imprimerie et la boussole","Le moteur à explosion seul"]'::jsonb, 0, 'Les campagnes se vident, les villes industrielles enflent.', 1),
    ('a4e801e6-a0ba-5012-a69d-5e41dd1d6215'::uuid, '3bf16b64-72ca-5501-bd4e-65d53c34a206'::uuid, 'Dans quel roman Zola décrit-il la mine comme un monstre dévorant ?', 'mcq', '["Germinal","L’Assommoir","La Bête humaine","Nana"]'::jsonb, 0, 'Publié en 1885.', 2),
    ('4cb7fd46-4601-539d-9e6d-56643554dbd7'::uuid, '3bf16b64-72ca-5501-bd4e-65d53c34a206'::uuid, 'Quel procédé donne à la machine un corps et une volonté ?', 'mcq', '["La personnification","L’ellipse","L’antithèse","La litote"]'::jsonb, 0, 'Elle respire, avale et gronde.', 3),
    ('6633429a-39fb-5d9d-9513-fef7b5efa07f'::uuid, '3bf16b64-72ca-5501-bd4e-65d53c34a206'::uuid, 'Quel renversement caractérise le roman industriel ?', 'mcq', '["La machine devient vivante et l’ouvrier devient une chose","L’ouvrier devient patron","La ville remplace la campagne","Le narrateur devient personnage"]'::jsonb, 0, 'C’est la trouvaille majeure du genre.', 4),
    ('3b1dbafc-b5ce-5f02-b152-6d95bff1b6b6'::uuid, '3bf16b64-72ca-5501-bd4e-65d53c34a206'::uuid, 'Quel roman de Zola fait de la locomotive un personnage ?', 'mcq', '["La Bête humaine","Germinal","Au Bonheur des Dames","L’Assommoir"]'::jsonb, 0, 'La machine y a un nom et un caractère.', 5),
    ('3d6c05b0-8cbf-5ae5-8215-291f870491db'::uuid, '3bf16b64-72ca-5501-bd4e-65d53c34a206'::uuid, 'Que représente la nature pour les romantiques ?', 'mcq', '["Un refuge et un miroir de l’âme","Un obstacle à vaincre","Une ressource à exploiter","Un décor sans importance"]'::jsonb, 0, 'Rousseau, Lamartine et Hugo en font un lieu de consolation.', 6),
    ('126fd66f-a5c1-5f1d-8955-fb8899b4d6d2'::uuid, '3bf16b64-72ca-5501-bd4e-65d53c34a206'::uuid, 'Quel écrivain du XXe siècle oppose la vie paysanne à la modernité ?', 'mcq', '["Giono","Zola","Verne","Hugo"]'::jsonb, 0, 'Il prolonge le regard romantique sur la nature.', 7),
    ('0d3a3bdb-8077-528b-bc50-906003615420'::uuid, '3bf16b64-72ca-5501-bd4e-65d53c34a206'::uuid, 'La littérature du XIXe siècle est unanimement enthousiaste face au progrès.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Deux regards s’opposent : l’enthousiasme de Verne et l’inquiétude de Zola.', 8),
    ('31075908-bd2c-5460-affd-d5e3b1604c3c'::uuid, '600f0b00-3e2f-5b18-8a42-f54d14dfe4e9'::uuid, 'Qu’est-ce qu’un roman d’anticipation ?', 'mcq', '["Un récit situé dans le futur qui extrapole une évolution déjà commencée","Un récit historique","Un conte merveilleux","Un récit de voyage réel"]'::jsonb, 0, 'Il part du présent et demande « et si cela continuait ? ».', 1),
    ('51f3a96a-015a-56b6-8c0d-180d227474c3'::uuid, '600f0b00-3e2f-5b18-8a42-f54d14dfe4e9'::uuid, 'Quel auteur du XIXe siècle pratique une anticipation technique et optimiste ?', 'mcq', '["Jules Verne","H. G. Wells","George Orwell","Ray Bradbury"]'::jsonb, 0, 'Sous-marin, fusée, visiophone y sont documentés.', 2),
    ('57075c51-8925-5829-a054-d4a21ccf4c54'::uuid, '600f0b00-3e2f-5b18-8a42-f54d14dfe4e9'::uuid, 'Quel auteur donne à l’anticipation une dimension sociale et inquiète ?', 'mcq', '["H. G. Wells","Jules Verne","Alexandre Dumas","Charles Perrault"]'::jsonb, 0, 'La Guerre des mondes, L’Île du docteur Moreau.', 3),
    ('5471f191-cd43-55fb-98f9-ca6832d9aef1'::uuid, '600f0b00-3e2f-5b18-8a42-f54d14dfe4e9'::uuid, 'Quel roman de Barjavel paraît en 1943 ?', 'mcq', '["Ravage","1984","Fahrenheit 451","La Machine à explorer le temps"]'::jsonb, 0, 'Il imagine l’effondrement d’une civilisation privée d’électricité.', 4),
    ('1a7099d1-be6b-5e83-a537-dbdd639a5bc3'::uuid, '600f0b00-3e2f-5b18-8a42-f54d14dfe4e9'::uuid, 'Qu’est-ce qu’un néologisme ?', 'mcq', '["Un mot nouveau, inventé pour désigner une réalité nouvelle","Une figure de style","Un retour en arrière","Un type de narrateur"]'::jsonb, 0, 'Il rend le monde futur crédible.', 5),
    ('243bf2c9-fbed-5d77-9e30-9feb7b17c218'::uuid, '600f0b00-3e2f-5b18-8a42-f54d14dfe4e9'::uuid, 'Comment l’auteur explique-t-il son monde futur au lecteur ?', 'mcq', '["Par un personnage guide : le savant ou le nouveau venu","Par des notes de bas de page","Par une préface obligatoire","Sans jamais l’expliquer"]'::jsonb, 0, 'Le procédé évite l’exposé didactique.', 6),
    ('bc07b2b4-e1bd-5e64-8bc0-dc9645ad625f'::uuid, '600f0b00-3e2f-5b18-8a42-f54d14dfe4e9'::uuid, 'Que faut-il chercher en lisant un roman d’anticipation ?', 'mcq', '["La tendance actuelle poussée à l’extrême et ce que l’auteur redoute","La date exacte de l’action","Le nombre de personnages","La longueur des chapitres"]'::jsonb, 0, 'Le futur décrit parle du présent où il a été écrit.', 7),
    ('88a363dc-dcfd-588b-9e90-0dc8fb3f6d56'::uuid, '600f0b00-3e2f-5b18-8a42-f54d14dfe4e9'::uuid, 'Un roman d’anticipation qui se trompe dans ses prédictions a échoué.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Prédire n’était pas le but : il s’agissait d’interroger le présent.', 8),
    ('a21d94ce-4706-55a1-83cc-5dfc3a92aa85'::uuid, '33aa3d61-4613-571d-a372-388488850abb'::uuid, 'Qu’est-ce que l’hortus conclusus médiéval ?', 'mcq', '["Un jardin clos de murs, utile et symbolique","Une forêt sacrée","Un parc royal ouvert","Un potager collectif"]'::jsonb, 0, 'Il évoque le paradis retrouvé.', 1),
    ('d382959d-7d02-523b-b917-7e162ef0b492'::uuid, '33aa3d61-4613-571d-a372-388488850abb'::uuid, 'Que représente la forêt dans la littérature médiévale ?', 'mcq', '["Le lieu du danger, de l’épreuve et du merveilleux","Un espace agricole","Un lieu de repos","Une frontière politique"]'::jsonb, 0, 'Les chevaliers y rencontrent fées, ermites et monstres.', 2),
    ('f409478b-dfda-5941-b9cc-9c73fbbe87a2'::uuid, '33aa3d61-4613-571d-a372-388488850abb'::uuid, 'Comment la nature est-elle peinte dans les enluminures médiévales ?', 'mcq', '["Sans profondeur, en aplats sur fond d’or","Avec une perspective rigoureuse","En noir et blanc","De façon photographique"]'::jsonb, 0, 'Elle est un signe, pas un paysage.', 3),
    ('ab47caba-631d-52f5-97b0-1a9c38d7da07'::uuid, '33aa3d61-4613-571d-a372-388488850abb'::uuid, 'Quelle invention de la Renaissance fait entrer la profondeur en peinture ?', 'mcq', '["La perspective","Le clair-obscur seul","La peinture à l’huile","Le fond d’or"]'::jsonb, 0, 'Le paysage devient un espace.', 4),
    ('1ca1df0e-f6a3-51f8-92f3-1484b512ef83'::uuid, '33aa3d61-4613-571d-a372-388488850abb'::uuid, 'Qui dessine le jardin de Versailles ?', 'mcq', '["Le Nôtre","Léonard de Vinci","Descartes","Ronsard"]'::jsonb, 0, 'Axes de symétrie, perspectives infinies, arbres taillés.', 5),
    ('3b381014-9569-5627-a8b1-24449e27d81b'::uuid, '33aa3d61-4613-571d-a372-388488850abb'::uuid, 'Que démontre le jardin à la française ?', 'mcq', '["La maîtrise et le pouvoir du roi sur la nature","Le respect de la nature sauvage","La pauvreté des moyens techniques","La liberté des jardiniers"]'::jsonb, 0, 'Ce que le roi fait aux arbres, il le fait au royaume.', 6),
    ('3f07fa44-42a7-5649-bd77-dc51f4ab3bb6'::uuid, '33aa3d61-4613-571d-a372-388488850abb'::uuid, 'Quelle formule de Descartes résume le programme du XVIIe siècle ?', 'mcq', '["Se rendre « comme maître et possesseur de la nature »","« Fais ce que voudras »","« Connais-toi toi-même »","« Cultivons notre jardin »"]'::jsonb, 0, 'La nature y devient objet de maîtrise.', 7),
    ('bf5d3570-e47e-53a4-a61c-6c1e42412006'::uuid, '33aa3d61-4613-571d-a372-388488850abb'::uuid, 'Le jardin à l’anglaise du XVIIIe siècle prolonge le style de Versailles.', 'true_false', '["Vrai","Faux"]'::jsonb, 1, 'Il en prend le contre-pied : allées sinueuses, faux désordre, nature rêvée.', 8)
  ) AS v(id, quiz_id, question, kind, options, correct_index, explanation, position)
-- Le quiz doit exister : si le NOT EXISTS ci-dessus a écarté un quiz (une
-- leçon en avait déjà un), ses questions ne partent pas dans le vide.
 WHERE EXISTS (SELECT 1 FROM public.quizzes qz WHERE qz.id = v.quiz_id)
ON CONFLICT (id) DO NOTHING;

-- 5. Sonde finale ----------------------------------------------------------
DO $$
DECLARE
  n_vides integer;
  n_chap  integer;
BEGIN
  SELECT count(*) INTO n_chap FROM public.chapters c
   JOIN public.subjects s ON s.id = c.subject_id
   WHERE s.slug IN ('francais');
  SELECT count(*) INTO n_vides FROM public.subjects s
   WHERE s.slug IN ('francais')
     AND NOT EXISTS (SELECT 1 FROM public.chapters c WHERE c.subject_id = s.id);
  IF n_vides > 0 THEN
    RAISE EXCEPTION 'Migration 307 incomplète : % matiere(s) encore sans chapitre', n_vides;
  END IF;
  RAISE NOTICE 'Migration 307 OK : % chapitres sur les matieres visees.', n_chap;
END $$;
