// FICHIER GÉNÉRÉ par scripts/cartes-exercices.ts — ne pas éditer à la main.
// Les codes des régions / pays, fleuves, massifs et déserts de chaque fond.

import type { Fond } from './projections'

export const CODES_FONDS: Record<Fond, { zones: Record<string, string>; fleuves: string[]; reliefs: string[]; deserts: string[] }> = {
 "france": {
  "zones": {
   "ARA": "Auvergne-Rhône-Alpes",
   "BFC": "Bourgogne-Franche-Comté",
   "BRE": "Bretagne",
   "COR": "Corse",
   "CVL": "Centre-Val de Loire",
   "GES": "Grand Est",
   "HDF": "Hauts-de-France",
   "IDF": "Île-de-France",
   "NAQ": "Nouvelle-Aquitaine",
   "NOR": "Normandie",
   "OCC": "Occitanie",
   "PAC": "Provence-Alpes-Côte d'Azur",
   "PDL": "Pays de la Loire"
  },
  "fleuves": [
   "seine",
   "loire",
   "garonne",
   "rhone",
   "rhin",
   "dordogne",
   "marne",
   "vienne",
   "tarn",
   "durance",
   "moselle",
   "meuse",
   "saone",
   "lot",
   "allier",
   "adour",
   "charente"
  ],
  "reliefs": [
   "alpes",
   "pyrenees",
   "massif-central",
   "jura",
   "vosges",
   "ardennes"
  ],
  "deserts": []
 },
 "monde": {
  "zones": {
   "AFG": "Afghanistan",
   "AGO": "Angola",
   "ALB": "Albanie",
   "ARE": "Émirats arabes unis",
   "ARG": "Argentine",
   "ARM": "Arménie",
   "ATF": "Terres australes et antarctiques françaises",
   "AUS": "Australie",
   "AUT": "Autriche",
   "AZE": "Azerbaïdjan",
   "BDI": "Burundi",
   "BEL": "Belgique",
   "BEN": "Bénin",
   "BFA": "Burkina Faso",
   "BGD": "Bangladesh",
   "BGR": "Bulgarie",
   "BHS": "Bahamas",
   "BIH": "Bosnie-Herzégovine",
   "BLR": "Biélorussie",
   "BLZ": "Belize",
   "BOL": "Bolivie",
   "BRA": "Brésil",
   "BRN": "Brunei",
   "BTN": "Bhoutan",
   "BWA": "Botswana",
   "CAF": "République centrafricaine",
   "CAN": "Canada",
   "CHE": "Suisse",
   "CHL": "Chili",
   "CHN": "République populaire de Chine",
   "CIV": "Côte d'Ivoire",
   "CMR": "Cameroun",
   "COD": "République démocratique du Congo",
   "COG": "République du Congo",
   "COL": "Colombie",
   "CRI": "Costa Rica",
   "CUB": "Cuba",
   "CYN": "Chypre du Nord",
   "CYP": "Chypre",
   "CZE": "Tchéquie",
   "DEU": "Allemagne",
   "DJI": "Djibouti",
   "DNK": "Danemark",
   "DOM": "République dominicaine",
   "DZA": "Algérie",
   "ECU": "Équateur",
   "EGY": "Égypte",
   "ERI": "Érythrée",
   "ESP": "Espagne",
   "EST": "Estonie",
   "ETH": "Éthiopie",
   "FIN": "Finlande",
   "FJI": "Fidji",
   "FLK": "îles Malouines",
   "FRA": "France",
   "GAB": "Gabon",
   "GBR": "Royaume-Uni",
   "GEO": "Géorgie",
   "GHA": "Ghana",
   "GIN": "Guinée",
   "GMB": "Gambie",
   "GNB": "Guinée-Bissau",
   "GNQ": "Guinée équatoriale",
   "GRC": "Grèce",
   "GRL": "Groenland",
   "GTM": "Guatemala",
   "GUY": "Guyana",
   "HND": "Honduras",
   "HRV": "Croatie",
   "HTI": "Haïti",
   "HUN": "Hongrie",
   "IDN": "Indonésie",
   "IND": "Inde",
   "IRL": "Irlande",
   "IRN": "Iran",
   "IRQ": "Irak",
   "ISL": "Islande",
   "ISR": "Israël",
   "ITA": "Italie",
   "JAM": "Jamaïque",
   "JOR": "Jordanie",
   "JPN": "Japon",
   "KAZ": "Kazakhstan",
   "KEN": "Kenya",
   "KGZ": "Kirghizistan",
   "KHM": "Cambodge",
   "KOR": "Corée du Sud",
   "KOS": "Kosovo",
   "KWT": "Koweït",
   "LAO": "Laos",
   "LBN": "Liban",
   "LBR": "Liberia",
   "LBY": "Libye",
   "LKA": "Sri Lanka",
   "LSO": "Lesotho",
   "LTU": "Lituanie",
   "LVA": "Lettonie",
   "MAR": "Maroc",
   "MDA": "Moldavie",
   "MDG": "Madagascar",
   "MEX": "Mexique",
   "MKD": "Macédoine du Nord",
   "MLI": "Mali",
   "MMR": "Birmanie",
   "MNE": "Monténégro",
   "MNG": "Mongolie",
   "MOZ": "Mozambique",
   "MRT": "Mauritanie",
   "MWI": "Malawi",
   "MYS": "Malaisie",
   "NAM": "Namibie",
   "NCL": "Nouvelle-Calédonie",
   "NER": "Niger",
   "NGA": "Nigeria",
   "NIC": "Nicaragua",
   "NLD": "Pays-Bas",
   "NOR": "Norvège",
   "NPL": "Népal",
   "NZL": "Nouvelle-Zélande",
   "OMN": "Oman",
   "PAK": "Pakistan",
   "PAN": "Panama",
   "PER": "Pérou",
   "PHL": "Philippines",
   "PNG": "Papouasie-Nouvelle-Guinée",
   "POL": "Pologne",
   "PRI": "Porto Rico",
   "PRK": "Corée du Nord",
   "PRT": "Portugal",
   "PRY": "Paraguay",
   "PSX": "Palestine",
   "QAT": "Qatar",
   "ROU": "Roumanie",
   "RUS": "Russie",
   "RWA": "Rwanda",
   "SAH": "Sahara occidental",
   "SAU": "Arabie saoudite",
   "SDN": "Soudan",
   "SDS": "Soudan du Sud",
   "SEN": "Sénégal",
   "SLB": "Îles Salomon",
   "SLE": "Sierra Leone",
   "SLV": "Salvador",
   "SOL": "Somaliland",
   "SOM": "Somalie",
   "SRB": "Serbie",
   "SUR": "Suriname",
   "SVK": "Slovaquie",
   "SVN": "Slovénie",
   "SWE": "Suède",
   "SWZ": "Eswatini",
   "SYR": "Syrie",
   "TCD": "Tchad",
   "TGO": "Togo",
   "THA": "Thaïlande",
   "TJK": "Tadjikistan",
   "TKM": "Turkménistan",
   "TLS": "Timor oriental",
   "TTO": "Trinité-et-Tobago",
   "TUN": "Tunisie",
   "TUR": "Turquie",
   "TWN": "Taïwan",
   "TZA": "Tanzanie",
   "UGA": "Ouganda",
   "UKR": "Ukraine",
   "URY": "Uruguay",
   "USA": "États-Unis",
   "UZB": "Ouzbékistan",
   "VEN": "Venezuela",
   "VNM": "Viêt Nam",
   "VUT": "Vanuatu",
   "YEM": "Yémen",
   "ZAF": "Afrique du Sud",
   "ZMB": "Zambie",
   "ZWE": "Zimbabwe"
  },
  "fleuves": [
   "danube",
   "volga",
   "nil",
   "amazone",
   "mississippi",
   "yangzi",
   "huang-he",
   "gange",
   "indus",
   "niger",
   "congo",
   "mekong",
   "zambeze",
   "saint-laurent",
   "parana",
   "ob",
   "ienissei",
   "lena",
   "brahmaputra"
  ],
  "reliefs": [
   "alpes",
   "caucase",
   "oural",
   "atlas",
   "himalaya",
   "andes",
   "rocheuses",
   "appalaches",
   "tibet"
  ],
  "deserts": [
   "sahara",
   "gobi",
   "kalahari",
   "namib",
   "atacama",
   "arabie",
   "syrie",
   "thar",
   "australie"
  ]
 },
 "mediterranee": {
  "zones": {
   "ALB": "Albanie",
   "AND": "Andorre",
   "ARE": "Émirats arabes unis",
   "ARM": "Arménie",
   "AUT": "Autriche",
   "AZE": "Azerbaïdjan",
   "BEL": "Belgique",
   "BGR": "Bulgarie",
   "BHR": "Bahreïn",
   "BIH": "Bosnie-Herzégovine",
   "BLR": "Biélorussie",
   "CHE": "Suisse",
   "CYN": "Chypre du Nord",
   "CYP": "Chypre",
   "CZE": "Tchéquie",
   "DEU": "Allemagne",
   "DZA": "Algérie",
   "EGY": "Égypte",
   "ESP": "Espagne",
   "FRA": "France",
   "GBR": "Royaume-Uni",
   "GEO": "Géorgie",
   "GRC": "Grèce",
   "HRV": "Croatie",
   "HUN": "Hongrie",
   "IRN": "Iran",
   "IRQ": "Irak",
   "ISR": "Israël",
   "ITA": "Italie",
   "JOR": "Jordanie",
   "KAZ": "Kazakhstan",
   "KOS": "Kosovo",
   "KWT": "Koweït",
   "LBN": "Liban",
   "LBY": "Libye",
   "LUX": "Luxembourg",
   "MAR": "Maroc",
   "MDA": "Moldavie",
   "MKD": "Macédoine du Nord",
   "MLI": "Mali",
   "MLT": "Malte",
   "MNE": "Monténégro",
   "MRT": "Mauritanie",
   "NER": "Niger",
   "NLD": "Pays-Bas",
   "POL": "Pologne",
   "PRT": "Portugal",
   "PSX": "Palestine",
   "QAT": "Qatar",
   "ROU": "Roumanie",
   "RUS": "Russie",
   "SAH": "Sahara occidental",
   "SAU": "Arabie saoudite",
   "SDN": "Soudan",
   "SRB": "Serbie",
   "SVK": "Slovaquie",
   "SVN": "Slovénie",
   "SYR": "Syrie",
   "TCD": "Tchad",
   "TKM": "Turkménistan",
   "TUN": "Tunisie",
   "TUR": "Turquie",
   "UKR": "Ukraine",
   "UZB": "Ouzbékistan",
   "YEM": "Yémen"
  },
  "fleuves": [
   "seine",
   "loire",
   "garonne",
   "rhone",
   "rhin",
   "po",
   "tibre",
   "ebre",
   "tage",
   "douro",
   "guadalquivir",
   "danube",
   "nil",
   "tigre",
   "euphrate",
   "jourdain"
  ],
  "reliefs": [
   "alpes",
   "pyrenees",
   "apennins",
   "carpates",
   "balkans",
   "alpes-dinariques",
   "pinde",
   "caucase",
   "atlas",
   "taurus",
   "zagros",
   "liban"
  ],
  "deserts": [
   "sahara",
   "arabie",
   "syrie"
  ]
 },
 "europe": {
  "zones": {
   "ALB": "Albanie",
   "ALD": "Åland",
   "AND": "Andorre",
   "ARM": "Arménie",
   "AUT": "Autriche",
   "AZE": "Azerbaïdjan",
   "BEL": "Belgique",
   "BGR": "Bulgarie",
   "BIH": "Bosnie-Herzégovine",
   "BLR": "Biélorussie",
   "CHE": "Suisse",
   "CYN": "Chypre du Nord",
   "CYP": "Chypre",
   "CZE": "Tchéquie",
   "DEU": "Allemagne",
   "DNK": "Danemark",
   "DZA": "Algérie",
   "EGY": "Égypte",
   "ESP": "Espagne",
   "EST": "Estonie",
   "FIN": "Finlande",
   "FRA": "France",
   "FRO": "îles Féroé",
   "GBR": "Royaume-Uni",
   "GEO": "Géorgie",
   "GRC": "Grèce",
   "GRL": "Groenland",
   "HRV": "Croatie",
   "HUN": "Hongrie",
   "IMN": "île de Man",
   "IRL": "Irlande",
   "IRN": "Iran",
   "IRQ": "Irak",
   "ISL": "Islande",
   "ISR": "Israël",
   "ITA": "Italie",
   "JOR": "Jordanie",
   "KAZ": "Kazakhstan",
   "KOS": "Kosovo",
   "LBN": "Liban",
   "LBY": "Libye",
   "LTU": "Lituanie",
   "LUX": "Luxembourg",
   "LVA": "Lettonie",
   "MAR": "Maroc",
   "MDA": "Moldavie",
   "MKD": "Macédoine du Nord",
   "MLT": "Malte",
   "MNE": "Monténégro",
   "NLD": "Pays-Bas",
   "NOR": "Norvège",
   "POL": "Pologne",
   "PRT": "Portugal",
   "PSX": "Palestine",
   "ROU": "Roumanie",
   "RUS": "Russie",
   "SAU": "Arabie saoudite",
   "SRB": "Serbie",
   "SVK": "Slovaquie",
   "SVN": "Slovénie",
   "SWE": "Suède",
   "SYR": "Syrie",
   "TUN": "Tunisie",
   "TUR": "Turquie",
   "UKR": "Ukraine"
  },
  "fleuves": [
   "seine",
   "loire",
   "garonne",
   "rhone",
   "rhin",
   "meuse",
   "po",
   "ebre",
   "tage",
   "douro",
   "danube",
   "elbe",
   "oder",
   "vistule",
   "tamise",
   "dniepr",
   "volga"
  ],
  "reliefs": [
   "alpes",
   "pyrenees",
   "massif-central",
   "apennins",
   "carpates",
   "balkans",
   "alpes-dinariques",
   "caucase",
   "alpes-scandinaves"
  ],
  "deserts": []
 }
}
